<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
?>
 <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css" />
 <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css" />
 <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>
   <!--  <link href="../assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />-->
  <!--  <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />-->
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />

<?php
$menu_id="2";
$sub_menu_id="1";
include("include/new_menu.php");
$query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1'";
$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
$row_fetched=mysql_fetch_array($result);
$tarh_name = $row_fetched["tarh_title_farsi"];
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                               در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h3 class="page-title">
                            <small id="page-title">عنوان طرح : <? echo $tarh_name;?></small>
                            
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="navigator-home" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="send-edit" href="tarh_list.phtml">
                                    ارسال/ويرايش طرح
                                </a>
                                <i id="fa-angle2" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="hazine_mosaferat" href="hazine_mosaferat.phtml?cod_tarh=<?php echo $cod_tarh; ?>">
                                    هزينه مسافرت
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
               <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <div id="caption-grid" class="caption">
                                    <i class="fa fa-magic"></i>ويزارد
                                </div>
                                                               
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <?php  $active_id="10"; include("include/wizard.php");?>
                                    <div class="col-md-9 col-sm-12 col-xs-12">
                                       <div class="portlet box blue">
											<div class="portlet-title">
												<div id="hazine_mosaferat_frm" class="caption">
													<i class="fa fa-reorder"></i>هزينه مسافرت
												</div>
												<div class="tools">
													<a href="javascript:;" class="collapse">
													</a>
													<a href="#portlet-config" data-toggle="modal"
													class="fa fa-info-circle" title="راهنما"
													style="color: white">
													</a>
												</div>
											</div>
											<div class="portlet-body form-horizontal">
											
												<!-- BEGIN FORM-->
												<form name="hazine_mosaferat_form" id="hazine_mosaferat_form" action="hazine_mosaferat_sabt.php?action=sabt" method="POST" class="form-horizontal">
												<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
												<input id="cod_hazine_safar" name="cod_hazine_safar" type="hidden" class="form-control" >
												
													<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue" >
							                                        <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 id="sabt_hazine_mosaferat" class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                             ثبت هزينه مسافرت
							                                        </h4>
							                                     </div>
							                                    <div class="modal-body">
																		<div class="form-body">
																          <div id="alert_danger" class="alert alert-danger display-hide">
																			<button class="close" data-close="alert"></button>
																			پر کردن فيلدهاي ستاره دار اجباري مي باشد.
																	      </div>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="target_label" class="control-label col-md-5">مقصد
																							<span class="required">
																							 *
																							</span>
																						</label>
																						<div class="col-md-7">
																							<div class="input-icon right">
																										<i class="fa"></i>
																								<input id="target" name="target" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="1">
																								
																							</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="dafe_safar_label" class="control-label col-md-5">دفعات مسافرت در مدت اجراي طرح
																							<span class="required">
																							 *
																							</span>
																						</label>
																						<div class="col-md-7">
																							<div class="input-icon right">
																										<i class="fa"></i>
																								<input name="dafe_safar" id="dafe_safar" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="2">
																							</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			<!--/row-->
																			<div class="row">
																			
																			<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="vasile_label" class="control-label col-md-5">نوع وسيله
																							<span class="required">
																							 *
																							</span>
																						</label>
																						<div class="col-md-7">
																							<div class="input-icon right">
																										<i class="fa"></i>
																								<input name="vasile" id="vasile" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="3">
																							</div>
																						</div>
																					</div>
																				</div>
																				<!--/span--> 
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="persons_cnt_label" class="control-label col-md-5">تعداد افراد
																							<span class="required">
																							 *
																							</span>
																						</label>
																						<div class="col-md-7">
																							<div class="input-icon right">
																										<i class="fa"></i>
																								<input name="persons_cnt" id="persons_cnt" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="4">
																							</div>
																						</div>
																					</div>
																				</div>
																				
																			</div>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="hazine_label" class="control-label col-md-5"> هزينه کل
																							<span class="required">
																							 *
																							</span>
																						</label>
																						<div class="col-md-7">
																							<div class="input-icon right">
																										<i class="fa"></i>
																								<input name="hazine" id="hazine" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="5">
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			
																		
																			
																		</div>
																		
																	<!-- END FORM-->
																								                                     
							                                    </div>
							                                    <div class="modal-footer">
							                                        <button id="save" type="submit"  class="btn green input-sm  input-small" tabindex="6">ذخيره</button>
																	<button id="cancel" type="button" class="btn red input-sm  input-small" data-dismiss="modal"><i class="fa fa-times" tabindex="7"></i>انصراف</button>
							                                    </div>
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      
							                      <div class="modal fade " id="delete"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																	
																		<div id="sure" class="form-body">
																			<h4 class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
																		</div>
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9">
																						<button id="yes" type="submit"  class="btn green">بلي</button>
																						<button id="no" type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>خير</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																	
																	<!-- END FORM-->
							                                    </div>
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
						                     </form>
						                        <a id="sabt_safar" class="btn blue btn-sm pull-left" data-toggle="modal" href="#basic">
						                           ثبت هزينه مسافرت
						                        </a>
												<!-- END FORM-->
												<table class="table table-striped table-bordered table-hover" id="sample_1">
				                                    <thead>
				                                        <tr>
				                                            <th id="th1">
				                                                مقصد
				                                            </th>
				                                            <th id="th2">
				                                                دفعات مسافرت در مدت اجراي طرح
				                                            </th>
				                                            <th id="th3" class="">
				                                                نوع وسيله
				                                            </th>
				                                            <th id="th4" class="">
				                                                تعداد افراد
				                                            </th>
				                                            <th id="th5" class="">
				                                            	هزينه
				                                            </th>
				                                            <th id="th6" class="">
				                                                ويرايش
				                                            </th>
				                                            <th id="th7" class="">
				                                                حذف
				                                            </th>
				                                            <th id="th8" class="hidden">
				                                                حذف
				                                            </th>
				                                        </tr>
				                                    </thead>
				                                   
			                                	</table>
											</div>
										</div>
                                    </div>

                                </div>
                            </div>
                            
                        </div>

                    </div>
                </div>
                <!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->
<script>
if(language=="en")
	{ debugger;
	document.getElementById("page-title").textContent="Research Title :";
	document.getElementById("navigator-home").textContent="Home";
	document.getElementById("send-edit").textContent="Send / Edit Research";
	document.getElementById("hazine_mosaferat_frm").innerHTML="<i  class='fa fa-reorder'></i>Travel expenses";
	document.getElementById("hazine_mosaferat").textContent="Travel expenses ";
	document.getElementById("sabt_hazine_mosaferat").innerHTML="<i class='fa fa-file-o' ></i>Registration Travel expenses";
	document.getElementById("target_label").innerHTML="Destination <span class='required'>*</span>";
	document.getElementById("dafe_safar_label").innerHTML="Number of trips during the project <span class='required'>*</span>";
	document.getElementById("vasile_label").innerHTML="Transport mode <span class='required'>*</span>";
	document.getElementById("persons_cnt_label").innerHTML="Number of people travelling <span class='required'>*</span>";
	document.getElementById("hazine_label").innerHTML="Cost<span class='required'>*</span>";
	document.getElementById("fa-angle").className="fa fa-angle-right";
	document.getElementById("fa-angle2").className="fa fa-angle-right";
	document.getElementById("save").textContent="Save";
	document.getElementById("cancel").textContent="Cancel";
	document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
	document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
	document.getElementById("th1").textContent="Destinations";
	document.getElementById("th2").textContent="Number of trips during the project";
	document.getElementById("th3").textContent="Transport mode ";
	document.getElementById("th4").textContent="Number of people travelling";
	document.getElementById("th5").textContent="Cost";
	document.getElementById("th6").textContent="Edit";
	document.getElementById("th7").textContent="Delete";
	document.getElementById("th8").textContent="Delete";
	document.getElementById("sabt_safar").textContent="Registration equipment and instruments";
	document.getElementById("alert_danger").innerHTML="<button class='close' data-close='alert'></button>You have some form errors. Please check below.";
	document.getElementById("sure").innerHTML="<h4 class='form-section'>Are you sure you want to delete this item</h4>";
	document.getElementById("yes").textContent="Yes";
	document.getElementById("no").textContent="No";
	
	
	
	}
</script>

<?php 
include("../include/primary_js.phtml");
?>

	
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
	   // initiate layout and plugins
	 //  App.init();
	   //FormSamples.init();
	   //$(".").select2();
		 $('body').addClass(" page-sidebar-closed");
	});
	</script>
	<!-- END JAVASCRIPTS -->
	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
	$("#hazine_mosaferat_form").submit(function(e)
			{
		var form2 = $('#hazine_mosaferat_form');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);
        if(language=="en"){
       	 form2.validate({
             errorElement: 'span', //default input error message container
             errorClass: 'help-block', // default input error message class
             focusInvalid: false, // do not focus the last invalid input
             ignore: "",
             rules:{
         					target:{
 	  	                 		required:true
 	  	                  },
 		  	                dafe_safar:{
 		  	                	number: true,
 	  	                  		required:true
 	  			          },
 		  			        vasile:{
 	  		                  	required:true
 	  				      },
 		  				    persons_cnt:{
 		  				    	number: true,
 	  		                 	required:true
 	  				      },
 		  				    hazine:{
 		  				    	number: true,
 	  		                  	required:true
 	  				      }	  				    
 	  	              },
 		  	      

             invalidHandler: function (event, validator) { //display error alert on form submit              
 	                    success2.hide();
 	                    error2.show();
 	                    App.scrollTo(error2, -200);
             },

             errorPlacement: function (error, element) { // render error placement for each input type
                 var icon = $(element).parent('.input-icon').children('i');
                 icon.removeClass('fa-check').addClass("fa-warning");  
                 icon.attr("data-original-title", error.text()).tooltip();
             },

             highlight: function (element) { // hightlight error inputs
                 $(element)
                     .closest('.form-group').addClass('has-error'); // set error class to the control group   
             },

             unhighlight: function (element) { // revert the change done by hightlight
                 
             },

             success: function (label, element) {
                 var icon = $(element).parent('.input-icon').children('i');
                 $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                 icon.removeClass("fa-warning").addClass("fa-check");
             },

             submitHandler: function (form) {
                 success2.show();
                 error2.hide();
             }
         });
            }else{
        form2.validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block', // default input error message class
            focusInvalid: false, // do not focus the last invalid input
            ignore: "",
            rules:{
        					target:{
	  	                 		required:true
	  	                  },
		  	                dafe_safar:{
		  	                	number: true,
	  	                  		required:true
	  			          },
		  			        vasile:{
	  		                  	required:true
	  				      },
		  				    persons_cnt:{
		  				    	number: true,
	  		                 	required:true
	  				      },
		  				    hazine:{
		  				    	number: true,
	  		                  	required:true
	  				      }	  				    
	  	              },
		  	            messages:{
		  	            			target:{
			  	                  		required:"پر کردن اين فيلد الزامي مي باشد"
			  	            	  },
				  	            	dafe_safar:{
				  	            		number: "لطفا عدد وارد نماييد.",
			  	                 		required:"پر کردن اين فيلد الزامي مي باشد"
			  	    		          },
				  	    		    vasile:{
			  	                  		required:"پر کردن اين فيلد الزامي مي باشد"
			  	    		          },
				  	    		    persons_cnt:{
				  	    		       	number: "لطفا عدد وارد نماييد.",
					  	         		required:"پر کردن اين فيلد الزامي مي باشد"
					  	    		  },
						  	    	hazine:{
						  	    		number: "لطفا عدد وارد نماييد.",
								 		required:"پر کردن اين فيلد الزامي مي باشد"
								  	  }
			      		          
			  	              },
	  	              

            invalidHandler: function (event, validator) { //display error alert on form submit              
	                    success2.hide();
	                    error2.show();
	                    App.scrollTo(error2, -200);
            },

            errorPlacement: function (error, element) { // render error placement for each input type
                var icon = $(element).parent('.input-icon').children('i');
                icon.removeClass('fa-check').addClass("fa-warning");  
                icon.attr("data-original-title", error.text()).tooltip();
            },

            highlight: function (element) { // hightlight error inputs
                $(element)
                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
            },

            unhighlight: function (element) { // revert the change done by hightlight
                
            },

            success: function (label, element) {
                var icon = $(element).parent('.input-icon').children('i');
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                icon.removeClass("fa-warning").addClass("fa-check");
            },

            submitHandler: function (form) {
                success2.show();
                error2.hide();
            }
        });
            }
		//dicision for edit or add
		debugger;
				var formURL;
				var postData = $(this).serializeArray();
				if(jadvZar_IsNew=="insert")		
					 formURL = $(this).attr("action");
				else if(jadvZar_IsNew=="edit")		
					formURL="hazine_mosaferat_sabt.php?action=edit";
				else if(jadvZar_IsNew=="delete")		
					formURL="hazine_mosaferat_sabt.php?action=delete";
				
				if($("#hazine_mosaferat_form").valid() || (jadvZar_IsNew=="delete"))
				{
				    $(".green").attr("disabled","disabled");
				$.ajax(
				{
					url : formURL,
					type: "POST",
					data : postData,
					success:function(data, textStatus, jqXHR) 
					{
					if(data=="exist"){
						$("#hazine_mosaferat_i").switchClass( "fa-times", "fa-check", 1000, "easeInOutQuad" );
						}
					else if(data=="notexist"){
						
						$("#hazine_mosaferat_i").switchClass( "fa-check", "fa-times", 1000, "easeInOutQuad" );
						}
					//alert(data);
					jadvZar_IsNew="insert";
					$("#basic").modal('hide');
					$("#delete").modal('hide');
					$("#hazine_mosaferat_form")[0].reset();

					//Begin of reset form validation 
				    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
				    $(".input-icon .fa-check").switchClass("fa-check","fa");
				    $(".alert-danger").hide();
				    $('.form-group').removeClass('has-error');
				    $('.form-group').removeClass('has-success');
				    //End of reset form validation
				    
				    	//debugger;
				            var uniSelect = $("#uniSelect");
				            var temp = $("#temp");
				            uniSelect.appendTo(temp);
				    		
				            $("#sample_1").DataTable().destroy();
							show_dataTable();
				        
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
					}
				}).always( $(".green").removeAttr("disabled","disabled"));
			}
			    e.preventDefault();	//STOP default action
			  //  $("#jadval_zarayeb_form").submit(); //SUBMIT FORM
			});
				
			
	 </script>
	 <script>
	 if(language=="en"){
		 	buttonText="Visibel Columns";
		 	sButtonText="Print";
		 	sButtonText2="Save";
		 	info="view _START_ to _END_ from _TOTAL_ items";
		 	sLengthMenu="View Content _MENU_";
		 	sZeroRecords="Not Found";
		 	sInfoEmpty="Empty";
		 	sInfoFiltered="(Filtered From _MAX_ Items)";
		 	sSearch="Search";
		 	sFirst="First";
		 	sPrevious="Previous";
		 	sNext="Next";
		 	sLast="Last";
		 	
		 	
		 }
		 else
		 {
		 	buttonText="ستون هاي قابل نمايش";
		 	sButtonText="چاپ";
		 	sButtonText2="ذخيره";
		 	info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
		 	sLengthMenu="نمايش محتويات _MENU_";
		 	sZeroRecords="موردي يافت نشد";
		 	sInfoEmpty="تهي";
		 	sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
		 	sSearch="جستجو";
		 	sFirst="ابتدا";
		 	sPrevious="قبلي";
		 	sNext="بعدي";
		 	sLast="انتها";
		 	
		 }
	 $(document).ready(function() {
		    var detailRows = [];
		show_dataTable();

	 });
	
	function show_dataTable()
	{
				    var dt;				
					
		    dt = $('#sample_1').DataTable({
				"dom": 'CT<"clearfix">lfrtip',
		        "tableTools": {
		            "sRowSelect": "os",
					 "aButtons": [
		                
						{
		                    "sExtends": "print",
		                    "sButtonText": sButtonText
		                },
		                
		                {
		                    "sExtends":    "collection",
		                    "sButtonText": sButtonText,
		                    "aButtons":    [ 
												"csv", 
												"xls"
											]
		                }
		            ],
		            
					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
		        },
		        "fnInitComplete": function(oSettings, json) {
					
					fixControlPosition();
					
	                },
		        "fnDrawCallback": function(oSettings) {
		            var trs = $("#sample_1 tr");
		            for (var i = 1; i < trs.length; i++) {

		                var rowId = ($(trs[i]).attr('id'));
		                $("#" + rowId + " td:last-child").trigger('click');

		            }
		            $('.edit_buttun').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                //var idx = $.inArray(tr.attr('id'), detailRows);
		                $('#target')[0].value = row.data().target;
		                $('#dafe_safar')[0].value = row.data().dafe_safar;
		                $('#vasile')[0].value = row.data().vasile;
		                $('#cod_hazine_safar')[0].value = row.data().cod_hazine_safar;
		                $('#persons_cnt')[0].value = row.data().persons_cnt;
		                $('#hazine')[0].value = row.data().hazine;
		               
		                
		              //  $('#naghsh_var')[0].value=row.data().naghsh_var;
		                jadvZar_IsNew="edit";
		                $("#basic").modal('show');
//		                if (row.child.isShown()) {
//		                    tr.removeClass('details');
//		                    row.child.hide();
//
//		                    // Remove from the 'open' array
//		                    detailRows.splice(idx, 1);
//		                } else {
//		                    tr.addClass('details');
//		                    row.child(format(row.data())).show();
//
//		                    // Add to the 'open' array
//		                    if (idx === -1) {
//		                        detailRows.push(tr.attr('id'));
//		                    }
//		                }
		            });
		            $('.delete_buttun').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                $('#cod_hazine_safar')[0].value = row.data().cod_hazine_safar;
		                
		                jadvZar_IsNew="delete";
		                $("#delete").modal('show');
	                
		            });
		        },
		        "colVis": {
		           "buttonText": buttonText,
		        	exclude:[7]
		       },
		        
                "paging": true,
                'bPaginate': true,
                "pagingType": "full_numbers",
                "processing": true,
                "serverSide": true,
                "bDestroy": true,
                "bAutoWidth": false,
                "language": {
            		
                    "sProcessing": "<img src='image/ajax-loader-white.gif'>",
                    "sLengthMenu": sLengthMenu,
                    "sZeroRecords": sZeroRecords,
                    "info": info,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sInfoPostFix": "",
                    "sSearch": sSearch,
                    "sUrl": "",
                    "oPaginate" : {
                        "sFirst": sFirst,
                        "sPrevious": sPrevious,
                        "sNext": sNext,
                        "sLast": sLast
                    }
                },
		        "sAjaxSource": "hazine_mosaferat_sabt.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>&action=hazine_mosaferat_list" ,
		        "aoColumns": [
		            { "data": "target" },
				    { "data": "dafe_safar" },
	                { "data": "vasile" },
	                { "data": "persons_cnt" },
	                { "data": "hazine" },
			        { "data": "edit", "bSortable": false },
				    { "data": "delete", "bSortable": false},
				    { "data": "cod_hazine_safar","sClass": "hidden"}
		        ]

		    });
	}
	
		var jadvZar_IsNew="insert";

		$('#basic').on('hidden.bs.modal', function () {
		   // debugger;
		    jadvZar_IsNew="insert";
		    $("#hazine_mosaferat_form")[0].reset();
		    //Begin of reset form validation 
		    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
		    $(".input-icon .fa-check").switchClass("fa-check","fa");
		    $(".alert-danger").hide();
		    $('.form-group').removeClass('has-error');
		    $('.form-group').removeClass('has-success');
		  //End of reset form validation
		});
		$('#delete').on('hidden.bs.modal', function () {
			   // debugger;
			    jadvZar_IsNew="insert";
			    $("#hazine_mosaferat_form")[0].reset();
			});
			 
	 </script>

<?php
footer_forms($admin,$seed);
?>

