<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
?>
 <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css" />
 <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css" />
 <link rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>
   <!--  <link href="../assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />-->
  <!--  <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />-->
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />

<?php
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">Modal title</h4>
                            </div>
                            <div class="modal-body">
                                Widget settings form goes here
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn blue">Save changes</button>
                                <button type="button" class="btn default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h3 class="page-title">
                            <small>جزئيات اين فرم / صفحه</small>
                            عنوان صفحه
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a href="index.html">
                                    خانه
                                </a>
                                <i class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a href="#">
                                    فرم ها
                                </a>
                                <i class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a href="#">
                                    فرم پژوهشيار
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
               <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-magic"></i>ويزارد
                                </div>
                                <div class="actions">
                                    <a href="#" class="btn green">
                                        قبلي
                                        <i class="fa fa-arrow-right"></i>
                                    </a>
                                    <a href="#" class="btn green">
                                        <i class="fa fa-arrow-left"></i> بعدي
                                    </a>
                                </div>
                               
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <?php  $active_id="1"; include("include/wizard.php");?>
                                    <div class="col-md-9 col-sm-9 col-xs-9">
                                       <div class="portlet box green">
											<div class="portlet-title">
												<div class="caption">
													<i class="fa fa-reorder"></i>فرم نمونه
												</div>
												<div class="tools">
													<a href="javascript:;" class="collapse">
													</a>
													<a href="#portlet-config" data-toggle="modal" class="config">
													</a>
													<a href="javascript:;" class="reload">
													</a>
													<a href="javascript:;" class="remove">
													</a>
												</div>
											</div>
											<div class="portlet-body form-horizontal">
											
												<!-- BEGIN FORM-->
												<form name="jadval_zarayeb_form" id="jadval_zarayeb_form" action="jadval_zarayeb_sabt.php?action=sabt" method="POST" class="form-horizontal">
												<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
												<input id="cod_zarib" name="cod_zarib" type="hidden" class="form-control" >
												
													<div class="modal fade " id="basic"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																																			<div class="form-body">
																			<h3 class="form-section">مشخصات طرح</h3>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">عنوان متغير</label>
																						<div class="col-md-9">
																							<input id="name_var" name="name_var" type="text" class="form-control" placeholder="" >
																							<span class="help-block">
																								 راهنماي يک خطي
																							</span>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">نقش متغير</label>
																						<div class="col-md-9">
																							<select name="naghsh_var" id="naghsh_var" class="form-control" data-placeholder="يک دسته بندي انتخاب کنيد" tabindex="1">
																								<option value="-1">انتخاب کنيد</option>
																							    <option value="0">مستقل</option>
																							    <option value="1">وابسته</option>
																							        
																							</select>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			<!--/row-->
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">نوع متغير</label>
																						<div class="col-md-9">
																							<select name="var_type" id="var_type" class="form-control"  data-placeholder="يک دسته بندي انتخاب کنيد" tabindex="1">
																								<option value="-1">انتخاب کنيد</option>
																							    <option value="0">کيفي / رتبه اي</option>
																							    <option value="1">کيفي / اسمي</option>
																							    <option value="2">کمي / پيوسته</option>
																							    <option value="3">کمي /گسسته</option>     
																							</select>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">تعريف علمي عملي</label>
																						<div class="col-md-9">
																							<input name="taarif_elmi_amali" id="taarif_elmi_amali" type="text" class="form-control" placeholder="">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">نحوه اندازه گيري</label>
																						<div class="col-md-9">
																							<input name="ravesh_andaze" id="ravesh_andaze" type="text" class="form-control" placeholder="">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">مقياس</label>
																						<div class="col-md-9">
																							<input name="meghyas" id="meghyas" type="text" class="form-control" placeholder="">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			
																				
																
																			
																		</div>
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9">
																						<button type="submit"  class="btn green">ذخيره</button>
																						<button type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>انصراف</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																	
																	<!-- END FORM-->
							                                    </div><!-- modal_body -->
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      
							                      <div class="modal fade " id="delete"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																	
																		<div class="form-body">
																			<h4 class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
																		</div>
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9">
																						<button type="submit"  class="btn green">بلي</button>
																						<button type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>خير</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																	</form>
																	<!-- END FORM-->
							                                    </div>
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
						                     <?php echo "<a class=\"btn blue\" data-toggle=\"modal\" href=\"jadval_zarayeb.phtml?admin=$admin&seed=$seed&action=test#basic\">";?>   
						                            ثبت متغير جديد
						                        </a>
						                        <div id="simple-msg"></div>
												<!-- END FORM-->
												<table class="table table-striped table-bordered table-hover" id="sample_1">
				                                    <thead>
				                                        <tr>
				                                            <th>
				                                                عنوان متغير
				                                            </th>
				                                            <th>
				                                                نقش متغير
				                                            </th>
				                                            <th class="hidden-xs">
				                                                نوع متغير
				                                            </th>
				                                            <th class="hidden-xs">
				                                                تعريف علمي عملي
				                                            </th>
				                                            <th class="hidden-xs">
				                                                نحوه اندازه گيري
				                                            </th>
				                                            <th class="hidden-xs">
				                                                مقياس
				                                            </th>
				                                            <th class="hidden-xs">
				                                                ويرايش
				                                            </th>
				                                            <th class="hidden-xs">
				                                                حذف
				                                            </th>
				                                            <th class="hidden">
				                                                حذف
				                                            </th>
				                                        </tr>
				                                    </thead>
				                                   
			                                	</table>
											</div>
										</div>
                                    </div>

                                </div>
                            </div>
                            
                        </div>

                    </div>
                </div>
                <!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->


<?php 
include("../include/primary_js.phtml");
?>

	
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
	   // initiate layout and plugins
	 //  App.init();
	   //FormSamples.init();
	   //$(".").select2();
	   
	});
	</script>
	<!-- END JAVASCRIPTS -->
	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn green btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
	$("#jadval_zarayeb_form").submit(function(e)
			{
		//dicision for edit or add
		debugger;
				var formURL;
				var postData = $(this).serializeArray();
				if(jadvZar_IsNew=="insert")		
					 formURL = $(this).attr("action");
				else if(jadvZar_IsNew=="edit")		
					formURL="jadval_zarayeb_sabt.php?action=edit";
				else if(jadvZar_IsNew=="delete")		
					formURL="jadval_zarayeb_sabt.php?action=delete";
				
				$.ajax(
				{
					url : formURL,
					type: "POST",
					data : postData,
					success:function(data, textStatus, jqXHR) 
					{
					//alert(data);
					jadvZar_IsNew="insert";
					$("#basic").modal('hide');
					$("#delete").modal('hide');
					$("#jadval_zarayeb_form")[0].reset();
				    	//debugger;
				            var uniSelect = $("#uniSelect");
				            var temp = $("#temp");
				            uniSelect.appendTo(temp);
				    		
				            $("#sample_1").DataTable().destroy();
				    		
				            dt = $('#sample_1').DataTable({
				    				"dom": 'T<"clear">lfrtip',
				    				"tableTools": {
				    					"sRowSelect": "os",
				    					 "aButtons": [
				    						 {
				    							"sExtends": "copy",
				    							"sButtonText": "کپي"
				    						},
				    						{
				    							"sExtends": "print",
				    							"sButtonText": "چاپ"
				    						},
				    						
				    						{
				    							"sExtends":    "collection",
				    							"sButtonText": "ذخيره",
				    							"aButtons":    [ 
				    												"csv", 
				    												"xls"
				    											]
				    						}
				    					],
				    					
				    					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
				    				},
				    				 "fnInitComplete": function(oSettings, json) {
										
										fixControlPosition();
										
						                },
				                "fnDrawCallback": function(oSettings) {
				                    var trs = $("#example tr");
				                    for (var i = 1; i < trs.length; i++) {
				                        var rowId = ($(trs[i]).attr('id'));
				                        debugger;
				                        $("#" + rowId + " td:last-child").trigger('click');

				                    }
				                    $('.edit_btn').on('click', function() {
						                debugger;
						                var tr = $(this).closest('tr');
						                var row = dt.row(tr);
						                //var idx = $.inArray(tr.attr('id'), detailRows);
						                $('#name_var')[0].value = row.data().name_var;
						                $('#cod_zarib')[0].value = row.data().cod_zarib;
						                $('#taarif_elmi_amali')[0].value = row.data().taarif_elmi_amali;
						                $('#ravesh_andaze')[0].value = row.data().ravesh_andaze;
						                $('#meghyas')[0].value = row.data().meghyas;
						                if(row.data().naghsh_var=='وابسته'){
						                	$('#naghsh_var option[value="1"]').attr("selected", "selected");
						                }else if(row.data().naghsh_var=='مستقل'){
						                	$('#naghsh_var option[value="0"]').attr("selected", "selected");
						                }
						                else
						                {
						                	$('#naghsh_var option[value="-1"]').attr("selected", "selected") ;
						                }
						                if(row.data().var_type=='کيفي / رتبه اي'){
						                	$('#var_type option[value="0"]').attr("selected", "selected");
						                }else if(row.data().var_type=='کيفي / اسمي'){
						                	$('#var_type option[value="1"]').attr("selected", "selected");
						                }
						                else if(row.data().var_type=='کمي / پيوسته'){
						                	$('#var_type option[value="2"]').attr("selected", "selected");
						                }
						                else if(row.data().var_type=='کمي /گسسته'){
						                	$('#var_type option[value="3"]').attr("selected", "selected");
						                }
						                else
						                	$('#var_type option[value="-1"]').attr("selected", "selected");
						              //  $('#naghsh_var')[0].value=row.data().naghsh_var;
						                jadvZar_IsNew="edit";
						                $("#basic").modal('show');
//						                if (row.child.isShown()) {
//						                    tr.removeClass('details');
//						                    row.child.hide();
				//
//						                    // Remove from the 'open' array
//						                    detailRows.splice(idx, 1);
//						                } else {
//						                    tr.addClass('details');
//						                    row.child(format(row.data())).show();
				//
//						                    // Add to the 'open' array
//						                    if (idx === -1) {
//						                        detailRows.push(tr.attr('id'));
//						                    }
//						                }
						            });
				                    $('.delete_btn').on('click', function() {
						                debugger;
						                var tr = $(this).closest('tr');
						                var row = dt.row(tr);
						                $('#cod_zarib')[0].value = row.data().cod_zarib;
						                
						                jadvZar_IsNew="delete";
						                $("#delete").modal('show');
					                
						            });
				                },
				                "sScrollY": 400,
				                "bScrollCollapse": true,
				                "paging": true,
				                'bPaginate': true,
				                "pagingType": "full_numbers",
				                "processing": true,
				                "serverSide": true,
				                "bDestroy": true,
				                "oLanguage": {
				        		
				                    "sProcessing": "<img src='image/ajax-loader-white.gif'>",
				                    "sLengthMenu": "نمايش محتويات _MENU_",
				                    "sZeroRecords": "موردي يافت نشد",
				                    "sinfo": "نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد",
				                    "sInfoEmpty": "تهي",
				                    "sInfoFiltered": "(فيلتر شده از مجموع _MAX_ مورد)",
				                    "sInfoPostFix": "",
				                    "sSearch": "جستجو:",
				                    "sUrl": "",
				                    "oPaginate" : {
				                        "sFirst": "ابتدا",
				                        "sPrevious": "قبلي",
				                        "sNext": "بعدي",
				                        "sLast": "انتها"
				                    }
				                },
				                "sAjaxSource": "jadval_zarayeb_list.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>" ,
				                "aoColumns": [
				                    { "data": "name_var" },
				                    { "data": "naghsh_var" },
				                    { "data": "var_type" },
				                    { "data": "taarif_elmi_amali" },
				                    { "data": "ravesh_andaze" },
				                    { "data": "meghyas" },
				                    { "data": "edit" },
				                    { "data": "delete"},
				                    { "data": "cod_zarib","sClass": "hidden"}
				                ]
				            });


				        
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
					}
				});
			    e.preventDefault();	//STOP default action
			  //  $("#jadval_zarayeb_form").submit(); //SUBMIT FORM
			});
				
			
	 </script>
	 <script>
	 $(document).ready(function() {
		    var detailRows = [];
		    var dt;
//				$(".dataTables_scrollBody").niceScroll({
//						styler: "fb",
//						cursorcolor: "#f2956d",
//						cursorwidth: "6",
//						cursorborderradius: "10px",
//						background: "#007785",
//						spacebarenabled: !1,
//						cursorborder: ""
//					});
					$(".dataTables_scrollHeadInner").width('100%');
					$(".dataTables_scrollHeadInner table").width('100%');
					$('#daneshkade').select2();
		    dt = $('#sample_1').DataTable({
				"dom": 'T<"clear">lfrtip',
		        "tableTools": {
		            "sRowSelect": "os",
					 "aButtons": [
		                 {
		                    "sExtends": "copy",
		                    "sButtonText": "کپي"
		                },
						{
		                    "sExtends": "print",
		                    "sButtonText": "چاپ"
		                },
		                
		                {
		                    "sExtends":    "collection",
		                    "sButtonText": "ذخيره",
		                    "aButtons":    [ 
												"csv", 
												"xls"
											]
		                }
		            ],
		            
					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
		        },
		        "fnInitComplete": function(oSettings, json) {
					
					fixControlPosition();
					
	                },
		        "fnDrawCallback": function(oSettings) {
		            var trs = $("#example tr");
		            for (var i = 1; i < trs.length; i++) {

		                var rowId = ($(trs[i]).attr('id'));
		                $("#" + rowId + " td:last-child").trigger('click');

		            }
		            $('.edit_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                //var idx = $.inArray(tr.attr('id'), detailRows);
		                $('#name_var')[0].value = row.data().name_var;
		                $('#cod_zarib')[0].value = row.data().cod_zarib;
		                $('#taarif_elmi_amali')[0].value = row.data().taarif_elmi_amali;
		                $('#ravesh_andaze')[0].value = row.data().ravesh_andaze;
		                $('#meghyas')[0].value = row.data().meghyas;
		                if(row.data().naghsh_var=='وابسته'){
		                	$('#naghsh_var option[value="1"]').attr("selected", "selected");
		                }else if(row.data().naghsh_var=='مستقل'){
		                	$('#naghsh_var option[value="0"]').attr("selected", "selected");
		                }
		                else
		                {
		                	$('#naghsh_var option[value="-1"]').attr("selected", "selected") ;
		                }
		                if(row.data().var_type=='کيفي / رتبه اي'){
		                	$('#var_type option[value="0"]').attr("selected", "selected");
		                }else if(row.data().var_type=='کيفي / اسمي'){
		                	$('#var_type option[value="1"]').attr("selected", "selected");
		                }
		                else if(row.data().var_type=='کمي / پيوسته'){
		                	$('#var_type option[value="2"]').attr("selected", "selected");
		                }
		                else if(row.data().var_type=='کمي /گسسته'){
		                	$('#var_type option[value="3"]').attr("selected", "selected");
		                }
		                else
		                	$('#var_type option[value="-1"]').attr("selected", "selected");
		              //  $('#naghsh_var')[0].value=row.data().naghsh_var;
		                jadvZar_IsNew="edit";
		                $("#basic").modal('show');
//		                if (row.child.isShown()) {
//		                    tr.removeClass('details');
//		                    row.child.hide();
//
//		                    // Remove from the 'open' array
//		                    detailRows.splice(idx, 1);
//		                } else {
//		                    tr.addClass('details');
//		                    row.child(format(row.data())).show();
//
//		                    // Add to the 'open' array
//		                    if (idx === -1) {
//		                        detailRows.push(tr.attr('id'));
//		                    }
//		                }
		            });
		            $('.delete_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                $('#cod_zarib')[0].value = row.data().cod_zarib;
		                
		                jadvZar_IsNew="delete";
		                $("#delete").modal('show');
	                
		            });
		        },
		        "sScrollY": 400,
		        "bScrollCollapse": true,
		        "paging": true,
		        'bPaginate': true,
		        "pagingType": "full_numbers",
		        "processing": true,
		        "serverSide": true,
		        "bDestroy": true,
		        "oLanguage": {
				
		            "sProcessing": "<img src='image/ajax-loader-white.gif'>",
		            "sLengthMenu": "نمايش محتويات _MENU_",
		            "sZeroRecords": "موردي يافت نشد",
		            "sinfo": "نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد",
		            "sInfoEmpty": "تهي",
		            "sInfoFiltered": "(فيلتر شده از مجموع _MAX_ مورد)",
		            "sInfoPostFix": "",
		            "sSearch": "جستجو:",
		            "sUrl": "",
		            "oPaginate" : {
		                "sFirst": "ابتدا",
		                "sPrevious": "قبلي",
		                "sNext": "بعدي",
		                "sLast": "انتها"
		            }
		        },
		        "sAjaxSource": "jadval_zarayeb_list.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>" ,
		        "aoColumns": [
		            { "data": "name_var" },
				    { "data": "naghsh_var" },
	                { "data": "var_type" },
	                { "data": "taarif_elmi_amali" },
			        { "data": "ravesh_andaze" },
					{ "data": "meghyas" },
                    { "data": "edit" },
				    { "data": "delete"},
				    { "data": "cod_zarib","sClass": "hidden"}
		        ]

		    });

	 });

		var jadvZar_IsNew="insert";

		$('#basic').on('hidden.bs.modal', function () {
		   // debugger;
		    jadvZar_IsNew=true;
		    $("#jadval_zarayeb_form")[0].reset();
		});
			 
	 </script>

<?php
footer_forms($admin,$seed);
?>

