<script>
document.addEventListener("DOMNodeInserted",function(element){
	//debugger;
if(element.relatedNode.tagName=="BODY")
	element.relatedNode.classList.add("page-sidebar-closed");

});
</script>
<?

include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
?>
 <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css" />
 <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css" />
 <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>
   <!--  <link href="../assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />-->
  <!--  <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />-->
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />


<?php
$menu_id="2";
$sub_menu_id="1";
include("include/new_menu.php");
$query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1'";
$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
$row_fetched=mysql_fetch_array($result);
$tarh_name = $row_fetched["tarh_title_farsi"];
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                                در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h3 class="page-title">
                            <small id="page-title">عنوان طرح : <? echo $tarh_name;?></small>
                            
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="breadcrumb_home" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle-left1" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb_send" href="tarh_list.phtml">
                                   ارسال/ويرايش طرح
                                </a>
                                <i id="fa-angle-left2" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb_title" href="jadval_zarayeb.phtml?cod_tarh=<?php echo $cod_tarh; ?>">
                                    جدول متغيرها
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
               <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <div id="wizard" class="caption">
                                    <i class="fa fa-magic"></i>ويزارد
                                </div>

                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <?php  $active_id="5"; include("include/wizard.php");?>
                                    <div class="col-md-9 col-sm-12 col-xs-12">
                                       <div class="portlet box blue">
											<div class="portlet-title">
												<div id="portlet_caption" class="caption">
													<i class="fa fa-reorder"></i>جدول متغيرها
												</div>
												<div class="tools">
													<a href="javascript:;" class="collapse">
													</a>
													<a id="portlet_config" href="#portlet-config" data-toggle="modal"
													class="fa fa-info-circle" title="راهنما"
													style="color: white">
													</a>
												</div>
											</div>
											<div class="portlet-body form-horizontal">
											
												<!-- BEGIN FORM-->
												<form name="jadval_zarayeb_form" id="jadval_zarayeb_form" action="jadval_zarayeb_sabt.php?action=sabt" method="POST" class="form-horizontal">
												<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
												<input id="cod_zarib" name="cod_zarib" type="hidden" class="form-control" >
												
													<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog ">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
							                                        <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                      	  <h4 id="modal_title" class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                            عنوان
							                                        </h4>
							                                     </div>
							                                    <div class="modal-body">
							                                  		 
																		<div class="form-body">
																       <div id="alert_danger" class="alert alert-danger display-hide">
																			<button class="close" data-close="alert"></button>
																			پر کردن فيلدهاي ستاره دار اجباري مي باشد.
																	      </div>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb1" class="control-label col-md-5">عنوان متغير
																						<span class="required">
																							 *
																							</span></label>
																						<div class="col-md-7">
																						<div class="input-icon right">
																										<i class="fa"></i>
																							<input id="name_var" name="name_var" type="text" class="form-control input-sm  input-small" placeholder="" tabindex="1">
																						</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb2" class="control-label col-md-5">نقش متغير
																						<span class="required">
																							 *
																							</span></label>
																						<div id="role_variable_label" class="col-md-7">
																						<div class="input-icon right">
																										<i class="fa"></i>
																							<select name="naghsh_var" id="naghsh_var" class="form-control input-sm  input-small" data-placeholder="يک دسته بندي انتخاب کنيد" tabindex="2">
																								<option value="">انتخاب کنيد</option>
																							    <option value="0">مستقل</option>
																							    <option value="1">وابسته</option>
																							        
																							</select>
																						</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			<!--/row-->
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb3" class="control-label col-md-5">نوع متغير
																						<span class="required">
																							 *
																							</span></label>
																						<div id="type_variable_label" class="col-md-7">
																							<div class="input-icon right">
																											<i class="fa"></i>
																								<select name="var_type" id="var_type" class="form-control input-sm  input-small"  data-placeholder="يک دسته بندي انتخاب کنيد" tabindex="3">
																									<option value="">انتخاب کنيد</option>
																								    <option value="0">کيفي / رتبه اي</option>
																								    <option value="1">کيفي / اسمي</option>
																								    <option value="2">کمي / پيوسته</option>
																								    <option value="3">کمي /گسسته</option>     
																								</select>
																							</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb4" class="control-label col-md-5">تعريف علمي-عملي</label>
																						<div class="col-md-7">
																							<input name="taarif_elmi_amali" id="taarif_elmi_amali" type="text" class="form-control input-sm input-small" placeholder="" tabindex="4">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
																			<div class="row">
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb5" class="control-label col-md-5">نحوه اندازه گيري</label>
																						<div class="col-md-7">
																							<input name="ravesh_andaze" id="ravesh_andaze" type="text" class="form-control input-sm input-small" placeholder="" tabindex="5">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				<div class="col-md-6">
																					<div class="form-group">
																						<label id="lb6" class="control-label col-md-5">مقياس</label>
																						<div class="col-md-7">
																							<input name="meghyas" id="meghyas" type="text" class="form-control input-sm input-small" placeholder="" tabindex="6">
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																			</div>
	
																		
																			
																		</div>										                                     
							                                    </div>
							                                     <div class="modal-footer">
							                                        <button id="btn1" type="submit"  class="btn green input-sm input-small" tabindex="7">ذخيره</button>
																	<button id="btn2" type="button" class="btn red input-sm input-small" data-dismiss="modal" tabindex="8"><i class="fa fa-times"></i>انصراف</button>
							                                    </div>
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      
							                      <div class="modal fade " id="delete"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																	
																		<div class="form-body">
																			<h4 id="delete_message" class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
																		</div>
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9">
																						<button id="btn3" type="submit"  class="btn green">بلي</button>
																						<button id="btn4" type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>خير</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																	
																	<!-- END FORM-->
							                                    </div>
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
						                     </form>
						                        <a id="new_variable" class="btn blue btn-sm pull-left" data-toggle="modal" href="#basic">
						                           ثبت متغير جديد
						                        </a>
												<!-- END FORM-->
												<div class="table-responsive">
													<table class="table table-striped table-bordered table-hover" id="sample_1">
					                                    <thead>
					                                        <tr>
					                                            <th id="th1">
					                                                عنوان متغير
					                                            </th>
					                                            <th id="th2">
					                                                نقش متغير
					                                            </th>
					                                            <th id="th3">
					                                                نوع متغير
					                                            </th>
					                                            <th id="th4">
					                                                تعريف علمي عملي
					                                            </th>
					                                            <th id="th5">
					                                                نحوه اندازه گيري
					                                            </th>
					                                            <th id="th6">
					                                                مقياس
					                                            </th>
					                                            <th id="th7">
					                                                ويرايش
					                                            </th>
					                                            <th id="th8">
					                                                حذف
					                                            </th>
					                                            <th id="th9" class="hidden">
					                                                حذف
					                                            </th>
					                                        </tr>
					                                    </thead>
					                                   
				                                	</table>
			                                	</div>
											</div>
										</div>
                                    </div>

                                </div>
                            </div>
                            
                        </div>

                    </div>
                </div>
                <!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->
<script>
if(language=="en"){																										    
debugger;
document.getElementById("page-title").textContent="Title of Research";
document.getElementById("breadcrumb_home").textContent="Home";
document.getElementById("breadcrumb_send").textContent="Send/Edit of Research";
document.getElementById("breadcrumb_title").textContent="Table of Variable";
document.getElementById("wizard").innerHTML="<i class='fa fa-magic'></i>Wizard";
document.getElementById("portlet_caption").innerHTML="<i class='fa fa-reorder'></i>Table of Variable";
document.getElementById("portlet_config").setAttribute("title","Information");
document.getElementById("fa-angle-left1").setAttribute("class","fa fa-angle-right");
document.getElementById("fa-angle-left2").setAttribute("class","fa fa-angle-right");
document.getElementById("modal_title").textContent="Title";
document.getElementById("lb1").innerHTML="variable title <span class='required'>*</span>";
document.getElementById("lb2").innerHTML="variable type <span class='required'>*</span>";
document.getElementById("lb3").innerHTML="measurement way <span class='required'>*</span>";
document.getElementById("type_variable_label").innerHTML="<select name='var_type' id='var_type' class='form-control input-sm  input-small'  data-placeholder='يک دسته بندي انتخاب کنيد' tabindex='3'><option value='-1'>Choose way of measurement</option><option value='0'>Qualitative/Rank</option><option value='1'>Qualitative/Nominal</option><option value='2'>Quantitative/Continuous</option><option value='3'>Quantitative/Discrete</option></select>";
document.getElementById("lb4").textContent="variable role";
document.getElementById("role_variable_label").innerHTML="<select name='naghsh_var' id='naghsh_var' class='form-control input-sm  input-small' data-placeholder='يک دسته بندي انتخاب کنيد' tabindex='2'><option value='-1'>Choose type of variable</option><option value='0'>Independent</option><option value='1'>dependent</option></select>";
document.getElementById("lb5").textContent="science-practical definition";
document.getElementById("lb6").textContent="scale";
document.getElementById("btn1").textContent="Save";
document.getElementById("btn2").textContent="Cancel";
document.getElementById("delete_message").textContent="Are you sure to remove this item?";
document.getElementById("btn3").textContent="Yes";
document.getElementById("btn4").innerHTML="<i class='fa fa-times'></i>No";
document.getElementById("new_variable").textContent="Entery new variable";
document.getElementById("th1").textContent="variable title";
document.getElementById("th2").textContent="variable role";
document.getElementById("th3").textContent="variable type";
document.getElementById("th4").textContent="science-practical definition";
document.getElementById("th5").textContent="way of measurement";
document.getElementById("th6").textContent="scale";
document.getElementById("th7").textContent="Edit";
document.getElementById("th8").textContent="Delete";
document.getElementById("th9").textContent="Delete";
document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
document.getElementById("alert_danger").innerHTML="<button class='close' data-close='alert'></button>You have some form errors. Please check below.";
}
</script>


<?php 
include("../include/primary_js.phtml");
?>


	
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
	   // initiate layout and plugins
	 //  App.init();
	   //FormSamples.init();
	   //$(".").select2();
		 //$('body').addClass(" page-sidebar-closed");
		
		// alert(language);
		$('table').css("font-size","13px");
	});

	
	</script>
	<!-- END JAVASCRIPTS -->

	 <script>
		var buttonText;
		var sButtonText;
		var info;
		//var	language="en";
		if(language=="en"){
			buttonText="Visibel Columns";
			sButtonText="Print";
			sButtonText2="Save";
			info="view _START_ to _END_ from _TOTAL_ items";
			sLengthMenu="View Content _MENU_";
			sZeroRecords="Not Found";
			sInfoEmpty="Empty";
			sInfoFiltered="(Filtered From _MAX_ Items)";
			sSearch="Search";
			sFirst="First";
			sPrevious="Previous";
			sNext="Next";
			sLast="Last";
			
			
		}
		else
		{
			buttonText="ستون هاي قابل نمايش";
			sButtonText="چاپ";
			sButtonText2="ذخيره";
			info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
			sLengthMenu="نمايش محتويات _MENU_";
			sZeroRecords="موردي يافت نشد";
			sInfoEmpty="تهي";
			sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
			sSearch="جستجو";
			sFirst="ابتدا";
			sPrevious="قبلي";
			sNext="بعدي";
			sLast="انتها";
			
		}
	 //language = "en";
	 $(document).ready(function() {
		    var detailRows = [];
		    var dt;				
		    dt = $('#sample_1').DataTable({
				"dom": 'CT<"clearfix">lfrtip',
		        "tableTools": {
		            "sRowSelect": "os",
					 "aButtons": [
		                 
						{
							
		                    "sExtends": "print",
		                    "sButtonText": sButtonText
		                },
		                
		                {
		                    "sExtends":    "collection",
		                    "sButtonText": sButtonText2,
		                    "aButtons":    [ 
												"csv", 
												"xls"
											]
		                }
		            ],
		            
					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
		        },
		        "fnInitComplete": function(oSettings, json) {
					
					fixControlPosition();
					
	                },
		        "fnDrawCallback": function(oSettings) {
		            var trs = $("#sample_1 tr");
		            for (var i = 1; i < trs.length; i++) {

		                var rowId = ($(trs[i]).attr('id'));
		                $("#" + rowId + " td:last-child").trigger('click');

		            }
		            $('.edit_buttun').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		    		    //Begin of reset form validation 
		    		    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
		    		    $(".input-icon .fa-check").switchClass("fa-check","fa");
		    		    $(".alert-danger").hide();
		    		    $('.form-group').removeClass('has-error');
		    		    $('.form-group').removeClass('has-success');
		    		  //End of reset form validation
		                //var idx = $.inArray(tr.attr('id'), detailRows);
		                $('#name_var')[0].value = row.data().name_var;
		                $('#cod_zarib')[0].value = row.data().cod_zarib;
		                $('#taarif_elmi_amali')[0].value = row.data().taarif_elmi_amali;
		                $('#ravesh_andaze')[0].value = row.data().ravesh_andaze;
		                $('#meghyas')[0].value = row.data().meghyas;

		                if(language=="en"){	
			                debugger;
			                
			                if(row.data().naghsh_var=='dependent'){
			                	$('#naghsh_var option[value="1"]').attr("selected", "selected");
			                }else if(row.data().naghsh_var=='Independent'){
			                	$('#naghsh_var option[value="0"]').attr("selected", "selected");
			                }
			                else
			                {
			                	$('#naghsh_var option[value="-1"]').attr("selected", "selected") ;
			                }
		                }
		                else{
		                	if(row.data().naghsh_var=='وابسته'){
			                	$('#naghsh_var option[value="1"]').attr("selected", "selected");
			                }else if(row.data().naghsh_var=='مستقل'){
			                	$('#naghsh_var option[value="0"]').attr("selected", "selected");
			                }
			                else
			                {
			                	$('#naghsh_var option[value="-1"]').attr("selected", "selected") ;
			                }
			             }

		                if(language=="en"){
		                	if(row.data().var_type=='Qualitative/Rank'){
			                	$('#var_type option[value="0"]').attr("selected", "selected");
			                }else if(row.data().var_type=='Qualitative/Nominal'){
			                	$('#var_type option[value="1"]').attr("selected", "selected");
			                }
			                else if(row.data().var_type=='Quantitative/Continuous'){
			                	$('#var_type option[value="2"]').attr("selected", "selected");
			                }
			                else if(row.data().var_type=='Quantitative/Discrete'){
			                	$('#var_type option[value="3"]').attr("selected", "selected");
			                }
			                else
			                	$('#var_type option[value="-1"]').attr("selected", "selected");
			                }else{

				                if(row.data().var_type=='کيفي / رتبه اي'){
				                	$('#var_type option[value="0"]').attr("selected", "selected");
				                }else if(row.data().var_type=='کيفي / اسمي'){
				                	$('#var_type option[value="1"]').attr("selected", "selected");
				                }
				                else if(row.data().var_type=='کمي / پيوسته'){
				                	$('#var_type option[value="2"]').attr("selected", "selected");
				                }
				                else if(row.data().var_type=='کمي /گسسته'){
				                	$('#var_type option[value="3"]').attr("selected", "selected");
				                }
				                else
				                	$('#var_type option[value="-1"]').attr("selected", "selected");
				            }
			            
		              //  $('#naghsh_var')[0].value=row.data().naghsh_var;
		                jadvZar_IsNew="edit";
		                $("#basic").modal('show');
//		                if (row.child.isShown()) {
//		                    tr.removeClass('details');
//		                    row.child.hide();
//
//		                    // Remove from the 'open' array
//		                    detailRows.splice(idx, 1);
//		                } else {
//		                    tr.addClass('details');
//		                    row.child(format(row.data())).show();
//
//		                    // Add to the 'open' array
//		                    if (idx === -1) {
//		                        detailRows.push(tr.attr('id'));
//		                    }
//		                }
		            });
		            $('.delete_buttun').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                $('#cod_zarib')[0].value = row.data().cod_zarib;
		                
		                jadvZar_IsNew="delete";
		                $("#delete").modal('show');
	                
		            });
		        },
		        "colVis": {
			           "buttonText": buttonText,
			           exclude:[0]
			       },
		        
		        "paging": true,
		        'bPaginate': true,
		        "pagingType": "full_numbers",
		        "processing": true,
		        "serverSide": true,
		        "bDestroy": true,
		        "bAutoWidth": false,
		        "language": {
		      		
		      	  "sProcessing": "<img src='image/ajax-loader-white.gif'>",
		            "sLengthMenu": sLengthMenu,
		            "sZeroRecords": sZeroRecords,
		            "info": info,
		            "sInfoEmpty": sInfoEmpty,
		            "sInfoFiltered": sInfoFiltered,
		            "sInfoPostFix": "",
		            "sSearch": sSearch,
		            "sUrl": "",
		            "oPaginate" : {
		                "sFirst": sFirst,
		                "sPrevious": sPrevious,
		                "sNext": sNext,
		                "sLast": sLast
                    }
                },
		        "sAjaxSource": "jadval_zarayeb_list.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>" ,
		        "aoColumns": [
		            { "data": "name_var" },
				    { "data": "naghsh_var" },
	                { "data": "var_type" },
	                { "data": "taarif_elmi_amali" },
			        { "data": "ravesh_andaze" },
					{ "data": "meghyas" },
                    { "data": "edit", "bSortable": false  },
				    { "data": "delete" , "bSortable": false },
				    { "data": "cod_zarib","sClass": "hidden"}
		        ]

		    });
		//show_dataTable();

			$("#jadval_zarayeb_form").submit(function(e)
					{
				//dicision for edit or add
				var form2 = $('#jadval_zarayeb_form');
		        var error2 = $('.alert-danger', form2);
		        var success2 = $('.alert-success', form2);
		        if(language=="en"){
			       	 form2.validate({
			             errorElement: 'span', //default input error message container
			             errorClass: 'help-block', // default input error message class
			             focusInvalid: false, // do not focus the last invalid input
			             ignore: "",
			             rules:{
				       	         	   name_var:{
			 	  	                 		required:true
			 	  	                  },
			 		  	                naghsh_var:{
				 	  	                	required:true
			 	  	                  		
			 	  			          },
				 	  			       var_type:{
			 	  		                  	required:true
			 	  				      }  				    
			 	  	              },
			 		  	      

			             invalidHandler: function (event, validator) { //display error alert on form submit              
			 	                    success2.hide();
			 	                    error2.show();
			 	                    App.scrollTo(error2, -200);
			             },

			             errorPlacement: function (error, element) { // render error placement for each input type
			                 var icon = $(element).parent('.input-icon').children('i');
			                 icon.removeClass('fa-check').addClass("fa-warning");  
			                 icon.attr("data-original-title", error.text()).tooltip();
			             },

			             highlight: function (element) { // hightlight error inputs
			                 $(element)
			                     .closest('.form-group').addClass('has-error'); // set error class to the control group   
			             },

			             unhighlight: function (element) { // revert the change done by hightlight
			                 
			             },

			             success: function (label, element) {
			                 var icon = $(element).parent('.input-icon').children('i');
			                 $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
			                 icon.removeClass("fa-warning").addClass("fa-check");
			             },

			             submitHandler: function (form) {
			                 success2.show();
			                 error2.hide();
			             }
			         });
			            }else{
			        form2.validate({
			            errorElement: 'span', //default input error message container
			            errorClass: 'help-block', // default input error message class
			            focusInvalid: false, // do not focus the last invalid input
			            ignore: "",
			            rules:{
			                    	name_var:{
				  	                 		required:true
				  	                  },
					  	                naghsh_var:{
					  	                	required:true
				  			          },
					  			        var_type:{
				  		                  	required:true
				  				      }  				    
				  	              },
					  	            messages:{
					  	                    	name_var:{
						  	                  		required:"پر کردن اين فيلد الزامي مي باشد"
						  	            	  },
							  	            	naghsh_var:{
							  	            		
						  	                 		required:"پر کردن اين فيلد الزامي مي باشد"
						  	    		          },
							  	    		        var_type:{
						  	                  		required:"پر کردن اين فيلد الزامي مي باشد"
						  	    		          }
						      		          
						  	              },
				  	              

			            invalidHandler: function (event, validator) { //display error alert on form submit              
				                    success2.hide();
				                    error2.show();
				                    App.scrollTo(error2, -200);
			            },

			            errorPlacement: function (error, element) { // render error placement for each input type
			                var icon = $(element).parent('.input-icon').children('i');
			                icon.removeClass('fa-check').addClass("fa-warning");  
			                icon.attr("data-original-title", error.text()).tooltip();
			            },

			            highlight: function (element) { // hightlight error inputs
			                $(element)
			                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
			            },

			            unhighlight: function (element) { // revert the change done by hightlight
			                
			            },

			            success: function (label, element) {
			                var icon = $(element).parent('.input-icon').children('i');
			                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
			                icon.removeClass("fa-warning").addClass("fa-check");
			            },

			            submitHandler: function (form) {
			                success2.show();
			                error2.hide();
			            }
			        });
			            }
				debugger;
						var formURL;
						var postData = $(this).serializeArray();
						if(jadvZar_IsNew=="insert")		
							 formURL = $(this).attr("action");
						else if(jadvZar_IsNew=="edit")		
							formURL="jadval_zarayeb_sabt.php?action=edit";
						else if(jadvZar_IsNew=="delete")		
							formURL="jadval_zarayeb_sabt.php?action=delete";
						if($("#jadval_zarayeb_form").valid() || (jadvZar_IsNew=="delete"))
						{
							$(".green").attr("disabled","disabled");
						$.ajax(
						{
							url : formURL,
							type: "POST",
							data : postData,
							success:function(data, textStatus, jqXHR) 
							{
							//alert(data);
							if(data=="exist")
							{
								$("#jadval_zarayeb_i").switchClass( "fa-times", "fa-check", 1000, "easeInOutQuad" );
							}
							else if(data=="notexist")
							{
								$("#jadval_zarayeb_i").switchClass( "fa-check","fa-times", 1000, "easeInOutQuad" );
							}
							jadvZar_IsNew="insert";
							$("#basic").modal('hide');
							$("#delete").modal('hide');
							$("#jadval_zarayeb_form")[0].reset();
							 //Begin of reset form validation 
						    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
						    $(".input-icon .fa-check").switchClass("fa-check","fa");
						    $(".alert-danger").hide();
						    $('.form-group').removeClass('has-error');
						    $('.form-group').removeClass('has-success');
						  //End of reset form validation
						    	//debugger;
						            var uniSelect = $("#uniSelect");
						            var temp = $("#temp");
						            uniSelect.appendTo(temp);
						            dt.ajax.url("jadval_zarayeb_list.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>");
						            dt.ajax.reload();
									//show_dataTable();
						        
							},
							error: function(jqXHR, textStatus, errorThrown) 
							{
							}
						}).always( $(".green").removeAttr("disabled","disabled"));
						}
					    e.preventDefault();	//STOP default action
					  //  $("#jadval_zarayeb_form").submit(); //SUBMIT FORM
					});

	 });
	
	function show_dataTable()
	{
		
	}
	
		var jadvZar_IsNew="insert";

		$('#basic').on('hidden.bs.modal', function () {
		   // debugger;
		    jadvZar_IsNew="insert";
		    $("#jadval_zarayeb_form")[0].reset();
		    $('#naghsh_var').prop('selectedIndex',"");
		    $('#var_type').prop('selectedIndex',"");
		});
		$('#delete').on('hidden.bs.modal', function () {
			   // debugger;
			    jadvZar_IsNew="insert";
			    $("#jadval_zarayeb_form")[0].reset();
			    $('#naghsh_var').prop('selectedIndex',"");
			    $('#var_type').prop('selectedIndex',"");
			});
			 
	 </script>
	 	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}

				
			
	 </script>

<?php
footer_forms($admin,$seed);
?>

