<?
include("include/database-connect.phtml");
include("include/include.phtml");
//include("include/vars.inc.phtml");

header_forms();
?>
<!-- BEGIN PAGE LEVEL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css"/>
    <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css"/>
    
    <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>

    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
    <link id="toastr" rel="stylesheet" type="text/css" href="../assets/plugins/bootstrap-toastr/toastr-rtl.min.css"/>
<!-- END PAGE LEVEL STYLES -->
    
    <!--First of test with previous css  -->
    <!-- <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" /> -->
      
    <!-- End of test with previous css -->
    <!-- END PAGE LEVEL STYLES -->
<?php
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content"> 
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                               در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h4 id="page-title" class="page-title">
                            <i class="fa fa-envelope"></i> ليست نامه ها
                        </h4>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="breadcrumb1" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle-left1" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb2" href="#">
                                    <i class="fa fa-envelope"></i> ليست نامه ها 
                                </a>
                               
                            </li>
                            
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                    
              <!-- BEGIN DATA TABLE PORTLET-->
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div id="portlet_caption" class="caption">
                                    <i class="fa fa-globe"></i>ليست نامه ها
                                </div>
                                <div class="tools">
									<a href="javascript:;" class="collapse">
									</a>
									<a href="#portlet-config" data-toggle="modal"
									class="fa fa-info-circle" title="راهنما"
									style="color: white">
									</a>
								</div>
                            </div>
                            <div class="portlet-body">
	                           <!--  <div class="col-md-3">
									<div class="form-group">
										
									</div>
				                </div>   -->
				                	<!-- BEGIN FORM-->
												
													<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
							                                        <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                          <h4 id="modal_title" class="modal-title">
							                                            <i  class="fa fa-file-o"></i>
							                                            عنوان
							                                        </h4>
							                                     </div>
							                                    <div class="modal-body">
							                                    
																		   <!-- BEGIN FORM-->
															               <!-- <form name="mojri_tarh" id="mojri_tarh_sabt" action="mojri_tarh.php?action=add_mojri&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&mojri_code=$mojri_code" method="POST" class="form-horizontal">-->	
																	<?php 
																		   echo "<form id=\"letter_reply\" method=\"post\" action=\"letter_sabt.php?action=send_email&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" class=\"form-horizontal\">";
																     ?>
																   <input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control" value="<?php echo $cod_tarh;?>"> 
																   <input id="letterno" name="letterno" type="hidden" class="form-control">
																		<div class="form-body">
																			<div id="alert_danger" class="alert alert-danger display-hide">
																				<button class="close" data-close="alert"></button>
																			    پر کردن فيلدهاي ستاره دار اجباري مي باشد.
																		    </div>
																			<div class="row">
																				<div class="col-md-9 col-md-push-1">
																					<div class="form-group">
																						<label id="lb1" class="control-label col-md-3">عنوان
																						<span class="required">
																							 *
																						</span>
																						</label>
																						<div class="col-md-9">
																							<div class="input-icon right">
																								<i class="fa"></i>
																								<input id="letter_subject" name="letter_subject" type="text" class="form-control" placeholder="">
																							</div>
																						</div>
																					</div>
																				</div>
																				<!--/span-->
																				
																			</div>
																			<!--/row-->
																			<div class="row">
																			<div class="col-md-9 col-md-push-1">
																					<div class="form-group">
																						<label id="lb2" class="control-label col-md-3">متن نامه</label>
																						<div class="col-md-9">
																								<textarea id="letter_body" name="letter_body" rows="7" cols="64"></textarea>
																						</div>
																					</div>
																				</div>
																			</div>
																			
																		</div>
																	
																	
																	<!-- END FORM-->
																	
							                                     
							                                    </div>
							                                      <div class="modal-footer">
								                                       <button id="btn1" type="submit"  class="btn green">ذخيره</button>
																	   <button id="btn2" type="button" class="btn red" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              </div>
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      </form>
							    <div class="col-md-3">
									 <div class="form-group">
										<label id="type_letter_lb" class="control-label col-md-4">نوع نامه:</label>
										<div id="type_letter_select" class="col-md-8">
											<select id="letter_type" class="select2_category form-control" data-placeholder="Choose a Category" tabindex="1">
												<option value="-1">همه</option>
												<option value="0">نامه هاي خوانده نشده</option>
												<option value="1">نامه هاي خوانده شده</option>
											</select>												
										</div>
									</div>
				                </div>  
                                <table class="table table-striped table-bordered table-hover" id="sample_1">
                                    <thead>
                                        <tr>
                                            <th class="hidden">
                                                id
                                            </th>
                                            <th id="th1">
                                                شماره نامه
                                            </th>
                                            <th id="th2">
                                                 تاريخ
                                            </th>
                                            <th id="th3">
                                                 کد طرح
                                            </th>
                                            <th id="th4">
                                                 عنوان نامه
                                            </th>
                                            <th id="th5">
                                                 از
                                            </th>
                                            <th id="th6">
                                                به 
                                            </th>
                                            <th id="th7">
                                                پاسخ
                                            </th>
                                            <th id="th8">
                                                جزييات
                                            </th> 
                                        </tr>
                                    </thead>
                                   <tbody>
                                   
                                   </tbody>
                                </table>
                             </div>
                        </div>
                        <!-- END DATA TABLE PORTLET-->      
                       
</div>
</div>
<!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->

<script>
if(language=="en"){																										    
debugger;
document.getElementById("page-title").innerHTML="<i class='fa fa-envelope'></i>Received Letters";
document.getElementById("breadcrumb1").textContent="Home";
document.getElementById("fa-angle-left1").setAttribute("class","fa fa-angle-right");
document.getElementById("breadcrumb2").innerHTML="<i class='fa fa-envelope'></i>Received Letters";
document.getElementById("portlet_caption").innerHTML="<i class='fa fa-globe'></i>Received Letters";
document.getElementById("modal_title").innerHTML="<i  class='fa fa-file-o'></i>Title";
document.getElementById("alert_danger").innerHTML="<button class='close' data-close='alert'></button>You have some form errors. Please check below.";
document.getElementById("lb1").textContent="Subject";
document.getElementById("lb2").textContent="Text";
document.getElementById("btn1").textContent="Save";
document.getElementById("btn2").textContent="Cancel";
document.getElementById("type_letter_lb").textContent="Letter type";
document.getElementById("type_letter_select").innerHTML="<select id='letter_type' class='select2_category form-control' data-placeholder='Choose a Category' tabindex='1'><option value='-1'>All</option><option value='0'>unread</option><option value='1'>read</option></select>";

document.getElementById("th1").textContent="Issued Letter Number";
document.getElementById("th2").textContent="Date";
document.getElementById("th3").textContent="Project Code";
document.getElementById("th4").textContent="Subject";
document.getElementById("th5").textContent="From";
document.getElementById("th6").textContent="To";
document.getElementById("th7").textContent="Reply";
document.getElementById("th8").textContent="Details";
document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
document.getElementById("toastr").href="../assets/plugins/bootstrap-toastr/toastr.min.css";
}
</script>

<?php 
include("../include/primary_js.phtml");
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="../assets/scripts/core/app.js"></script>-->
    <!--<script src="../assets/scripts/custom/table-advanced.js"></script>-->
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
            // initiate layout and plugins
            
         //   TableAdvanced.init();
        });
    </script>
    <script>
    function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
function format(d) {
    var r;
    $.ajax({
        url: "letter_details.php",
        type: "POST",
        data: { id: d.id },
        async: false,
        dataType: "html",
        success: function(result) {
            r = result;

        }
    });
    return r;
}
$("#letter_reply").submit(function(e){
    // for more info visit the official plugin documentation: 
        // http://docs.jquery.com/Plugins/Validation
        debugger;
        var form2 = $('#letter_reply');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);
       /* jQuery.validator.addMethod("test", function(value, element) {
            return this.optional(element) || /^09[123]\d{8}/.test(value);
        }, "Your entered data is not phone number");*/
if(language=="en"){ 
        form2.validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block', // default input error message class
            focusInvalid: false, // do not focus the last invalid input
            ignore: "",
            rules:{
            	letter_subject:{
  	                  required:true,
  	                  //test:true,
    	              //rangelength:[11,11]
  	                  },
  	              },
  	              

            invalidHandler: function (event, validator) { //display error alert on form submit              
                    success2.hide();
                    error2.show();
                    App.scrollTo(error2, -200);
            },

            errorPlacement: function (error, element) { // render error placement for each input type
                var icon = $(element).parent('.input-icon').children('i');
                icon.removeClass('fa-check').addClass("fa-warning");  
                icon.attr("data-original-title", error.text()).tooltip();
            },

            highlight: function (element) { // hightlight error inputs
                $(element)
                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
            },

            unhighlight: function (element) { // revert the change done by hightlight
                
            },

            success: function (label, element) {
                var icon = $(element).parent('.input-icon').children('i');
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                icon.removeClass("fa-warning").addClass("fa-check");
            },

            submitHandler: function (form) {
                success2.show();
                error2.hide();
            }
        });
}
else{
		  form2.validate({
	          errorElement: 'span', //default input error message container
	          errorClass: 'help-block', // default input error message class
	          focusInvalid: false, // do not focus the last invalid input
	          ignore: "",
	          rules:{
	          	letter_subject:{
		                  required:true,
		                  //test:true,
	  	              //rangelength:[11,11]
		                  },
		              },
		  	    messages:{
		  	    	letter_subject:{
		                  required:"پر کردن اين فيلد الزامي مي باشد",
		            	  },
			  	      },
		              
	
	          invalidHandler: function (event, validator) { //display error alert on form submit              
	                  success2.hide();
	                  error2.show();
	                  App.scrollTo(error2, -200);
	          },
	
	          errorPlacement: function (error, element) { // render error placement for each input type
	              var icon = $(element).parent('.input-icon').children('i');
	              icon.removeClass('fa-check').addClass("fa-warning");  
	              icon.attr("data-original-title", error.text()).tooltip();
	          },
	
	          highlight: function (element) { // hightlight error inputs
	              $(element)
	                  .closest('.form-group').addClass('has-error'); // set error class to the control group   
	          },
	
	          unhighlight: function (element) { // revert the change done by hightlight
	              
	          },
	
	          success: function (label, element) {
	              var icon = $(element).parent('.input-icon').children('i');
	              $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
	              icon.removeClass("fa-warning").addClass("fa-check");
	          },
	
	          submitHandler: function (form) {
	              success2.show();
	              error2.hide();
	          }
	      });
}

var formURL;
var postData = $(this).serializeArray();	
	 formURL = $(this).attr("action");
	 debugger;
if($("#letter_reply").valid())
{
    $(".green").attr("disabled","disabled");
	$.ajax(
	{
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			    //alert(data);
			    //debugger;
				if(data=="sent")
				{
					if(language=="en")
						success="Reply to mentioned letter, sent.";
					else
						success="پاسخ به نامه مذکور ارسال شد";
					toastr.options.timeOut="5000";
			        toastr.options.positionClass="toast-top-right";
					toastr.success(success);
				}
				$("#basic").modal('hide');
				$("#letter_reply")[0].reset();
			
	           $("#sample_1").DataTable().destroy();
	    		
	           show_dataTable(); 
	           $(".green").removeAttr("disabled","disabled");
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
		}
	});

	}
    e.preventDefault();	//STOP default action
});
$(document).ready(function() {
  //  var detailRows = [];
   // var dt;
	debugger;
   show_dataTable();
   $('#letter_type').change(function() {
		debugger;
		if(language=="en")
			caption="All";
		else
			caption="ليست نامه ها";
		if($('#letter_type :selected').val()=="-1")
			$(".caption").text(caption);
		else
			$(".caption").text($('#letter_type :selected').text());
	    $("#sample_1").DataTable().destroy();
	    show_dataTable();
   });

});
var buttonText;
var sButtonText;
var info;
//var	language="en";
if(language=="en"){
	buttonText="Visibel Columns";
	sButtonText3="Copy";
	sButtonText="Print";
	sButtonText2="Save";
	info="view _START_ to _END_ from _TOTAL_ items";
	sLengthMenu="View Content _MENU_";
	sZeroRecords="Not Found";
	sInfoEmpty="Empty";
	sInfoFiltered="(Filtered From _MAX_ Items)";
	sSearch="Search";
	sFirst="First";
	sPrevious="Previous";
	sNext="Next";
	sLast="Last";
	
	
}
else
{
	buttonText="ستون هاي قابل نمايش";
	sButtonText3="کپي";
	sButtonText="چاپ";
	sButtonText2="ذخيره";
	info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
	sLengthMenu="نمايش محتويات _MENU_";
	sZeroRecords="موردي يافت نشد";
	sInfoEmpty="تهي";
	sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
	sSearch="جستجو";
	sFirst="ابتدا";
	sPrevious="قبلي";
	sNext="بعدي";
	sLast="انتها";
	
}
function show_dataTable(){
	 var detailRows = [];
     var dt;
	 dt = $('#sample_1').DataTable({
	  	   "colVis": {
	           "buttonText": buttonText
	       },
					    				"dom": 'CT<"clearfix">lfrtip',
					    				"tableTools": {
					    					"sRowSelect": "os",
					    					 "aButtons": [
					    						 {
					    							"sExtends": "copy",
					    							"sButtonText": sButtonText3
					    						},
					    						{
					    							"sExtends": "print",
					    							"sButtonText": sButtonText
					    						},
					    						
					    						{
					    							"sExtends":    "collection",
					    							"sButtonText": sButtonText2,
					    							"aButtons":    [ 
					    												"csv", 
					    												"xls"
					    											]
					    						}
					    					],
					    					
					    					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
					    				},
					                "fnInitComplete": function(oSettings, json) {
									
									fixControlPosition();
									
					                },
	        "fnDrawCallback": function(oSettings) {
	            var trs = $("#sample_1 tr");
	            for (var i = 1; i < trs.length; i++) {

	                var rowId = ($(trs[i]).attr('id'));
	                $("#" + rowId + " td:last-child").trigger('click');

	            }
	            $('.row-details').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                var idx = $.inArray(tr.attr('id'), detailRows);

	                if (row.child.isShown()) {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-open');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-close');
	                
	                    row.child.hide();

	                    // Remove from the 'open' array
	                    detailRows.splice(idx, 1);
	                } else {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-close');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-open');
	                    
	                
	                    row.child(format(row.data())).show();

	                    // Add to the 'open' array
	                    if (idx === -1) {
	                        detailRows.push(tr.attr('id'));
	                    }
	                }
	            });
	            $('.reply_btn').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                //alert(row.data().id);
	                $('#letterno')[0].value = row.data().id;
	            });
	        },
	        
	        "paging": true,
	        'bPaginate': true,
	        "pagingType": "full_numbers",
	        "processing": true,
	        "serverSide": true,
	        "bDestroy": true,
	        "bAutoWidth": false,
	        "order": [[ 2, "desc" ]],
	        "language": {
			
	        	"sProcessing": "<img src='image/ajax-loader-white.gif'>",
	            "sLengthMenu": sLengthMenu,
	            "sZeroRecords": sZeroRecords,
	            "info": info,
	            "sInfoEmpty": sInfoEmpty,
	            "sInfoFiltered": sInfoFiltered,
	            "sInfoPostFix": "",
	            "sSearch": sSearch,
	            "sUrl": "",
	            "oPaginate" : {
	                "sFirst": sFirst,
	                "sPrevious": sPrevious,
	                "sNext": sNext,
	                "sLast": sLast
	            }
	        },
	        "sAjaxSource": "letter_sabt.php?admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>&action=letter_list&+letter_type=" + $('#letter_type :selected').val(),
	        "aoColumns": [
				{ "data": "id", "sClass": "hidden"},
	            { "data": "letter_no" },
	            { "data": "letter_date" },
	            { "data": "cod_tarh" },
	            { "data": "letter_subject" },
	            { "data": "from_letter" },
	            { "data": "to_letter" },
	            { "data": "edit" },
	            { "data": "details", "sClass": "row-details row-details-close", "bSortable": false} 
	        ]

	    });
}
$('#basic').on('hidden.bs.modal', function () {
	   // debugger;
	    $("#letter_reply")[0].reset();
	    //Begin of reset form validation 
	    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
	    $(".input-icon .fa-check").switchClass("fa-check","fa");
	    $(".alert-danger").hide();
	    $('.form-group').removeClass('has-error');
	    $('.form-group').removeClass('has-success');
	    //End of reset form validation
	});
</script>
    
<?php
footer_forms($admin,$seed);
?>

