<?
 include("include/database-connect.phtml");
 include("include/include.phtml");
 
  
global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;
?>
 
<?
while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);

  if( $type == 1 or $type==2 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login.phtml");
   exit();
  }
 }
 else
 {
   header ("Refresh: 0; url=../login.phtml");
   exit();
  }
 $q="select * from karshenasan where  karshenas_email='$admin'";
 $rs=mysql_query($q) or die("error 333");
 $rf=mysql_fetch_array($rs);
 $username=$rf["username"];
 
 $q="update sessions  set usertype='3',username='$username'  where username='$admin' and rand='$seed'";
 $rs=mysql_query($q) or die("error 333");
 
 
 ?>
 
 
 
 <SCRIPT language="JavaScript">

 
window.location="<? echo "../karshenas/tarh_list_new.phtml?admin=$username&seed=$seed";?>";
 

</SCRIPT>
