<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms();
?>
 <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css" />
 <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css" />
 <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>
   <!--  <link href="../assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />-->
  <!--  <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />-->
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
  <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />

<?php
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                 <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                                در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h3 id="page_title" class="page-title">
                           اساتيد راهنما و مشاور
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="breadcrumb_home" href="">
                                    خانه
                                </a>
                                <i id="fa_angle1" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb_your_thesis" href="payan_name_list.phtml">
                                    پايان نامه شما
                                </a>
                                <i id="fa_angle2" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb_supervisors" href="ostad_rahnama.phtml">
                                    اساتيد راهنما
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
               <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <div id="wizard" class="caption">
                                    <i class="fa fa-magic"></i>ويزارد
                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <?php  $active_id="15"; include("include/wizard.php");?>
                                    <div class="col-md-9 col-sm-9 col-xs-9">
                                       <div class="portlet box blue">
											<div class="portlet-title">
												<div id="caption_supervisor" class="caption">
													<i class="fa fa-reorder"></i>اساتيد راهنما و مشاور
												</div>
												<div class="tools">
													<a href="javascript:;" class="collapse">
													</a>
													<a href="#portlet-config" data-toggle="modal"
													class="fa fa-info-circle" title="راهنما"
													style="color: white">
													</a>
												</div>
											</div>
											<div class="portlet-body form-horizontal">
											
												<!-- BEGIN FORM-->
												<form name="search_ostad" id="search_ostad" action="ostad_rahnama.php" method="POST" class="form-horizontal">
												<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
												
												
													<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog ">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
							                                        <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                          <h4 id="modal_title_looking_professor" class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                            جستجو استاد مورد نظر
							                                        </h4>
							                                     </div>
							                                    <div class="modal-body">
							                                    
																   <input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control" value="<?php echo $cod_tarh;?>"> 
															   	   <input id="mojri_code" name="mojri_code" type="hidden" class="form-control">
																		<div class="form-body">
																		
																			<div id="alert_danger" class="alert alert-danger display-hide">
																				<button class="close" data-close="alert"></button>
																			    وارد کردن نام و نام خانوادگي الزامي است.
																		    </div>
																			
																			<div class="row">
																					<div class="col-md-6">
																						<div class="form-group">
																								<label id="first_name_lb" class="control-label col-md-3">نام 
																								<span class="required">
																									 *
																								</span>
																								</label>
																								<div class="col-md-9">
																									<div class="input-icon right">
																										<i class="fa col-md-push-6"></i>
																										<input name="name" id="name" type="text" class="form-control" placeholder="" tabindex="1">
																									</div>
																								</div>
																							</div>
																					</div>
																										
																					<!--/span-->
																					<div class="col-md-6">
																						   <div class="form-group">
																								<label id="last_name_lb" class="control-label col-md-3">نام خانوادگي
																								<span class="required">
																									 *
																								</span>
																								</label>
																								<div class="col-md-9">
																									<div class="input-icon right">
																										<i class="fa col-md-push-6"></i>
																										<input name="family" id="family" type="text" class="form-control" placeholder="" tabindex="2">
																									</div>
																								</div>
																							</div>
																					</div>
																										
																					<!--/span-->
																			</div>
																			<!--/row-->
																			<div class="row">
																			<!--/span-->
																				   <div class="col-md-6">
																						   <div class="form-group">
																								<label id="email_lb" class="control-label col-md-3">ايميل
																								<span class="required">
																									 
																								</span>
																								</label>
																								<div class="col-md-9">
																									<div class="input-icon right">
																										<i class="fa col-md-push-6"></i>
																										<input name="email" id="email" type="text" class="form-control" placeholder="" tabindex="3">
																									</div>
																								</div>
																							</div>						
																					</div>
																										
																			<!--/span-->
																				   <div class="col-md-6">
																						<div class="form-group">
																							<label id="expert_lb" class="control-label col-md-3">تخصص</label>
																							<div class="col-md-9">
																									<input name="takhasos" id="takhasos" type="text" class="form-control" placeholder="" tabindex="4">
																							</div>
																						</div>
																					</div>
																										
																			<!--/span-->
																			</div>
																			
																		
																			
																		</div>
																	
																	
																	<!-- END FORM-->
																	
							                                     
							                                    </div>
							                                      <div class="modal-footer">
							                                      	   <button id="search_btn" type="submit" class="btn blue input-sm  input-small" data-loading-text="در حال جستجو...">جستجو</button>
																	   <button id="cancel_search_btn" type="button" class="btn red input-sm  input-small" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              </div>
							                                </div>
							                                <!-- /.modal-content --> 
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      </form>
							                        <div class="modal fade " id="ostad_list"  tabindex="-1" role="ostad_list" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                    <div class="modal-header bg-blue">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 id="sabt_ostad_modal_title" class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                   
							                                   <form name="sabt_ostad" id="sabt_ostad" action="ostad_rahnama.php?action=sabt" method="POST" class="form-horizontal">
							                                  	   <input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
								                                   
								                                   <div class="form-actions fluid">
								                                   				<div class="table-responsive" id="div_ostad_list"></div>
																				<div class="row">
																					
																					<div class="col-md-6">
																						<div class="col-md-offset-3 col-md-9">
																							<button type="submit" id="sabt_btn"  class="btn blue">اعمال</button>
																							<button id="cancel_professor_btn" type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>انصراف</button>
																						</div>
																					</div>
																					<div class="col-md-6">
																					</div>
																				</div>
																	</div>
							                                     </form>
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      <div class="modal fade " id="delete"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																	
																		<div class="form-body">
																			<h4 id="delete_message" class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
																		</div>
																		<form name="delete_ostad" id="delete_ostad" action="#" method="POST" class="form-horizontal">
																		<input id="position1" name="position1" type="hidden" class="form-control" >
																		<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9 delete_btn">
																						<button id="yes_btn" type="submit"  class="btn blue">بلي</button>
																						<button id="no_btn" type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>خير</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																		</form>
																	
																	<!-- END FORM-->
							                                    </div>
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
						                        <a id="supervisor1" style="margin-right:.5em" class="btn blue btn-sm pull-left" onclick="change_mode(0);" data-toggle="modal" href="#basic">
						                           ثبت استاد راهنما اول
						                        </a>
						                        <a id="supervisor2" style="margin-right:.5em" class="btn blue btn-sm pull-left" onclick="change_mode(1);" data-toggle="modal" href="#basic">
						                           ثبت استاد راهنما دوم
						                        </a>
						                       <a id="supervisor3" style="margin-right:.5em" class="btn blue btn-sm pull-left" onclick="change_mode(2);" data-toggle="modal" href="#basic">
						                            ثبت استاد مشاور اول 
						                        </a>
						                        <a id="supervisor4" style="margin-right:.5em" class="btn blue btn-sm pull-left" onclick="change_mode(3);" data-toggle="modal" href="#basic">
						                          ثبت استاد مشاور دوم
						                        </a>
						                        
												<!-- END FORM-->
												<table class="table table-striped table-bordered table-hover" id="sample_1">
				                                    <thead>
				                                        <tr>
				                                            <th id="th1" class="hidden-xs">
				                                                سمت
				                                            </th>
				                                            <th id="th2" class="hidden-xs">
				                                                نام
				                                            </th>
				                                            <th id="th3" class="hidden-xs">
				                                                نام خانوادگي
				                                            </th>
				                                            <th id="th4" class="hidden-xs">
				                                                تخصص
				                                            </th>
				                                            <th id="th5" class="hidden-xs">
				                                                حذف
				                                            </th>
				                                           <!--  <th class="hidden">
				                                                حذف
				                                            </th>--> 
				                                        </tr>
				                                    </thead>
				                                   
			                                	</table>
											</div>
										</div>
                                    </div>

                                </div>
                            </div>
                            
                        </div>

                    </div>
                </div>
                <!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->

<script>
if(language=="en"){
	
	debugger;
	document.getElementById("page_title").textContent="Supervisors";;
	document.getElementById("breadcrumb_home").textContent="Home";
	document.getElementById("fa_angle1").className="fa fa-angle-right";
	document.getElementById("breadcrumb_your_thesis").textContent="Your Thesis";
	document.getElementById("fa_angle2").className="fa fa-angle-right";
	document.getElementById("breadcrumb_supervisors").textContent="Supervisors";
	document.getElementById("wizard").innerHTML="<i class='fa fa-magic'></i>Wizard";
	document.getElementById("caption_supervisor").innerHTML="<i class='fa fa-reorder'></i>Supervisors";
 	document.getElementById("modal_title_looking_professor").innerHTML="<i class='fa fa-reorder'></i>Looking Professors";
 	document.getElementById("alert_danger").innerHTML="<button class='close' data-close='alert'></button>Required first name and last name";
 	document.getElementById("first_name_lb").textContent="First Name";
 	document.getElementById("last_name_lb").textContent="Last Name";
 	document.getElementById("email_lb").textContent="Email";
 	document.getElementById("expert_lb").textContent="Expert";
	document.getElementById("search_btn").textContent="Looking";
	document.getElementById("search_btn").setAttribute("data-loading-text","Loading...");
 	document.getElementById("cancel_search_btn").textContent="Cancel";
 	document.getElementById("sabt_btn").textContent="Save";
 	document.getElementById("cancel_professor_btn").textContent="Cancel";
 	document.getElementById("delete_message").textContent="Are you sure to remove this item?";
 	document.getElementById("yes_btn").textContent="Yes";
 	document.getElementById("no_btn").innerHTML="<i class='fa fa-times'></i>No";
 	document.getElementById("supervisor1").textContent="Supervisor1";
 	document.getElementById("supervisor2").textContent="Supervisor2";
 	document.getElementById("supervisor3").textContent="Supervisor3";
 	document.getElementById("supervisor4").textContent="Supervisor4";
 	document.getElementById("th1").textContent="Title";
 	document.getElementById("th2").textContent="First Name";
 	document.getElementById("th3").textContent="Last Name";
 	document.getElementById("th4").textContent="Expert";
 	document.getElementById("th5").textContent="Delete";
	document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
	document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
}
</script>
<?php 
include("../include/primary_js.phtml");
?>

	
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
		 $('body').addClass(" page-sidebar-closed");
 		 $(":input").addClass("input-sm input-small");
 		 $(".delete_btn :button").removeClass("input-sm input-small");
 		 $(".modal-header :button").removeClass("input-sm input-small");
  		$(".alert-danger :button").removeClass("input-sm input-small");
	});
	var mode;
	function change_mode(val)
	{
		mode=val;
		if(language=="en")
		{
			if(mode==0)
				$("#sabt_ostad_modal_title").text("Supervisor1");
			else if(mode==1)
				$("#sabt_ostad_modal_title").text("Supervisor2");
			else if(mode==2)
				$("#sabt_ostad_modal_title").text("Supervisor3");
			else if(mode==3)
				$("#sabt_ostad_modal_title").text("Supervisor4");
		}
		else
		{
			if(mode==0)
				$("#sabt_ostad_modal_title").text("ثبت استاد راهنما اول");
			else if(mode==1)
				$("#sabt_ostad_modal_title").text("ثبت استاد راهنما دوم");
			else if(mode==2)
				$("#sabt_ostad_modal_title").text("ثبت استاد مشاور اول");
			else if(mode==3)
				$("#sabt_ostad_modal_title").text("ثبت استاد مشاور دوم");
		}
			
	}

	$("#search_ostad").submit(function(e)
	{
        var form2 = $('#search_ostad');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);
		if(language=="en")
		{
			   form2.validate({
		            errorElement: 'span', //default input error message container
		            errorClass: 'help-block', // default input error message class
		            focusInvalid: false, // do not focus the last invalid input
		            ignore: "",
		            rules:{
		  	        	  name:{
		  	                  required:true
		  	                  },
		    	          family:{
		      	              required:true
		      	               },
		  	              },

		            invalidHandler: function (event, validator) { //display error alert on form submit              
		                    success2.hide();
		                    error2.show();
		                    App.scrollTo(error2, -200);
		            },

		            errorPlacement: function (error, element) { // render error placement for each input type
		                var icon = $(element).parent('.input-icon').children('i');
		                icon.removeClass('fa-check').addClass("fa-warning");  
		                icon.attr("data-original-title", error.text()).tooltip();
		            },

		            highlight: function (element) { // hightlight error inputs
		                $(element)
		                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
		            },

		            unhighlight: function (element) { // revert the change done by hightlight
		                
		            },

		            success: function (label, element) {
		                var icon = $(element).parent('.input-icon').children('i');
		                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
		                icon.removeClass("fa-warning").addClass("fa-check");
		            },

		            submitHandler: function (form) {
		                success2.show();
		                error2.hide();
		            }
		        });
		}
		else
		{
			   form2.validate({
		            errorElement: 'span', //default input error message container
		            errorClass: 'help-block', // default input error message class
		            focusInvalid: false, // do not focus the last invalid input
		            ignore: "",
		            rules:{
		  	        	  name:{
		  	                  required:true
		  	                  },
		    	          family:{
		      	              required:true
		      	               },
		  	              },
			  	          messages:{
		      		      name:{
		  	                   required:"پر کردن اين فيلد الزامي مي باشد",
		  	    		          }, 
		    	    	  family:{
		    	  	      	   required:"پر کردن اين فيلد الزامي مي باشد"
		    	  	      	      }, 
				  	      },
		  	              

		            invalidHandler: function (event, validator) { //display error alert on form submit              
		                    success2.hide();
		                    error2.show();
		                    App.scrollTo(error2, -200);
		            },

		            errorPlacement: function (error, element) { // render error placement for each input type
		                var icon = $(element).parent('.input-icon').children('i');
		                icon.removeClass('fa-check').addClass("fa-warning");  
		                icon.attr("data-original-title", error.text()).tooltip();
		            },

		            highlight: function (element) { // hightlight error inputs
		                $(element)
		                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
		            },

		            unhighlight: function (element) { // revert the change done by hightlight
		                
		            },

		            success: function (label, element) {
		                var icon = $(element).parent('.input-icon').children('i');
		                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
		                icon.removeClass("fa-warning").addClass("fa-check");
		            },

		            submitHandler: function (form) {
		                success2.show();
		                error2.hide();
		            }
		        });
		}
		if ($("#search_ostad").valid()){
			debugger;
			var formURL;
			var postData = $("#search_ostad").serializeArray();

			var btn = $("#search_btn");
			btn.button('loading');
					$.ajax(
					{
						url : "ostad_rahnama.php?action=search",
						type: "POST",
						data : postData,
						success:function(data, textStatus, jqXHR) 
						{
						debugger;
						//alert(data);
						
						jadvZar_IsNew="insert";
						$("#basic").modal('hide');
						$("#search_ostad")[0].reset();
						//$("#div_ostad_list").text(data);
						document.getElementById("div_ostad_list").innerHTML=data;
						$("#ostad_list").modal('show');
			            $("#sample_1").DataTable().destroy();
						show_dataTable();
					        
						},
						error: function(jqXHR, textStatus, errorThrown) 
						{
						}
					}).always(function () { 
						 btn.button('reset');
				    });
			}
	    e.preventDefault();	//STOP default action
		});

	$("#sabt_ostad").submit(function(e)
	{
		if(language=="en")
		{
			$(this).validate({
	            rules:{
	            	ostad_name:{
	  	                  required:true
	  	                  },
	  	              },
	  	        invalidHandler: function (event, validator) { //display error alert on form submit     
	  	        if($( "#div_ostad_list" ).prev().length==0)	
	  	        	 $( "#div_ostad_list" ).before( "<span for='ostad_name' class='help-block col-lg-5 col-lg-push-4'>Choose a professor</span>" );
	  	            }, 
	            success: function (label, element) {
	            	$( ".help-block").hide();
		              
	            }, 
	            errorPlacement: function (error, element) { // render error placement for each input type
	            	$( "label[class=error]").hide();
	            },
	            submitHandler: function (form) {
	            	$( ".help-block").show();
	            }

	        });
		}
		else
		{
			$(this).validate({
	            rules:{
	            	ostad_name:{
	  	                  required:true
	  	                  },
	  	              },
		  	          messages:{
			  	    ostad_name:{
	  	                  required:"انتخاب حداکثر يک استاد الزامي است",
	  	    		          },  
			  	              },
	  	        invalidHandler: function (event, validator) { //display error alert on form submit     
	  	        if($( "#div_ostad_list" ).prev().length==0)	
	  	        	 $( "#div_ostad_list" ).before( "<span for='ostad_name' class='help-block col-lg-5 col-lg-push-4'>انتخاب حداکثر يک استاد الزامي است</span>" );
	  	            }, 
	            success: function (label, element) {
	            	$( ".help-block").hide();
		              
	            }, 
	            errorPlacement: function (error, element) { // render error placement for each input type
	            	$( "label[class=error]").hide();
	            },
	            submitHandler: function (form) {
	            	$( ".help-block").show();
	            }

	        });
		}
        if ($("#sabt_ostad").valid()){
		debugger;
		var formURL;
		var postData = $("#sabt_ostad").serializeArray();
		
		debugger;
		$.ajax(
		{
			url : "ostad_rahnama.php?action=sabt"+"&ostad_type="+mode,
			type: "POST",
			data : postData,
			success:function(data, textStatus, jqXHR) 
			{
			debugger;
			//alert(data);
			if(data=="exist"){
				$("#ostad_rahnama_i").switchClass( "fa-times", "fa-check", 1000, "easeInOutQuad" );
				}
			
			jadvZar_IsNew="insert";
			$("#basic").modal('hide');
			$("#search_ostad")[0].reset();
			document.getElementById("div_ostad_list").innerHTML=data;

		            $("#sample_1").DataTable().destroy();
					show_dataTable();
		        
			},
			error: function(jqXHR, textStatus, errorThrown) 
			{
			}
		}).always($("#ostad_list").modal('hide'));
			}
	    e.preventDefault();	//STOP default action
		});

	$("#delete_ostad").submit(function(e)
	{
		debugger;
		var formURL;
		var postData = $("#delete_ostad").serializeArray();
		
		debugger;
		$.ajax(
		{
			url : "ostad_rahnama.php?action=delete",
			type: "POST",
			data : postData,
			success:function(data, textStatus, jqXHR) 
			{
			debugger;
			//alert(data);
			//$("#basic").modal('hide');
			 if(data=="notexist"){
				$("#ostad_rahnama_i").switchClass( "fa-check", "fa-times", 1000, "easeInOutQuad" );
				}
			$("#search_ostad")[0].reset();
		    $("#sample_1").DataTable().destroy();
		    show_dataTable();
		        
			},
			error: function(jqXHR, textStatus, errorThrown) 
			{
			}
		}).always($("#delete").modal('hide'));
	    e.preventDefault();	//STOP default action
		});
	</script>
	<!-- END JAVASCRIPTS -->
	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}				
	 </script>
	 <script>
	 $(document).ready(function() {
		show_dataTable();
		$("#sample_1_info").hide();
		$('#basic').on('hidden.bs.modal', function () {
			   // debugger;
			    
			    $("#search_ostad")[0].reset();
			    //Begin of reset form validation 
			    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
			    $(".input-icon .fa-check").switchClass("fa-check","fa");
			    $(".alert-danger").hide();
			    $('.form-group').removeClass('has-error');
			    $('.form-group').removeClass('has-success');
			    //End of reset form validation
			});
	 });
		var buttonText;
		var sButtonText;
		var info;
		//var	language="en";
		if(language=="en"){
			buttonText="Visibel Columns";
			sButtonText="Print";
			sButtonText2="Save";
			info="view _START_ to _END_ from _TOTAL_ items";
			sLengthMenu="View Content _MENU_";
			sZeroRecords="Not Found";
			sInfoEmpty="Empty";
			sInfoFiltered="(Filtered From _MAX_ Items)";
			sSearch="Search";
			sFirst="First";
			sPrevious="Previous";
			sNext="Next";
			sLast="Last";
			
			
		}
		else
		{
			buttonText="ستون هاي قابل نمايش";
			sButtonText="چاپ";
			sButtonText2="ذخيره";
			info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
			sLengthMenu="نمايش محتويات _MENU_";
			sZeroRecords="موردي يافت نشد";
			sInfoEmpty="تهي";
			sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
			sSearch="جستجو";
			sFirst="ابتدا";
			sPrevious="قبلي";
			sNext="بعدي";
			sLast="انتها";
			
		}
		function show_dataTable()
		{
			var dt;				
						
			    dt = $('#sample_1').DataTable({
			    	   "colVis": {
			               "buttonText": buttonText
			           },
			           "dom": 'CT<"clearfix">lfrtip',
				        "tableTools": {
				            "sRowSelect": "os",
							 "aButtons": [
				                 
								{
									
				                    "sExtends": "print",
				                    "sButtonText": sButtonText
				                },
				                
				                {
				                    "sExtends":    "collection",
				                    "sButtonText": sButtonText2,
				                    "aButtons":    [ 
														"csv", 
														"xls"
													]
				                }
				            ],
				            
							"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
				        },
			        "fnInitComplete": function(oSettings, json) {
						
						fixControlPosition();
						
		                },
			        "fnDrawCallback": function(oSettings) {
			            var trs = $("#sample_1 tr");
			            for (var i = 1; i < trs.length; i++) {

			                var rowId = ($(trs[i]).attr('id'));
			                $("#" + rowId + " td:last-child").trigger('click');

			            }
			            $('.delete_btn').on('click', function() {
			                debugger;
			                var tr = $(this).closest('tr');
			                var row = dt.row(tr);
			                $('#position1')[0].value = row.data().position1;
			                
			                jadvZar_IsNew="delete";
			                $("#delete").modal('show');
		                
			            });
			        },
			        "paging": true,
			        'bPaginate': true,
			        "pagingType": "full_numbers",
			        "processing": true,
			        "serverSide": true,
			        "bDestroy": true,
			        "bAutoWidth": false,
			        "language": {
			      		
			      	  "sProcessing": "<img src='image/ajax-loader-white.gif'>",
			            "sLengthMenu": sLengthMenu,
			            "sZeroRecords": sZeroRecords,
			            "info": info,
			            "sInfoEmpty": sInfoEmpty,
			            "sInfoFiltered": sInfoFiltered,
			            "sInfoPostFix": "",
			            "sSearch": sSearch,
			            "sUrl": "",
			            "oPaginate" : {
			                "sFirst": sFirst,
			                "sPrevious": sPrevious,
			                "sNext": sNext,
			                "sLast": sLast
	                    }
	                },
			        "sAjaxSource": "ostad_rahnama.php?action=list&cod_tarh=<?php echo $cod_tarh;?>" ,
			        "aoColumns": [
			            { "data": "position1" },
					    { "data": "name" },
		                { "data": "family" },
		                { "data": "takhasos" },
					    { "data": "delete"}
			        ]

			    });
		}
			 
	 </script>

<?php
footer_forms($admin,$seed);
?>

