<?
include("include/database-connect.phtml");
include("include/include.phtml");
//include("include/vars.inc.phtml");
//include("include/class.phpmailer.php");
//require_once("include/mailserver-statistics.phtml");
//require_once("../email/send_email_smtp.php");

//require_once('lib/nusoap.php');

header_forms();
?>
<style>
.table th,.table tr {
    background-color: rgb(255, 255, 255	);
    color: black;
	padding: 5px;
    text-align: center;
	font-weight:bold;
	cursor:pointer;
}
.table tbody > tr:hover {
    background-color: #f5f5f5 !important;
}

.table table {
    border-collapse: collapse;
    padding: 5px;
	margin:0 auto;
	border:1px solid #ddd;
    /*border-spacing:20px 10px;*/
    /*border:none;*/
}

.table tbody > tr:nth-of-type(2n+1) {
    background-color: #f9f9f9;
    color: rgb(0,0,0);
	font-weight:normal;
}

.table tbody > tr:nth-of-type(2n) {
    background-color: rgb(255, 255, 255);
    color: rgb(0,0,0);
	font-weight:normal;
}

</style>
<!-- BEGIN PAGE LEVEL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link id="select2" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css"/>
    <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css"/>
    
    <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>

    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
    <link id="toastr" rel="stylesheet" type="text/css" href="../assets/plugins/bootstrap-toastr/toastr-rtl.min.css"/>
<!-- END PAGE LEVEL STYLES -->
    
    <!--First of test with previous css  -->
    <!-- <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" /> -->
      
    <!-- End of test with previous css -->
    <!-- END PAGE LEVEL STYLES -->
<?php
$menu_id="2";
$sub_menu_id="3";
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content"> 
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h3 id="page-title" class="page-title">
                            <small> </small>پایان نامه های دانشجویان شما
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="navigator-home" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="navigator-thesis" href="ostad_payan_name.phtml">
                                    پایان نامه های دانشجویان شما
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                    
              <!-- BEGIN DATA TABLE PORTLET-->
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div id="caption-grid" class="caption">
                                    <i class="fa fa-globe"></i>پایان نامه هایی که شما استاد راهنمای آن هستید
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
									</a>
									<a href="#portlet-config" data-toggle="modal"
									class="fa fa-info-circle" title="راهنما"
									style="color: white">
									</a>
                                </div>
                            </div>
                             <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			                    <div class="modal-dialog">
			                        <div class="modal-content">
			                            <div class="modal-header">
			                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
			                                <h4 class="modal-title">راهنما</h4>
			                            </div>
			                            <div class="modal-body">
			                                در حال تکمیل می باشد.
			                            </div>
			                            <div class="modal-footer">
			                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
			                            </div>
			                        </div>
			                        <!-- /.modal-content -->
			                    </div>
		                    <!-- /.modal-dialog -->
		                    </div>
                            <div class="portlet-body">
	                           <!--  <div class="col-md-3">
									<div class="form-group">
										 
									</div>
				                </div>   -->
				                	<!-- BEGIN FORM-->
												
													<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
											                     <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
											                            <h4 id="modal_title_letter" class="modal-title">
											                                <i class="fa fa-file-o"></i>
											                                 لیست نامه ها
											                             </h4>
											                    </div>
											                   <div class="modal-body">
											                   <!-- BEGIN FORM-->
														       <form id="send_letter" method="post" action="ostad_letter_to_mojri_body.php?action=send_email" class="form-horizontal table">
							                                    
																		   
																	<!-- letter_to_mojri_body(); -->
							                                  
							                                   </div>
							                                <!-- /.modal-content -->
							                                  <div class="modal-footer">
								                                       <button id="save" type="submit"  class="btn green">ذخیره</button>
																	   <button id="cancel" type="button" class="btn red" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              
							                                      </div>
							                                </form>
							                                <!-- End FORM-->
							                                
							                                </div>
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      <div class="modal fade" id="modal_create_tarh" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
											                     <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
											                            <h4 id="modal_title_change_thesis" class="modal-title">
											                                <i class="fa fa-file-o"></i>
											                                <?php echo $cod_tarh;?>تبدیل پایان نامه به طرح
											                             </h4>
											                    </div>
											                   <div class="modal-body">
											             <!-- BEGIN change_status_tarh FORM -->
							                                <? echo "<form id=\"change_status\" name=\"change_status\" method=\"post\" action=\"ostad_letter_to_mojri_body.php?action=change_status&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" class=\"form-horizontal\">"; ?>
							                                    
																		   
																	
							                                  
							                                   </div>
							                                <!-- /.modal-content -->
							                                  <div class="modal-footer">
								                                       <button id="save0" type="submit"  class="btn green">ذخیره</button>
																	   <button id="cancel0" type="button" class="btn red" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              
							                                      </div>
							                                </form>
							                                <!-- End change_status_tarh FORM-->
							                                
							                                </div>
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      
						                         <div class="modal fade" id="modal_versions" tabindex="-1" role="basic" aria-hidden="true">
						                            <div class="modal-dialog modal-wide">
						                                <div class="modal-content">
						                                  <div class="modal-header bg-blue">
										                     <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
										                            <h4 id="modal_title_version" class="modal-title">
										                                <i class="fa fa-file-o"></i>
										                                <?php echo $cod_tarh;?>ویرایشهای مربوط به طرح با کد
										                             </h4>
										                    </div>
										                   <div class="modal-body table" id="versions">
										             	
						                                  
						                                   </div>
						                                <!-- /.modal-content -->
						                                
						                                </div>
						                            </div>
						                            <!-- /.modal-dialog -->
						                      </div>
						                      <div class="modal fade" id="confirm" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog modal-wide">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
											                     <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
											                            <h4 class="modal-title">
											                                <i id="confirmation" class="fa fa-file-o"></i>
											                                <?php echo $cod_tarh;?>تایید
											                             </h4>
											                    </div>
											                   <div class="modal-body">
											             <!-- BEGIN change_status_tarh FORM -->
							                                <? echo "<form id=\"professor_confirm\" method=\"post\" action=\"ostad_payan_name_sabt.php?admin=$admin&seed=$seed&action=sabt_tarh\">"; ?>
							                                    
															<input type="hidden" id="cod_tarh" name="cod_tarh">		   
																	
							                                  
							                                   </div>
							                                <!-- /.modal-content -->
							                                  <div class="modal-footer">
								                                       <button id="confirmation1" type="submit"  class="btn green">تایید</button>
																	   <button id="cancel1" type="button" class="btn red" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              
							                                      </div>
							                                </form>
							                                <!-- End change_status_tarh FORM-->
							                                
							                                </div>
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							                      
							    <div class="col-md-3">
									 <div class="form-group">
										<label id="type_label" class="control-label col-md-4">نوع :</label>
										<div class="col-md-8">
											<select id="ostad_type" class="select2_category form-control" data-placeholder="Choose a Category" tabindex="1">
												<option id="option" value="-1">همه</option>
												<option id="option0" value="0">استاد راهنما هستید</option>
												<option id="option1" value="1">استاد مشاور هستید</option>
											</select>												
										</div>
									</div>
				                </div>  
				                <div class="table-responsive">
		                                <table class="table table-striped table-bordered table-hover" id="sample_1">
		                                    <thead>
		                                        <tr>
		                                            <th id="th1">
		                                                کد طرح
		                                            </th>
		                                            <th id="th2">
		                                                 عنوان فارسی
		                                            </th>
		                                            <th id="th3">
		                                                 کد دانشجویی
		                                            </th>
		                                            <th id="th4">
		                                                 نام ونام خانوادگی دانشجویی
		                                            </th>
		                                            <th id="th5">
		                                                  مقطع تحصیلی
		                                            </th>
		                                            <th id="th6">
		                                                 دانشکده / مرکز
		                                            </th>
		                                            <th id="th7">
		                                                نوع استاد 
		                                            </th>
		                                            <th id="th8">
		                                                تاریخ ارسال
		                                            </th>
		                                             <th id="th9">
		                                                تایید استاد
		                                            </th>
		                                             <th id="th10">
		                                                وضعیت پایان نامه از لحاظ اخلاقی
		                                            </th>
		                                             <th id="th11">
		                                                 کارشناس مربوطه
		                                            </th>
		                                             <th id="th12">
		                                                 جزئیات
		                                            </th>
		                                        </tr>
		                                    </thead>
		                                   <tbody>
		                                   
		                                   </tbody>
		                                </table>
                                </div>
                             </div>
                        </div>
                        <!-- END DATA TABLE PORTLET-->      
                       
</div>
</div>
<!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->
<script>
if(language=="en"){
	
	debugger;
	document.getElementById("page-title").textContent="List of your students` thesis";;
	document.getElementById("navigator-home").textContent="Home";
	document.getElementById("navigator-thesis").textContent="Your students` thesis";
	document.getElementById("th1").textContent="Research Code";
	document.getElementById("th2").textContent="Title";
	document.getElementById("th3").textContent="Student Number";
	document.getElementById("th4").textContent="Name of Student";
	document.getElementById("th5").textContent="Level of study";
	document.getElementById("th6").textContent="School/Research center";
	document.getElementById("th7").textContent="Master Type";
	document.getElementById("th8").textContent="Submission Date";
	document.getElementById("th9").textContent="Approval status";
	document.getElementById("th10").textContent="Ethical committee approval status";
	document.getElementById("th11").textContent="Relevant Expert";
	document.getElementById("th12").textContent="Details";
	document.getElementById("fa-angle").className="fa fa-angle-right";
	document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
	document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
	document.getElementById("caption-grid").innerHTML="<i id='caption-grid' class='fa fa-globe'></i> All Projects";
	document.getElementById("select2").href="../assets/plugins/select2/select2-rtl.css";
	document.getElementById("type_label").textContent="Type of Involvement";
	document.getElementById("option").textContent="All";
	document.getElementById("option0").textContent="as a supervisor";
	document.getElementById("option1").textContent="as an advisor";
	document.getElementById("cancel").textContent="Cancel";
	document.getElementById("save").textContent="Save";
	document.getElementById("confirmation").textContent="confirmation";
	document.getElementById("confirmation1").textContent="confirmation";
	document.getElementById("cancel1").textContent="Cancel";
	document.getElementById("save0").textContent="Save";
	document.getElementById("cancel0").textContent="Cancel";
	//document.getElementById("editing").textContent="Editing of Research";
	//document.getElementById("change").textContent="Change Thesis to Research";	
}
</script>
<?php 
include("../include/primary_js.phtml");
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="../assets/scripts/core/app.js"></script>-->
    <!--<script src="../assets/scripts/custom/table-advanced.js"></script>-->
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
            // initiate layout and plugins
        	//var detailRows = [];
            var dt;
        	debugger;
           show_dataTable();
         //   TableAdvanced.init();       	 
        });
        function letter_to_mojri_body(data){
       	 $.ajax({
 	        url: "letter_to_mojri_body.php?action=send_letter",
 	        type: "POST",
 	        data: { cod_tarh: data},
 	        async: false,
 	        dataType: "html",
 	        success: function(result) {
 	           $("#send_letter").html(result);
 	           if(language=="en")
 	           		$("#modal_title_letter").html("<i class='fa fa-file-o'></i>Letters list with code"+data);
 	           else
  	        	  	$("#modal_title_letter").html("<i class='fa fa-file-o'></i>لیست نامه های طرح با کد"+data);
 	           $("#basic").modal("show");

 	        }
 	    });
        }

        function create_tarh(data){
         	 $.ajax({
   	        url: "letter_to_mojri_body.php?action=change_status",
   	        type: "POST",
   	        data: { cod_tarh: data},
   	        async: false,
   	        dataType: "html",
   	        success: function(result) {
   	           $("#change_status").html(result);
   	           $("#modal_title_change_thesis").html("<i class='fa fa-file-o'></i> Change thesis to research with code"+data);
   	           $("#modal_create_tarh").modal("show");

   	        }
   	    });
          }

        function versions(data){
       	 $.ajax({
 	        url: "letter_to_mojri_body.php?action=versions",
 	        type: "POST",
 	        data: { cod_tarh: data},
 	        async: false,
 	        dataType: "html",
 	        success: function(result) {
 	           $("#versions").html(result);
 	           if(language=="en")
 	           		$("#modal_title_version").html("<i class='fa fa-file-o'></i>Editing of research with code"+data);
 	           else
  	        	  $("#modal_title_version").html("<i class='fa fa-file-o'></i>ویرایشهای مربوط به طرح با کد"+data);
 	 	           
 	           $("#modal_versions").modal("show");

 	        }
 	    });
        }
    </script>
    
    <script>
    function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
function format(d) {
    var r;
    $.ajax({
        url: "ostad_payan_name_details.php",
        type: "POST",
        data: { cod_tarh: d.cod_tarh },
        async: false,
        dataType: "html",
        success: function(result) {
            r = result;

        }
    });
    return r;
}
$("#professor_confirm").submit(function(e){

	debugger;

var formURL;
var postData = $(this).serializeArray();	
	 formURL = $(this).attr("action");
	 debugger;
	 
    $(".green").attr("disabled","disabled");
	$.ajax(
	{
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			     //alert(data);
			    //debugger;
				if(data=="success")
				{
					toastr.options.timeOut="5000";
			        toastr.options.positionClass="toast-top-right";
					toastr.success('تایید با موفقیت انجام شد');
				}
				$("#confirm").modal('hide');
				//$("#")[0].reset();
			
// 	           $("#sample_1").DataTable().destroy();
	    		
// 	           show_dataTable(); 
			    //var url_ostad_payan_name=$('#ostad_type :selected').val();
				dt.ajax.url("ostad_payan_name_sabt.php?action=select&cod_tarh=<?php echo $cod_tarh;?>&ostad_type=" + $('#ostad_type :selected').val());
		        dt.ajax.reload();
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			alert("error");
		}
	}).always($(".green").removeAttr("disabled","disabled"));

    e.preventDefault();	//STOP default action 
});
$("#send_letter").submit(function(e){

	debugger;
	//alert("hi");
    // for more info visit the official plugin documentation: 
        // http://docs.jquery.com/Plugins/Validation
         debugger;
        var form2 = $('#send_letter');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);
       /* jQuery.validator.addMethod("test", function(value, element) {
            return this.optional(element) || /^09[123]\d{8}/.test(value);
        }, "Your entered data is not phone number");*/
        form2.validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block', // default input error message class
            focusInvalid: false, // do not focus the last invalid input
            ignore: "",
            rules:{
            	letter_subject:{
  	                  required:true,
  	                  //test:true,
    	              //rangelength:[11,11]
  	                  },
  	              },
	  	    messages:{
	  	    	letter_subject:{
  	                  required:"پر کردن این فیلد الزامی می باشد",
  	            	  },
		  	      },
  	              

            invalidHandler: function (event, validator) { //display error alert on form submit              
                    success2.hide();
                    error2.show();
                    App.scrollTo(error2, -200);
            },

            errorPlacement: function (error, element) { // render error placement for each input type
                var icon = $(element).parent('.input-icon').children('i');
                icon.removeClass('fa-check').addClass("fa-warning");  
                icon.attr("data-original-title", error.text()).tooltip();
            },

            highlight: function (element) { // hightlight error inputs
                $(element)
                    .closest('.form-group').addClass('has-error'); // set error class to the control group   
            },

            unhighlight: function (element) { // revert the change done by hightlight
                
            },

            success: function (label, element) {
                var icon = $(element).parent('.input-icon').children('i');
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                icon.removeClass("fa-warning").addClass("fa-check");
            },

            submitHandler: function (form) {
                success2.show();
                error2.hide();
            }
        });

var formURL;
var postData = $(this).serializeArray();	
	 formURL = $(this).attr("action");
	 debugger;
if($("#send_letter").valid())
{
    $(".green").attr("disabled","disabled");
	$.ajax(
	{
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			     //alert(data);
			    debugger;
				if(data=="sent")
				{
					toastr.options.timeOut="5000";
			        toastr.options.positionClass="toast-top-right";
					toastr.success('پاسخ به نامه مذکور ارسال شد');
				}
				$("#basic").modal('hide');
				$("#send_letter")[0].reset();
			
// 	           $("#sample_1").DataTable().destroy();
	    		
// 	           show_dataTable(); 
				//var url_ostad_payan_name=$('#ostad_type :selected').val();
				dt.ajax.url("ostad_payan_name_sabt.php?action=select&cod_tarh=<?php echo $cod_tarh;?>&ostad_type=" + $('#ostad_type :selected').val());
		        dt.ajax.reload();
	           
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			alert("error");
		}
	}).always($(".green").removeAttr("disabled","disabled"));

	}
    e.preventDefault();	//STOP default action 
});

$("#change_status").submit(function(e){
	//alert("hi");
         debugger;
var formURL;
var postData = $(this).serializeArray();	
	 formURL = $(this).attr("action");
	 debugger;
    $(".green").attr("disabled","disabled");
	$.ajax(
	{
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
// 			     alert(data);
			    //debugger;
				if(data=="پایان نامه یکبار به طرح تبدیل شده")
				{
					toastr.options.timeOut="5000";
			        toastr.options.positionClass="toast-top-right";
					toastr.warning('پایان نامه یکبار به طرح تبدیل شده');
				}
				if(data=="sent")
				{
					toastr.options.timeOut="5000";
			        toastr.options.positionClass="toast-top-right";
					toastr.success('پاسخ به نامه مذکور ارسال شد');
				}
				$("#modal_create_tarh").modal('hide');
				$("#change_status")[0].reset();
			
// 	           $("#sample_1").DataTable().destroy();
	    		
// 	           show_dataTable(); 
				//var url_ostad_payan_name=$('#ostad_type :selected').val();
				dt.ajax.url("ostad_payan_name_sabt.php?action=select&cod_tarh=<?php echo $cod_tarh;?>&ostad_type=" + $('#ostad_type :selected').val());
		        dt.ajax.reload();
	           
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			alert("error");
		}
	}).always($(".green").removeAttr("disabled","disabled"));
    e.preventDefault();	//STOP default action 
});
var buttonText;
var sButtonText;
var info;
//var	language="en";
if(language=="en"){
	buttonText="Visibel Columns";
	sButtonText="Print";
	sButtonText2="Save";
	info="view _START_ to _END_ from _TOTAL_ items";
	sLengthMenu="View Content _MENU_";
	sZeroRecords="Not Found";
	sInfoEmpty="Empty";
	sInfoFiltered="(Filtered From _MAX_ Items)";
	sSearch="Search";
	sFirst="First";
	sPrevious="Previous";
	sNext="Next";
	sLast="Last";
	captiontxt="your students thesis";
	captiontxt1="Theses that you are";
	
	
}
else
{
	buttonText="ستون های قابل نمایش";
	sButtonText="چاپ";
	sButtonText2="ذخیره";
	info="نمایش _START_ تا _END_ از مجموع _TOTAL_ مورد";
	sLengthMenu="نمایش محتویات _MENU_";
	sZeroRecords="موردی یافت نشد";
	sInfoEmpty="تهی";
	sInfoFiltered="(فیلتر شده از مجموع _MAX_ مورد)";
	sSearch="جستجو";
	sFirst="ابتدا";
	sPrevious="قبلی";
	sNext="بعدی";
	sLast="انتها";
	captiontxt="پایان نامه های دانشجویان شما";
	captiontxt1="پایان نامه هایی که شما";
	
	
}

$(document).ready(function() {
//     var detailRows = [];
//     var dt;
	debugger;
//    show_dataTable();
   $('#ostad_type').change(function() {
		debugger;
		if($('#ostad_type :selected').val()=="-1")
			$(".caption").text(captiontxt);
		else
			$(".caption").text(captiontxt1+" "+$('#ostad_type :selected').text());
// 	    $("#sample_1").DataTable().destroy();
// 	    show_dataTable();
		//var url_ostad_payan_name=$('#ostad_type :selected').val();
		dt.ajax.url("ostad_payan_name_sabt.php?action=select&cod_tarh=<?php echo $cod_tarh;?>&ostad_type=" + $('#ostad_type :selected').val());
        dt.ajax.reload();
   });

});
function show_dataTable(){
 	 var detailRows = [];
//      var dt;
	 dt = $('#sample_1').DataTable({
	  	   "colVis": {
	           "buttonText": buttonText
	       },
					    				"dom": 'CT<"clearfix">lfrtip',
					    				"tableTools": {
					    					"sRowSelect": "os",
					    					 "aButtons": [
					    						{
					    							"sExtends": "print",
					    							"sButtonText": sButtonText
					    						},
					    						
					    						{
					    							"sExtends":    "collection",
					    							"sButtonText": sButtonText2,
					    							"aButtons":    [ 
					    												"csv", 
					    												"xls"
					    											]
					    						}
					    					],
					    					
					    					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
					    				},
					                "fnInitComplete": function(oSettings, json) {
					                	
									fixControlPosition();
									$(".dataTable > thead > tr > th.sorting, .dataTable > thead > tr > th.sorting_asc, .dataTable > thead > tr > th.sorting_desc").css("padding-right","8px");
									
					                },
	        "fnDrawCallback": function(oSettings) {
	            var trs = $("#sample_1 tr");
	            for (var i = 1; i < trs.length; i++) {

	                var rowId = ($(trs[i]).attr('id'));
	                $("#" + rowId + " td:last-child").trigger('click');

	            }
	            $('.row-details').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                var idx = $.inArray(tr.attr('id'), detailRows);

	                if (row.child.isShown()) {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-open');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-close');
	                
	                    row.child.hide();

	                    // Remove from the 'open' array
	                    detailRows.splice(idx, 1);
	                } else {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-close');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-open');
	                    
	                
	                    row.child(format(row.data())).show();

	                    // Add to the 'open' array
	                    if (idx === -1) {
	                        detailRows.push(tr.attr('id'));
	                    }
	                }
	            });
	            $('.confirm_btn').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                $('#cod_tarh')[0].value = row.data().cod_tarh;
                
	            });
	        },
	        
	        "paging": true,
	        'bPaginate': true,
	        "pagingType": "full_numbers",
	        "processing": true,
	        "serverSide": true,
	        "bDestroy": true,
	        "bAutoWidth": false,
	        "language": {
			
	            "sProcessing": "<img src='image/ajax-loader-white.gif'>",
	            "sLengthMenu": sLengthMenu,
	            "sZeroRecords": sZeroRecords,
	            "info": info,
	            "sInfoEmpty": sInfoEmpty,
	            "sInfoFiltered": sInfoFiltered,
	            "sInfoPostFix": "",
	            "sSearch": sSearch,
	            "sUrl": "",
	            "oPaginate" : {
	                "sFirst": sFirst,
	                "sPrevious": sPrevious,
	                "sNext": sNext,
	                "sLast": sLast
	            }
	        },
	        "sAjaxSource": "ostad_payan_name_sabt.php?cod_tarh=<?php echo $cod_tarh;?>&action=select&ostad_type=" + $('#ostad_type :selected').val(),
	        "aoColumns": [
				{ "data": "cod_tarh"},
	            { "data": "tarh_title_farsi" },
	            { "data": "daneshjo_no" },
	            { "data": "fullname" },
	            { "data": "maghtah" },
	            { "data": "daneshkade" },
	            { "data": "type_ostad" },
	            { "data": "farsistartdate" },
	            { "data": "accepttarh" },
	            { "data": "payanname_akhlagh_status" },
	            { "data": "name_family_sender" },
	            { "data": "details", "sClass": "row-details row-details-close", "bSortable": false} 
	        ]

	    });
}
$('#basic').on('hidden.bs.modal', function () {
	   // debugger;
	    $("#send_letter")[0].reset();
	    //Begin of reset form validation 
	    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
	    $(".input-icon .fa-check").switchClass("fa-check","fa");
	    $(".alert-danger").hide();
	    $('.form-group').removeClass('has-error');
	    $('.form-group').removeClass('has-success');
	    //End of reset form validation
	});

$('#modal_create_tarh').on('hidden.bs.modal', function () {
	   // debugger;
	   // $("#change_status")[0].reset();
	});
</script>
    
<?php
footer_forms($admin,$seed);
?>

