<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms();
?>
<!-- BEGIN PAGE LEVEL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css"/>
    <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css"/>
    
    <link rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>

    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
    <link href="../assets/plugins/persian-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../assets/plugins/bootstrap-toastr/toastr-rtl.min.css"/>
<!-- END PAGE LEVEL STYLES -->
    
    <!--First of test with previous css  -->
    <!-- <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" /> -->
      
    <!-- End of test with previous css -->
    <!-- END PAGE LEVEL STYLES -->
<?php
$menu_id="2";
$sub_menu_id="2";
include("include/new_menu.php");

 $query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";
 $result=mysql_query($query) or die("Error");
 if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	$tarh_name=$row_fetched["tarh_title_farsi"];
 }

 $query="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
 $result=mysql_query($query) or die("Error");
 $exists=0;
 if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	$mojri=$row_fetched["mojri_code"];
 	$heiat_elmi=$row_fetched["heiat_elmi"];
 	$start_time=$row_fetched["start_time"];
 	$pish_pardakht=$row_fetched["pish_pardakht"];
 	$payanname=$row_fetched["payanname"];
 	$nazerin=$row_fetched["nazerin"];
 	$unnazerin=$row_fetched["unnazerin"];
	$hesab=$row_fetched["hesab"];
    $mobile=$row_fetched["mobile"];
	$bank_name=$row_fetched["bank_name"];
	$melli_cod=$row_fetched["melli_cod"];
	$shaba_cod=$row_fetched["shaba_cod"];
	$time_month=$row_fetched["time_month"];
    $exists=1; 	
 } 	
 else
 {
 	$bank_name="";
 	$unnazerin="";
 	$payanname="";
 	$mojri="";
 	$heiat_elmi="";
 	$start_time="";
 	$pish_pardakht="";
 	$nazerin="";
	$hesab='';
    $mobile='';

 
 }
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content"> 
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h4 class="page-title"> 
                            <small>مقالات منتج از اين طرح : <?php echo $tarh_name;?></small>
                        </h4>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a href="index.html">
                                    خانه
                                </a>
                                <i class="fa fa-angle-left"></i>
                            </li>
                            
                            <li>
                                <a href="tarh_list.phtml">
                                    طرح هاي ارسالي شما
                                </a>
                                <i class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a href="tarh_list.phtml?position=1">
                                    طرح هاي پايان يافته
                                </a>
                                <i class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a href="#">
                                    ارسال گزارش مقاله 
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
							<div class="row">
				<div class="col-md-12">
					<div class="portlet box blue" id="form_wizard_1">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-reorder"></i> ارسال گزارش مقاله -
								<span class="step-title">
									 مرحله 1 از 4
								</span>
							</div>
							<div class="tools hidden-xs">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
							</div>
						</div>
						<div class="portlet-body form">
							<form action="answer_question_gharardad_sabt.php?step=delete_gozaresh" class="form-horizontal" id="delete_gozaresh">
							<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control"  value="<?php echo $cod_tarh;?>">
							<input name="gozaresh_id" id="gozaresh_id" type="hidden" >
							 					<div class="modal fade " id="delete"  tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog">
							                                <div class="modal-content">
							                                    <div class="modal-header">
							                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							                                        <h4 class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                       
							                                        </h4>
							                                    </div>
							                                    <div class="modal-body">
							                                        <!-- BEGIN FORM-->
																	
																		<div class="form-body">
																			<h4 class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
																		</div>
																		<div class="form-actions fluid">
																			<div class="row">
																				<div class="col-md-6">
																					<div class="col-md-offset-3 col-md-9">
																						<button type="submit"  class="btn green">بلي</button>
																						<button type="button" class="btn red" data-dismiss="modal" ><i class="fa fa-times"></i>خير</button>
																					</div>
																				</div>
																				<div class="col-md-6">
																				</div>
																			</div>
																		</div>
																	
																	<!-- END FORM-->
							                                    </div>
							                                    
							                                </div>
							                                <!-- /.modal-content -->
							                            </div>
							                            <!-- /.modal-dialog -->
							                      </div>
							     </form>
							
							<form action="#" class="form-horizontal" id="submit_form">
							<input name="cod_tarh" id="cod_tarh" type="hidden" value="<?php echo $cod_tarh;?>">
							<input name="admin" id="admin" type="hidden" value="<?php echo $admin;?>">
							<input name="version" id="version" type="hidden" value="<?php echo $version;?>">
								<div class="form-wizard">
									<div class="form-body">
										<ul class="nav nav-pills nav-justified steps">
											<li>
												<a href="#tab1" data-toggle="tab" id="step1" class="step">
													<span class="number">
														 1
													</span>
													<span class="desc">
														<i class="fa fa-check"></i>آيين‌نامه اختصاص امتياز به نتايج طرح‌هاي تحقيقاتي    
													</span>
												</a>
											</li>
											<li>		
												<a href="#tab2" data-toggle="tab" id="step2" class="step">
													<span class="number">
														 2
													</span>
													<span class="desc">
														<i class="fa fa-check"></i> ارسال مقاله
													</span>
												</a>
											</li>
											<li>
												<a href="#tab3" data-toggle="tab" id="step3" class="step active">
													<span class="number">
														 3
													</span>
													<span class="desc">
														<i class="fa fa-check"></i> ارسال فايل مقاله
													</span>
												</a>
											</li>
											<li>
												<a href="#tab4" data-toggle="tab" id="step4" class="step">
													<span class="number">
														 4
													</span>
													<span class="desc">
														<i class="fa fa-check"></i> تکميل و ارسال
													</span>
												</a>
											</li>
										</ul>
										<div id="bar" class="progress progress-striped" role="progressbar">
											<div class="progress-bar progress-bar-success">
											</div>
										</div>
										<div class="tab-content">
											<div class="alert alert-danger display-none">
												<button class="close" data-dismiss="alert"></button>
												پر کردن تمام فيلد ها اجباري است
											</div>
											<div class="alert alert-success display-none">
												<button class="close" data-dismiss="alert"></button>
												Your form validation is successful!
											</div>
											<div class="tab-pane active" id="tab1">
												<h3 class="block">آيين‌نامه اختصاص امتياز به نتايج طرح‌هاي تحقيقاتي</h3>
												<div class="form-body">															
														<span class="help-block">با توجه به <a href="agreement/article revised1.doc">آيين‌نامه اختصاص امتياز به نتايج طرح‌هاي تحقيقاتي</a> اين طرح مشمول کدام يک از موارد زير مي باشد توضيح دهيد:</span>
														<div class="row margin-top-20">
															<div class="col-md-10">
																<div class="form-group">
																<label class="control-label col-md-4">نوآوري ، اكتشاف، اختراع ثبت شده و بومي‌سازي فناوري</label>
																	<div class="col-md-8">
								                                            <textarea id="noavari" name="noavari" class="form-control" rows="3"><? echo $ravesh_ejra; ?></textarea>
						                                            </div>
					                                            </div>
															</div>
															
															<!--/span-->
														</div>	
														<div class="row margin-top-20">
															<div class="col-md-10">
																<div class="form-group">
																<label class="control-label col-md-4">استفاده از نتايج طرح تحقيقاتي توسط مشتريان خارج از دانشگاه</label>
																	<div class="col-md-8">
								                                            <textarea id="natayej_tarh_kharej_daneshgah" name="natayej_tarh_kharej_daneshgah" class="form-control" rows="3"><? echo $ravesh_ejra; ?></textarea>
						                                            </div>
					                                            </div>
															</div>
															
															<!--/span-->
														</div>	
														<div class="row margin-top-20">
															<div class="col-md-10">
																<div class="form-group">
																<label class="control-label col-md-4">توليد در مقياس انبوه شده و يا در صنايع دارويي، غذايي، تجهيزات پزشكي و مواد شوينده، آرايشي و بهداشتي</label>
																	<div class="col-md-8">
								                                            <textarea id="tolid" name="tolid" class="form-control" rows="3"><? echo $ravesh_ejra; ?></textarea>
						                                            </div>
					                                            </div>
															</div>
															
															<!--/span-->
														</div>	
														<div class="row margin-top-20">
															<div class="col-md-10">
																<div class="form-group">
																<label class="control-label col-md-4">استفاده از نتايج طرح در مديريت خدمات بهداشتي، درماني، آموزشي و پژوهشي يا در جهت بهبود شيوه‌هاي زندگي مردم</label>
																	<div class="col-md-8">
								                                            <textarea id="natayej_tarh_dar_modiriyat" name="natayej_tarh_dar_modiriyat" class="form-control" rows="3"><? echo $ravesh_ejra; ?></textarea>
						                                            </div>
					                                            </div>
															</div>
															
															<!--/span-->
														</div>							
												</div>					
											</div>
											<div class="tab-pane" id="tab2">
													<h3 class="block">ارسال مقاله</h3>
													<div class="form-body">
														 <div class="row">
																		<div class="col-md-6">
																			<div class="form-group">
																				<label class="control-label col-md-3">عنوان مقاله*</label>
																				<div class="col-md-6">
																					<input id="maghale_title" name="maghale_title" type="text" class="form-control" placeholder="" value="<? echo $kalame_1; ?>">
																					
																				</div>
																			</div>
																			
																		</div>	
																		<div class="col-md-6">
																			<div class="form-group">
																				<label class="control-label col-md-3">نام مجله*</label>
																				<div class="col-md-6">
																					<input id="journal_name" name="journal_name" type="text" class="form-control" placeholder="" value="<? echo $kalame_1; ?>">
																					
																				</div>
																			</div>
																			
																		</div>									
															</div>		
															<div class="row">
																		  <div class="col-md-6">
																				<div class="form-group">
																					<label class="control-label col-md-3">ISSN*</label>
																					<div class="col-md-6">
																						<input id="issn" name="issn" type="text" class="form-control" placeholder="" value="<? echo $kalame_1; ?>">
																					</div>
																				</div>
																			</div>
																			<div class="col-md-6">
																				<div class="form-group">
																					<label class="control-label col-md-3">جايگاه نويسنده*</label>
																					<div class="col-md-6">
																						 <div class="radio-list">
																						 
										                                                    <label>
										                                                        <input type="radio" id="outer_level" name="outer_level" value="1" data-title="اول يا مسئول" ></input>اول يا مسئول
										                                                    </label>
										                                                
										                                                    <label>
										                                                        <input type="radio" id="outer_level" name="outer_level" value="0"  data-title="ساير" > </input> ساير
										                                                    </label>											                                                    
										                                                </div>
																					</div>
																				</div>
																			</div>									
															</div>	
															<div class="row">
																		  
																			<div class="col-md-6">
																				<div class="form-group">
																					<label class="control-label col-md-3">وضعيت مقاله از نظر وابستگي به دانشگاه علوم پزشکي تهران *</label>
																					<div class="col-md-6">
																						 <div class="radio-list">
																						 
										                                                    <label>
										                                                        <input type="radio" id="affiliation" name="affiliation" value="0" data-title="دارد" ></input> دارد
										                                                    </label>
										                                                
										                                                    <label>
										                                                        <input type="radio" id="affiliation" name="affiliation" value="1"  data-title="ندارد" > </input> ندارد
										                                                    </label>											                                                    
										                                                </div>
																					</div>
																				</div>
																			</div>	
																			<div class="col-md-6">
																			<div class="form-group">
																				<label class="control-label col-md-3">سال شمسي انتشار*</label>
																				<div class="col-md-6">
																					<input id="year_publish_shamsi" name="year_publish_shamsi" type="text" class="form-control" placeholder="">
																					
																				</div>
																			</div>
																			
																		</div>									
															</div>	
															<div class="row">
																		  			
																			<div class="col-md-6">
																				<div class="form-group">
																					<label class="control-label col-md-3">سال ميلادي انتشار*</label>
																					<div class="col-md-6">
																						<input id="year_publish_milady" name="year_publish_milady" type="text" class="form-control" placeholder="">
																						
																					</div>
																				</div>
																		    </div>	
																		    <div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">indexing*</label>
																						<div class="col-md-6">
																							<select id="indexing" name="indexing" class="form-control" data-placeholder="?? ???? ???? ?????? ????" tabindex="1">
																								<option value="">انتخاب کنيد</option>
																							    <option  value="2">ايندکس نشده</option>
																			    				<option  value="3">ISI</option>
																			    				<option  value="4">pubmed</option>
																			    				<option  value="5">scopus</option>
																			    				<option  value="6">علمي و پژوهشي</option>																							        
																							</select>
																						</div>
																					</div>
																				</div>									
															</div>
															<div class="row">
																		    <div class="col-md-6">
																					<div class="form-group">
																						<label class="control-label col-md-3">نوع مقاله*</label>
																						<div class="col-md-6">
																							<select id="maghale_type" name="maghale_type" class="form-control" data-placeholder="?? ???? ???? ?????? ????" tabindex="1">
																								<option value="">انتخاب کنيد</option>
																							    <option  value="2">Brief Report</option>
																			    				<option  value="3">Ccase Report</option>
																			    				<option  value="4">Editorial</option>
																			    				<option  value="5">Image Article</option>
																			    				<option  value="6">Letter to Editor</option>
																			    				<option  value="6">Orginal</option>		
																			    				<option  value="6">Research letter</option>		
																			    				<option  value="6">Review</option>		
																			    				<option  value="6">Short Communication</option>																	        
																							</select>
																						</div>
																					</div>
																				</div>									
															</div>
														 <div class="form-actions fluid">
															<div class="col-md-offset-3 col-md-9">
																<button id="send_article_btn" type="submit" class="btn green btn-primary">ذخيره</button>																					
															</div>
														 </div>																																					
														</div>	
																
														<div id="attachment_table" class="table-responsive">
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<th class="hidden">id</th>	
																	<th>رديف</th>
																	<th>نام فايل</th>
																	<th>حذف</th>
																</thead>
														
																<tbody>
																	
																	<?php 
																	$query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='100'";
																	 
																	$result=mysql_query($query) or die("Error");
																		
																	
																	$mycount=0;
																	$dir_name="../reports/".$cod_tarh;
																	if ($dir = @opendir($dir_name))
																	{
																	$mydir = dir($dir_name);
																	//while(($file = $mydir->read()) !== false)
																	$number_of_row=1;
																	while($file = $mydir->read())
																	{
																		if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0 || strcmp(trim($file),"Thumbs.db")==0) && strcmp(substr($file,0,5),'final')==0 )
																		{
																			$myq="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='100' and submitted='1'";
																			$res=mysql_query($myq) or die("Error");
																			if(mysql_num_rows($res)>0)
																				$level_submitted='1';
																			else
																				$level_submitted='0';
																	?>
																		<tr>
																		<td><?php echo $number_of_row; ?></td>
																		<td class="hidden"><?php echo $file;?></td>
																		<td><a target="_blank" href="../reports/<?php echo $cod_tarh; ?>/<?php echo $file; ?>"><?php echo $file; ?></a></td>
																		<?php
																		if($level_submitted==0)
																		{
																			?>
																		<td><?php echo "<a class=\"btn delete_buttun\" id=\"$file\" onclick=delete_element('$file') data-toggle=\"modal\" href=\"#delete\" ><i class=\"fa fa-trash-o\" ></i></a>";?></td>
																		<?php } else{  ?>
																		<td>غير قابل حذف</td>
																		<?php }	?>
																	</tr>
																	<?php 
																			$number_of_row++;
																			}
																			
																		 }
																		closedir($dir);
																	}
																	?>
																	
																</tbody>
															</table>
														</div>
											</div>
											<div class="tab-pane" id="tab3">
													<h3 class="block">ارسال مقاله</h3>
													<div class="form-body">
														<div class="form-group">
																<p class="help-block col-md-10 text-center">
																		تعداد فايلهاي ارسالي حداکثر 12 عدد مي باشد	 
															    </p>
															    <p class="help-block col-md-10 text-center">
																		حداکثر حجم فايل 8 مگابايت مي باشد. نام فايل را انگليسي و بدون فاصله وارد کنيدفايل ارسالي بايد به فرمت Word يا PDF باشد.صرفا از فونت زر استفاده کنيد	 
															    </p>
															    <p class="help-block col-md-10 text-center">
																		فايلهاي ضميمه با نام انگليسي معتبر هستند	 
															    </p>
														</div>
														<div class="row">
																<div class="form-group">
																<label for="photo" class="control-label col-md-4">فايل ضميمه:</label>
																	<div class="col-md-3 col-md-push-1">
																		<input type="file" id="fupload" name="fupload" accept="application/msword,application/pdf,.docx">
																	</div>
															  </div>
														</div>
														 
														 <div class="form-actions fluid">
															<div class="col-md-offset-3 col-md-9">
																<button id="upload_file_btn" type="submit" class="btn green btn-primary" data-loading-text="در حال بارگذاري...">ذخيره</button>																					
															</div>
														 </div>																																					
														</div>	
																
														<div id="attachment_table" class="table-responsive">
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<th class="hidden">id</th>	
																	<th>رديف</th>
																	<th>نام فايل</th>
																	<th>حذف</th>
																</thead>
														
																<tbody>
																	
																	<?php 
																	$query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='100'";
																	 
																	$result=mysql_query($query) or die("Error");
																		
																	
																	$mycount=0;
																	$dir_name="../reports/".$cod_tarh;
																	if ($dir = @opendir($dir_name))
																	{
																	$mydir = dir($dir_name);
																	//while(($file = $mydir->read()) !== false)
																	$number_of_row=1;
																	while($file = $mydir->read())
																	{
																		if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0 || strcmp(trim($file),"Thumbs.db")==0) && strcmp(substr($file,0,5),'final')==0 )
																		{
																			$myq="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='100' and submitted='1'";
																			$res=mysql_query($myq) or die("Error");
																			if(mysql_num_rows($res)>0)
																				$level_submitted='1';
																			else
																				$level_submitted='0';
																	?>
																		<tr>
																		<td><?php echo $number_of_row; ?></td>
																		<td class="hidden"><?php echo $file;?></td>
																		<td><a target="_blank" href="../reports/<?php echo $cod_tarh; ?>/<?php echo $file; ?>"><?php echo $file; ?></a></td>
																		<?php
																		if($level_submitted==0)
																		{
																			?>
																		<td><?php echo "<a class=\"btn delete_buttun\" id=\"$file\" onclick=delete_element('$file') data-toggle=\"modal\" href=\"#delete\" ><i class=\"fa fa-trash-o\" ></i></a>";?></td>
																		<?php } else{  ?>
																		<td>غير قابل حذف</td>
																		<?php }	?>
																	</tr>
																	<?php 
																			$number_of_row++;
																			}
																			
																		 }
																		closedir($dir);
																	}
																	?>
																	
																</tbody>
															</table>
														</div>
											</div>
											<div class="tab-pane" id="tab4">
												<h3 class="block">تکميل و ارسال</h3>
												<h4 class="form-section">اطلاعات طرف قرارداد</h4>
												<div class="form-group">
													<label class="control-label col-md-3">نام و نام خانوادگي طرف قرارداد</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="mojri_name">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">کد ملي</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="melli_cod">
														</p>
													</div>
												</div>
												
												<div class="form-group">
													<label class="control-label col-md-3">شماره حساب</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="hesab">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">شماره شبا</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="shaba_cod">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">شماره موبايل</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="mobile">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">آيا فرد در استخدام دانشگاه است ؟</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="heiat_elmi">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">آيا طرح ماحصل پايان نامه است ؟</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="payanname">
														</p>
													</div>
												</div>
												<h4 class="form-section">ناظرين پيشنهادي</h4>
												<div class="form-group">
													<label class="control-label col-md-3">ناظرين پيشنهادي</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="nazerin">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">ناظرين غير پيشنهادي</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="unnazerin">
														</p>
													</div>
												</div>
												<h4 class="form-section">زمان قراداد</h4>
												<div class="form-group">
													<label class="control-label col-md-3">تاريخ شروع قراداد</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="start_time">
														</p>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">مدت قرارداد</label>
													<div class="col-md-4">
														<p class="form-control-static" data-display="time_month">
														</p>
													</div>
												</div>
												<h4 class="form-section">گزارشات</h4>
												<div id="gozaresh_tablel" class="table-responsive">
														
												</div>
											</div>
										</div>
									</div>
									<div class="form-actions fluid">
										<div class="row">
											<div class="col-md-12">
												<div class="col-md-offset-3 col-md-9">
													<a href="javascript:;" class="btn default button-previous">
														<i class="m-icon-swapleft"></i> صفحه قبل
													</a>
													<a href="javascript:;" class="btn blue button-next">
														 ادامه <i class="m-icon-swapright m-icon-white"></i>
													</a>
													<a href="javascript:;" class="btn green button-submit">
														 اتمام <i class="m-icon-swapright m-icon-white"></i>
													</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
<!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->





<?php 
include("../include/primary_js.phtml");
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
    <script src="../assets/persian-datepicker/jquery.ui.datepicker-cc.all.min.js" type="text/javascript"></script>
	
    <script type="text/javascript" src="../assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
	<script type="text/javascript" src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="../assets/scripts/core/app.js"></script>-->
    <!--<script src="../assets/scripts/custom/table-advanced.js"></script>-->
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
      	  $('#year_publish_shamsi').datepicker({
              dateFormat: 'yy/mm/dd',
              //minDate: new Date(),
              //maxDate: +45,
              showButtonPanel: true,
              //numberOfMonths: 3,
              //showAnim: "bounce"
              changeMonth: true,
              changeYear: true,
              //showOn: "button",
              //buttonImage: "images/calendar.gif",
              //buttonImageOnly: true,
              //buttonText: "انتخاب تاريخ",
              altField: "#alternate",
              altFormat: "yy",
              showWeek: true,
              firstDay: 1
          });
        	$('#year_publish_milady').datepicker({
                dateFormat: 'yy/mm/dd',
                //minDate: new Date(),
                //maxDate: +45,
                showButtonPanel: true,
                //numberOfMonths: 3,
                //showAnim: "bounce"
                changeMonth: true,
                changeYear: true,
                //showOn: "button",
                //buttonImage: "images/calendar.gif",
                //buttonImageOnly: true,
                //buttonText: "انتخاب تاريخ",
                altField: "#alternate",
                altFormat: "yy",
                showWeek: true,
                firstDay: 1
            });
       	 FormWizard.init();
        });
    </script>
     <script>
     function delete_element(id) {
        
         $('#gozaresh_id')[0].value = id;
     
     };
     $("#delete_gozaresh").submit(function(e)
  	 {
			debugger;
    	 	var postData = $(this).serializeArray();
    	 	var formURL = $(this).attr("action");
			$.ajax(
			{
				data:postData,
				url : formURL,
				type: "POST",		
				success:function(data, textStatus, jqXHR) 
				{
					$("#gozaresh_table").html(data);
					$("#gozaresh_tablel").html(data);	
					$("#delete").modal('hide');	
				},
				error: function(jqXHR, textStatus, errorThrown) 
				{
				}
			});
			 e.preventDefault();	//STOP default action
  	 });
    </script>
    <script>
    var FormWizard = function () {


        return {
            //main function to initiate the module
            init: function () {
                if (!jQuery().bootstrapWizard) {
                    return;
                }

                function format(state) {
                    if (!state.id) return state.text; // optgroup
                    return "<img class='flag' src='assets/img/flags/" + state.id.toLowerCase() + ".png'/>&nbsp;&nbsp;" + state.text;
                }

                $("#country_list").select2({
                    placeholder: "Select",
                    allowClear: true,
                    formatResult: format,
                    formatSelection: format,
                    escapeMarkup: function (m) {
                        return m;
                    }
                });

                var form = $('#submit_form');
                var error = $('.alert-danger', form);
                var success = $('.alert-success', form);

                form.validate({
                    doNotHideMessage: true, //this option enables to show the error/success messages on tab switch.
                    errorElement: 'span', //default input error message container
                    errorClass: 'help-block', // default input error message class
                    focusInvalid: false, // do not focus the last invalid input
                    rules: {
                        //account
                		melli_cod: {
                            minlength: 10,
                            maxlength: 10,
                            required: true
                           
                        },
                        mobile: {
                            minlength: 11,
                            maxlength: 11,
                            required: true
                        },
                        hesab: {
                            minlength: 5,
                            required: true                       
                        },
                        heiat_elmi: {                      
                            required: true                       
                        },
                        payanname: {                      
                            required: true                       
                        },
                        //profile
                        shaba_cod: {
                            required: true
                        },
                        start_time: {
                            required: true                       
                        },
                        time_month: {
                            required: true
                        },
                        date_gozaresh: {
                            required: true
                        },
                        marhale: {
                            required: true
                        }
                       
                    },

                    

                    errorPlacement: function (error, element) { // render error placement for each input type
                        if (element.attr("name") == "gender") { // for uniform radio buttons, insert the after the given container
                            error.insertAfter("#form_gender_error");
                        } else if (element.attr("name") == "payment[]") { // for uniform radio buttons, insert the after the given container
                            error.insertAfter("#form_payment_error");
                        } else {
                            error.insertAfter(element); // for other inputs, just perform default behavior
                        }
                    },

                    invalidHandler: function (event, validator) { //display error alert on form submit   
                        success.hide();
                        error.show();
                        App.scrollTo(error, -200);
                    },

                    highlight: function (element) { // hightlight error inputs
                        $(element)
                            .closest('.form-group').removeClass('has-success').addClass('has-error'); // set error class to the control group
                    },

                    unhighlight: function (element) { // revert the change done by hightlight
                        $(element)
                            .closest('.form-group').removeClass('has-error'); // set error class to the control group
                    },

                    success: function (label) {
                        if (label.attr("for") == "gender" || label.attr("for") == "payment[]") { // for checkboxes and radio buttons, no need to show OK icon
                            label
                                .closest('.form-group').removeClass('has-error').addClass('has-success');
                            label.remove(); // remove error label here
                        } else { // display success icon for other inputs
                            label
                                .addClass('valid') // mark the current input as valid and display OK icon
                            .closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                        }
                    },

                    submitHandler: function (form) {
    					debugger;
                        success.show();
                        error.hide();
    				//	fkjfjkj
    					debugger;
    					
                        //add here some ajax code to submit your form or just call form.submit() if you want to submit the form without ajax
    					
                    }

                });

                var displayConfirm = function() {
                    $('#tab4 .form-control-static', form).each(function(){
                        var input = $('[name="'+$(this).attr("data-display")+'"]', form);
                        if (input.is(":radio")) {
                            input = $('[name="'+$(this).attr("data-display")+'"]:checked', form);
                        }
                        if (input.is(":text") || input.is("textarea")) {
                            $(this).html(input.val());
                        } else if (input.is("select")) {
                            $(this).html(input.find('option:selected').text());
                        } else if (input.is(":radio") && input.is(":checked")) {
                            $(this).html(input.attr("data-title"));
                        } else if ($(this).attr("data-display") == 'payment') {
                            var payment = [];
                            $('[name="payment[]"]').each(function(){
                                payment.push($(this).attr('data-title'));
                            });
                            $(this).html(payment.join("<br>"));
                        }
                    });
                }

                var handleTitle = function(tab, navigation, index) {
                    var total = navigation.find('li').length;
                    var current = index + 1;
                    // set wizard title
                    $('.step-title', $('#form_wizard_1')).text('مرحله ' + (index + 1) + ' از ' + total);
                    // set done steps
                    jQuery('li', $('#form_wizard_1')).removeClass("done");
                    var li_list = navigation.find('li');
                    for (var i = 0; i < index; i++) {
                        jQuery(li_list[i]).addClass("done");
                    }

                    if (current == 1) {
                        $('#form_wizard_1').find('.button-previous').hide();
                    } else {
                        $('#form_wizard_1').find('.button-previous').show();
                    }

                    if (current >= total) {
                        $('#form_wizard_1').find('.button-next').hide();
                        $('#form_wizard_1').find('.button-submit').show();
                        displayConfirm();
                    } else {
                        $('#form_wizard_1').find('.button-next').show();
                        $('#form_wizard_1').find('.button-submit').hide();
                    }
                    App.scrollTo($('.page-title'));
                }

                // default form wizard
                $('#form_wizard_1').bootstrapWizard({
                    'nextSelector': '.button-next',
                    'previousSelector': '.button-previous',
                    onTabClick: function (tab, navigation, index, clickedIndex) {
                        success.hide();
                        error.hide();
                        var step_var=tab.children().attr("id");
                        var postData = form.serializeArray();
                        if(step_var=="step4")
    					{
    						$.ajax(
    								{
    									data:postData,
    									url : "send_maghale_sabt.php?step=gozareshat",
    									type: "POST",
    									
    									success:function(data, textStatus, jqXHR) 
    									{
    									$("#gozaresh_tablel").html(data);
    									},
    									error: function(jqXHR, textStatus, errorThrown) 
    									{
    									}
    								});
    					}
                        else if (step_var!="step3" && form.valid() == false) {
                            return false;
                        }
                        handleTitle(tab, navigation, clickedIndex);
                    },
                    onNext: function (tab, navigation, index) {
                        success.hide();
                        error.hide();
    					debugger;
    					var postData = form.serializeArray();
    					var step_var=tab.children().attr("id");
    					if(step_var=="step3")
    					{
    						$.ajax(
    								{
    									data:postData,
    									url : "send_maghale_sabt.php?step=gozareshat",
    									type: "POST",
    									
    									success:function(data, textStatus, jqXHR) 
    									{
    									$("#gozaresh_tablel").html(data);
    									},
    									error: function(jqXHR, textStatus, errorThrown) 
    									{
    									}
    								});
    					}
    					else
    					{
    	                    if (form.valid() == false) {
    	                        return false;
    	                    }
    						else
    						{							
    								$.ajax(
    								{
    									data:postData,
    									url : "send_maghale_sabt.php?step="+step_var,
    									type: "POST",
    									
    									success:function(data, textStatus, jqXHR) 
    									{
    										alert(data);
    									},
    									error: function(jqXHR, textStatus, errorThrown) 
    									{
    									}
    								});
    							}
    					}

                        handleTitle(tab, navigation, index);
                    },
                    onPrevious: function (tab, navigation, index) {
                        success.hide();
                        error.hide();

                        handleTitle(tab, navigation, index);
                    },
                    onTabShow: function (tab, navigation, index) {
                        var total = navigation.find('li').length;
                        var current = index + 1;
                        var $percent = (current / total) * 100;
                        $('#form_wizard_1').find('.progress-bar').css({
                            width: $percent + '%'
                        });
    					
                    }
                });

                $('#form_wizard_1').find('.button-previous').hide();
                $('#form_wizard_1 .button-submit').click(function () {
                	var postData = form.serializeArray();
                	$.ajax(
    						{
    							data:postData,
    							url : "answer_question_gharardad_sabt.php?step=step4",
    							type: "POST",
    							
    							success:function(data, textStatus, jqXHR) 
    							{
    								toastr.options.timeOut="3000";
    						        toastr.options.positionClass="toast-top-right";
    								toastr.success('سوالات قرارداد با موفقيت ثبت شد');
    								setInterval(function(){
    										window.location.href="tarh_list.phtml";	
    									},3000);
    							},
    							error: function(jqXHR, textStatus, errorThrown) 
    							{
    							}
    						});
                }).hide();
            }

        };

    }();
    
    	$("#gozaresh_btn").on('click', function() {
        	
        	var form = $('#submit_form');
	       	 form.validate({
	             doNotHideMessage: true, //this option enables to show the error/success messages on tab switch.
	             errorElement: 'span', //default input error message container
	             errorClass: 'help-block', // default input error message class
	             focusInvalid: false, // do not focus the last invalid input
	             rules: {
	                 //account	         		
	                 marhale: {
	                     required: true
	                 },
	                 date_gozaresh: {
	                     required: true
	                 }
	                
	             },
	
	             
	
	             errorPlacement: function (error, element) { // render error placement for each input type
	                 if (element.attr("name") == "gender") { // for uniform radio buttons, insert the after the given container
	                     error.insertAfter("#form_gender_error");
	                 } else if (element.attr("name") == "payment[]") { // for uniform radio buttons, insert the after the given container
	                     error.insertAfter("#form_payment_error");
	                 } else {
	                     error.insertAfter(element); // for other inputs, just perform default behavior
	                 }
	             },
	
	             invalidHandler: function (event, validator) { //display error alert on form submit   
	                 success.hide();
	                 error.show();
	                 App.scrollTo(error, -200);
	             },
	
	             highlight: function (element) { // hightlight error inputs
	                 $(element)
	                     .closest('.form-group').removeClass('has-success').addClass('has-error'); // set error class to the control group
	             },
	
	             unhighlight: function (element) { // revert the change done by hightlight
	                 $(element)
	                     .closest('.form-group').removeClass('has-error'); // set error class to the control group
	             },
	
	             success: function (label) {
	                 if (label.attr("for") == "gender" || label.attr("for") == "payment[]") { // for checkboxes and radio buttons, no need to show OK icon
	                     label
	                         .closest('.form-group').removeClass('has-error').addClass('has-success');
	                     label.remove(); // remove error label here
	                 } else { // display success icon for other inputs
	                     label
	                         .addClass('valid') // mark the current input as valid and display OK icon
	                     .closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
	                 }
	             },
	
	             submitHandler: function (form) {
						debugger;
	                 success.show();
	                 error.hide();
	                 //add here some ajax code to submit your form or just call form.submit() if you want to submit the form without ajax
						
	             }
	
	         });
	       	 if (form.valid() == false)
		     {
                 return false;
             }
			else
			{
				var postData = form.serializeArray();
				$.ajax(
				{
					data:postData,
					url : "answer_question_gharardad_sabt.php?step=step3",
					type: "POST",
					
					success:function(data, textStatus, jqXHR) 
					{
						$("#gozaresh_table").html(data);
						$("#gozaresh_tablel").html(data);		
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
					}
				});
			}
    	});
    	
    </script>
    
    
<?php
footer_forms($admin,$seed);
?>

