<?
include("include/database-connect.phtml");
include("include/include.phtml");


header_forms($admin,$seed);
?>
<link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css" />
<link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css" />
<link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css" />
<link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
<link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
<link id="toastr" rel="stylesheet" type="text/css" href="../assets/plugins/bootstrap-toastr/toastr-rtl.min.css"/>

<style>
.modal-body p {
	text-align: center;
}
</style>
<?php
include("include/new_menu.php");
?>

<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
		<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
		<div class="modal fade" id="portlet-config" tabindex="-1"
			role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"
							aria-hidden="true"></button>
						<h4 id="modal_title1" class="modal-title">اطلاع رساني</h4>
					</div>
					<div class="modal-body">
						
                    </div>
					<div class="modal-footer">
						<button type="button" class="btn default" data-dismiss="modal">Close</button>
					</div>
				</div>
				<!-- /.modal-content -->
			</div>
			<!-- /.modal-dialog -->
		</div>
		<!-- /.modal -->
		<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

		<!-- BEGIN PAGE HEADER-->
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 id="page_title" class="page-title">
					<small></small>
                            عنوان صفحه
                        </h3>
				<ul class="page-breadcrumb breadcrumb">

					<li id="breadcrumb1">
					    <i class="fa fa-home"></i> <a href="index.html"> خانه </a>
						<i class="fa fa-angle-left"></i>
				    </li>
					<li id="breadcrumb2">
						<a href="#"> فرم ها </a> <i class="fa fa-angle-left"></i>
					</li>
					<li id="breadcrumb3"><a href="#"> فرم پژوهشيار </a></li>
				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>
		<!-- END PAGE HEADER-->
		<div class="row">
			<div class="col-md-12">
				<!--<div class="portlet box grey">
					   <div class="portlet-title">
						<div class="caption">
							<i class="fa fa-magic"></i>ويزارد
						</div>
						<div class="actions">
							<a href="#" class="btn green"> قبلي <i
								class="fa fa-arrow-right"></i>
							</a> <a href="#" class="btn green"> <i class="fa fa-arrow-left"></i>
								بعدي
							</a>
						</div>

					</div>--> 
					<div class="portlet-body">
						<div class="row">
                                    <?php  //$active_id="14"; include("include/wizard.php");?>
                                    <div class="col-md-12 col-sm-12 col-xs-12">
								<div class="portlet box green">
									<div class="portlet-title">
										<div class="caption">
											<i class="fa fa-reorder"> <span id="portlet_caption">گزارشات مرحله</span> <?php echo $marhale;?></i>
										</div>
										<div class="tools">
											<a id="portlet_config" href="#portlet-config" data-toggle="modal"
												class="fa fa-info-circle" title="اطلاع رساني"
												style="color: white"> </a>
										</div>
									</div>
									<div class="portlet-body form-horizontal">
										<!-- BEGIN FORM-->

										<div class="modal fade" id="basic" tabindex="-1" role="basic"
											aria-hidden="true">
											<div class="modal-dialog">
												<div class="modal-content">
													<div id="modal_title2" class="modal-header bg-blue">
													گزارشات
														<button type="button" id="modal-close" class="close"
															data-dismiss="modal" aria-hidden="true"></button>
													</div>
													<div class="modal-body">

														
																<!-- BEGIN FORM-->
																<!-- <form name="mojri_tarh" id="mojri_tarh_sabt" action="mojri_tarh.php?action=add_mojri&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&mojri_code=$mojri_code" method="POST" class="form-horizontal">-->	
																	<?php 
																	     echo "<form id=\"send_report_sabt\" method=\"post\" enctype=\"multipart/form-data\" action=\"send_marhale_report_sabt.php?action=sabt&cod_tarh=$cod_tarh&marhale=$marhale\" class=\"form-horizontal\">";
																     ?>
																<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control" value="<?php echo $cod_tarh;?>">
																<input id="delete_id" name="delete_id" type="hidden">
																<div class="form-body">
																	<div class="form-horizontal">
																		
																		<div class="form-group">
																			<p id="help-block1" class="help-block">
																		    	تعداد فايلهاي ارسالي حداکثر 12 عدد مي باشد
																		    </p>
																		    <p id="help-block2" class="help-block">
																				حداکثر حجم فايل 8 مگابايت مي باشد. نام فايل را انگليسي و بدون فاصله وارد کنيدفايل ارسالي بايد به فرمت Word يا PDF باشد.صرفا از فونت زر استفاده کنيد 
																		    </p>
																		    <p id="help-block3" class="help-block">
																		    فايلهاي ضميمه با نام انگليسي معتبر هستند 
																		    </p>
																		   
																				<div class="col-md-9">
																					<div class="form-group">
																						<label id="lb1" class="control-label col-md-3">توضيح</label>
																						<div class="col-md-9">
																							<input id="name_var" name="comments" type="text" class="form-control" placeholder="" tabindex="1">
																						</div>
																					</div>
																				</div>
																				<!--/span-->

																			<!--/row-->
																			<div class="col-md-12 col-md-push-5">
																			    <label id="lb2" for="photo" class="control-label">فايل ضميمه:</label>
																				<input type="file" id="fupload" name="fupload" accept="application/msword,application/pdf,.docx">
																			</div>
																	    </div>
																
																	</div>
																	<!--/row-->
																</div>
																



																<!-- END FORM-->
														
												</div>
													<div class="modal-footer">
													<button id="upload_file_btn" type="submit" class="btn green btn-primary" data-loading-text="در حال بارگذاري...">ذخيره</button>
																				<button id="cancel_btn" type="button" class="btn red"
																					data-dismiss="modal">
																					<i class="fa fa-times"></i>انصراف
																				</button>
													</div>
												</div>
												<!-- /.modal-content -->
											</div>
											<!-- /.modal-dialog -->
										</div>

										<div class="modal fade " id="delete" tabindex="-1" role="basic" aria-hidden="true">
											<div class="modal-dialog">
												<div class="modal-content">
													<div class="modal-header">
														<button type="button" class="close" data-dismiss="modal"
															aria-hidden="true"></button>
														<h4 class="modal-title">
															<i class="fa fa-file-o"></i>

														</h4>
													</div>
													<div class="modal-body">
														<!-- BEGIN FORM-->

														<div class="form-body">
															<h4 id="delete_message" class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
														</div>
														<div class="form-actions fluid">
															<div class="row">
																<div class="col-md-6">
																	<div class="col-md-offset-3 col-md-9">
																		<button id="delete_yes_btn" type="submit" class="btn green">بلي</button>
																		<button id="delete_no_btn" type="button" class="btn red" data-dismiss="modal">
																			<i class="fa fa-times"></i>خير
																		</button>
																	</div>
																</div>
																<div class="col-md-6"></div>
															</div>
														</div>

														<!-- END FORM-->
													</div>

												</div>
												<!-- /.modal-content -->
											</div>
											<!-- /.modal-dialog -->
										</div>
										</form>
										<a id="send_report_step_btn" class="btn blue btn-sm pull-left" data-toggle="modal" data-backdrop="static"
											href="#basic">ارسال گزارش مرحله <?php echo $marhale;?></a>
										<!-- END FORM-->
										<div class="table-responsive">
											<table class="table table-striped table-bordered table-hover" id="sample_1">
												<thead>
													<tr>
														<th id="th1">نام فايل</th>
														<th id="th2">توضيحات</th>
														<th id="th3">حذف</th>
														<th class="hidden">delete_id</th>
													</tr>
	
												</thead>
	
											</table>
										
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>

				<!--  </div>-->

			</div>
		</div>
		<!-- END PAGE CONTENT-->
	</div>
</div>
<!-- END CONTENT -->

<script>
if(language=="en"){																										    
debugger;
document.getElementById("page_title").innerText="Title of Research";
document.getElementById("breadcrumb1").innerHTML=" <i class='fa fa-home'></i> <a href='index.html'> Home </a><i class='fa fa-angle-right'></i>";
document.getElementById("breadcrumb2").innerHTML="<a href='#'> Forms </a> <i class='fa fa-angle-right'></i>";
document.getElementById("breadcrumb3").innerText="Research Form";
document.getElementById("portlet_caption").innerText="Reports step";
document.getElementById("portlet_config").setAttribute("title","Information");
document.getElementById("modal_title1").innerText="Information";
document.getElementById("modal_title2").innerHTML="Reports <button type='button' id='modal-close' class='close' data-dismiss='modal' aria-hidden='true'></button>";
document.getElementById("help-block1").innerText="Maximum number of attached files must be 12";
document.getElementById("help-block2").innerText="File name must be in English and without space between it's letters.The attached file format just be Pdf OR Word.Only use ZAR font inside your file";
document.getElementById("help-block3").innerText="Attached file names in english are valid";
document.getElementById("lb1").innerText="Description";
document.getElementById("lb2").innerText="Attachment file";
document.getElementById("upload_file_btn").innerText="Save";
document.getElementById("upload_file_btn").setAttribute=("data-loading-text","Loading...");
document.getElementById("cancel_btn").innerText="Cancel";
document.getElementById("delete_message").innerText="Are you sure to delete this item?";
document.getElementById("delete_yes_btn").innerText="Yes";
document.getElementById("delete_no_btn").innerText="No";
document.getElementById("send_report_step_btn").innerText="Send report step";
document.getElementById("th1").innerText="File name";
document.getElementById("th2").innerText="Description";
document.getElementById("th3").innerText="Delete";


document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
document.getElementById("toastr").href="../assets/plugins/bootstrap-toastr/toastr.min.css";
}
</script>

<?php 
include("../include/primary_js.phtml");
?>

	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
	   // initiate layout and plugins
	 //  App.init();
	   //FormSamples.init();
	   //$(".").select2();
		 //$('body').addClass(" page-sidebar-closed");
	});
	</script>
	<!-- END JAVASCRIPTS -->
	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn green btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem				
		}
	$("#send_report_sabt").submit(function(e)
			{
		//dicision for edit or add
		debugger;
				var formURL;
				//var postData = $(this).serializeArray();
				if(jadvZar_IsNew=="insert")		
					 formURL = $(this).attr("action");
				//else if(jadvZar_IsNew=="edit")		
					//formURL="upload_file_sabt.php?action=edit";
				else if(jadvZar_IsNew=="delete")		
					formURL="send_marhale_report_sabt.php?action=delete";
				 var btn = $("#upload_file_btn");
				 btn.button('loading');
				$.ajax(
				{
					url : formURL,
					data : new FormData(this),
					cache: false,
				    contentType: false,
				    processData: false,
				    type: "POST",
					success:function(data, textStatus, jqXHR) 
					{
						//alert(data);
						if(language=="en"){
							delete_message="Attachment removed";
							upload_message="Attachment uploaded";
							error_message1="error ,This file is already loaded";
							error_message2="error ,File size more than 8 megabytes or The file extension is not correct";
							error_message3="error ,Maximum number of uploaded files is 12";
							}
						else{
							delete_message="ضميمه حذف شد";
							upload_message="ضميمه با موفقيت ثبت شد";
							error_message1="خطا , چنين فايلي قبلا بارگذاري شده";
							error_message2="حجم فايل ارسالي بيش از 8 مگابايت مي باشد يا پسوند فايل صحيح نمي باشد.";
							error_message3="تعداد فايلهاي ارسالي حداکثر 12 عدد مي باشد";
							}
 						if(data=="ضميمه حذف شد")
 						{
								toastr.options.timeOut="5000";
 						        toastr.options.positionClass="toast-top-right";
 								toastr.success(delete_message);
 						}
 						if(data=="true")
 						{
 								toastr.options.timeOut="5000";
 						        toastr.options.positionClass="toast-top-right";
 								toastr.success(upload_message);
 						}
						else if(data=="-5")
						{ 
 								toastr.options.timeOut="5000";
 								toastr.options.positionClass="toast-top-right";
 								toastr.error(error_message1);
								
							}
						else if(data=="-2")
 						{
								toastr.options.timeOut="5000";
								toastr.options.positionClass="toast-top-right";
					    		toastr.error(error_message2);
 						}
					    else if(data=="false")
						{
 								toastr.options.timeOut="5000";
 								toastr.options.positionClass="toast-top-right";
			      			    toastr.error(error_message3);
 						}
					
					jadvZar_IsNew="insert";
					$("#basic").modal('hide');
					$("#delete").modal('hide');
					$("#send_report_sabt")[0].reset();
				    	//debugger;
// 				            var uniSelect = $("#uniSelect");
// 				            var temp = $("#temp");
// 				            uniSelect.appendTo(temp);
				    		
				            $("#sample_1").DataTable().destroy();
							show_dataTable();
				        
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
						alert(textStatus);
					}
				}).always(function () { 
					 btn.button('reset');
			    });
			    e.preventDefault();	//STOP default action
			    //$("#upload_file_sabt").submit(); //SUBMIT FORM
			});
				
			
	</script>
	 <script>
	 $(document).ready(function() {
		 debugger;
		    //var detailRows = [];
		show_dataTable();

	 });

		var buttonText;
		var sButtonText;
		var info;
		//var	language="en";
		if(language=="en"){
			buttonText="Visibel Columns";
			sButtonText="Print";
			sButtonText2="Save";
			info="view _START_ to _END_ from _TOTAL_ items";
			sLengthMenu="View Content _MENU_";
			sZeroRecords="Not Found";
			sInfoEmpty="Empty";
			sInfoFiltered="(Filtered From _MAX_ Items)";
			sSearch="Search";
			sFirst="First";
			sPrevious="Previous";
			sNext="Next";
			sLast="Last";
			
			
		}
		else
		{
			buttonText="ستون هاي قابل نمايش";
			sButtonText="چاپ";
			sButtonText2="ذخيره";
			info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
			sLengthMenu="نمايش محتويات _MENU_";
			sZeroRecords="موردي يافت نشد";
			sInfoEmpty="تهي";
			sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
			sSearch="جستجو";
			sFirst="ابتدا";
			sPrevious="قبلي";
			sNext="بعدي";
			sLast="انتها";
			
		}
	
	function show_dataTable()
	{
		var dt;				
					
		    dt = $('#sample_1').DataTable({
				"dom": 'CT<"clearfix">lfrtip',
		        "tableTools": {
		            "sRowSelect": "os",
					 "aButtons": [
// 		                 {
// 		                    "sExtends": "copy",
// 		                    "sButtonText": "کپي"
// 		                },
						{
		                    "sExtends": "print",
		                    "sButtonText": sButtonText
		                },
		                
		                {
		                    "sExtends":    "collection",
		                    "sButtonText": sButtonText2,
		                    "aButtons":    [ 
												"csv", 
												"xls"
											]
		                }
		            ],
		            
					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
		        },
		        "fnInitComplete": function(oSettings, json) {
			        
			        //Begin of hide some of element from data table
		        	$("#sample_1_paginate").css("display","none");	
		        	$("#sample_1_info").css("display","none");
				    $("#sample_1_length").css("display","none");
					$("#sample_1_filter").css("display","none");
					//End of hide some of element from data table
					
					fixControlPosition();
					
	                },
		        "fnDrawCallback": function(oSettings) {
		            var trs = $("#sample_1 tr");
		            for (var i = 1; i < trs.length; i++) {

		                var rowId = ($(trs[i]).attr('id'));
		                $("#" + rowId + " td:last-child").trigger('click');

		            }
		            
		           /* $('.edit_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                //var idx = $.inArray(tr.attr('id'), detailRows);
		                $('#fupload')[0].value = row.data().fupload;
		                
		                jadvZar_IsNew="edit";
		                $("#basic").modal('show');
		            });*/
		            $('.delete_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                debugger;
		                $('#delete_id')[0].value = row.data().delete_id;
		                
		                jadvZar_IsNew="delete";
		                $("#delete").modal('show');
	                
		            });
		        },
		        "colVis": {
		           "buttonText": buttonText
		       },
		        "scrollX": true,
                "paging": true,
                'bPaginate': true,
                "pagingType": "full_numbers",
                "processing": true,
                "serverSide": true,
                "bDestroy": true,
                "oLanguage": {
                    "sProcessing": "<img src='image/ajax-loader-white.gif'>",
                    "sLengthMenu": sLengthMenu,
		            "sZeroRecords": sZeroRecords,
		            "info": info,
		            "sInfoEmpty": sInfoEmpty,
		            "sInfoFiltered": sInfoFiltered,
		            "sInfoPostFix": "",
		            "sSearch": sSearch,
		            "sUrl": "",
		            "oPaginate" : {
		                "sFirst": sFirst,
		                "sPrevious": sPrevious,
		                "sNext": sNext,
		                "sLast": sLast
                    }
                },
                
		        "sAjaxSource": "send_marhale_report_sabt.php?action=select&cod_tarh=<?php echo $cod_tarh;?>&marhale=<?php echo $marhale;?>" ,
		        "aoColumns": [
		            { "data": "file" },
		            { "data": "comments" },
				    { "data": "delete" },
				    { "data": "delete_id","sClass": "hidden"}
		        ]

		    });
	}
	
		var jadvZar_IsNew="insert";

		$('#basic').on('hidden.bs.modal', function () {
		   // debugger;
		    jadvZar_IsNew="insert";
		    $("#send_report_sabt")[0].reset();
		});
		$('#delete').on('hidden.bs.modal', function () {
			   // debugger;
			    jadvZar_IsNew="insert";
			    $("#send_report_sabt")[0].reset();
			});

	 </script>

<?php
footer_forms($admin,$seed);
?>
