<?
include("include/database-connect.phtml");
include("include/include.phtml");
//include("include/vars.inc.phtml");

header_forms();
$query="select mobile from user_login where email='$admin'";
$result=mysql_query($query);
$row_fetch=mysql_fetch_array($result);
$mobile=$row_fetch["mobile"];
?>
<!-- BEGIN PAGE LEVEL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css"/>
    <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css"/>
    
    <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>

    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
<!-- END PAGE LEVEL STYLES -->
    
    <!--First of test with previous css  -->
    <!-- <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" /> -->
      
    <!-- End of test with previous css -->
    <!-- END PAGE LEVEL STYLES -->
<?php
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content"> 
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                               در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h4 id="page-title" class="page-title">
                            <i class="fa fa-mobile"></i> صندوق پيامک <?php echo "(".$mobile.")";?>
                        </h4>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="breadcrumb1" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle-left1" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="breadcrumb2" href="sms_list.phtml">
                                    <i class="fa fa-mobile"></i>  صندوق پيامک من 
                                </a>
                               
                            </li>
                            
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                    
              <!-- BEGIN DATA TABLE PORTLET-->
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div id="portlet_caption" class="caption">
                                    <i class="fa fa-globe"></i>صندوق پيامک <?php echo "(".$mobile.")";?> 
                                </div>
                                <div class="tools">
									<a href="javascript:;" class="collapse">
									</a>
									<a href="#portlet-config" data-toggle="modal"
									class="fa fa-info-circle" title="راهنما"
									style="color: white">
									</a>
								</div>
                            </div>
                            <div class="portlet-body">
	                           <!--  <div class="col-md-3">
									<div class="form-group">
										
									</div>
				                </div>   -->
												
							    <div class="col-md-3">
									 <div class="form-group">
										<label id="type_sms_lb" class="control-label col-md-4"> وضعيت پيامک:</label>
										<div id="type_sms_select" class="col-md-8">
											<select id="sms_type" class="select2_category form-control" data-placeholder="Choose a Category" tabindex="1">
												<option value="-1">همه</option>
												<option value="1">در حال انتظار</option>
												<option value="2">رسيده به گوشي</option>
												<option value="3">نرسيده به گوشي</option>
												<option value="4">کد خطا</option>
											</select>												
										</div>
									</div>
				                </div>  
                                <table class="table table-striped table-bordered table-hover" id="sample_1">
                                    <thead>
                                        <tr>
                                        	<th id="th1">
                                                 رديف
                                            </th>
                                        	<th class="hidden">
                                                massage_id
                                            </th>
                                            <th class="hidden">
                                                id
                                            </th>
                                            <th id="th2">
                                                 تاريخ
                                            </th>
                                            <th id="th3">
                                                 متن پيامک
                                            </th>
                                            <th id="th4">
                                                  موضوع
                                            </th>
                                            <th id="th5">
                                                  وضعيت
                                            </th>
                                        </tr>
                                    </thead>
                                   <tbody>
                                   
                                   </tbody>
                                </table>
                             </div>
                        </div>
                        <!-- END DATA TABLE PORTLET-->      
                       
</div>
</div>
<!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->

<script>
if(language=="en"){																										    
debugger;
document.getElementById("page-title").innerHTML="<i class='fa fa-envelope'></i> SMS list<?php echo "(".$mobile.")";?>";
document.getElementById("breadcrumb1").textContent="Home";
document.getElementById("fa-angle-left1").setAttribute("class","fa fa-angle-right");
document.getElementById("breadcrumb2").innerHTML="<i class='fa fa-envelope'></i> SMS list";
document.getElementById("portlet_caption").innerHTML="<i class='fa fa-globe'></i>SMS list";
document.getElementById("type_sms_select").innerHTML="<select id='sms_type' class='select2_category form-control' data-placeholder='Choose a Category' tabindex='1'><option value='-1'>All</option><option value='1'>Waiting</option><option value='2'>Delivered</option><option value='3'>Did not deliver</option><option value='4'>Error</option></select>";
document.getElementById("type_sms_lb").textContent="Status";
document.getElementById("th1").textContent="Number of row";
document.getElementById("th2").textContent="Date";
document.getElementById("th3").textContent="Text";
document.getElementById("th4").textContent="Subject";
document.getElementById("th5").textContent="Status";
document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
}
</script>

<?php 
include("../include/primary_js.phtml");
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="../assets/scripts/core/app.js"></script>-->
    <!--<script src="../assets/scripts/custom/table-advanced.js"></script>-->
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
            // initiate layout and plugins
            
         //   TableAdvanced.init();
        });
    </script>
    <script>
    function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
$(document).ready(function() {
  //  var detailRows = [];
   // var dt;
	debugger;
   show_dataTable();
   $('#sms_type').change(function() {
		debugger;
		if(language=="en")
			caption="All";
		else
			caption="ليست پيامک ها";
		if($('#sms_type :selected').val()=="-1")
			$(".caption").text(caption);
		else
			$(".caption").text($('#sms_type :selected').text());
	    $("#sample_1").DataTable().destroy();
	    show_dataTable();
   });

});
var buttonText;
var sButtonText;
var info;
//var	language="en";
if(language=="en"){
	buttonText="Visibel Columns";
	sButtonText="Print";
	sButtonText2="Save";
	info="view _START_ to _END_ from _TOTAL_ items";
	sLengthMenu="View Content _MENU_";
	sZeroRecords="Not Found";
	sInfoEmpty="Empty";
	sInfoFiltered="(Filtered From _MAX_ Items)";
	sSearch="Search";
	sFirst="First";
	sPrevious="Previous";
	sNext="Next";
	sLast="Last";
	
	
}
else
{
	buttonText="ستون هاي قابل نمايش";
	sButtonText="چاپ";
	sButtonText2="ذخيره";
	info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
	sLengthMenu="نمايش محتويات _MENU_";
	sZeroRecords="موردي يافت نشد";
	sInfoEmpty="تهي";
	sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
	sSearch="جستجو";
	sFirst="ابتدا";
	sPrevious="قبلي";
	sNext="بعدي";
	sLast="انتها";
	
}
function show_dataTable(){
	 var detailRows = [];
     var dt;
	 dt = $('#sample_1').DataTable({
	  	   "colVis": {
	           "buttonText": buttonText
	       },
					    				"dom": 'CT<"clearfix">lfrtip',
					    				"tableTools": {
					    					"sRowSelect": "os",
					    					 "aButtons": [
					    						{
					    							"sExtends": "print",
					    							"sButtonText": sButtonText
					    						},
					    						
					    						{
					    							"sExtends":    "collection",
					    							"sButtonText": sButtonText2,
					    							"aButtons":    [ 
					    												"csv", 
					    												"xls"
					    											]
					    						}
					    					],
					    					
					    					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
					    				},
					                "fnInitComplete": function(oSettings, json) {
									
									fixControlPosition();
									
					                },
	        "fnDrawCallback": function(oSettings) {
	            var trs = $("#sample_1 tr");
	            for (var i = 1; i < trs.length; i++) {

	                var rowId = ($(trs[i]).attr('id'));
	                $("#" + rowId + " td:last-child").trigger('click');

	            }
	            $('.row-details').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                var idx = $.inArray(tr.attr('id'), detailRows);

	                if (row.child.isShown()) {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-open');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-close');
	                
	                    row.child.hide();

	                    // Remove from the 'open' array
	                    detailRows.splice(idx, 1);
	                } else {
	                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-close');
	                	$("#"+tr.attr('id')+" td:last").addClass('row-details-open');
	                    
	                
	                    row.child(format(row.data())).show();

	                    // Add to the 'open' array
	                    if (idx === -1) {
	                        detailRows.push(tr.attr('id'));
	                    }
	                }
	            });
	            $('.reply_btn').on('click', function() {
	                debugger;
	                var tr = $(this).closest('tr');
	                var row = dt.row(tr);
	                //alert(row.data().id);
	                $('#letterno')[0].value = row.data().id;
	            });
	        },
	        
	        "paging": true,
	        'bPaginate': true,
	        "pagingType": "full_numbers",
	        "processing": true,
	        "serverSide": true,
	        "bDestroy": true,
	        "bAutoWidth": false,
	        "order": [[ 2, "desc" ]],
	        "language": {
			
	        	"sProcessing": "<img src='image/ajax-loader-white.gif'>",
	            "sLengthMenu": sLengthMenu,
	            "sZeroRecords": sZeroRecords,
	            "info": info,
	            "sInfoEmpty": sInfoEmpty,
	            "sInfoFiltered": sInfoFiltered,
	            "sInfoPostFix": "",
	            "sSearch": sSearch,
	            "sUrl": "",
	            "oPaginate" : {
	                "sFirst": sFirst,
	                "sPrevious": sPrevious,
	                "sNext": sNext,
	                "sLast": sLast
	            }
	        },
	        "sAjaxSource": "sms_list.php?mobile=<?php echo $mobile;?>&admin=<?php echo $admin;?>&cod_tarh=<?php echo $cod_tarh;?>&action=sms_list&+sms_type=" + $('#sms_type :selected').val(),
	        "aoColumns": [
				{ "data": "number_of_rows" },
				{ "data": "massage_id", "sClass": "hidden"},
				{ "data": "id", "sClass": "hidden"},
	            { "data": "date" },
	            { "data": "massage_text" },
	            { "data": "subject" },
	            { "data": "status" }, 
	        ]

	    });
}
$('#basic').on('hidden.bs.modal', function () {
	   // debugger;
	    $("#letter_reply")[0].reset();
	    //Begin of reset form validation 
	    $(".input-icon .fa-warning").switchClass("fa-warning","fa");
	    $(".input-icon .fa-check").switchClass("fa-check","fa");
	    $(".alert-danger").hide();
	    $('.form-group').removeClass('has-error');
	    $('.form-group').removeClass('has-success');
	    //End of reset form validation
	});
</script>
    
<?php
footer_forms($admin,$seed);
?>

