<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms();
?>


<!-- BEGIN PAGE LEVEL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-rtl.css"/>
    <link id="select2-metronic" rel="stylesheet" type="text/css" href="../assets/plugins/select2/select2-metronic-rtl.css"/>
    
    <link id="DT_bootstrap" rel="stylesheet" href="../assets/plugins/data-tables/DT_bootstrap_rtl.css"/>

    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
<!-- END PAGE LEVEL STYLES -->
    
    <!--First of test with previous css  -->
    <!-- <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" /> -->
      
    <!-- End of test with previous css -->
    <!-- END PAGE LEVEL STYLES -->
<?php
$menu_id="2";
$sub_menu_id="2";
include("include/new_menu.php");
?>

 <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content"> 
                
                <!-- BEGIN PAGE HEADER-->
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                        <h4 id="page-title" class="page-title">
                            
                            ليست طرح هاي تحقيقاتي شما
                        </h4>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="navigator-home" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle" class="fa fa-angle-left"></i>
                            </li>
                            
                            <li>
                                <a id="navigator-tarhlist" href="tarh_list.phtml">
                                    طرح هاي ارسالي شما
                                </a>
                            </li>
                        </ul>
                        <!-- END PAGE TITLE & BREADCRUMB-->
                    </div>
                </div>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                    
              <!-- BEGIN DATA TABLE PORTLET-->
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div id="caption-grid" class="caption">
                                    <i  class="fa fa-globe"></i>همه طرح ها
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
									</a>
									<a id="portlet_config" href="#portlet-config" data-toggle="modal"
									class="fa fa-info-circle" title="راهنما"
									style="color: white">
									</a>
                                </div>
                            </div>
                            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                    <div class="modal-dialog">
		                        <div class="modal-content">
		                            <div class="modal-header">
		                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		                                <h4 class="modal-title">راهنما</h4>
		                            </div>
		                            <div class="modal-body">
		                                در حال تکمیل می باشد.
		                            </div>
		                            <div class="modal-footer">
		                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
		                            </div>
		                        </div>
		                        <!-- /.modal-content -->
		                    </div>
		                    <!-- /.modal-dialog -->
		                    </div>
                            <div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
							                            <div class="modal-dialog ">
							                                <div class="modal-content">
							                                  <div class="modal-header bg-blue">
											                     <button type="button" id="modal-close" class="close" data-dismiss="modal" aria-hidden="true"></button>
											                            <h4 id="h4_title" class="modal-title">
											                                <i class="fa fa-file-o"></i>
											                                
											                             </h4>
											                    </div>
											                   <div class="modal-body">
											                   <!-- BEGIN FORM-->
														       <form id="modal_form" method="post" action="#" class="form-horizontal table">
							                                    
							                                    <input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control" >
							                                    <input id="unarch" name="unarch" type="hidden" class="form-control" >
														        <div class="form-body">
															    	<div id="alert-danger" class="alert alert-danger display-hide">
																			<button class="close" data-close="alert"></button>
																		    پر کردن فيلدهاي ستاره دار اجباري مي باشد.
																	</div>
																		<div class="row">
																		<div class="col-md-9 col-md-push-1">
																				<div class="form-group">
																					<label id="abc" class="control-label col-md-3">دليل آرشيو طرح</label>
																					<div class="col-md-9">
																							<textarea id="archieve_reason" name="archieve_reason" rows="5" cols="50"></textarea>
																					</div>
																				</div>
																			</div>
																		</div>
																		
																</div>
																		   
																	<!-- letter_to_mojri_body(); -->
							                                  
							                                   </div>
							                                <!-- /.modal-content -->
							                                  <div class="modal-footer">
							                                  
								                                       <button id="archieve_btn_save" type="submit"  class="btn green">ذخيره</button>
																	   <button id="archieve_btn_cancel" type="button" class="btn red" data-dismiss="modal"> <i class="fa fa-times"></i>انصراف</button>							                              
							                                      </div>
							                                </form>
							                                <!-- End FORM-->
							                                
							                                </div>
							                            </div>
							                            <!-- /.modal-dialog -->
							</div>
                            <div class="portlet-body">
	                            <div class="col-md-3" style="padding-left: 0;width: 21%;">
									<div class="form-inline">
										<label class="control-label"><span id="position-label">موقعيت طرح</span>
											
											<? 
												if(!isset($position))
													$position="-1";
											    ?>
											<select id="position" class="select2_category form-control input-small" data-placeholder="Choose a Category" tabindex="1">
											    <?php
												if(strcmp($position,"-1")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos-1" <? echo $selected;?> value="-1">همه</option>
												<? if(strcmp($position,"0")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos0" <? echo $selected;?> value="0">در حال کارشناسي</option>
												<? if(strcmp($position,"1")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos1" <? echo $selected;?> value="1">آماده به قرارداد</option>
												<? if(strcmp($position,"2")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos2" <? echo $selected;?> value="2">در حال  اجرا</option>
												<? if(strcmp($position,"3")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos3" <? echo $selected;?> value="3">پايان يافته</option>
												<? if(strcmp($position,"4")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos4" <? echo $selected;?> value="4"> پايان يافته با  کسب امتياز</option>
												<? if(strcmp($position,"5")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos5" <? echo $selected;?> value="5">بايگاني شده</option>
												<? if(strcmp($position,"6")==0)
														$selected=" selected ";
												   else
													    $selected="";    	
												?>
												<option id="pos6" <? echo $selected;?> value="6">مختومه</option>
											</select>	
										</label>											
									</div>
				                </div>  
				                
				                <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="sample_1">
                                    <thead>
                                        <tr>
                                            <th id="th1">
                                                کد طرح
                                            </th>
                                            <th id="th2">
                                                عنوان فارسي
                                            </th>
                                            <th id="th3">
                                                دانشکده / مرکز
                                            </th>
                                            <th id="th4">
                                                تاريخ ارسال
                                            </th>
                                            <th id="th5">
                                                موقعيت طرح
                                            </th>
                                            <th id="th6">
                                               ويرايش / درخواست ويرايش 
                                            </th>
                                            <th id="th7">
                                                جزييات
                                            </th>
                                        </tr>
                                    </thead>
                                   <tbody>
                                   
                                   </tbody>
                                </table>
                                </div>
                             </div>
                        </div>
                        <!-- END DATA TABLE PORTLET-->      
                       
</div>
</div>
<!-- END PAGE CONTENT-->
</div>
</div>
<!-- END CONTENT -->

<script>


////var	language="en";

if(language=="en"){
	
	debugger
	document.getElementById("page-title").textContent="List of Research Projects";;
	document.getElementById("navigator-home").textContent="Home";
	document.getElementById("navigator-tarhlist").textContent="Your Projects";
	document.getElementById("pos-1").textContent="All";
	document.getElementById("pos0").textContent="Proposals under evaluation";
	document.getElementById("pos1").textContent="Projects ready for contract";
	document.getElementById("pos2").textContent="ongoing Projects";
	document.getElementById("pos3").textContent="Finished Projects";
	document.getElementById("pos4").textContent="Finished and Scored Projects";
	document.getElementById("pos5").textContent="Archived";
	document.getElementById("pos6").textContent="Closed";
	document.getElementById("position-label").textContent="Research Status";
	//document.getElementById("position-label").innerHTML="Research Status<select id=\"position\" class=\"select2_category form-control input-small\" data-placeholder=\"Choose a Category\" tabindex=\"1\"><option value=\"-1\">All</option><option value=\"0\">Proposals under evaluation</option><option value=\"1\">Projects ready for contract</option><option value=\"2\">ongoing Projects</option><option value=\"3\">Finished Projects</option><option value=\"4\">Finished and Scored Projects </option><option value=\"5\">Archived</option><option value=\"6\">Closed</option></select>";
	document.getElementById("alert-danger").innerHTML="<button class='close' data-close='alert'></button>You have some form errors. Please check below.";
	document.getElementById("archieve_btn_save").textContent="Save";
	document.getElementById("archieve_btn_cancel").textContent="Cancel";
	document.getElementById("th1").textContent="Research Code";
	document.getElementById("th1").textContent="Research Code";
	document.getElementById("th2").textContent="Title";
	document.getElementById("th3").textContent="School / Faculty";
	document.getElementById("th4").textContent="Submission Date";
	document.getElementById("th5").textContent="Research Status";
	document.getElementById("th6").textContent="Edit / Edit Request";
	document.getElementById("th7").textContent="Details";
	document.getElementById("fa-angle").className="fa fa-angle-right";
	document.getElementById("DT_bootstrap").href="../assets/plugins/data-tables/DT_bootstrap.css";
	document.getElementById("select2-metronic").href="../assets/plugins/select2/select2-metronic.css";
	document.getElementById("caption-grid").innerHTML="<i id='caption-grid' class='fa fa-globe'></i> All Projects";
}

	</script>



<?php 
include("../include/primary_js.phtml");
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="../assets/scripts/core/app.js"></script>-->
    <!--<script src="../assets/scripts/custom/table-advanced.js"></script>-->
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        jQuery(document).ready(function () {
            // initiate layout and plugins
         //   TableAdvanced.init();,
        });
        var modal_action;
        function archive(data,unarch){

			debugger;
			$("#cod_tarh")[0].value = data;
			$("#unarch")[0].value = unarch;
			if(language=="en"){
				var cause_archive="cause of archive";
				var archive="Thesis archive";
			}
			else{
				var cause_archive="دليل آرشيو";
				var archive="آرشيو پايان نامه";
			}
			$("#abc").text(cause_archive);
			$("#h4_title").text(archive);
			modal_action="archive";
			 $("#basic").modal("show");
            
//            debugger;
//         	 $.ajax({
//   	        url: "details_tarh.php?action=archive",
//   	        type: "POST",
//   	        data: { cod_tarh: data},
//   	        async: false,
//   	        dataType: "html",
//   	        success: function(result) {
//   	           $("#archive_tarh").html(result);
//   	           $("#basic").modal("show");
//
//   	        }
//   	    });
          }
        
    </script>
    <script>
    function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem
		}
function format(d) {
    var r;
    $.ajax({
        url: "details.php?semat=mojri",
        type: "POST",
        data: { cod_tarh: d.cod_tarh },
        async: false,
        dataType: "html",
        success: function(result) {
            r = result;

        }
    });
    return r;
}
var buttonText;
var sButtonText;
var info;
//var	language="en";
if(language=="en"){
	buttonText="Visibel Columns";
	sButtonText="Print";
	sButtonText2="Save";
	info="view _START_ to _END_ from _TOTAL_ items";
	sLengthMenu="View Content _MENU_";
	sZeroRecords="Not Found";
	sInfoEmpty="Empty";
	sInfoFiltered="(Filtered From _MAX_ Items)";
	sSearch="Search";
	sFirst="First";
	sPrevious="Previous";
	sNext="Next";
	sLast="Last";
	
	
}
else
{
	buttonText="ستون هاي قابل نمايش";
	sButtonText="چاپ";
	sButtonText2="ذخيره";
	info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
	sLengthMenu="نمايش محتويات _MENU_";
	sZeroRecords="موردي يافت نشد";
	sInfoEmpty="تهي";
	sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
	sSearch="جستجو";
	sFirst="ابتدا";
	sPrevious="قبلي";
	sNext="بعدي";
	sLast="انتها";
	
}
	

$(document).ready(function() {
    var detailRows = [];
    var dt;
	
    dt = $('#sample_1').DataTable({
  	   "colVis": {
           "buttonText": buttonText
       },
				    				"dom": 'CT<"clearfix">lfrtip',
				    				"tableTools": {
				    					"sRowSelect": "os",
				    					 "aButtons": [
				    						
				    						{
				    							"sExtends": "print",
				    							"sButtonText": sButtonText
				    						},
				    						
				    						{
				    							"sExtends":    "collection",
				    							"sButtonText": sButtonText2,
				    							"aButtons":    [ 
				    												"csv", 
				    												"xls",
				    											]
				    						}
				    					],
				    					
				    					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
				    				},
				                "fnInitComplete": function(oSettings, json) {
								
								fixControlPosition();
								
				                },
        "fnDrawCallback": function(oSettings) {
            var trs = $("#sample_1 tr");
            for (var i = 1; i < trs.length; i++) {

                var rowId = ($(trs[i]).attr('id'));
                $("#" + rowId + " td:last-child").trigger('click');

            }
            $('.uncolck_buttun').on('click', function() {
            	var tr = $(this).closest('tr');
                var row = dt.row(tr);
            	debugger;
    			$("#cod_tarh")[0].value = row.data().cod_tarh;;
    			if(language=="en")
    				$("#abc").text("Cause of request for edit");
    			else
    				$("#abc").text("دليل درخواست ويرايش");
				if(language=="en")
    				$("#h4_title").text("Edit request");
				else
					$("#h4_title").text("درخواست ويرايش");
    			modal_action="unlock";
    			 $("#basic").modal("show");
            	
            });
            $('.row-details').on('click', function() {
                debugger;
                var tr = $(this).closest('tr');
                var row = dt.row(tr);
                var idx = $.inArray(tr.attr('id'), detailRows);

                if (row.child.isShown()) {
                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-open');
                	$("#"+tr.attr('id')+" td:last").addClass('row-details-close');
                
                    row.child.hide();

                    // Remove from the 'open' array
                    detailRows.splice(idx, 1);
                } else {
                	$("#"+tr.attr('id')+" td:last").removeClass('row-details-close');
                	$("#"+tr.attr('id')+" td:last").addClass('row-details-open');
                    
                
                    row.child(format(row.data())).show();

                    // Add to the 'open' array
                    if (idx === -1) {
                        detailRows.push(tr.attr('id'));
                    }
                }
            });
        },
        
        "paging": true,
        'bPaginate': true,
        "pagingType": "full_numbers",
        "processing": true,
        "serverSide": true,
        "destroy": true,
        "bAutoWidth": false,
        "order": [[ 3, "desc" ]],
        "language": {
		
            "sProcessing": "<img src='image/ajax-loader-white.gif'>",
            "sLengthMenu": sLengthMenu,
            "sZeroRecords": sZeroRecords,
            "info": info,
            "sInfoEmpty": sInfoEmpty,
            "sInfoFiltered": sInfoFiltered,
            "sInfoPostFix": "",
            "sSearch": sSearch,
            "sUrl": "",
            "oPaginate" : {
                "sFirst": sFirst,
                "sPrevious": sPrevious,
                "sNext": sNext,
                "sLast": sLast
            }
        },
        "sAjaxSource": "server_side.php?position=" + $('#position :selected').val(),
        "aoColumns": [
            { "data": "cod_tarh" },
            { "data": "tarh_title_farsi" },
            { "data": "daneshkade_name" },
            { "data": "tarh_time" },
            { "data": "position", "bSortable": false },
            { "data": "edit", "bSortable": false },
            { "data": "ss", "sClass": "row-details row-details-close", "bSortable": false }
        ]

    });
	///////////////////////////////////////////
    $("#modal_form").submit(function(e){

    	debugger;
    	//alert("hi");
        // for more info visit the official plugin documentation: 
            // http://docs.jquery.com/Plugins/Validation
             debugger;
            var form2 = $('#modal_form');
            var error2 = $('.alert-danger', form2);
            var success2 = $('.alert-success', form2);
           /* jQuery.validator.addMethod("test", function(value, element) {
                return this.optional(element) || /^09[123]\d{8}/.test(value);
            }, "Your entered data is not phone number");*/
            form2.validate({
                
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                focusInvalid: false, // do not focus the last invalid input
                ignore: "",
                rules:{
            	archieve_reason:{
      	                  required:true
      	                  //test:true,
        	              //rangelength:[11,11]
      	                  }
      	              },
    	  	    messages:{
        	           archieve_reason:{
      	                  required:"پر کردن اين فيلد الزامي مي باشد",
      	            	  }
    		  	      },
      	              
      		  	    
                invalidHandler: function (event, validator) { //display error alert on form submit              
                        success2.hide();
                        error2.show();
                        App.scrollTo(error2, -200);
                },

                errorPlacement: function (error, element) { // render error placement for each input type
                    var icon = $(element).parent('.input-icon').children('i');
                    icon.removeClass('fa-check').addClass("fa-warning");  
                    icon.attr("data-original-title", error.text()).tooltip();
                },

                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group   
                },

                unhighlight: function (element) { // revert the change done by hightlight
                    
                },

                success: function (label, element) {
                    var icon = $(element).parent('.input-icon').children('i');
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                    icon.removeClass("fa-warning").addClass("fa-check");
                },

                submitHandler: function (form) {
                    success2.show();
                    error2.hide();
                }
            });

    var formURL;
    var postData = $(this).serializeArray();	
    	 //formURL = $(this).attr("action");
	 if(modal_action=="archive")
		 	formURL="archive_tarh.php?action=finish";
	 else if(modal_action=="unlock")
		 formURL="unlock_request.php?action=finish";
    	 debugger;
    if($("#modal_form").valid())
    {
        $(".green").attr("disabled","disabled");
    	$.ajax(
    	{
    		url : formURL,
    		type: "POST",
    		data : postData,
    		success:function(data, textStatus, jqXHR) 
    		{
    			     //alert(data);
    			    debugger;
    			    if(modal_action=="archive"){
        			    if($("#unarch")[0].value=="0")
    			     		$("#" + data + " td:eq(4)").text("بايگاني شده");
    			    	if($("#unarch")[0].value=="1")
			     			$("#" + data + " td:eq(4)").text("خروج از بايگاني");
    			    }
    			    else if(modal_action=="unlock")
    			    	$("#" + data + " td:eq(5)").children().children().switchClass( "fa-lock","fa-unlock", 1000, "easeInOutQuad" );
    				$("#basic").modal('hide');
    				$("#send_letter")[0].reset();
    			
    	        //   $("#sample_1").DataTable().destroy();
    	    		
    	          // show_dataTable(); 
    	           
    		},
    		error: function(jqXHR, textStatus, errorThrown) 
    		{
    			alert("error");
    		}
    	}).always($(".green").removeAttr("disabled","disabled"));

    	}
        e.preventDefault();	//STOP default action 
    });
/////////////
   $('#position').change(function() {
	debugger;
		if($('#position :selected').val()=="-1")
		{
			
			if(language=="en"){
				$(".caption").html("<i id='caption-grid' class='fa fa-globe'></i> All Projects");
			}
			else{
				$(".caption").html("<i id='caption-grid' class='fa fa-globe'></i>همه طرح ها");
			}
		}
		else
		{
			if(language=="en"){
				$(".caption").html($('#position :selected').text()+"<i id='caption-grid' class='fa fa-globe'></i>");
			}
			else{
				$(".caption").html("<i id='caption-grid' class='fa fa-globe'></i> طرح هاي "+$('#position :selected').text());
			}
		}
        dt.ajax.url("server_side.php?+position=" + $('#position :selected').val());
        dt.ajax.reload();
    });


});
$('#basic').on('hidden.bs.modal', function () {
	    debugger;
	    $("#modal_form")[0].reset();
	    $(".alert-danger").hide();
	});
</script>
    
<?php
footer_forms($admin,$seed);
?>

