<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms();
?>
<link rel="stylesheet" type="text/css"	href="../assets/plugins/select2/select2-rtl.css" />
<link rel="stylesheet" type="text/css"	href="../assets/plugins/select2/select2-metronic-rtl.css" />
<link rel="stylesheet"	href="../assets/plugins/data-tables/DT_bootstrap_rtl.css" />
<link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.colVis.css" rel="stylesheet" />
<link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="../assets/plugins/bootstrap-toastr/toastr-rtl.min.css"/>

<style>
.modal-body p {
	text-align: center;
}
</style>
<?php
include("include/new_menu.php");
$query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1'";
$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
$row_fetched=mysql_fetch_array($result);
$tarh_name = $row_fetched["tarh_title_farsi"];
?>

<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
	<div class="page-content">
		<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
		<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">راهنما</h4>
                            </div>
                            <div class="modal-body">
                               در حال تکمیل می باشد.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn default red" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
		<!-- /.modal -->
		<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

		<!-- BEGIN PAGE HEADER-->
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				 <h3 class="page-title">
                            <small id="page-title">عنوان طرح :</small>
                            <small><? echo $tarh_name;?></small>
                            
                        </h3>
                        <ul class="page-breadcrumb breadcrumb">

                            <li>
                                <i class="fa fa-home"></i>
                                <a id="navigator-home" href="home.php">
                                    خانه
                                </a>
                                <i id="fa-angle" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="send-edit" href="tarh_list.phtml">
                                    ارسال/ويرايش طرح
                                </a>
                                <i id="fa-angle2" class="fa fa-angle-left"></i>
                            </li>
                            <li>
                                <a id="attachment" href="upload_file.phtml?cod_tarh=<?php echo $cod_tarh; ?>">
                                    ضمائم
                                </a>
                            </li>
                        </ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>
		<!-- END PAGE HEADER-->
		<div class="row">
			<div class="col-md-12">
				<div class="portlet box grey">
					<div  class="portlet-title">
						<div id="caption-grid" class="caption">
							<i class="fa fa-magic"></i>ويزارد
						</div>
						
					</div>
					<div class="portlet-body">
						<div class="row">
                                    <?php  $active_id="14"; include("include/wizard.php");?>
                                    <div class="col-md-9 col-sm-9 col-xs-9">
								<div class="portlet box blue">
									<div class="portlet-title">
										<div id="caption_title" class="caption">
											<i class="fa fa-reorder">ضمائم</i>
										</div>
										<div class="tools">
											<a href="javascript:;" class="collapse">
											</a>
											<a href="#portlet-config" data-toggle="modal"
											class="fa fa-info-circle" title="راهنما"
											style="color: white">
											</a>
										</div>
									</div>
									<div class="portlet-body form-horizontal">
										<!-- BEGIN FORM-->

										<div class="modal fade" id="basic" tabindex="-1" role="basic"
											aria-hidden="true">
											<div class="modal-dialog">
												<div class="modal-content">
													<div id="modal_" class="modal-header bg-blue">
													
														<button type="button" id="modal-close" class="close"
															data-dismiss="modal" aria-hidden="true"></button>
															<h4 id="upload_attachment" class="modal-title">
							                                            <i class="fa fa-file-o"></i>
							                                            ضميمه
							                                </h4>
													</div>
													<div class="modal-body">

														
																<!-- BEGIN FORM-->
																<!-- <form name="mojri_tarh" id="mojri_tarh_sabt" action="mojri_tarh.php?action=add_mojri&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&mojri_code=$mojri_code" method="POST" class="form-horizontal">-->	
																	<?php 
																	     echo "<form id=\"upload_file_sabt\" method=\"post\" enctype=\"multipart/form-data\" action=\"upload_file_sabt.php?action=sabt&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" class=\"form-horizontal\">";
																     ?>
																<input id="cod_tarh" name="cod_tarh" type="hidden" class="form-control" value="<?php echo $cod_tarh;?>">
																<input id="delete_id" name="delete_id" type="hidden">
																<div class="form-body">
																	<div class="form-horizontal">
																		<div class="form-group">
																			<p id="help-block1" class="help-block">
																		    	تعداد فايلهاي ارسالي حداکثر 12 عدد مي باشد
																		    </p>
																		    <p id="help-block2" class="help-block">
																				حداکثر حجم فايل 8 مگابايت مي باشد. نام فايل را انگليسي و بدون فاصله وارد کنيدفايل ارسالي بايد به فرمت Word يا PDF باشد.صرفا از فونت زر استفاده کنيد 
																		    </p>
																		    <p id="help-block3" class="help-block">
																		    فايلهاي ضميمه با نام انگليسي معتبر هستند 
																		    </p>
																			<div class="col-md-12 col-md-push-5">
																			    <label for="photo" id="control-label" class="control-label">فايل ضميمه:</label>
																				<input type="file" id="fupload" name="fupload" accept="application/msword,application/pdf,.docx">
																			</div>
																	    </div>
																
																	</div>
																	<!--/row-->
																</div>
																



																<!-- END FORM-->
														
												</div>
													<div class="modal-footer">
													<button id="upload_file_btn" type="submit" class="btn green btn-primary" data-loading-text="در حال بارگذاري...">ذخيره</button>
													<button id="btn1" type="button" class="btn red" data-dismiss="modal">
														<i class="fa fa-times"></i>انصراف
													</button>
													</div>
												</div>
												<!-- /.modal-content -->
											</div>
											<!-- /.modal-dialog -->
										</div>

										<div class="modal fade " id="delete" tabindex="-1" role="basic" aria-hidden="true">
											<div class="modal-dialog">
												<div class="modal-content">
													<div class="modal-header">
														<button type="button" class="close" data-dismiss="modal"
															aria-hidden="true"></button>
														<h4 class="modal-title">
															<i class="fa fa-file-o"></i>

														</h4>
													</div>
													<div class="modal-body">
														<!-- BEGIN FORM-->

														<div class="form-body">
															<h4 id="delete_question" class="form-section">آيا از حذف اين آيتم اطمينان داريد؟</h4>
														</div>
														<div class="form-actions fluid">
															<div class="row">
																<div class="col-md-6">
																	<div class="col-md-offset-3 col-md-9">
																		<button id="delete_yes" type="submit" class="btn green">بلي</button>
																		<button id="delete_no" type="button" class="btn red" data-dismiss="modal">
																			<i class="fa fa-times"></i>خير
																		</button>
																	</div>
																</div>
																<div class="col-md-6"></div>
															</div>
														</div>

														<!-- END FORM-->
													</div>

												</div>
												<!-- /.modal-content -->
											</div>
											<!-- /.modal-dialog -->
										</div>
										</form>
										<a id="upload_btn" class="btn blue btn-sm pull-left" data-toggle="modal" data-backdrop="static"
											href="#basic">ارسال فايل ضمائم</a>
										<!-- END FORM-->
										<table class="table table-striped table-bordered table-hover" id="sample_1">
											<thead>
												<tr>
													<th id="th1" class="">نام فايل</th>
													<th id="th2" class="">حذف</th>
													<th class="hidden">delete_id</th>
												</tr>

											</thead>

										</table>
									</div>
								</div>
							</div>

						</div>
					</div>

				</div>

			</div>
		</div>
		<!-- END PAGE CONTENT-->
	</div>
</div>
<!-- END CONTENT -->
<script type="text/javascript">


if(language=="en")
{ 
	document.getElementById("page-title").textContent="Research Title :";
	document.getElementById("navigator-home").textContent="Home";
	document.getElementById("send-edit").textContent="Send / Edit Research";
	document.getElementById("attachment").textContent="Attachments";
	document.getElementById("caption_title").textContent="Attachments";
	document.getElementById("upload_btn").textContent="Submit Attachments";
	document.getElementById("control-label").textContent="Attachment";
	document.getElementById("fa-angle").className="fa fa-angle-right";
	document.getElementById("fa-angle2").className="fa fa-angle-right";
	document.getElementById("caption-grid").innerHTML="<i id='caption-grid' class='fa fa-magic'></i> Wizard";
	document.getElementById("upload_attachment").innerHTML="<i class='fa fa-file-o'></i>Attachment";
	document.getElementById("upload_file_btn").textContent="Save";
	document.getElementById("btn1").textContent="Cancel";
	document.getElementById("help-block1").textContent="Maximum number of attachments is 12";
	document.getElementById("help-block2").textContent="The maximum file size is 8MB.The file names must be english,whitout apace,The file format must be in Word or PDF.Only use ZAR font inside your file";
	document.getElementById("help-block3").textContent="Attached file names in english are valid";
	document.getElementById("th1").textContent="File Name";
	document.getElementById("th2").textContent="Delete";
	document.getElementById("delete_question").textContent="Are you sure to delete?";
	document.getElementById("delete_yes").textContent="Yes";
	document.getElementById("delete_no").textContent="No";
	
	
}

</script>


<?php 
include("../include/primary_js.phtml");
?>

	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../assets/plugins/data-tables/DT_bootstrap.js"></script> 
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.colVis.js"></script>
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	<script src="../assets/plugins/bootstrap-toastr/toastr.min.js"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../assets/scripts/core/app.js"></script>
	<script src="../assets/scripts/custom/form-samples.js"></script>
	
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
	jQuery(document).ready(function() {    
	   // initiate layout and plugins
	 //  App.init();
	   //FormSamples.init();
	   //$(".").select2();
		 $('body').addClass(" page-sidebar-closed");
	});
	</script>
	<!-- END JAVASCRIPTS -->
	<script>
	function fixControlPosition(){
		//ja be jayi btn haye table tools (print,copy,....)
							$(".DTTT_button_collection,.DTTT_button_csv,.DTTT_button_xls,.DTTT_button_print,.DTTT_button_copy,.ColVis_Button").addClass("btn blue btn-sm");
							$(".DTTT_container").insertBefore(".dataTables_wrapper");
							$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
							$('#sample_1_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
							$('#sample_1_wrapper .dataTables_length select').select2(); // initialize select2 dropdown
							$("#sample_1_filter").append('<div class="clearfix" > </div>');//firefox problem				
		}
	$("#upload_file_sabt").submit(function(e)
			{
		//dicision for edit or add
		debugger;
				var formURL;
				//var postData = $(this).serializeArray();
				if(jadvZar_IsNew=="insert")		
					 formURL = $(this).attr("action");
				//else if(jadvZar_IsNew=="edit")		
					//formURL="upload_file_sabt.php?action=edit";
				else if(jadvZar_IsNew=="delete")		
					formURL="upload_file_sabt.php?action=delete";
				 var btn = $("#upload_file_btn");
				 btn.button('loading');
				$.ajax(
				{
					url : formURL,
					data : new FormData(this),
					cache: false,
				    contentType: false,
				    processData: false,
				    type: "POST",
					success:function(data, textStatus, jqXHR) 
					{
					debugger;
                        //alert(data);
						if(data=="ضميمه حذف شد")
						{      
								toastr.options.timeOut="5000";
						        toastr.options.positionClass="toast-top-right";
								toastr.success('ضميمه حذف شد');
						}
						if(data=="123")
						{       $("#upload_file_i").switchClass( "fa-check", "fa-times", 1000, "easeInOutQuad" );
								toastr.options.timeOut="5000";
						        toastr.options.positionClass="toast-top-right";
								toastr.success('123ضميمه حذف شد');
						}
						if(data=="true")
							
						{       $("#upload_file_i").switchClass( "fa-times", "fa-check", 1000, "easeInOutQuad" );
								toastr.options.timeOut="5000";
						        toastr.options.positionClass="toast-top-right";
								toastr.success('ضميمه با موفقيت ثبت شد');
								
						}
						else if(data=="-5")
						{ 
								toastr.options.timeOut="5000";
								toastr.options.positionClass="toast-top-right";
								toastr.error('چنين فايلي قبلا بارگذاري شده','خطا');
								
							}
						else if(data=="-2")
						{
								toastr.options.timeOut="5000";
								toastr.options.positionClass="toast-top-right";
					    		toastr.error('حجم فابل ارسالي بيش از 8 مگابايت مي باشد يا پسوند فايل صحيح نمي باشد.','خطا');
						}
						else if(data=="false")
						{
								toastr.options.timeOut="5000";
								toastr.options.positionClass="toast-top-right";
			      			    toastr.error('تعداد فايلهاي ارسالي حداکثر 12 عدد مي باشد','خطا');
						}
					
					jadvZar_IsNew="insert";
					$("#basic").modal('hide');
					$("#delete").modal('hide');
					$("#upload_file_sabt")[0].reset();
				    	//debugger;
				            var uniSelect = $("#uniSelect");
				            var temp = $("#temp");
				            uniSelect.appendTo(temp);
				    		
				            $("#sample_1").DataTable().destroy();
							show_dataTable();
				        
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
						alert(textStatus);
					}
				}).always(function () { 
					 btn.button('reset');
			    });
			    e.preventDefault();	//STOP default action
			    //$("#upload_file_sabt").submit(); //SUBMIT FORM
			});
				
			
	 </script>
	 <script>
	 var buttonText;
	 var sButtonText;
	 var info;
	 if(language=="en"){
			buttonText="Visibel Columns";
			sButtonText="Print";
			sButtonText2="Save";
			info="view _START_ to _END_ from _TOTAL_ items";
			sLengthMenu="View Content _MENU_";
			sZeroRecords="Not Found";
			sInfoEmpty="Empty";
			sInfoFiltered="(Filtered From _MAX_ Items)";
			sSearch="Search";
			sFirst="First";
			sPrevious="Previous";
			sNext="Next";
			sLast="Last";
			
			
		}
		else
		{
			buttonText="ستون هاي قابل نمايش";
			sButtonText="چاپ";
			sButtonText2="ذخيره";
			info="نمايش _START_ تا _END_ از مجموع _TOTAL_ مورد";
			sLengthMenu="نمايش محتويات _MENU_";
			sZeroRecords="موردي يافت نشد";
			sInfoEmpty="تهي";
			sInfoFiltered="(فيلتر شده از مجموع _MAX_ مورد)";
			sSearch="جستجو";
			sFirst="ابتدا";
			sPrevious="قبلي";
			sNext="بعدي";
			sLast="انتها";
			
		}


	 
	 $(document).ready(function() {
		 
		    var detailRows = [];
		show_dataTable();

	 });
	
	function show_dataTable()
	{
		var dt;				
		
	    dt = $('#sample_1').DataTable({
			"dom": 'CT<"clearfix">lfrtip',
	        "tableTools": {
	            "sRowSelect": "os",
				 "aButtons": [
	               
					{
	                    "sExtends": "print",
	                    "sButtonText": sButtonText
	                },
	                
	                {
	                    "sExtends":    "collection",
	                    "sButtonText": sButtonText2,
	                    "aButtons":    [ 
											"csv", 
											"xls"
										]
	                }
	            ],
		            
					"sSwfPath": "../assets/advanced-datatable/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
		        },
		        "fnInitComplete": function(oSettings, json) {
			        
			        //Begin of hide some of element from data table
		        	$("#sample_1_paginate").css("display","none");	
		        	$("#sample_1_info").css("display","none");
				    $("#sample_1_length").css("display","none");
					$("#sample_1_filter").css("display","none");
					//End of hide some of element from data table
					
					fixControlPosition();
					
	                },
		        "fnDrawCallback": function(oSettings) {
		            var trs = $("#sample_1 tr");
		            for (var i = 1; i < trs.length; i++) {

		                var rowId = ($(trs[i]).attr('id'));
		                $("#" + rowId + " td:last-child").trigger('click');

		            }
		           /* $('.edit_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                //var idx = $.inArray(tr.attr('id'), detailRows);
		                $('#fupload')[0].value = row.data().fupload;
		                
		                jadvZar_IsNew="edit";
		                $("#basic").modal('show');
		            });*/
		            $('.delete_btn').on('click', function() {
		                debugger;
		                var tr = $(this).closest('tr');
		                var row = dt.row(tr);
		                $('#delete_id')[0].value = row.data().delete_id;
		                
		                jadvZar_IsNew="delete";
		                $("#delete").modal('show');
	                
		            });
		        },
		        "colVis": {
		           "buttonText": buttonText,
		           exclude:[2]
		       },
		        
		       "paging": true,
               'bPaginate': true,
               "pagingType": "full_numbers",
               "processing": true,
               "serverSide": true,
               "bDestroy": true,
               "bAutoWidth": false,
				"language": {
           		
                   "sProcessing": "<img src='image/ajax-loader-white.gif'>",
                   "sLengthMenu": sLengthMenu,
                   "sZeroRecords": sZeroRecords,
                   "info": info,
                   "sInfoEmpty": sInfoEmpty,
                   "sInfoFiltered": sInfoFiltered,
                   "sInfoPostFix": "",
                   "sSearch": sSearch,
                   "sUrl": "",
                   "oPaginate" : {
                       "sFirst": sFirst,
                       "sPrevious": sPrevious,
                       "sNext": sNext,
                       "sLast": sLast
                   }
		       },
		        "sAjaxSource": "upload_file_sabt.php?&action=select&admin=<?php echo $admin;?>&seed=<?php echo $seed;?>&cod_tarh=<?php echo $cod_tarh;?>" ,
		        "aoColumns": [
		            { "data": "file" },
				    { "data": "delete", "bSortable": false },
				    { "data": "delete_id","sClass": "hidden"}
		        ]

		    });
	}
	
		var jadvZar_IsNew="insert";

		$('#basic').on('hidden.bs.modal', function () {
		   // debugger;
		    jadvZar_IsNew="insert";
		    $("#upload_file_sabt")[0].reset();
		});
		$('#delete').on('hidden.bs.modal', function () {
			   // debugger;
			    jadvZar_IsNew="insert";
			    $("#upload_file_sabt")[0].reset();
			});

	 </script>

<?php
footer_forms($admin,$seed);
?>
