<HTML><HEAD>
<TITLE>.:: pajooheshyar ::.</TITLE>
<STYLE></STYLE>
<META http-equiv=Content-Language content=en-us>
<META http-equiv=Content-Type content=text/html; charset=utf-8 charset=utf-8>
<META content=""
name=Description>
<META content="" name=keywords>
<STYLE type=text/css>
BODY {
	SCROLLBAR-FACE-COLOR: #003366;
	SCROLLBAR-HIGHLIGHT-COLOR: #000000;
	SCROLLBAR-SHADOW-COLOR: #000000;
	SCROLLBAR-3DLIGHT-COLOR: #a1a1a1;
	SCROLLBAR-ARROW-COLOR: #000000;
	SCROLLBAR-TRACK-COLOR: #bfbfbf;
	SCROLLBAR-DARKSHADOW-COLOR: #ffffff;
	SCROLLBAR-BASE-COLOR: #a1a1a1;
	background-color: #CCCCCC;
}

a:link {
	color: #333333;
	text-decoration: none;
}
a:visited {
	color: #333333;
	text-decoration: none;
}
a:hover {
	color: #7592B5;
	text-decoration: none;
}
a:active {
	color: #E8EAF6;
	text-decoration: none;
}
</STYLE>
<SCRIPT language=JavaScript type=text/JavaScript>
</SCRIPT>
<META content="" name=des>
<META content="rahpouyan company "
name=designers>
<META content="Microsoft FrontPage 4.0" name=GENERATOR>
<meta name="keywords" content="advertise;propaganda;web;webpage;website;web design;web designers;web developer;webdevelopers;garphic;graphic design;iranian graphic design;persian;persian graphic design;garphic;graphics;geraphic developer;designers;design;cd catalog;presentations;presentation;cd;computer;pc;oragnization;nafis;graphic soloution;network;it;it graphic;university;company;complex;soloutions;help;graphic help;website designers;website opening;html;php;perl">
<meta name="description" content="web graphic center
make your website &amp; cd catalog in our copmany for best way.
">
<meta name="designers" content="web website design center">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></HEAD>
<BODY leftMargin=0 topMargin=0
_1/but1_eff.JPG','image_main_page/top_but_1_eff.jpg','images/but_1_eff.jpg','images/but_2_eff.jpg','images/but_3_eff.jpg','images/but_4_eff.jpg','images/but_5_eff.jpg')">
<CENTER>
<TABLE borderColor=black cellSpacing=0 cellPadding=0 width=800 bgColor=#ffffff
border=0 height="611"><!--DWLayoutTable-->
  <tr>
    <TD height=117 colspan="5" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <!--DWLayoutTable-->
        <tr>
          <td height="19" colspan="3" background="img_data/top_1_01.jpg" style="font-size: 7pt; font-family: Tahoma; color: #666666">
			<span lang="fa">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</span>&nbsp;
			<span lang="fa">تاريخ :&nbsp; 25/2/1384&nbsp;&nbsp;&nbsp; ساعت :
			15:23:24</span></td>
          <td width="93" rowspan="2" valign="top"><img src="img_data/top_1_02.jpg" width="93" height="98"></td>
          <td width="108" rowspan="3" valign="top"><img src="img_data/top_1_03.jpg" width="108" height="117"></td>
          <td width="274" rowspan="3" valign="top"><img src="img_data/top_1_04.jpg" width="274" height="117"></td>
        </tr>
        <tr>
          <td width="46" height="79" valign="top"><img src="img_data/top_1_05.jpg" width="46" height="79"></td>
          <td width="155" valign="top"><img src="img_data/top_1_06.jpg" width="155" height="79"></td>
        <td width="124" valign="top"><img src="img_data/top_1_07.jpg" width="124" height="79"></td>
        </tr>
        <tr>
          <td height="19" colspan="4" valign="bottom" background="img_data/top_1_08.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
			<span lang="fa">نقشه سايت&nbsp; ::&nbsp; درباره نرم افزار&nbsp; ::&nbsp;
			ارتباط با مديريت &nbsp;&nbsp;&nbsp; </span></td>
          </tr>
        </table></TD>
    </tr>
	<tr>
    <TD width="164" rowspan="3" valign="top" background="img_data/left_td_back.jpg">
	    <table width="164" border="0" cellpadding="0" cellspacing="0" background="img_data/left_td_back.jpg" height="428">
          <!--DWLayoutTable-->
          <tr>
            <td height="8"></td>
          </tr>
			<tr>
            <td height="197" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="img_data/td_news_back.jpg" id="news_td">
                  <!--DWLayoutTable-->
                  <tr>
                    <td height="22" colspan="3" valign="top" background="img_data/td_news_pic.jpg">&nbsp;</td>
                  </tr>
                  <tr>
                    <td width="19" height="8"></td>
                    <td width="120"></td>
                    <td width="25"></td>
                  </tr>
                  <tr>
                    <td height="145"></td>
                    <td valign="top" style="font-size: 8pt; font-family: Tahoma; color: #666666" width="120" height="145"><!--DWLayoutEmptyCell-->&nbsp;</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td height="8"></td>
                    <td></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td height="14" colspan="3" valign="top"><img src="img_data/td_news_pic_2.jpg" width="164" height="14"></td>
                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                </table></td>
          </tr>
      </table>	    </TD>
    <TD width="12" height="17"></TD>
    <TD width="460"></TD>
    <TD width="14"></TD>
    <TD width="150" rowspan="3" valign="top" background="img_data/right_td_back.jpg">
        <table width="150" border="0" cellpadding="0" cellspacing="0" background="img_data/right_td_back.jpg" height="429">
            <!--DWLayoutTable-->
            <tr>
              <td height="19" valign="top"><img src="img_data/top_2.jpg" width="150" height="19"></td>
            </tr>
			<tr>
              <td height="221" valign="top">
				<table width="150" border="0" cellpadding="0" cellspacing="0" background="img_data/buts_back.jpg" height="221">
                <!--DWLayoutTable-->
                <tr>
                  <td width="150" height="221" valign="top">
					<table border="0" width="140" height="216">
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">طرحهاي تحقيقاتي</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">محقيقن</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">گزارش طرحهاي تحقيقاتي</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">جستجو</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">جستجوي پيشرفته</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">عضو جديد</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">تماس با ما</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="index.HTM">خروج</a></span></td>
						</tr>
					</table>
				  </td>
                </tr>
              </table></td>
            </tr>
			<tr>
              <td height="189" width="150">&nbsp;</td>
            </tr>
        </table>        <p></TD>
  	</tr>
	<tr>
	  <TD height="231"></TD>
	  <TD valign="top" rowspan="2">
