<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/vars.inc.phtml");
include("include/styles.phtml");

echo "<br>";


$status="";
if (strcmp($action,"add")==0)
{

  if(strlen(trim($shomare_pardakht)) > 0 )
  {
      $startdate = date("Y-m-d");;
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $startyear = substr($farsistartdate,0,4);
  $startmon = substr($farsistartdate,5,2);
  $startday = substr($farsistartdate,8,2);
  $paperno=$startyear."-".$startmon."-".$startday."-".$shomare_pardakht;
  echo $farsistartdate;
    if(!isset($old)){
    	
    	$old="0";
    }
    $query="select * from dastoor_pardakht where paperno=\"$paperno\" ";
    $result=mysql_query($query) or die("Error");
    if(mysql_num_rows($result) <=0 )
    {
 	 $query="insert into dastoor_pardakht set paperno='$paperno',paperdate=\"$farsistartdate\",old='$old'";
	
	 $result=mysql_query($query) or die ("Error in inserting data into jalase_shora1");
	 echo "<SCRIPT language=\"JavaScript\">";
      echo "window.location=\"dastoor_pardakht_marhale.phtml?admin=$admin&seed=$seed&paperno=$paperno&old=$old\"";
      echo "</SCRIPT>";
	
    }
     else
      $status="duplicate_entry";
    
  }
  else
   $status="entry_error";
}

?>


<? echo "<form name=\"add-tarh\" method=\"post\"  action=\"$PHP_SELF?action=add&admin=$admin&seed=$seed&jalase_type=$jalase_type\">"; ?>




<TABLE cellSpacing=0 cellPadding=0 width="500" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
  <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">

          <table border="0" width="100%"  bgcolor="#EEE7F8" height="100%" cellpadding="0" cellspacing="0">
          
            <tr>
              <td width="300" align="right" >
                <p align="right"><input type="text" name="shomare_pardakht" size="48" class="edit-tarh-type" value="" class="edit-user" ></td>
              <td width="200" align="left" >
                <p align="left" class="tahoma1"><span class="star-message">*</span>شماره نامه پرداخت</td>
            </tr>
            
             <tr>
              <td width="300" align="right" >
                <p align="right"><input type="checkbox" name="old"   value="1" align="center"></td>
              <td width="200" align="left" >
                <p align="left" class="tahoma1"><span class="star-message">*</span>ليست طرح هاي قديمي</td>
            </tr>
            
		
            
          </table>

      </td>
    </tr>
<?php 
  echo "<tr>";
  echo "<td width=\"100%\" colspan=\"2\" height=\"32\">";
  echo "<p align=\"center\"><input class=\"but-tarh-type\" type=\"submit\" value=\"ثبت\" name=\"submit_tarh\"></td>";
  echo "</tr>";
  echo "</form>";

  echo "</table>";


  footer_forms($admin,$seed);
?>



