<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");



echo "<br>";




if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];
if(isset($rank_jalase) && strcmp($rank_jalase,"-1")!=0)
{
	$year_caution="cod_tarh like \"$rank_jalase".'%'."\"";
}
else 
	$year_caution="1";
	
	
	
if(isset($cod_jalase) && strcmp($cod_jalase,"-1")!=0)
{                                     
	$cod_jalase_caution="shora_pajohesh_daneshgah.cod_jalase = '$cod_jalase'";
}
else 
	$cod_jalase_caution="1";
		
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
    	
	
if(isset($name_e))
{
  $query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,shora_pajohesh_daneshgah where  tarh.cod_tarh=shora_pajohesh_daneshgah.cod_tarh and tarh.refered_shora='1' and  $cod_jalase_caution and (tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and vaziat_tarh.vaziat=tarh.vaziat_moaven and send_moavenat ='1' and (vaziat_tarh.vaziat!='12' or vaziat_tarh.vaziat!='13' or vaziat_tarh.vaziat!='14')   group by tarh.cod_tarh order by tarh_time desc" ;
}
else
  $query="select tarh_hesabdari.personname as personname_mojri,tarh_hesabdari.accountno as accountno_mojri,tarh_hesabdari.shebano as shebano_mojri,tarh_hesabdari.id as tarh_hesabdari_id,marhale_gharardad_hesabdari.* from tarh_hesabdari,marhale_gharardad_hesabdari,dastoor_pardakht_marhale where  tarh_hesabdari.id=dastoor_pardakht_marhale.tarh_hesabdari_id and  marhale_gharardad_hesabdari.id=dastoor_pardakht_marhale.marhale_gharardad_id and dastoor_pardakht_marhale.paperno='$paperno' ";
//  echo $query;
 

$result=mysql_query($query) or die("Error in selecting data from tarh 100");

$reccount = mysql_num_rows($result);
//echo $reccount;

 if(isset($name_e))
{
  $query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,shora_pajohesh_daneshgah where  tarh.cod_tarh=shora_pajohesh_daneshgah.cod_tarh and   tarh.refered_shora='1' and  $cod_jalase_caution and (tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and vaziat_tarh.vaziat=tarh.vaziat_moaven and send_moavenat ='1' and (vaziat_tarh.vaziat!='12' or vaziat_tarh.vaziat!='13' or vaziat_tarh.vaziat!='14')   group by tarh.cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query=$query="select tarh_hesabdari.personname as personname_mojri,tarh_hesabdari.accountno as accountno_mojri,tarh_hesabdari.shebano as shebano_mojri,tarh_hesabdari.id as tarh_hesabdari_id,marhale_gharardad_hesabdari.* from tarh_hesabdari,marhale_gharardad_hesabdari,dastoor_pardakht_marhale where  tarh_hesabdari.id=dastoor_pardakht_marhale.tarh_hesabdari_id and  marhale_gharardad_hesabdari.id=dastoor_pardakht_marhale.marhale_gharardad_id and dastoor_pardakht_marhale.paperno='$paperno'  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage;
//echo $query;

$result=mysql_query($query) or die("Error in selecting data from tarh 200");
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&action=sabt&paperno=$paperno\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="95%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>تعيين مراحل پرداختي<b><br></td>
 </tr>

 </table>
 

<?
}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."paperno=$paperno"; 	
 pubshowpages("dastoor_pardakht_view.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
   <td width="7%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايش</font></td>  
     <td width="7%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ماليات مرحله</font></td>  
   <td width="7%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">سهم ناظر</font></td>  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">شماره شبا ناظر</font></td>  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">شماره حساب ناظر</font></td>  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ناظر اين مرحله</font></td>
    <td width="7%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">سهم مجري</font></td> 
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مبلغ قابل پرداخت</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مبلغ مرحله</font></td>
    <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مرحله قرارداد</font></td> 
	<td width="13%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">شماره شبا مجري</font></td>
   <td width="8%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">شماره حساب مجري</font></td>
    <td width="3%" align="center" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري طرف قرارداد</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>

<?
  
 $row="1";
 $doctor_in_list=1;
 $color=$list_color_1;
 $k=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $marhale_gharardad_hesabdari_id=$row_fetched["id"];
  $tarh_hesabdari_id=$row_fetched["tarh_hesabdari_id"];
  $cod_tarh=$row_fetched["researchno"];
  $personname=$row_fetched["personname_mojri"];
  $accountno=$row_fetched["accountno_mojri"];
  $shebano=$row_fetched["shebano_mojri"];
  $stepno=$row_fetched["stepno"];
  $stepamount=$row_fetched["stepamount"];
  $mablagh_ghable_pardakht=$row_fetched["mablagh_ghable_pardakht"];
  $amount1=$row_fetched["amount1_pardakht"];
  $amount2=$row_fetched["amount2"];
  $personname_nazer=$row_fetched["personname"];
  $accountno_nazer=$row_fetched["accountno"];
  $shebano_nazer=$row_fetched["shebano"];
  $tax=$row_fetched["tax_pardakht"];
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  $row_cnt=($current-1)*$RecPerPage+$row;
  
  echo "<input type=\"hidden\" name=\"c".$k."\" value=\"".$tarh_hesabdari_id."\">";
  echo "<input type=\"hidden\" name=\"g".$k."\" value=\"".$marhale_gharardad_hesabdari_id."\">";  
  echo "<td width=\"7%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a  href=\"edit_marhale_gharardad_hesabdari.phtml?admin=$admin&seed=$seed&marhale_gharardad_hesabdari_id=$marhale_gharardad_hesabdari_id&tarh_hesabdari_id=$tarh_hesabdari_id&paperno=$paperno\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
  echo "<td width=\"7%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($tax, 6, '.', ',')."</td>";
  echo "<td width=\"7%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($amount2,6, '.', ',')."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$shebano_nazer</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$accountno_nazer</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$personname_nazer</td>";
  echo "<td width=\"7%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($amount1,6, '.', ',')."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_ghable_pardakht,6, '.', ',')."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($stepamount,6, '.', ',')."</td>";
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$stepno</td>";
  echo "<td width=\"13%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$shebano</td>";
  echo "<td width=\"8%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$accountno</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$personname</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$cod_tarh</td>";
  echo "</tr>";
  $k++;
  
 }
 
 

echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}

footer_forms($admin,$seed);


?>

