<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);

include("include/styles.phtml");
include("include/vars.inc.phtml");
require_once('lib/nusoap.php');
require("include/class.phpmailer.php");
require("include/class.smtp.php");

require("include/mailserver-statistics.phtml");
 
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  old
  if (strcmp($action,"edit_hazine_second")==0  )
  {
  	   $mablagh=str_replace(",","",$mablagh);
  	   $sayer_hazine=str_replace(",","",$sayer_hazine);
  	   $query  = "update  feedback_pardakht  set    mablagh = \"$mablagh\",hesab_no = \"$hesab_no\", year = \"$year\" ,month=\"$month\" ,day=\"$day\",name=\"$name\",family=\"$family\" ,marhale =\"$marhale\", cod_tarh  =\"$cod_tarh\"  where id='$id'  ";
         
	   $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");
	  // 	 savelog($cod_tarh,$admin,'edit','edit hazineha others from tarh '.$cod_tarh);

  }
  if (strcmp($action,"add_hazine")==0  )
  {
        $query  = "select * from sayer_hazine where cod_tarh=\"$cod_tarh\"  and version='-1'";
        $result = mysql_query($query) or die("Error in inserting data into  sayer hazineha");
         if( mysql_num_rows($result) <= 0 )
         {
          $mablagh=str_replace(",","",$mablagh);
 	     	   $query  = "insert into    feedback_pardakht  set    mablagh = \"$mablagh\",hesab_no = \"$hesab_no\", year = \"$year\" ,month=\"$month\" ,day=\"$day\",name=\"$name\",family=\"$family\" ,marhale =\"$marhale\", cod_tarh  =\"$cod_tarh\"    ";

           $result = mysql_query($query) or die("Error in inserting data into  sayer hazineha");
		      	$query="select user_login.* from tarh, user_login where cod_tarh='$cod_tarh' and tarh.creator=user_login.email";
     	$result=mysql_query($query) or die("error ");
     	$row_fetched=mysql_fetch_array($result);
     	$telno=$row_fetched["mobile"];
		 $email=$row_fetched["email"];
        $action="تاييد پرداخت مرحله "."<br>.".$tayeed_marhale."<br>.".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
        if($tayeed_marhale==0)
     	  $tayeed_marhale=1;
     	
		if($tayeed_marhale==100)
     	  $tayeed_marhale='final';
		  $tarikh=$year."-".$month."-".$day;
        $letter_body="mablagh  $mablagh rial baraie marhale $tayeed_marhale az tarh $cod_tarh dar tarikh $tarikh be hesab shomare $hesab_no variz shod ";
        send_sms("$telno",$letter_body,$admin);










		    $query="select * from user_login where email=\"$email\"";
			 
   $result=mysql_query($query) or die("error mail");
  if(mysql_num_rows($result) > 0 )
  {
      $row_fetched=mysql_fetch_array($result);
    
      $username=$row_fetched["email"];
      $password=$row_fetched["password"];
      $email=$username;
      $name_e=$row_fetched["name_e"];
      $family_e=$row_fetched["family_e"];
    
	
    }
	else
	{
	 ?>
       		 <script language="javascript">
       		 window.location="<? echo "feedback_report.phtml?admin=$admin&seed=$seed ";  ?>";
      		  </script>
       		 <?
	}
		  $mail = new PHPMailer();
    $emailbody="";
    $emailbody=$emailbody."<br><b>Please Do not reply this email<b><br><br>";
    $emailbody=$emailbody."<br>mablagh  $mablagh rial baraie marhale $tayeed_marhale az tarh $cod_tarh dar tarikh $tarikh be hesab shomare $hesab_no variz shod<br>";
   
    $emailbody=$emailbody."<center><font face=Arial size=2 color=green>This email has been sent by <a href=\"".$url_address."\">".$url_address."</a>";
    $emailbody=$emailbody."<br>Powered by Peyvand Co. (Peyvandco.com).</font></center>";
 
    $mail->IsSMTP();                                      // set mailer to use SMTP
    $mail->SMTPAuth=$smtpauth;
    $mail->Username=$email_username;
    $mail->Password=$email_password;
	                                      // set mailer to use SMTP
	$mail->host = "$mailserver_host";  // specify main and backup server
 
	//	$mail->Host = "$mailserver_host"; 
    $mailname=$familye." ".$name_e;
 
    $mail->From = $email_from;
	$mail->FromName = $email_from_name;
    $mail->AddAddress($email, $mailname);
    $mail->IsHTML(true);                                  // set email format to HTML

    $mail->Subject = "Payment From  $url_address";
    $mail->Body    = $emailbody;
    $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
     
    if(!$mail->Send())
    {
        echo "error";
    }
 
 
         //	 savelog($cod_tarh,$admin,'add','add hazine others to tarh '.$cod_tarh." by taksir equal ".$hazine_taksir);
        	 ?>
       		 <script language="javascript">
       		 window.location="<? echo "feedback_report.phtml?admin=$admin&seed=$seed ";  ?>";
      		  </script>
       		 <?
        	 
         }
     
  }
 if (strcmp($action,"delete_hazine")==0)
 {
    $query="delete from feedback_pardakht  where id = \"$delete_id\"  ";
    
    $result=mysql_query($query) or die("Error in  delete data from daneshjo ");
    	// savelog($cod_tarh,$admin,'delete','delete hazine others from tarh '.$cod_tarh." by id ".$delete_id);
 }

 


if(strcmp($action,"edit")==0) 
{
	$query="select * from feedback_pardakht  where id='$id' ";
	$result=mysql_query($query) or die("Error");
	if(mysql_num_rows($result) > 0)
	{
		$rf=mysql_fetch_array($result);
		$name=$rf["name"];
		$family=$rf["family"];
		$year=$rf["year"];
		$month=$rf["month"];
		$day=$rf["day"];
		$marhale=$rf["marhale"];
		$cod_tarh=$rf["cod_tarh"];
		$hesab_no=$rf["hesab_no"];
	    $mablagh=$rf["mablagh"];
		$id=$rf["id"];

	}
}
else 
{
  	$name='';
		$family='';
		$year='';
		$month='';
		$day='';
		$marhale='';
		$cod_tarh='';
		$hesab_no='';
	    $mablagh='';
 
}



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// old
?>

<? 

 if(strcmp($action,"edit")==0)
 {
   echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=edit_hazine_second&admin=$admin&seed=$seed&id=$id\">";
 }
 else
  {
   echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_hazine&admin=$admin&seed=$seed\">";
 }

 
 
 ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
 <TD align=right width="100%" style="background-position:right; background-repeat:no-repeat"   background="image/top_bg.gif" class='tahoma1' height=19>جدول پرداختي
      </TD>
  </TR>
 
</TABLE>



<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }

?>
   <tr>
    <td width="300" align="right"><input     onkeypress="return checkit()" value=<? echo "\"".$year."\""; ?> type="text" name="year" size="20"   class="edit-small-1"></td>
    <td width="200" class="tahoma1">سال</td>
  </tr>

  <tr>
    <td width="300" align="right"><input    onkeypress="return checkit()" value=<? echo "\"".$month."\""; ?> type="text" name="month" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >ماه</td>
  </tr>

  <tr>
    <td width="300" align="right"><input     onkeypress="return checkit()" value=<? echo "\"".$day."\""; ?> type="text" name="day" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >روز</td>
  </tr>
 <tr>
    <td width="300" align="right"><input dir=RTL      value=<? echo "\"".$name."\""; ?> type="text" name="name" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >نام</td>
  </tr>
 <tr>
    <td width="300" align="right"><input   dir=RTL     value=<? echo "\"".$family."\""; ?> type="text" name="family" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >نام خانوادگي</td>
  </tr> 
   <tr>
    <td width="300" align="right"><input   value=<? echo "\"".$cod_tarh."\""; ?> type="text" name="cod_tarh" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >کد طرح</td>
  </tr>
  <tr>
    <td width="300" align="right"><input   value=<? echo "\"".$marhale."\""; ?> type="text" name="marhale" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >مرحله</td>
  </tr>
  
 <tr>
    <td width="300" align="right"><input   value=<? echo "\"".$hesab_no."\""; ?> type="text" name="hesab_no" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >شماره حساب</td>
  </tr>

 <tr>
    <td width="300" align="right"><input  onkeyup="MakingMoneyForm(this)"   onkeypress="return checkit()" value=<? echo "\"".$mablagh."\""; ?> type="text" name="mablagh" size="20"  class="edit-small-1" ></td>
    <td width="200" class="tahoma1" >مبلغ</td>
  </tr>
 


  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>

<?
 
   $color="PALETURQUOISE";
   $query  = "select * from feedback_pardakht  where 1   ";
   
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi1212");
   
   if(mysql_num_rows($result) > 0)
   {
//   	$row_fetched=mysql_fetch_array($result);
    echo "<br>";
    echo "<table width=\"500\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \" >";
    echo "<tr>";
    echo "<table width=\"500\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \"  >";
    echo "<tr>";
    echo "<td  bgcolor=$color colspan=\"36\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\"><b>جدول پرداختي<b></p></td>";
     echo "</tr>";

    echo "<tr>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حذف</p></td>";
  echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ويرايش</p></td>";
 echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">مبلغ</p></td>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">شماره حساب</p></td>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">کد طرح</p></td>";
       echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">مرحله</p></td>";
        echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام خانوادگي</p></td>";
       echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام</p></td>";
        echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">روز</p></td>";
       echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ماه </p></td>";
      echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">سال</p></td>";


    echo "</tr>";
  $color="PALETURQUOISE";
   while($myrow_fetched=mysql_fetch_array($result))
   {
   
    echo "<tr bgcolor=\"$color\">";
    
    $sayer_hazine  = $myrow_fetched["sayer_hazine"];
    $hazine_taksir = $myrow_fetched["hazine_taksir"];
    $sum_hazine=$sayer_hazine+$hazine_taksir;
    $id= $myrow_fetched["id"];
    $delete_id=$id;
    
  //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=feedback_report.phtml&admin=$admin&seed=$seed&action=delete_hazine&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    
 echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\"><a href='$HP_SELF?admin=$admin&seed=$seed&id=$id&action=edit'><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
        echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["mablagh"]."</td>";

      echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["hesab_no"]."</td>";

       echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["cod_tarh"]."</td>";

     echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["marhale"]."</td>";
  
       echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["family"]."</td>";

       echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["name"]."</td>";

    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["day"]."</td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["month"]."</td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["year"]."</td>";
    echo "</tr>";
   }
   echo "</table>";

  }
 
 
 footer_forms($admin,$seed);
?>

