<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/class.phpmailer.php");
include("include/mailserver-statistics.phtml");
require_once('lib/nusoap.php');

echo "<br>";

if(isset($action))
{
  if (strcmp($action,"change_status")==0 )
  {
  	$query="select * from dastoor_pardakht_marhale,marhale_gharardad_hesabdari where dastoor_pardakht_marhale.marhale_gharardad_id=marhale_gharardad_hesabdari.id and stepno='100' and dastoor_pardakht_marhale.paperno='$paperno'";
  	$result=mysql_query($query) or die("error ");
     	while($row_fetched=mysql_fetch_array($result)){
     	$cod_tarh=$row_fetched["researchno"];
  	
     $query="update tarh set finalized ='1' where cod_tarh='$cod_tarh'";
       	 $result2=mysql_query($query) or die("Error");
		 insert_position($cod_tarh,"11",$admin);
     	}
     $query="update dastoor_pardakht set finish ='1' where paperno='$paperno'";
       	 $result=mysql_query($query) or die("Error");
		 
     ?>
           <script language="javascript">
           window.location="<? echo "dastoor_pardakht_list_finish".".phtml?admin=$admin&seed=$seed";  ?>";
           </script>
           <?
  }

}

?>

<? echo "<form name=\"change_status\" method=\"post\" action=\"$PHP_SELF?action=change_status&admin=$admin&seed=$seed&paperno=$paperno&main_window=$main_window\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 width="100%" cellPadding=0 border=1>
  <TBODY>
    <TR>
    <TD align=right width="100%"  class="tahoma1" height=19>
     
      خاتمه يافته کردن دستور پرداخت
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


 <tr>
    <td width="100%" colspan="2" class="tahoma1">
      <p align="center">خاتمه يافته کردن دستور پرداخت</td>
</tr>

<tr>
    <td width="100%" colspan="2" class="tahoma1" dir='rtl'>
      <p align="center">با خاتمه يافته کردن دستور پرداخت تمام طرح هاي با مرحله 100 اين ليست به طرح هاي خاتمه يافته منتقل ميشوند</td>
</tr>
 
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="#" onClick="history.go('-1')" >بازگشت</a></td>
  </tr>
</table>
<?

  footer_forms($admin,$seed);
 ?>




