<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

if(isset($action))
{
  $ptr1="i0"; 	
  $mablagh1=0;
  for($i=0;$i<=100;$i++)
  {
  	$ptr1="i".$i;
  	$mablagh=$$$ptr1;
  //	echo $mablagh."<br>";
  //	if($mablagh > 0 && $mablagh < 100 )
    	$mablagh1=$mablagh1+(int)$mablagh;
  }
  //echo $mablagh1;
  //exit();
  if($mablagh1==100)
  {
  if(strcmp($action,"sabt_zamanbandi")==0)
  {
  	$ptr1="i0";
	$query="select * from gozaresh_gharardad where marhale='0' and cod_tarh='$cod_tarh'";
  	$result=mysql_query($query) or die("Error 800");
  	if(mysql_num_rows($result) > 0)
  	{
  	  $mablagh=$$$ptr1;
  	  $query="update gozaresh_gharardad set mablagh ='$mablagh' where cod_tarh='$cod_tarh' and marhale='0'";
	  $result=mysql_query($query) or die("Error 800");
  	}
  	else
  	{
  	  $query00="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'"; 
      $result00=mysql_query($query00) or die("Error10");
      if(mysql_num_rows($result00)>0)
      {
 	      $row_fetched00=mysql_fetch_array($result00);
     	  $start_time=$row_fetched00["start_time"]; 	 	 	 	
     	  $time_month=$row_fetched00["time_month"];     	
      }
  
  	  $mablagh=$$$ptr1;
  	  $query="insert into gozaresh_gharardad set mablagh ='$mablagh' , cod_tarh='$cod_tarh' ,date_gozaresh='$start_time', marhale='0'";  	  
      $result=mysql_query($query) or die("Error 800");
  	}
  	
  	
  	
  	
  	 for($i=0;$i<=100;$i++)
  	 {
  	  	$ptr1="i".$i;
  	  	$myid=$$ptr1;
  	  	
  	    if(isset($$myid))
		{	
		  $myid=substr($myid,1);
		  
	      $query="select * from gozaresh_gharardad where id='$myid' and cod_tarh='$cod_tarh'";
  	      
		  $result=mysql_query($query) or die("Error 800");
  	      if(mysql_num_rows($result) > 0)
  	      {
  	        $mablagh=$$$ptr1;
  	        $query="update gozaresh_gharardad set mablagh ='$mablagh' where id='$myid'";
  	      
	        $result1=mysql_query($query) or die("Error 8000");
	          echo $query;
  	       }
		}
  	  
  	}
  	
  	
  	
  //s	exit();
  	
  	
  	
  	
  	
  	
  	
  	
  	
  	/*
  	
  	if( $start_time > 0 && $time_month > 0 )
    {
     $year=substr($start_time,0,4);
     $month=substr($start_time,5,2);
     $day=substr($start_time,8,2);
     $start_time=$year."-".$month."-".$day;
     $month_add=$time_month+$month;
     if($month_add > 12 )
     {
       $year_add=(int)($month_add/12); 
	   $year=$year+$year_add;	 	 	
       $month=$month_add-($year_add*12);     
    
     }
   else
     $month=$month_add;
   
     $end_time=$year."-".$month."-".$day;
    }
    else
     $end_time=0;
  	$ptr1="i100";
	$query="select * from gozaresh_gharardad where marhale='100' and cod_tarh='$cod_tarh'";
	
  	$result=mysql_query($query) or die("Error 800");
  	if(mysql_num_rows($result) > 0)
  	{
  	  $mablagh=$$$ptr1;
  	  $query="update gozaresh_gharardad set mablagh ='$mablagh' where cod_tarh='$cod_tarh' and marhale='100'";
  	  
	  $result=mysql_query($query) or die("Error 800");
	  
  	}
  	else
  	{
  	  $query00="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'"; 
      $result00=mysql_query($query00) or die("Error10");
      if(mysql_num_rows($result00)>0)
      {
 	      $row_fetched00=mysql_fetch_array($result00);
     	  $start_time=$row_fetched00["start_time"]; 	 	 	 	
     	  $time_month=$row_fetched00["time_month"];     	
      }
  
  	  $mablagh=$$$ptr1;
  	  $query="insert into gozaresh_gharardad set mablagh ='$mablagh' , cod_tarh='$cod_tarh' ,date_gozaresh='$end_time', marhale='100'";  	  
      
	  $result=mysql_query($query) or die("Error 800");
  	}
*/
  	?>
          <script language="javascript">
           window.location="<? echo "new_gharardad.phtml?admin=$admin&seed=$seed";  ?>";
          </script>
          <?
  }
  }
  else
   $status="sum_error";
}

echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=sabt_zamanbandi&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
$query="select * from gozaresh_gharardad  where  cod_tarh=\"$cod_tarh\" ";
echo "<br>";
 $result=mysql_query($query) or die("Error in query data from tarh-type");
 if(mysql_num_rows($result) > 0)
 {
	echo "<table border=\"0\" width=\"500\" bgcolor=\"#EEE7F8\"  cellspacing=\"0\" cellpadding=\"2\"  bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
    echo "<tr>";   
    echo "<td colspan=3 width=\"100%\" align=\"center\"  height=\"20\" class=\"tahoma1\" align=\"center\"><b>تاريخ گزارشات طرح</b></td>";        
    echo "</tr>";
    echo "<tr>";   
    echo "<td width=\"100\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">درصد کار</td>";    
    echo "<td width=\"200\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">تاريخ </td>";
    echo "<td width=\"200\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">مرحله</td>";
    $cntr=0;
    
    $query00="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
    $result00=mysql_query($query00) or die("Error10");
    if(mysql_num_rows($result00)>0)
    {
 	  $row_fetched00=mysql_fetch_array($result00);
  	  $start_time=$row_fetched00["start_time"]; 	 	 	 	
 	  $time_month=$row_fetched00["time_month"];     	
    }
  
    if( $start_time > 0 && $time_month > 0 )
    {
     $year=substr($start_time,0,4);
     $month=substr($start_time,5,2);
     $day=substr($start_time,8,2);
     $start_time=$year."-".$month."-".$day;
     $month_add=$time_month+$month;
     if($month_add > 12 )
     {
       $year_add=(int)($month_add/12); 
	   $year=$year+$year_add;	 	 	
       $month=$month_add-($year_add*12);     
    
     }
   else
     $month=$month_add;
   
     $end_time=$year."-".$month."-".$day;
    }
 else
  {
    $end_time="تعريف نشده";   
  }
   $q="select * from gozaresh_gharardad where cod_tarh='$cod_tarh' and marhale='0'";
   $rslt=mysql_query($q) or die("Error");
   if(mysql_num_rows($rslt) > 0)
   {
   	 $myrf=mysql_fetch_array($rslt);
  	 $mablagh=$myrf["mablagh"];
   }
  else
   $mablagh=0;
   $id=0; 
   if(strcmp($status,"sum_error")==0)
   {
   	 echo "<tr bgcolor=\"$color\">";  
     echo "<td colspan=\"3\" width=\"100%\">";
     echo "<p align=\"center\"  class=\"tahoma1\"><b>مجموع درصدها بايد 100 باشد</b></td>";  
     echo "</tr>";
   
   }
/*   echo "<tr bgcolor=\"$color\">";  
   echo "<td width=\"100\">";
   echo "<p align=\"center\"  class=\"tahoma1\"><input type=\"hidden\" name=\"i".$cntr."\" size=\"20\" value='p$id'><input value=\"$mablagh\" type=\"text\" name=\"p$id\" size=\"20\"></td>";
   echo "<td width=\"200\">";
   echo "<p align=\"center\"  class=\"tahoma1\">$start_time</td>";   
   echo "<td width=\"200\">";
   echo "<p align=\"center\"  class=\"tahoma1\">گزارش اول</td>";  
   echo "</tr>";
  */  
    
  $Query=mysql_query("select * from gozaresh_gharardad  where cod_tarh='$cod_tarh'   order by marhale asc " ) or die("Error in selecting tarh-type");
  $cntr=0;
  while($row_fetched=mysql_fetch_array($Query))
  {
   $id=$row_fetched["id"];	
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
   echo "<tr bgcolor=\"$color\">";  
   echo "<td width=\"100\">";
   echo "<p align=\"center\"  class=\"tahoma1\"><input type=\"hidden\" name=\"i".$cntr."\" size=\"20\" value='p$id'><input type=\"text\" name=\"p$id\" size=\"20\" value=\"".$row_fetched["mablagh"]."\"></td>";
   echo "<td width=\"200\">";
   echo "<p align=\"center\"  class=\"tahoma1\">".substr($row_fetched["date_gozaresh"],0,100)."</td>";   
   echo "<td width=\"200\">";
   $marhale=$row_fetched["marhale"];
   if(strcmp($row_fetched["marhale"],'0')==0)
     $marhale="اول";
  
   if(strcmp($row_fetched["marhale"],'100')==0)
     $marhale="نهايي";
     
   echo "<p align=\"center\"  class=\"tahoma1\">".$marhale;
   echo "</td>";
  
   echo "</tr>";
   $cntr++;
 
  }
  if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
  $id=-2;
  
  
  
  $q="select * from gozaresh_gharardad where cod_tarh='$cod_tarh' and marhale='100'";
  $rslt=mysql_query($q) or die("Error");
  if(mysql_num_rows($rslt) > 0)
  {
  	$myrf=mysql_fetch_array($rslt);
  	$mablagh=$myrf["mablagh"];
  }
  else
   $mablagh=0;
  
 /* echo "<tr bgcolor=\"$color\">";  
  echo "<td width=\"100\">";
  echo "<p align=\"center\"  class=\"tahoma1\"><input type=\"hidden\" name=\"i100\" size=\"20\" value='p100'><input value=\"$mablagh\" type=\"text\" name=\"p100\" size=\"20\"></td>";
  echo "<td width=\"200\">";
  echo "<p align=\"center\"  class=\"tahoma1\">$end_time</td>";   
  echo "<td width=\"200\">";
  echo "<p align=\"center\"  class=\"tahoma1\">گزارش نهايي</td>";
  */
  echo "</tr>";
  echo "<tr bgcolor=\"$color\">";  
  echo "<td colspan='3' width=\"100%\" align=\"center\">";
  echo "<input type=\"submit\" value=\"Submit\" name=\"B1\"></td>";
  echo "</tr>";
  echo "</table>";

}
  echo "</form>"; 
  footer_forms($admin,$seed);
 ?>
