<?

global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;
include("include/database-connect.phtml");
include("include/include.phtml");
if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type == 1 )
    updatesession($username,$rand);
  else
  {
   header ("Refresh: 0; url=../login.phtml");
   exit();
  }
 }
 


include("include/styles.phtml");
include("include/vars.inc.phtml"); 
?>

<html>
<head>
    <title>Warning</title>
    <meta http-equiv="Content-Language" content="fa">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

</head>
<body>
<?
include("include/styles.phtml");
?>
<script language="javascript">
var w = 250;
var h = 120;
var winl = (screen.width-w)/2;
var wint = (screen.height-h)/2;
if (winl < 0) winl = 0;
if (wint < 0) wint = 0;

mywin=parent.window;

mywin.moveTo(winl,wint);

var x=10
for (i=0;i,i<50;i++){
mywin.moveBy(0,x)
mywin.moveBy(x,0)
mywin.moveBy(0,-x)
mywin.moveBy(-x,0)
}
</script>

<script language="javascript">
function refreshmain()
{
   opener.location="<? echo "$mainwindow?admin=$admin&seed=$seed&action=$action&delete_id=$delete_id&cod_tarh=$cod_tarh&marhale=$marhale"; ?>";

   self.close();
}

</script>

<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="5">
<tr>
<td align="center">
<p align="center" class="tahoma1">آيا مايل به حذف هستيد ؟
</td>
</tr>

<tr>
<td align="center" colspan="2">
<input type="button" value="خير" name="delete" class="but-small"  onclick="javascript: window.close()">&nbsp;<input type="button" value="بلي" name="cancel" class="but-small" onClick="refreshmain()" >
</td>
</tr>
</table>
</body>
</html>
