<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
//require("include/class.phpmailer.php");
//require("include/mailserver-statistics.phtml");

echo "<br>";


$RecPerPage=30;
//confirm_tarh=1
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
    
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if ( ! isset($tarh_year))
    $tarh_year = '-1';




if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

//echo $tarh_year;
if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;


if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}


$query="select * from nazer_mali where username='$admin'";
 
$result=mysql_query($query) or die("Error");
$rf=mysql_fetch_array($result);
$sms_box=$rf["sms_box"];
 if($sms_box > 0 )
 {
  $sms_box="sms_to='$sms_box' or sms_to='+98$sms_box' ";
  
 }
 else
  $sms_box='0';
  
if(isset($name_e)  && strlen(trim($name_e))>0)
{
  $query="select * from input_sms where    (sms_text like $myname_search) and   $sms_box  order by id desc  ";
}
else
  $query="select * from input_sms where    $sms_box order by id desc " ;

 

$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e) && strlen(trim($name_e))>0)
{
  $query="select * from input_sms where    (sms_text like $myname_search) and   $sms_box order by id desc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from input_sms where   $sms_box  order by id desc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;

 

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>ليست پيام هاي کوتاه<b></td>
 </tr>
 
 </table> 
 
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    

echo "<td  align=\"left\" class=\"tahoma1\"></td>";
 
?>

 

  
  
  
   

<?
 
 echo "<td  align=\"left\" class=\"tahoma1\"> </td>";
 
  
 
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 
 </tr>


 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 //$myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";	
	
 pubshowpages("list_received_sms.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
     <td width="35%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">متن SMS</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">شماره همراه</font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
 	
   
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["sms_text"]."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"> ".$row_fetched["sms_from"]."</td>";
 
  echo "</tr>";

 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show("پيام کوتاهي يافت نشد","red");
}
 
  
footer_forms($admin,$seed);


?>
