<?
include("include/database-connect.phtml");

include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
//require_once('lib/nusoap.php');
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");
//$karshenasi_koll_1=mablagh_karshenasi($cod_tarh);
include ("../sms/include/WebServiceSms.php");
include ("../sms/send_long_sms.php");

if(isset($action))
 if(strcmp($action,"accept_payment")==0)
 {
  for($i=0;$i<10;$i++)
  {
    $id_pardakht="myid".$i;
    
    if(isset($$id_pardakht))
    {
       $id_pardakht=$$id_pardakht;
       $id_payment_status="radio".$i;
       $id_payment_status=$$id_payment_status;
       $query="update tarh_old_pardakht set tayeed_pardakht='$id_payment_status' where id='$id_pardakht'";
        
       $result=mysql_query($query) or die("Error");
       if($id_payment_status > 0)
       {
         $action="<br>".$cod_tarh."مربوط به طرح".$id_pardakht."تاييد پرداخت مرحله";
          set_log($action,$admin,date("Y-m-d, g:i a"));
       }  
	    $query="update tarh_old  set email='$email',mobile='$mobile' where cod_tarh='$cod_tarh'";
        
       $result=mysql_query($query) or die("Error oo");
      
      
       
     	if($tayeed_marhale==0)
     	  $tayeed_marhale=1;
     	
		if($tayeed_marhale==100)
     	  $tayeed_marhale='final';
        
        $action="تاييد پرداخت مرحله "."<br>".$tayeed_marhale."<br>".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
       // $letter_body="marhale ".$tayeed_marhale." az tarh ".$cod_tarh." tayeed shod ";
        //echo $letter_body."<br>".$mobile."<br>".$admin;
       // send_sms("$mobile",$letter_body,$admin);
       $message_string="پژوهشيار:مرحله $tayeed_marhale از طرح با کد $cod_tarh تاييد شد. research.tums.ac.ir";
		//$message_string=iconv("windows-1256", "UTF-8",$message_string);
		$subject="تاييد مرحله طرح توسط ناظر مالي";
		$massage_id=send_long_sms($message_string,$mobile,$subject);
        
     
     
     
     
   

    $mail = new PHPMailer();
    $emailbody="";
    
    $emailbody=$letter_body;
    $emailbody=$emailbody."<br>Powered by Peyvand Co. (Peyvandco.com).</font></center>";

    $mail->IsSMTP();                                      // set mailer to use SMTP
    $mail->SMTPAuth=$smtpauth;
    $mail->Username="";
    $mail->Password="";
	                                      // set mailer to use SMTP
	$mail->Host = $mailserver_host;  // specify main and backup server
    $mailname=$familye." ".$name_e;
    $mail->From = $email_from;
	$mail->FromName = $email_from_name;
    $mail->AddAddress($email, $mailname);
    $mail->IsHTML(true);                                  // set email format to HTML

    $mail->Subject = "Payane Marhale Nezarat Gozaresh marhale $tayeed_marhale marbot be tarh $cod_tarh dar modiriat omore pajoohesh";
    $mail->Body    = $emailbody;
    $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
    if(!$mail->Send())
    {
        $status="mail_err";
    }
     
      
        //$letter_body="Tayeed Pardakht marhale ".$tayeed_marhale. " tarh ".$cod_Tarh." tayeed shod ";
        //echo $mobile;
        
        // send_sms($mobile,$letter_body,$admin);
       // send_sms_old($mobile,$letter_body);
       //echo $query;
    }
  }
 }
 
 
 if(strcmp($action,"del")==0)
 {
    $query="delete from  tarh_old_pardakht where  id='$delete_id' ";
    	  
     $result=mysql_query($query) or die("Error");
       if($id_payment_status > 0)
       {
         $action="<br>".$cod_tarh."حذف پرداخت مربوط به طرح";
          set_log($action,$admin,date("Y-m-d, g:i a"));
       }   
    
 
 }
 
 
echo "<br>";
$query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";
$result=mysql_query($query) or die("Error");
$my_rf=mysql_fetch_array($result);
$tarh_name=$my_rf["tarh_name"];

echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=accept_payment&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
   

    
    
     $query="select * from tarh_old_pardakht where  cod_tarh='$cod_tarh' order by marhale  asc";
     $result=mysql_query($query) or die("Error");
     if(mysql_num_rows($result) > 0)
	 {
     echo "<table border=\"0\" width=\"90%\"  cellspacing=\"1\" cellpadding=\"1\" >";
     echo "<tr>";
     echo "<td align=\"center\" colspan='6'  width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$tarh_name</b></td>";   
     echo "</tr>";
     
     $color="PALETURQUOISE";
     
     echo "<tr>";
       echo "<td align=\"center\" colspan='6'  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>($cod_tarh)پرداختها</b></td>";
     echo "</tr>";
     
     echo "<tr>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>حذف</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>پرداخت نشده</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>پرداخت شده</b></td>"; 
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مبلغ</b></td>";
      echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>تاريخ پرداخت</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مرحله</b></td>";   
     echo "</tr>";
     $mycntr=0;
     while($row_fetched=mysql_fetch_array($result))
     {
     $id=$row_fetched["id"];	
     $marhale=$row_fetched["marhale"];	
     $mablagh=$row_fetched["mablagh"];
     $tayeed_pardakht=$row_fetched["tayeed_pardakht"];
     $date_pardakht=$row_fetched["date_pardakht"];
     echo "<tr>";
     if($tayeed_pardakht==1)
     {
       $ok_checked=" checked ";
       $no_checked=" ";
     }
     else
     {
       $ok_checked=" ";
	   $no_checked=" checked ";
	   
     }  
     echo "<input name='myid$mycntr'   type='hidden' value='$id'>";
     echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=old_tarhs_payments.phtml&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&action=delete_tarh_payment&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a</td>";
	 echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><input name='radio$mycntr' $no_checked type='radio' value='0'></td>";  
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><input name='radio$mycntr' $ok_checked type='radio' value='1'></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>". number_format($mablagh)."</b></td>";
          echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b> $date_pardakht</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$marhale</b></td>";
     echo "</tr>";
      $mycntr++;
     }
     $query="select * from  tarh_old   where cod_tarh='$cod_tarh'";
        
     $result1=mysql_query($query) or die("Error");
     $rf=mysql_fetch_array($result1) or die("Error");
     $mobile=$rf["mobile"];
     $email=$rf["email"];
	  
     echo "<tr>";
     echo "<td width=\"100%\" colspan=\"3\">";
     echo "<p align=\"right\"><input type=\"text\" value='$mobile'  name=\"mobile\" class=\"but-small\"></td>";
     echo "<td width=\"100%\" colspan=\"3\"  class='tahoma1'>";
     echo "<p align=\"left\">: شماره موبايل</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"100%\" colspan=\"3\">";
     echo "<p align=\"right\"><input type=\"text\"  value='$email' name=\"email\" class=\"but-small\"></td>";
     echo "<td width=\"100%\" colspan=\"3\" class='tahoma1'>";
     echo "<p align=\"left\">: آدرس ايميل</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"100%\" colspan=\"6\">";
     echo "<p align=\"center\"><input type=\"submit\" value=\"تاييد\" name=\"B1\" class=\"but-small\"></td>";
     echo "</tr>";
     echo "</table>";
	 }
	 else
	  message_show("مبلغي پرداخت نشده","red");
  echo "</form>"; 
   
footer_forms($admin,$seed);
?>

