<?
include("include/database-connect.phtml");
include("include/session.phtml");

function DBreccount($DBname)
{

  $query="select count(*) as mycnt from $DBname";
  $result = mysql_query($query);
  $row_fetched = mysql_fetch_array($result);
  return strval($row_fetched["mycnt"]);

}

//---------------------------------------------------------------------------------------

function insert_position($cod_tarh,$position,$admin)
{
	
  $action_date=date("Y-m-d");
  $query="insert into tarh_position set cod_tarh='$cod_tarh',position='$position',creator='$admin',action_date='$action_date' ";

  $result=mysql_query($query) or die("Error in inserting data into position");
}

//---------------------------------------------------------------------------------------

function current_position($cod_tarh)
{
  $query="select * from  tarh_position where  cod_tarh='$cod_tarh' order by id desc";
  
  $result_position=mysql_query($query) or die("Error in selecting data from position");
  if(mysql_num_rows($result_position) > 0 )
  {
  	$row_fetched_position=mysql_fetch_array($result_position);
  	$position=$row_fetched_position["position"];
  	return $position;
  	
  }
  else 
   return -1;  // no record in position database for this tarh
  
}
//---------------------------------------------------------------------------------------


function delete_file($base_dir,$dir,$file_name_ok)
{
  $mybasedir= getcwd();
  if(strlen(trim(dir)) > 0)
     $filename=$base_dir."/".$dir."/".$file_name_ok;
  else
     $filename=$base_dir."/".$file_name_ok;
  $dirname=$base_dir."/".$dir;
 // echo $filename;
  @unlink($filename);
  if(strlen(trim($dir)) > 0 and strlen(trim($file_name_ok)) <= 0)
  {
  	
    clr_dir($dirname);
  }
  chdir("$mybasedir");
  return -4;
}
//----------------------------------------------------------------

function clr_dir($dir) {
if(@ ! $opendir = opendir($dir)) {
return false;
}
while(false !== ($readdir = readdir($opendir))) {
if($readdir !== '..' && $readdir !== '.') {
$readdir = trim($readdir);
if(is_file($dir.'/'.$readdir)) {
if(@ ! unlink($dir.'/'.$readdir)) {
return false;
}
} elseif(is_dir($dir.'/'.$readdir)) {
// Calls itself to clear subdirectories
if(! clr_dir($dir.'/'.$readdir)) {
return false;
}
}
}
}
closedir($opendir);
if(@ ! rmdir($dir)) {
return false;
}
return true;
}

//---------------------------------------------------------------------------------------

function upload_file($base_dir,$dir,$file_name_ok)
{
// -1    bad file size
// -2    bad extention
// -3    bad file size
// -4    can not upload
// -5    directory exists
// -6    file exists
// $ext  extion of uploaded file
// global $userfile,$userfile_name,$userfile_size,$userfile_type,$archive_type,$archive_dir,$WINDIR;
// 10  file uploaded
$mybasedir= getcwd();
//echo $mybasedir;
global $_FILES,$max_file_size;


// global $fupload,$fupload_name,$fupload_size,$fupload_type,$max_file_size;
$fupload=$_FILES["fupload"]['tmp_name'];
$fupload_name=$_FILES["fupload"]["name"];
$fupload_size=$_FILES["fupload"]["size"];
$fupload_type=$_FILES["fupload"]["type"];

//echo "1-$fupload_name------   $max_file_size";
// echo "-->$fupload<br>";
// echo "-->$fupload_name<br>";
// echo "-->$fupload_size<br>";
// echo "-->$fupload_type<br>";

// if(isset($WINDIR))
//    $userfile=str_replace("\\\\","\\",$userfile);


//echo $filename;

$filename=basename($fupload_name);

//$ff1=strstr($filename,".");
$ff1=$filename;
$ii=0;
while(strchr(substr($ff1,1,strlen($ff1)-1),"."))
{
/*	if($i++>5)
	exit();*/
  $ff1=strstr(substr($ff1,1,strlen($ff1)-1),".");
  //echo $ff1."<br>";
}
 $ff1=strtolower($ff1);
 


/*if($fupload_size<=0)
 return -3;
if($fupload_size>2000000000)
  return -1;
*/
if (!file_exists($base_dir))
  mkdir($base_dir,0770);

if(chdir($base_dir))
{
  if(strlen(trim($dir)) > 0)
   if (!file_exists($dir))
     mkdir("$dir",0770);
}
else
return -9;

if(strcmp($ff1,"application/msword")!=0)
 $ext="msword";
else
 if(strcmp($ff1,"application/pdf")!=0)
   $ext="msword";
 else
   if(strcmp($ff1,"image/pjpeg")!=0)
    $ext="msword";
   else
     if(strcmp($ff1,"image/gif")!=0)
       $ext="msword";

$ext=substr(strchr($ff1,"."),1);

if(strlen(trim($file_name_ok)) > 0 )
  $fupload_name = $file_name_ok;

if(strlen(trim($dir)) > 0)
  $filename_upload="$dir/$fupload_name";
else
  $filename_upload="$fupload_name";


if(!@file_exists("$filename_upload"))
{
  if(!@copy ( $fupload,"$filename_upload"))
  {
    chdir("$mybasedir");
    return -4;
  }
  else
  {
   chdir("$mybasedir");
   return 10;
  }
}
else
{
  chdir("$mybasedir");
  return -5; // duplicate enter
}
chdir("$mybasedir");
return $ext;
}

//---------------------------------------------------------------------------------------


function footer_forms($admin,$seed)
{
?>

   </td>
      </tr>
    </table></TD>
    <TD width="150" valign="top" background="img_data/right_td_back.jpg">
        <table width="150" border="0" cellpadding="0" cellspacing="0" background="img_data/right_td_back.jpg" height="429">
            <!--DWLayoutTable-->
            <tr>
              <td height="19" valign="top"><img src="img_data/top_2.jpg" width="150" height="19"></td>
            </tr>
			<tr>
              <td height="241" valign="top" align="center">
				<table width="150" border="0" cellpadding="0" cellspacing="0" background="img_data/buts_back.jpg" height="275">
                <!--DWLayoutTable-->
                <tr>
                  <td width="150" height="275" valign="top">
					<table border="0" width="140" height="305">
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "tarh_list.phtml?admin=$admin&seed=$seed"; ?>" >وضعيت طرحهاي تحقيقاتي</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "ready_contract.phtml?admin=$admin&seed=$seed"; ?>" >طرحهاي آماده به قرارداد</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "in_doing.phtml?admin=$admin&seed=$seed"; ?>" >طرح هاي در حال اجرا</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "finished.phtml?admin=$admin&seed=$seed"; ?>" >طرح هاي پايان يافته</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "license_agrement.phtml?admin=$admin&seed=$seed"; ?>" >ارسال طرح تحقيقاتي</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "profile.phtml?admin=$admin&seed=$seed"; ?>" >تغيير پروفايل</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "chg_pass.phtml?admin=$admin&seed=$seed"; ?>" >تغيير رمز عبور</a></span></td>
						</tr>
							<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><img src="image/new.gif" ><a href="<? echo "informatics.phtml?admin=$admin&seed=$seed"; ?>" >اطلاع رساني</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "letter_list.phtml?admin=$admin&seed=$seed"; ?>" >ليست نامه ها</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "activities.phtml?admin=$admin&seed=$seed"; ?>" >شرح فعاليتها</a></span></td>
						</tr>
						<tr>
							<td style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href="<? echo "logout.phtml?admin=$admin&seed=$seed"; ?>" >خروج</a></span></td>
						</tr>
					
					</table>
				  </td>
                </tr>
              </table><span class="tahoma1"><b>F7 = تغيير زبان</b></span>
<SCRIPT language=JavaScript>var clocksize=100;</SCRIPT>
                  <SCRIPT src="js/clock.js"></SCRIPT>
                  
			  </td>
            </tr>
			<tr>
              <td height="189" width="150" valign="top" align="center">&nbsp;</td>
            </tr>
        </table>

		</TD>
  	</tr>
	<tr>
	  <TD height=27 colspan="2" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="img_data/down_td_back.jpg">
            <!--DWLayoutTable-->
            <tr>
              <td width="164" height="24" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="img_data/down_td_back_2.jpg">
                  <!--DWLayoutTable-->
                  <tr>
                    <td width="7" height="24"></td>
                    <td width="136" valign="top"><a href="http://www.rahpouyanco.com" target="_blank"><img src="img_data/rah_pic_down.jpg" width="136" height="24" border="0"></a></td>
                    <td width="7"></td>
                    <td width="14" valign="top"><img src="img_data/down_td_pic.jpg" width="14" height="24"></td>
                  </tr>
              </table></td>
              <td width="631" style="font-size: 7pt; font-family: Tahoma; color: #E8EAF6" align="center">
				<p align="right">
				<span lang="fa">راهنما&nbsp; |&nbsp; </span>English&nbsp;&nbsp;&nbsp;&nbsp; </td>
              <td width="5" rowspan="2" valign="top"><img src="img_data/down_td_back.jpg" width="1" height="24"></td>
            </tr>
            <tr>
              <td height="3"></td>
              <td></td>
            </tr>
      </table></TD>
    </tr>
</TABLE>
</CENTER>
</BODY></HTML>







   <?

}

//---------------------------------------------------------------------------------------

function header_forms($admin,$seed)
{

global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type == 2 )
   {
    if(isset($cod_tarh))
	{
	   $q="select * from tarh where cod_tarh='$cod_tarh' and creator='$admin'";
	   echo $q;
	   $rs=mysql_query($q) or die("dffdfgd");
	   if(mysql_num_rows($rs) <= 0)
	     {
		 	 header ("Refresh: 0; url=../login.phtml");
  			 exit();
		 }
	}
    updatesession($admin,$seed);
  }
  else
  {
   header ("Refresh: 0; url=../login.phtml");
   exit();
  }
 }
 else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }

$myq="select * from user_login where email='$admin'";
$res=mysql_query($myq) or die("Error");
$rf=mysql_fetch_array($res);

$name_family=$rf["name"]."&nbsp;".$rf["family"];

  ?>

<HTML><HEAD>
<TITLE> <? echo $name_family; ?></TITLE>

<STYLE type=text/css>
BODY {
	SCROLLBAR-FACE-COLOR: #003366;
	SCROLLBAR-HIGHLIGHT-COLOR: #000000;
	SCROLLBAR-SHADOW-COLOR: #000000;
	SCROLLBAR-3DLIGHT-COLOR: #a1a1a1;
	SCROLLBAR-ARROW-COLOR: #000000;
	SCROLLBAR-TRACK-COLOR: #bfbfbf;
	SCROLLBAR-DARKSHADOW-COLOR: #ffffff;
	SCROLLBAR-BASE-COLOR: #a1a1a1;
	background-color: #CCCCCC;
}

a:link {
	color: #333333;
	text-decoration: none;
}
a:visited {
	color: #333333;
	text-decoration: none;
}
a:hover {
	color: #7592B5;
	text-decoration: none;
}
a:active {
	color: #6072DE;
	text-decoration: none;
}

</STYLE>
<SCRIPT language=JavaScript type=text/JavaScript>
function MakingMoneyForm(me)
				{
				
					if((event.keyCode==13) || (event.keyCode==9) || (event.keyCode==39) || (event.keyCode==37) || (event.keyCode==16))
						return;

					var TempStr = ''
					
					while(me.value.indexOf(',') != -1)
						me.value = me.value.replace(',','')
					
					var R = me.value.length % 3;
					TempStr =  me.value.substring(0,R);
					for(var i = R ; i < me.value.length ; i++ )
					{
						if ((me.value.length-i)%3==0)
						{
							TempStr = TempStr + "," + me.value.substring(i,i+1) 
						}
						else 
							TempStr = TempStr +  me.value.substring(i,i+1) 
					}
					
					//Removing First ','
					if(TempStr.substring(0,1) == ",")
						TempStr = TempStr.substring(1,TempStr.length)
					
					me.value=TempStr

						
				}

</SCRIPT>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></HEAD>
<script language="javascript" src="js/farsi.js"></script>
<BODY leftMargin=0 topMargin=0 >
<CENTER>
<TABLE borderColor=black cellSpacing=0 cellPadding=0 width=800 bgColor=#ffffff border=0 height="611"><!--DWLayoutTable-->
  <tr>
    <TD height=117 colspan="2" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <!--DWLayoutTable-->
        <tr>
          <td height="19" colspan="3" background="img_data/top_1_01.jpg" style="font-size: 7pt; font-family: Tahoma; color: #666666">
			<span lang="fa">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</span>&nbsp;
			<span lang="fa">تاريخ :&nbsp; <span dir="rtl"><? echo today();?></span>&nbsp;&nbsp;&nbsp; ساعت :
			<? echo date("H:i"); ?></span></td>
          <td width="93" rowspan="2" valign="top"><img src="img_data/top_1_02.jpg" width="93" height="98"></td>
          <td width="108" rowspan="3" valign="top"><img src="img_data/top_1_03.jpg" width="108" height="117"></td>
          <td width="274" rowspan="3" valign="top"><img src="img_data/top_1_04.jpg" width="274" height="117"></td>
        </tr>
        <tr>
          <td width="46" height="79" valign="top"><img src="img_data/top_1_05.jpg" width="46" height="79"></td>
          <td width="155" valign="top"><img src="img_data/top_1_06.jpg" width="155" height="79"></td>
        <td width="124" valign="top"><img src="img_data/top_1_07.jpg" width="124" height="79"></td>
        </tr>
        <?
		 $query="select * from user_login where email = '$admin'";
		 $result=mysql_query($query) or die("Error in selecting data from user_login");
		 if(mysql_num_rows($result) >0 )
		 {
		    $row_fetched = mysql_fetch_array($result);
		    $name = $row_fetched["name"];
		    $family = $row_fetched["family"];
		 }
		?>
        <tr>
          <td height="19" colspan="4" valign="bottom" background="img_data/top_1_0888.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
			<span lang="fa">نام کاربر : <? echo $name."&nbsp;".$family; ?></span></td>
          </tr>
        </table></TD>
    </tr>
	<tr>
    <TD width="651" height="476" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
      <!--DWLayoutTable-->
      <tr>
        <td width="650" height="476" align="center" valign="top">







  <?

}

//-----------------------------------------------------------------------

function admin_type($admin)     // 0 == admin daneshkade  1== admin kol
{
  $query="select * from modir_daneshkade where modir_username=\"$admin\"";
  $result=mysql_query($query) or die("Error in selectiong data from modir daneshkade");
  if(mysql_num_rows($result) > 0)
  {
   $row_fetched=mysql_fetch_array($result);
   return $row_fetched["modir_type"];
  }
  else
    return -1;
  
  
}

//-----------------------------------------------------------------------
function message_show($message,$color)     // 0 == admin daneshkade  1== admin kol
{
 echo "<table border=\"0\" width=\"100%\" height=\"90%\">";
 echo "<tr>";
 echo "<td width=\"100%\" align=\"center\" ><font face=\"tahoma\" size=\"2\" color=\"$color\">$message</font></td>";
 echo "</tr>";
 echo "</table>";
}

//-----------------------------------------------------------------------
function set_log($action,$admin,$date)     // 0 == admin daneshkade  1== admin kol
{
   $query="insert into log set username=\"$admin\" , action=\"$action\", date='".$date."'";
   $result=mysql_query($query) or die("Error in inserting data into log file");
}

//-----------------------------------------------------------------------
function pubshowpages($link,$current,$PageCountShows,$Reccount,$startw,$endw,$RecPerPage,$username,$rand,$args,$width,$bgcolor)
{

     $PageCNT = ceil($Reccount/$RecPerPage);
     if($PageCNT <=1 )
       return;
     if(($startw==0 && $endw==0) )
     {
      $startw=1;
      if($PageCNT < $PageCountShows )
        $endw = $PageCNT;
      else
        $endw = $PageCountShows;
     }
     else    //line 50
     {
      if($PageCNT < $PageCountShows)
      {
        $startw = 1;
        $endw = $PageCNT;
      }
      else
      {
        //   fgfdgdfdf
        if( ($current-$startw) > floor(($endw-$startw)/2) )  //line60
        {
         if( ($endw+ceil(($endw-$startw)/2)) < $PageCNT )
         {
            $tmpvar = $startw;
            $startw += ceil(($endw-$startw)/2);
            $endw += ceil(($endw-$tmpvar)/2);
         }
         else
         {
           if($endw < $PageCNT)
           {
             $startw+=($PageCNT-$endw);
             $endw+=($PageCNT-$endw);
           }
         }
        }
        else
        {
          if( ($current-$startw) < ceil(($endw-$startw)/2) )
          {
            if(($startw-ceil(($endw-$startw)/2)) > 1  )
            {
               $tmpvar = $startw;
               $startw-=ceil(($endw-$startw)/2);
               $endw-=ceil(($endw-$tmpvar)/2);
            }
            else
            {
               $tmpvar = $startw;
               $startw=1;

               if( $PageCNT > $PageCountShows )
                  $endw = $PageCountShows;
               else
                  $endw=$PageCNT;
             }
          }
        }
     }
    }

if ( $current == $PageCNT )
{
  $endw=$PageCNT;
  if ($PageCountShows < $PageCNT )
    $startw = ($PageCNT+1) - $PageCountShows;
  else
    $startw = 1 ;


}

 echo"<table width=\"$width\"   border=0 align=\"center\" valign=\"center\"  cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"$bgcolor\">";
 $i=0;

 echo "<tr>";

 echo "<td width = 20% align=left dir=\"rtl\">";
 echo "<p align=\"center\" class=\"tahoma1\">";
 echo "$Reccount مورد يافت شد";
 echo "</p>";
 echo "</td>";
 echo "<td width = 60% align=center>";

 if($PageCNT>2 &&  $current > 1 )
 {
    printf("<a style=\"text-decoration: none\" href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\"size=3 color=green></font>",$link,1,0,0,$username,$rand,$args);
    echo "<img src=\"image/fullleft.gif\" border=\"0\">";
    echo "</a>";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }
 else
 {
    echo "<img src=\"image/fullleft.gif\" border=\"0\">";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
  
 }


 if($current > 1 )
 {
    printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\"size=3 color=green></font>",$link,$current-1,$startw,$endw,$username,$rand,$args);
    echo "<img src=\"image/left.gif\" border=\"0\">";
    echo "</a>";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }
else
 {
    echo "<img src=\"image/left.gif\" border=\"0\">";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }


 if($PageCNT>1)
 {
  for($i=$startw ;$i<=$endw;$i++)
  {
   if($i==$current)
      printf("<font face=\"arial\" size=2 color=green><spawn align=\"center\" class=\"tahoma1\"><b>&nbsp;%s&nbsp;</b></spawn></font>",$i);
   else
      printf("<a style=\"text-decoration: none\" href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=blue><spawn align=\"center\" class=\"tahoma1\"><b>&nbsp;%s&nbsp;</b></spawn></font></a>",$link,$i,$startw,$endw,$username,$rand,$args,$i);
  }
 }

 if(  $current < $PageCNT )
 {
   printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$current+1,$startw,$endw,$username,$rand,$args);
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/right.gif\" border=\"0\">";
   //echo "Next";
   echo "</a>";
 }
 else
 {
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/right.gif\" border=\"0\">";
 }

 if($PageCNT>2 && $current < $PageCNT )
 {
   printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$PageCNT,$startw,$endw,$username,$rand,$args);
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/fullright.gif\" border=\"0\">";
   echo "</a>";
 }
 else
 {
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/fullright.gif\" border=\"0\">";
 }


 echo"</td>";
 echo "<td width = 20% align=right>";
 echo "<p align=\"center\" class=\"tahoma1\">";
 echo "صفحه $current از $PageCNT";

 echo "</p>";
 echo "</td>";

 echo"</tr>";
 echo"</table>";


}

//-------------------------------------------------------------------

function BaseFromMiladiDate($mldyear , $mldmonth , $mldday )
{
  $PrevMonthDayMld = array(0,31,59,90,120,151,181,212,243,273,304,334);
  $iDaySum = 0 ;
  $iNewDateElapsed =0 ;
  $iBaseYear = 1996 ;
  $iBaseDateElapsed = 79 ;
  $iNewDateElapsed = ($mldday -1 ) + $PrevMonthDayMld[$mldmonth-1];
  if ( (($mldyear % 4 ) == 0 ) && ( $mldmonth > 2))
     $iNewDateElapsed++;

  $iDaySum = $iNewDateElapsed - $iBaseDateElapsed +($mldyear-$iBaseYear) *365 +(int)(($mldyear -$iBaseYear ) / 4 );

  if ((($mldyear - $iBaseYear) % 4 ) != 0 )
     $iDaySum = $iDaySum+1;
  return $iDaySum;
}
//---------------------------------------------------------------------
function hijricalender ( $year , $month , $day )
{
  $PrevMonthDayHjr = array(0,31,62,93,124,155,186,216,246,276,306,336);
  if ( $year < 1995 || $month < 1 || $month > 12 || $day > 31 || $day < 1 )
    return 0;
  $daysum = BaseFromMiladiDate($year , $month , $day );
  $iaddyear=0;
  while ($daysum >0 )
  {
      $daysum = $daysum -365;
      if (($iaddyear % 4 ) == 0 )
        $daysum--;
      $iaddyear++;
  }
  if ( $daysum <0 )
  {
      $iaddyear--;
      $daysum = $daysum+365;
      if (($iaddyear % 4 ) == 0 )
        $daysum++;
  }
  $itodayyear = 1375+$iaddyear;
  $itodaymonth=1;
  while ( $daysum >= $PrevMonthDayHjr[$itodaymonth])
  {
      $itodaymonth++;
      if( $itodaymonth ==12 )
        break;
  }
  $daysum=$daysum - $PrevMonthDayHjr[$itodaymonth-1];
  $itodayday = 1 + $daysum;
  $isodate = sprintf("%04d/%02d/%02d",$itodayyear ,$itodaymonth, $itodayday);
  return  $isodate;
}
//-------------------------------------------------------------------

function enum2fnum($englishnum)
{
  $return1 = str_replace("1", "ہ", $englishnum);
  $return2 = str_replace("2", "×", $return1);
  $return3 = str_replace("3", "à", $return2);
  $return4 = str_replace("4", "â", $return3);
  $return5 = str_replace("5", "ç", $return4);
  $return6 = str_replace("6", "è", $return5);
  $return7 = str_replace("7", "é", $return6);
  $return8 = str_replace("8", "ê", $return7);
  $return9 = str_replace("9", "ë", $return8);
  $return0 = str_replace("0", "ô", $return9);
  $return11 = str_replace("ہ", "&#1777;", $return0);
  $return12 = str_replace("×", "&#1778;", $return11);
  $return13 = str_replace("à", "&#1779;", $return12);
  $return14 = str_replace("â", "&#1780;", $return13);
  $return15 = str_replace("ç", "&#1781;", $return14);
  $return16 = str_replace("è", "&#1782;", $return15);
  $return17 = str_replace("é", "&#1783;", $return16);
  $return18 = str_replace("ê", "&#1784;", $return17);
  $return19 = str_replace("ë", "&#1785;", $return18);
  $return20 = str_replace("ô", "&#1776;", $return19);
  $return21 = str_replace(":", "<font compset size 3><b>:</b></font>", $return20);
  return $return21;

}


//-----------------------------------------------------------------

function today()
{

		$mydate=date("Y-m-d");
		$endyear=substr($mydate,0,4);
		$endmon=substr($mydate,5,2);
		$endday=substr($mydate,8,2);
		$todaydate= hijricalender($endyear,$endmon,$endday);

		return $todaydate;
}


?>
