<?

//-----------------------------------------------------------------------

function startsession($admuser,$seed,$usertype)
{
	@session_start();
			session_register('admin');//user id
			session_register('seed');//user password
			session_register('logintime');
			session_register('usertype');
			session_register('ip');
			
			
	$_SESSION["admin"]=$admuser;
	$_SESSION["seed"]=$seed;
	$_SESSION["logintime"]=time();
	$_SESSION["usertype"]=$usertype;
	
	if ( getenv("HTTP_X_FORWARDED_FOR"))
	   $ip = getenv("HTTP_X_FORWARDED_FOR" );
	else
	   $ip = getenv("REMOTE_ADDR");
	
	$_SESSION["ip"]=$ip;

}

//-------------------------------------------------------

function updatesession($admuser,$seed)
{

	$_SESSION["logintime"]=time();
}

//-------------------------------------------------------

function checksession($admuser,$seed)
{

 if ( getenv("HTTP_X_FORWARDED_FOR"))
   $ip = getenv("HTTP_X_FORWARDED_FOR" );
 else
   $ip = getenv("REMOTE_ADDR");
	
   $time=$_SESSION["logintime"];
   $ip=$_SESSION["ip"];
    if((time() > ($time+24000)) || (strcmp(trim($ip) , trim($ip)) <> 0 ))
       return 0;	

 else
      return $_SESSION["usertype"];


}

//-------------------------------------------------------

function clearsession($admuser,$seed)
{
 	@session_start();
			session_unregister('admin');//user id
			session_unregister('seed');//user password
			session_unregister('logintime');
			session_unregister('usertype');
			session_unregister('ip');
			session_unregister('la');
			session_unregister('cod_karshenas');
			session_unregister('cod_karshenas_shora');
}

//-------------------------------------------------------

function randString ($pass_len = 50)
{
 $allchars = 'abcdefghijklnmopqrstuvwxyzABCDEFGHIJKLNMOPQRSTUVWXYZ0123456789';
 $string = '';
 mt_srand ((double) microtime() * 1000000);
 for ($i = 0; $i < $pass_len; $i++)
 {
  $string .= $allchars{mt_rand (0,strlen($allchars))};
 }
 return $string;
}

//-------------------------------------------------------

?>
