<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
 
echo "<br>";


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;


/*
$query="select * from modir_daneshkade where  modir_username = '$admin'";
	$result=mysql_query($query);
	$row_fetched=mysql_fetch_array($result);
	$cod_daneshkade=$row_fetched["cod_daneshkade"];
*/
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

if(isset($name_e))
{
  $query="select * from user_login where (name like $myname_search  or family like $myname_search)   order by family desc";
}
else
  $query="select * from user_login where 1 order by family desc";


$result=mysql_query($query) or die("Error in selecting data from tarh 1");

$reccount = mysql_num_rows($result);

 if(isset($name_e))
{
  $query="select * from user_login where (name like $myname_search  or family like $myname_search)   order by family desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from user_login where 1 order by family desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh");
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>مجريان<b></td>
 </tr>
 </table>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>

 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>

 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 if(isset($name_e))	
   $myascdescpub=$myascdescpub."&name_e=$name_e";	
 pubshowpages("doers.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>

      <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">پست الکترونيکي</font></td>
    <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
  </tr>
  <?

 $color="#DADADA";
 $color="PALETURQUOISE";
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $from_letter=$row_fetched["from_letter"];
  $id=$row_fetched["id"];
 // echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><p align=\"center\"><a href=\"change_users_password.phtml?admin=$admin&seed=$seed&db=user_login&username=".$row_fetched["cod_user"]."&user_field=cod_user\" ><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["email"]."</a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["family"]."</a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["name"]."</a></td>";
  echo "</tr>";

 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
footer_forms($admin,$seed);


?>
