<?
include("include/database-connect.phtml");
include("include/include.phtml");
global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  
  if( $type == 1 )
    updatesession($username,$rand);
  else
  {
   header ("Refresh: 0; url=index.phtml");
   exit();
  }
 }
 
include("include/styles.phtml");
include("include/vars.inc.phtml");
echo "<META http-equiv=content-type content=text/html;charset=windows-1256>";
//header_forms($admin,$seed);
echo "<br>";


if( isset($action) )
 if ( strlen(trim($notes)) > 0 )
 {
   $query="select * from group_karshenasan where username='$admin'";
   $result=mysql_query($query) or die ("Error in selecting data");
   $row_fetched=mysql_fetch_array($result);
   $karshenas_id=$row_fetched["cod_karshenas"];

   $notes=str_replace("'","",$notes);
   $notes=str_replace("\"","",$notes);
   $notes=str_replace(";","",$notes);
	 
   $query="select max(version) as maxver from karshenasan_tarh where cod_tarh='$cod_tarh'";

   $result=mysql_query($query) or die("Error in selecting data from 1");

   $rf1=mysql_fetch_array($result);
   $maxver=$rf1["maxver"];
   if($maxver=='-1')
      $maxver='1';
   else
      $maxver=$maxver+1;
      
      
     $query="update group_karshenasan_tarh set version='$maxver' where cod_tarh='$cod_tarh' and version='-1' ";
     $result=mysql_query($query) or die ("Error in updating data into user login");
   
    // $query="update group_karshenasan_tarh set   gant='$gant',variables='$variables',note_submitted='1',chekide='$chekide',sabt='$sabt',mojrian='$mojrian',daneshjoyan='$daneshjoyan',raveshejra='$raveshejra',hazineha='$hazineha',akhlaghi='$akhlaghi',zamaem='$zamaem',comment_karshenas='$notes' , refered='$refered' where cod_tarh='$cod_tarh' and cod_karshenas='$karshenas_id'  ";

     $query="insert into group_karshenasan_tarh set  note_date='".date("Y-m-d")."',version='-1', gant='$gant',variables='$variables',note_submitted='1',chekide='$chekide',sabt='$sabt',mojrian='$mojrian',daneshjoyan='$daneshjoyan',raveshejra='$raveshejra',hazineha='$hazineha',akhlaghi='$akhlaghi',zamaem='$zamaem',comment_karshenas='$notes' , cod_tarh='$cod_tarh' , cod_karshenas='$karshenas_id'  ";  


   $result=mysql_query($query) or die ("Error in updating data into user login");
   
   message_show(".نظريه شما ارسال شد","green");
  
  // $action="تغيير کلمه عبور";
  // set_log($action,$admin,date("Y-d-m"));

   
 }
 else
   $status="entry_error";




    $notes="";
    $chekide='0';
  	$sabt='0';
  	$mojrian='0';
  	$daneshjoyan='0';
  	$raveshejra='0';
  	$hazineha='0';
  	$akhlaghi='0';
  	$zamaem='0';
  	$gant='0';
  	$variables='0';
 


?>
<script>
targetWidth = screen.availWidth;
targetHeight = screen.availHeight;
window.resizeTo(targetWidth, targetHeight);
window.toolbar="no";


</script>

<script>
function refresh_main()
{
	 document.user_login.submit();
     opener.location.reload(true);

}
</script>
<script language="javascript" src="js/farsi.js"></script>
<?
$query="select * from tarh where cod_tarh='$cod_tarh'";

$result1=mysql_query($query) or die("Error in selecting data from tarh");
$row_fetched1=mysql_fetch_array($result1);

?>
<br>
<center>
<TABLE cellSpacing=0  width="490" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD dir="rtl" align=center  class="tahoma1"  height=19  dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$row_fetched1["tarh_title_farsi"];
      ?>
      </TD>
  </TR>

</table>
</center>
<center>
<body onclose="refresh_main()">
<form  name="user_login" action="<? echo "$PHP_SELF?action=set_note&admin=$admin&seed=$seed&cod_tarh=$cod_tarh"; ?>" method="post">
  <table cellSpacing="0" cellPadding="0" width="500" border="0">
   <tbody>

      <tr>
        <td width="100%">
          <table cellSpacing="0" cellPadding="0" width="100%" border="0">
            <tbody>
              <tr>
                <td vAlign="bottom" align="left">
                  <table cellSpacing="0" cellPadding="0" border="0">
                    <tbody>
                      <tr>
                        <td align="middle" width="360" height="19"></td>
                        <td align="middle" width="140" background="image/notes_title.gif" height="19"></td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
      </tr>
    </tbody>
  </table>
  
  
  
  <table style="BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; BORDER-LEFT: 1px solid; BORDER-BOTTOM: 1px solid" borderColor="#333333" cellSpacing="0" cellPadding="2" width="500" height="80" bgColor="#eee7f8" border="0">
    <tbody>
      <?
      if (strcmp($status,"entry_error")==0)
      {
        echo "<tr>";
        echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">متن وارد شده خالي است</td>";
        echo "</tr>";
      }
      ?>
      <tr>
        <td align="right" width="400"><textarea   rows="8" cols="40" name="notes"  dir=RTL   ><? echo $notes; ?></textarea></td>
        <td class="tahoma1" width="100">نظر شما در مورد اين طرح</td>
      </tr>

      <tr>
        <td colspan="2" align="center" width="400">
		<span class="error-message">
        نظر خود را در مورد قسمتهاي مختلف طرح مشخص کنيد
        </span>
         </td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="chekide"  class="edit-user" dir="rtl">
		<?
		  if(strcmp($chekide,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($chekide,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($chekide,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($chekide,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    </select>
		</td>
        <td class="tahoma1" width="100">چکيده طرح</td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="sabt"  class="edit-user"  dir="rtl">
		
		<?
		  if(strcmp($sabt,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($sabt,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($sabt,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($sabt,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    
		
   		</select>
		</td>
        <td class="tahoma1" width="100"> ثبت طرح</td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="mojrian"  class="edit-user"  dir="rtl">
          		<?
		  if(strcmp($mojrian,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($mojrian,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($mojrian,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($mojrian,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    
		
	    </select>
		</td>
        <td class="tahoma1" width="100"> مجريان و همکاران</td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="daneshjoyan"  class="edit-user"  dir="rtl">
            		<?
		  if(strcmp($daneshjoyan,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($daneshjoyan,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($daneshjoyan,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($daneshjoyan,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    
	    </select>
		</td>
        <td class="tahoma1" width="100"> دانشجويان</td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="raveshejra"  class="edit-user"  dir="rtl">
               		<?
		  if(strcmp($raveshejra,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($raveshejra,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($raveshejra,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($raveshejra,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    
	    </select>
		</td>
        <td class="tahoma1" width="100"> روش اجرا</td>
      </tr>

      <tr>
        <td align="right" width="400">
		<select size="1" name="hazineha"  class="edit-user"  dir="rtl">
               		<?
		  if(strcmp($hazineha,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($hazineha,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($hazineha,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($hazineha,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           

	    </select>
		</td>
        <td class="tahoma1" width="100"> هزينه ها</td>
      </tr>


      <tr>
        <td align="right" width="400">
		<select size="1" name="akhlaghi"  class="edit-user"  dir="rtl">
                  		<?
		  if(strcmp($akhlaghi,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($akhlaghi,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($akhlaghi,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($akhlaghi,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    </select>
		</td>
        <td class="tahoma1" width="100"> ملاحظات اخلاقي</td>
      </tr>

<tr>
        <td align="right" width="400">
		<select size="1" name="gant"  class="edit-user"  dir="rtl">
                           		<?
		  if(strcmp($gant,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($gant,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($gant,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($gant,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    </select>
		</td>
        <td class="tahoma1" width="100"> جدول زمان بندي</td>
      </tr>



<tr>
        <td align="right" width="400">
		<select size="1" name="variables"  class="edit-user"  dir="rtl" >
                           		<?
		  if(strcmp($variables,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($variables,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($variables,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($variables,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    </select>
		</td>
        <td class="tahoma1" width="100"> جدول متغيرها</td>
      </tr>



      <tr>
        <td align="right" width="400">
		<select size="1" name="zamaem"  class="edit-user"  dir="rtl">
                           		<?
		  if(strcmp($zamaem,'0')==0)
		    $a=" selected ";
		  else 
		    $a="";
		  if(strcmp($zamaem,'1')==0)
		    $b=" selected ";
		  else 
		    $b="";
		    
		  if(strcmp($zamaem,'2')==0)
		    $c=" selected ";
		  else 
		    $c="";  
		    
		  if(strcmp($zamaem,'3')==0)
		    $d=" selected ";
		  else 
		    $d="";  
		?>
		   <option  <? echo $a; ?> value="0" >بدون اشکال</option>
           <option  <? echo $b; ?> value="1" >عدم وجود اطلاعات</option>
           <option  <? echo $c; ?> value="2" >بايد اصلاح شود</option>
           
	    </select>
		</td>
        <td class="tahoma1" width="100"> ضمائم</td>
      </tr>


       
     
      <tr>
        <td width="100%" colSpan="2">
          <p align="center"><input class="but-small" type="button" onclick="refresh_main()" value="ثبت" name="B1"></p>
        </td>
      </tr>
      
      
      
    </tbody>
  </table>
</form>


<?

 $query="select * from group_karshenasan where username='$admin'";						  
 $result=mysql_query($query) or die("Error in selecting data from group_karshenasan");
 $row_fetched=mysql_fetch_array($result);
			   

if(strcmp($row_fetched["karshenas_type"],"1")!=0)
{
$query="select * from group_karshenasan_tarh where cod_tarh='$cod_tarh'" ;
$query="select * from group_karshenasan,group_karshenasan_tarh where cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas ";
						  

$result=mysql_query($query) or die("Error in selecting data from group_karshenasan_tarh");



if(mysql_num_rows($result) > 0 )
{
	
 //pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="70%" cellpadding="1" cellspacing="1">
 <tr>
    <td width="100%" colspan='5' bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1" ><font color="black">نظر شما و همکاران ستاد در مورد اين طرح</font></td>
   
    
  </tr>
  <tr>
    <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس در مورد قسمتهاي طرح</font></td>
    <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام کاربري</font></td>
	<td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام </font></td>
    
  </tr>
  <?


 $color=$list_color_1;
 $table = array();
 $table[0] = "بدون اشکال";
 $table[1] = "عدم وجود اطلاعات";
 $table[2] = "بايد اصلاح شود";
 $table[3] = "ناقص";

 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
 
 
 $string="";
 $note_submitted=$row_fetched["note_submitted"];
// if(strcmp($note_submitted,"1")==0)
// {
 	$cnt=$row_fetched["chekide"];
 	$string=$string."  چکيده : ".$table[$cnt];
 	$cnt=$row_fetched["sabt"];
 	$string=$string."<br>"." ثبت : ".$table[$cnt];
 	$cnt=$row_fetched["mojrian"];
 	$string=$string."<br>"." مجريان : ".$table[$cnt];
 	$cnt=$row_fetched["daneshjoyan"];
 	$string=$string."<br>"." دانشجويان : ".$table[$cnt];
 	$cnt=$row_fetched["raveshejra"];
 	$string=$string."<br>"." روش اجرا : ".$table[$cnt];
 	$cnt=$row_fetched["hazineha"];
 	$string=$string."<br>"."  هزينه ها : ".$table[$cnt];
 	$cnt=$row_fetched["akhlaghi"];
 	$string=$string."<br>"." ملاحظات اخلاقي : ".$table[$cnt];
 	$cnt=$row_fetched["gant"];
 	$string=$string."<br>"." جدول زمانبندي : ".$table[$cnt];
 	$cnt=$row_fetched["variables"];
 	$string=$string."<br>"." جدول متغيرها : ".$table[$cnt];
 	$cnt=$row_fetched["zamaem"];
 	$string=$string."<br>"." ضمائم : ".$table[$cnt];
// }
 //else
  // $string="نظر ايشان ثبت نشده";
 
 
 // if(strcmp($note_submitted,"1")==0) 
    $comment_note=$row_fetched["comment_karshenas"];
  //else
  //	$comment_note="نظر ايشان ثبت نشده"; 

  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"ltr\">".$string."</td>";
  
  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\"  dir=\"rtl\">".$comment_note."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["username"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  

 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".نظر ي وجود ندارد","red");
}
} 


$query="select * from karshenasan_tarh where cod_tarh='$cod_tarh'" ;
 $query="select * from karshenasan,karshenasan_tarh where  cod_tarh='$cod_tarh' and karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas";
						  
//echo $query;
$result=mysql_query($query) or die("Error in selecting data from group_karshenasan_tarh");



if(mysql_num_rows($result) > 0 )
{
	
 //pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="70%" cellpadding="1" cellspacing="1">
<tr>
    <td width="100%" colspan="5" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس در مورد قسمتهاي طرح</font></td>
  
  </tr>
  <tr>
    <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس در مورد قسمتهاي طرح</font></td>
    <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام کاربري</font></td>
	<td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام </font></td>
    
  </tr>
  <?


 $color=$list_color_1;
 $table = array();
 $table[0] = "بدون اشکال";
 $table[1] = "عدم وجود اطلاعات";
 $table[2] = "بايد اصلاح شود";
 $table[3] = "ناقص";

 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
 
 
 $string="";
 $note_submitted=$row_fetched["refered"];
 //if(strcmp($note_submitted,"1")==0)
// {
 	$cnt=$row_fetched["chekide"];
 	$string=$string."  چکيده : ".$table[$cnt];
 	$cnt=$row_fetched["sabt"];
 	$string=$string."<br>"." ثبت : ".$table[$cnt];
 	$cnt=$row_fetched["mojrian"];
 	$string=$string."<br>"." مجريان : ".$table[$cnt];
 	$cnt=$row_fetched["daneshjoyan"];
 	$string=$string."<br>"." دانشجويان : ".$table[$cnt];
 	$cnt=$row_fetched["raveshejra"];
 	$string=$string."<br>"." روش اجرا : ".$table[$cnt];
 	$cnt=$row_fetched["hazineha"];
 	$string=$string."<br>"."  هزينه ها : ".$table[$cnt];
 	$cnt=$row_fetched["akhlaghi"];
 	$string=$string."<br>"." ملاحظات اخلاقي : ".$table[$cnt];
 		$cnt=$row_fetched["gant"];
 	$string=$string."<br>"." جدول زمانبندي : ".$table[$cnt];
 	$cnt=$row_fetched["variables"];
 	$string=$string."<br>"." جدول متغيرها : ".$table[$cnt];
 	$cnt=$row_fetched["zamaem"];
 	$string=$string."<br>"." ضمائم : ".$table[$cnt];
// }
 //else
 //  $string="نظر ايشان ثبت نشده";
 
 
  //if(strcmp($note_submitted,"1")==0) 
    $comment_note=$row_fetched["comment_karshenas"];
 // else
  //	$comment_note="نظر ايشان ثبت نشده"; 

  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"ltr\">".$string."</td>";
  
  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\"  dir=\"rtl\">".$comment_note."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["username"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  
//echo "</tr>";
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".نظر ي وجود ندارد","red");
}
?>
</body>
<br>
<?
  //footer_forms($admin,$seed);
?>
