<?
 
   $myq="select * from tarh where payannameh='1' and cod_tarh='$cod_tarh'";
					    $res_user=mysql_query($myq) or die("Error");
					   
					    $payan_name_or_tarh =mysql_num_rows($res_user) ;
   
 
if( $payan_name_or_tarh <= 0)
  $title_caption=" طرح ";
else
  $title_caption=" پايان نامه ";
  
             
 
echo "<br>";

  $query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1' ";
  
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $first_ostad = $row_fetched["first_ostad"];
  $second_ostad = $row_fetched["second_ostad"];
  $third_ostad = $row_fetched["third_ostad"];
  $forth_ostad = $row_fetched["forth_ostad"];
  $query_savabet_system="select * from savabetsystem";
   $savabet_system=mysql_query($query_savabet_system) or die("Error in selectiong data from query_savabet_system");
   if(mysql_num_rows($savabet_system) > 0 )
   {
     $tarhtype_second = mysql_fetch_array($savabet_system);
     $tarh_type_1 = $tarhtype_second["tarh_type_1"];
     $tarh_type_2 = $tarhtype_second["tarh_type_2"];
   }
   else
   {
     $tarh_type_1 = "";
     $tarh_type_2 = "";
   }


   $query="select * from tarh where cod_tarh='$cod_tarh'   and version='-1' ";
  
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
     $payan_name = $row_fetched["payan_name1"];
     $payan_name_daraje_elmi = $row_fetched["payan_name_daraje_elmi"];  


     if($payan_name==0)
	   $payan_name="پايان نامه نيست";
	 if($payan_name==1)
	   $payan_name="پايان نامه با سقف اعتباري پايان نامه ها";
 	 if($payan_name==2)
	   $payan_name="پايان نامه با سقف اعتباري بالاتر از پايان نامه ها";

	
	 
	 
     echo "<br>";
?>
    <TABLE cellSpacing=0 width="98%"  cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

    <TR>

      <TD align=center class="tahoma1"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo "عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
    </TR>

  </table>
<?
    echo "<br>";
    echo "<table border=\"0\" width=\"98%\"  cellspacing=\"1\" cellpadding=\"1\" >";
    $color="PALETURQUOISE";
    $row_fetched=mysql_fetch_array($result);
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["tarh_title_farsi"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">عنوان $title_captio</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["tarh_title_english"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">(عنوان $title_captio (انگليسي</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["kelidvajeh"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">کليد واژه ها</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["line"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">لاين تحقيقاتي</td>";
    echo "</tr>";

    $daneshkade=$row_fetched["cod_daneshkade"];
	$myq="select * from daneshkade where cod_daneshkade='$daneshkade'";
	$myres=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_daneshkade = mysql_fetch_array($myres);
	$daneshkade_name=$row_fetched_daneshkade["daneshkade_name"];    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$daneshkade_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">دانشکده / مرکز هدف</td>";
    echo "</tr>";
    
    $second_daneshkade=$row_fetched["second_cod_daneshkade"];
	$myq="select * from daneshkade where cod_daneshkade='$second_daneshkade'";
	$myres=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_daneshkade = mysql_fetch_array($myres);
	$daneshkade_name=$row_fetched_daneshkade["daneshkade_name"];    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$daneshkade_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">دانشکده / مرکز هدف</td>";
    echo "</tr>";
    
    $cod_group=$row_fetched["cod_group"];
	$myq="select * from group_daneshkade where cod_group='$cod_group'";
	
	$myres=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_group = mysql_fetch_array($myres);
	$group_name=$row_fetched_group["group_name"];    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$group_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">گروه هدف</td>";
    echo "</tr>";

	if($row_fetched["tarh_type"]< 10 )
	  $tarh_type_code =trim($row_fetched["tarh_type"]);
	else
	  $tarh_type_code=$row_fetched["tarh_type"];
    $query="select * from tarhtype where tarh_type='".$tarh_type_code."'";
    
    $myresult = mysql_query($query);
    $my_fetch_array = mysql_fetch_array($myresult);

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$my_fetch_array["tarh_type_desc"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">نوع $title_captio</td>";
    echo "</tr>";

if( $payan_name_or_tarh> 0)
{


    $query2="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";
	$result2=mysql_query($query2) or die("Error in selecting data from user_login11");
	$row_fetched2=mysql_fetch_array($result2);
	$first_ostad=$row_fetched2['first_ostad'];
	$second_ostad=$row_fetched2['second_ostad'];
	$first_ostad_moshaver=$row_fetched2['first_ostad_moshaver'];
	$second_ostad_moshaver=$row_fetched2['second_ostad_moshaver']; 

	$myq="select * from user_login where email='$first_ostad'";
	
	$ostad_res=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_ostad = mysql_fetch_array($ostad_res);
	$ostad_name=$row_fetched_ostad["name"]."&nbsp".$row_fetched_ostad["family"];

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$ostad_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استاد راهنماي اول</td>";
    echo "</tr>";


    $myq="select * from user_login where email='$second_ostad'";
	
	$ostad_res=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_ostad = mysql_fetch_array($ostad_res);
	$ostad_name=$row_fetched_ostad["name"]."&nbsp".$row_fetched_ostad["family"]; 


    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$ostad_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استاد راهنماي دوم</td>";
    echo "</tr>";
	
	 $myq="select * from user_login where email='$first_ostad_moshaver'";
	
	$ostad_res=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_ostad = mysql_fetch_array($ostad_res);
	$ostad_name=$row_fetched_ostad["name"]."&nbsp".$row_fetched_ostad["family"]; 


    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$ostad_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استاد مشاور اول</td>";
    echo "</tr>";
	
	 $myq="select * from user_login where email='$second_ostad_moshaver'";
	
	$ostad_res=mysql_query($myq) or die("Error in selecting daneshkade");
	$row_fetched_ostad = mysql_fetch_array($ostad_res);
	$ostad_name=$row_fetched_ostad["name"]."&nbsp".$row_fetched_ostad["family"]; 


    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$ostad_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استاد مشاور دوم</td>";
    echo "</tr>";

}

    $query="select * from tarhtype_1 where tarh_type='".$row_fetched["tarh_type_1"]."'";
    $myresult = mysql_query($query);
    $my_fetch_array = mysql_fetch_array($myresult);

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$my_fetch_array["tarh_type_desc"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">نوع مطالعه</td>";
    echo "</tr>";

if( $payan_name_or_tarh> 0)
{

    $query="select * from tarhtype_2 where tarh_type='".$row_fetched["tarh_type_2"]."'";
    $myresult = mysql_query($query);
    $my_fetch_array = mysql_fetch_array($myresult);

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$my_fetch_array["tarh_type_desc"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">$tarh_type_1</td>";
	echo "</tr>";
}
  
  if( $payan_name_or_tarh <= 0)

{
  
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$payan_name."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">آيا طرح پايان نامه است</td>";
    echo "</tr>";
}


      $query="select * from maghta_payan_name where maghta_payan_name=$payan_name_daraje_elmi";
      $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
	if(mysql_num_rows($qresult) > 0)
	{
	$rf_payan=mysql_fetch_array($qresult);
	$desc_payan=$rf_payan["maghta_payan_name_desc"];
	}
    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$desc_payan."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">مقطع پايان نامه</td>";
    echo "</tr>";
  
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["zarorat"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">خلاصه ضرورت اجراي طرح</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["ahdaf"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">اهداف کلي , اختصاصي و کاربردي</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["soalat"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">سوالات پژوهشي و فرضيات</td>";
    echo "</tr>";
    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["shive_ejra"])."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">خلاصه روش اجرا و شيوه هاي تحليل</td>";
    echo "</tr>";
    
    echo "</table>";
   }
?>
 <table border="0" width="500">
<tr>
    <td width="100%"  align="center" class="tahoma1"><a style="text-decoration:none" href="view_tarh_form.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
</tr>

</table>
 