<?

echo "<br>";

  $query="select * from tarh where cod_tarh='$cod_tarh'  ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];

   $query = "select  * from tarh where  tarh.cod_tarh = \"$cod_tarh\"";
 
   $result=mysql_query($query) or die("Error in selecting data from First mojri 2");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
?>
    <TABLE cellSpacing=0 width="60%"  cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

    <TR>

      <TD align=center class="tahoma1"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
    </TR>

  </table>
<?
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";

  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

    echo "<br>";
    echo "<table border=\"0\" width=\"60%\"  cellspacing=\"1\" cellpadding=\"1\" >";
    $color="PALETURQUOISE";
    $row_fetched=mysql_fetch_array($myresult_mojri);
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["name"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">نام</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["family"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">نام خانوادگي</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["work_addr"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">آدرس محل کار</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["home_addr"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">آدرس منزل</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["telno"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">تلفن</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["fax"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">فکس</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["email"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">پست الکترونيکي</td>";
    echo "</tr>";

    echo "</table>";
   }
?>
 <table border="0" width="500">
<tr>
    <td width="100%"  align="center" class="tahoma1"><A HREF="javascript:history.go(-1)"> بازگشت</a></td>
</tr>

</table>
