<?

if(!isset($version))
 $version="-1";
 $query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $servicing = $row_fetched["servicing"];

echo "<br>";
   $query="select * from tarh where cod_tarh='$cod_tarh'  and version='$version' ";

   $result=mysql_query($query) or die("Error in selecting data from tarh");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
?>

<TABLE cellSpacing=0  width="98%" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD dir="rtl" align=center  class="tahoma1"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
  </TR>
  <?php  echo "<tr>";
      
      echo "<td align=\"center\" colspan=\"9\"  class=\"tahoma1\"><a target='_blank' href='hazine_personnel_print.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>چاپ فرم امضاي مجريان / همکاران</a></td>";
       
      echo "</tr>";
      ?>
</table>
<br>
<labale class="tahoma1"><font color=red>موارد بولد در اين ويرايش تغيير کرده اند يا جديد اضافه شده اند</font></labale>
<!--  --></br>
<br>

<?
   $color="PALETURQUOISE";
   $query="select * from  eatebar_sazmanha where cod_tarh='$cod_tarh'  and version='$version'";
   
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi1212");
   
   if(mysql_num_rows($result) > 0)
   {
//   	$row_fetched=mysql_fetch_array($result);
    echo "<br>";
    echo "<table width=\"98%\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \" >";
    echo "<tr>";
    echo "<table width=\"98%\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \"  >";
    echo "<tr>";
    echo "<td  bgcolor=$color colspan=\"6\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\"><b>تامين اعتبار از ساير سازمانها<b></p></td>";
     echo "</tr>";

    echo "<tr>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نحوه پرداخت</p></td>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">مبلغ</p></td>";
    //echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">فکس</p></td>";
   // echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">شماره تلفن</p></td>";
  //  echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">آدرس پستي</p></td>";
    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام موسسه</p></td>";
    echo "</tr>";
  $color="PALETURQUOISE";
  $eatebare_sazmanha_pardakht_add=0;
   while($myrow_fetched=mysql_fetch_array($result))
   {
             	$new_update=$myrow_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     else {
     		$str="";
     		$str2="";
     	}
    echo "<tr bgcolor=\"$color\">";
    
    $mojri_code = $myrow_fetched["mojri_code"];
   	$eatebare_sazmanha_value = $myrow_fetched["eatebare_sazmanha_value"]; 
   	$eatebare_sazmanha_pardakht = $myrow_fetched["eatebare_sazmanha_pardakht"];
   	$eatebare_sazmanha_fax = $myrow_fetched["eatebare_sazmanha_fax"];
   	$eatebare_sazmanha_telno= $myrow_fetched["eatebare_sazmanha_telno"];
   	$eatebare_sazmanha_organ = $myrow_fetched["eatebare_sazmanha_organ"];
    $eatebare_sazmanha_address = $myrow_fetched["eatebare_sazmanha_address"];
    $eatebare_sazmanha_pardakht_add=$eatebare_sazmanha_value+$eatebare_sazmanha_pardakht_add;
    $id_pardakht= $myrow_fetched["id"];
    	if(strcmp($eatebare_sazmanha_pardakht,'0')==0)
        $eatebare_sazmanha="اعتبار توسط مجري دريافت مي شود ";
    if(strcmp($eatebare_sazmanha_pardakht,'1')==0)
        $eatebare_sazmanha=" اعتبار به دانشگاه پرداخت ميشود تا از طريق قرارداد به مجري پرداخت شود ";
 
    //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$str.$eatebare_sazmanha.$str2."</td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$eatebare_sazmanha_value.$str2."</td>";
   /// echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">$eatebare_sazmanha_fax</td>";
   // echo "<td bgcolor=$color  class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">$eatebare_sazmanha_telno</td>";
  //  echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">$eatebare_sazmanha_address</td>";
    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$eatebare_sazmanha_organ.$str2."</td>";
    echo "</tr>";
   }
   echo "</table>";

  }
?>









<?
  $color="PALETURQUOISE";
   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version'";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     echo "<br>";
     echo "<table width=\"98%\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"100%\" bgcolor=$color colspan=\"9\" align=\"center\" class=\"tahoma1\"><b>هزينه پرسنلي</b></td>";
     echo "</tr>";
    
     echo "<tr>";
     echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">جمع</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">حق الزحمه در ساعت</td>";
     echo "<td width=\"5%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">مجموع ساعات</td>";
     echo "<td width=\"26%\"  bgcolor=$color align=\"center\"  class=\"tahoma1\">درجه تحصيلي</td>";
     echo "<td width=\"14%\"  bgcolor=$color align=\"center\"  class=\"tahoma1\">تعداد افراد</td>";
     echo "<td width=\"20%\" bgcolor=$color  align=\"center\"  class=\"tahoma1\">نوع فعاليت</td>";
      echo "<td width=\"20%\" bgcolor=$color  align=\"center\"  class=\"tahoma1\">نام مجري / همکار / ديگر افراي</td>";
     echo "</tr>";

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
          	$new_update=$row_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     else {
     		$str="";
     		$str2="";
     	}
       echo "<tr>";
       
       $mojri_code=$row_fetched["mojri_code"];
       $query1="select distinct user_login.* from user_login  where user_login.email='$mojri_code'";
       $result1=mysql_query($query1) or die("Error");
       $mojri_name_family="*";
       
       if(mysql_num_rows($result1)>0)		   
	   {
	   	
	   	$myrf=mysql_fetch_array($result1);
	   	$mojri_name_family=$myrf["name"]."&nbsp;".$myrf["family"];
	   	
	   }
	
       $query2="select distinct mojri.* from  mojri  where mojri.mojri_code= '$mojri_code'";
       $result2=mysql_query($query2) or die("Error in selecting data from mojri_tarh");
       
       if(mysql_num_rows($result2)>0)		   
	   {
	   	
	   	$myrf=mysql_fetch_array($result2);
	   	$mojri_name_family=$myrf["name"]."&nbsp;".$myrf["family"];
	   	
	   }
	
       
       
//       echo "<td align=\"center\" class=\"tahoma1\"><img src=\"image/button_drop.png\" border=0 alt=\"Delete\"></td>";
  //   echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=hazine_personnel.phtml&admin=$admin&seed=$seed&action=delete_hazine&cod_tarh=".$cod_tarh."&delete_id=".$row_fetched["cod_hazine"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$str.number_format($my_summary).$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\" >".$str.number_format($row_fetched["per_hour"]).$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\" >".$str.number_format($row_fetched["majmoa_saat"]).$str2."</td>";

       $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";

       $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
       if(mysql_num_rows($qresult) > 0 )
       {
         $row_degree = mysql_fetch_array($qresult);
         $degree_result = $row_degree["darajeelmi_desc"];
       }
       else
         $degree_result = "ثبت نشده";
       echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\">".$str.$degree_result.$str2."</td>";


       echo "<td align=\"center\"  bgcolor=$color class=\"tahoma1\">".$str.number_format($row_fetched["persons"]).$str2."</td>";
       echo "<td align=\"center\"  bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["activity_type"].$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\">".$str.$mojri_name_family.$str2."</td>";
       echo "</tr>";
     }
      echo "<tr>";
     // echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\">&nbsp;</td>";
      echo "<td align=\"center\"  bgcolor=$color class=\"tahoma1\">".number_format($mycount)."</td>";
      echo "<td align=\"right\" bgcolor=$color colspan=\"6\"  class=\"tahoma1\">مجموع</td>";
      echo "</tr>";
     echo "</table>";

   }


   }
	if(strcmp($servicing,"1")==0){
    	$hazine_azmayesh_lable="هزينه استفاده از خدمات آزمايشگاهي و کارگاهي";
    }
    else
    	$hazine_azmayesh_lable="هزينه هاي آزمايشات وخدمات تخصصي";
   
   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     echo "<br>";
     echo "<table width=\"98%\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"100%\" bgcolor=$color colspan=\"9\" align=\"center\" class=\"tahoma1\"><b>$hazine_azmayesh_lable</b></td>";
     echo "</tr>";

     echo "<tr>";
    // echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">حذف</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">جمع</td>";
     echo "<td width=\"5%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">هزينه هر دفعه</td>";
     echo "<td width=\"26%\"  bgcolor=$color align=\"center\"  class=\"tahoma1\">تعداد آزمايش</td>";
     echo "<td width=\"14%\"  bgcolor=$color align=\"center\"  class=\"tahoma1\">محل انجام</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">نوع آزمايش</td>";
     echo "</tr>";

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
               	$new_update=$row_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     else {
     		$str="";
     		$str2="";
     	}
       echo "<tr>";
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
       echo "<td width=\"5%\" bgcolor=$color  align=\"center\" class=\"tahoma1\">".$str.number_format($my_summary).$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\" >".$str.number_format($row_fetched["hazine_har_bar"]).$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\" >".$str.number_format($row_fetched["azmayesh_cnt"]).$str2."</td>";

       if (strcmp($row_fetched["azmayesh_center"],'1')==0)
        $mahall_azmayesh="خصوصي";
       if (strcmp($row_fetched["azmayesh_center"],'2')==0)
        $mahall_azmayesh="داخل دانشگاه";
	   if (strcmp($row_fetched["azmayesh_center"],'3')==0)
        $mahall_azmayesh="دولتي خارج دانشگاه"; 
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$mahall_azmayesh.$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["mozoa_azmayesh"].$str2."</td>";
       echo "</tr>";
     }
      echo "<tr>";
      //echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">&nbsp;</td>";
      echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".number_format($mycount)."</td>";
      echo "<td align=\"right\" bgcolor=$color colspan=\"5\"  class=\"tahoma1\">مجموع</td>";
      echo "</tr>";
     echo "</table>";

   }


 $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";

   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {
     echo "<br>";

     echo "<table width=\"98%\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"100%\" bgcolor=$color colspan=\"9\" align=\"center\" class=\"tahoma1\"><b>فهرست وسايل و مواردي که بايد خريداري شود</b></td>";
     echo "</tr>";
     //echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">حذف</td>";
     echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">قيمت کل</td>";
     echo "<td width=\"20%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">قيمت واحد</td>";
	 echo "<td width=\"20%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">مقياس</td>";
	 echo "<td width=\"20%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">تعداد يا مقدار</td>";
     echo "<td width=\"5%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">مصرفي يا غير مصرفي</td>";
     echo "<td width=\"26%\" bgcolor=$color  align=\"center\"  class=\"tahoma1\">Code No</td>";
     echo "<td width=\"14%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">شرکت سازنده</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">نام دستگاه</td>";
     echo "</tr>";

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$new_update=$row_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     	else {
     		$str="";
     		$str2="";
     	}
       echo "<tr>";
       //echo "<td align=\"center\" class=\"tahoma1\"><img src=\"image/button_drop.png\" border=0 alt=\"Delete\"></td>";
       //echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=fehrest_kharid.phtml&admin=$admin&seed=$seed&action=delete_fehrest_kharid&cod_tarh=".$cod_tarh."&delete_id=".$row_fetched["cod_kharid"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
       $mycount=$mycount+$row_fetched["count"];
       $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
       echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$str.number_format($row_fetched["price"]*$row_fetched["count"]).$str2."</td>";
       echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$str.number_format($row_fetched["price"]).$str2."</td>";
	   echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$str.$row_fetched["meghyas"].$str2."</td>";
	   echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\" >".$str.number_format($row_fetched["count"]).$str2."</td>";
     
	   if(strcmp( $row_fetched["usage_unusage"] ,"0")==0 )
         echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\" >$str مصرفي $str2</td>";
       else
         echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\" >$str غير مصرفي $str2</td>";

       echo "<td align=\"center\" bgcolor=$color  class=\"tahoma1\">".$str.$row_fetched["country"].$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["company"].$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["name_dastgah"].$str2."</td>";
       echo "</tr>";
     }
      echo "<tr>";
     // echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">&nbsp;</td>";
      echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".number_format($mycount1)."</td>";
      echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">&nbsp;</td>";
	  echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".number_format($mycount)."</td>";
      $summary_of_vasayel_kharid = $mycount1;
      echo "<td align=\"right\"  bgcolor=$color colspan=\"5\"  class=\"tahoma1\">مجموع</td>";
      echo "</tr>";
     echo "</table>";

   }



 $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {
     echo "<br>";
     echo "<table width=\"98%\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"100%\" bgcolor=$color colspan=\"9\" align=\"center\" class=\"tahoma1\"><b>هزينه مسافرت</b></td>";
     echo "</tr>";
     //echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">حذف</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">هزينه  به ريال</td>";
     echo "<td width=\"5%\"  bgcolor=$color align=\"center\" class=\"tahoma1\">تعداد افراد</td>";
     echo "<td width=\"26%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">نوع وسيله</td>";
     echo "<td width=\"14%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">دفعات مسافرت</td>";
     //echo "<td width=\"20%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">منظور از مسافرت</td>";
     echo "<td width=\"20%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">مقصد</td>";
     echo "</tr>";

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
               	$new_update=$row_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     else {
     		$str="";
     		$str2="";
     	}
       echo "<tr>";
       //echo "<td align=\"center\" class=\"tahoma1\"><img src=\"image/button_drop.png\" border=0 alt=\"Delete\"></td>";
//       echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=hazine_mosaferat.phtml&admin=$admin&seed=$seed&action=delete_hazine_mosaferat&cod_tarh=".$cod_tarh."&delete_id=".$row_fetched["cod_hazine_safar"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
       echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$str.number_format($row_fetched["hazine"]).$str2."</td>";
       //echo "<td align=\"center\"  class=\"tahoma1\" >".$row_fetched["hazine"]."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\" >".$str.number_format($row_fetched["persons_cnt"]).$str2."</td>";

       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["vasile"].$str2."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.number_format($row_fetched["dafe_safar"]).$str2."</td>";
       //echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$row_fetched["manzoor_mosaferat"]."</td>";
       echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".$str.$row_fetched["target"].$str2."</td>";
       echo "</tr>";
     }
      echo "<tr>";
      //echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">&nbsp;</td>";
      echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".number_format($mycount)."</td>";
      echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">".number_format($mycount1)."</td>";
      echo "<td align=\"right\" bgcolor=$color colspan=\"4\"  class=\"tahoma1\">مجموع</td>";
      echo "</tr>";
     echo "</table>";

   }

?>


<?


   $color="PALETURQUOISE";
   $query  = "select * from sayer_hazine where cod_tarh=\"$cod_tarh\"  and version='$version'";
   
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi1212");
   
   if(mysql_num_rows($result) > 0)
   {
   
//   	$row_fetched=mysql_fetch_array($result);
    echo "<br>";
    echo "<table width=\"98%\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \" >";
    echo "<tr>";
    echo "<table width=\"98%\"  cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \"  >";
    echo "<tr>";
    echo "<td  bgcolor=$color colspan=\"6\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\"><b>ساير هزينه ها<b></p></td>";
     echo "</tr>";

    echo "<tr>";
    if(strcmp($servicing,"1")==0){
    	 echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">بالاسري دانشگاه</p></td>";
	     echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حق نظارت</p></td>";
    	 echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ماليات</p></td>";
    }
    else{
	    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ساير هزينه ها</p></td>";
	    echo "<td  bgcolor=$color  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">هزينه تکثير اوراق</p></td>";
    } 
    echo "</tr>";
  $color="PALETURQUOISE";
   while($myrow_fetched=mysql_fetch_array($result))
   {
             	$new_update=$myrow_fetched["new_update"];
     	//echo $new_update;
     	if($new_update=="1"){
     		$str="<b>";
     		$str2="</b>";
     	}
     else {
     		$str="";
     		$str2="";
     	}
    echo "<tr bgcolor=\"$color\">";
    
    $sayer_hazine  = $myrow_fetched["sayer_hazine"];
    $hazine_taksir = $myrow_fetched["hazine_taksir"];
    $maliat  = $myrow_fetched["maliat"];
    $nezarat  = $myrow_fetched["nezarat"];
    $balasari  = $myrow_fetched["balasari"];
    $id= $myrow_fetched["id"];
  
    //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
     if(strcmp($servicing,"1")==0){
     	 echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$balasari.$str2."</td>";
	     echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$nezarat.$str."</td>";
     	 echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$maliat.$str2."</td>";
	    
     }
     else{
	    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$sayer_hazine.$str2."</td>";
	    echo "<td bgcolor=$color  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$str.$hazine_taksir.$str."</td>";
   }
	echo "</tr>";
   }
   echo "</table>";

  }







   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version' order by activity_type ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";
       $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
       if(mysql_num_rows($qresult) > 0 )
       {
         $row_degree = mysql_fetch_array($qresult);
         $degree_result = $row_degree["darajeelmi_desc"];
       }
       else
         $degree_result = "ثبت نشده";
     }
      $personnel_sum=$mycount;
   }

   
   
   
   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";

   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='$version'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
$maliat=0;
$nezarat=0;
$balasari=0;
$sum_sayer=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
   $hazine_taksir = $hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_row_fetched["sayer_hazine"];
    $maliat = $hazine_row_fetched["maliat"];
    $nezarat = $hazine_row_fetched["nezarat"];
    $balasari = $hazine_row_fetched["balasari"];
     $sum_sayer=$sum_sayer+$hazine_digar+$hazine_taksir+$maliat+$nezarat+$balasari;
  }
 }
?>
<br>
<table border="0" width="98%" colspan="0" cellspan="0" align="center">

<tr>
   <td width="100%" colspan="4" valign="top" align="center">
   <span <? echo $text_font_style; ?>>
 <?
	 
     echo "<table width=\"100%\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"20%\" bgcolor=$color  align=\"center\" class=\"tahoma1\"><b>(مجموع(ريال<b></td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\"><b>هزينه<b></td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\" bgcolor=$color   align=\"center\" class=\"tahoma1\">".number_format($personnel_sum)."</td>";
     echo "<td width=\"80%\" bgcolor=$color  align=\"center\"  class=\"tahoma1\">جمع هزينه پرسنلي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\" bgcolor=$color   align=\"center\" class=\"tahoma1\">".number_format($lab_sum)."</td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\">جمع هزينه هاي آزمايشات وخدمات تخصصي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"  bgcolor=$color  align=\"center\" class=\"tahoma1\">".number_format($trip_sum)."</td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\">جمع هزينه هاي مسافرت</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\" bgcolor=$color   align=\"center\" class=\"tahoma1\">".number_format($vasile_sum)."</td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\">جمع هزِينه هاي وسايل</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"  bgcolor=$color  align=\"center\" class=\"tahoma1\">".number_format($sum_sayer)."</td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\">جمع ساير هزينه ها</td>";
     echo "</tr>";

     echo "<tr>";
     echo "<td width=\"20%\"  bgcolor=$color  align=\"center\" class=\"tahoma1\">".number_format($eatebare_sazmanha_pardakht_add)."</td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\"  class=\"tahoma1\">اعتبار از سازمانهاي ديگر</td>";
     echo "</tr>";

	 echo "<tr>";
	 $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
     echo "<td width=\"20%\" bgcolor=$color   align=\"center\" class=\"tahoma1\"><b>".number_format($sum_of_all)."</b></td>";
     echo "<td width=\"80%\" bgcolor=$color   align=\"center\" class=\"tahoma1\"><b>جمع کل</b></td>";

     echo "</tr>";


     echo "</table>";


?>
</td>
</tr>

</table>


<table border="0" width="500">
<tr>
    <td width="100%"  align="center" class="tahoma1"><a style="text-decoration:none" href="view_tarh_form.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
</tr>

</table>


