<?php


$color="PALETURQUOISE";
 	echo "<br><br>"; 
	 
	//$result=mysql_query($query1) or die("Error in selecting data from user_login1");

	$query2="select * from tarh where cod_tarh='$cod_tarh'";
	$result2=mysql_query($query2) or die("Error in selecting data from user_login11");
	$row_fetched2=mysql_fetch_array($result2);
	$first_ostad=$row_fetched2['first_ostad'];
	//echo $first_ostad;
	$second_ostad=$row_fetched2['second_ostad'];
	$first_ostad_moshaver=$row_fetched2['first_ostad_moshaver'];
	$second_ostad_moshaver=$row_fetched2['second_ostad_moshaver'];
	$email=$row_fetched2['creator'];
	if (strcmp($first_ostad,"")!=0 or strcmp($second_ostad,"")!=0 or strcmp($first_ostad_moshaver,"")!=0 or strcmp($second_ostad_moshaver,"")!=0)
	{
	echo "<table border=\"1\" width=\"500\" dir='rtl' cellpadding=\"0\" cellspacing=\"0\">";
 	
	echo "<tr>";
	echo "<td width=\"10%\" align='center' bgcolor='$color' class=\"tahoma1\"><b>سمت</b></td>";
	echo "<td width=\"10%\" align='center' bgcolor='$color' class=\"tahoma1\"><b>نام</b></td>";
	echo "<td width=\"10%\" align='center' bgcolor='$color' class=\"tahoma1\"><b>نام خانوادگي</b></td>";
	echo "<td width=\"10%\" align='center' bgcolor='$color' class=\"tahoma1\"><b>تخصص</b></td>";
	//echo "<td width=\"10%\" align='center' bgcolor='$color' class=\"tahoma1\">حذف</td>";
	echo "</tr>";
	}
	$qu="select * from user_login where email='$first_ostad'";
	$rsl=mysql_query($qu) or die("Error in selecting data from user_login21");
	$rf=mysql_fetch_array($rsl);
	$name1=$rf['name'];
	$family1=$rf['family'];
	$takhasos1=$rf['takhasos'];
	
	
	
	 
	 echo "<input type='hidden' name='ostad' value='$ostad'>";
	 
    if(strcmp($first_ostad,"")!=0 ){
     echo "<tr>";
     echo "<td width=\"2%\" bgcolor=$color align='center' class=\"tahoma1\">استاد راهنماي اول</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$name1."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$family1."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$takhasos1."</td>";
 	 //echo "<td  bgcolor=$color><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=ostad_rahnama.phtml&admin=$admin&seed=$seed&action=delete_ostad&cod_tarh=".$cod_tarh."&delete_id=".$ostad."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 	 echo "</tr>";
    }
    if(strcmp($second_ostad,"")!=0 ){
    	$qu="select * from user_login where email='$second_ostad'";
	$rsl=mysql_query($qu) or die("Error in selecting data from user_login21");
	$rf=mysql_fetch_array($rsl);
	$name2=$rf['name'];
	$family2=$rf['family'];
	$takhasos2=$rf['takhasos'];
    		echo "<tr>";
 	 echo "<td width=\"2%\" bgcolor=$color align='center' class=\"tahoma1\">استاد راهنماي دوم</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$name2."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$family2."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$takhasos2."</td>";
 	// echo "<td  bgcolor=$color><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=ostad_rahnama.phtml&admin=$admin&seed=$seed&action=delete_ostad&cod_tarh=".$cod_tarh."&delete_id=".$ostad."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 	 echo "</tr>";
 	 
    }
	 if(strcmp($first_ostad_moshaver,"")!=0 ){
      $qu="select * from user_login where email='$first_ostad_moshaver'";
	$rsl=mysql_query($qu) or die("Error in selecting data from user_login21");
	$rf=mysql_fetch_array($rsl);
	$name3=$rf['name'];
	$family3=$rf['family'];
	$takhasos3=$rf['takhasos'];
   	echo "<tr>";
 	 echo "<td width=\"2%\" bgcolor=$color align='center' class=\"tahoma1\">استاد مشاور اول</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$name3."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$family3."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$takhasos3."</td>";
 	 //echo "<td  bgcolor=$color><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=ostad_rahnama.phtml&admin=$admin&seed=$seed&action=delete_ostad&cod_tarh=".$cod_tarh."&delete_id=".$ostad."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 	 echo "</tr>";
 	 
    }
	 if(strcmp($second_ostad_moshaver,"")!=0 ){
    $qu="select * from user_login where email='$second_ostad_moshaver'";
	$rsl=mysql_query($qu) or die("Error in selecting data from user_login21");
	$rf=mysql_fetch_array($rsl);
	$name4=$rf['name'];
	$family4=$rf['family'];
	$takhasos4=$rf['takhasos'];
	 echo "<tr>";
 	 echo "<td width=\"2%\" bgcolor=$color align='center' class=\"tahoma1\">استاد مشاور دوم</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$name4."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$family4."</td>";
 	 echo "<td width=\"10%\" bgcolor=$color align='center' class=\"tahoma1\">".$takhasos4."</td>";
 	// echo "<td  bgcolor=$color><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=ostad_rahnama.phtml&admin=$admin&seed=$seed&action=delete_ostad&cod_tarh=".$cod_tarh."&delete_id=".$ostad."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 	 echo "</tr>";
 	 
    }
	echo "</table>";	
	 footer_forms($admin,$seed);