<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>

<script>
function checkit(){
	var key
	key = window.event.keyCode
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	  window.event.returnValue= false;

}
</script>

<?
echo "<br>";


if (strcmp($action,"add")==0)
{
  if(strlen(trim($safte_number)) > 0 )
  {
    $query="select * from factor_gharardad  where  safte_number=\"$safte_number\" ";

    $result=mysql_query($query) or die("Error in query data from tarh-type");
    if(mysql_num_rows($result) <= 0)
    {
      $query="insert into factor_gharardad set  cod_tarh=\"$cod_tarh\",safte_number='$safte_number', safte_mablagh ='$safte_mablagh'";
	  //echo $query;
      mysql_query($query) or die ("Error in inserting data in tarh-type");
    }
     else
      $status="duplicate_entry";
  }
  else
   $status="entry_error";
}


if (strcmp($action,"del")==0)
{
  if(strlen(trim($delete_id)) > 0 )
  {
    $query="select * from factor_gharardad where  id=\"$delete_id\"";

    $result=mysql_query($query) or die("Error in query data from tarh-type");
    if(mysql_num_rows($result) > 0)
    {
      $query="delete from factor_gharardad where id='$delete_id'";

      mysql_query($query) or die ("Error in inserting data in tarh-type");
    }

  }
}


$query="select * from tarh where cod_tarh='$cod_tarh' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $zarorat_ejra=$row_fetched["zarorat_ejra"];
  $bayan_masale=$row_fetched["bayan_masale"];
  $bayan_masale=$row_fetched["bayan_masale"];
  $taarif_vajeh=$row_fetched["taarif_vajeh"];
  $hadaf_faree=$row_fetched["hadaf_faree"];
  $hadaf_kolli=$row_fetched["hadaf_kolli"];
  $hadaf_jozii=$row_fetched["hadaf_jozii"];
  $hadaf_karbordi=$row_fetched["hadaf_karbordi"];
  $soalat_pajoheshi=$row_fetched["soalat_pajoheshi"];
  $farziatt=$row_fetched["farziatt"];
  $fehrest_manabea=$row_fetched["fehrest_manabea"];
  $mablagh_aghd_gharardad=$row_fetched["mablagh_aghd_gharardad"];   
  
 $query1="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
$res=mysql_query($query1) or die("Error");
$myrf=mysql_fetch_array($res);

$need_pish_pardakht=$myrf["pish_pardakht"];
$is_heiat_elmi=$myrf["heiat_elmi"];
if(strcmp(trim($need_pish_pardakht),"1")==0)
{
	
	if(strcmp(trim($is_heiat_elmi),"1")==0)
	{
	  $pish_pardakht=($mablagh_aghd_gharardad*40)/100;
	  
	  if($pish_pardakht <= 40000000)
	   $sefte=0;
	  else
	   $sefte=$pish_pardakht-40000000; 	
	}
	else
	{
	  $pish_pardakht=(int)(($mablagh_aghd_gharardad*40)/100);	
	  $sefte=$pish_pardakht;
	  
	}
}
else
  $sefte=0;
  
   echo "<form name=\"add-tarh\" method=\"post\"  action=\"$PHP_SELF?action=add&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>
<TABLE cellSpacing=0 cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center width="500" class="tahoma1"  dir="rtl" height=19 bgcolor="#EEE7F8">
      <?
	   echo ""."عنوان طرح   : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>




 <TABLE cellSpacing=0 cellPadding=0 border=0 width="100%">
  <TBODY>
    <TR>
    <TD align=middle width="100%"   height=19 class="tahoma1" align="right">
    (پاسخ به سوالات کارشناسان (مرحله سوم 
    <br>
    <?
	 if($sefte==0)
	   echo "<br>شما نياز به تهيه سفته نداريد";
	 else
	   echo " شما بايد به مبلغ ".number_format($sefte)." ريال سفته تهيه کنيد "."<br>";  
	?>
    
	</TD>
  </TR>
  </TBODY>
  </TABLE>
  
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


  <table border="0"  width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  
  if (strcmp($status,"sum_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مجموع رقم سفته ها به مجموع رقمي که بايد سفته بدهيد متفاوت است</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">
        <div align="center">
          <table border="0" width="100%" bgcolor="F0F0FF" height="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="safte_number" size="48" class="edit-tarh-type"   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>سريال سفته</td>
            </tr>

            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="safte_mablagh" size="48" class="edit-tarh-type"   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>مبلغ سفته</td>
            </tr>
           
            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="اضافه" name="submit_tarh"></td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
  </table>
</form>
<br>

<?
 $query="select * from factor_gharardad  where  cod_tarh=\"$cod_tarh\" ";

 $result=mysql_query($query) or die("Error in query data from tarh-type");
 if(mysql_num_rows($result) > 0)
{
    echo "<table border=\"0\" width=\"500\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"97\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"371\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">مبلغ</td>";
    echo "<td width=\"371\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">سريال سفته</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
  $Query=mysql_query("select * from factor_gharardad  where cod_tarh='$cod_tarh'") or die("Error in selecting tarh-type");
  while($row_fetched=mysql_fetch_array($Query))
  {
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
  echo "<tr bgcolor=\"$color\">";
  echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
  echo "<td width=\"97\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=answer_questions2.phtml&cod_tarh=$cod_tarh&admin=$admin&seed=$seed&action=delete&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 
 echo "<td width=\"100\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".substr($row_fetched["safte_mablagh"],0,100)."</td>";
  
  echo "<td width=\"271\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".substr($row_fetched["safte_number"],0,100)."</td>";
  echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
  echo "</tr>";

  }
  echo "<tr>";
  echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
  //echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"97\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"100\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"271\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
  echo "</tr>";
  echo "</table>";
}
else
{

  echo "<p align=\"center\"  class=\"tahoma1\">با کليک روي کليد اضافه ميتوانيد يک شماره سفته اضافه کنيد  اضافه کنيد";

}
?>
 <table border="0" width="100%"  cellpadding="0" cellspacing="0">
<tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="button" onclick="javascript: window.location='<? echo "answer_questions1.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh";?>'" value="مرحله قبل" name="B2" class="but-small"><input type="button"  onclick="javascript: window.location='<? echo "answer_questions3.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh";?>'" value="مرحله بعد" name="B1" class="but-small"></td>
  </tr>
  </table>
<?
   footer_forms($admin,$seed);
?>



