<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

if(isset($action))
{
 if(strcmp($action,"del")==0)
  {
    
     $query="delete from tarh where cod_tarh=\"$delete_id\"";
     //echo $query;
     $result=mysql_query($query) or die("Error in updating data into tarh1");
     $query="delete from shora_tarh_vaziat where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh2");
     $query="delete from sayer_hazine where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh3");
     $query="delete from ravesh_ejra where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh4");
     $query="delete from mojri_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh5");
     $query="delete from letter_to_mojri where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh6");
     $query="delete from karshenasan_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh7");
     $query="delete from jadval_zarayeb where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh8");
     $query="delete from hazine_safar where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh9");
     $query="delete from hazine_personnel where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh10");
     $query="delete from hazine_azmayesh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh11");
     $query="delete from hamkar_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh12");
     $query="delete from fhrest_vasayel_kharid where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh13");
     //$query="delete from daneshjo_tarh where cod_tarh=\"$delete_id\"";
    // $result=mysql_query($query) or die("Error in updating data into tarh14");    
     $action=". طرح با کد مقابل حذف شد"."<br>".$delete_id;   
     set_log($action,$admin,date("Y-m-d, g:i a"));
     savelog($admin,'delete','delete tarh '.$cod_tarh);
	
  }
}

if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
$ready_gharardad = " 1 ";


if(isset($ready_contract))
{
	if(strcmp($ready_contract,"-1")==0)
       $ready_gharardad = " 1 ";
	if(strcmp($ready_contract,"1")==0)
       $ready_gharardad = " ready_gharardad='1' ";
    if(strcmp($ready_contract,"2")==0)
       $ready_gharardad = " ready_gharardad!='1' ";
   
}

 
$grant_hsr_isolation='tarh_type!=6';
$grant_hsr_isolation="(tarh_type!=6 or tarh_select!='0')";
/*
$myq="select * from tarhtype_2 where grant_tarh='1'";
$res=mysql_query($myq) or die("Error");
$grant_q="";
While($myrf=mysql_fetch_array($res) )
{
	$grant_q=$grant_q." and "."tarh_type_2 != '".$myr["tarh_type"]."'";
}

$grant_hsr_isolation=$grant_hsr_isolation.$grant_q;
*/
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
    

if(isset($name_e))
{
  $query="select * from tarh  where      archieved='1' and   (cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)    and  tarh.creator='$admin' and version='-1'  group by cod_tarh order by tarh_time desc";
}
else
  $query="select * from tarh  where     archieved='1'   and  tarh.creator='$admin' and version='-1'  group by cod_tarh order by tarh_time desc";
//echo $query;

$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);

 if(isset($name_e))
{
  $query="select * from tarh  where      archieved='1'  and  (cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and version='-1'    and  tarh.creator='$admin' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ; 
}
else
  $query="select * from tarh  where        archieved='1'    and tarh.creator='$admin' and version='-1'  group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh2");
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرح هاي بايگاني شده<b></td>
 </tr>
 </table>
 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&name_e=$name_e&seed=$seed&ascdescfield=$ascdescfield&ascdesc=$ascdesc\">";
?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
  
  <?
  echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&ready_contract=$ready_contract\">";
?>
 
 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
	$myascdescpub=$myascdescpub."$name_e=$name_e&ready_contract=$ready_contract";
 pubshowpages("archieved.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
<!--   <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">حذف</font></td> --> 
   <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دليل آرشيو</font></td> 
  
  <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">خروج از آرشيو</font></td> 
    
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
        <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کارشناس مربوطه</font></td>
     
         
      
	 <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نوع طرح</font></td>
     
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  <?

 $color=$list_color_1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  
   $tarh_select=$row_fetched["tarh_select"];
  $tarh_select_desc="";
  if(strcmp($tarh_select,'0')==0)
   $tarh_select_desc="طرح دانشجويي";
  if(strcmp($tarh_select,'1')==0)
   $tarh_select_desc="HSR";
  if(strcmp($tarh_select,'2')==0)
   $tarh_select_desc="طرح غير پايان نامه اي";
  if(strcmp($tarh_select,'3')==0)
   $tarh_select_desc="طرح پايان نامه اي";
   
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";


  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.finished='0' and group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas order by group_karshenasan_tarh.id desc ";
  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas  and (group_karshenasan.username='rahmani' or group_karshenasan.creator='rahmani') order by id desc";
  $myres=mysql_query($myq1) or die("Error");
  
  if(mysql_num_rows($myres) > 0)
  {
    $myrf=mysql_fetch_array($myres);
    $name_family_sender=$myrf["karshenas_name"]."&nbsp;".$myrf["karshenas_family"]."&nbsp;<br>".$myrf["mobile"];
  }
  else
  {
  	 $name_family_sender="نامعلوم";
  }
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=archieved.phtml&admin=$admin&seed=$seed&action=del&cod_tarh=".$cod_tarh."&delete_id=".$cod_tarh."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
   echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["archieve_reason"]."</td>";
  $archiever=current_position($cod_tarh);
  
  if(strcmp($archiever,'21')!=0)
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">طرح توسط مدير سيستم آرشيو شده</td>";
  else 
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&unarchieve=1\" ><img border=\"0\" src=\"image/archive.jpg\" alt=\"archive\" ></a></td>";
   
     
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$name_family_sender</td>";
  //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"group_karshenas_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\"  alt=\"Notes\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_moavenat.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Moavenat\" ></a></td>";
// echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["rotbe_tarh"]."</td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target = \"_blank\" href=\"shenasname_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/shenasname_tarh.gif\" width=\"11\" height=\"13\" alt=\"Shenasname tarh\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";

  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  //send_moavenat='0' 
  
   if($row_fetched["status"]=="0")
      {
       if($row_fetched["confirm_tarh"]=="1")
  	     $mystatus="در دست بررسي";
    	else   
         $mystatus="نامعلوم";
      } 
     else
      {
        $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
        $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
        $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
        $mystatus=$row_fetched_tarh["vaziat_desc"];
        if($row_fetched_tarh["view_or_no"]=="1")
           $editable=0;
        else
           $editable=1;
      }
  
  if($row_fetched["send_moavenat"]!="0")
  {
  	$mystatus=$mystatus." /"." ارسال شده به معاونت پژوهشي";
  }
  if($row_fetched["confirm_moaven_tarh"]!="0")
  {
  	$mystatus=$mystatus." /"." در دست بررسي در معاونت پژوهشي";
  }

  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration : none\" href=\"change_status.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mystatus."</a></td>";
  //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_moavenat.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/send_daneshkade.gif\" alt=\"Send Moavenat\" ></a></td>";
 // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"change_year_rank.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Change Rank\" ></a></td>";
   echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$tarh_select_desc."</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $farsistartdate."</a></td>";
  
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
    $First_mojri_name = "اطلاعات موجود نيست";
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td   bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  echo "<td  bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["cod_tarh"]."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
footer_forms($admin,$seed);


?>

