<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");
$ostad_taype1_caution="";
if ( ! isset($ostad_taype1))
    $ostad_taype1 = '-1';
 
if(strcmp($ostad_taype1,'-1')==0 )
{
	$ostad_taype1_caution="(first_ostad='$admin' or second_ostad='$admin' or third_ostad='$admin' or forth_ostad='$admin' or  first_ostad_moshaver='$admin' or second_ostad_moshaver='$admin' or third_ostad_moshaver='$admin' or forth_ostad_moshaver='$admin')";
}
elseif(strcmp($ostad_taype1,'0')==0){
	$ostad_taype1_caution="(first_ostad='$admin' or second_ostad='$admin' or third_ostad='$admin' or forth_ostad='$admin')";
}
elseif(strcmp($ostad_taype1,'1')==0){
	$ostad_taype1_caution="(first_ostad_moshaver='$admin' or second_ostad_moshaver='$admin' or third_ostad_moshaver='$admin' or forth_ostad_moshaver='$admin')";
}


if(isset($action) && strcmp($action,"sabt_tarh")==0)
{

 for($i=0;$i<30;$i++)
   {
    $myvariable="sabtetarh".$i;
    
 //  echo $$myvariable;
    if (isset($$myvariable))
    {
      $myvariable="sabtetarh".$i;
      
      $q="update tarh set accepttarh='1' where cod_tarh='".$$myvariable."' and version='-1'";
     // echo $q;
	  $rss=mysql_query($q) or die("error");
	  insert_position($cod_tarh,"32",$admin);
	///  echo $q;
  }
}
}
echo "<br>";

$query="select * from user_login where  email=\"$admin\"";

$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");

if ( mysql_num_rows($result) > 0 )
{
   	$rf=mysql_fetch_array($result);
    if( strlen(trim($rf["mobile"])) <= 0 || strlen(trim($rf["melli_code"])) <= 0   || strlen( trim($rf["takhasos"]) ) <= 0   )
	{
	   	 ?>
           <script language="javascript">
           window.location="<? echo "profile.phtml?admin=$admin&seed=$seed";  ?>";
           </script>
           <?
	}  
}
    
   
if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh  where archieved='0' and indoing='0' and $ostad_taype1_caution and  payannameh='1' and   is_tarh='0' and ready_gharardad='0' and ( tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)   and version=\"-1\" order by tarh_time desc";
}
else
  $query="select * from tarh   where  archieved='0' and $ostad_taype1_caution and indoing='0' and  payannameh='1' and   is_tarh='0' and ready_gharardad='0'   and version=\"-1\"  order by tarh_time desc";

$result=mysql_query($query) or die("Error in selecting data from tarh");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e))
{
  $query="select * from tarh where  archieved='0' and indoing='0' and $ostad_taype1_caution and payannameh='1' and   is_tarh='0' and ready_gharardad='0' and (tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)   and version=\"-1\"  order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from tarh where  archieved='0' and indoing='0' and  $ostad_taype1_caution and payannameh='1' and   is_tarh='0' and ready_gharardad='0'   and version=\"-1\"  order by tarh_time desc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;


  $myquery_mojri = "SELECT  * FROM  user_login WHERE user_login.email='$admin'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }


$result=mysql_query($query) or die("Error in selecting data from tarh");
 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
  <tr>
   <td width="100%"   >
      <p align="center" class="tahoma1"><font color="black"><b>پايان نامه هايي که شما استاد راهنماي آن هستيد</b></font></td>
   </td>
   </tr>
   </table>
   <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>

 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc\">";
?>
 <?php echo "<td  align=\"left\" class=\"tahoma1\">  <select class='tahoma1' size=\"1\" name=\"ostad_taype1\" onchange=\"JavaScript:document.change_daneshkade.submit();\"  dir=\"rtl\">";
	if(strcmp($ostad_taype1,'-1')==0)
		$selected=" selected ";
	else
	  $selected=""; 
 echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";
if(strcmp($ostad_taype1,'0')==0)
		$selected=" selected ";
	else
	  $selected=""; 
 echo "<option $selected value=\"0\" class=\"tahoma1\">استاد راهنما هستيد</option>";
if(strcmp($ostad_atype1,'1')==0)
		$selected=" selected ";
	else
	  $selected=""; 
 echo "<option $selected value=\"1\" class=\"tahoma1\">استاد مشاور هستيد</option>";
 ?>
 	
 	
 </td>
 <?
 echo "</form>";
echo "<form name=\"change_daneshkade1\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc\">";
?>
 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small"  dir=RTL   >
 </td>
 </tr>
 </table>
 </form>
<?
}
if(mysql_num_rows($result) > 0 )
{
	echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&action=sabt_tarh\">";
 pubshowpages("ostad_payan_name.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
 
 
  <tr>
   
     <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>
     <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کارشناس مربوطه   </font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تبديل پايان نامه به طرح</font></td>
      
   <!-- <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بايگاني</font></td>  -->
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظرات</font></td>  
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نامه ها</font></td>      
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت پايان نامه <br> از لحاظ اخلاقي </font></td> 
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاييد استاد</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ تسويه حساب</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ دفاع</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ناريخ عقد قرار داد</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نوع استاد</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکدا / مرکز</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مقطع تحصيلي</font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام ونام خانوادگي دانشجويي</font></td>
   <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد دانشجويي</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  <?


 $color=$list_color_1;
$i=0;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  
  $moshaver_amar=$row_fetched["moshaver_amar"];
  $moshaver_tarrah=$row_fetched["moshaver_tarrah"];
  $first_ostad=$row_fetched["first_ostad"];
   $first_ostad=strtolower($first_ostad);
    $admin=strtolower($admin);
  $first_ostad_flag='0';
  if(strcmp($first_ostad,"$admin")==0)
    $first_ostad_flag='1';
  
  $query="select karshenasan.*,karshenasan_tarh.*,karshenasan_tarh_note.comment_karshenas,karshenasan_tarh_note.note_date,karshenasan_tarh_note.id as main_note_id from karshenasan,karshenasan_tarh_note,karshenasan_tarh where karshenasan_tarh.karshenasi_type='1'  and karshenasan_tarh.finished='1' and karshenasan_tarh.cod_tarh=karshenasan_tarh_note.cod_tarh and karshenasan_tarh.cod_karshenas=karshenasan_tarh_note.cod_karshenas  and  karshenasan_tarh.cod_tarh='$cod_tarh' and karshenasan.cod_karshenas=karshenasan_tarh_note.cod_karshenas and mojri_view='1' order by karshenasan_tarh_note.id desc";
  
   $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and group_karshenasan.karshenas_type='1'  and (group_karshenasan.username='rahmani' and group_karshenasan.creator='rahmani')";

 // $query="select karshenasan_tarh.*   from  karshenasan_tarh where karshenasan_tarh.karshenasi_type='1'  and karshenasan_tarh.finished='1'  and  karshenasan_tarh.cod_tarh='$cod_tarh' and mojri_view='1' ";
		  				  
 // echo $query;
  $result_karshenasan_notes=mysql_query($myq1) or die("Error in selecting data from group_karshenasan_tarh 2");
$result_karshenasan_notes_cnt=mysql_num_rows($result_karshenasan_notes);

   $tarh_select=$row_fetched["tarh_select"];
  $tarh_select_desc="";
  if(strcmp($tarh_select,'0')==0)
   $tarh_select_desc="طرح دانشجويي";
  if(strcmp($tarh_select,'1')==0)
   $tarh_select_desc="HSR";
  if(strcmp($tarh_select,'2')==0)
   $tarh_select_desc="طرح غير پايان نامه اي";
  if(strcmp($tarh_select,'3')==0)
   $tarh_select_desc="طرح پايان نامه اي";
   if(strcmp($tarh_select,'4')==0)
   $tarh_select_desc="فناوري اطلاعات";
  
  $submit_moshaver_amar=$row_fetched["submit_moshaver_amar"];
  $submit_moshaver_tarrah=$row_fetched["submit_moshaver_tarrah"];
  
  
  
  
  
  $in_doing=$row_fetched["indoing"];
  $ready_gharardad=$row_fetched["ready_gharardad"];
  $finalized=$row_fetched["finalized"];
  $confirm_daneshkade_title=$row_fetched["confirm_daneshkade_title"];
  $tarh_select=$row_fetched["tarh_select"];
  
   $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
 
  if( strcmp($row_fetched["ready_gharardad"],"1")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"12")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"13")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"14")==0)
       $editable=0;
    else
       $editable=1;
//  echo  $editable;
  $position_tarh_code=current_position($cod_tarh);
  $query1="select * from letter_to_mojri where (to_letter='$admin' and cod_tarh='$cod_tarh' and visited='0'and admin_confirm ='1' ) order by cod_tarh desc";
 // echo $query1;
  $result1=mysql_query($query1) or die("error");
  if(mysql_num_rows($result1) > 0)
    $new_msg="image/letter_new.gif";    
    else 
  $new_msg="image/letter.gif";  
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
  $editable=1;
  $vaziat_moaven = $row_fetched["vaziat_moaven"];
  $vaziat_daneshkade=$row_fetched["vaziat"];
  $mystatus_daneshkade="";
 
 //-------------------------------------------------------------------------------------- 
 	$payanname_akhlagh=$row_fetched["payanname_akhlagh"];
 	if(strcmp($payanname_akhlagh,"-1")==0){
 		$payanname_akhlagh_status="در دست بررسي";
 	}
 elseif(strcmp($payanname_akhlagh,"0")==0){
 		$payanname_akhlagh_status="رد اخلاق";
 	}
 	else 
 	{
 		$payanname_akhlagh_status="تاييد اخلاق";
 	}
 	
  //--------------------------------------------------------
  //echo $row_fetched["confirm_tarh"].":".$daneshkade_tarh_type.":".$mytarh_type;
  if($row_fetched["vaziat"]=="0")
    {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus_daneshkade="<br>"." دانشکده: "."در دست بررسي";
  	else   
       $mystatus_daneshkade="<br>"." دانشکده: "."نامعلوم";
  } 
  else
  {
  	$query="select * from vaziat_tarh where vaziat='$vaziat_daneshkade'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus_daneshkade="<br>"." دانشکده: ".$row_fetched_tarh["vaziat_desc"]."<br>";   
  }
  //--------------------------------------------------------------------------------------
  
   if($vaziat_moaven=="0")
   {
    if($row_fetched["confirm_moaven_tarh"]=="1")
  	   $mystatus_moavenat="<br>"." معاونت: "."در دست بررسي";
  	else   
       $mystatus_moavenat="<br>"." معاونت: "."نامعلوم";
   } 
  else
  {
  	$query="select * from vaziat_tarh where vaziat='$vaziat_moaven'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus_moavenat="<br>"." معاونت: ".$row_fetched_tarh["vaziat_desc"]."<br>";   
    
  }
  
  $mystatus=$mystatus_daneshkade."<br>".$mystatus_moavenat;
 //--------------------------------------------------------------------------------------

 
  $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
  $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
  $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
 // $mystatus="<br>"." معاونت: ".$row_fetched_tarh["vaziat_desc"]."<br>".$mystatus;   
  
  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.finished='0' and group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and   (group_karshenasan.username!='ar_shamshiri' and group_karshenasan.creator!='ar_shamshiri') order by group_karshenasan_tarh.id desc ";
 
  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas  and (group_karshenasan.username='rahmani' or group_karshenasan.creator='rahmani') order by id desc";

  $myres=mysql_query($myq1) or die("Error");
  $name_family_sender="";
  if(mysql_num_rows($myres) > 0)
  {
     $myrf=mysql_fetch_array($myres);
      $vaziat_hozor=$myrf["vaziat_hozor"];
	  if(strcmp($vaziat_hozor,"1")==0)
	     $vaziat_hozor="حاضر";
	  if(strcmp($vaziat_hozor,"2")==0)
	     $vaziat_hozor="مرخصي ساعتي";
	  if(strcmp($vaziat_hozor,"3")==0)
	     $vaziat_hozor="مرخصي ";
		 
     $name_family_sender=$name_family_sender."<br>".$hand."&nbsp;".$myrf["karshenas_name"]."&nbsp;".$myrf["karshenas_family"]."&nbsp;<br>".$myrf["mobile"]."<br>".$vaziat_hozor."<br>";
     
  }
  else
  {
  	 $name_family_sender="نامعلوم";
  }
  
  
      $query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";
   $rs34=mysql_query($query) or die("error 6677");
   $rf54=mysql_fetch_array($rs34);
   $user_email=$rf54["creator"];
   $first_ostad =$rf54["first_ostad"];
   $second_ostad  =$rf54["second_ostad"];
   $third_ostad =$rf54["third_ostad"];
   $forth_ostad  =$rf54["forth_ostad"];
   $first_ostad_moshaver =$rf54["first_ostad_moshaver"];
   $second_ostad_moshaver =$rf54["second_ostad_moshaver"];
   $third_ostad_moshaver =$rf54["third_ostad_moshaver"];
   $forth_ostad_moshaver =$rf54["forth_ostad_moshaver"];

   $accepttarh   =$rf54["accepttarh"];
   $first_ostad=strtolower($first_ostad);
   $first_ostad_moshaver=strtolower($first_ostad_moshaver);
   
   $type_ostad="";
   //echo $first_ostad;
   if(strcmp($first_ostad,"$admin")==0){
	   $type_ostad='استاد راهنماي اول';
	   }
	     
 if(strcmp($second_ostad,"$admin")==0){
 	
	   $type_ostad='استاد راهنماي دوم';
	   }
 if(strcmp($third_ostad,"$admin")==0){
	   $type_ostad='استاد راهنماي سوم';
	   }
 if(strcmp($forth_ostad,"$admin")==0){
	   $type_ostad='استاد راهنماي چهارم';
	   } 
	   if(strcmp($first_ostad_moshaver,"$admin")==0  || strcmp($second_ostad_moshaver,"$admin")==0 || strcmp($third_ostad_moshaver,"$admin")==0 ||  strcmp($forth_ostad_moshaver,"$admin")==0){
		   $type_ostad='مشاور';
		   }
   
    $querycodedane="select * from user_login,darajeelmi where  user_login.email='$user_email'";
   
     $resultcodedaneshjoo=mysql_query($querycodedane) or die("error querycodedane");
     $array_resultcodedaneshjoo=mysql_fetch_array($resultcodedaneshjoo);
   		$daneshjo_no=$array_resultcodedaneshjoo['daneshjo_no'];
		$name=$array_resultcodedaneshjoo['name'];
		$family=$array_resultcodedaneshjoo['family'];
		$fullname=$name.'&nbsp;'.$family;
		$madrak=$array_resultcodedaneshjoo['madrak'];
		if($madrak==1){
			$maghtah='زير کارشناسي';
		}elseif($madrak==2){
			$maghtah='کارشناسي';
		}elseif($madrak==3){
			$maghtah='کارشناسي ارشد';
		}elseif($madrak==4){
			$maghtah='دکتراي حرفه اي';
		}elseif($madrak==5){
			$maghtah='PHD';
		}elseif($madrak==6){
			$maghtah='تخصص';
		}elseif($madrak==7){
			$maghtah='فوق تخصص';
		}elseif($madrak==8){
			$maghtah='MPH';
		}
   $query11="select * from user_login,darajeelmi where user_login.darajeelmi=darajeelmi.darajeelmi and user_login.email='$user_email'";
   
     $result11=mysql_query($query11) or die("error 6677");
     $rf45=mysql_fetch_array($result11);
 
  
  
  
  if(strcmp($position_tarh_code,'24')==0 && strcmp($rf45["need_moshavereh"],'1')==0)
  {
  	if(strcmp($submit_moshaver_amar,'0')==0)
	  $str_code="<br>"."تاييد مشاور آمار ندارد"."($moshaver_amar_name) <br> ";
	else
	  $str_code="<br>"."تاييد مشاور آمار دارد"."<br> ";   
	
   if(strcmp($submit_moshaver_tarrah,'0')==0)
	  $str_code=$str_code."<br>"."تاييد مشاور طراحي ندارد"."($moshaver_tarrah_name) <br> ";
	else
	  $str_code=$str_code."<br>"."تاييد مشاور طراحي دارد"." <br> ";     
  }  
  else
    $str_code=""; 
 // echo "<td  dir='rtl' bgcolor=$color align=\"center\" class=\"tahoma1\">$str_code ".$position_tarh["$position_tarh_code"]."</td>";
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ويرايش ها</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$name_family_sender</td>";
  if(strcmp($first_ostad_flag,'1')==0)
   echo  "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"create_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >تبديل</a></td>";
  else
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">----</td>";
   
  
  
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";


//  if(  $editable &&  strcmp($row_fetched["finished"],"0")==0)
 //   echo  "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border='0'  src=\"image/archive.jpg\"   alt=\"Archive\" ></a></td>";
 // else
 //   echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/archive.jpg\"   alt=\"Archive\" ></td>";    
        
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"></a></td>"; 
	
	if(strcmp($first_ostad_flag,'1')==0)
 {
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"$new_msg\"></a></td>";
  }
  else
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">----</td>";

  
  
   
 
 
 
  $mytarh_type = $row_fetched["status"];
 
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
//  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dirl='rtl'>".$mystatus."</td>";
// echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$tarh_select_desc."</a></td>";
	echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$payanname_akhlagh_status</td>";
 if(strcmp($first_ostad_flag,'1')==0)
 {
    if($accepttarh)
    {
      echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\" id='sabtetarh'>تاييد شده</td>";
    }
    else
    {
	  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\" id='sabtetarh'><input value='$cod_tarh' type='checkbox' name='sabtetarh".$i."'  /></td>";
	  echo "<input type='hidden' name='sabtetarh_code".$i."' value='$cod_tarh'>";
    }
  }	
  else
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\" id='sabtetarh'>----</td>";
	
	$i++;
 echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$farsistartdate."</a></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$type_ostad</td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$daneshkade</td>";
    
  //echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_english"]."</a></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$maghtah."</td>";
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$fullname."</td>";
	 echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$daneshjo_no."</td>";
  echo "<td   bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  
  $cod_tarh=$row_fetched["cod_tarh"];


  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";

  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/

 }
 
 	echo "<tr>";
	 echo "<td  colspan='52' bgcolor=$color align=\"center\" class=\"tahoma1\" class=\"but-small\"> <input type='submit' value='تاييد' > </td>";

	echo "</tr>";
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".در حال حاضر  پايان نامه اي که استاد راهنماي آن شما باشيد  وجود ندارد","red");
}
echo "</form>";

//echo  "<iframe cols=\"150,300\" name=\"main\" src=\"informatics.phtml?admin=$admin&seed=$seed\">";

footer_forms($admin,$seed);
?>

