<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");


echo "<br>";

$query="select * from user_login where  email=\"$admin\"";

$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");

if ( mysql_num_rows($result) > 0 )
{
   	$rf=mysql_fetch_array($result);
    if( strlen(trim($rf["mobile"])) <= 0 || strlen(trim($rf["melli_code"])) <= 0   || strlen( trim($rf["takhasos"]) ) <= 0   )
	{
	   	 ?>
           <script language="javascript">
           window.location="<? echo "profile.phtml?admin=$admin&seed=$seed";  ?>";
           </script>
           <?
	}  
}
    
   
if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh  where archieved='0' and indoing='0' and   payannameh='1' and   is_tarh='0' and ready_gharardad='0' and ( tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and creator = '$admin' and version=\"-1\" order by tarh_time desc";
}
else
  $query="select * from tarh   where  archieved='0' and indoing='0' and  payannameh='1' and   is_tarh='0' and ready_gharardad='0' and creator = '$admin'  and version=\"-1\"  order by tarh_time desc";

$result=mysql_query($query) or die("Error in selecting data from tarh");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e))
{
  $query="select * from tarh where  archieved='0' and indoing='0' and  payannameh='1' and   is_tarh='0' and ready_gharardad='0' and (tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and creator = '$admin'  and version=\"-1\"  order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from tarh where  archieved='0' and indoing='0' and  payannameh='1' and   is_tarh='0' and ready_gharardad='0' and creator = '$admin'  and version=\"-1\"  order by tarh_time desc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
//echo $query;
  $myquery_mojri = "SELECT  * FROM  user_login WHERE user_login.email='$admin'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }


$result=mysql_query($query) or die("Error in selecting data from tarh");
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
  <tr>
   <td width="100%"   >
      <p align="center" class="tahoma1"><font color="black"><b>پايان نامه ها</b></font></td>
   </td>
   </tr>
 <tr>
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
	
 pubshowpages("payan_name_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
 
 
  <tr>
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">آرشيو پايان نامه</font></td>
   
     <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
      
     <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کارشناس مربوطه   </font></td>
      <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مدير پايان نامه   </font></td>
     <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت پاياننامه از نظر تاييد استادراهنما   </font></td>
   <!-- <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بايگاني</font></td>  -->
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><span   onmouseover="showToolTip(event,' چنانچه هنوز گزينه خاتمه و ارسال را در انتهاي اجزاي پروپوزال نزده ايد اين پايان نامه در محيط دانشکده قابل رويت نيست، ولي شما ميتوانيد اجزاي پروپوزال را ويرايش نماييد. پس از انتخاب گزينه خاتمه ارسال پايان نامه از قابليت ويرايش خارج و در محيط دانشکده قابل رويت ميشود. در چنين حالتي ميتوانيد با انتخاب علامت قفل از دانشکده درخواست ويرايش نموده و اين دانشکده است که پايان نامه را براي شما باز نموده تا بتوانيد آن را ويرايش نماييد'  );return false" onmouseout="hideToolTip()"><img src='../images/help_icon.jpg' border='0' /></span><font color="black">ويرايش / درخواست ويرايش</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نامه ها</font></td>      
   <!-- <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح در<br> دانشکده <br>معاونت</font></td> -->
   
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکدا / مرکز</font></td>
  
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td   bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد پايان نامه</font></td>
  </tr>
  <?


 $color=$list_color_1;

 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  
  $moshaver_amar=$row_fetched["moshaver_amar"];
  $moshaver_tarrah=$row_fetched["moshaver_tarrah"];
  
  $query="select karshenasan.*,karshenasan_tarh.*,karshenasan_tarh_note.comment_karshenas,karshenasan_tarh_note.note_date,karshenasan_tarh_note.id as main_note_id from karshenasan,karshenasan_tarh_note,karshenasan_tarh where karshenasan_tarh.karshenasi_type='1'  and karshenasan_tarh.finished='1' and karshenasan_tarh.cod_tarh=karshenasan_tarh_note.cod_tarh and karshenasan_tarh.cod_karshenas=karshenasan_tarh_note.cod_karshenas  and  karshenasan_tarh.cod_tarh='$cod_tarh' and karshenasan.cod_karshenas=karshenasan_tarh_note.cod_karshenas and mojri_view='1' order by karshenasan_tarh_note.id desc";
  
   $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and group_karshenasan.karshenas_type='1'  and (group_karshenasan.username='rahmani' and group_karshenasan.creator='rahmani')";

 // $query="select karshenasan_tarh.*   from  karshenasan_tarh where karshenasan_tarh.karshenasi_type='1'  and karshenasan_tarh.finished='1'  and  karshenasan_tarh.cod_tarh='$cod_tarh' and mojri_view='1' ";
		  				  
 // echo $query;
  $result_karshenasan_notes=mysql_query($myq1) or die("Error in selecting data from group_karshenasan_tarh 2");
$result_karshenasan_notes_cnt=mysql_num_rows($result_karshenasan_notes);

   $tarh_select=$row_fetched["tarh_select"];
  $tarh_select_desc="";
  if(strcmp($tarh_select,'0')==0)
   $tarh_select_desc="طرح دانشجويي";
  if(strcmp($tarh_select,'1')==0)
   $tarh_select_desc="HSR";
  if(strcmp($tarh_select,'2')==0)
   $tarh_select_desc="طرح غير پايان نامه اي";
  if(strcmp($tarh_select,'3')==0)
   $tarh_select_desc="طرح پايان نامه اي";
   if(strcmp($tarh_select,'4')==0)
   $tarh_select_desc="فناوري اطلاعات";
  
  $submit_moshaver_amar=$row_fetched["submit_moshaver_amar"];
  $submit_moshaver_tarrah=$row_fetched["submit_moshaver_tarrah"];
  
  
  
  
  
  $in_doing=$row_fetched["indoing"];
  $ready_gharardad=$row_fetched["ready_gharardad"];
  $finalized=$row_fetched["finalized"];
  $confirm_daneshkade_title=$row_fetched["confirm_daneshkade_title"];
  $tarh_select=$row_fetched["tarh_select"];
  
   $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
 
  if( strcmp($row_fetched["ready_gharardad"],"1")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"12")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"13")==0 || strcmp($row_fetched_tarh["vaziat_moaven"],"14")==0)
       $editable=0;
    else
       $editable=1;
//  echo  $editable;
  $position_tarh_code=current_position($cod_tarh);
  $query1="select * from letter_to_mojri where (to_letter='$admin' and cod_tarh='$cod_tarh' and visited='0'and admin_confirm ='1' ) order by cod_tarh desc";
 // echo $query1;
  $result1=mysql_query($query1) or die("error");
  if(mysql_num_rows($result1) > 0)
    $new_msg="image/letter_new.gif";    
    else 
  $new_msg="image/letter.gif";  
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
  $editable=1;
  $vaziat_moaven = $row_fetched["vaziat_moaven"];
  $vaziat_daneshkade=$row_fetched["vaziat"];
  $mystatus_daneshkade="";
 
 //-------------------------------------------------------------------------------------- 
  //echo $row_fetched["confirm_tarh"].":".$daneshkade_tarh_type.":".$mytarh_type;
  if($row_fetched["vaziat"]=="0")
    {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus_daneshkade="<br>"." دانشکده: "."در دست بررسي";
  	else   
       $mystatus_daneshkade="<br>"." دانشکده: "."نامعلوم";
  } 
  else
  {
  	$query="select * from vaziat_tarh where vaziat='$vaziat_daneshkade'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus_daneshkade="<br>"." دانشکده: ".$row_fetched_tarh["vaziat_desc"]."<br>";   
  }
  //--------------------------------------------------------------------------------------
  
   if($vaziat_moaven=="0")
   {
    if($row_fetched["confirm_moaven_tarh"]=="1")
  	   $mystatus_moavenat="<br>"." معاونت: "."در دست بررسي";
  	else   
       $mystatus_moavenat="<br>"." معاونت: "."نامعلوم";
   } 
  else
  {
  	$query="select * from vaziat_tarh where vaziat='$vaziat_moaven'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus_moavenat="<br>"." معاونت: ".$row_fetched_tarh["vaziat_desc"]."<br>";   
    
  }
  
  $mystatus=$mystatus_daneshkade."<br>".$mystatus_moavenat;
 //--------------------------------------------------------------------------------------

  $query_modir="select * from modir_daneshkade,modir_daneshkade_tarh where modir_daneshkade.cod_modir=modir_daneshkade_tarh.cod_modir and modir_daneshkade_tarh.cod_tarh='$cod_tarh'";
  $result_modir=mysql_query($query_modir) or die("Error in selectiong data from tarhtype");
  if(mysql_num_rows($result_modir) > 0 ){
  	$row_fetched_modir=mysql_fetch_array($result_modir);
  	$modir_payanname_name=$row_fetched_modir["modir_payanname_name"];
  	$email_view_able=$row_fetched_modir["email_view_able"];
  	$phone_view_able=$row_fetched_modir["phone_view_able"];
  	$mobile_view_able=$row_fetched_modir["mobile_view_able"];
  	if($email_view_able=="1"){
  		$modir_payanname_name=$modir_payanname_name."<br>".$row_fetched_modir["modir_email"];
  	}
  if($phone_view_able=="1"){
  		$modir_payanname_name=$modir_payanname_name."<br>".$row_fetched_modir["modir_tel"];
  	}
  if($mobile_view_able=="1"){
  		$modir_payanname_name=$modir_payanname_name."<br>".$row_fetched_modir["modir_mobile"];
  	}
  }
 //-------------------------------------------------
  $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
  $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
  $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
 // $mystatus="<br>"." معاونت: ".$row_fetched_tarh["vaziat_desc"]."<br>".$mystatus;   
  
  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.finished='0' and group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and   (group_karshenasan.username!='ar_shamshiri' and group_karshenasan.creator!='ar_shamshiri') order by group_karshenasan_tarh.id desc ";
 
  $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas  and (group_karshenasan.username='rahmani' or group_karshenasan.creator='rahmani') order by id desc";

  $myres=mysql_query($myq1) or die("Error");
  $name_family_sender="";
  if(mysql_num_rows($myres) > 0)
  {
     $myrf=mysql_fetch_array($myres);
      $vaziat_hozor=$myrf["vaziat_hozor"];
	  if(strcmp($vaziat_hozor,"1")==0)
	     $vaziat_hozor="حاضر";
	  if(strcmp($vaziat_hozor,"2")==0)
	     $vaziat_hozor="مرخصي ساعتي";
	  if(strcmp($vaziat_hozor,"3")==0)
	     $vaziat_hozor="مرخصي ";
		 
     $name_family_sender=$name_family_sender."<br>".$hand."&nbsp;".$myrf["karshenas_name"]."&nbsp;".$myrf["karshenas_family"]."&nbsp;<br>".$myrf["mobile"]."<br>".$vaziat_hozor."<br>";
     
  }
  else
  {
  	 $name_family_sender="نامعلوم";
  }
  
  
      $query="select * from tarh where cod_tarh='$cod_tarh'";
   $rs34=mysql_query($query) or die("error 6677");
   $rf54=mysql_fetch_array($rs34);
   $user_email=$rf54["creator"];
   
   $query11="select * from user_login,darajeelmi where user_login.darajeelmi=darajeelmi.darajeelmi and user_login.email='$user_email'";
   
     $result11=mysql_query($query11) or die("error 6677");
     $rf45=mysql_fetch_array($result11);
 
  
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/archive.jpg\" alt=\"archive\" ></a></td>";
 
  if(strcmp($position_tarh_code,'24')==0 && strcmp($rf45["need_moshavereh"],'1')==0)
  {
  	if(strcmp($submit_moshaver_amar,'0')==0)
	  $str_code="<br>"."تاييد مشاور آمار ندارد"."($moshaver_amar_name) <br> ";
	else
	  $str_code="<br>"."تاييد مشاور آمار دارد"."<br> ";   
	
   if(strcmp($submit_moshaver_tarrah,'0')==0)
	  $str_code=$str_code."<br>"."تاييد مشاور طراحي ندارد"."($moshaver_tarrah_name) <br> ";
	else
	  $str_code=$str_code."<br>"."تاييد مشاور طراحي دارد"." <br> ";     
  }  
  else
    $str_code=""; 
    
    
    
    
    
    
    
 // echo "<td  dir='rtl' bgcolor=$color align=\"center\" class=\"tahoma1\">$str_code ".$position_tarh["$position_tarh_code"]."</td>";
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$name_family_sender</td>";
  
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$modir_payanname_name</td>";
  
  $accepttarh=$row_fetched["accepttarh"];
  if($accepttarh=="1")
  	$accept="تاييديه استاد راهنما";
  if($accepttarh=="0")
  	$accept="منتظر تاييد استاد راهنما";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$accept</td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";


//  if(  $editable &&  strcmp($row_fetched["finished"],"0")==0)
 //   echo  "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border='0'  src=\"image/archive.jpg\"   alt=\"Archive\" ></a></td>";
 // else
 //   echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/archive.jpg\"   alt=\"Archive\" ></td>";    
        
  if(!($tarh_select==3 && $confirm_daneshkade_title==0)) 
  {
    if(  $editable &&  strcmp($row_fetched["finished"],"0")==0)
      echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
    else
      echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"unlock_request.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/unlock.gif\" alt=\"Unlock Request\" ><a></td>";
  }
  else
       echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_tarh_confirm_name.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a><br>منتظر تاييد نام</td>";  
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_list.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"$new_msg\"></a></td>";
  
  
  
   
 
 
 
  $mytarh_type = $row_fetched["status"];
 
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
//  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dirl='rtl'>".$mystatus."</td>";
// echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$tarh_select_desc."</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$farsistartdate."</a></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$daneshkade</td>";
    
  //echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_english"]."</a></td>";
  echo "<td   bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  
  $cod_tarh=$row_fetched["cod_tarh"];


  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";

  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".در حال حاضر طرح تحقيقاتي ارسال شده اي از شما وجود ندارد","red");
}
echo "</form>";

//echo  "<iframe cols=\"150,300\" name=\"main\" src=\"informatics.phtml?admin=$admin&seed=$seed\">";

footer_forms($admin,$seed);
?>

