<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";
 
if(isset($action))
{
  if (strcmp($action,"sabt")==0)
  {
  
  
  
	 $file_cnt=0;
     $dir_name="../reports/".$cod_tarh;
     if ($dir = @opendir($dir_name))
     {
     
     $mydir = dir($dir_name);
     //while(($file = $mydir->read()) !== false)
     while($file = $mydir->read())
	   if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0) )
	    $file_cnt++;
      closedir($dir);
     
     }

  
  
  
  
  
  
  
 
       $status_upload=upload_file("../reports",$cod_tarh,"");
       if(!strcmp($status_upload,"10") == 0 )
	     $status="upload_error";
	   else 
	   {
	   	$fupload_name=$_FILES["fupload"]["name"];
	   	$send_date=date("Y-m-d");
	   	$query="insert into  marhale_report set filename='$fupload_name',marhale='$marhale',cod_tarh='$cod_tarh',comments='$comments',send_date='$send_date'";
	   	 
	   	$r_update=mysql_query($query) or die("Error");
	   	
	   }
	 
      
	  $query="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and  cod_tarh='$cod_tarh' and group_karshenasan.karshenas_type='1'";
      $result123=mysql_query($query) or die("Error 120000");
	  while($rf=mysql_fetch_array($result123)){
	  $sms_box=$rf["sms_box"]; 
	  $startdate =$send_date;
      $startyear = substr($startdate,0,4);
      $startmon = substr($startdate,5,2);
      $startday = substr($startdate,8,2);
      $send_date=hijricalender( $startyear , $startmon , $startday ); 
	 
	  $query="insert into input_sms set sms_from='ADMIN' ,sms_to='$sms_box' , sms_text='File Gozaresh miyanie marboot be tarh $cod_tarh  dar tarikh   $send_date  ersal shod'";
	  $result=mysql_query($query) or die("Error 120000");
       }    
  }
  
   if (strcmp($action,"delete_file")==0)
  {
  	$query="select * from marhale_report where id='$delete_id'";
  	$result=mysql_query($query);
  	
  	$row_fetched=mysql_fetch_array($result);
  	$delete_filename=$row_fetched["filename"];
  	$del_file="../reports/".$cod_tarh;
    delete_file($del_file,"",$delete_filename);
    $query="delete  from marhale_report where id='$delete_id'";
  	$result=mysql_query($query);
    
  }
}

?>

<? echo "<form name=\"mojri_tarh\" method=\"post\" enctype=\"multipart/form-data\" action=\"$PHP_SELF?action=sabt&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&marhale=$marhale\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=left width="50"   height=19>    
    <a style="text-decoration:none" href="send_report.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="450" height=19 align="right" class="tahoma1">ارسال گزارش اين مرحله
      </TD>
  </TR>
    <TR>
     
      <TD align=middle colspan='2' width="500" height=19 align="right" class="tahoma1">توجه داشته باشيد گزارش شما ابتدا بايد به تاييد ساب ادمين مربوطه در دانشكده يا مركز شما برسد بنا بر اين با ايشان تماس حاصل فرماييد
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>



<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">

<?


 if (strcmp($status_upload,"-5") == 0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين فايلي قبلا بارگذاري شده</td>";
    echo "</tr>";
  }
 echo "<tr>";
    echo "<td align=\"center\" dir='rtl' class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">حداکثر حجم فايل 2 مگابايت مي باشد. نام فايل را انگليسي و بدون فاصله وارد کنيد<br> فايل ارسالي بايد به فرمت Word يا PDF باشد.صرفا از فونت زر استفاده کنيد </td>";
    echo "</tr>";
    
    
 


if (strcmp($status,"exceed_upload") == 0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">حداکثر 3 عدد فايل همراه قابل بارگذاري است</td>";
    echo "</tr>";
  }




if (strcmp($status_upload,"-2") == 0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">قابل بارگذاري هستند Ms word و Adobe Acrobat  تنها فايلهاي</td>";
    echo "</tr>";
  }

 
?>
 <tr>
     <td width="100" align="right"><input type="text" name="comments" class="edit-user" dir=RTL    ></td>
    <td width="400" class="tahoma1" valign="top" >توضيح
  </tr>

  <tr>
     <td width="100" align="right"><input type="file" name="fupload" class="edit-user"></td>
    <td width="400" class="tahoma1" valign="top" >نام فايل
  </tr>



  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>



  <?
  $query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
   
  $result=mysql_query($query) or die("Error");
   
     $mycount=0;
    if(mysql_num_rows($result) > 0)
    {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
       echo "<tr>";      
      echo "<td width=\"20%\" colspan='4' align=\"center\"  class=\"tahoma1\"><b>با کليک روي نام فايل محتويات آن قابل مشاهده مي باشد</b></td>";
      echo "</tr>";
      
      echo "<tr>";
      echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">حذف</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">توضيحات</td>";
      echo "</tr>";

     //echo $dir_name;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$id=$row_fetched["id"];
     	
     	   $myq="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='$marhale' and submitted='1'";
     $res=mysql_query($myq) or die("Error");
     if(mysql_num_rows($res)>0)
       $level_submitted='1';
     else 
       $level_submitted='0';  
     	
     	
	      echo "<tr>";
	     if($level_submitted==0)
             echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=send_marhale_report.phtml&admin=$admin&seed=$seed&action=delete_file&marhale=$marhale&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         else 
             echo "<td ><p align=\"center\" class='tahoma1'> غير قابل حذف</td>";    
         echo "<td align=\"center\"  class=\"tahoma1\"><a target=\"_blank\" href=\"../reports/$cod_tarh/$file".$row_fetched["filename"]."\">".$row_fetched["filename"]."</a></td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["send_date"]."</td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["comments"]."</td>";
         echo "</tr>";
	   
     }
         echo "<tr>";
	     echo "<td width=\"20%\" colspan='4' align=\"center\"  class=\"tahoma1\">در صورتي که امکان حذف گزارشي از طرح وجود نداشته باشد ، به اين معني است که مبلغ اين مرحله تاييد شده است</td>";
         echo "</tr>";
      echo "</table>";
	 }
     
    
     

  

 footer_forms($admin,$seed);
?>



 