<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

 function checkaddslashes($str){
    $str2 = str_replace("\'", "*****", $str);
    if(strpos($str2,"'")!== false)
        return str_replace('*****', "\'", addslashes($str2));
    else
        return $str;
}

$year_date = date("Y") - 1921 ;
$today=str_replace("/","-",today());




echo "<br>";


if(isset($action))
{
  if (strcmp($action,"add_tarh")==0)
  {

    if( (strlen(trim($maghale_title)) > 0)  && (strlen(trim($journal_name)) > 0)  &&   strlen(trim($issn)) > 0 && strlen(trim($year_publish_shamsi)) > 2 && strlen(trim($year_publish_milady)) > 2 &&   strcmp($indexing,"-1")!=0 &&   strcmp($maghale_type,"-1")!= 0)
    {
		
		$maghale_title=addslashes($maghale_title);

	    
      $query="select * from maghale where maghale_title =\"$maghale_title\" and creator=\"$admin\" and cod_tarh='$cod_tarh'";
	//  echo $query;
      $result=mysql_query($query) or die("Error in selecting data from tarh  12");

      if ( mysql_num_rows($result) <= 0 )
      {	
		$query="insert into maghale  set  creator='$admin',cod_tarh='$cod_tarh',maghale_title='$maghale_title',journal_name='$journal_name',issn='$issn',outer_level='$outer_level',Affiliation='$affiliation',year_publish_shamsi='$year_publish_shamsi',year_publish_milady='$year_publish_milady',indexing='$indexing',maghale_type='$maghale_type'";
		$result=mysql_query($query) or die("Error in selecting data from tarh  11");
		
		$myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas  and (group_karshenasan.username='rahmani' or group_karshenasan.creator='rahmani') order by id desc";
//echo $myq1;
  			$myres=mysql_query($myq1) or die("Error");
			$rf=mysql_fetch_array($myres);
			$sms_box=$rf["sms_box"]; 
			//echo $sms_box;
			$startdate =date("Y-m-d");
		    $startyear = substr($startdate,0,4);
		    $startmon = substr($startdate,5,2);
		    $startday = substr($startdate,8,2);
		    $send_date=hijricalender( $startyear , $startmon , $startday ); 
			 
			$query="insert into input_sms set sms_from='Mojri' ,sms_to='$sms_box' , sms_text='etelaate maghaleye tarh ba code $cod_tarh dar tarikhe $send_date dar mohit mojri sabt shod.'";
			//  echo $query;
			$result=mysql_query($query) or die("Error 120000 er");
		
		$query="select * from maghale where  maghale_title =\"$maghale_title\" and creator=\"$admin\" and cod_tarh='$cod_tarh'";
		$result=mysql_query($query) or die("Error in selecting data from tarh  11");	
		$row_fetched=mysql_fetch_array($result);
		$maghale_id=$row_fetched["maghale_id"];
     ?>
           <script language="javascript">
           window.location="<? echo "upload_maghale.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&maghale_id=$maghale_id";  ?>";
           </script>
           <? 

         }
         else
          $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }
  
 if (strcmp($action,"delete")==0)
 {
    $query="delete from maghale where maghale_id = \"$delete_id\" and cod_tarh=\"$cod_tarh\" ";
    
    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
    
    $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas  and (group_karshenasan.username='rahmani' or group_karshenasan.creator='rahmani') order by id desc";
//echo $myq1;
  			$myres=mysql_query($myq1) or die("Error");
			$rf=mysql_fetch_array($myres);
			$sms_box=$rf["sms_box"]; 
			//echo $sms_box;
			$startdate =date("Y-m-d");
		    $startyear = substr($startdate,0,4);
		    $startmon = substr($startdate,5,2);
		    $startday = substr($startdate,8,2);
		    $send_date=hijricalender( $startyear , $startmon , $startday ); 
			 
			$query="insert into input_sms set sms_from='Mojri' ,sms_to='$sms_box' , sms_text='etelaate maghaleye tarh ba code $cod_tarh dar tarikhe $send_date az mohit mojri hazf shod.'";
			//  echo $query;
			$result=mysql_query($query) or die("Error 120000 er");
    
    $action="حذف مقاله طرح از طرح"."<br>".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
        
      delete_file("../maghale",$delete_id,"");
     $action="ضميمه حذف شد"."<br>".$delete_id;
           set_log($action,$admin,date("Y-m-d, g:i a"));

 }
if (strcmp($action,"delete")==0)
 {
    $query="delete from maghale where maghale_id = \"$delete_id\" and cod_tarh=\"$cod_tarh\" ";
    
    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
    $action="حذف مقاله طرح از طرح"."<br>".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
        
      delete_file("../maghale",$delete_id,"");
     $action="ضميمه حذف شد"."<br>".$delete_id;
           set_log($action,$admin,date("Y-m-d, g:i a"));

 }
 if (strcmp($action,"edit")==0)
  {
  	$query="select * from maghale  where  maghale_id='$maghale_id'";
  	
	$result=mysql_query($query) or die("Error in selecting data from mojri");
  	if(mysql_num_rows($result) > 0)
  	{
  	   $row_fetched=mysql_fetch_array($result);	
  	   $maghale_title=$row_fetched["maghale_title"];	
  	   $journal_name=$row_fetched["journal_name"];
  	   $issn=$row_fetched["issn"];
  	   $outer_level=$row_fetched["outer_level"];
  	   $affiliation=$row_fetched["Affiliation"];
  	   $year_publish_shamsi=$row_fetched["year_publish_shamsi"];
  	   $year_publish_milady=$row_fetched["year_publish_milady"];
  	   $indexing=$row_fetched["indexing"];
  	   $maghale_type=$row_fetched["maghale_type"];
  
  	}
  	else
  	{  	   	
  	  	
  	   $maghale_title="";	
  	   $journal_name="";
  	   $issn="";
  	   $outer_level="";
  	   $affiliation="";
  	   $year_publish_shamsi="";
  	   $year_publish_milady="";
  	   $indexing="";
  	   $maghale_type="";
    	}
  	
  }
  
if (strcmp($action,"edit_second")==0)
  {

    if( (strlen(trim($maghale_title)) > 0)  && (strlen(trim($journal_name)) > 0)  &&   strlen(trim($issn)) > 0 && strlen(trim($year_publish_shamsi)) > 2 && strlen(trim($year_publish_milady)) > 2 &&   strcmp($indexing,"-1")!=0 &&   strcmp($maghale_type,"-1")!= 0)
    {
		
		$maghale_title=addslashes($maghale_title);

		$query="update  maghale  set  maghale_title='$maghale_title',journal_name='$journal_name',issn='$issn',outer_level='$outer_level',Affiliation='$affiliation',year_publish_shamsi='$year_publish_shamsi',year_publish_milady='$year_publish_milady',indexing='$indexing',maghale_type='$maghale_type' where maghale_id='$maghale_id' and cod_tarh='$cod_tarh'";
		$result=mysql_query($query) or die("Error in selecting data from tarh  11");
		
			
  	   $maghale_title="";	
  	   $journal_name="";
  	   $issn="";
  	   $outer_level="";
  	   $affiliation="";
  	   $year_publish_shamsi="";
  	   $year_publish_milady="";
  	   $indexing="";
  	   $maghale_type="";
        
    }
    else
      $status="entry_error";
  }
}

?>

<?
if (strcmp($action,"edit")==0)
  {
  	echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=edit_second&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&maghale_id=$maghale_id\">"; 
  }
  else {
  	echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=add_tarh&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
  }?>

 <TABLE cellSpacing=0 width="500"  cellPadding=0 border=0>
  <TBODY>
    <TR>
     
      <TD align=right width="100%" class='tahoma1' dir='rtl'  height=19>مقاله
      </TD>
  </TR>
  </TBODY>
  </TABLE>
 


<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">.مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">.مقاله با اين عنوان وجود دارد</td>";
    echo "</tr>";
  }
?>
  <tr>
    <td width="350" align="right"><input type="text" name="maghale_title" size="20"  class="edit-user" dir=RTL value="<?php echo $maghale_title;?>"   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span> عنوان مقاله</td>
  </tr>
  
   <tr>
    <td width="350" align="right"><input type="text" name="journal_name"  value="<?php echo $journal_name;?>" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام مجله</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="issn" size="20"  value="<?php echo $issn;?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>ISSN</td>
  </tr>
  <?php if(strcmp($outer_level,"1")==0){
  	$selected1="checked";
  	
  }
  else
   	$selected="checked";
  ?>
  <tr>
    <td width="350" class="tahoma1" align="right">اول يا مسئول<input type="radio" name="outer_level" value="1" <?php echo $selected1; ?>  >ساير<input type="radio" name="outer_level" value="0" <?php echo $selected; ?>  class="tahoma1" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>جايگاه نويسنده </td>
  </tr> 
  
  <?php
	$selected="";
	$selected1="";
  if(strcmp($affiliation,"0")==0){
  	$selected1="checked";
  	
  }
  else
   	$selected="checked";
  ?>
<tr>
    <td width="350" class="tahoma1" align="right">دارد<input type="radio" name="affiliation" value="0" <?php echo $selected1; ?>   >ندارد<input type="radio" name="affiliation" value="1"  <?php echo $selected; ?>   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>وضعيت مقاله از نظر وابستگي به دانشگاه علوم پزشکي تهران</td>
  </tr> 

<tr>
    <td width="350" align="right"><select size="1" name="year_publish_shamsi" class="edit-user" dir="rtl">
    <option value="0">انتخاب کنيد</option>
    <option <? if($year_publish_shamsi==1388) echo "selected"; ?> value="1388">1388</option>
    <option <? if($year_publish_shamsi==1389) echo "selected"; ?> value="1389">1389</option>
    <option <? if($year_publish_shamsi==1390) echo "selected"; ?> value="1390">1390</option>
    <option <? if($year_publish_shamsi==1391) echo "selected"; ?> value="1391">1391</option>
    <option <? if($year_publish_shamsi==1392) echo "selected"; ?> value="1392">1392</option>
    <option <? if($year_publish_shamsi==1393) echo "selected"; ?> value="1393">1393</option>
    <option <? if($year_publish_shamsi==1394) echo "selected"; ?> value="1394">1394</option>
    <option <? if($year_publish_shamsi==1395) echo "selected"; ?> value="1395">1395</option>
    <option <? if($year_publish_shamsi==1396) echo "selected"; ?> value="1396">1396</option>
    <option <? if($year_publish_shamsi==1397) echo "selected"; ?>value="1397">1397</option>
    <option <? if($year_publish_shamsi==1398) echo "selected"; ?> value="1398">1398</option>

    
  </select></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>سال شمسي انتشار</td>
  </tr>
  <tr>
    <td width="350" align="right"><select size="1" name="year_publish_milady" class="edit-user" dir="rtl">
    <option value="0">انتخاب کنيد</option>
    <option <? if($year_publish_milady==2010) echo "selected"; ?> value="2010">2010</option>
    <option <? if($year_publish_milady==2011) echo "selected"; ?> value="2011">2011</option>
    <option <? if($year_publish_milady==2012) echo "selected"; ?> value="2012">2012</option>
    <option <? if($year_publish_milady==2013) echo "selected"; ?> value="2013">2013</option>
    <option <? if($year_publish_milady==2014) echo "selected"; ?> value="2014">2014</option>
    <option <? if($year_publish_milady==2015) echo "selected"; ?> value="2015">2015</option>
    <option <? if($year_publish_milady==2016) echo "selected"; ?> value="2016">2016</option>
    <option <? if($year_publish_milady==2017) echo "selected"; ?> value="2017">2017</option>
    <option <? if($year_publish_milady==2018) echo "selected"; ?> value="2018">2018</option>
    <option <? if($year_publish_milady==2019) echo "selected"; ?> value="2019">2019</option>
    <option <? if($year_publish_milady==2020) echo "selected"; ?> value="2020">2020</option>

    
  </select></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>سال ميلادي انتشار</td>
  </tr>
 <tr>
  <?
    $query="select * from maghale_indexing order by indexing_desc  ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    $groupcount = mysql_num_rows($qresult);
  ?>
  
 
    <td width="350" align="right"><select size="1"   name="indexing" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
    	if(strcmp($indexing,$row_fetched["index_id"])==0)
    		$selected="selected";
    	else
    		$selected="";
         echo "<option $selected value=\"".$row_fetched["index_id"]."\" class=\"tahoma1\">".$row_fetched["indexing_desc"]."</option>";
    }
    ?>
    </select>
	 
	</td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>indexing</td>
  </tr>
  
  
   <tr>
  <?
    $query="select * from maghale_type order by maghale_type_desc  ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    $groupcount = mysql_num_rows($qresult);
  ?>
    <td width="350" align="right"><select size="1"   name="maghale_type" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
    	if(strcmp($maghale_type,$row_fetched["maghale_type_id"])==0)
    		$selected="selected";
    	else
    		$selected="";
         echo "<option $selected value=\"".$row_fetched["maghale_type_id"]."\" class=\"tahoma1\">".$row_fetched["maghale_type_desc"]."</option>";
    }
    ?>
	</td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نوع مقاله</td>
  </tr>
 

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
  

  
</table>





</form>


<?
$query="select * from maghale where cod_tarh='$cod_tarh'";
   
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"700\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"0\" width=\"700\"  cellspacing=\"0\" cellpadding=\"0\" >"; 
	 echo "<tr>";
      echo "<td width=\"100%\"  colspan='14'   height=\"20\"><p align=\"center\" class=\"tahoma1\">مقالات منتج از اين طرح </p></td>";
    echo "</tr>"; 
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"60\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "<td width=\"30\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حذف</p></td>";
    echo "<td width=\"30\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ويرايش</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ضمائم</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نوع مقاله</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">indexing</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">سال ميلادي انتشار</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">سال شمسي انتشار</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">وابستگي</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">جايگاه</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">issn</p></td>";
    echo "<td width=\"63\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام مجله</p></td>";
    echo "<td width=\"66\" background=\"image/top-top.gif\" height=\"60\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">عنوان مقاله</p></td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height\"60\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
   	$outer_level=$myrow_fetched["outer_level"];
   	if(strcmp($outer_level,"0")==0)
   		$outer_level="اول يا مسئول";
   	else if(strcmp($outer_level,"1")==0)
   		$outer_level="ساير";
   		
   	$affiliation=$myrow_fetched["Affiliation"];
   	if(strcmp($affiliation,"0")==0)
   		$affiliation="ندارد";
   	else if(strcmp($affiliation,"1")==0)
   		$affiliation="دارد";
   
   	$indexing=$myrow_fetched["indexing"];
   	$q="select * from maghale_indexing where index_id='$indexing'";
   	$re=mysql_query($q) or die("Error in selecting data from karshenas elmi");
   	$my=mysql_fetch_array($re);
   	$indexing=$my["indexing_desc"];
   	
   	$maghale_type=$myrow_fetched["maghale_type"];
   	$q="select * from maghale_type where maghale_type_id='$maghale_type'";
   	$re=mysql_query($q) or die("Error in selecting data from karshenas elmi");
   	$my=mysql_fetch_array($re);
   	$maghale_type=$my["maghale_type_desc"];
   	
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    echo "<tr bgcolor=\"$color\">";
    echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\">&nbsp;</td>";
    $maghale_id = $myrow_fetched["maghale_id"];
    //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"30\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=send_maghale.phtml&admin=$admin&seed=$seed&action=delete&cod_tarh=".$cod_tarh."&delete_id=".$myrow_fetched["maghale_id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"30\"><p align=\"center\"><a style=\"text-decoration:none\" href=\"send_maghale.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&maghale_id=$maghale_id&action=edit\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"upload_maghale.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&maghale_id=$maghale_id\">"."فايل مقاله"."</a></p></td>";
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$maghale_type."</p></td>"; 
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$indexing."</p></td>"; 
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["year_publish_milady"]."</p></td>"; 
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["year_publish_shamsi"]."</p></td>";  
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$affiliation."</p></td>";  
    echo "<td class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">".$outer_level."</p></td>";
	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["issn"]."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["journal_name"]."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["maghale_title"]."</p></td>";
    echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";
   }
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "<td width=\"30\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"30\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";    
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"63\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"66\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";

   echo "</table>";

  }


  footer_forms($admin,$seed);?>