<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>
<script language="Javascript1.2"><!-- // load htmlarea
_editor_url = "";                     // URL to htmlarea files
var win_ie_ver = parseFloat(navigator.appVersion.split("MSIE")[1]);
if (navigator.userAgent.indexOf('Mac')        >= 0) { win_ie_ver = 0; }
if (navigator.userAgent.indexOf('Windows CE') >= 0) { win_ie_ver = 0; }
if (navigator.userAgent.indexOf('Opera')      >= 0) { win_ie_ver = 0; }
if (win_ie_ver >= 5.5) {
 document.write('<scr' + 'ipt src="' +_editor_url+ 'editor.js"');
 document.write(' language="Javascript1.2"></scr' + 'ipt>');
} else { document.write('<scr'+'ipt>function editor_generate() { return false; }</scr'+'ipt>'); }
// --></script>

<?
echo "<br>";

if(isset($action))
{
  if (strcmp($action,"finish")==0)
  {
   
      $query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";

      $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
      
      if ( mysql_num_rows($result) == 1)
      {
      	  if ( strlen(trim($unlock_reason)) > 0)
      {
	
		$query="update tarh  set unlock_reason='$unlock_reason',edit_request=\"1\" where  cod_tarh='$cod_tarh' and version='-1'";
	
        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
        $action="درخواسا ويزايش طرح"."<br>".$tarh_name;
   
        set_log($action,$admin,date("Y-m-d, g:i a"));
		message_show(".درخواست ويرايش ارسال شد","green");
		footer_forms($admin,$seed);
		exit();
      }		
      }
    
  }
}

  $query="select * from tarh where cod_tarh='$cod_tarh' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $zarorat_ejra=$row_fetched["zarorat_ejra"];
  $bayan_masale=$row_fetched["bayan_masale"];
  $bayan_masale=$row_fetched["bayan_masale"];
  $taarif_vajeh=$row_fetched["taarif_vajeh"];
  $hadaf_faree=$row_fetched["hadaf_faree"];
  $hadaf_kolli=$row_fetched["hadaf_kolli"];
  $hadaf_jozii=$row_fetched["hadaf_jozii"];
  $hadaf_karbordi=$row_fetched["hadaf_karbordi"];
  $soalat_pajoheshi=$row_fetched["soalat_pajoheshi"];
  $farziatt=$row_fetched["farziatt"];
  $fehrest_manabea=$row_fetched["fehrest_manabea"];
  $query="select * from user_login where email='$admin' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $payan_name = $row_fetched["payan_name"];
  

?>


<?  echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=finish&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<TABLE cellSpacing=0 cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center width="500" class="tahoma1"  height=19 bgcolor="#EEE7F8">
      <?
      if (strcmp($payan_name,"0")==0)
	   echo ""."عنوان طرح   : ".$tarh_name ;
	   else 
	   echo ""."عنوان پايان نامه   : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>




  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
  
  
    <TR>
    <TD align=middle width="360"   height=19>
      </TD>
      <TD align=middle width="140"  background="image/edit_request.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8" cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">طرحي با اين عنوان توسط شما تعريف شده</td>";
    echo "</tr>";
  }
?>

  <tr>
   
    <td width="100%" class="tahoma1" valign="top" align="right"><span class="star-message">.درخواست شما براي ويرايش مجدد سيستم به مدير سيستم ارسال مي شود و پس از تاييد ايشان طرح براي ويرايش مجدد فعال مي شود</span></td>
  </tr>

<tr>
    <td width="70%" align="right"><textarea   rows="7"  name="unlock_reason"  class="edit-user"  dir=RTL   ><? echo $zarorat; ?></textarea></td>
    <td width="30%" class="tahoma1" valign="top"><span class="star-message">*</span>دليل درخواست ويرايش</td>
  </tr>
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ارسال" name="B1" class="but-small"></td>
  </tr>
</table>

</form>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="sabt_tarh_second.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
  </tr>
</table>
<?
  footer_forms($admin,$seed);
 ?>




