<?php @session_start();?>
<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>صفحه بدون محتوا</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <script src="../assets/plugins/pace/pace.min.js" type="text/javascript"></script>
    <link href="../assets/plugins/pace/themes/pace-theme-flash-rtl.css" rel="stylesheet" type="text/css" />
    <link href="../assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="../assets/plugins/bootstrap/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="../assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link href="../assets/css/style-metronic-rtl.css" rel="stylesheet" type="text/css" />
    <link href="../assets/css/style-rtl.css" rel="stylesheet" type="text/css" />
    <link href="../assets/css/style-responsive-rtl.css" rel="stylesheet" type="text/css" />
    <link href="../assets/css/plugins-rtl.css" rel="stylesheet" type="text/css" />
    <link href="../assets/css/themes/blue-rtl.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="../assets/css/custom-rtl.css" rel="stylesheet" type="text/css" />
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
    <!-- BEGIN HEADER -->
    <div class="header navbar navbar-fixed-top">
        <!-- BEGIN TOP NAVIGATION BAR -->
        <div class="header-inner">
            <!-- BEGIN LOGO -->
            <a class="navbar-brand" href="index.html">
                <img src="../assets/img/logo.png" alt="logo" class="img-responsive" />
            </a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <img src="../assets/img/menu-toggler.png" alt="" />
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN NOTIFICATION DROPDOWN -->
                <li class="dropdown" id="header_notification_bar">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="fa fa-warning"></i>
                        <span class="badge">
                            6
                        </span>
                    </a>
                    <ul class="dropdown-menu extended notification">
                        <li>
                            <p>
                                شما 14 اعلان جديد داريد
                            </p>
                        </li>
                        <li>
                            <ul class="dropdown-menu-list scroller" style="height: 250px;">
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-success">
                                            <i class="fa fa-plus"></i>
                                        </span>
                                        عضويت کاربر جديد
                                        <span class="time">
                                            هم اکنون
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-danger">
                                            <i class="fa fa-bolt"></i>
                                        </span>
                                        قطعي در سرور شماره 2
                                        <span class="time">
                                            15 دقيقه قبل
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-warning">
                                            <i class="fa fa-bell-o"></i>
                                        </span>
                                        زمانبندي طرح وارد نشده است
                                        <span class="time">
                                            22 دقيقه قبل
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-info">
                                            <i class="fa fa-bullhorn"></i>
                                        </span>
                                        خطا در نرم افزار
                                        <span class="time">
                                            40 دقيقه قبل
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-danger">
                                            <i class="fa fa-bolt"></i>
                                        </span>
                                        طرح هاي ناقص
                                        <span class="time">
                                            2 ساعت قبل
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-danger">
                                            <i class="fa fa-bolt"></i>
                                        </span>
                                        2 کاربر مدود شدند
                                        <span class="time">
                                            5 ساعت قبل
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-warning">
                                            <i class="fa fa-bell-o"></i>
                                        </span>
                                        خطا در اجرا
                                        <span class="time">
                                            45 دقيقه
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="label label-icon label-info">
                                            <i class="fa fa-bullhorn"></i>
                                        </span>
                                        خطاي سيستمي
                                        <span class="time">
                                            55 دقيقه قبل
                                        </span>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="external">
                            <a href="#">
                                مشاهده تمامي اعلان ها <i class="m-icon-swapright"></i>
                            </a>
                        </li>
                    </ul>
                </li>
				<?php 
				header("Content-type: image/jpeg");

				
				$query="select * from user_login where email='$admin'";
				$result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
				$row_fetched = mysql_fetch_array($result);
				$name=$row_fetched["name"];
				$family=$row_fetched["family"];
				$picture=$row_fetched["picture"];
				?>
                <li class="dropdown user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <?php echo '<img with="29px" height="32px" src="data:image/jpeg;base64,'.base64_encode( $picture).'"/>';?>
                        
                        <span class="username">
                       <?php   echo $name." ".$family;?>
                        </span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="extra_profile.html">
                                <i class="fa fa-user"></i> پروفايل کاربري
                            </a>
                        </li>
                        <li>
                            <a href="page_calendar.html">
                                <i class="fa fa-calendar"></i> تقويم من
                            </a>
                        </li>
                        <li>
                            <a href="inbox.html">
                                <i class="fa fa-envelope"></i> صندوق من
                                <span class="badge badge-danger">
                                    3
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-tasks"></i> وظايف من
                                <span class="badge badge-success">
                                    7
                                </span>
                            </a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="javascript:;" id="trigger_fullscreen">
                                <i class="fa fa-arrows"></i> اجراي تمام صفحه
                            </a>
                        </li>
                        <li>
                            <a href="extra_lock.html">
                                <i class="fa fa-lock"></i> Lock Screen
                            </a>
                        </li>
                        <li>
                            <a href="logout.phtml">
                                <i class="fa fa-key"></i> خروج
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END TOP NAVIGATION BAR -->
    </div>
    <!-- END HEADER -->
     <div class="clearfix">
    </div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">