<?php
$domain_name="research.tums.ac.ir";
$url_address="http://research.tums.ac.ir";
//$mailserver_host="127.0.0.1";
$mailserver_host="sina.tums.ac.ir";

//$email_from="admin@research.tums.ac.ir";
$email_from="pajoheshyar@sina.tums.ac.ir";
$email_from_name="Admin of Research";
$email_contact_email="mohsen.niazi@gmail.com";
$email_contact_email1="rezaii@sina.tums.ac.ir";
$email_contact_email2="pajoheshyar@sina.tums.ac.ir";
$email_contact_name="Mohsen Niazi";
$email_contact_name1="Dr Rezaii";
$email_contact_name2="Dr Kabiri";
//$email_username="mail_server_admin";
$email_username="pajoheshyar";
//$email_password="pd42ssm";
$email_password="pajohesh86";
$smtpauth="false";
?>
