
<?
include("include/styles.phtml");
include("include/include.phtml");
header_forms();


include("include/styles.phtml");
include("include/vars.inc.phtml");
 
 
 
 if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(!isset($ascdesc))
  $ascdesc="desc";

 ?>
 
  <?
   echo "<br>";

     echo "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\"  width=\"80%\" >";
	 echo "<tr>";
	        echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\" dir='rtl'><font color='green'><b>جهت ورود به محيط کاربري خود روي گزينه ورود اعضا کليک کنيد </b></font></td> ";
	 echo "</tr>";
 
      echo "</table>";
 echo "<br>";


   $query="select id from  news  order by id desc";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   
   $reccount = mysql_num_rows($result);

   $query="select * from  news  order by id desc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;;

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");

   
  pubshowpages("news.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage ,$myascdescpub,"80%",'white');
   
   if(mysql_num_rows($result) > 0)
   {

          echo "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\"  width=\"80%\" >";


     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
		      echo "<tr>";

         $id=$row_fetched["id"];
	     $startdate = $row_fetched["news_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
       //echo "<td align=\"center\" class=\"tahoma1\"><img src=\"image/button_drop.png\" border=0 alt=\"Delete\"></td>";
        echo "<td width=\"5%\"  align=\"right\" class=\"tahoma1\" dir='rtl'><font color='green'><img border='0' src='images\\marker_img.gif'> ( $farsistartdate) ".$row_fetched["title"]."</font></td> ";
	 echo "</tr>";
	echo "<tr>"; 
	  echo "<td width=\"26%\"  align=\"right\"  class=\"tahoma1\" dir='rtl'><br>".nl2br( $row_fetched["body"])."<hr><br></td>" ;
       
      
     echo "</tr>";
	  
	   
	   
	   
 
     
     }
      echo "</table>";
    

   }
 
  ?>

 
 <?
 footer_forms();
?>
