<style>
<!--
.but-tarh-type    { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:100 }
.edit-tarh-type   { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:230 }
.tahoma1          {font-family: tahoma; font-size: 8pt}
.tahoma2          {font-family: tahoma; font-size: 11pt}
.but-small        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:80 }
.but-wide         { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:120 }
.edit-signup      { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:380 }
.edit-daneshkade  { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:230 }
.edit-small       { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:130 }
.submit-signup    { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:180 }
.error-message    {font-family: tahoma; font-size: 8pt; color=red}
.edit-user        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:330 }
.star-message     {font-family: tahoma; font-size: 8pt; color=red}
.combo             { BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; FONT-SIZE: 9pt; BORDER-LEFT: 1px solid; WIDTH: 330px; BORDER-BOTTOM: 1px solid; FONT-FAMILY: tahoma}
.combo1             { BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; FONT-SIZE: 9pt; BORDER-LEFT: 1px solid; WIDTH: 130px; BORDER-BOTTOM: 1px solid; FONT-FAMILY: tahoma}
.edit-small-1       { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:250 }
.edit-small-2       { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:150 }
.verdana1          {FONT-WEIGHT: 600; FONT-SIZE: 8pt; MARGIN: 0cm 0cm 0pt; COLOR: black; DIRECTION: ltr; LINE-HEIGHT: 100%; FONT-FAMILY: "Verdana","Tahoma","Arial"; unicode-bidi: embed; TEXT-DECORATION: none}
.verdana2          {FONT-WEIGHT: 600; FONT-SIZE: 11pt; MARGIN: 0cm 0cm 0pt; COLOR: black; DIRECTION: ltr; LINE-HEIGHT: 100%; FONT-FAMILY: "Verdana","Tahoma","Arial"; unicode-bidi: embed; TEXT-DECORATION: none}
-->
</style>
<META http-equiv=content-type content=text/html;charset=utf-8>
