<?
include("include/database-connect.phtml");
include("include/session.phtml");
require("include/mailserver-statistics.phtml");

function jalali_to_gregorian($j_y, $j_m, $j_d) 
{ 
    $g_days_in_month = array(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31); 
    $j_days_in_month = array(31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 29);
    
   

   $jy = $j_y-979; 
   $jm = $j_m-1; 
   $jd = $j_d-1; 

   $j_day_no = 365*$jy + div($jy, 33)*8 + div($jy%33+3, 4); 
   for ($i=0; $i < $jm; ++$i) 
      $j_day_no += $j_days_in_month[$i]; 

   $j_day_no += $jd; 

   $g_day_no = $j_day_no+79; 

   $gy = 1600 + 400*div($g_day_no, 146097); /* 146097 = 365*400 + 400/4 - 400/100 + 400/400 */ 
   $g_day_no = $g_day_no % 146097; 

   $leap = true; 
   if ($g_day_no >= 36525) /* 36525 = 365*100 + 100/4 */ 
   { 
      $g_day_no--; 
      $gy += 100*div($g_day_no,  36524); /* 36524 = 365*100 + 100/4 - 100/100 */ 
      $g_day_no = $g_day_no % 36524; 

      if ($g_day_no >= 365) 
         $g_day_no++; 
      else 
         $leap = false; 
   } 

   $gy += 4*div($g_day_no, 1461); /* 1461 = 365*4 + 4/4 */ 
   $g_day_no %= 1461; 

   if ($g_day_no >= 366) { 
      $leap = false; 

      $g_day_no--; 
      $gy += div($g_day_no, 365); 
      $g_day_no = $g_day_no % 365; 
   } 

   for ($i = 0; $g_day_no >= $g_days_in_month[$i] + ($i == 1 && $leap); $i++) 
      $g_day_no -= $g_days_in_month[$i] + ($i == 1 && $leap); 
   $gm = $i+1; 
   $gd = $g_day_no+1; 

   return array($gy, $gm, $gd); 
}





function check_field_value($id,$var_val)
{
  	
   
   $tok = strtok($id,",");
   while ($tok) {
    //if(strcmp($tok,$permission)==0)
	 // return 1;
	 // echo $tok."<br>";
	 $var_len=strlen($var_val);
	 if(strcmp(substr($tok,$var_len,1),"=")==0)
	 {
	   
	   if(strcmp($var_val,substr($tok,0,$var_len))==0)
	   {
	   	 $tok_len=strlen($tok);
	   	 $tok_len=$tok_len-($var_len+3);
	     $return_var=substr($tok,$var_len+2,$tok_len);
		 
		 return $return_var;
	     
	     //exit();
	   } 
	 }
      $tok = strtok(",");
   }
   
   
  
 return -1;
}
//-------------------------------------------------------

function send_mojri_sms($message)
{
  
 $username = 'olomPezeshki';
$password = 'medicalu_01';
$domain = 'magfa';

$j=0;
 
$a="";
$b="";
$c="";
//$message=iconv("windows-1256", "UTF-8",$message);
for($i=0;$i<strlen($message);$i+=131)
{
	if($i==0)
	  $a=substr($message,$i,131);
	 else 
	if($i>=131 && $i<262)
	  $b=substr($message,$i,131);
	 else 
    if($i>=262 && $i<393)
	  $c=substr($message,$i,131);
    
  //$msg1[$j]=substr($message,$i,160);
  $j++;	
}
$mymsg="";
 $query="select * from  user_login where 1";
 
 $result=mysql_query($query) or die("Error");
 $cell_number=array();
 $i=1;
 //$myudh="%05%00%03%47%02%01";

if(mysql_num_rows($result)<=0)
 return -4;

 $array_cnt=0;
 while($rf=mysql_fetch_array($result))
 {
 	$mobile=$rf["mobile"];
  	
 //	if($i <= mysql_num_rows($result))
 //	{
      //$cell_number=$cell_number."$mobile,";
      $cell_number[$array_cnt]=$mobile;
 //	}
      if(strlen($mobile)==11 && strcmp(substr($mobile,0,2),'09')==0)
      {
	    $i++;	
	    $array_cnt++;
      }
 }
//  print_r($cell_number);
// Connect ...
//$client = new soapclient('http://192.168.0.1/engine/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
$client = new soapclient('http://webservice.magfa.com/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
 
// Read error
$err = $client->getError();
if ($err) {
	echo "<h2>Constructor error</h2><pre>$err</pre>";
}

// Authentication
$client->setCredentials($username, $password, 'basic');



// echo "if(strlen($message) <131 ) {	    $result[\"enqueue1\"] = $client->call(\"enqueue\", 	array($domain,0,array(\"$a\",\"$a\"),array($cell_number),array($mytmp),array($myudh),));";
//print_r( $cell_number); 
  

 if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array("30007912")
						//UDH
		)
	);
	
/*
 if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		0,					//Message Type
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array("")
						//UDH
		)
	);
*/	
  
	
 	//echo $msg1($k-1);
 
 //echo "<br>".$k."<br>";
  
 if ($client->fault) {
	echo '<h2>Fault 1111</h2><pre>';	   
    }   
	
 
}
return 0;

//-----------------------------------------------------------------------------------

 if(strlen($message)>=131 && strlen($message)<262)
 {      
 
 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
	    array("$a","$b" ), 			//Message
		array("$cell_number","$cell_number"),			//Destination
		 array("30007912","30007912"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02"),
					//UDH
		)
	);
	
	 
  if ($client->fault) {
	echo '<h2>Fault 2222</h2><pre>';	   
    }  

 }
  //-------------------------------------------------------------------------------------
  
  if(strlen($message)>=262 && strlen($message)<393)
 { 	 
 	
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
	    array("$a","$b","$c" ), 			//Message
		array("$cell_number","$cell_number","$cell_number"),			//Destination
	    array("30007912","30007912","30007912"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02","%05%00%03%47%02%03"),
		 			//UDH
		)
	);	
 	

 if ($client->fault) {
	echo '<h2>Fault 3333</h2><pre>';	   
    }  
      
    }







 

}


//--------------------------------------------------------------------------


function dateAdd($interval,$number,$dateTime) {
        
    $dateTime = (strtotime($dateTime) != -1) ? strtotime($dateTime) : $dateTime;       
    $dateTimeArr=getdate($dateTime);
                
    $yr=$dateTimeArr[year];
    $mon=$dateTimeArr[mon];
    $day=$dateTimeArr[mday];
    $hr=$dateTimeArr[hours];
    $min=$dateTimeArr[minutes];
    $sec=$dateTimeArr[seconds];

    switch($interval) {
        case "s"://seconds
            $sec += $number; 
            break;

        case "n"://minutes
            $min += $number; 
            break;

        case "h"://hours
            $hr += $number; 
            break;

        case "d"://days
            $day += $number; 
            break;

        case "ww"://Week
            $day += ($number * 7); 
            break;

        case "m": //similar result "m" dateDiff Microsoft
            $mon += $number; 
            break;

        case "yyyy": //similar result "yyyy" dateDiff Microsoft
            $yr += $number; 
            break;

        default:
            $day += $number; 
         }       
                
        $dateTime = mktime($hr,$min,$sec,$mon,$day,$yr);
        $dateTimeArr=getdate($dateTime);
        
        $nosecmin = 0;
        $min=$dateTimeArr[minutes];
        $sec=$dateTimeArr[seconds];

        if ($hr==0){$nosecmin += 1;}
        if ($min==0){$nosecmin += 1;}
        if ($sec==0){$nosecmin += 1;}
        
        if ($nosecmin>2){     return(date("Y-m-d",$dateTime));} else {     return(date("Y-m-d G:i:s",$dateTime));}
} 


//--------------------------------------------------------------------------
function div($a,$b) {
    return (int) ($a / $b);
}

//--------------------------------------------------------------------------


function send_shora_sms($message,$cod_shora)
{
 
 $username = 'olomPezeshki';
$password = 'medicalu_01';
$domain = 'magfa';


$j=0;
 
$a="";
$b="";
$c="";
//$message=iconv("windows-1256", "UTF-8",$message);
for($i=0;$i<strlen($message);$i+=131)
{
	if($i==0)
	  $a=substr($message,$i,131);
	 else 
	if($i>=131 && $i<262)
	  $b=substr($message,$i,131);
	 else 
    if($i>=262 && $i<393)
	  $c=substr($message,$i,131);
    
  //$msg1[$j]=substr($message,$i,160);
  $j++;	
}
$mymsg="";
 $query="select * from  karshenas_shora  where cod_shora='$cod_shora'";
 $result=mysql_query($query) or die("Error");
 $cell_number=array();
 $sender=array();
 $i=1;
 //$myudh="%05%00%03%47%02%01";

if(mysql_num_rows($result)<=0)
 return -4;

 $array_cnt=0;
 while($rf=mysql_fetch_array($result))
 {
 	$mobile=$rf["mobile"];
 	if($i <= mysql_num_rows($result))
 	{
      //$cell_number=$cell_number."$mobile,";
      $cell_number[$array_cnt]=$mobile;
 	}
      
	$i++;	
	$array_cnt++;
 }
// if(strlen($shno) <= 0)
  $shno="30007912";

  $sender[0]=30007912;
// Connect ...
//$client = new soapclient('http://192.168.0.1/engine/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
$client = new soapclient('http://webservice.magfa.com/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
 
// Read error
$err = $client->getError();
if ($err) {
	echo "<h2>Constructor error</h2><pre>$err</pre>";
}

// Authentication
$client->setCredentials($username, $password, 'basic');

for($i=0;$i<=$array_cnt;$i++)
{
 
	$mobile=$cell_number[$i];
 	 
    $result["enqueue1"] = $client->call("enqueue", // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$mobile"),			//Destination
	 	array($shno)
						//UDH
		)
	);
    
     
}
return 0;

// echo "if(strlen($message) <131 ) {	    $result[\"enqueue1\"] = $client->call(\"enqueue\", 	array($domain,0,array(\"$a\",\"$a\"),array($cell_number),array($mytmp),array($myudh),));";
//print_r( $cell_number); 
   if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array($sender)
						//UDH
		)
	);
	/*
 if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
    	array("$a"),//Message						
		array("$cell_number"),			//Destination
	 	array("30007912")
						//UDH
		)
	);
  */
	
 	//echo $msg1($k-1);
 
 //echo "<br>".$k."<br>";

 if ($client->fault) {
	echo '<h2>Fault 1111</h2><pre>';	   
    }   
	
 
}
return 0;
}

//-----------------------------------------------------------------------------------
function send_group_sms($message,$cell_numbers,$shno)
{
$username = 'olomPezeshki';
$password = 'medicalu_01';
$domain = 'magfa';



$j=0;
 
$a="";
$b="";
$c="";
//$message=iconv("windows-1256", "UTF-8",$message);
for($i=0;$i<strlen($message);$i+=160)
{
	if($i==0)
	  $a=substr($message,$i,160);
	 else 
	if($i>=131 && $i<262)
	  $b=substr($message,$i,160);
	 else 
    if($i>=262 && $i<393)
	  $c=substr($message,$i,160);
    
  //$msg1[$j]=substr($message,$i,160);
  $j++;	
}
$mymsg="";
 $cell_number=array();
 $i=1;
 //$myudh="%05%00%03%47%02%01";

if(strlen($cell_numbers)<=0)
 return -4;

 $array_cnt=0;
 
  
 
// Connect ...
//$client = new soapclient('http://192.168.0.1/engine/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
$client = new soapclient('http://webservice.magfa.com/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
 
// Read error
$err = $client->getError();
if ($err) {
	echo "<h2>Constructor error</h2><pre>$err</pre>";
}

 
// Authentication
$client->setCredentials($username, $password, 'basic');

if(strlen($shno) <= 0)
  $shno="30007912";

// echo "if(strlen($message) <131 ) {	    $result[\"enqueue1\"] = $client->call(\"enqueue\", 	array($domain,0,array(\"$a\",\"$a\"),array($cell_number),array($mytmp),array($myudh),));";
//print_r( $cell_number); 
$tok = strtok($cell_numbers, ",");

while ($tok !== false) 
{
	$cell_number=$tok;
	 if(strlen($message) <160 )
 {	 
    $result["enqueue1"] = $client->call("enqueue", // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array($shno)
						//UDH
		)
	);
    
    $tok = strtok(",");
    $array_cnt++;
}
 

 /*
	

   if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array("$shno")
						//UDH
		)
	);
*/
 
	/*
 if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
    	array("$a"),//Message						
		array("$cell_number"),			//Destination
	 	array("30007912")
						//UDH
		)
	);
  */
	
 	//echo $msg1($k-1);
 
 //echo "<br>".$k."<br>";
  
 if ($client->fault) {
	echo '<h2>Fault 1111</h2><pre>';	   
    }   
	
 
}
return 0;



//-----------------------------------------------------------------------------------

 if(strlen($message)>=131 && strlen($message)<262)
 {      
 
 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		0,					//Message Type
	    array("$a","$b" ), 			//Message
		array("$cell_number","$cell_number"),			//Destination
		 array("$shno","$shno"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02"),
					//UDH
		)
	);
	
	 
  if ($client->fault) {
	echo '<h2>Fault 2222</h2><pre>';	   
    }  

 }
  //-------------------------------------------------------------------------------------
  
  if(strlen($message)>=262 && strlen($message)<393)
 { 	 
 	
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		0,					//Message Type
	    array("$a","$b","$c" ), 			//Message
		array("$cell_number","$cell_number","$cell_number"),			//Destination
	    array("$shno","$shno","$shno"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02","%05%00%03%47%02%03"),
		 			//UDH
		)
	);	
 	

 if ($client->fault) {
	echo '<h2>Fault 3333</h2><pre>';	   
    }  
      
    }

}


//--------------------------------------------------------------------------------


function send_group_sms_new($message,$cell_numbers,$shno)
{
$username = 'olomPezeshki';
$password = 'medicalu_01';
$domain = 'magfa';



$j=0;
 
$a="";
$b="";
$c="";
//$message=iconv("windows-1256", "UTF-8",$message);
 
$mymsg="";
 $cell_number=array();
 $i=1;
 //$myudh="%05%00%03%47%02%01";

if(strlen($cell_numbers)<=0)
 return -4;

 $array_cnt=0;
 
  
 
// Connect ...
//$client = new soapclient('http://192.168.0.1/engine/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
$client = new soapclient('http://webservice.magfa.com/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
 
// Read error
$err = $client->getError();
if ($err) {
	echo "<h2>Constructor error</h2><pre>$err</pre>";
}

 
// Authentication
$client->setCredentials($username, $password, 'basic');

if(strlen($shno) <= 0)
  $shno="30007912";




$tok = strtok($cell_numbers, ",");


$itemcntr=0;
$recipientNumbers = array();
while ($tok !== false) 
{
    $itemcntr++;
    array_push($recipientNumbers, new soapval('item'+$itemcntr,'string',$tok));
    $tok = strtok(","); 
}

        // creating the parameter array
  $params = array(
       'domain'=>$domain,
       'messageBodies'=>array($message),
       'recipientNumbers'=>$recipientNumbers,
       'senderNumbers'=>array($shno)
      );


  $response = $client->call("enqueue",$params);

 

 
 if ($client->fault) {
	echo '<h2>Fault 1111</h2><pre>';	   
    }   
	
 
 
return 0;


 

}

 //---------------------------------------------------------------------------------


function savelog($adminuser,$operation,$activity)
{
 $op_date=date("Y/m/d");
 $op_time=date("H:i:s");

 $q1="insert into userlog set adminuser='$adminuser', operation='$operation', op_date='$op_date', op_time='$op_time', activity='$activity'";
//echo $q1;
 $result=mysql_query($q1) or die("Server error in log saving");
 if(mysql_affected_rows()>0)
   return 1;
 else
   return 0;
}
//------------------------------------------------------------------------------------
 



 
function rename_directory($base_dir,$target_dir)
{
  $mybasedir= getcwd();
  chdir("../attachments");
   rename("$base_dir","$target_dir");

  chdir("$mybasedir");
   chdir("../reports");
   rename("$base_dir","$target_dir");
  chdir("$mybasedir");
 
  return -4;
}

//----------------------------------------------------------------


//----------------------------------------------------------------------

function delete_file($base_dir,$dir,$file_name_ok)
{
  $mybasedir= getcwd();
  if(strlen(trim(dir)) > 0)
     $filename=$base_dir."/".$dir."/".$file_name_ok;
  else
     $filename=$base_dir."/".$file_name_ok;
  $dirname=$base_dir."/".$dir;
  @unlink($filename);
  if(strlen(trim($dir)) > 0 and strlen(trim($file_name_ok)) <= 0)
  {
  	
    clr_dir($dirname);
  }
  chdir("$mybasedir");
  return -4;
}
//----------------------------------------------------------------

function clr_dir($dir) {
if(@ ! $opendir = opendir($dir)) {
return false;
}
while(false !== ($readdir = readdir($opendir))) {
if($readdir !== '..' && $readdir !== '.') {
$readdir = trim($readdir);
if(is_file($dir.'/'.$readdir)) {
if(@ ! unlink($dir.'/'.$readdir)) {
return false;
}
} elseif(is_dir($dir.'/'.$readdir)) {
// Calls itself to clear subdirectories
if(! clr_dir($dir.'/'.$readdir)) {
return false;
}
}
}
}
closedir($opendir);
if(@ ! rmdir($dir)) {
return false;
}
return true;
}

//---------------------------------------------------------------------------------------

function upload_file($base_dir,$dir,$file_name_ok)
{
// -1    bad file size
// -2    bad extention
// -3    bad file size
// -4    can not upload
// -5    directory exists
// -6    file exists
// $ext  extion of uploaded file
// global $userfile,$userfile_name,$userfile_size,$userfile_type,$archive_type,$archive_dir,$WINDIR;
// 10  file uploaded
$mybasedir= getcwd();
global $_FILES,$max_file_size;


// global $fupload,$fupload_name,$fupload_size,$fupload_type,$max_file_size;
$fupload=$_FILES["fupload"]['tmp_name'];
$fupload_name=$_FILES["fupload"]["name"];
$fupload_size=$_FILES["fupload"]["size"];
$fupload_type=$_FILES["fupload"]["type"];
//echo "1-$fupload_name------   $max_file_size";
// echo "-->$fupload<br>";
// echo "-->$fupload_name<br>";
// echo "-->$fupload_size<br>";
// echo "-->$fupload_type<br>";

// if(isset($WINDIR))
//    $userfile=str_replace("\\\\","\\",$userfile);




$filename=basename($fupload_name);

//$ff1=strstr($filename,".");
$ff1=$filename;
$ii=0;
while(strchr(substr($ff1,1,strlen($ff1)-1),"."))
{
/*	if($i++>5)
	exit();*/
  $ff1=strstr(substr($ff1,1,strlen($ff1)-1),".");
  //echo $ff1."<br>";
}

if((strcmp($ff1,".xls")!=0) && (strcmp($ff1,".doc")!=0) &&  (strcmp($ff1,".pdf")!=0) &&  (strcmp($ff1,".gif")!=0) &&  (strcmp($ff1,".jpg")!=0) &&  (strcmp($ff1,".tiff")!=0)  )
  return -2;



/*if($fupload_size<=0)
 return -3;
if($fupload_size>2000000000)
  return -1;
*/
if (!file_exists($base_dir))
  mkdir($base_dir,0770);

if(chdir($base_dir))
{
  if(strlen(trim($dir)) > 0)
   if (!file_exists($dir))
     mkdir("$dir",0770);
}
else
return -9;

if(strcmp($ff1,"application/msword")!=0)
 $ext="msword";
else
 if(strcmp($ff1,"application/pdf")!=0)
   $ext="msword";
 else
   if(strcmp($ff1,"image/pjpeg")!=0)
    $ext="msword";
   else
     if(strcmp($ff1,"image/gif")!=0)
       $ext="msword";

$ext=substr(strchr($ff1,"."),1);

if(strlen(trim($file_name_ok)) > 0 )
  $fupload_name = $file_name_ok;

if(strlen(trim($dir)) > 0)
  $filename_upload="$dir/$fupload_name";
else
  $filename_upload="$fupload_name";


if(!@file_exists("$filename_upload"))
{
  if(!@copy ( $fupload,"$filename_upload"))
  {
    chdir("$mybasedir");
    return -4;
  }
  else
  {
   chdir("$mybasedir");
   return 10;
  }
}
else
{
  chdir("$mybasedir");
  return -5; // duplicate enter
}
chdir("$mybasedir");
return $ext;
}

//---------------------------------------------------------------------------------------
function arabic2utf($content)
{
//$utf=array(1=>"&#1590;",2=>"&#1589;",3=>"&#1579;",4=>"&#1602;",5=>"&#1601;",6=>"&#1594;",7=>"&#1593;",8=>"&#1607;",9=>"&#1582;",10=>"&#1581;",11=>"&#1580;",12=>"&#1670;",13=>"&#1588;",14=>"&#1587;",15=>"&#1610;",16=>"&#1576;",17=>"&#1604;",18=>"&#1575;",19=>"&#1578;",20=>"&#1606;",21=>"&#1605;",22=>"&#1705;",23=>"&#1711;",24=>"&#1592;",25=>"&#1591;",26=>"&#1586;",27=>"&#1585;",28=>"&#1584;",29=>"&#1583;",30=>"&#1574;",31=>"&#1608;",32=>"&#1662;",33=>"&#1688;");
   $utf=array(1=>"ط¶",2=>"طµ",3=>"ط«",4=>"ظ‚",5=>"ظپ",6=>"ط؛",7=>"ط¹",8=>"ظ‡",9=>"ط®",10=>"ط­",11=>"ط¬",12=>"ع†",13=>"ط´",14=>"ط³",15=>"غŒ",16=>"ط¨",17=>"ظ„",18=>"ط§",19=>"طھ",20=>"ظ†",21=>"ظ…",22=>"ع©",23=>"ع¯",24=>"ط¸",25=>"ط·",26=>"ط²",27=>"ط±",28=>"ط°",29=>"ط¯",30=>"ط¦",31=>"ظˆ",32=>"ظ¾",33=>"عک",34=>"ط§");
$arabic=array(1=>"ض",2=>"ص",3=>"ث",4=>"ق",5=>"ف",6=>"غ",7=>"ع",8=>"ه",9=>"خ",10=>"ح",11=>"ج",12=>"چ",13=>"ش",14=>"س",15=>"ي",16=>"ب",17=>"ل",18=>"ا",19=>"ت",20=>"ن",21=>"م",22=>"ك",23=>"گ",24=>"ظ",25=>"ط",26=>"ز",27=>"ر",28=>"ذ",29=>"د",30=>"ئ",31=>"و",32=>"پ",33=>"ژ",34=>"آ");
  for($i=1;$i<=34;$i++)
   $content=str_replace($arabic[$i],"-".$arabic[$i]."-",$content);

  for($i=1;$i<=34;$i++)
   $content=str_replace("-".$arabic[$i]."-",$utf[$i],$content);
return $content;
}
//---------------------------------------------------------------------------------------

function DBreccount($DBname)
{

  $query="select count(*) as mycnt from $DBname";
  
  $result = mysql_query($query);
  $row_fetched = mysql_fetch_array($result);
  return strval($row_fetched["mycnt"]);

}

//---------------------------------------------------------------------------------------


function insert_position($cod_tarh,$position,$admin)
{
	
  $action_date=date("Y-m-d");
  $query="insert into tarh_position set cod_tarh='$cod_tarh',position='$position',creator='$admin',action_date='$action_date' ";

  $result=mysql_query($query) or die("Error in inserting data into position");
}


//---------------------------------------------------------------------------------------

function current_position($cod_tarh)
{
  $query="select * from  tarh_position where  cod_tarh='$cod_tarh' order by id desc";
  
  $result_position=mysql_query($query) or die("Error in selecting data from position");
  if(mysql_num_rows($result_position) > 0 )
  {
  	$row_fetched_position=mysql_fetch_array($result_position);
  	$position=$row_fetched_position["position"];
  	return $position;
  	
  }
  else 
   return -1;  // no record in position database for this tarh
  
}

//-------------------------------------------------------------------------------

function send_sms($cell_number,$message)
{

/*	
 $username = 'niazi_ws';
$password = 'pahsmn';
$domain = 'niazi';
*/
 $username = 'olomPezeshki';
$password = 'medicalu_01';
$domain = 'magfa';
 

// Connect ...
//$client = new soapclient('http://192.168.0.1/engine/services/urn:SOAPSmsQueue?wsdl', 'wsdl');
$client = new soapclient('http://webservice.magfa.com/services/urn:SOAPSmsQueue?wsdl', 'wsdl');


// Read error
$err = $client->getError();
if ($err) {
	echo "<h2>Constructor error</h2><pre>$err</pre>";
}

// Authentication
$client->setCredentials($username, $password, 'basic');




$j=0;
 
$a="";
$b="";
$c="";
//$message=iconv("windows-1256", "UTF-8",$message);


for($i=0;$i<strlen($message);$i+=164)
{
	if($i==0)
	  $a=substr($message,$i,164);
	 else 
	if($i>=164 && $i<328)
	  $b=substr($message,$i,164);
	 else 
    if($i>=328 && $i<492)
	  $c=substr($message,$i,164);
    
  //$msg1[$j]=substr($message,$i,160);
  $j++;	
}


 /*
 if(strlen($message) <131 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		0,					//Message Type
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array("")
						//UDH
		)
	);
*/	
 
 
 if(strlen($message) <164 )
 {	 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		array("$a"),			//Message
		array("$cell_number"),			//Destination
	 	array("30007912")
						//UDH
		)
	);
	
 
 
 	//echo $msg1($k-1);
 
 //echo "<br>".$k."<br>";
  
 if ($client->fault) {
 	echo $client->response();
	echo '<h2>Fault 1111</h2><pre>';	   
    }   
	
 
}


//-----------------------------------------------------------------------------------

 if(strlen($message)>=164 && strlen($message)<328)
 {      
 
 
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		
	    array("$a","$b" ), 			//Message
		array("$cell_number","$cell_number"),			//Destination
		 array("+9830007912","+9830007912"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02"),
					//UDH
		)
	);
	
	 
  if ($client->fault) {
	echo '<h2>Fault 2222</h2><pre>';	   
    }  

 }
  //-------------------------------------------------------------------------------------
  
  if(strlen($message)>=328 && strlen($message)<492)
 { 	 
 	
    $result["enqueue1"] = $client->call("enqueue",          // Method
	array(						// Parameters
		$domain,				//Domain
		0,					//Message Type
	    array("$a","$b","$c" ), 			//Message
		array("$cell_number","$cell_number","$cell_number"),			//Destination
	    array("+9830007912","+9830007912","+9830007912"),
		array("%05%00%03%47%02%01","%05%00%03%47%02%02","%05%00%03%47%02%03"),
		 			//UDH
		)
	);	
 	

 if ($client->fault) {
	echo '<h2>Fault 3333</h2><pre>';	   
    }  
      
    }







 

}

////////////////////////////
//---------------------------------------------------------------------------------------

function hazineha_detail_view($cod_tarh)
{


   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1' order by activity_type ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";
       $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
       if(mysql_num_rows($qresult) > 0 )
       {
         $row_degree = mysql_fetch_array($qresult);
         $degree_result = $row_degree["darajeelmi_desc"];
       }
       else
         $degree_result = "ثبت نشده";
     }
      $personnel_sum=$mycount;
   }

   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='-1' order by mozoa_azmayesh ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='-1' order by name_dastgah";

   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   $vasile_sum_masrafi=0;
   $vasile_sum_gheir_masrafi=0;
   
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      if(strcmp(trim($row_fetched["usage_unusage"]),"0")==0)
        $vasile_sum_masrafi=$vasile_sum_masrafi+$row_fetched["price"]*$row_fetched["count"];
  
      if(strcmp(trim($row_fetched["usage_unusage"]),"1")==0)
        $vasile_sum_gheir_masrafi=$vasile_sum_gheir_masrafi+$row_fetched["price"]*$row_fetched["count"];
        
        
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;
      

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='-1' order by target";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='-1'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
$maliat=0;
$nezarat=0;
$balasari=0;
$sum_sayer=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
    $hazine_taksir = $hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_row_fetched["sayer_hazine"];
    $maliat = $hazine_row_fetched["maliat"];
    $nezarat = $hazine_row_fetched["nezarat"];
    $balasari = $hazine_row_fetched["balasari"];
    $sum_sayer=$sum_sayer+$hazine_digar+$hazine_taksir+$maliat+$nezarat+$balasari;
  }
 }
?>
 
 <?
	 
    
	 $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum ;

$query = "select * from eatebar_sazmanha where cod_tarh='$cod_tarh'  and version='-1'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$eatebar=0;
$eatebare_sazmanha_pardakht_add=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
  	$eatebar_org=$hazine_row_fetched["eatebare_sazmanha_value"];
  	$eatebar_org=str_replace("/","",$eatebar_org);
    $eatebar = $eatebar+$eatebar_org;
   
  }
 }
    
    
    $eatebare_sazmanha_pardakht_add=$eatebar;

?>
 
 <table border="0" width="90%" cellpadding="1" cellspacing="1"   >

 <tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($personnel_sum); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه پرسنلي
 </td>
 </tr>
 
  <tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($lab_sum); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه آزمايشگاه
 </td>

 </tr>

  
  <tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($vasile_sum); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه وسايل و مواد
 </td>

 </tr>


<tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($vasile_sum_masrafi); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه وسايل و مواد مصرفي
 </td>

 </tr>
<tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($vasile_sum_gheir_masrafi); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه وسايل و مواد غير مصرفي
 </td>

 </tr>
 <tr>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($trip_sum); ?>
 </td>
 <td  class="tahoma1" bgcolor=<? echo $color; ?>>
 هزينه سفر
 </td>

 </tr>
 <tr>
 <td class="tahoma1" bgcolor=<? echo $color; ?>>
  <? echo number_format($sum_sayer); ?>
 </td>
 <td class="tahoma1" bgcolor=<? echo $color; ?>>
 ساير هزينه ها
 </td>

 </tr>


 </tr>
 <tr>
 <td class="tahoma1">
  <? echo number_format($eatebare_sazmanha_pardakht_add); ?>
 </td>
 <td class="tahoma1">
 تامين اعتبار از سازمانهاي ديگر
 </td>

 </tr> 
  <tr>
 <td class="tahoma1">
  <? echo number_format($sum_of_all); ?>
 </td>
 <td class="tahoma1">
 مجموع
 </td>

 </tr> 
</table>
 
<?

}
 
///////////////////////////
function add_hazineha($cod_tarh , $version)
{
  $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version' order by activity_type ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";
       $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
       if(mysql_num_rows($qresult) > 0 )
       {
         $row_degree = mysql_fetch_array($qresult);
         $degree_result = $row_degree["darajeelmi_desc"];
       }
       else
         $degree_result = "ثبت نشده";
     }
      $personnel_sum=$mycount;
   }

   
   
   
   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";

   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='$version'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
    $hazine_taksir = $hazine_taksir+$hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_digar+$hazine_row_fetched["sayer_hazine"];
  }
 }
  $sum_sayer=$hazine_digar+$hazine_taksir;
   $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
	
     echo "<table width=\"280\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\"><b>(مجموع(ريال<b></td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\"><b>هزينه<b></td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"     align=\"center\" class=\"tahoma1\">".number_format($personnel_sum)."</td>";
     echo "<td width=\"80%\"   align=\"center\"  class=\"tahoma1\">جمع هزينه پرسنلي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($lab_sum)."</td>";
     echo "<td width=\"80%\"     align=\"center\"  class=\"tahoma1\">جمع هزينه هاي آزمايشات وخدمات تخصصي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"    align=\"center\" class=\"tahoma1\">".number_format($trip_sum)."</td>";
     echo "<td width=\"80%\"     align=\"center\"  class=\"tahoma1\">جمع هزينه هاي مسافرت</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"    align=\"center\" class=\"tahoma1\">".number_format($vasile_sum)."</td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\">جمع هزِينه هاي وسايل</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($sum_sayer)."</td>";
     echo "<td width=\"80%\"   align=\"center\"  class=\"tahoma1\">جمع ساير هزينه ها</td>";
     echo "</tr>";

     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($eatebare_sazmanha_pardakht_add)."</td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\">اعتبار از سازمانهاي ديگر</td>";
     echo "</tr>";

	 echo "<tr>";
	 $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\"><b>".number_format($sum_of_all)."</b></td>";
     echo "<td width=\"80%\"   align=\"center\" class=\"tahoma1\"><b>جمع کل</b></td>";

     echo "</tr>";


     echo "</table>";

 	
}


//---------------------------------------------------------------------------------


function sum_of_hazine($cod_tarh,$version)
{
   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version' order by activity_type ";
   $personnel_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
      
     }
      $personnel_sum=$mycount;
   }

   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";
   $lab_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";
   $vasile_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";
   $trip_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='$version'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
    $hazine_taksir = $hazine_taksir+$hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_digar+$hazine_row_fetched["sayer_hazine"];
  }
 }
  $sum_sayer=$hazine_taksir+ $hazine_digar;
 return $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
}

//---------------------------------------------------------------------------------------


function prepare_database($admin)
{
  // echo "<div style=\"position:absolute;visibility:visible;\" id='mylayer' ><p align='center'><br><br><br><img src=\"image/wait_animated.gif\"><br><span class='tahoma1'> سيستم در حال آماده سازي گزارش است </span></p></div>";
 
   $version='-1';
   $query="delete from prepared_report where admin='$admin'";
   $result_tarhs=mysql_query($query) or die("Error 1");
	$k=0;
  
   $query="select * from tarh where version='-1'";
   $result_tarhs=mysql_query($query) or die("Error 1");
   while($row_fetch_tarhs=mysql_fetch_array($result_tarhs))
   {
   $k++;
   if($k<30)
     echo "<p align='center'><br><br><br><img src=\"image/wait_animated.gif\"><br><span class='tahoma1'> سيستم در حال آماده سازي گزارش است </span></p>";
 
  
   $cod_tarh=$row_fetch_tarhs["cod_tarh"];
   $daneshkade=$row_fetch_tarhs["cod_daneshkade"];
   $position_tarh=current_position($cod_tarh);
   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version' order by activity_type ";
   $personnel_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
      
     }
      $personnel_sum=$mycount;
   }

   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";
   $lab_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";
   $vasile_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";
   $trip_sum=0;
   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='$version'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
    $hazine_taksir = $hazine_taksir+$hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_digar+$hazine_row_fetched["sayer_hazine"];
  }
 }
 $sum_sayer=$hazine_taksir+ $hazine_digar;
 $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
 $query="insert into prepared_report set daneshkade='$daneshkade',position_tarh='$position_tarh',cod_tarh='$cod_tarh',admin='$admin',hazine_personnel='$personnel_sum',hazine_azmayesh='$lab_sum',hazine_vasayel='$vasile_sum',hazine_mosaferat='$trip_sum',hazine_others='$sum_sayer',hazine_all='$sum_of_all'";
 // echo $query;
 $result=mysql_query($query)or die("Error 121");
 
 }

}


//---------------------------------------------------------------------------------------


function record_duplicate($table_name,$cod_tarh,$sec_id_name,$id_auto_inc)
{

$query="select max(version) as maxver from $table_name where cod_tarh='$cod_tarh'";

$result=mysql_query($query) or die("Error in selecting data from 1");

$rf1=mysql_fetch_array($result);
$maxver=$rf1["maxver"];
if($maxver=='-1')
  $maxver='1';
else
  $maxver=$maxver+1;
$query="select * from $table_name where cod_tarh='$cod_tarh' and version='-1'";
$res_org=mysql_query($query) or die("error in selecting data from 2");


$field_count=mysql_num_fields($res_org);
while($rf=mysql_fetch_array($res_org))
{
  $query="insert into $table_name  values(";
  for($i=0;$i<$field_count;$i++)
  {
    $field_name=mysql_field_name($res_org,$i);	
    if(strcmp($field_name,"version")!=0)
    {
      if(strcmp($field_name,$sec_id_name)==0 && strcmp($id_auto_inc,'1')==0)
      {
	     if($i==0) 
          $query=$query."'"."'";
        else  
          $query=$query.","."'"."'";
      }
	  else
	  {	
	  	$rf[$i]=str_replace("'","",$rf[$i]);
	  	$rf[$i]=str_replace("\"","",$rf[$i]);
	  	
	    
	    
        if($i==0) 
          $query=$query."'".$rf[$i]."'";
        else  
          $query=$query.","."'".$rf[$i]."'";
	  }
    }
    else
    {
     if($i==0) 
       $query=$query."'"."-2"."'";
    else  
       $query=$query.","."'"."-2"."'";
   }
  	
 // $query="insert into test values($rf[0],$rf[1],$rf[2])";
   }
   $query=$query.")";
   //echo $query;
   
   $result=mysql_query($query) or die("Error 3333333333");
if(strlen($sec_id_name) > 0 )
{
  $sec_id_value=$rf[$sec_id_name];	
  $sec_arg=" and $sec_id_name='$sec_id_value'";
}
else
  $sec_arg="";
   $query="update $table_name set version='$maxver' where cod_tarh='$cod_tarh' and version='-1' $sec_arg";
 
   $result=mysql_query($query) or die("Error in selecting data from 4");
   
   $query="update $table_name set version='-1' where cod_tarh='$cod_tarh' and version='-2'";  
 
   $result=mysql_query($query) or die("Error in selecting data from 5");
   

}
}


function bold_update($table,$cod_tarh){
	$query="update $table set new_update='0' where cod_tarh='$cod_tarh' and version='-1'";  
 	$result=mysql_query($query) or die("Error in selecting data from 5");
}

function bold_update_ravesh_ejra($cod_tarh){
	$query="update ravesh_ejra set new_update_ravesh_ejra='0',new_update_moshakhasat_abzar='0',new_update_ravesh_mohasebe='0',new_update_molahezat_akhlaghi='0',new_update_mahdoudiat_ejra='0' where cod_tarh='$cod_tarh' and version='-1'";  
 	$result=mysql_query($query) or die("Error in selecting data from 5");
}
function bold_update_tarh_body($cod_tarh){
	$query="update tarh set new_update_zarorat_ejra='0',new_update_bayan_masale='0',new_update_taarif_vajeh='0',new_update_ahdaf='0',new_update_soalat='0',new_update_fehrest_manabea='0' where cod_tarh='$cod_tarh' and version='-1'";  
 	echo $query;
	$result=mysql_query($query) or die("Error in selecting data from 5");
}

//---------------------------------------------------------------------------



function mablagh_karshenasi($cod_tarh)
{


 $query="select * from tarh where cod_tarh='$cod_tarh' and version=\"-1\" ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  
  
  $mablagh_aghd_gharardad = $row_fetched["mablagh_aghd_gharardad"];
  
 $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1' order by activity_type ";
      $result00=mysql_query($query) or die("Error in selecting data from hazine personnel");
      if(mysql_num_rows($result00) > 0)
      {
     
        $mycount=0;
       while($row_fetched00=mysql_fetch_array($result00))
       {
  
       $my_summary = $row_fetched00["per_hour"]*$row_fetched00["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       }       
      }
      $hazine_personnel=$mycount;
      
      $darsad_50=$mablagh_aghd_gharardad*50/100;
      
      
$query="select * from gozaresh_gharardad  where cod_tarh='$cod_tarh' and marhale!='0' and marhale!='100' order by marhale asc ";
$result1=mysql_query($query) or die("Error");
$cntr=1;
$mablagh12=0;
$karshenasi=0;
while($rf66=mysql_fetch_array($result1))
{
// echo $cntr;
  if($hazine_personnel > $darsad_50)
  {
  	$mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
  	$nezarat=100000+$mablagh_marhale_n/100;
  	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
  	
	$maliat_marhale_n=$mablagh_marhale_n*5/100;
	$hagh_ol_zahme_karshenasi_n=100000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
	$mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n;
	$mablagh_khales_mojri=$mablagh_khales_mojri-$hagh_ol_zahme_karshenasi_n;
	  		
  }
  else
  {
  	 $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
	 $mablagh_marhale_n=($darsad_marhale+(100000+($darsad_marhale/100)))*100/95;
	 $maliat_marhale_n=$mablagh_marhale_n*5/100;
	 $hagh_ol_zahme_karshenasi_n=100000+($darsad_marhale/100);
	 
	 $mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n-$hagh_ol_zahme_karshenasi_n;
	 
  }	
  
  $karshenasi=$karshenasi+$hagh_ol_zahme_karshenasi_n;
}







  $query="select * from gozaresh_gharardad where marhale='0' and cod_tarh='$cod_tarh'";
      $result88=mysql_query($query) or die("Error");
      if(mysql_num_rows($result88) > 0)
	  {
	  	$rf66=mysql_fetch_array($result88);
	    if($hazine_personnel > $darsad_50)
	    {
	      $mablagh_marhale_0=$rf66["mablagh"]*$mablagh_koll/100;
	      $maliat_marhale_0=$mablagh_marhale_0*5/100;
	      $hagh_ol_zahme_karshenasi_0=($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
		  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0;
		   $mablagh_khales_mojri_0= $mablagh_khales_mojri_0-$hagh_ol_zahme_karshenasi_0;
	      
	  		
	    }
	    else
	    {
	      $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
	      $mablagh_marhale_0=($darsad_marhale+($darsad_marhale/100))*100/95;
	      $maliat_marhale_0=$mablagh_marhale_0*5/100;
	      $hagh_ol_zahme_karshenasi_0=($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
		  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0-$hagh_ol_zahme_karshenasi_0;
	      
	      
	  		      
	    }
	    
	    
	  	
	  }
	  $karshenasi=$karshenasi+$hagh_ol_zahme_karshenasi_0;
	//  echo "mohsen <br>".$end_time."<br>".$month_remain."<br>".$mablagh_marhale_0."<br>".$mablagh_aghd_gharardad."<br>".$maliat_1."<br>".$hazine_personnel;
	  //exit();
	   //$mablagh_koll_tarh=$maliat_koll+$nezarat_koll+$mablagh_aghd_gharardad;
	  
	  //-------------------marhale Nahayee ------------------------------------------
	  
	  $a=100000;
	  $query="select * from gozaresh_gharardad where marhale='100' and cod_tarh='$cod_tarh'";
      $result=mysql_query($query) or die("Error");
      $b=0;
	  if(mysql_num_rows($result) > 0)
	  {
	  	$rf66=mysql_fetch_array($result);
	   if($hazine_personnel > $darsad_50)
       {
  	      $mablagh_marhale_end=$rf66["mablagh"]*$mablagh_koll/100;
  	      $nezarat=125000+$mablagh_marhale_end/100;
      	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
  	
	      $maliat_marhale_end=$mablagh_marhale_end*5/100;
	      $hagh_ol_zahme_karshenasi_end=125000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
	  	
	      $mablagh_khales_mojri_end=$mablagh_marhale_end-$maliat_marhale_end;
	      $mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
	      $hagh_ol_zahme_karshenasi_end=125000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
	  		
        }
        else
        {
  	      $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
  	      $hagh_ol_zahme_karshenasi_end=100000+($darsad_marhale/100)+$month_remain*5000;
	      $mablagh_marhale_end=($darsad_marhale+$hagh_ol_zahme_karshenasi_end)*100/95;
	      $maliat_marhale_end=$mablagh_marhale_end*5/100;
	      $mablagh_khales_mojri_end=$mablagh_marhale_end-$maliat_marhale_end-$hagh_ol_zahme_karshenasi_end;
	     
	     
        }
	  }
$karshenasi=$karshenasi+$hagh_ol_zahme_karshenasi_end;
return $karshenasi;



	
}

//---------------------------------------------------------------------------------------

function header_forms($admin,$seed)
{
	
	global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;




 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type == 1 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
 }
else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
  include("include/header.phtml");

  /*?>
  <html>
  <head>
 <META http-equiv=content-type content=text/html;charset=windows-1256> 
 <SCRIPT language=JavaScript type=text/JavaScript>
function MakingMoneyForm(me)
				{
				
					if((event.keyCode==13) || (event.keyCode==9) || (event.keyCode==39) || (event.keyCode==37) || (event.keyCode==16))
						return;

					var TempStr = ''
					
					while(me.value.indexOf(',') != -1)
						me.value = me.value.replace(',','')
					
					var R = me.value.length % 3;
					TempStr =  me.value.substring(0,R);
					for(var i = R ; i < me.value.length ; i++ )
					{
						if ((me.value.length-i)%3==0)
						{
							TempStr = TempStr + "," + me.value.substring(i,i+1) 
						}
						else 
							TempStr = TempStr +  me.value.substring(i,i+1) 
					}
					
					//Removing First ','
					if(TempStr.substring(0,1) == ",")
						TempStr = TempStr.substring(1,TempStr.length)
					
					me.value=TempStr

						
				}

</SCRIPT>
 
<SCRIPT LANGUAGE="JavaScript">

function textCounter(field,cntfield,maxlimit) {
if (field.value.length > maxlimit) // if too long...trim it!
field.value = field.value.substring(0, maxlimit);
// otherwise, update 'characters left' counter
else
cntfield.value = maxlimit - field.value.length;
}
//  End -->
</script>

<STYLE type=text/css>
BODY {
	SCROLLBAR-FACE-COLOR: #003366;
	SCROLLBAR-HIGHLIGHT-COLOR: #000000;
	SCROLLBAR-SHADOW-COLOR: #000000;
	SCROLLBAR-3DLIGHT-COLOR: #a1a1a1;
	SCROLLBAR-ARROW-COLOR: #000000;
	SCROLLBAR-TRACK-COLOR: #bfbfbf;
	SCROLLBAR-DARKSHADOW-COLOR: #ffffff;
	SCROLLBAR-BASE-COLOR: #a1a1a1;
	background-color: #CCCCCC;
}

a:link {
	color: #333333;
	text-decoration: none;
}
a:visited {
	color: #333333;
	text-decoration: none;
}
a:hover {
	color: #7592B5;
	text-decoration: none;

a:active {
	color: #6072DE;
	text-decoration: none;		
}

</STYLE>
<link rel="stylesheet" href="../css/style.css" type="text/css" media="screen" />
  	<link rel="stylesheet" href="../css/slide.css" type="text/css" media="screen" />
		<script src="js/jquery-1.3.2.min.js" type="text/javascript"></script>
 	<script src="../js/slide.js" type="text/javascript"></script>

    <script language="javascript" src="../js/farsi.js"></script>
   <script language="javascript" src="../js/public.js"></script>

 <link rel="stylesheet" href="../js/bubble-tooltip.css" media="screen">
	<script type="text/javascript" src="../js/bubble-tooltip.js"></script>
    
<script language="javascript" src="../js/public_smo_scripts.js"></script>
  
<script language="JavaScript" src="../js/menu.js"></script> 
   <link href="../js/menu.css" type="text/css" rel="stylesheet">

<title>سيستم جامع پژوهشي</title>


<script language="javascript" src="js/farsi.js"></script>
<script language="javascript" src="js/public_smo_scripts.js"></script>

<script language="JavaScript" type="text/JavaScript">function mmLoadMenus() {
	
 if (! window.mm_menu_letter)
  {
    window.mm_menu_letter = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,100,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_letter.addMenuItem(\"دبير خانه\",\"location='letter_to_mojri_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_letter.addMenuItem(\"نامه كارشناسان جهت تاييد\",\"location='confirm_letters.phtml?admin=$admin&seed=$seed'\");"; ?>
     <? echo "mm_menu_letter.addMenuItem(\"نامه هاي ارسالي شما\",\"location='your_letter_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    mm_menu_letter.hideOnMouseOut=true;
    mm_menu_letter.bgColor='#555555';
    mm_menu_letter.menuBorder=0;
    mm_menu_letter.menuLiteBgColor='#FFFFFF';
    mm_menu_letter.menuBorderBgColor='#777777';
  }	
	
  if (! window.mm_menu_karshenasan)
  {
    window.mm_menu_karshenasan = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,100,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_karshenasan.addMenuItem(\"تعريف کارشناس\",\"location='karshenasan_add.phtml?admin=$admin&seed=$seed'\");"; ?>
    mm_menu_karshenasan.hideOnMouseOut=true;
    mm_menu_karshenasan.bgColor='#555555';
    mm_menu_karshenasan.menuBorder=0;
    mm_menu_karshenasan.menuLiteBgColor='#FFFFFF';
    mm_menu_karshenasan.menuBorderBgColor='#777777';
  }
  
  
   if (! window.mm_menu_tarhs)
  {
    window.mm_menu_payannameha = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_payannameha.addMenuItem(\"بررسي اخلاق پايان نامه ها\",\"location='payanname_list_new_before_akhlagh.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_payannameha.addMenuItem(\"پايان نامه هاي بررسي اخلاقي شده\",\"location='payanname_list_new_after_akhlagh.phtml?admin=$admin&seed=$seed'\");"; ?>
  
    mm_menu_payannameha.hideOnMouseOut=true;
    mm_menu_payannameha.bgColor='#555555';
    mm_menu_payannameha.menuBorder=0;
    mm_menu_payannameha.menuLiteBgColor='#FFFFFF';
    mm_menu_payannameha.menuBorderBgColor='#777777';
  }
  
  
  
  if (! window.mm_menu_mostaghel)
  {
    window.mm_menu_mostaghel = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_mostaghel.addMenuItem(\"گردش کاري مراکز مستقل در دانشگاه\",\"location='sent_daneshgah_confirm.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_mostaghel.addMenuItem(\"طرح هاي آماده به قرارداد\",\"location='new_gharardad_mostaghel.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_mostaghel.addMenuItem(\"طرح هاي در حال اجرا\",\"location='in_doing_mostaghel.phtml?admin=$admin&seed=$seed'\");"; ?>
     
    mm_menu_mostaghel.hideOnMouseOut=true;
    mm_menu_mostaghel.bgColor='#555555';
    mm_menu_mostaghel.menuBorder=0;
    mm_menu_mostaghel.menuLiteBgColor='#FFFFFF';
    mm_menu_mostaghel.menuBorderBgColor='#777777';
  } 
  
  if (! window.mm_menu_tarhs)
  {
    window.mm_menu_tarhs = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي جديد\",\"location='tarh_list_new.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي قبل از تصويب\",\"location='tarh_list_new_before_submit.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي بعد از تصويب\",\"location='tarh_list_new_after_submit.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي آماده به قرارداد\",\"location='new_gharardad.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي در حال اجرا\",\"location='in_doing.phtml?admin=$admin&seed=$seed'\");"; ?>
  
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي در حال اجراي مراکز مستقل\",\"location='in_doing_daneshkade.phtml?admin=$admin&seed=$seed'\");"; ?>
  
  <? echo "mm_menu_tarhs.addMenuItem(\"طرح هاي پايان يافته\",\"location='finished.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرحهاي بايگاني شده\",\"location='baygani_shode.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"سوابق آشيو طرح\",\"location='archive_reason_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs.addMenuItem(\"طرح هاي رد شده\",\"location='rejected.phtml?admin=$admin&seed=$seed'\");"; ?>
    <?// echo "mm_menu_tarhs.addMenuItem(\"ثبت طرح جديد\",\"location='tarh_admin_new.phtml?admin=$admin&seed=$seed'\");"; ?>

    mm_menu_tarhs.hideOnMouseOut=true;
    mm_menu_tarhs.bgColor='#555555';
    mm_menu_tarhs.menuBorder=0;
    mm_menu_tarhs.menuLiteBgColor='#FFFFFF';
    mm_menu_tarhs.menuBorderBgColor='#777777';
  }

  if (! window.mm_menu_tarhs_hsr)
  {
    window.mm_menu_tarhs_hsr = new Menu("root",148,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"HSR طرحهاي جديد\",\"location='hsr_tarh_list_new.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"HSR طرحهاي قبل از تصويب\",\"location='hsr_tarh_list_new_before_submit.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"HSR طرحهاي بعد از تصويب\",\"location='hsr_tarh_list_new_after_submit.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"طرحهاي آماده به قرارداد\",\"location='hsr_new_gharardad.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"طرح هاي در حال اجرا\",\"location='hsr_in_doing.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"طرح هاي خاتمه يافته\",\"location='hsr_finished.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_tarhs_hsr.addMenuItem(\"طرحهاي بايگاني شده\",\"location='hsr_baygani_shode.phtml?admin=$admin&seed=$seed'\");"; ?>

    <?// echo "mm_menu_tarhs.addMenuItem(\"ثبت طرح جديد\",\"location='tarh_admin_new.phtml?admin=$admin&seed=$seed'\");"; ?>

    mm_menu_tarhs_hsr.hideOnMouseOut=true;
    mm_menu_tarhs_hsr.bgColor='#555555';
    mm_menu_tarhs_hsr.menuBorder=0;
    mm_menu_tarhs_hsr.menuLiteBgColor='#FFFFFF';
    mm_menu_tarhs_hsr.menuBorderBgColor='#777777';
  }


   if (! window.mm_menu_sms)
  {
    window.mm_menu_sms = new Menu("root",148,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_sms.addMenuItem(\"ارسال پيام کوتاه\",\"location='send_sms.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_sms.addMenuItem(\"ليست پيام کوتاه هاي ساب ادمين ها\",\"location='subadmin_sms_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? //echo "mm_menu_sms.addMenuItem(\"ارسال پيام کوتاه به اعضاي شورا\",\"location='send_shora_sms.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_sms.addMenuItem(\"ليست پيام هاي کوتاه  به سيستم\",\"location='list_received_sms.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_sms.addMenuItem(\"ارسال پيام کوتاه به مجريان\",\"location='send_mojrian_sms.phtml?admin=$admin&seed=$seed'\");"; ?> 
   
   
    mm_menu_sms.hideOnMouseOut=true;
    mm_menu_sms.bgColor='#555555';
    mm_menu_sms.menuBorder=0;
    mm_menu_sms.menuLiteBgColor='#FFFFFF';
    mm_menu_sms.menuBorderBgColor='#777777';
  }


if (! window.mm_menu_reports)
  {
    window.mm_menu_reports = new Menu("root",168,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_reports.addMenuItem(\"تعداد طرح بر اساس نام مرکز\",\"location='group_by_center.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"گزارش اخلاقي طرح ها\",\"location='akhlaghi.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"فعاليت کارشناسان ستادي به تفکيک\",\"location='group_karshenasan_activity.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"گزارش فعاليت کارشناسان ستادي شماره 1\",\"location='group_karshenasan_activity1.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"جمع بودجه طرحها به تفکيک مرکز\",\"location='budje_group_by_center.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"گزارش مالي طرح بر اساس گزارشات\",\"location='user_delivery_report.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"جمع بودجه طرحها به تفکيک موارد طرح\",\"location='budje_item_tarh.phtml?admin=$admin&seed=$seed'\");"; ?>    
    <? echo "mm_menu_reports.addMenuItem(\"گزارش مالي به صورت انتخابي\",\"location='budje_selective.phtml?admin=$admin&seed=$seed'\");"; ?>    
     <? echo "mm_menu_reports.addMenuItem(\"گزارش گرانتها\",\"location='grant_report.phtml?admin=$admin&seed=$seed'\");"; ?>
      <? echo "mm_menu_reports.addMenuItem(\"گزارش مالي\",\"location='initial_report.phtml?admin=$admin&seed=$seed'\");"; ?>
      <? echo "mm_menu_reports.addMenuItem(\"گزارش بر اساس فيلدهاي طرح\",\"location='search_field.phtml?admin=$admin&seed=$seed'\");"; ?>
      <? echo "mm_menu_reports.addMenuItem(\"گزارش تعهدات و پرداختي ها\",\"location='search_by_center.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_reports.addMenuItem(\"گزارش پرداخت بصورت ساليانه\",\"location='report_yearly.phtml?admin=$admin&seed=$seed'\");"; ?>
   <? echo "mm_menu_reports.addMenuItem(\"گزارش طرح هاي در حال اجرا و خاتمه يافته\",\"location='report_rank_yearly.phtml?admin=$admin&seed=$seed'\");"; ?>
  

 mm_menu_reports.hideOnMouseOut=true;
    mm_menu_reports.bgColor='#555555';
    mm_menu_reports.menuBorder=0;
    mm_menu_reports.menuLiteBgColor='#FFFFFF';
    mm_menu_reports.menuBorderBgColor='#777777';
  }

 if (! window.mm_menu_shora_pajoheshi)
  {
    window.mm_menu_shora_pajoheshi = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_shora_pajoheshi.addMenuItem(\"تعريف شوراي پژوهشي\",\"location='taarif_shora.phtml?admin=$admin&seed=$seed'\");"; ?>
	<? echo "mm_menu_shora_pajoheshi.addMenuItem(\"تعريف جلسه شوراي پژوهشي\",\"location='jalase_shora.phtml?admin=$admin&seed=$seed&jalase_type=no_akhlagh'\");"; ?>	
	<? echo "mm_menu_shora_pajoheshi.addMenuItem(\"تعريف جلسه شوراي اخلاق\",\"location='jalase_shora.phtml?admin=$admin&seed=$seed&jalase_type=akhlagh'\");"; ?>
    <? echo "mm_menu_shora_pajoheshi.addMenuItem(\"جلسات شوراي پژوهشي مراکز\",\"location='jalase_shora_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_shora_pajoheshi.addMenuItem(\"جلسات شوراي دانشگاه\",\"location='jalase_shora_moavenat_list.phtml?admin=$admin&seed=$seed&jalase_type=no_akhlagh'\");"; ?>
    
	mm_menu_shora_pajoheshi.hideOnMouseOut=true;
    mm_menu_shora_pajoheshi.bgColor='#555555';
    mm_menu_shora_pajoheshi.menuBorder=0;
    mm_menu_shora_pajoheshi.menuLiteBgColor='#FFFFFF';
    mm_menu_shora_pajoheshi.menuBorderBgColor='#777777';
  }

 if (! window.mm_menu_dabirkhane)
  {
    window.mm_menu_dabirkhane = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    
    <? echo "mm_menu_dabirkhane.addMenuItem(\"ليست نامه ها\",\"location='letter_to_mojri_list.phtml?admin=$admin&seed=$seed'\");"; ?>
    mm_menu_dabirkhane.hideOnMouseOut=true;
    mm_menu_dabirkhane.bgColor='#555555';
    mm_menu_dabirkhane.menuBorder=0;
    mm_menu_dabirkhane.menuLiteBgColor='#FFFFFF';
    mm_menu_dabirkhane.menuBorderBgColor='#777777';
  }

if (! window.mm_menu_modiriat_karbaran)
  {

    window.mm_menu_modiriat_karbaran = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);    
    <? echo "mm_menu_modiriat_karbaran.addMenuItem(\"تعريف مدير گروه کارشناسي\",\"location='add_modir_karshenasan.phtml?admin=$admin&seed=$seed&user=karshenasi'\");"; ?>
    <? echo "mm_menu_modiriat_karbaran.addMenuItem(\"تعريف ناظر\",\"location='add_user.phtml?admin=$admin&seed=$seed&user=nazer'\");"; ?>
    <? echo "mm_menu_modiriat_karbaran.addMenuItem(\"تعريف مدير بخش مالي\",\"location='add_user.phtml?admin=$admin&seed=$seed&user=mali'\");"; ?>
    <? echo "mm_menu_modiriat_karbaran.addMenuItem(\"تعريف مدير بخش اخلاق\",\"location='add_user.phtml?admin=$admin&seed=$seed&user=akhlagh'\");"; ?>
    mm_menu_modiriat_karbaran.hideOnMouseOut=true;
    mm_menu_modiriat_karbaran.bgColor='#555555';
    mm_menu_modiriat_karbaran.menuBorder=0;
    mm_menu_modiriat_karbaran.menuLiteBgColor='#FFFFFF';
    mm_menu_modiriat_karbaran.menuBorderBgColor='#777777';

  }


if (! window.mm_menu_savabet)
  {
    window.mm_menu_savabet = new Menu("root",128,18,"Arial, Helvetica, sans-serif",12,"#FFFFFF","#000000","#000066","#FFCC00","right","middle",3,0,200,-5,7,true,true,true,0,true,true);
    <? echo "mm_menu_savabet.addMenuItem(\"متن ارسال طرح به دانشگاه\",\"location='main-content.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_savabet.addMenuItem(\"نوع طرح\",\"location='tarh-type.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_savabet.addMenuItem(\"نوع مطالعه\",\"location='tarh-type-1.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_savabet.addMenuItem(\"نوع طرح 1\",\"location='tarh-type-2.phtml?admin=$admin&seed=$seed'\");"; ?>

	<?// echo "mm_menu_savabet.addMenuItem(\"نوع نامه\",\"location='letter_type.phtml?admin=$admin&seed=$seed'\");"; ?>

	<? echo "mm_menu_savabet.addMenuItem(\"درجه علمي\",\"location='daraje-elmi.phtml?admin=$admin&seed=$seed'\");"; ?>
	<? echo "mm_menu_savabet.addMenuItem(\"مقطع پايان نامه\",\"location='maghta_payan_name.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_savabet.addMenuItem(\"تعريف نوع کارشناس\",\"location='karshenas_type.phtml?admin=$admin&seed=$seed'\");"; ?>

	<? echo "mm_menu_savabet.addMenuItem(\"تعريف دانشکده / مرکز\",\"location='add_daneshkade.phtml?admin=$admin&seed=$seed'\");"; ?>

	<? echo "mm_menu_savabet.addMenuItem(\"وضعيت طرح\",\"location='vaziat-tarh.phtml?admin=$admin&seed=$seed'\");"; ?>
		<? echo "mm_menu_savabet.addMenuItem(\"نوع حساب بانکي\",\"location='hesab_type.phtml?admin=$admin&seed=$seed'\");"; ?>

    <? //echo "mm_menu_savabet.addMenuItem(\"ثوابت چاپ\",\"window.open('print_statistics.phtml?admin=$admin&seed=$seed','_blank')\");"; ?>
    <? //echo "mm_menu_savabet.addMenuItem(\"ثوابت چاپ شناسنامه طرح\",\"window.open('print_shenasname_statistics.phtml?admin=$admin&seed=$seed','_blank')\");"; ?>   
    <?  echo "mm_menu_savabet.addMenuItem(\"محتواي صفحه اصلي\",\"location='main-content.phtml?admin=$admin&seed=$seed'\");"; ?>

    <? //echo "mm_menu_savabet.addMenuItem(\"مشخصات پست الکترونيک\",\"location='email_from.phtml?admin=$admin&seed=$seed'\");"; ?>
    <? echo "mm_menu_savabet.addMenuItem(\"Ranking\",\"location='ranking.phtml?admin=$admin&seed=$seed'\");"; ?>
   
       <?  echo "mm_menu_savabet.addMenuItem(\"اخبار\",\"location='news.phtml?admin=$admin&seed=$seed'\");"; ?>
   
       <?  echo "mm_menu_savabet.addMenuItem(\"توضيحات صورتجلسه\",\"location='sooratjalase.phtml?admin=$admin&seed=$seed'\");"; ?>

   mm_menu_savabet.hideOnMouseOut=true;
    mm_menu_savabet.bgColor='#555555';
    mm_menu_savabet.menuBorder=0;
    mm_menu_savabet.menuLiteBgColor='#FFFFFF';
    mm_menu_savabet.menuBorderBgColor='#777777';
  }

mm_menu_karshenasan.writeMenus();
mm_menu_tarhs.writeMenus();
mm_menu_tarhs_hsr.writeMenus();
mm_menu_shora_pajoheshi.writeMenus();
mm_menu_savabet.writeMenus();
mm_menu_modiriat_karbaran.writeMenus();
mm_menu_reports.writeMenus();
mm_menu_letter.writeMenus();
mm_menu_payannameha.writeMenus();
} // mmLoadMenus()
<!--

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

//-->
</script>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<script language="JavaScript" src="js/mm_menu.js"></script>
</head>




<BODY leftMargin=0 topMargin=0
_1/but1_eff.JPG','image_main_page/top_but_1_eff.jpg','images/but_1_eff.jpg','images/but_2_eff.jpg','images/but_3_eff.jpg','images/but_4_eff.jpg','images/but_5_eff.jpg')">
<CENTER>
<script language="JavaScript1.2">mmLoadMenus();</script>
<TABLE borderColor=black cellSpacing=0 cellPadding=0 width=93% bgColor=#ffffff
border=0 height="100%"><!--DWLayoutTable-->
  <tr>
    <TD height=117 colspan="2" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <!--DWLayoutTable-->
        <tr>
          <td height="19" colspan="3" background="img_data/top_1_01.jpg" style="font-size: 7pt; font-family: Tahoma; color: #666666">
			<span lang="fa">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</span>&nbsp;
			<span lang="fa">تاريخ :&nbsp; <span dir="rtl"><? echo today();?></span>&nbsp;&nbsp;&nbsp; ساعت :
			<? echo date("H:i"); ?></span></td>
          <td width="93" rowspan="2" valign="top"><img src="img_data/top_1_02.jpg" width="93" height="98"></td>
          <td width="108" rowspan="3" valign="top"><img src="img_data/top_1_03.jpg" width="108" height="117"></td>
          <td width="274" rowspan="3" valign="top"><img src="img_data/top_1_04.jpg" width="274" height="117"></td>
        </tr>
        <tr>
          <td width="46" height="79" valign="top"><img src="img_data/top_1_05.jpg" width="46" height="79"></td>
          <td width="155" valign="top"><img src="img_data/top_1_06.jpg" width="155" height="79"></td>
        <td width="100%" valign="top"><img src="img_data/top_1_07.jpg" width="100%" height="79"></td>
        </tr>
        <tr>
          <td height="19" colspan="4" valign="bottom" background="img_data/top_1_0888.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
			<span lang="fa">
				<?
						 $query="select * from modir_daneshkade where modir_username='$admin'";
						 
						 $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
						 $row_fetched=mysql_fetch_array($result);
						 if(strcmp($row_fetched["modir_type"],'4')!=0)
						 {
							echo "محيط کاري مدير سيستم";							
						 }
						 else
						   echo "محيط کاري معاون مديريت پژوهش";
   			   ?>

			</span></td>
          </tr>
        </table></TD>
    </tr>
	<tr>
    <TD width="100%" height="100%" valign="top"><!-- 651 -->
	<table width="100%" border="0" cellpadding="0" cellspacing="0">
      <!--DWLayoutTable-->
      <tr>
        <td width="100%" height="100%" align="center" valign="top"> <!-- 650 -->


  <?*/

}

//-----------------------------------------------------------------------

function footer_forms($admin,$seed)
{
	include("include/footer.phtml");
		exit();
?>

 </td>
      </tr>
    </table></TD>
    <TD width="150" valign="top" background="img_data/right_td_back.jpg">
        <table width="150" border="0" cellpadding="0" cellspacing="0" background="img_data/right_td_back.jpg" height="100%">
            <!--DWLayoutTable-->
            <tr>
              <td height="19" valign="top"><img src="img_data/top_2.jpg" width="150" height="19"></td>
            </tr>
			<tr>
              <td height="570" valign="top" align="center">
				<table width="150" border="0" cellpadding="0" cellspacing="0"  height="570">
                <!--DWLayoutTable-->
                <tr>
                  <td width="150" height="505" valign="top"  >
					<table border="0" width="140" height="725">
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_tarhs,-204,0,null,'spacer1')">
							<span lang="fa"><a href="#"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;طرحهاي تحقيقاتي</a><img src="img_data/spacer.gif" name="spacer1" ></span></td>
						</tr>
   						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_tarhs_hsr,-224,0,null,'spacer19')">
							<span lang="fa"><a href="#"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HSR طرحهاي تحقيقاتي </a><img src="img_data/spacer.gif" name="spacer19" ></span></td>
						</tr>
                        <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image23','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_mostaghel,-224,0,null,'spacer23')">
							<span lang="fa"><a href="#"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  مراکز مستقل </a><img src="img_data/spacer.gif" name="spacer23" ></span></td>
						</tr>
                        <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_payannameha,-224,0,null,'spacer72')">
							<span lang="fa"><a href="#"  >بررسي اخلاقي پايان نامه ها </a><img src="img_data/spacer.gif" name="spacer72" ></span></td>
						</tr>
                        
							<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right" >
							<span lang="fa"><a href=<? echo "\"old_tarhs.phtml?admin=$admin&seed=$seed\""; ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;طرح هاي قديمي </a></span></td>
						</tr>
                        <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"   onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_sms,-224,0,null,'spacer56')" >
							<span lang="fa"><a href="#"  >  پيام کوتاه</a><img src="img_data/spacer.gif" name="spacer56" ></span></td>
						</tr>
						 <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"    >
							<span lang="fa"><a href=<? echo "\"gozareshat_old.phtml?admin=$admin&seed=$seed\""; ?> >گزارشات نهايي تاييد نشده</a><img src="img_data/spacer.gif" name="spacer0506" ></span></td>
						</tr>
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right" >
							<span lang="fa"><a href=<? echo "\"karshenasan_add.phtml?admin=$admin&seed=$seed\""; ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;کارشناسان و ناظرين</a><img src="img_data/spacer.gif" name="spacer2" ></span></td>
						</tr>
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right" onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image10','','plat_6/but_3_eff.jpg',1);MM_showMenu(window.mm_menu_shora_pajoheshi,-204,0,null,'spacer3')">
							<span lang="fa"><a href="#" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;شوراي پژوهشي</a><img src="img_data/spacer.gif" name="spacer3" ></span></td>
						</tr>
							<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"doers.phtml?admin=$admin&seed=$seed\""; ?>>مجريان</a></span></td>
						</tr>

						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right" onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image11','','plat_6/but_4_eff.jpg',1);MM_showMenu(window.mm_menu_savabet,-204,0,null,'spacer4')">
							<span lang="fa"><a href="#" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ثوابت سيستم</a><img src="img_data/spacer.gif" name="spacer4" ></span></td>
						</tr>
						<tr> 
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_letter,-204,0,null,'spacer15')">
							<span lang="fa"><a href="#">دبيرخانه</a><img src="img_data/spacer.gif" name="spacer15" ></span></td>
						</tr>
                      <!--  	<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"confirm_letters.phtml?admin=$admin&seed=$seed\""; ?>>نامه کارشناسان جهت تاييد</a><img src="img_data/spacer.gif" name="spacer5" ></span></td>
						</tr>
							<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"your_letter_list.phtml?admin=$admin&seed=$seed\""; ?>>نامه هاي ارسالي شما</a><img src="img_data/spacer.gif" name="spacer5" ></span></td>
						</tr>
						-->
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_swapImage('Image8','','plat_6/but_1_eff.jpg',1);MM_showMenu(window.mm_menu_reports,-204,0,null,'spacer6')">
							<span lang="fa"><a href="#"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;گزارشات</a><img src="img_data/spacer.gif" name="spacer6" ></span></td>
						</tr>
						 <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"send_excel.phtml?admin=$admin&seed=$seed\""; ?>>ارسال فايل </a><img src="img_data/spacer.gif" name="spacer5" ></span></td>
						</tr>
                         <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"gant_correction.phtml?admin=$admin&seed=$seed\""; ?>>تصحيح در جدول گانت</a><img src="img_data/spacer.gif" name="spacer5" ></span></td>
						</tr>
						 <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"correction.phtml?admin=$admin&seed=$seed\""; ?>>تصحيح در نرم افزار </a><img src="img_data/spacer.gif" name="spacer5" ></span></td>
						</tr>
							<?
						 $query="select * from message_to_admin where (message_to='admin' ) and readed='0' ";
 
 						 $result11=mysql_query($query) or die("error in selecting data from letter_to_mojri");
                         if(mysql_num_rows($result11) > 0)
                           $aa="<sup><font	color=red>New Message</font></sup>";
                         else
						   $aa="";  
						?>
						
							 <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"search_tarh.phtml?admin=$admin&seed=$seed\""; ?>> جستجوي طرح</a></span></td>
						</tr>  
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"file_sharing.phtml?admin=$admin&seed=$seed\""; ?>> ارسال فايل به همکاران</a></span></td>
						</tr>  
						 <tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"karshenasan_messages.phtml?admin=$admin&seed=$seed\""; ?>><? echo $aa; ?>پيام کارشناسان</a></span></td>
						</tr>  
							<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"informatics.phtml?admin=$admin&seed=$seed\""; ?>>اطلاع رساني</a></span></td>
						</tr>
						<?
						 $query="select * from modir_daneshkade where modir_username='$admin'";
						 
						 $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
						 $row_fetched=mysql_fetch_array($result);
						 if(strcmp($row_fetched["modir_type"],'4')!=0)
						 {
						?>
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"add_assistant.phtml?admin=$admin&seed=$seed\""; ?>>تعريف معاون</a></span></td>
						</tr>
						<?
						 }
						 else
						 {
						?>
					<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right"  onMouseOut="MM_swapImgRestore();MM_startTimeout();" onMouseOver="MM_showMenu(window.mm_menu_modiriat_karbaran,-204,0,null,'spacer50')">
							<span lang="fa"><a href="#">مديريت کاربران</a><img src="img_data/spacer.gif" name="spacer50" ></span></td>
						</tr> 
					
						<?
						 }
						?>
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"chg_pass.phtml?admin=$admin&seed=$seed\""; ?>>تغيير رمز عبور</a></span></td>
						</tr>
						<tr>
							<td  background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"change_cod_tarh.phtml?admin=$admin&seed=$seed\""; ?>>تغيير کد طرح</a></span></td>
						</tr>
							<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"change_mojri_tarh.phtml?admin=$admin&seed=$seed\""; ?>>تغيير نام مجري طرح</a></span></td>
						</tr>
						<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"user_activities.phtml?admin=$admin&seed=$seed\""; ?>>فعاليتها</a></span></td>
						</tr>
				    	<tr>
							<td background="img_data/buts_back.jpg" style="font-size: 8pt; font-family: Tahoma; color: #666666" align="right">
							<span lang="fa"><a href=<? echo "\"logout.phtml?admin=$admin&seed=$seed\""; ?>>خروج</a></span></td>
						</tr>

					</table>
				  </td>
                </tr>
              </table><span class="tahoma1"><b>F7 = تغيير زبان</b></span>
<SCRIPT language=JavaScript>var clocksize=100;</SCRIPT>
                  <SCRIPT src="js/clock.js"></SCRIPT>
			  </td>
            </tr>
			<tr>
              <td  width="150">&nbsp;</td>
            </tr>
        </table>

		</TD>
  	</tr>
	<tr>
	  <TD height=27 colspan="2" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="img_data/down_td_back.jpg">
            <!--DWLayoutTable-->
            <tr>
              <td width="164" height="24" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="img_data/down_td_back_2.jpg">
                  <!--DWLayoutTable-->
                  <tr>
                    <td width="7" height="24"></td>
                    <td width="136" valign="top"><a href="http://www.rahpouyanco.com" target="_blank"><img src="img_data/rah_pic_down.jpg" width="136" height="24" border="0"></a></td>
                    <td width="7"></td>
                    <td width="14" valign="top"><img src="img_data/down_td_pic.jpg" width="14" height="24"></td>
                  </tr>
              </table></td>
              <td width="631" style="font-size: 7pt; font-family: Tahoma; color: #E8EAF6" align="center">
				<p align="right">
				<span lang="fa">راهنما&nbsp; |&nbsp; لينكهاي مفيد&nbsp; |&nbsp; </span>English&nbsp;&nbsp;&nbsp;&nbsp; </td>
              <td width="5" rowspan="2" valign="top"><img src="img_data/down_td_back.jpg" width="1" height="24"></td>
            </tr>
            <tr>
              <td height="3"></td>
              <td></td>
            </tr>
      </table></TD>
    </tr>
</TABLE>
</CENTER>
</BODY></HTML>

   <?

}

//---------------------------------------------------------------------------------------


function admin_type($admin)     // 0 == admin daneshkade  1== admin kol
{
  $query="select * from modir_daneshkade where modir_username=\"$admin\"";
  $result=mysql_query($query) or die("Error in selectiong data from modir daneshkade");
  if(mysql_num_rows($result) > 0)
  {
   $row_fetched=mysql_fetch_array($result);
   return $row_fetched["modir_type"];
  }
  else
    return -1;
  
  
}


//-----------------------------------------------------------------------


function pubshowpages($link,$current,$PageCountShows,$Reccount,$startw,$endw,$RecPerPage,$username,$rand,$args,$width,$bgcolor)
{


  if($RecPerPage >=1000)
    
	{
	  $current=1;
      echo"<table width=\"$width\"   border=0 align=\"center\" valign=\"center\"  cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"$bgcolor\">";
	  $i=0;

 	  echo "<tr>";
      echo "<td align='center'>";
	  echo "<a style=\"text-decoration: none\" href=$link?admin=$username&seed=$rand&$args><font face=\"arial\" size=2 color=green></font>";
      echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
      echo "-";
      echo "</a>";
      echo "</td>";
      echo "</tr>";
      echo "<table>";
      return;
      
      
	}
     $PageCNT = ceil($Reccount/$RecPerPage);
     if($PageCNT <=1 )
       return;
     if(($startw==0 && $endw==0) )
     {
      $startw=1;
      if($PageCNT < $PageCountShows )
        $endw = $PageCNT;
      else
        $endw = $PageCountShows;
     }
     else    //line 50
     {
      if($PageCNT < $PageCountShows)
      {
        $startw = 1;
        $endw = $PageCNT;
      }
      else
      {
        //   fgfdgdfdf
        if( ($current-$startw) > floor(($endw-$startw)/2) )  //line60
        {
         if( ($endw+ceil(($endw-$startw)/2)) < $PageCNT )
         {
            $tmpvar = $startw;
            $startw += ceil(($endw-$startw)/2);
            $endw += ceil(($endw-$tmpvar)/2);
         }
         else
         {
           if($endw < $PageCNT)
           {
             $startw+=($PageCNT-$endw);
             $endw+=($PageCNT-$endw);
           }
         }
        }
        else
        {
          if( ($current-$startw) < ceil(($endw-$startw)/2) )
          {
            if(($startw-ceil(($endw-$startw)/2)) > 1  )
            {
               $tmpvar = $startw;
               $startw-=ceil(($endw-$startw)/2);
               $endw-=ceil(($endw-$tmpvar)/2);
            }
            else
            {
               $tmpvar = $startw;
               $startw=1;

               if( $PageCNT > $PageCountShows )
                  $endw = $PageCountShows;
               else
                  $endw=$PageCNT;
             }
          }
        }
     }
    }

if ( $current == $PageCNT )
{
  $endw=$PageCNT;
  if ($PageCountShows < $PageCNT )
    $startw = ($PageCNT+1) - $PageCountShows;
  else
    $startw = 1 ;


}

 echo"<table width=\"$width\"   border=0 align=\"center\" valign=\"center\"  cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"$bgcolor\">";
 $i=0;

 echo "<tr>";

 echo "<td width = 20% align=left dir=\"rtl\">";
 echo "<p align=\"center\" class=\"tahoma1\">";
 echo "$Reccount مورد يافت شد";
 echo "</p>";
 echo "</td>";
 echo "<td width = 60% align=center>";

 if($PageCNT>2 &&  $current > 1 )
 {
    printf("<a style=\"text-decoration: none\" href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\"size=3 color=green></font>",$link,1,0,0,$username,$rand,$args);
    echo "<img src=\"image/fullleft.gif\" border=\"0\">";
    echo "</a>";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }
 else
 {
    echo "<img src=\"image/fullleft.gif\" border=\"0\">";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
  
 }


 if($current > 1 )
 {
    printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\"size=3 color=green></font>",$link,$current-1,$startw,$endw,$username,$rand,$args);
    echo "<img src=\"image/left.gif\" border=\"0\">";
    echo "</a>";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }
else
 {
    echo "<img src=\"image/left.gif\" border=\"0\">";
    echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
 }


 if($PageCNT>1)
 {
  for($i=$startw ;$i<=$endw;$i++)
  {
   if($i==$current)
      printf("<font face=\"arial\" size=2 color=green><spawn align=\"center\" class=\"tahoma1\"><b>&nbsp;%s&nbsp;</b></spawn></font>",$i);
   else
      printf("<a style=\"text-decoration: none\" href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=blue><spawn align=\"center\" class=\"tahoma1\"><b>&nbsp;%s&nbsp;</b></spawn></font></a>",$link,$i,$startw,$endw,$username,$rand,$args,$i);
  }
 }

 if(  $current < $PageCNT )
 {
   printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$current+1,$startw,$endw,$username,$rand,$args);
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/right.gif\" border=\"0\">";
   //echo "Next";
   echo "</a>";
 }
 else
 {
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/right.gif\" border=\"0\">";
 }

 if($PageCNT>2 && $current < $PageCNT )
 {
   printf("<a style=\"text-decoration: none\"href=%s?current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$PageCNT,$startw,$endw,$username,$rand,$args);
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/fullright.gif\" border=\"0\">";
   echo "</a>";
    if($RecPerPage <1000)
    {
      printf("<a style=\"text-decoration: none\"href=%s?showall=1&current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$PageCNT,$startw,$endw,$username,$rand,$args);
      echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
      echo "+";
      echo "</a>";
     }
	else
	{
	  $current=1;
	  printf("<a style=\"text-decoration: none\"href=%s? current=%d&startw=%d&endw=%d&admin=%s&seed=%s&%s><font face=\"arial\" size=2 color=green></font>",$link,$PageCNT,$startw,$endw,$username,$rand,$args);
      echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
      echo "+";
      echo "</a>";
	}
	
	  
 }
 else
 {
 
   echo "<spawn align=\"center\" class=\"tahoma1\">&nbsp;</spawn>";
   echo "<img src=\"image/fullright.gif\" border=\"0\">";
 }


 echo"</td>";
 echo "<td width = 20% align=right>";
 echo "<p align=\"center\" class=\"tahoma1\">";
 echo "صفحه $current از $PageCNT";

 echo "</p>";
 echo "</td>";

 echo"</tr>";
 echo"</table>";


}

//-----------------------------------------------------------------------

function check_tarh_parts($cod_tarh)     // 0 == admin daneshkade  1== admin kol
{
  $check_tarh_string="";
  
  $query="select * from daneshjo_tarh where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:دانشجويان"."<br>";


  $query="select * from hamkar_tarh where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:همکاران"."<br>";
    
    
  $query="select * from hazine_azmayesh where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:هزينه آزمايش"."<br>";
 
  $query="select * from hazine_personnel where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:هزينه پرسنل"."<br>";
 
  $query="select * from hazine_safar where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:هزينه سفر"."<br>";
  
  $query="select * from jadval_zarayeb where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص: جدول ضرايب"."<br>";
 
  $query="select * from ravesh_ejra where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ناقص:  روش اجرا"."<br>";

 $query="select * from sayer_hazine where cod_tarh='$cod_tarh'";
  $result=mysql_query($query) or die("Error in selecting data");  
  if(mysql_num_rows($result) <=0 )
    $check_tarh_string=$check_tarh_string."ساير هزينه ها :ناقص"."<br>";
     
 return $check_tarh_string;    

}

//-----------------------------------------------------------------------

function message_show($message,$color)     // 0 == admin daneshkade  1== admin kol
{

 echo "<table border=\"0\" width=\"100%\" height=\"10%\">";
 echo "<tr>";
 echo "<td width=\"100%\"  align=\"center\" ><font face=\"tahoma\" size=\"2\" color=\"$color\">$message</font></td>";
 echo "</tr>";
 echo "</table>";

}

//-----------------------------------------------------------------------
function set_log($action,$admin,$date)     // 0 == admin daneshkade  1== admin kol
{
   $query="insert into log set username=\"$admin\" , action=\"$action\", date=\"$date\"";
   $result=mysql_query($query) or die("Error in inserting data into log file");
}



//-------------------------------------------------------------------

function BaseFromMiladiDate($mldyear , $mldmonth , $mldday )
{
  $PrevMonthDayMld = array(0,31,59,90,120,151,181,212,243,273,304,334);
  $iDaySum = 0 ;
  $iNewDateElapsed =0 ;
  $iBaseYear = 1996 ;
  $iBaseDateElapsed = 79 ;
  $iNewDateElapsed = ($mldday -1 ) + $PrevMonthDayMld[$mldmonth-1];
  if ( (($mldyear % 4 ) == 0 ) && ( $mldmonth > 2))
     $iNewDateElapsed++;

  $iDaySum = $iNewDateElapsed - $iBaseDateElapsed +($mldyear-$iBaseYear) *365 +(int)(($mldyear -$iBaseYear ) / 4 );

  if ((($mldyear - $iBaseYear) % 4 ) != 0 )
     $iDaySum = $iDaySum+1;
  return $iDaySum;
}
//---------------------------------------------------------------------

function hijricalender ( $year , $month , $day )
{
  $PrevMonthDayHjr = array(0,31,62,93,124,155,186,216,246,276,306,336);
  if ( $year < 1995 || $month < 1 || $month > 12 || $day > 31 || $day < 1 )
    return 0;
  $daysum = BaseFromMiladiDate($year , $month , $day );
  $iaddyear=0;
  while ($daysum >0 )
  {
      $daysum = $daysum -365;
      if (($iaddyear % 4 ) == 0 )
        $daysum--;
      $iaddyear++;
  }
  if ( $daysum <0 )
  {
      $iaddyear--;
      $daysum = $daysum+365;
      if (($iaddyear % 4 ) == 0 )
        $daysum++;
  }
  $itodayyear = 1375+$iaddyear;
  $itodaymonth=1;
  while ( $daysum >= $PrevMonthDayHjr[$itodaymonth])
  {
      $itodaymonth++;
      if( $itodaymonth ==12 )
        break;
  }
  $daysum=$daysum - $PrevMonthDayHjr[$itodaymonth-1];
  $itodayday = 1 + $daysum;
  $isodate = sprintf("%04d/%02d/%02d",$itodayyear ,$itodaymonth, $itodayday);
  return  $isodate;
}
//-------------------------------------------------------------------

function enum2fnum($englishnum)
{
  $return1 = str_replace("1", "ہ", $englishnum);
  $return2 = str_replace("2", "×", $return1);
  $return3 = str_replace("3", "à", $return2);
  $return4 = str_replace("4", "â", $return3);
  $return5 = str_replace("5", "ç", $return4);
  $return6 = str_replace("6", "è", $return5);
  $return7 = str_replace("7", "é", $return6);
  $return8 = str_replace("8", "ê", $return7);
  $return9 = str_replace("9", "ë", $return8);
  $return0 = str_replace("0", "ô", $return9);
  $return11 = str_replace("ہ", "&#1777;", $return0);
  $return12 = str_replace("×", "&#1778;", $return11);
  $return13 = str_replace("à", "&#1779;", $return12);
  $return14 = str_replace("â", "&#1780;", $return13);
  $return15 = str_replace("ç", "&#1781;", $return14);
  $return16 = str_replace("è", "&#1782;", $return15);
  $return17 = str_replace("é", "&#1783;", $return16);
  $return18 = str_replace("ê", "&#1784;", $return17);
  $return19 = str_replace("ë", "&#1785;", $return18);
  $return20 = str_replace("ô", "&#1776;", $return19);
  $return21 = str_replace(":", "<font compset size 3><b>:</b></font>", $return20);
  return $return21;

}

//-------------------------------------------------------------------

function send_mail_tarh($cod_tarh)
{


 $besme = "style=\"font-family: tahoma; font-size: 10\"";
 $titr_asli =  "style=\"font-family: tahoma; font-size: 10\"";
 $porseshname =  "style=\"font-family: tahoma; font-size: 10\"";
 $anavin_asli =  "style=\"font-family: tahoma; font-size: 10\"";
 $anavin_farii_text =  "style=\"font-family: tahoma; font-size: 10\"";
 $anavin_farii =  "style=\"font-family: tahoma; font-size: 10\"";
 $titr_anavin_farii =  "style=\"font-family: tahoma; font-size: 10\"";
 $jadval_title =  "style=\"font-family: tahoma; font-size: 10\"";
 print_title($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_globals($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_mojrian($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_daneshjoyan($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_hamkaran($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_modir_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_modir_mali_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_body_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_ravesh_ejra($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_jadval_zamani($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_page_break();
 print_hazineha($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);

}

//-------------------------------------------------------------------


function send_letter_to_mojri($mojri_name,$mojri_family,$tarh_title_english,$tarh_title_farsi,$band_azad,$cod_tarh,$content_letter_type)
{
?>
<META http-equiv=content-type content=text/html;charset=utf-8>
<table id="Table_00" border="0" width="100%" height="100%">
  <tr>
    <td width="34%" align="center" height="586"></td>
    <td width="800" align="center" height="586">

<!-- Start Main Table (Table_01) here -->
    <table id="Table_01" class=TableStyle0 dir=ltl style="BORDER-COLLAPSE: collapse" borderColor=#336699 border="0" width="800" height="586" cellspacing="0" cellpadding="0">
      <tr>
        <td width="50" height="20">
	      </td>
        <td width="350" height="20">
	      </td>
        <td width="350" height="20">
	      </td>
        <td width="50" height="20">
	      </td>
      </tr>
      <tr>
        <td width="50" height="58">
	      </td>
        <td width="350" height="58">
	      </td>
        <td width="350" height="58">
          <p align="right">
          <img border="0" src="mui.ac.ir/researches/admin/images/MUI-Logo04b.jpg" width="80" height="120">
	      </td>
        <td width="50" height="58">
	      </td>
      </tr>
      <tr>
        <td width="50" height="25">
	      </td>
	      
	      <?
           $First_mojri_name = $mojri_name."&nbsp;".$mojri_family;
	      ?>
        <td width="350" height="25" align="right">
          <? echo $First_mojri_name; ?>
	      </td>
        <td class=NormalText1 width="350" height="25" align="right">
          سركار خانم دكتر / جناب آقاى دكتر
	      </td>
        <td width="50" height="25">
	      </td>
      </tr>
      <tr>
        <td width="50" height="25">
	      </td>
        <td width="350" height="25" align="right">
	      </td>
        <td class=NormalText1 width="350" height="25" align="right">
          با سلام
	      </td>
        <td width="50" height="25">
	      </td>
      </tr>
      <tr>
        <td width="50" height="25">
	      </td>
        <td width="350" height="25" align="right">
	      </td>
        <td class=NormalText1 width="350" height="25" align="right">
          احتراماً به استحضار مىرساند كه طرح
          پيشنهادى شما تحت عنوان
	      </td>
        <td width="50" height="25">
	      </td>
      </tr>
      <tr>
        <td width="50" height="100">
	      </td>
        <td width="700" height="100" align="right" colspan="2">
          <?
			echo $tarh_title_farsi."<br>".$tarh_title_english;
		  ?>
	      </td>
        <td width="50" height="100">
	      </td>
      </tr>
      <tr>
        <td width="50" height="35">
	      </td>
        <td class=NormalText1 width="700" height="35" align="right" colspan="2">
          <?
			echo $content_letter_type."<br>".$band_azad;
		  ?>
	      </td>
        <td width="50" height="35">
	      </td>
      </tr>
      <tr>
        <td width="50" height="35">
	      </td>
        <td class=NormalText1 width="700" height="35" align="right" colspan="2">
	      </td>
        <td width="50" height="35">
	      </td>
      </tr>
      <tr>
        <td width="50" height="35">
	      </td>
        <td class=NormalText1 width="350" height="35" align="right">
          <?
			 echo $chairman_of_letter;
		  ?>
	      </td>
        <td width="350" height="35" align="right">
	      </td>
        <td width="50" height="25">
	      </td>
      </tr>
      <tr>
        <td width="50" height="60">
        </td>
        <td width="350" height="60">
        </td>
        <td width="350" height="60">
        </td>
        <td width="50" height="60">
        </td>
      </tr>
    </table> <!-- Finish Main Table (Table_01) here -->
   </td>
   <td width="34%" align="center" height="586"></td>
  </tr>
</table><!-- Finish Table_00 here -->


<?
}


//-------------------------------------------------------------------------------

function today()
{

		$mydate=date("Y-m-d");
		$endyear=substr($mydate,0,4);
		$endmon=substr($mydate,5,2);
		$endday=substr($mydate,8,2);
		$todaydate= hijricalender($endyear,$endmon,$endday);
		
		return $todaydate;
}

?>
