
<?php

     include("include/include.phtml");
     header_forms($admin,$seed);
	 include("include/database-connect.phtml");
     include("include/styles.phtml");
   /*  $query="select * from daneshkade where cod_daneshkade=\"$daneshkade\"";
     $result=mysql_query($query) or die("Error in selectiong data from daneshkade");
     $row_fetch_daneshkade=mysql_fetch_array($result);
     echo "<head>";
     echo "<title>ويرايش مديران دانشکده ".$row_fetch_daneshkade["daneshkade_name"]."</title>";
     echo "</head>";*/
     echo "<br>";
?>



<!-- <table border="0" width="500" cellspacing="0" cellpadding="9" >
<tr>
<td width="100%" align="center" class="tahoma1">
<?  // echo "ويرايش مديران دانشکده ".$row_fetch_daneshkade["daneshkade_name"]; ?>
</td>
</tr>
</table> -->



<TABLE cellSpacing="0" cellPadding="0" width="500" border="0">
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/title-user-define.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>



<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<tr>
<td >
<?

$status="";
if(isset($action))
{
  if (strcmp($action,"add_admin")==0)
  {

      if(strlen(trim($admin_dan_name)) > 0  &&   strlen(trim($admin_dan_family)) > 0  && strlen(trim($admin_dan_username)) > 0 && strlen(trim($modir_payanname_name )) > 0  &&  strlen(trim($moaven_or_daneshjoyee)) > 0 && strlen(trim($admin_dan_email)) > 0 && strlen(trim($admin_dan_pass)) > 0 && strlen(trim($admin_dan_repass)) > 0 && strcmp(trim($admin_dan_pass),trim($admin_dan_repass))==0  && strstr($admin_dan_email, '@') && !strstr($admin_dan_username,'@') )
    {
      $query="select * from modir_daneshkade where modir_username=\"$admin_dan_username\"";

      $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");

      if ( mysql_num_rows($result) <= 0 )
      {
        $query="insert into modir_daneshkade set  moaven_or_daneshjoyee='$moaven_or_daneshjoyee', modir_english_name='$admin_dan_english_name' ,modir_english_family='$admin_dan_english_family', modir_username='$admin_dan_username', cod_daneshkade = '$daneshkade', modir_name='$admin_dan_name', modir_family = '$admin_dan_family', modir_email ='$admin_dan_email' , modir_tel ='$admin_dan_tel' , modir_fax ='$admin_dan_fax', modir_mobile ='$admin_dan_mobile', password='$admin_dan_pass',modir_type =0,modir_payanname_name='$modir_payanname_name',email_view_able='$email_view_able',phone_view_able='$phone_view_able',mobile_view_able='$mobile_view_able' ";

        $result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
            $modir_name='';
			$modir_family='';
			$modir_username='';
			$daneshjooei_type='';
			$modir_email='';
			$modir_payanname_name='';
			$moaven_or_daneshjoyee='';
			$modir_dan_fax='';
			$modir_dan_tel='';
			$modir_dan_mobile='';
			$email_view_able='';
			$phone_view_able='';
			$mobile_view_able='';
      }
      else
       $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }
  
  if (strcmp($action,"delete_admin_dan")==0)
  {
    if(strlen($delete_id) > 0 )
    {
      $query="delete from modir_daneshkade where cod_modir=\"$delete_id\"";
      $result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
    }
  }
if (strcmp($action,"edit_modir")==0)
  {
    if(strlen($cod_modir) > 0 )
    {
      $query="update  modir_daneshkade set moaven_or_daneshjoyee='$moaven_or_daneshjoyee', modir_english_name='$admin_dan_english_name' ,modir_english_family='$admin_dan_english_family', modir_username='$admin_dan_username', cod_daneshkade = '$daneshkade', modir_name='$admin_dan_name', modir_family = '$admin_dan_family', modir_email ='$admin_dan_email' , modir_tel ='$admin_dan_tel' , modir_fax ='$admin_dan_fax', modir_mobile ='$admin_dan_mobile', modir_tel ='$admin_dan_tel' , modir_fax ='$admin_dan_fax', modir_mobile ='$admin_dan_mobile',modir_type =0,modir_payanname_name='$modir_payanname_name',email_view_able='$email_view_able',phone_view_able='$phone_view_able',mobile_view_able='$mobile_view_able' where cod_modir=\"$cod_modir\"";
      $result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
    $modir_name='';
	$modir_family='';
	$modir_username='';
	$daneshjooei_type='';
	$modir_email='';
	$modir_payanname_name='';
	$moaven_or_daneshjoyee='';
	$modir_dan_fax='';
	$modir_dan_tel='';
	$modir_dan_mobile='';
	$email_view_able='';
	$phone_view_able='';
	$mobile_view_able='';
    }
  }
}

if(strcmp($action,"edit")==0){
	$query="select * from modir_daneshkade where cod_modir='$username'";
	$result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
	$row_fetched=mysql_fetch_array($result);
	$modir_name=$row_fetched['modir_name'];
	$modir_english_name=$row_fetched['modir_english_name'];
	$modir_family=$row_fetched['modir_family'];
	$modir_english_family=$row_fetched['modir_english_family'];
	$modir_username=$row_fetched['modir_username'];
	$daneshjooei_type=$row_fetched['daneshjooei_type'];
	$modir_email=$row_fetched['modir_email'];
	$modir_payanname_name=$row_fetched['modir_payanname_name'];
	$moaven_or_daneshjoyee=$row_fetched['moaven_or_daneshjoyee'];
	$email_view_able=$row_fetched['email_view_able'];
	$phone_view_able=$row_fetched['phone_view_able'];
	$mobile_view_able=$row_fetched['mobile_view_able'];
	$admin_dan_mobile=$row_fetched['modir_mobile'];
	$modir_dan_tel=$row_fetched['modir_tel'];
	$modir_dan_fax=$row_fetched['modir_fax'];
	
}


?>



<?
if(strcmp($action,"edit")==0)
    echo "<form name=\"edit_modir_form\" method=\"post\"  action=\"$PHP_SELF?action=edit_modir&admin=$admin&seed=$seed&daneshkade=$daneshkade&cod_modir=$username\">";
else
    echo "<form name=\"add_admin_daneshkade\" method=\"post\"  action=\"$PHP_SELF?action=add_admin&admin=$admin&seed=$seed&daneshkade=$daneshkade\">"; ?>
<table border="0" width="490">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>


  <tr>
    <td width="25%"><input type="text" name="admin_dan_name"  class="edit-user"  dir=RTL value="<?echo $modir_name;?>"  ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام </td>
  </tr>
   <!--   <tr>
    <td width="25%"><input type="text" name="admin_dan_english_name" value="<?echo $modir_english_name;?>" class="edit-user" ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>(نام (انگليسي </td>
  </tr>
  -->
  <tr>
    <td width="25%"><input type="text" name="admin_dan_family"  class="edit-user"  value="<?echo $modir_family;?>" dir=RTL   ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>
<!-- 
  <tr>
    <td width="25%"><input type="text" name="admin_dan_english_family" value="<?echo $modir_english_family;?>" class="edit-user"  ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>(نام خانوادگي (انگليسي</td>
  </tr>
 -->
  <tr>
    <td width="25%"><input type="edit" name="admin_dan_username" value="<?echo $modir_username;?>" class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام کاربري</td>
  </tr>
    <tr>
    <td width="25%"><select size="1"    name="moaven_or_daneshjoyee" class="edit-user" dir="rtl">
    <?if($moaven_or_daneshjoyee==0)
    	$select="selected";
    	else 
    	$select="";
    ?>
    <option value="0" <?php echo  $select;?> class="tahoma1">معاون پژوهشي دانشکده / مرکز </option>
    <?if($moaven_or_daneshjoyee==1)
    	$select="selected";
    	else 
    	$select="";
    ?>
    <option value="1" <?php echo  $select;?> class="tahoma1">مديريت پايان نامه ها</option>

    </select>
    </td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نوع کاربر</td>
  </tr>
  
  <tr>
    <td width="25%"><input type="text" name="modir_payanname_name" value="<?echo $modir_payanname_name;?>" class="edit-user" ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام دريافت کننده پايان نامه</td>
  </tr>
  <!-- 
  <tr>
    <td width="25%"><select size="1"    name="danehjooei_type" class="edit-user" dir="rtl">
    <option value="0" class="tahoma1">همه موارد</option>
    <option value="1" class="tahoma1">دکتري عمومي،تخصصي،فوق تخصص،mph </option>
    <option value="2" class="tahoma1">کارشناسي ارشد،phd</option>

    </select>
    </td>
    <td width="25%" class="tahoma1">نوع آموزشي</td>
  </tr>
   -->
  <tr>
	<?if($email_view_able=="1")
    	$select="checked";
    	else 
    	$select="";
    ?>
    <td width="25%"><input type="text" name="admin_dan_email" value="<?echo $modir_email;?>" class="edit-user" ><input type="checkbox" <?echo $select;?> name="email_view_able" value="1"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
  <?if($phone_view_able=="1")
    	$select="checked";
    	else 
    	$select="";
    ?>
  <tr>
  
    <td width="25%"><input type="text" name="admin_dan_tel"  class="edit-user"><input type="checkbox" <?echo $select;?> name="phone_view_able" value="1"></td>
    <td width="25%" class="tahoma1">تلفن</td>
  </tr>
  <?if($mobile_view_able=="1")
    	$select="checked";
    	else 
    	$select="";
    ?>
  <tr>
  
    <td width="25%"><input type="text" name="admin_dan_mobile"  class="edit-user"><input type="checkbox" <?echo $select;?> name="mobile_view_able" value="1"></td>
    <td width="25%" class="tahoma1">موبايل</td>
  </tr>
  <tr>
    <td width="25%"><input type="text" name="admin_dan_fax"  class="edit-user"></td>
    <td width="25%" class="tahoma1">فکس</td>
  </tr>
  <? if(strcmp($action,"edit")!=0){?>
  <tr>
    <td width="25%"><input type="password" name="admin_dan_pass"  class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>کلمه عبور</td>
  </tr>
  <tr>
    <td width="25%"><input type="password" name="admin_dan_repass"  class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>تکرار کلمه عبور</td>
  </tr>
  <?}?>
  <tr>
    <td width="50%" colspan="2" align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
  

</table>
</td>
</tr>

</table>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="add_daneshkade.phtml?<?echo "admin=$admin&seed=$seed&daneshkade=$daneshkade" ?>" >اضافه کردن دانشکده</a></td>
</tr>
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><span class="star-message">توجه :نام کاربري بايد فاقد @ باشد</span></td>
</tr>

</table>


 <?
   $query="select * from modir_daneshkade where cod_daneshkade=\"$daneshkade\" and modir_type='0'";
   $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
     echo "<td  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">کلمه عبور</p></td>";
    echo "<td    height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نوع کاربر</p></td>";

echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حذف</p></td>";
    echo "<td    height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ويرايش</p></td>";
    echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام خانوادگي</p></td>";
    echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام</p></td>";
    echo "<td     height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام کاربري</p></td>";
     echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    $cod_modir=$myrow_fetched["cod_modir"];
	 $moaven_or_daneshjoyee=$myrow_fetched["moaven_or_daneshjoyee"];

    echo "<tr bgcolor=\"$color\">";
     echo "<td  ><p align=\"center\"><a href=\"change_users_password.phtml?admin=$admin&seed=$seed&db=modir_daneshkade&username=".$cod_modir."&user_field=cod_modir\" ><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
	
	if(strcmp(trim($moaven_or_daneshjoyee),'0')==0)
       $moaven_or_daneshjoyee_dsc="معاون پژوهشي د/م";
	else
       $moaven_or_daneshjoyee_dsc="مسئول طرح هاي دانشجويي";

    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$moaven_or_daneshjoyee_dsc."</p></td>";
	
    echo "<td  ><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_admin_dan.phtml?mainwindow=admin_daneshkade.phtml&admin=$admin&seed=$seed&daneshkade=$daneshkade&action=delete_daneshkade&delete_id=".$myrow_fetched["cod_modir"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td  ><p align=\"center\"><a href=\"admin_daneshkade.phtml?admin=$admin&seed=$seed&action=edit&username=".$cod_modir."&user_field=cod_modir&daneshkade=$daneshkade\" ><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";

    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".substr($myrow_fetched["modir_family"],0,18)."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".substr($myrow_fetched["modir_name"],0,18)."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["modir_username"]."</p></td>";
     echo "</tr>";
   }
 
   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>


