<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");


  $query="select * from tarh where cod_tarh='$cod_tarh' ";
 // echo $query;
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];

  $query="select * from send_article where cod_tarh='$cod_tarh' ";
 // echo $query;
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
 // $tarh_name = $row_fetched["tarh_title_farsi"];
  $noavari= $row_fetched["noavari"];
  $natayej_tarh_kharej_daneshgah= $row_fetched["natayej_tarh_kharej_daneshgah"];
  $tolid= $row_fetched["tolid"];
  $natayej_tarh_dar_modiriyat= $row_fetched["natayej_tarh_dar_modiriyat"];
   //echo $query;
   //echo "<br>";
  // $query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";

  // $result=mysql_query($query) or die("Error in selecting data from tarh");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
?>

<TABLE cellSpacing=0  width="90%" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center  class="tahoma1"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<?

    echo "<table border=\"0\" width=\"90%\"  cellspacing=\"1\" cellpadding=\"1\" >";
    $color="PALETURQUOISE";
    //$row_fetched=mysql_fetch_array($result);
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$noavari."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">نوآوري ، اكتشاف، اختراع ثبت شده و بومي‌سازي فناوري</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$natayej_tarh_kharej_daneshgah."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استفاده از نتايج طرح تحقيقاتي توسط مشتريان خارج از دانشگاه</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$tolid."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">توليد در مقياس انبوه شده و يا در صنايع دارويي، غذايي، تجهيزات پزشكي و مواد شوينده، آرايشي و بهداشتي</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$natayej_tarh_dar_modiriyat."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">استفاده از نتايج طرح در مديريت خدمات بهداشتي، درماني، آموزشي و پژوهشي يا در جهت بهبود شيوه‌هاي زندگي مردم</td>";
    echo "</tr>";
    
   
    echo "</table>";
   }
?>
 <table border="0" width="500">
<tr>
    <td width="100%"  align="center" class="tahoma1"><a style="text-decoration:none" href="finished.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
</tr>

</table>
 <?
 	footer_forms($admin,$seed);
 ?>