<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");

echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";

$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
 
  $modir_caution=' 1 ';  
  
  
//confirm_tarh=1
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
    
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if ( ! isset($tarh_year))
    $tarh_year = '-1';




if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

//echo $tarh_year;
if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($action))
 {
 if(strcmp($action,"del")==0)
  {
    
     $query="delete from tarh where cod_tarh=\"$delete_id\"";
     
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from shora_tarh_vaziat where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from sayer_hazine where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from ravesh_ejra where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from mojri_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from letter_to_mojri where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from karshenasan_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from jadval_zarayeb where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_safar where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_personnel where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_azmayesh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hamkar_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from fhrest_vasayel_kharid where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from daneshjo_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $action=". طرح با کد مقابل حذف شد"."<br>".$delete_id;   
     set_log($action,$admin,date("Y-m-d, g:i a"));
	
     
  }
 
 
  if(strcmp($action,"confirm_tarh")==0)
  {
    $query="select * from tarh where cod_tarh=\"$cod_tarh\" and version='-1' ";
    
    $result=mysql_query($query) or die("Error in updating data into tarh");
    if(mysql_num_rows($result) > 0)
    {
     $my_row_fetched=mysql_fetch_array($result);
   //  $cod_tarh_user =$my_row_fetched["cod_tarh_user"];
     
    
      $query="update tarh set confirm_moaven_tarh='1',vaziat_moaven='8' where cod_tarh=\"$cod_tarh\" and version='-1' ";
 
      mysql_query($query) or die("Error in updating data into tarh");
       insert_position($cod_tarh,"6",$admin);
      $query="select * from tarh where cod_tarh=\"$cod_tarh\"";
      $tarh_result=mysql_query($query) or die("Error in selecting data into tarh");
	  $row_fetched=mysql_fetch_array($tarh_result);
 
    }
  }
 }

  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh,user_login where user_login.email=tarh.creator  and archieved='1' and tarh_type!='6' and $tarh_type_caution   and $modir_caution and  (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and $daneshkade_caution and $year_caution and tarh.version='-1' order by $ascdescfield $ascdesc";
}
else
  $query="select * from tarh where  archieved='1' and  tarh_type!='6' and $tarh_type_caution   and $modir_caution  and $daneshkade_caution  and $year_caution  and tarh.version='-1' order by $ascdescfield $ascdesc ";


$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e))
{
  $query="select * from tarh,user_login where user_login.email=tarh.creator  and archieved='1' and tarh_type!='6' and $tarh_type_caution   and $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and $daneshkade_caution  and $year_caution  and tarh.version='-1' order by  $ascdescfield $ascdesc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select  * from tarh where  archieved='1' and tarh_type!='6' and  $tarh_type_caution   and $modir_caution and  $daneshkade_caution  and $year_caution  and tarh.version='-1' order by $ascdescfield $ascdesc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;


if(strcmp($ascdesc,'asc')==0)
  $ascdesc="desc";
else
  $ascdesc="asc";  

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرحهاي بايگاني شده<b></td>
 </tr>
 <tr>
 <td  align="center" class="tahoma1">
   رنگ قرمز به معني اچ اس آر و رنگ سبز به معني گرانت است
 </td> 
 </tr>
 </table> 
<?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>

 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
 
?>

</select> دانشکده / مرکز 
</td>
  
  
  
   

<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  
  
<?

 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 
 </tr>


 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";	
	
 pubshowpages("baygani_shode.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دليل آرشيو</font></td>  
 
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">موقعيت طرح</font></td>  
  <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح از نظر کارشناسي</font></td>
  
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">خروج از آرشيو</font></td>  
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>  
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
     <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاييد دريافت</font></td>
     <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">درخواست ويرايش</font></td>
    <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظريه ادمين دانشکده</font></td>   
     <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارجاع طرح به دانشکده / مرکز</font></td>  
	<td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رتبه در رنک و سال مربوطه</font></td>     
    <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايش</font></td> 
      <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال نامه</font></td> 
   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح</font></td>
     <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
    <td width="35%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=tarh_title_farsi&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>عنوان فارسي</a></font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=cod_tarh&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>کد طرح</a></font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
 	
  	
  $cod_tarh=$row_fetched["cod_tarh"];
  $position_tarh_code=current_position($cod_tarh);
  
  
  
  $status_comment="";

  $q="select * from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas   and version='-1'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	    $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }	
	 else
	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }
  	}
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  }
 
 
  
  
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh' and version='-1'";
 
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    
  }

  
  
  
 // echo $position_tarh_code;
  $ttype_2=$row_fetched["tarh_type_2"];
  $color_line="black";
  $tarh_type_q="select * from tarhtype_2 where tarh_type='$ttype_2' and (tarh_type_desc like \"%گرانت%\" or  tarh_type_desc like \"%گرنت%\")";
  //echo $tarh_type_q;
  $tarh_type_r=mysql_query($tarh_type_q) or die("error");
  if(mysql_num_rows($tarh_type_r)>0)
  {
  	 $color_line="green";
  }
  
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
  
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
    echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'>".$row_fetched["archieve_reason"]."</td>";
  echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$position_tarh["$position_tarh_code"]."</td>";
  echo "<td   bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$status_comment."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&unarchieve=1\" ><img border=\"0\" src=\"image/archive.jpg\" alt=\"archive\" ></a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويرايشها</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
//  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=tarh_list_new.phtml&admin=$admin&seed=$seed&action=delete_tarh&delete_id=".$row_fetched["cod_tarh"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a</td>";  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"tarh_list_new.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"Confirm\" ></a></td>";
  $edit_request=$row_fetched["edit_request"];
  if(strcmp($edit_request,'1')==0)
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"unlock_confirm.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\">دارد</a></td>";
  else
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">-----</td>";
    
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a   href=\"admin_comments.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"images/comments.jpg\" width=\"11\" height=\"13\" alt=\"Admin Comments\" ></a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"return_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"images/return.gif\"   alt=\"Return Back\" ></a></td>";
  
  
  $year_tarh=substr($cod_tarh,0,2);
  $rank_tarh=substr($cod_tarh,3,2);


  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >".$year_tarh.":سال"."<br>".$rank_tarh.":رنک"."<br>".$row_fetched["rotbe_tarh"].":رتبه"."</td>";	  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
  {
  	if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم"; 
  }
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }
  
  
  
  
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //$myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh'  ORDER  BY mojri.mojri_code";
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }




  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $daneshkade."</font></a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $farsistartdate."</font></a></td>";
 
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$First_mojri_name."</font></a></td>";
  else
    echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";

  $cod_tarh=$row_fetched["cod_tarh"];
  $version=$row_fetched["version"];
  if( strcmp(trim($cod_tarh_user),"0")!=0 )
     echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$cod_tarh."</font></a></td>";
     
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرح بايگاني شده اي يافت نشد","red");
}
echo "</form>";
if($reccount>0)
{
?>
 
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
<?    


 echo "<form name=\"change_tarh_type\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&cod_daneshkade=$cod_daneshkade_new\">";



 $query="select * from tarhtype order by  tarh_type  desc";
 $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
 echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"tarh_type\" onchange=\"JavaScript:document.change_tarh_type.submit();\" dir=\"rtl\">";
 echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

 while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_type"],$tarh_type)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_type"]."\" class=\"tahoma1\">".$row_fetched["tarh_type_desc"]."</option>";
 }
 
?>

</select> نوع طرح 
</td>
  
  </table>
<? 
} 
footer_forms($admin,$seed);


?>
