<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");
 
echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";

$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
if(strcmp(trim($row_fetched["modir_type"]),'4')==0 )
  $modir_caution=" tarh.send_moavenat='1' ";
else
  $modir_caution=' 1 ';  
  
  
//confirm_tarh=1
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
    
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
{
	//$cod_daneshkade=30;
   $daneshkade_caution=" 1 ";
 }  
$cod_daneshkade_new=$cod_daneshkade;
if ( ! isset($tarh_year))
    $tarh_year = '-1';




if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

//echo $tarh_year;
if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($action))
 {
 if(strcmp($action,"del")==0)
  {
    
     $query="delete from tarh where cod_tarh=\"$delete_id\"";
     
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from shora_tarh_vaziat where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from sayer_hazine where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from ravesh_ejra where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from mojri_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from letter_to_mojri where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from karshenasan_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from jadval_zarayeb where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_safar where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_personnel where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hazine_azmayesh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from hamkar_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from fhrest_vasayel_kharid where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $query="delete from daneshjo_tarh where cod_tarh=\"$delete_id\"";
     $result=mysql_query($query) or die("Error in updating data into tarh");
     $action=". طرح با کد مقابل حذف شد"."<br>".$delete_id;   
     set_log($action,$admin,date("Y-m-d, g:i a"));
	
     
  }
 
 
  if(strcmp($action,"confirm_tarh")==0)
  {
    $query="select * from tarh where cod_tarh=\"$cod_tarh\" and version='-1' ";
    
    $result=mysql_query($query) or die("Error in updating data into tarh");
    if(mysql_num_rows($result) > 0)
    {
     $my_row_fetched=mysql_fetch_array($result);
   //  $cod_tarh_user =$my_row_fetched["cod_tarh_user"];
     
    
      $query="update tarh set confirm_moaven_tarh='1' where cod_tarh=\"$cod_tarh\" and version='-1' ";
 
      mysql_query($query) or die("Error in updating data into tarh");
      $query="select * from tarh where cod_tarh=\"$cod_tarh\"";
      $tarh_result=mysql_query($query) or die("Error in selecting data into tarh");
	  $row_fetched=mysql_fetch_array($tarh_result);
  
    }
  }
 }

$indoing_string='1';
if(isset($indoing))
{
	if(strcmp($indoing,'0')==0)
	  $indoing_string=' tarh.indoing=0 ';
	
	if(strcmp($indoing,'1')==0)
	  $indoing_string=' tarh.indoing=1 ';
	  
	
}

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh where  tarh.archieved ='0' and  $indoing_string and $tarh_type_caution and confirm_moaven_tarh='1' and $modir_caution and  (cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and $daneshkade_caution and $year_caution and version='-1' order by $ascdescfield $ascdesc";
} 
else
  $query="select * from tarh where   tarh.archieved ='0' and   $indoing_string and $tarh_type_caution and confirm_moaven_tarh='1' and $modir_caution  and $daneshkade_caution  and $year_caution  and version='-1' order by $ascdescfield $ascdesc ";



$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 
/* if(isset($name_e))
{
  $query="select * from tarh where  tarh_type!='6' and $tarh_type_caution and confirm_moaven_tarh='0' and $modir_caution and (cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and $daneshkade_caution  and $year_caution  and version='-1' order by  $ascdescfield $ascdesc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select  * from tarh where  tarh_type!='6' and  $tarh_type_caution and confirm_moaven_tarh='0' and $modir_caution and  $daneshkade_caution  and $year_caution  and version='-1' order by $ascdescfield $ascdesc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;


if(strcmp($ascdesc,'asc')==0)
  $ascdesc="desc";
else
  $ascdesc="asc";  

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 */
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>گزارش گيري از طرحها<b></td>
 </tr>
 </table> 
 


 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
 
  <?
echo "<form name=\"change_indoing\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type&cod_daneshkade=$cod_daneshkade\">";
?>
<?    



 echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"indoing\" onchange=\"JavaScript:document.change_indoing.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

 
  	if(strcmp( $indoing,'0')==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".'0'."\" class=\"tahoma1\">".'قبل از اجرا'."</option>";
  	if(strcmp( $indoing,'1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
    echo "<option $selected value=\"".'1'."\" class=\"tahoma1\">".'در حال اجرا'."</option>";
  
 
?>

</select> وضعيت اجرايي 
</td>
  
  
  
   

<?
echo "</form>";
 
 
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type&indoing=$indoing\">";
?>

 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
 
?>

</select> دانشکده / مرکز 
</td>
  
  
  
   

<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type&indoing=$indoing\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  
  
<?

 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 
 </tr>


 </table>
<?
echo "</form>";
}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";	
 //pubshowpages("report_mali.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
if(isset($name_e))
  $search_string="name_e=".trim($name_e);
else
  $search_string="";

echo "<form name=\"select_tarhs\" method=\"post\"  action=\"budje_selective_result.phtml?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type&$search_string\">";

?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
  <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><input type="checkbox" name="checkall" onClick="checkUncheckAll(this);"></font></td>

 <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تامين اعتبار از ساير سازمانها</font></td>        


<td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مبلغ تصويب شده توسط ناظر مالي</font></td>        
 
<td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بودجه مصوب مدير</font></td>        
 <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بودجه مصوب</font></td>                  
  <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بودجه پيشنهادي</font></td>           
   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رتبه در رنک و سال مربوطه</font></td>     
  <!-- <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح</font></td>  -->
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
   <!-- <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td> -->
    <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "report_mali.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=tarh_title_farsi&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>عنوان فارسي</a></font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "report_mali.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=cod_tarh&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>کد طرح</a></font></td>
  <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
   
  </tr>
  <?

 $color=$list_color_1;
 $i=0;
 $cntr=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $mablagh_aghd_gharardad=$row_fetched["mablagh_aghd_gharardad"];
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq) or die("error");
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
  
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
 
  
  $year_tarh=substr($cod_tarh,0,2);
  $rank_tarh=substr($cod_tarh,3,2);
  
  $query = "select * from eatebar_sazmanha where cod_tarh='$cod_tarh'  and version='-1'";
 $result11 = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$eatebar=0;
$eatebare_sazmanha_pardakht_add=0;
 if(mysql_num_rows($result11) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result11))	
  {
  	$eatebar_org=$hazine_row_fetched["eatebare_sazmanha_value"];
  	$eatebar_org=str_replace("/","",$eatebar_org);
    $eatebar = $eatebar+$eatebar_org;
   
  }
 }
    
    
    $eatebare_sazmanha_pardakht_add=$eatebar;
 $eatebare_sazmanha_pardakht_add=number_format($eatebare_sazmanha_pardakht_add);
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  ><input type=\"hidden\" name=\"dan".$i."\" value=\"$cod_daneshkade\"><input type=\"checkbox\" name=\"c".$i."\" value=\"$cod_tarh\">"."</td>";	  
  
  $qt1="select * from jalase_shora_tarh where cod_tarh='$cod_tarh'";
  $rt1=mysql_query($qt1) or die("error");
  $budje_mosavab=0;
  if(mysql_num_rows($rt1) > 0)
  {
  	 $rft1=mysql_fetch_array($rt1);
  	 $budje_mosavab=$rft1["budjeh"];
  	 
  } 
  $budje_mosavab=str_replace("/","",$budje_mosavab);
  $budje_mosavab=number_format($budje_mosavab);
  
   $budje=sum_of_hazine($cod_tarh,"-1");
   $budje=number_format($budje);
   
   
   $qt1="select sum(mablagh) as mablagh  from tarh_indoing where cod_tarh='$cod_tarh' and submitted='1' ";
  $rt2=mysql_query($qt1) or die("error");
  $rf2=mysql_fetch_array($rt2);
  $mablagh_nazer_mali=number_format($rf2["mablagh"]);
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >$eatebare_sazmanha_pardakht_add</td>";
  
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >$mablagh_nazer_mali</td>";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >$mablagh_aghd_gharardad</td>";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >$budje_mosavab</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >$budje</td>";
  
  echo "<input type=\"hidden\" name=\"aghd".$i."\" value=\"$mablagh_aghd_gharardad\">";
  echo "<input type=\"hidden\" name=\"mosavab".$i."\" value=\"$budje_mosavab\">";
   echo "<input type=\"hidden\" name=\"nazer".$i."\" value=\"$mablagh_nazer_mali\">";
  echo "<input type=\"hidden\" name=\"budje".$i."\" value=\"$budje\">";
  
  $i++;
 
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"  >".$year_tarh.":سال"."<br>".$rank_tarh.":رنک"."<br>".$row_fetched["rotbe_tarh"].":رتبه"."</td>";

  
 // $editable=1;
  //$mytarh_type = $row_fetched["vaziat"];
/*  if($row_fetched["vaziat"]=="0")
  {
  	if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم"; 
  }
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }
 */ 
  
  
  
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //$myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh'  ORDER  BY mojri.mojri_code";
/*  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }
*/



 // echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $daneshkade."</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $farsistartdate."</a></td>";
 
 /* if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
    
    */
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";

  $cod_tarh=$row_fetched["cod_tarh"];
  $version=$row_fetched["version"];
  if( strcmp(trim($cod_tarh_user),"0")!=0 )
     echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
    echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $cntr."</a></td>";
    $cntr++;
   
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
   
 }
 
 //// end of while
echo "</table>";
echo "<input type=\"submit\" value=\"گزارش گيري\" name=\"B1\"  class=\"but-small\">";
echo "<input type=\"hidden\" name=\"cntr_record\" value=\"$i\">";
echo "</form>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرح ارسال شده  جديدي يافت نشد","red");
}

if($reccount>0)
{
?>
 
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
<?    


 echo "<form name=\"change_tarh_type\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&cod_daneshkade=$cod_daneshkade_new\">";



 $query="select * from tarhtype order by  tarh_type  desc";
 $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
 echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"tarh_type\" onchange=\"JavaScript:document.change_tarh_type.submit();\" dir=\"rtl\">";
 echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

 while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_type"],$tarh_type)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_type"]."\" class=\"tahoma1\">".$row_fetched["tarh_type_desc"]."</option>";
 }
 
?>

</select> نوع طرح 
</td>
  
  </table>
<? 
} 
footer_forms($admin,$seed);


?>
