<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

if ( ! isset($current))
    $current = 1;

$RecPerPage=12;
$query="select * from daneshkade ";


$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);


$query="select * from daneshkade where 1  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage;
//echo $query;
$result=mysql_query($query) or die("Error in selecting data from tarh 2"); 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>گزارش بودجه درخواستي طرحها<b></td>
 </tr>
 </table>
 
<?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";


}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade";	
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc";
 pubshowpages("budje_group_by_center.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>

    <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">بودجه درخواستي ارسال کنندگان</font></td>
       <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
  
    </tr>
  <?

 $color=$list_color_1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $q="select * from tarh where cod_daneshkade='$cod_daneshkade'";
  
  $r=mysql_query($q) or die("error");
  $sum_dan=0;
  while($rf=mysql_fetch_array($r))
  {
  	$cd=$rf["cod_tarh"];
  	$sum_dan=$sum_dan+sum_of_hazine($cd,"-1");
  }
  echo "<tr>";
  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$sum_dan."</td>";
  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</td>";
  echo "</tr>";
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
footer_forms($admin,$seed);
?>