<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/styles.phtml");
header_forms($admin,$seed);
echo "<br>";

if(isset($action))
{
  if (strcmp($action,"sabt")==0)
  {
      $status_upload=upload_file("../rezayatname",$cod_tarh,"rezayatname.doc");
       if(!strcmp($status_upload,"10") == 0 )
	     $status="upload_error";
	
	 if(strcmp(trim($status),"upload_error")==0)
       $rezayatname_filename="";
     else
       $rezayatname_filename="rezayatname.doc";
     
     $query  = "update tarh set moshkelat_akhlaghi =\"$moshkelat_akhlaghi\", halle_moshkelat_akhlaghi = \"$halle_moshkelat_akhlaghi\",rezayatname=$rezayatname,rezayatname_filename=\"$rezayatname_filename\" where cod_tarh=\"$cod_tarh\"  and version='-1'";
	 $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");
	 $action=" ثبت فرم کميته اخلاقي با کد ".$cod_tarh;
     set_log($action,$admin,date("Y-m-d, g:i a"));
     message_show(".فرم ملاحظات اخلاقي با موفقيت ثبت شد ","green");
     echo "<table border=\"0\" width=\"500\">";
     echo "<tr>";
     echo "<td width=\"50%\" colspan=\"2\" align=\"center\" valign=\"top\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"hazineha.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >بازگشت</a></td>";
     echo "</tr>";
     echo "</table>";
	 footer_forms($admin,$seed);
	 exit();
     
  }
}

?>

<? echo "<form name=\"mojri_tarh\"  method=\"post\" enctype=\"multipart/form-data\" action=\"$PHP_SELF?action=sabt&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
   <TD align=left width="249"   >
     <a style="text-decoration:none" href="sabt_tarh_second.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="251"  background="image/comite_akhlaghi.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?

  $query  = "select * from tarh  where  cod_tarh=\"$cod_tarh\"  and version='-1'";
  $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");

  $row_fetched = mysql_fetch_array($result);
  $moshkelat_akhlaghi = $row_fetched["moshkelat_akhlaghi"];
  $halle_moshkelat_akhlaghi = $row_fetched["halle_moshkelat_akhlaghi"];
  $rezayatname_val = $row_fetched["rezayatname"];
  //echo $row_fetched["rezayatname"]."<br>";
  //echo strcmp(trim($rezayatname),"0");
  $rezayatnamefile = $row_fetched["rezayatnamefile"];
  //$comite_daneshgah_keshvar = $row_fetched["comite_daneshgah_keshvar"];

  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>

<tr>
    <td width="100" align="right"><textarea   rows="3"  name="moshkelat_akhlaghi" class="edit-user"  dir=RTL   ><? echo $moshkelat_akhlaghi  ; ?></textarea></td>
    <td width="400" class="tahoma1"  valign="top">ملاحظات و مشكلات اخلاقي طرح</td>
  </tr>

   <tr>
    <td width="100" align="right"><textarea   rows="3"  name="halle_moshkelat_akhlaghi" class="edit-user"  dir=RTL   ><? echo $halle_moshkelat_akhlaghi  ; ?></textarea></td>
    <td width="400" class="tahoma1"  valign="top">راه حل مشكلات اخلاقي</td>
  </tr>

   <tr>
    <td width="100" align="right" >
  
  <select size="1" name="rezayatname" class="edit-user">
  <?
  
  if($rezayatname_val==0)
  {
	
   echo "<option  value=\"0\" class=\"tahoma1\" selected>خير</option>";
   echo "<option  value=\"1\"  class=\"tahoma1\">بلي</option>";
  }
  else
  {
    
   echo "<option  value=\"0\" class=\"tahoma1\" >خير</option>";
   echo "<option  value=\"1\"  class=\"tahoma1\" selected>بلي</option>";
  }
   ?>
   </select>
   </td>
   
   <td width="400" class="tahoma1"  valign="top">آيا طرح رضايتنامه اخلاقي دارد</td>
   </tr>

  <tr>
    <td width="100" align="right"><input type="file"   rows="3"  name="fupload" class="edit-user"  dir=RTL   ><? echo $rezayatnamefile  ; ?></td>
    <td width="400" class="tahoma1"  valign="top">(.doc) فايل رضايتنامه</td>
  </tr>
  
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>

 
<?
  footer_forms($admin,$seed);
 ?>




