<?
include("include/include.phtml");
include("include/database-connect.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");


echo "<br>";


if(isset($action))
{
  if (strcmp($action,"signup")==0)
  {

    if( strlen(trim($name)) > 0 &&strlen(trim($family)) > 0 )
    {
      	  
        $query  = "insert into control_gharardad_karshenas  set  karshenas_name=\"$name\",karshenas_family=\"$family\"";      	
        $result=mysql_query($query) or die("Error in inserting data into control_gharardad_karshenas");
        //$action="ثبت شماره موبايل";
        //set_log($action,$admin,date("Y-m-d, g:i a"));
		 ?>
        <!--  <script language="javascript">
           window.location="<? echo "control.phtml?admin=$admin&seed=$seed";  ?>";
           </script>  --> 
           <?

		//footer_forms($admin,$seed);
		//exit();
     

    }
    else
      $status="entry_error";
  }
  

 if (strcmp($action,"delete_karshenas")==0)
 {
    $query="delete from control_gharardad_karshenas where id = \"$delete_id\"";
    
    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
    
 }

}

      

?>


<? echo "<form name=\"signup\" method=\"post\"  action=\"$PHP_SELF?&admin=$admin&seed=$seed&action=signup\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
 <TR>
    <TD align=right width="100%" class="tahoma1"  height=19>
     تعريف کارشناس کنترل قرارداد
      </TD>
  </TR>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8" cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


  <tr>
    <td width="350" align="right"><input type="text" name="name"  size="20" class="edit-sugnup" dir=RTL     ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="family" size="20" class="edit-sugnup" dir=RTL     ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>

  
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>

<?
    
if(DBreccount("control_gharardad_karshenas") > 0)
{
    echo "<table border=\"0\" width=\"400\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"274\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام و نام خانوادگي</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
  $Query=mysql_query("select * from control_gharardad_karshenas order by id") or die("Error in selecting tarh-type");
  while($row_fetched=mysql_fetch_array($Query))
  {
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
    $karshenas_name=$row_fetched["karshenas_name"];
    $karshenas_family=$row_fetched["karshenas_family"]; 
    $karshenas_fullname= $karshenas_name." ".$karshenas_family;
  echo "<tr bgcolor=\"$color\">";
  echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
  echo "<td width=\"47\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"delete_or_apply_tarh_type.phtml?mainwindow=control_gharardad_karshenas.phtml&admin=$admin&seed=$seed&action=delete_karshenas&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
  echo "<td width=\"47\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"edit_karshenas.phtml?mainwindow=control_gharardad_karshenas.phtml&admin=$admin&seed=$seed&action=delete&edit_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=380,height=120,left=((screen.width-320) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\"></td>";
  echo "<td width=\"274\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$karshenas_fullname."</td>";
  echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
  echo "</tr>";

  }
  echo "<tr>";
  echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"274\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
  echo "</tr>";
  echo "</table>";
}
else
{

  echo "<p align=\"center\"  class=\"tahoma1\">با کليک روي کليد اضافه ميتوانيد يک نوع طرح اضافه کنيد";

}

  footer_forms($admin,$seed);
 ?>




