<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);

if(strcmp($row_fetched["modir_type"],'4') ==0 )
  $modir_caution=" (tarh.send_moavenat='1' or tarh_type_2='3' or tarh_type_2='4'  or tarh_type_2='9' or tarh_type_2='10' or tarh_type_2='8' or tarh_type_2='11' or tarh_type_2='14'     or tarh_type_2='12' or tarh_type_2='13'  or tarh_type_2='16'  or tarh_type_2='17') ";
else
  $modir_caution='1';  
   
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
  
if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($current))
    $current = 1;

    
       if($startyear!='-1' or $startmon!='-1' or $startday!='-1'){
         	// echo $start_year;
 		 $hijri_start_date =jalali_to_gregorian($startyear,$startmon,$startday);
         $year=$hijri_start_date[0];
         $month=str_pad($hijri_start_date[1],2,"0",STR_PAD_LEFT);
         $day=str_pad($hijri_start_date[2],2,"0",STR_PAD_LEFT);
         $start_date=$year."-".$month."-".$day;
        //echo  $start_date;
         }
         else 
         $start_date="";
 


          if($endyear!='-1' or $endmon!='-1' or $endday!='-1'){
          $hijri_end_date =jalali_to_gregorian($endyear,$endmon,$endday);
         $year=$hijri_end_date[0];
         $month=str_pad($hijri_end_date[1],2,"0",STR_PAD_LEFT);
         $day=str_pad($hijri_end_date[2],2,"0",STR_PAD_LEFT);
         $end_date=$year."-".$month."-".$day;
          }
          else 
          $end_date="";
    

           if($start_date!="" or $end_date!=""){
  
		  	$date_c1="tarh.send_ready_gharardad_date>='$start_date' and tarh.send_ready_gharardad_date<='$end_date'  ";
		  	//echo $date_c1;
		  }
		  else 
		  {
		    $date_c1="1";
		  }

if(strcmp($karshenas,'-1')!=0 )
{
	$karshenas_caution="control_gharardad_tarh.cod_karshenas = '$karshenas'";
}
else
   $karshenas_caution="1";
   
   
if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="tarh.cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
  

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=$max_record;
      $current=1;
    }
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
	$query="select  tarh.*  from tarh ,control_gharardad_tarh,user_login where user_login.email=tarh.creator and tarh.ready_gharardad='1' and  tarh.cod_tarh=control_gharardad_tarh.cod_tarh   and $daneshkade_caution and $year_caution and $date_c1 and $karshenas_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or tarh.cod_tarh like $myname_search or tarh.tarh_title_farsi like $myname_search or  tarh.tarh_title_english like $myname_search)  and tarh.version='-1' group by cod_tarh order by tarh_time desc";
  //$query="select  tarh.*  from tarh ,user_login where user_login.email=tarh.creator and ready_gharardad='0' and tarh_type!='6'   and $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and   submission_status ='1'   and $daneshkade_caution and $year_caution and  confirm_moaven_tarh='1'  and tarh.version='-1' group by cod_tarh order by tarh_time desc"; 
}
else
  //$query="select  tarh.*  from tarh  where  ready_gharardad='0'  and   submission_status ='1' and tarh_type!='6'   and $modir_caution    and confirm_moaven_tarh='1'  and $daneshkade_caution and $year_caution  and tarh.version='-1' group by cod_tarh order by tarh_time desc";
 $query="select  tarh.*  from tarh ,control_gharardad_tarh,user_login where user_login.email=tarh.creator and tarh.ready_gharardad='1' and  tarh.cod_tarh=control_gharardad_tarh.cod_tarh  and $daneshkade_caution and $year_caution and $date_c1 and $karshenas_caution and tarh.version='-1' group by cod_tarh order by tarh_time desc";
//echo $query;

$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);


 if(isset($name_e))
{
 // $query="select  tarh.* from tarh ,user_login where user_login.email=tarh.creator  and   submission_status ='1' and ready_gharardad='0' and tarh_type!='6'  and  $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)    and $daneshkade_caution and $year_caution and confirm_moaven_tarh='1'  and tarh.version='-1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
 $query="select  tarh.*  from tarh ,control_gharardad_tarh,user_login where user_login.email=tarh.creator and tarh.ready_gharardad='1' and   tarh.cod_tarh=control_gharardad_tarh.cod_tarh  and $daneshkade_caution and $year_caution and $date_c1 and $karshenas_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or tarh.cod_tarh like $myname_search or tarh.tarh_title_farsi like $myname_search or  tarh.tarh_title_english like $myname_search) and tarh.version='-1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
 // $query="select  tarh.*  from tarh  where ready_gharardad='0' and   submission_status ='1' and tarh_type!='6'  and $modir_caution   and confirm_moaven_tarh='1'  and $daneshkade_caution and $year_caution  and tarh.version='-1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
$query="select  tarh.*  from tarh ,control_gharardad_tarh,user_login where  user_login.email=tarh.creator and tarh.ready_gharardad='1' and  tarh.cod_tarh=control_gharardad_tarh.cod_tarh  and $daneshkade_caution and $year_caution and $date_c1 and $karshenas_caution and tarh.version='-1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh2");
 //echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>گزارش طرحهاي آماده به قرارداد<b></td>
 </tr>
 <tr>
 <td   align="center" class="tahoma1">
   رنگ قرمز به معني اچ اس آر و رنگ سبز به معني گرانت است
 </td> 
 </tr>
 </table>
 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\">  <select size=\"1\" name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" class='tahoma1' dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
  
?>
  </select>دانشکده / مرکز
  </td>
<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  <?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&tarh_type=$tarh_type\">";

?> 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type&startday=$startday&startmon=$startmon&startyear=$startyear&endday=$endday&endmon=$endmon&endyear=$endyear&karshenas=$karshenas";
 if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";	

 pubshowpages("control_gharardad_report.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
<?
//	echo "<tr>";
 //   echo "<td colspan='45' width=\"16\"   height=\"20\" align='left'><a href='control_gharardad_excel.phtml?admin=$admin&seed=$seed&cod_shora=$cod_shora '><img src='image/excell.jpg' border='0'></img></a></td>";
  //  echo "</td>";
  //  echo "</tr>";
?>
  <tr>
  
     
    <td  width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">موقعيت طرح</font></td>  
 
        <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>  

    <td  width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>

     <td  width="5%" bgcolor=<? echo "$title_color"; ?>>  
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
        
    <td   width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ درخواست آماده به قرارداد</font></td>
      <td   width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال به آماده به قرارداد</font></td>
      <td  width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نوع طرح</font></td> 
      
      <td  width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام کارشناس ثبت کننده اطلاعات کنترل قرارداد</font></td> 
    <td  width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
   <td   width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td  width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  
  <?

 $color=$list_color_1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $control_gharardad_date=$row_fetched["date"];
  $cod_tarh=$row_fetched["cod_tarh"];
   $ttype_2=$row_fetched["tarh_type_2"];
  $color_line="black";
  $tarh_type_q="select * from tarhtype_2 where tarh_type='$ttype_2' and (tarh_type_desc like \"%گرانت%\" or  tarh_type_desc like \"%گرنت%\")";
  //echo $tarh_type_q;
  $tarh_type_r=mysql_query($tarh_type_q) or die("error");
  if(mysql_num_rows($tarh_type_r)>0)
  {
  	 $color_line="green";
  }
  
 	
  
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
   $mostaghel =$myrf["mostaghel"];
  if(strcmp(trim($mostaghel),'1')==0)
     $daneshkade=$daneshkade."(مرکز مستقل)";
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  $position_tarh_code=current_position($cod_tarh);	
 
  
  echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$position_tarh[$position_tarh_code]."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويرايشها</a></td>";
  
  
  //echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"send_new_gharardad.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ارسال</td>";
echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To...\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target = \"_blank\" href=\"shenasname_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/shenasname_tarh.gif\" width=\"11\" height=\"13\" alt=\"Shenasname tarh\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";

  $editable=1;
  $mytarh_type = $row_fetched["vaziat_moaven"];
  if($row_fetched["vaziat_moaven"]=="0")
  {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }


  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
 
  $status_comment="";

  $q="select * from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas   and version='-1'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	    $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }	
	 else
	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }
  	}
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  }
 
 
  
  
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh' and version='-1'";
 
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    
  }

 
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    //$status_comment=$status_comment."<br>"."ارسال به اپيدميولوژيست : ".$plus."<br>";  
  
    //$status_comment=$status_comment."<br>"."-".": ارسال به اپيدميولوژيست"."<br>";
  }
  
  
  $myquery="select * from control_gharardad_tarh where (cod_tarh=\"$cod_tarh\") ";
  //echo $myquery;
    $myresult=mysql_query($myquery) or die("Error in selecting data from tarh  ");
	$num_rows=mysql_num_rows($myresult);
      if ( $num_rows > 0 )
           	$control_gharardad_status="<b>دارد</b>";
      else 
 	    	$control_gharardad_status="ندارد";
 	    	
 	 $row_fetched_gharardad=mysql_fetch_array($myresult);
 	 $modir_confirm=$row_fetched_gharardad["modir_confirm"];
 	 
 	 if(strcmp($modir_confirm,'0')==0)
 	 	$modir_confirm_st="<b><font color='red'>رد</font></b>";
 	 else if(strcmp($modir_confirm,'1')==0)
 	 	$modir_confirm_st="<b><font color='red'>تاييد</font></b>";
 	 else if(strcmp($modir_confirm,'2')==0)
 	 	$modir_confirm_st="<b><font color='red'>تاييد مشروط</font></b>";
 	else 
 		$modir_confirm_st="ثبت نشده";
 	 	
 	 $bazbini_request=$row_fetched_gharardad["bazbini_request"];
 	 
 	if(strcmp($bazbini_request,'')!=0)
 	 	$bazbini_request_st="<b><font color='red'>دارد</font></b>";
 	 else 
 	 	$bazbini_request_st="ندارد";
 	 	
 	 $cod_karshenas=$row_fetched_gharardad["cod_karshenas"];
 	 $tarh_type2=$row_fetched_gharardad["tarh_type"];
 		if(strcmp($tarh_type2,"1")==0)
			$tarh_type_st="معمولي";
		if(strcmp($tarh_type2,"2")==0)
			$tarh_type_st="گرنت";
		if(strcmp($tarh_type2,"3")==0)
			$tarh_type_st="HSR";

	$send_ready_gharardad_date=$row_fetched["send_ready_gharardad_date"];
	$startyear = substr($send_ready_gharardad_date,0,4);
    $startmon = substr($send_ready_gharardad_date,5,2);
    $startday = substr($send_ready_gharardad_date,8,2);
    $send_ready_gharardad_date2=hijricalender( $startyear , $startmon , $startday );
    $send_ready_gharardad_date2 = enum2fnum($send_ready_gharardad_date2);

  //   echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_tarh_before_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ارسال</a></td>";

    $control_gharardad_date=$row_fetched_gharardad["date"];
    //echo $control_gharardad_date;
	$startyear = substr($control_gharardad_date,0,4);
    $startmon = substr($control_gharardad_date,5,2);
    $startday = substr($control_gharardad_date,8,2);
    $control_gharardad_date2=hijricalender( $startyear , $startmon , $startday );
    $control_gharardad_date2 = enum2fnum($control_gharardad_date2);
  
 
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  
  
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $daneshkade."</font></a></td>";
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $control_gharardad_date2."</font></a></td>";
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $send_ready_gharardad_date2."</font></a></td>";
  
  
  echo "<td bgcolor=$color width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$tarh_type_st."</td>"; 
  
 
 // echo $cod_karshenas;
    $query="select * from group_karshenasan where cod_karshenas='$cod_karshenas' ";
   // echo $query;
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    $row_fetched3=mysql_fetch_array($qresult);
    $name=$row_fetched3["karshenas_name"];
    $family=$row_fetched3["karshenas_family"];
    $karshenas_gharardad=$name." ".$family;
  
  echo "<td bgcolor=$color width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$karshenas_gharardad."</td>";
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
    $First_mojri_name = "اطلاعات موجود نيست";
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$First_mojri_name."</font></a></td>";
  else
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"15%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["cod_tarh"]."</font></a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
if($reccount>0)
{
?>
 
 
<? 
} 
footer_forms($admin,$seed);


?>