<script>
function checkit()
{
	var key
	key = window.event.keyCode
	
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	{
		if(key!=46)
	      window.event.returnValue= false;
	    else  
	    window.event.returnValue= true
	}

	  
}
</script>
<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";
 $query="select * from tarh where cod_tarh='$cod_tarh'  and version='-1'";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];

if(isset($action))
{
  if (strcmp($action,"add_daneshjo")==0)
  {

     if(strlen(trim($name)) > 0 && strlen(trim($family)) > 0  &&  strlen(trim($email)) > 0  &&  strstr($email, '@') &&  strlen(trim($daneshjo_no)) > 0 )
     {
      $query="select * from daneshjo where  cod_daneshjo=\"$daneshjo_no\"";
      $result=mysql_query($query) or die("Error in selecting data from  mojri list ");
      if ( mysql_num_rows($result) <= 0 )
      {

        $query  = "insert into daneshjo set maghtaee_tahsili=\"$maghtaee_tahsili\",reshteh_tahsili=\"$reshteh_tahsili\" ,daneshkade =\"$daneshkade\", name=\"$name\" , name_e=\"$name_e\", family=\"$family\", family_e = \"$family_e\",  address_job = \"$work_addr\", address_job_en = \"$work_addr_en\",address_home = \"$home_addr\", address_home_en = \"$home_addr_en\", telno = \"$telno\", fax =\"$fax\", melli_code =\"$cod_melli\", email =\"$email\", cod_daneshjo =\"$daneshjo_no\", hesab =\"$hesab\" , bank_name =\"$bank_name\" , shoabe=\"$shoabe\" , sex=\"$sex\", cod_bank=\"$cod_bank\"";
        
        $result = mysql_query($query) or die("Error in inserting data into daneshjo list");

        $query = "insert into daneshjo_tarh set cod_daneshjo = \"$daneshjo_no\" , cod_tarh=\"$cod_tarh\" ";
        
		$result = mysql_query($query) or die("Error in inserting data into daneshjo_tarh");
        
        $action="اضافه / ويرايش دانشجو يان طرح"."<br>".$name."&nbsp;&nbsp;".$family;
        set_log($action,$admin,date("Y-m-d, g:i a"));
   
		$name="";	
  	    $family="";
  	    $email="";
  	    $telno="";
  	    $fax="";
  	    $hesab="";
  	    $bank_name="";
  	    $address_job="";
  	    $lelli_code="";
  	    $maghtaee_tahsili="";
  	    $reshteh_tahsili="";
  	    $shoabe="";
  	    $cod_bank="";
  	    $sex="";
  	    $daneshjo_no="";
  	    $home_addr="";
    

      }
      else
       {
         $row_fetched = mysql_fetch_array($result);
         $mojri_code = $row_fetched["cod_daneshjo"];
         $query="select * from daneshjo_tarh where  cod_daneshjo=\"$daneshjo_no\"  and version='-1'";
         $result = mysql_query($query) or die("Error in selecting data from mojri_tarh");
         if(mysql_num_rows($result) <=0 )
         {
           $query = "insert into daneshjo_tarh set cod_daneshjo = \"$daneshjo_no\" , cod_tarh=\"$cod_tarh\" ";
           $result = mysql_query($query) or die("Error in inserting data into mojri_tarh");
           $action="اضافه / ويرايش دانشجو يان طرح"."<br>".$name."&nbsp;&nbsp;".$family;
           set_log($action,$admin,date("Y-d-m"));
           //message_show("مشخصات دانشجو  با موفقيت ثبت شد","green");
	  	   //footer_forms($admin,$seed);
		   $status="entry_finish";
		   $name="";	
  	 	   $family="";
  	   	   $email="";
  	   	   $telno="";
  	   	   $fax="";
  	   	   $hesab="";
  	   	   $bank_name="";
  	   	   $address_job="";
  	   	   $lelli_code="";
  	   	   $maghtaee_tahsili="";
  	   	   $reshteh_tahsili="";
  	   	   $shoabe="";
  	   	   $cod_bank="";
  	       $sex="";
  	       $home_addr="";
  	       $daneshjo_no="";
  	      // exit();
   

         }
       }
     }
     else
       $status="entry_error";
  }

 if (strcmp($action,"delete_daneshjo")==0)
 {
    $query="delete from daneshjo_tarh where cod_daneshjo = \"$delete_id\" and cod_tarh=\"$cod_tarh\"  and version='-1'";

    $result=mysql_query($query) or die("Error in  delete data from daneshjo ");
     $action="حذف دانشجوي طرح از طرح"."<br>".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
   
 }



  if (strcmp($action,"edit_daneshjo")==0)
  {
  	$query="select * from daneshjo_tarh , daneshjo where  daneshjo.cod_daneshjo='$cod_daneshjo' and daneshjo_tarh.cod_daneshjo=daneshjo.cod_daneshjo and daneshjo_tarh.cod_tarh='$cod_tarh' and daneshjo_tarh.version='-1'";
  	
	$result=mysql_query($query) or die("Error in selecting data from mojri");
  	if(mysql_num_rows($result) > 0)
  	{
  	   $row_fetched=mysql_fetch_array($result);	
  	   $name=$row_fetched["name"];	
  	   $family=$row_fetched["family"];
  	   $email=$row_fetched["email"];
  	   $telno=$row_fetched["telno"];
  	   $fax=$row_fetched["fax"];
  	   $melli_code=$row_fetched["melli_code"];
  	   $hesab=$row_fetched["hesab"];
  	   $address_home=$row_fetched["address_home"];
  	   $bank_name=$row_fetched["bank_name"];
  	   $address_job=$row_fetched["address_job"];
  	   $melli_code=$row_fetched["melli_code"];
  	   $maghtaee_tahsili=$row_fetched["maghtaee_tahsili"];
  	   $reshteh_tahsili=$row_fetched["reshteh_tahsili"];
  	   $shoabe=$row_fetched["shoabe"];
  	   $cod_bank=$row_fetched["cod_bank"];
  	   $sex=$row_fetched["sex"];
  	   
  	   
  	  	   
  	}
  	else
  	{  	   	
  	   $name="";	
  	   $family="";
  	   $email="";
  	   $telno="";
  	   $fax="";
  	   $hesab="";
  	   $bank_name="";
  	   $address_job="";
  	   $lelli_code="";
  	   $maghtaee_tahsili="";
  	   $reshteh_tahsili="";
  	   $shoabe="";
  	   $cod_bank="";
  	   $melli_code="";
  	   $sex="";
  	   $home_addr="";
  	   $address_home="";
  	   $daneshjo_no="";
  	}
  	
  }
  
  
  
   if (strcmp($action,"edit_daneshjo_second")==0)
  {  	

     if(strlen(trim($name)) > 0 && strlen(trim($family)) > 0 &&  strlen(trim($email)) > 0  &&  strstr($email, '@'))
     {
      $query="select * from daneshjo where  cod_daneshjo=\"$daneshjo_no\"";
      $result=mysql_query($query) or die("Error in selecting data from  mojri list ");
     

        $query  = "update  daneshjo set maghtaee_tahsili=\"$maghtaee_tahsili\",reshteh_tahsili=\"$reshteh_tahsili\" ,daneshkade =\"$daneshkade\", name=\"$name\" , name_e=\"$name_e\", family=\"$family\", family_e = \"$family_e\",  address_job = \"$work_addr\", address_job_en = \"$work_addr_en\",address_home = \"$home_addr\", address_home_en = \"$home_addr_en\", telno = \"$telno\", fax =\"$fax\", melli_code =\"$cod_melli\", email =\"$email\",  hesab =\"$hesab\" , bank_name =\"$bank_name\" , shoabe=\"$shoabe\" , sex=\"$sex\", cod_bank=\"$cod_bank\" where cod_daneshjo =\"$cod_daneshjo\"";
        
		$result = mysql_query($query) or die("Error in inserting data into daneshjo list");
        
        $action="اضافه / ويرايش دانشجو يان طرح"."<br>".$name."&nbsp;&nbsp;".$family;       
       
        set_log($action,$admin,date("Y-m-d, g:i a"));
        $status="entry_finish";
         $name="";	
  	   $family="";
  	   $email="";
  	   $telno="";
  	   $fax="";
  	   $hesab="";
  	   $bank_name="";
  	   $address_job="";
  	   $lelli_code="";
  	   $maghtaee_tahsili="";
  	   $reshteh_tahsili="";
  	   $shoabe="";
  	   $cod_bank="";
  	   $melli_code="";
  	   $sex="";
  	   $home_addr="";
  	   $address_home="";
	//	message_show("مشخصات دانشجو  با موفقيت ثبت شد","green");
	//	footer_forms($admin,$seed);
	//	exit();
   
     }
     else
       $status="entry_error";
  }


}

if(strcmp($action,"edit_daneshjo")==0)
   echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=edit_daneshjo_second&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshjo=$cod_daneshjo\">";    
else
   echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_daneshjo&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";    
 
 
 ?>
 



<TABLE cellSpacing=0 cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center width="500" class="tahoma1"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=left width="249"   height=19>
     <a style="text-decoration:none" href="sabt_tarh_second.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="251"  background="image/daneshjo_tarh.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
  if (strcmp($status,"entry_finish")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">اطلاعات با موفقيت ثبت شد</td>";
    echo "</tr>";
  }
?>
  <tr>
    <td width="350" align="right"><input type="text" name="name" size="20" value="<? echo $name; ?>" class="edit-user"dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span> نام</td>
  </tr>

 <!-- <tr>
    <td width="350" align="right"><input type="text" name="name_e" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(نام (انگليسي</td>
  </tr>   -->

  <tr>
  <td width="350" align="right"><input type="text" name="family" size="20" value="<? echo $family; ?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>

 <tr>
   <td width="350" align="right"><select size="1" name="sex" class="edit-user" dir="rtl">
      <option value="-1" class="tahoma1">انتخاب کنيد</option>
      <?
	  if(strcmp($sex,"0")==0)
	    $female=" selected ";
	  else
	    $female="";  
	    
	    if(strcmp($sex,"1")==0)
	    $male=" selected ";
	  else
	    $male="";
	  ?>
      <option value="0" <? echo $female; ?> class="tahoma1">زن</option>
      <option value="1"  <? echo $male; ?> class="tahoma1">مرد</option>

    </select></td>
    <td width="150" class="tahoma1">جنسيت</td>
    </tr>
<!--   <tr>
    <td width="350" align="right"><input type="text" name="family_e" value="" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(نام خانوادگي(انگليسي</td>
  </tr>  -->







   <tr>
    <td width="350" align="right" ><select size="1" name="maghtaee_tahsili" class="edit-user" dir="rtl">
    <?
	if(strcmp($maghtaee_tahsili,"0")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option <? echo  $selected; ?> value="0">کارداني</option>
    <?
	if(strcmp($maghtaee_tahsili,"1")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option <? echo  $selected; ?> value="1">کارشناسي</option>
    <?
	if(strcmp($maghtaee_tahsili,"2")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option <? echo  $selected; ?> value="2">کارشناسي ارشد</option>
    <?
	if(strcmp($maghtaee_tahsili,"3")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option <? echo  $selected; ?> value="3">دکتراي حرفه اي</option>
    <?
	if(strcmp($maghtaee_tahsili,"4")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option  <? echo  $selected; ?> value="4">PHD</option>
    <?
	if(strcmp($maghtaee_tahsili,"5")==0)
	  $selected=" selected ";
	else
	  $selected="";
	?>
    <option <? echo  $selected; ?> value="5">دکتراي تخصصي</option>
  </
  </select></td>
    <td width="150" class="tahoma1">مقطع تحصيلي</td>
  </tr>

 <tr>
    <td width="350" align="right"><input type="text" name="reshteh_tahsili" size="20" value="<? echo $reshteh_tahsili; ?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">رشته تحصيلي</td>
  </tr>


  <tr>
    <td width="350" align="right"><input type="text" name="work_addr" size="20" value="<? echo $address_job; ?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">آدرس محل کار</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="work_addr_en" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(آدرس محل کار (انگليسي</td>
  </tr>  -->

    <tr>
    <td width="350" align="right"><input type="text" name="home_addr" size="20" value="<? echo $address_home; ?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">آدرس منزل</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="home_addr_en" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(آدرس منزل (انگليسي</td>
  </tr>   -->

   <tr>
    <td width="350" align="right"><input type="text" name="telno" size="20" value="<? echo $telno; ?>" class="edit-user" ></td>
    <td width="150" class="tahoma1">تلفن</td>
   </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="fax" size="20" value="<? echo $fax; ?>" class="edit-user" ></td>
    <td width="150" class="tahoma1">فاکس</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="email" size="20" value="<? echo $email; ?>" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
  
   <tr>
    <td width="350" align="right"><input type="text" name="cod_melli" size="20" value="<? echo $melli_code; ?>" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد ملي</td>
  </tr>
<?
if(strcmp($action,"edit_daneshjo")!=0)
{
?>
  <tr>
    <td width="350" align="right"><input type="text" name="daneshjo_no" size="20" value="<? echo $cod_daneshjo; ?>" class="edit-user" onkeypress="return checkit()" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>شماره دانشجويي</td>
  </tr>

<?
}
?>
<tr>
    <td width="350" align="right"><input type="text" name="hesab" size="20"  value="<? echo $hesab; ?>" onfocus="hesab.value='' " class="edit-user" onkeypress="return checkit()" ></td>
    <td width="150" class="tahoma1">شماره حساب</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="bank_name" size="20"  value="<? echo $bank_name; ?>" onfocus="bank_name.value='' " class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">نام بانک</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="shoabe" size="20"  value="<? echo $shoabe; ?>" onfocus="shoabe.value='' " class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">شعبه بانک</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="cod_bank" size="20"  value="<? echo $cod_bank; ?>" onfocus="cod_bank.value='' " class="edit-user" onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1">کد بانک</td>
  </tr>


  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="sabt_tarh_second.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
  </tr>
</table>


 <?
   $query="select * from daneshjo , daneshjo_tarh where daneshjo.cod_daneshjo = daneshjo_tarh.cod_daneshjo and daneshjo_tarh.cod_tarh=\"$cod_tarh\"  and daneshjo_tarh.version='-1' ";

   $result=mysql_query($query) or die("Error in selecting data from daneshjo");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"0\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"190\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام خانوادگي</td>";
    echo "<td width=\"184\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    $cod_daneshjo = $myrow_fetched["cod_daneshjo"];
    echo "<tr bgcolor=\"$color\">";
    echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
    //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=daneshjo_tarh.phtml&admin=$admin&seed=$seed&action=delete_daneshjo&cod_tarh=".$cod_tarh."&delete_id=".$myrow_fetched["cod_daneshjo"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"47\"><p align=\"center\"><a href=\"$PHP_SELF?admin=$admin&seed=$seed&action=edit_daneshjo&cod_tarh=".$cod_tarh."&cod_daneshjo=".$myrow_fetched["cod_daneshjo"]."\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
    echo "<td  class=\"tahoma1\" width=\"190\" align=\"right\"><a style=\"text-decoration:none\" href=\"daneshjo_tarh_every_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshjo=$cod_daneshjo\">".substr($myrow_fetched["family"],0,18)."</a></td>";
    echo "<td  class=\"tahoma1\" width=\"184\" align=\"right\"><a style=\"text-decoration:none\" href=\"daneshjo_tarh_every_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshjo=$cod_daneshjo\">".substr($myrow_fetched["name"],0,18)."</a></td>";
    echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   }
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"190\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"184\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
    echo "</tr>";

   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>




