<script>
function checkit()
{
	var key
	key = window.event.keyCode
	
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	{
		if(key!=46)
	      window.event.returnValue= false;
	    else  
	    window.event.returnValue= true
	}

	  
}
</script>
<script type="text/javascript">
      function changeTT() {
        ssSelect = document.getElementById("mojri_code");
        ttSelect = document.getElementById("persons");
        ttSelect = document.getElementById("degree");
        ssValue = ssSelect.options[ssSelect.selectedIndex].value;
        if (ssValue != "-2") {
        document.mojri_tarh.persons.disabled="disabled";
          document.mojri_tarh.degree.disabled="disabled";
        } else {
        	  document.mojri_tarh.persons.disabled=null;
          document.mojri_tarh.degree.disabled=null;
        
          
        }
      }
</script>
<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

if(isset($action))
{
  if (strcmp($action,"add_hazine_personnel")==0)
  {

     if(strlen(trim($per_hour)) > 0 && strlen(trim($majmoa_saat)) > 0  && strlen(trim($activity_type)) > 0  )
     {
   
        $query  = "update hazine_personnel set  mojri_code='$mojri_code' ,degree=\"$degree\",activity_type=\"$activity_type\" , persons=\"$persons\",majmoa_saat=\"$majmoa_saat\",per_hour=\"$per_hour\" where cod_hazine=$cod_hazine and version='-1'";
        
	    $result = mysql_query($query) or die("Error in inserting data into jadval zarayeb");
        $action="ويرايش هزِينه پرسنلي با عنوان "."<br>".$activity_type." با کد ".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));        
        ?>
         <script language="javascript">
           window.location="<? echo "hazine_personnel.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh";  ?>";
           </script>
        <?
       }
     else
       $status="entry_error";
  }

 if (strcmp($action,"delete_hazine")==0)
 {
    $query="delete from hazine_personnel where cod_hazine = \"$delete_id\" and cod_tarh=\"$cod_tarh\"  and version='-1'";

    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
    
    $action="حذف هزينه پرسنلي براي طرح با کد "." با کد ".$cod_tarh;
    set_log($action,$admin,date("Y-m-d, g:i a"));
 }
}

?>

<? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_hazine_personnel&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_hazine=$cod_hazine\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=left width="249"   height=19>
     <a style="text-decoration:none" href="hazine_personnel.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="251"  background="image/hazine_personnel.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
$query="select * from hazine_personnel where cod_hazine='$cod_hazine'";
$res=mysql_query($query) or die("error");
$rf=mysql_fetch_array($res);
$activity_type=$rf["activity_type"];
$persons=$rf["persons"];
$degree=$rf["degree"];
$majmoa_saat=$rf["majmoa_saat"];
$per_hour=$rf["per_hour"];
$mojri_code=$rf["mojri_code"];


  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>


 <tr>
  <?
  
   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";	
	$result1=mysql_query($query1) or die("Error");
	
   $query2="select distinct mojri.* from mojri_tarh , tarh,mojri  where mojri.mojri_code=mojri_tarh.mojri_code and mojri_tarh.cod_tarh = tarh.cod_tarh  and tarh.cod_tarh=\"$cod_tarh\" ";
   $result2=mysql_query($query2) or die("Error in selecting data from mojri_tarh");
 

  ?>
    <td width="350" align="right"><select onchange="changeTT();" size="1" name="mojri_code" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <option value="-2" class="tahoma1">*</option>
    <?

    while($row_fetched=mysql_fetch_array($result1))
    {
    	 $darajeelmi=$row_fetched["darajeelmi"];
	   	 $q="select * from darajeelmi where darajeelmi='$darajeelmi'";
	   	  
	    $daraje_query_result=mysql_query($q);
	   $mojri_name_family=$row_fetched["name"]."&nbsp;".$row_fetched["family"];
	    if(mysql_num_rows($daraje_query_result)>0)
	    {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    }
	    if(strcmp($mojri_code,$row_fetched["email"])==0)
	     $selected= " selected ";
	    else 
	     $selected = ""; 
      echo "<option $selected value=\"".$row_fetched["email"]."\" class=\"tahoma1\">".$mojri_name_family."</option>";
    }
     while($row_fetched=mysql_fetch_array($result2))
    {
    	
      $darajeelmi=$row_fetched["darajeelmi"];
	   	 $q="select * from darajeelmi where darajeelmi='$darajeelmi'";
	   	  
	    $daraje_query_result=mysql_query($q);
	   $mojri_name_family=$row_fetched["name"]."&nbsp;".$row_fetched["family"];
	    if(mysql_num_rows($daraje_query_result)>0)
	    {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    }
	     if(strcmp($mojri_code,$row_fetched["mojri_code"])==0)
	     $selected= " selected ";
	    else 
	     $selected = ""; 
	    
      echo "<option  $selected  value=\"".$row_fetched["mojri_code"]."\" class=\"tahoma1\">".$mojri_name_family."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">نام مجري / همکار / ديگر افراد</td>
  </tr>
 
  <tr>
    <td width="350" align="right"><input type="text" <? echo "value=\"$activity_type\""; ?> name="activity_type" size="20" value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نوع فعاليت</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" <? echo "value=\"$persons\""; ?> name="persons" size="20" value="" class="edit-user" onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1" ><span class="star-message">*</span>تعداد افراد</td>
  </tr>


   <tr>
  <?
    $query="select * from darajeelmi order by darajeelmi_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi 1");

  ?>
    <td width="350" align="right"><select size="1" name="degree" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
    	if(strcmp($degree,$row_fetched["darajeelmi"])==0)
    	  $selected=" selected ";
    	else
		  $selected="";  
      echo "<option $selected value=\"".$row_fetched["darajeelmi"]."\" class=\"tahoma1\">".$row_fetched["darajeelmi_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">درجه علمي</td>
  </tr>
  
  
  
  <tr>
    <td width="350" align="right"><input type="text" <? echo "value=\"$majmoa_saat\""; ?> name="majmoa_saat" size="20" value="" class="edit-user"  onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1" ><span class="star-message">*</span>مجموع ساعات</td>
  </tr>

 <tr>
 <td width="350" align="right"><input type="text"  <? echo "value=\"$per_hour\""; ?> name="per_hour" size="20" value="" class="edit-user"  onkeypress="return checkit()"></td>
 <td width="150" class="tahoma1"><span class="star-message">*</span>حق الزحمه در ساعت</td>
 </tr>

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>


<?
 footer_forms($admin,$seed);
?>