<html>
<?

include("include/styles.phtml");
include("include/database-connect.phtml");
?>
<head>
<title>ويرايش وضعيت طرح</title>
<script language="javascript" src="js/farsi.js"></script>

<script language="javascript">
function refreshmain()
{
   opener.location="<? echo "vaziat-tarh.phtml?admin=$admin&seed=$seed";  ?>";

   self.close();
}

</script>


</head>
<body>

<?

 if(strlen($edit_id) > 0)
 {
   $query="select * from vaziat_tarh where vaziat=$edit_id";
//   echo $query;
   $result=mysql_query($query) or die("error in selecting data from daraje elmi");
   $row_fetched_val=mysql_fetch_array($result);
   
 }

if (strcmp($action,"save")==0)
{
  if(strlen($edit_id) > 0 && strlen(trim($vaziat)) > 0 && strlen(trim($vaziat_english)) > 0 )
  {
  	
if(isset($view_or_no))
{
  if(strcmp($view_or_no,"on")==0)
	$view_ok = 1;
  else
	$view_ok=0;
}
else
 $view_ok=0;
	
	
    $query="update vaziat_tarh set vaziat_desc='$vaziat', vaziat_english_desc='$vaziat_english',vaziat_english_desc='$vaziat_english',from_mail='$email_from',from_name='$email_from_name',from_subject='$email_from_subject',from_body='$email_body',view_or_no=$view_ok where  vaziat=$edit_id";
    $result=mysql_query($query) or die("Error in updating data in vaziat-tarh");
    ?>
    <script language="javascript">
    refreshmain();
    </script>
    <?

  }
  else
  {
   ?>
    <script language="javascript">
      self.close();
    </script>

   <?
  }

}

?>





<form method="POST" action="<? echo "edit_vaziat_tarh.phtml?admin=$admin&seed=$seed&action=save&edit_id=$edit_id"; ?>">

<table border="0" width="100%" height="100%" align="center" cellpading="0" cellspacing="0">
    <tr>
      <td width="50%" align="right"><input type="text" name="vaziat" class="edit-tarh-type"  dir=RTL    value="<? echo $row_fetched_val["vaziat_desc"]; ?>"></td>
      <td width="50%"><p class="tahoma1">درجه علمي</p></td>
    </tr>
     <tr>
      <td width="50%" align="right"><input type="text" name="vaziat_english" class="edit-tarh-type"  value="<? echo $row_fetched_val["vaziat_english_desc"]; ?>"></td>
      <td width="50%"><p class="tahoma1">(درجه علمي (انگليسي</p></td>
    </tr>
    
                <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">در قسمت زير مشخصات پست الکترونيکي</span></td>
            </tr>
            <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">که پس از تغيير وضعيت فرد به ايشان</span></td>
            </tr>
            <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">ارسال مي شود مشخص ميشود</span></td>
            </tr>

            <tr>
              <td width="250" align="right">
                <p align="right"><input type="text" name="email_from" size="48" class="edit-tarh-type"  value="<? echo $row_fetched_val["from_mail"]; ?>" ></td>
              <td width="150" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>e-mail آدرس مبدا </td>
            </tr>

            <tr>
              <td width="250" align="right">
                <p align="right"><input type="text" name="email_from_name" size="48" class="edit-tarh-type"  value="<? echo $row_fetched_val["from_name"]; ?>" ></td>
              <td width="150" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>e-mail نام مبدا </td>
            </tr>

            <tr>
              <td width="250" align="right">
                <p align="right"><input type="text" name="email_from_subject" size="48" class="edit-tarh-type"  value="<? echo $row_fetched_val["from_subject"]; ?>" ></td>
              <td width="150" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>e-mail موضوع </td>
            </tr>

            <tr>
              <td width="250" align="right">
                <p align="right"><textarea type="text" name="email_body" size="48" class="edit-tarh-type" ><? echo $row_fetched_val["from_body"]; ?></textarea></td>
              <td width="150" align="left" VALIGN="TOP">
                <p align="left" class="tahoma1"><span class="star-message">*</span>متن نامه</td>
            </tr>
    
    
     <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">در قسمت زير مشخص ميشود که طرحهاي</span></td>
            </tr>
            <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">با اين وضعيت قابل مشاهده توسط کاربران</span></td>
            </tr>
            <tr>
              <td width="100%" align="center" colspan="2">
                <p align="center" class="tahoma1"><span class="star-message">در صفحه اصلي هست يا خير</span></td>
            </tr>
<?
if(strcmp($row_fetched_val["view_or_no"],"1")==0)
  $checked=" checked " ;
else
  $checked="" ;  
  
?>
            <tr>
              <td width="250" align="right">
                <p align="right"><input <? echo $checked; ?> type="checkbox" name="view_or_no" size="48"  ></td>
              <td width="150" align="left">
                <p align="left" class="tahoma1">قابل مشاهده در وب سايت</td>
            </tr>

    <tr>
    <td align="center" colspan="2">
      <input type="button" value="بستن" name="close" class="but-small"  onclick="javascript: window.close()">&nbsp;<input type="submit" value="ثبت" name="submit" class="but-small">
    </td>
    </tr>
  </table>

 </form>
</body>
</html>
