<html>
<?
include("include/styles.phtml");
include("include/database-connect.phtml");
?>
<head>
<title>ويرايش درجه علمي</title>
<script language="javascript" src="js/farsi.js"></script>

<script language="javascript">
function refreshmain()
{
   opener.location="<? echo "maghta_payan_name.phtml?admin=$admin&seed=$seed";  ?>";

   self.close();
}

</script>


</head>
<body>

<?

 if(strlen($edit_id) > 0)
 {
   $query="select * from maghta_payan_name where maghta_payan_name=$edit_id";
   $result=mysql_query($query) or die("error in selecting data from daraje elmi");
   $row_fetched_val=mysql_fetch_array($result);
   
 }

if (strcmp($action,"save")==0)
{
  if(strlen($edit_id) > 0 && strlen(trim($daraje_elmi)) > 0 && strlen(trim($daraje_elmi_english)) > 0 )
  {
    $query="update maghta_payan_name set maghta_payan_name_desc='$daraje_elmi', maghta_payan_name_english_desc='$daraje_elmi_english' where maghta_payan_name=$edit_id";
   
    $result=mysql_query($query) or die("Error in updating data in edittarh");
    ?>
    <script language="javascript">
    refreshmain();
    </script>
    <?

  }
  else
  {
   ?>
    <script language="javascript">
      self.close();
    </script>

   <?
  }

}

?>





<form method="POST" action="<? echo "edit_maghta_payan_name.phtml?admin=$admin&seed=$seed&action=save&edit_id=$edit_id"; ?>">

<table border="0" width="100%" height="100%" align="center" cellpading="0" cellspacing="0">
    <tr>
      <td width="50%" align="right"><input type="text" name="daraje_elmi" class="edit-tarh-type"  dir=RTL    value="<? echo $row_fetched_val["maghta_payan_name_desc"]; ?>"></td>
      <td width="50%"><p class="tahoma1">مقطع پايان نامه</p></td>
    </tr>
     <tr>
      <td width="50%" align="right"><input type="text" name="daraje_elmi_english" class="edit-tarh-type"  value="<? echo $row_fetched_val["maghta_payan_name_english_desc"]; ?>"></td>
      <td width="50%"><p class="tahoma1">(مقطع پايان نامه (انگليسي</p></td>
    </tr>
    <tr>
    <td align="center" colspan="2">
      <input type="button" value="بستن" name="close" class="but-small"  onclick="javascript: window.close()">&nbsp;<input type="submit" value="ثبت" name="submit" class="but-small">
    </td>
    </tr>
  </table>

 </form>
</body>
</html>
