<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>

<script>
function checkit(){
	var key
	key = window.event.keyCode
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	  window.event.returnValue= false;

}
</script>

<?
echo "<br>";


if (strcmp($action,"add")==0)
{
  if(strlen(trim($tarh_name)) > 0 && strlen(trim($tarh_english_name)) > 0 )
  {
    $query="select * from file_type  where  file_type=\"$tarh_name\" ";

    $result=mysql_query($query) or die("Error in query data from tarh-type");
    if(mysql_num_rows($result) <= 0)
    {
      $query="insert into file_type set  file_type='$tarh_name',file_type_en='$tarh_english_name'";
	  //echo $query;
      mysql_query($query) or die ("Error in inserting data in tarh-type");
    }
     else
      $status="duplicate_entry";
  }
  else
   $status="entry_error";
}


if (strcmp($action,"delete")==0)
{ 
  if(strlen(trim($delete_id)) > 0 )
  {
    $query="select * from file_type where  cod_file_type=\"$delete_id\"";

    $result=mysql_query($query) or die("Error in query data from tarh-type");
  
    if(mysql_num_rows($result) > 0)
    {
      $query="select * from file_sharing  where  file_type =\"$delete_id\"";

      $result=mysql_query($query) or die("Error in query data from tarh-type");	
      
      if(mysql_num_rows($result) <=0 )
      {
      
      		 
        $query="delete from file_type where cod_file_type='$delete_id'";

        mysql_query($query) or die ("Error in inserting data in tarh-type1");
      }
       else
       $status='delete_error';
    }

  }
}




?>



<? echo "<form name=\"add-tarh\" method=\"post\"  action=\"$PHP_SELF?action=add&admin=$admin&seed=$seed\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="400" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/tarh-type.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="400" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  if (strcmp($status,"delete_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">بدليل استفاده از اين نوع طرح ، اين مورد قابل حذف نيست</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">
        <div align="center">
          <table border="0" width="100%" bgcolor="F0F0FF" height="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="tarh_name" size="48" class="edit-tarh-type"  dir=RTL   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>نوع فايل</td>
            </tr>
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="tarh_english_name" size="48" class="edit-tarh-type" ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>(نوع فايل (انگليسي</td>
            </tr>
              
            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="اضافه" name="submit_tarh"></td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
  </table>
</form>
<br>

<?
 
if(DBreccount("tarhtype") > 0)
{
    echo "<table border=\"0\" width=\"400\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"274\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نوع فايل</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
  $Query=mysql_query("select * from file_type order by file_type desc") or die("Error in selecting tarh-type");
  while($row_fetched=mysql_fetch_array($Query))
  {
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
  echo "<tr bgcolor=\"$color\">";
  echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
  echo "<td width=\"47\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"delete_or_apply_tarh_type.phtml?mainwindow=file_type.phtml&admin=$admin&seed=$seed&action=delete&delete_id=".$row_fetched["cod_file_type"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
  echo "<td width=\"47\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"edit_file_type.phtml?mainwindow=tarh-type.phtml&admin=$admin&seed=$seed&action=delete&edit_id=".$row_fetched["cod_file_type"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=380,height=120,left=((screen.width-320) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\"></td>";
  echo "<td width=\"274\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".substr($row_fetched["file_type"],0,200)."</td>";
  echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
  echo "</tr>";

  }
  echo "<tr>";
  echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"274\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
  echo "</tr>";
  echo "</table>";
}
else
{

  echo "<p align=\"center\"  class=\"tahoma1\">با کليک روي کليد اضافه ميتوانيد يک نوع فايل اضافه کنيد";

}

   footer_forms($admin,$seed);
?>



