<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";

if(isset($action))
{
	
	
	
  if (strcmp($action,"sabt")==0)
  {
  
  
  
	 $file_cnt=0;
     $dir_name="../file_sharing/".$cod_tarh;
     if ($dir = @opendir($dir_name))
     {
     
     $mydir = dir($dir_name);
     //while(($file = $mydir->read()) !== false)
     while($file = $mydir->read())
	   if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0) )
	    $file_cnt++;
      closedir($dir);
     
	 }

  
  
  
  
  
  
  
	 
       $status_upload=upload_file("../file_sharing",'',"");
       if(!strcmp($status_upload,"10") == 0 )
	     $status="upload_error";
	   else 
	   {
	   
	   	$fupload_name=$_FILES["fupload"]["name"];
	   	$send_date=date("Y-m-d");
	   	$query="insert into  file_sharing set filename='$fupload_name',comments='$comments',send_date='$send_date',file_type='$file_type_file',daneshkade_view='$daneshkade_view',mostaghel_view='$mostaghel_view'";
	   	 
	   	$r_update=mysql_query($query) or die("Error");
	   	
	   }
 
     
  }
  
   if (strcmp($action,"delete_file")==0)
  {
  	$query="select * from file_sharing where id='$delete_id'";
  	$result=mysql_query($query);
  	
  	$row_fetched=mysql_fetch_array($result);
  	$delete_filename=$row_fetched["filename"];
  	$del_file="../file_sharing/";
    delete_file($del_file,"",$delete_filename);
    $query="delete  from file_sharing where id='$delete_id'";
    //echo $query;
  	$result=mysql_query($query);
    
  }
  
	if (strcmp($action,"edit_file")==0)
  {
  	$query="update file_sharing set comments='$comments',file_type='$file_type_file',daneshkade_view='$daneshkade_view',mostaghel_view='$mostaghel_view' where id='$id'";
	  	$r_update=mysql_query($query) or die("Error");
  	
  	
  }
}
if(strcmp($action,"edit")==0){
$query="select * from file_sharing where id='$id'";
  	$result=mysql_query($query);
  	$row_fetched=mysql_fetch_array($result);
  	$file_name_edit=$row_fetched['filename'];
  	$comment_edit=$row_fetched['comments'];
  	$file_type=$row_fetched['file_type'];
}
?>

<?if(strcmp($action,"edit")==0)
{ echo "<form name=\"mojri_tarh_esit\" method=\"post\" enctype=\"multipart/form-data\" action=\"$PHP_SELF?action=edit_file&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&marhale=$marhale&id=$id\">"; }

else {
	echo "<form name=\"mojri_tarh\" method=\"post\" enctype=\"multipart/form-data\" action=\"$PHP_SELF?action=sabt&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&marhale=$marhale\">";} ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=left width="249"   height=19>    
    <a style="text-decoration:none" href="send_report.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="251" height=19 align="right" class="tahoma1">ارسال فايل
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>



<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">

<?


 if (strcmp($status_upload,"-5") == 0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين فايلي قبلا بارگذاري شده</td>";
    echo "</tr>";
  }
 echo "<tr>";
    echo "<td align=\"center\" dir='rtl' class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">حداکثر حجم فايل 2 مگابايت مي باشد. نام فايل را انگليسي و بدون فاصله وارد کنيد<br> فايل ارسالي بايد به فرمت Word يا PDF باشد.صرفا از فونت زر استفاده کنيد </td>";
    echo "</tr>";
    
    
 


 



if (strcmp($status_upload,"-2") == 0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">قابل بارگذاري هستند Ms word و Adobe Acrobat  تنها فايلهاي</td>";
    echo "</tr>";
  }

 
?>
 <tr>
     <td width="100" align="right"><input type="text" value="<?echo $comment_edit;?>" name="comments" class="edit-user" dir=RTL    ></td>
    <td width="400" class="tahoma1" valign="top" >توضيح
  </tr>

  <tr>
     <td width="100" align="right"><input type="file" name="fupload" class="edit-user" value="<?echo $file_name_edit;?>"></td>
    <td width="400" class="tahoma1" valign="top" >نام فايل
  </td></tr>
<?
	$query="select * from file_type";
	 $result=mysql_query($query) or die("Error");
  ?>
  <tr>
  <td width="100" align="right"><select name="file_type_file" size="1" class="edit-user" dir="rtl">
  <option value="-1" class="tahoma1">انتخاب کنيد</option>
  <?
   while($row_fetched=mysql_fetch_array($result))
   {
   	    	if($file_type==$row_fetched["cod_file_type"])
    		$selected="selected";
    	else 
    		$selected="";
   	 echo "<option $selected value=\"".$row_fetched["cod_file_type"]."\" class=\"tahoma1\">".$row_fetched["file_type"]."</option>";
   }
  ?>
  </select></td>
   <td width="400" class="tahoma1" valign="top" >نوع فايل
  </td>
  </tr>
  
  <tr>
     <td width="100" align="right"><input type="checkbox"  name="daneshkade_view" value="1" class="edit-user" dir=RTL  ></td>
    <td width="400" class="tahoma1" valign="top" >مشاهده توسط ادمين دانشکده
  </tr>
  
   <tr>
     <td width="100" align="right"><input type="checkbox"  name="mostaghel_view" value="1" class="edit-user" dir=RTL  ></td>
    <td width="400" class="tahoma1" valign="top" >مشاهده توسط ادمين مرکز مستقل
  </tr>

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>

</form>

  <?
  $query="select * from file_sharing where 1";
   
  $result=mysql_query($query) or die("Error");
   
     $mycount=0;
    if(mysql_num_rows($result) > 0)
    {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
       echo "<tr>";      
      echo "<td width=\"100%\" colspan='5' align=\"center\"  class=\"tahoma1\"><b>با کليک روي نام فايل محتويات آن قابل مشاهده مي باشد</b></td>";
      echo "</tr>";
      
      echo "<tr>";
      echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">حذف</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نوع فايل</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">توضيحات</td>";
      echo "</tr>";

     //echo $dir_name;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$id=$row_fetched["id"];
     	$file_type1=$row_fetched["file_type"];
     	
     	$query1="select * from file_type where cod_file_type='$file_type1'";
	 	$result1=mysql_query($query1) or die("Error");
     	$row_fetched1=mysql_fetch_array($result1);
     	$file_type_name=$row_fetched1['file_type'];
     	if($file_type1=="")
     		$file_type_name="ثبت";
	     echo "<tr>"; 
         echo "<td width=\"5%\"  align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=file_sharing.phtml&admin=$admin&seed=$seed&action=delete_file&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\"><a href=\"file_sharing.phtml?admin=$admin&seed=$seed&action=edit&id=$id\">".$file_type_name."</a></td>"; 	 
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\"><a target=\"_blank\" href=\"../file_sharing/$cod_tarh/$file".$row_fetched["filename"]."\">".$row_fetched["filename"]."</a></td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["send_date"]."</td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["comments"]."</td>";
         echo "</tr>";
	   
     }
       
      echo "</table>";
	 }
     
    
     

  

 footer_forms($admin,$seed);
?>





 