<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
echo "<br>";
echo "<br>";
echo "<br>";
 $query="select * from modir_daneshkade where modir_username='$admin'";
 $result=mysql_query($query) or die("Error");
 $rf=mysql_fetch_array($result) or die("Error");
 $cod_daneshkade=$rf["cod_daneshkade"];
 
 $query="select distinct marhale_report.*,tarh.tarh_title_farsi  from tarh,marhale_report where tarh.cod_tarh=marhale_report.cod_tarh and tarh.cod_daneshkade='$cod_daneshkade' and submit_subadmin='0' ";
  $query="select distinct marhale_report.*,tarh.tarh_title_farsi ,tarh.cod_tarh,tarh.cod_daneshkade from tarh,marhale_report where tarh.cod_tarh=marhale_report.cod_tarh   and submit_subadmin='0' and marhale='100' and adddate(marhale_report.send_date,'7')<'".date("Y-m-d")."'";

 
  //$query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
   
  $result=mysql_query($query) or die("Error");
   
     $mycount=0;
    if(mysql_num_rows($result) > 0)
    {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"90%\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\" bgcolor= $title_color  colspan='6' align=\"center\"  class=\"tahoma1\"><b>گزارشاتي که ساب ادمين آنها را تاييد نکرده و مدت يک هفته از ارسال آنها گذشته</b></td>";
      echo "</tr>";
      echo "<tr>";
        echo "<td width=\"10%\"  bgcolor= $title_color  align=\"center\"  class=\"tahoma1\">تاييد گزارش</td>"; 
      echo "<td width=\"10%\" bgcolor= $title_color  align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "<td width=\"5%\"   bgcolor= $title_color align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
      echo "<td width=\"10%\"   bgcolor= $title_color  align=\"center\"  class=\"tahoma1\">توضيحات</td>";
      echo "<td width=\"10%\"  bgcolor= $title_color  align=\"center\"  class=\"tahoma1\">دانشکده</td>";
      echo "<td width=\"55%\"  bgcolor= $title_color  align=\"center\"  class=\"tahoma1\">نام طرح</td>";
      echo "</tr>";
     $color=$list_color_1;

     //echo $dir_name;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$id=$row_fetched["id"];
     	$cod_tarh=$row_fetched["cod_tarh"];
     	$marhale=$row_fetched["marhale"];
     	
     	$startdate = $row_fetched["send_date"];
  		$startyear = substr($startdate,0,4);
  		$startmon = substr($startdate,5,2);
  		$startday = substr($startdate,8,2);
  		$farsistartdate=hijricalender( $startyear , $startmon , $startday );
  		$farsistartdate = enum2fnum($farsistartdate);
  		$comments=$row_fetched["comments"];
  		$cod_daneshkade=$row_fetched["cod_daneshkade"];
  		$q="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  		$rs=mysql_query($q) or die("error");
  		$rf1=mysql_fetch_array($rs);
  		$daneshkade=$rf1["daneshkade_name"];
  		if(strlen($comments) <=0)
  		 $comments="&nbsp;";
	      echo "<tr>";
        // echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=send_marhale_report.phtml&admin=$admin&seed=$seed&action=delete_file&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         echo "<td width=\"10%\" align=\"center\" bgcolor=$color class=\"tahoma1\"><a  href=\"submit_marhale.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&marhale=$marhale\">تاييد</a></td>";
         echo "<td width=\"10%\"  align=\"center\" bgcolor=$color class=\"tahoma1\"><a target=\"_blank\" href=\"../reports/$cod_tarh/$file".$row_fetched["filename"]."\">".$row_fetched["filename"]."</a></td>";
         echo "<td width=\"5%\"  align=\"center\" bgcolor=$color class=\"tahoma1\">".$farsistartdate."</td>";
         echo "<td width=\"10%\"  align=\"center\" bgcolor=$color class=\"tahoma1\">".$comments."</td>";
         echo "<td width=\"10%\"  align=\"center\" bgcolor=$color class=\"tahoma1\">".$daneshkade."</td>";
          echo "<td width=\"55%\"  align=\"center\" bgcolor=$color class=\"tahoma1\" dir='rtl'>".$row_fetched["tarh_title_farsi"]."</td>";
         echo "</tr>";
	   
     }
       echo "<tr>";
       echo "<td width=\"55%\"  colspan='6' align=\"center\"  class=\"tahoma1\" dir='rtl'><b>ليست فوق گزارشات نهايي طرح هايي است که از مدت ارسال آنها يک هفته يا بيشتر گذشته شما ميتوانيد آنها را تاييد کنيد </b></td>";
       echo "</tr>";
      echo "</table>";
	 }
	 else 
	 {
	 	 echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\"  colspan='3' align=\"center\"  class=\"tahoma1\">موردي يافت نشد</td>";
      echo "</tr>";
      echo "</table>";
      
	 }
     
    
     

  

 footer_forms($admin,$seed);
?>



 
