<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";
   $query="select * from group_karshenasan where cod_karshenas=$cod_karshenas  order by  karshenas_name ";

   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";


    echo "<table border=\"0\" width=\"60%\"  cellspacing=\"1\" cellpadding=\"1\" >";
    $color="PALETURQUOISE";
    $row_fetched=mysql_fetch_array($result);
    echo "<tr>";
    echo "<td width=\"100%\" colspan=\"2\" bgcolor=$color  class=\"tahoma1\" align=\"center\">مشخصات کارشناس </td>";
    echo "</tr>";
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">نام</td>";
    echo "</tr>";

    

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">نام خانوادگي</td>";
    echo "</tr>";

    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["shenasname"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">شماره شناسنامه</td>";
    echo "</tr>";

    
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["melli_code"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">کد ملي</td>";
    echo "</tr>";








    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">پست الکترونيکي</td>";
    echo "</tr>";

    $karshenas_rade_elmi=$row_fetched["karshenas_rade_elmi"];
    $query="select * from darajeelmi  where darajeelmi = $karshenas_rade_elmi ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    $my_row_daraje = mysql_fetch_array($qresult);
    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$my_row_daraje["darajeelmi_desc"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">درجه علمي</td>";
    echo "</tr>";

    echo "<tr>";
    echo "<td width=\"60%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_takhasos"]."</td>";
    echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\">تخصص</td>";
    echo "</tr>";


   

    echo "</table>";
   }
?>

<?
footer_forms($admin,$seed);
?>
