<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>
 
<script>
function checkit()
{
	var key
	key = window.event.keyCode
	
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	{
		if(key!=46)
	      window.event.returnValue= false;
	    else  
	    window.event.returnValue= true
	}

	  
}
</script>
<script type="text/javascript">
      function changeTT() {
        ssSelect = document.getElementById("mojri_code");
        ttSelect = document.getElementById("persons");
        ttSelect = document.getElementById("degree");
        ssValue = ssSelect.options[ssSelect.selectedIndex].value;
        if (ssValue != "-2") {
        document.mojri_tarh.persons.disabled="disabled";
          document.mojri_tarh.degree.disabled="disabled";
        } else {
        	  document.mojri_tarh.persons.disabled=null;
          document.mojri_tarh.degree.disabled=null;
        
          
        }
      }
</script>

 
<?


echo "<br>";

if(isset($action))
{
  if (strcmp($action,"add_hazine_personnel")==0)
  {
 
     if(strlen(trim($per_hour)) > 0 && strlen(trim($majmoa_saat)) > 0 && strlen(trim($activity_type)) > 0  )
     {
      $query="select * from hazine_personnel where  activity_type=\"$activity_type\" and cod_tarh=\"$cod_tarh\"  and version='-1'";
      $result=mysql_query($query) or die("Error in selecting data from  jadval zarayeb ");
      if ( mysql_num_rows($result) <= 0 )
      {
      	$per_hour=str_replace(",","",$per_hour);
      	$majmoa_saat=str_replace(",","",$majmoa_saat);
      	$persons=str_replace(",","",$persons);
        $query  = "insert into hazine_personnel set mojri_code='$mojri_code' ,degree=\"$degree\",activity_type=\"$activity_type\" , persons=\"$persons\",majmoa_saat=\"$majmoa_saat\",per_hour=\"$per_hour\",cod_tarh=\"$cod_tarh\",version=\"-1\"";
      // echo $query;
        $result=mysql_query($query);
        $action="ثبت هزِينه پرسنلي با عنوان "."<br>".$activity_type." با کد ".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));        

      }
      else
       {
        $status="duplicate_entry";
       }
     }
     else
       $status="entry_error";
  }

 if (strcmp($action,"delete_hazine")==0)
 {
    $query="delete from hazine_personnel where cod_hazine = \"$delete_id\" and cod_tarh=\"$cod_tarh\"  and version='-1'";

    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
    
    $action="حذف هزينه پرسنلي براي طرح با کد "." با کد ".$cod_tarh;
    set_log($action,$admin,date("Y-m-d, g:i a"));
 }
}

?>

<? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_hazine_personnel&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=left width="249"   height=19>
     <a style="text-decoration:none" href="hazineha.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
      <TD align=middle width="251"  background="image/hazine_personnel.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>
  
<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="0"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">کليه هزينه ها به ريال ميباشد</td>";
    echo "</tr>";
  if (strcmp($status,"entry_error")==0)
  {
  	
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
   echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">در صورتيکه هزينه پرسنلي مربوط به مجري يا همکاران نمي باشد * را براي نام فرد انتخاب کنيد</td>";
    echo "</tr>";
?>
 <tr>
  <?
   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";	
	$result1=mysql_query($query1) or die("Error");
	
   $query2="select distinct mojri.* from mojri_tarh , tarh,mojri  where mojri.mojri_code=mojri_tarh.mojri_code and mojri_tarh.cod_tarh = tarh.cod_tarh  and tarh.cod_tarh=\"$cod_tarh\" ";
   $result2=mysql_query($query2) or die("Error in selecting data from mojri_tarh");
 

  ?>
    <td width="350" align="right"><select onchange="changeTT();" size="1" name="mojri_code" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <option value="-2" class="tahoma1">*</option>
    <?

    while($row_fetched=mysql_fetch_array($result1))
    {
    	 $darajeelmi=$row_fetched["darajeelmi"];
	   	 $q="select * from darajeelmi where darajeelmi='$darajeelmi'";
	   	  
	    $daraje_query_result=mysql_query($q);
	   $mojri_name_family=$row_fetched["name"]."&nbsp;".$row_fetched["family"];
	    if(mysql_num_rows($daraje_query_result)>0)
	    {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    }
      echo "<option value=\"".$row_fetched["email"]."\" class=\"tahoma1\">".$mojri_name_family."</option>";
    }
     while($row_fetched=mysql_fetch_array($result2))
    {
    	
      $darajeelmi=$row_fetched["darajeelmi"];
	   	 $q="select * from darajeelmi where darajeelmi='$darajeelmi'";
	   	  
	    $daraje_query_result=mysql_query($q);
	   $mojri_name_family=$row_fetched["name"]."&nbsp;".$row_fetched["family"];
	    if(mysql_num_rows($daraje_query_result)>0)
	    {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    }
      echo "<option value=\"".$row_fetched["mojri_code"]."\" class=\"tahoma1\">".$mojri_name_family."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">نام مجري / همکار / ديگر افراد</td>
  </tr>
   <tr>
    <td width="500" colspan='2' class="tahoma1" align="middle"><b>مجري محترم ، در وارد کردن کليه هزينه هاي طرح خود از اعداد بدون جدا کننده (, - / ) استفاده کنيد <br></b></td>
  </tr>
  <tr>
    <td width="350" align="right"><input type="text" name="activity_type" size="20" value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نوع فعاليت</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="persons" size="20" value=""  onkeyup="MakingMoneyForm(this)"class="edit-user" onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1" ><span class="star-message">*</span>تعداد افراد</td>
  </tr>


   <tr>
  <?
    $query="select * from darajeelmi order by darajeelmi_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi 1");

  ?>
    <td width="350" align="right"><select size="1" name="degree" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
      echo "<option value=\"".$row_fetched["darajeelmi"]."\" class=\"tahoma1\">".$row_fetched["darajeelmi_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">درجه علمي</td>
  </tr>
  
  
  
  <tr>
    <td width="350" align="right"><input type="text" name="majmoa_saat" size="20"  onkeyup="MakingMoneyForm(this)" value="" class="edit-user"  onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1" ><span class="star-message">*</span>مجموع ساعات</td>
  </tr>

  <tr>
 <td width="350" align="right"><input type="text" name="per_hour" size="20"  onkeyup="MakingMoneyForm(this)" value="" class="edit-user"  onkeypress="return checkit()"></td>
 <td width="150" class="tahoma1"><span class="star-message">*</span>حق الزحمه در ساعت</td>
 </tr>


 
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>




  <?
   $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1'  ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
     echo "<tr>";
     
     echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">حذف</td>";
     echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">ويرايش</td>";
	 echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">جمع</td>";
     echo "<td width=\"20%\" align=\"center\" class=\"tahoma1\">حق الزحمه در ساعت</td>";
     echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">مجموع ساعات</td>";
     echo "<td width=\"26%\"  align=\"center\"  class=\"tahoma1\">درجه تحصيلي</td>";
     echo "<td width=\"14%\"  align=\"center\"  class=\"tahoma1\">تعداد افراد</td>";
     echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نوع فعاليت</td>";
     echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نام مجري / همکار / ديگر افراي</td>";
     echo "</tr>";

   
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $daraje_mojri="";
       $mojri_name_family="*";
     
       $mojri_code=$row_fetched["mojri_code"];
      // echo $mojri_code;
       if(strcmp($mojri_code,'-1')!=0 && strcmp($mojri_code,'-2')!=0)
       {
        $query1="select distinct user_login.* from user_login  where user_login.email='$mojri_code'";
        $result1=mysql_query($query1) or die("Error");
        
        if(mysql_num_rows($result1)>0)		   
	    {
	   	
	   	 $myrf=mysql_fetch_array($result1);
	   	 $mojri_name_family=$myrf["name"]."&nbsp;".$myrf["family"];
	   	
	   	 $darajeelmi=$myrf["darajeelmi"];
	     $daraje_query_result=mysql_query("select * from darajeelmi where darajeelmi='$darajeelmi'");
	   
	     if(mysql_num_rows($daraje_query_result)>0)
	     {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	///$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    	$daraje_mojri=$daraje_rf["darajeelmi_desc"];
	    	// echo $darajeelmi."a".$daraje_mojri;
	     }
	   	
	     }
	
       $query2="select distinct mojri.* from  mojri  where mojri.mojri_code= '$mojri_code'";
       $result2=mysql_query($query2) or die("Error in selecting data from mojri_tarh");
      // if(strlen($daraje_mojri)<=0)
        if(mysql_num_rows($result2)>0)		   
	   {
	   	
	   	$myrf=mysql_fetch_array($result2);
	   	$mojri_name_family=$myrf["name"]."&nbsp;".$myrf["family"];
	    $darajeelmi=$myrf["darajeelmi"];
	    $daraje_query_result=mysql_query("select * from darajeelmi where darajeelmi='$darajeelmi'");
	   
	    if(mysql_num_rows($daraje_query_result)>0)
	    {
	    	$daraje_rf=mysql_fetch_array($daraje_query_result);
	    	///$mojri_name_family=$mojri_name_family."-".$daraje_rf["darajeelmi_desc"];
	    	$daraje_mojri=$daraje_rf["darajeelmi_desc"];
	    	//echo $darajeelmi."a".$daraje_mojri;
	    }
	   	
	   }
       }
       echo "<tr>";
       $cod_hazine=$row_fetched["cod_hazine"];
//       echo "<td align=\"center\" class=\"tahoma1\"><img src=\"image/button_drop.png\" border=0 alt=\"Delete\"></td>";
       echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=hazine_personnel.phtml&admin=$admin&seed=$seed&action=delete_hazine&cod_tarh=".$cod_tarh."&delete_id=".$row_fetched["cod_hazine"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
       echo "<td ><p align=\"center\"><a href=\"edit_hazine_personnel.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_hazine=$cod_hazine\" ><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
       $a=$row_fetched["per_hour"];
       $b=$row_fetched["majmoa_saat"];
       $c=$row_fetched["persons"];
       if(strcmp($mojri_code,'-1')!=0 && strcmp($mojri_code,'-2')!=0)          
         $my_summary = $a*$b;
       else 
         $my_summary = $a*$b;  
       $mycount=$mycount+$my_summary;
       echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">".number_format($my_summary)."</td>";
       echo "<td align=\"center\"  class=\"tahoma1\" >".number_format($row_fetched["per_hour"])."</td>";
       echo "<td align=\"center\"  class=\"tahoma1\" >".number_format($row_fetched["majmoa_saat"])."</td>";
      //  echo "b".$daraje_mojri;
         if(strcmp($mojri_code,'-1')==0 || strcmp($mojri_code,'-2')==0)
       {
         $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";
        // echo $query;
         $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
         if(mysql_num_rows($qresult) > 0 )
         {
           $row_degree = mysql_fetch_array($qresult);
           $degree_result = $row_degree["darajeelmi_desc"];
           $daraje_mojri=$degree_result;
           //echo "a".$daraje_mojri;
         }
         else
           $degree_result = "ثبت نشده";
           
          // $daraje_mojri=$degree_result;
           
       }   
       echo "<td align=\"center\"  class=\"tahoma1\">".$daraje_mojri."</td>";
        if(strcmp($mojri_code,'-1')!=0 && strcmp($mojri_code,'-2')!=0)
          $persons=1;
        else 
          $persons=  number_format($row_fetched["persons"]);
       
       echo "<td align=\"center\"  class=\"tahoma1\">".$persons."</td>";
       echo "<td align=\"center\"  class=\"tahoma1\">".$row_fetched["activity_type"]."</td>";
       echo "<td align=\"center\"  class=\"tahoma1\">".$mojri_name_family."</td>";
       echo "</tr>";
     }
      echo "<tr>";
      
      echo "<td align=\"center\" colspan=\"2\"  class=\"tahoma1\">&nbsp;</td>";
      echo "<td align=\"center\"  class=\"tahoma1\">".number_format($mycount)."</td>";
      echo "<td align=\"right\" colspan=\"6\"  class=\"tahoma1\">مجموع</td>";
      echo "</tr>";
      
      echo "<tr>";
      
      echo "<td align=\"center\" colspan=\"9\"  class=\"tahoma1\"><a target='_blank' href='hazine_personnel_print.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>چاپ</a></td>";
       
      echo "</tr>";
     echo "</table>";

   }

 footer_forms($admin,$seed);
?>

