<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
/*
if(strcmp($row_fetched["modir_type"],'4') ==0 )
  $modir_caution=" tarh.send_moavenat='1' ";
else
  
  */
  $modir_caution='1';  
  
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
  
if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($current))
    $current = 1;



if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
  

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
    
    
if(isset($name_e))
{
  $query="select tarh.* from tarh ,user_login where user_login.email=tarh.creator  and finalized ='1' and indoing='1' and tarh_type='6'   and $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)   and $daneshkade_caution and $year_caution      and version='-1' and ready_gharardad='1' group by cod_tarh order by tarh_time desc";
}
else
  $query="select tarh.* from tarh  where  finalized ='1' and indoing='1' and tarh_type='6'   and $modir_caution    and $daneshkade_caution and $year_caution  and version='-1' and ready_gharardad='1' group by cod_tarh order by tarh_time desc";

//echo $query;
$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);


if(isset($name_e))
{
  $query="select tarh.* from tarh ,user_login where  user_login.email=tarh.creator  and finalized ='1' and indoing='1' and tarh_type='6'   and  $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)   and $daneshkade_caution and $year_caution and version='-1' and ready_gharardad='1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select tarh.* from tarh  where   finalized ='1' and indoing='1' and tarh_type='6'   and $modir_caution     and $daneshkade_caution and $year_caution  and version='-1' and ready_gharardad='1' group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;

///echo $query;

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 //echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%" dir="rtl"><b>طرح هاي خاتمه يافته HSR<b></td>
 </tr>
 </table>
 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\">  <select size=\"1\" name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" class=\"but-small\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
  
?>
  </select>دانشکده / مرکز
  </td>
<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  <?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&tarh_type=$tarh_type\">";

?> 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
	
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
   $myascdescpub=$myascdescpub."&name_e=$name_e";
 pubshowpages("hsr_finished.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>
  
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ قرارداد</font></td>  
      
         <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">گزارش پرداخت</font></td>

   <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">گزارشات</font></td>
  <!-- <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ قرارداد</font></td> -->

        <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>  
      
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
<!-- <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال براي کارشناس</font></td> -->
   
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال نامه</font></td> 
      
        <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح از نظر کارشناسي</font></td>
  
   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
        
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
   <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=tarh_title_farsi&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>عنوان فارسي</a></font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=cod_tarh&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>کد طرح</a></font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
 // echo $myq;
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  
   $query11="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
   $result11=mysql_query($query11) or die("Error10");
  
   if(mysql_num_rows($result11)>0)
   {
 	$row_fetched11=mysql_fetch_array($result11);
 	$zarib_maliat=$row_fetched11["maliat"];
    $exists=1; 	
    
   } 	
   else
   {
 	$zarib_maliat=5;
   }
  
  $query="select * from tarh_hesabdari where researchno='$cod_tarh'";
  $result_final=mysql_query($query) or die("ERror 12212");
  if(mysql_num_rows($result_final) > 0)
  {
  	echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" style=\"text-decoration:none\" href=\"rtf.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >صدور قرارداد با ماليات $zarib_maliat درصد</a></td>";
  }
  else
  	echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" style=\"text-decoration:none\" href=\"rtf_old.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >صدور قرارداد با ماليات $zarib_maliat درصد</a></td>";
  
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"list_payments.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >گزارشات</a></td>";  

  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"reports_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >گزارشات</a></td>";  
 
//  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target='_blank' style=\"text-decoration:none\" href=\"rtf.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >چاپ قرارداد</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويرايشها</a></td>";
  $mablagh_admin=$row_fetched["mablagh_aghd_gharardad"];
  $mablagh_admin=number_format($mablagh_admin);
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"change_gharardad_mablagh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mablagh_admin."</a></td>";
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To...\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target = \"_blank\" href=\"shenasname_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/shenasname_tarh.gif\" width=\"11\" height=\"13\" alt=\"Shenasname tarh\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["status"]=="0")
  {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }


  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
 
 
   $status_comment="";

  $q="select * from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas and group_karshenasan.karshenas_type='0'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	    $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }	
	 else
	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }
  	}
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  }


 $q="select * from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas and group_karshenasan.karshenas_type='1'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
  	 }
  	 else
  	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
  	 }
    }	
  }
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  //}
  
  
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    //$status_comment=$status_comment."<br>"."ارسال به اپيدميولوژيست : ".$plus."<br>";  
  
    //$status_comment=$status_comment."<br>"."-".": ارسال به اپيدميولوژيست"."<br>";
  }


  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$status_comment."</td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration : none\" href=\"change_status_after_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mystatus."</a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $daneshkade."</a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $farsistartdate."</a></td>";
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
    $First_mojri_name = "اطلاعات موجود نيست";
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["cod_tarh"]."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
 
footer_forms($admin,$seed);


?>