<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
$query="select * from jalase_shora where jalase_id ='$shomare_jalase'";
//echo $query;
$result_jalase=mysql_query($query) or die("Error");
$row_fetched_result_jalase=mysql_fetch_array($result_jalase);

$query="select * from karshenas_shora, jalase_shora_karshenas_shora,jalase_shora where jalase_shora.jalase_id='$shomare_jalase' and   jalase_shora.jalase_id=jalase_shora_karshenas_shora.shomare_jalase and  jalase_shora_karshenas_shora.cod_karshenas=karshenas_shora.cod_karshenas     group by karshenas_shora.cod_karshenas ";

$result_karshenasan_shora=mysql_query($query) or die("Error in selecting data from karshenas_shora");
$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];
$query="select tarh.*, jalase_shora_tarh.* from tarh ,jalase_shora_tarh where jalase_shora_tarh.shomare_jalase='$shomare_jalase' and jalase_shora_tarh.cod_tarh=tarh.cod_tarh    group by tarh.cod_tarh  desc" ;
//echo $query;
$color=$list_color_1;
 
$result_tarh_jalase_shora=mysql_query($query) or die("Error in selecting data from tarh");

  echo "<br><table  border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  echo "<tr>";
  echo "<td width=\"50%\"  bgcolor=$color  class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["shomare_jalase"]."</td>";
  echo "<td width=\"50%\"  bgcolor=$color class=\"tahoma1\"  align=\"left\">:شماره جلسه</td>";
  echo "</tr>";
  echo "<tr>";
  echo "<td width=\"50%\"  bgcolor=$color class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["tarikh_jalase"]."</td>";
  echo "<td width=\"50%\" bgcolor=$color  class=\"tahoma1\"  align=\"left\">:تاريخ جلسه</td>";
  echo "</tr>";
  /*echo "<tr>";
  echo "<td width=\"50%\" class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["band_azad"]."</td>";
  echo "<td width=\"50%\" class=\"tahoma1\"  align=\"left\">:توضيحات</td>";
  echo "</tr>";*/
  echo "<tr>";
  echo "<td width=\"50%\" class=\"tahoma1\" align=\"right\">&nbsp;</td>";
  echo "<td width=\"50%\" class=\"tahoma1\"  align=\"left\">&nbsp;</td>";
  echo "</tr>";
echo "</table>";
$color=$list_color_1;
 
 

$query="select * from mosavabat  where   shomare_jalase='$shomare_jalase'";
 
$result_mosavabat=mysql_query($query) or die("error 1");
if(mysql_num_rows($result_mosavabat)>0)
{
  echo "<br><table border=\"1\" width=\"100%\" cellpadding\"0\" cellspacing=\"0\">";
  echo "<tr>";    
  echo "<td width=\"100%\" colspan=\"2\" class=\"tahoma1\"  align=\"center\"><b>مصوبات شوراي پژوهشي</b></td>";
  echo "</tr>";
  
  while($row_fetched=mysql_fetch_array($result_mosavabat))
  {
  
	echo "<tr>";
	

    echo "<td width=\"80%\" height=\"60\" class=\"tahoma1\" dir=\"rtl\" align=\"right\">"."<br>".$row_fetched["kar_shora_name"]."&nbsp;".$row_fetched["mosavabe"]."</td>";
	 
    echo "<td width=\"20%\" height=\"60\" class=\"tahoma1\" dir=\"rtl\" align=\"right\">"."<br>".$row_fetched["kar_shora_name"]."&nbsp;".$row_fetched["subject"]."</td>";
	 


    echo "</tr>";
    
  }
  echo "</table>";
}
 
 
 
 
 
if(mysql_num_rows($result_karshenasan_shora)>0)
{
 echo "<table border=\"0\"   width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color  colspan=\"2\" class=\"tahoma1\"  align=\"center\"><b>حاضرين در جلسه</b></td>";
    echo "</tr>";
  while($row_fetched=mysql_fetch_array($result_karshenasan_shora))
  {
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
    echo "<td width=\"70%\" bgcolor=$color class=\"tahoma1\" align=\"right\">".$row_fetched["kar_shora_family"]."&nbsp;".$row_fetched["kar_shora_name"]."</td>";
    echo "<td width=\"30%\" bgcolor=$color class=\"tahoma1\"  align=\"left\">:نام و نام خانوادگي</td>";
    echo "</tr>";
  }
  echo "</table>";
}
$color=$list_color_1;
 
  echo "<table border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color colspan=\"6\" class=\"tahoma1\"  align=\"center\"><b>وضعيت طرحها در اين جلسه</b></td>";
    echo "</tr>";
 
if(mysql_num_rows($result_tarh_jalase_shora)>0)
{
 	echo "<tr>";    
   echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بند آزاد</td>";
	//echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بودجه مصوب</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">رتبه طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">نظر شورا</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">عنوان طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">کد طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">رديف</td>";
    echo "</tr>";
  
  $color=$list_color_1;
 $row_cntr=1;
  while($row_fetched=mysql_fetch_array($result_tarh_jalase_shora))
  {
  	$cod_tarh=$row_fetched["cod_tarh"];
  	$query="select * from jalase_shora_tarh  where cod_tarh='$cod_tarh' and shomare_jalase='$shomare_jalase'";
  //	echo $query;
  	$res=mysql_query($query)or die("tttt");
  	$row_fetched_budje=mysql_fetch_array($res);
  	
  	
  //	$query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,jalase_shora_tarh where jalase_shora_tarh.shomare_jalase='$shomare_jalase' and jalase_shora_tarh.cod_tarh=tarh.cod_tarh and  vaziat_tarh.vaziat=tarh.vaziat_moaven   group by tarh.cod_tarh  desc" ;
   
  	
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
	//$vaziat_tarh_shora= $row_fetched["vaziat_tarh_shora"];
	$vaziat_tarh_shora= $row_fetched["vaziat_jalase_shora"];
	if(strcmp($vaziat_tarh_shora,'0')==0)
	   $vaziat_tarh_shora_desc="دارد";
	   
	if(strcmp($vaziat_tarh_shora,'1')==0)
	   $vaziat_tarh_shora_desc="نا حدودي دارد";
	   
	if(strcmp($vaziat_tarh_shora,'2')==0)
	   $vaziat_tarh_shora_desc="ندارد";

 	   
	   
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["tozih_akhlaghi"]."</td>";
	//echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched_budje["budjeh"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["rotbe_tarh"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$vaziat_tarh_shora_desc."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\" align=\"right\" dir=\"rtl\">".$row_fetched["tarh_title_farsi"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["cod_tarh"]."</td>";
     echo "<td   class=\"tahoma1\"  align=\"center\">".$row_cntr."</td>";
     $row_cntr++;
    echo "</tr>";
  }
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  ////////$shomare_jalase_org=$shomare_jalase;
  $query="select * from jalase_shora   where    shomare_jalase='$shomare_jalase'";
  	
  	$res=mysql_query($query)or die("tttt");
  	$row_fetched_budje=mysql_fetch_array($res);
  	
  	
  	$jalase_id=$row_fetched_budje["jalase_id"];
  echo "<form name=\"sabt_tarh\" target=\"_blank\" method=\"post\"  action=\"print_jalase_admin_akhlagh.phtml?admin=$admin&seed=$seed&action=sabt&shomare_jalase=$shomare_jalase\">";
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\"><b>بند آزاد مربوط به جلسه</b></td>";
  echo "</tr>";

  echo "<tr>";
  echo "<td  colspan=\"6\"  align=\"center\"><textarea   rows=\"7\"  name=\"band_azad_jalase\"  class=\"edit-user\"  dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\"></textarea></td>";  
  echo "</tr>";
 
 
}
 echo "<tr>";
  echo "<td width=\"30%\" align=\"center\" colspan=\"6\" class=\"tahoma1\"><input type=\"submit\"  value=\"خاتمه و صدور صورت جلسه چاپي \" name=\"finish\" ></td>";
  echo "</tr>";
 
  /*echo "<tr>";
  echo "<br><td colspan=\"6\"  class=\"tahoma1\"  align=\"center\"><b><a target=\"_blank\" href=\"print_jalase.phtml?admin=$admin&seed=$seed&shomare_jalase=$shomare_jalase\">"."چاپ صورت جلسه"."</a></b></td>";
  echo "</tr>";*/
  echo "</form>";
  echo "</table>";

footer_forms($admin,$seed);
?>