<?php

include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";
   
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=$max_record;
      $current=1;
    }
    

if(isset($action))
{
  if (strcmp($action,"add_karshenas")==0)
  {

     if(strlen(trim($username)) > 0 && strcmp(trim($karshenas_type),"-1")!=0 && strlen(trim($kar_name)) > 0 && strlen(trim($kar_family)) > 0 &&  strlen(trim($kar_pass)) > 0 &&  strlen(trim($kar_re_pass)) > 0  && strcmp(trim($kar_pass),trim($kar_re_pass))==0 &&  strlen(trim($kar_email)) > 0 &&  strstr($kar_email, '@')  )
    {
	
	 if(isset($material ) )
	{
			$material=1;
	}
		else
			$material=0;
			
	if(isset($doers_view ) )
	{
			$doers_view=1;
	}
		else
			$doers_view=0;
	  if(strlen(trim($saltavalod)) > 5)
		 $saltavalod="";
      $query="select * from karshenasan where username=\"$username\"";
      $result=mysql_query($query) or die("Error in selecting data from karshenas elmi 12");

      if ( mysql_num_rows($result) <= 0 )
      {

        $query="insert into karshenasan set material='$material',doers_view ='$doers_view', mobile='$mobile',username='$username',karshenas_type='$karshenas_type_select',karshenas_name='$kar_name' ,karshenas_name_e='$kar_name_e', karshenas_family='$kar_family', karshenas_family_e = '$kar_family_e',  karshenas_rade_elmi='$kar_rade_elmi',  karshenas_takhasos  = '$kar_takhasos', karshenas_takhasos_e  = '$kar_takhasos_e',  karshenas_email  ='$kar_email', cod_daneshkade='$daneshkade' , shenasname='$shenasname' , sal_tavalod='$saltavalod' , fath_name='$nampedar', fath_name_e='$nampedar_e', creator='$admin', password='$kar_pass',melli_code='$cod_melli'";

        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
        $karshenas_type_select="-1";

      }
      else
       $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }

 if (strcmp($action,"delete_karshenas")==0)
 {
 	  $query="select * from karshenasan where cod_karshenas=\"$delete_id\"";
      $result=mysql_query($query) or die("Error in selecting data from karshenas elmi 12");

      if ( mysql_num_rows($result) > 0 )
      {
       $rf=mysql_fetch_array($result);
      
         $query="delete from karshenasan where cod_karshenas = \"$delete_id\"";
         $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
         $action="حذف كارشناس با كد"."<br>".$delete_id;
         set_log($action,$admin,date("Y-m-d, g:i a"));
      
      }
    
 }
 
 
 
   if (strcmp($action,"edit_karshenas_second")==0)
  {
     
     if( strcmp(trim($karshenas_type_select),"-1")!=0 && strlen(trim($kar_name)) > 0 && strlen(trim($kar_family)) > 0 &&  strlen(trim($kar_email)) > 0 &&  strstr($kar_email, '@')  )
    {
	  if(strlen(trim($saltavalod)) > 5)
		 $saltavalod="";
      $query="select * from karshenasan where cod_karshenas=\"$cod_karshenas\"";
      $result=mysql_query($query) or die("Error in selecting data from karshenas elmi 12");
 if(isset($material ) )
	{
			$material=1;
	}
		else
			$material=0;
			
	if(isset($doers_view ) )
	{
			$doers_view=1;
	}
		else
			$doers_view=0;
      if ( mysql_num_rows($result) > 0 )
      {

        $query="update  karshenasan set material='$material',doers_view ='$doers_view', mobile='$mobile',karshenas_type='$karshenas_type_select',karshenas_name='$kar_name' ,karshenas_name_e='$kar_name_e', karshenas_family='$kar_family', karshenas_family_e = '$kar_family_e',  karshenas_rade_elmi='$kar_rade_elmi',  karshenas_takhasos  = '$kar_takhasos', karshenas_takhasos_e  = '$kar_takhasos_e',  karshenas_email  ='$kar_email', cod_daneshkade='$daneshkade' , shenasname='$shenasname' , sal_tavalod='$saltavalod' , fath_name='$mojri_email', fath_name_e='1',melli_code='$cod_melli' where cod_karshenas='$cod_karshenas'";
      // echo $query;
        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
        $karshenas_type_select="-1";
         if(strlen(trim($cod_karshenas1)) > 0){
         	$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas1'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         	
	      	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas1'";
	      	echo $query;
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas1'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas1'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	     
	      }
      if(strlen(trim($cod_karshenas2)) > 0){
      		$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas2'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         
	      	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas2'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas2'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas2'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	     
	      }
      if(strlen(trim($cod_karshenas3)) > 0){
      		$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas3'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         
	      	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas3'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas3'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	  		
	      	$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas3'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      }
      if(strlen(trim($cod_karshenas4)) > 0){
      		$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas4'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         
	      	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas4'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas4'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	  		
	      	$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas4'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      }
	      
      if(strlen(trim($cod_karshenas5)) > 0){
      		$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas5'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         
	      	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	  		
	      	$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      }
	      if(strlen(trim($cod_karshenas_shora)) > 0){
	      	$query="update karshenas_shora set kar_shora_email='$kar_email',fath_name_e='1' where cod_karshenas='$cod_karshenas_shora'";
      		//$query="update karshenasan set fath_name_e='2' where cod_karshenas='$cod_karshenas5'";
	     	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	     	$query="update karshenasan set sal_tavalod='1' where cod_karshenas='$cod_karshenas'";
         
	      //	$query="update karshenasan_tarh set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      	//$query="update karshenasan_tarh_note set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	//$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	  		
	      	//$query="update karshenasan_letter_view set cod_karshenas='$cod_karshenas' where cod_karshenas='$cod_karshenas5'";
	      	//$result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
	      	
	      }
        
        $action="";
        
      }
      else
       $status="duplicate_entry";
    }
    else
    {
      $status="entry_error";
      $action="edit_karshenas";
    }
  }
 
 
 
 if (strcmp($action,"edit_karshenas")==0) 
 {
 	$query="select * from karshenasan where cod_karshenas='$cod_karshenas'";
 	$result=mysql_query($query) or die("Error in selecting data from karshenasan"); 	
 	$row_fetched=mysql_fetch_array($result);
 	$karshenas_name=$row_fetched["karshenas_name"];
 	$karshenas_family=$row_fetched["karshenas_family"];
 	$shenasname=$row_fetched["shenasname"];
 	$sal_tavalod=$row_fetched["sal_tavalod"];
 	$mojri_email=$row_fetched["fath_name"];
 	$melli_code=$row_fetched["melli_code"];
 	$karshenas_type=$row_fetched["karshenas_type"];
 	$karshenas_type_select=$row_fetched["karshenas_type"];
 	$karshenas_email=$row_fetched["karshenas_email"];
 	$karshenas_rade_elmi=$row_fetched["karshenas_rade_elmi"];
 	$karshenas_takhasos=$row_fetched["karshenas_takhasos"];
	$mobile=$row_fetched["mobile"];  	
	$material=$row_fetched["material"];  	
	$doers_view =$row_fetched["doers_view"];  	
 }
 else
 {
 	$karshenas_name="";
 	$karshenas_family="";
 	$shenasname="";
 	$sal_tavalod="";
 	$fath_name="";
 	$melli_code="";
 	$karshenas_type="";
 	$karshenas_type_select=""; 	
 	$karshenas_email="";
 	$karshenas_rade_elmi="";
 	$karshenas_takhasos="";
 	$mobile="";
 }

}

if(strcmp($action,"edit_karshenas")==0)
 echo "<form name=\"add_karshenas\" method=\"post\"  action=\"$PHP_SELF?action=edit_karshenas_second&admin=$admin&seed=$seed&cod_karshenas=$cod_karshenas\">"; 
else 
 echo "<form name=\"add_karshenas\" method=\"post\"  action=\"$PHP_SELF?action=add_karshenas&admin=$admin&seed=$seed\">"; 
 
 
 ?>

<table border="0"  width="600" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="349"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/karshenasan.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


<table border="0" width="600" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>
  <tr>
    <td width="450" align="right"><input type="text" value="<? echo $karshenas_name; ?>" name="kar_name" size="20" class="edit-user"dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span> نام</td>
  </tr>
 <!--  <tr>
    <td width="450" align="right"><input type="text" name="kar_name_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام (انگليسي</td>
  </tr>  -->

  <tr>
    <td width="450" align="right"><input type="text" value="<? echo $karshenas_family; ?>" name="kar_family" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>
 
 <!--  <tr>
    <td width="450" align="right"><input type="text" name="kar_family_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام خانوادگي(انگليسي</td>
  </tr>  -->
  
  
<!--   <tr>
    <td width="450" align="right"><input type="text" name="nampedar_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام پدر (انگليسي</td>
  </tr> -->
   <tr>
    <td width="450" align="right"><input type="text" value="<? echo $mobile; ?>" name="mobile" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">شماره موبايل</td>
  </tr>
  
  
   <tr>
    <td width="450" align="right"><input type="text" value="<? echo $melli_code; ?>" name="cod_melli" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد ملي</td>
  </tr>
  
  
  
  
  
  
  
  <?
    echo "<tr>";
    $query="select * from karshenas_type order by karshenas_type_desc desc";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    echo "<td width=\"450\" align=\"right\"><select size=\"1\" name=\"karshenas_type_select\" class=\"edit-user\" dir=\"rtl\">";
    echo "<option value=\"-1\" class=\"tahoma1\">انتخاب کنيد</option>";

    while($row_fetched=mysql_fetch_array($qresult))
    {
    	if(strcmp($row_fetched["karshenas_type"],$karshenas_type_select)==0)
    	  $selected=" selected ";
        else
		  $selected="";    	  
         echo "<option $selected value=\"".$row_fetched["karshenas_type"]."\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</option>";
    }

   echo "</select></td>";

     ?>
      <td width="150" class="tahoma1"><span class="star-message">*</span>نوع کارشناس</td>
  </tr>

  <tr>
    <td width="450" align="right"><input type="text" value="<? echo $karshenas_email;?>" value="پست الکترونيکي نام کاربري ايشان است" onfocus="kar_email.value='' " name="kar_email" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
   <tr>
  <?
    $query="select * from darajeelmi order by darajeelmi_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");

  ?>
    <td width="450" align="right"><select size="1" name="kar_rade_elmi" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
       if(strcmp($row_fetched["darajeelmi"].$karshenas_rade_elmi)==0)
    	  $selected=" selected ";
        else
		  $selected="";
		      
      echo "<option $selected value=\"".$row_fetched["darajeelmi"]."\" class=\"tahoma1\">".$row_fetched["darajeelmi_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">درجه علمي</td>
  </tr>
  <tr>
    <td width="450" align="right"><input value="<? echo $karshenas_takhasos ; ?>" type="text" name="kar_takhasos" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">تخصص</td>
  </tr>
  <?
  if(strcmp($doers_view,'1')==0)
  {
  $doer_check=" checked ";
  }
  else
  $doer_check="";
  ?>
 <tr>
    <td width="450" align="right"><input type="checkbox" value="1"  <? echo $doer_check; ?>  name="doers_view" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>امکان مشاهده مجريان</td>
  </tr>
  
  <?
  if(strcmp($material,'1')==0)
  {
  $material=" checked ";
  }
  else
  $material="";
  ?>
 <tr>
    <td width="450" align="right"><input type="checkbox" value="1" <? echo $material; ?>  name="material" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>امکان جستجوي در مواد</td>
  </tr>
  
   <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas1" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد کارشناس 1</td>
  </tr>
   <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas2" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد کارشناس 2</td>
  </tr>
   <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas3" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد کارشناس 3</td>
  </tr>
   <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas4" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">4 کد کارشناس</td>
  </tr>
   <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas5" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد کارشناس 5</td>
  </tr>
  
  <tr>
    <td width="450" align="right"><input type="text" name="cod_karshenas_shora" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><font color=red>کد عضو شورا</font></td>
  </tr>
   <?
  if(strcmp($mojri_email,'1')==0)
  {
  $mojri_email=" checked ";
  }
  else
  $mojri_email="";
  ?>
  <tr>
    <td width="450" align="right"><input type="checkbox" value="1" <? echo $mojri_email; ?>  name="mojri_email" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">يکسان کردن ايميل با محيط مجري</td>
  </tr>
  
 <!-- <tr>
    <td width="450" align="right"><input type="text" name="kar_takhasos_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(تخصص (انگليسي</td>
  </tr>  -->
<?
  if(strcmp($action,"edit_karshenas")!=0)
{
?>
	
   <tr>
    <td width="450" align="right"><input type="password" name="kar_pass" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>رمز عبور</td>
  </tr>

  <tr>
    <td width="450" align="right"><input type="password" name="kar_re_pass" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>تکرار رمز عبور</td>
  </tr>
<?
}
?>
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>


 <?
  $karshenas_type_filter="1"; 
// if(isset($karshenas_type_select) && strcmp($karshenas_type_select,'-1')!=0 && strcmp($action,"edit_karshenas")!=0)
 if( strcmp($karshenas_type_select,'-1')!=0  && strlen($karshenas_type_select) > 0)
 {
 	$karshenas_type_filter=" karshenas_type='$karshenas_type_select' ";
 }
 else 
 {
    $karshenas_type_filter="1";
    $karshenas_type_select="-1";
 }
//echo $karshenas_type_filter;
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
   $query="select * from karshenasan where $karshenas_type_filter and (karshenas_name like $myname_search or  karshenas_family like $myname_search) order by  karshenas_family ";
else
   $query="select * from karshenasan where $karshenas_type_filter and 1 order by  karshenas_family";   

  $result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 
   
   
   if(isset($name_e))
   $query="select * from karshenasan where $karshenas_type_filter and (karshenas_name like $myname_search or  karshenas_family like $myname_search) order by  karshenas_family "." limit ".($current-1)*$RecPerPage.",".$RecPerPage;
else
   $query="select * from karshenasan where $karshenas_type_filter and 1 order by  karshenas_family"." limit ".($current-1)*$RecPerPage.",".$RecPerPage;   
   
   //echo $query;
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"0\" width=\"700\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<form name=\"karshenas_type\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&name_e=$name_e&ascdescfield=$ascdescfield&ascdesc=$ascdesc\">";



$query="select * from karshenas_type order by  karshenas_type_desc  desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"> نوع کازشناس <select size=\"1\" class='tahoma1' name=\"karshenas_type_select\" onchange=\"JavaScript:document.karshenas_type.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["karshenas_type"],$karshenas_type_select)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["karshenas_type"]."\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</option>";
 }
 
 
echo "</select>";
echo "</td>";
 
   
 
echo "</form>";
    
    echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed\">";
    ?>
    <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 <?echo "</form>";?>
 
 
 
 
 
 
 
 
 
 
 
 <?
 

   // echo "<tr>";
    echo "<tr>";
    $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";	
	
  pubshowpages("karshenasan_edgham.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"60%",$title_color);
 
    echo "<table border=\"0\" width=\"700\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<td width=\"16\"   height=\"20\"></td>";
    echo "<td width=\"47\"   height=\"20\" class=\"tahoma1\" align=\"center\">کلمه عبور</td>";
    echo "<td width=\"47\"  height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\"   height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
	echo "<td width=\"47\"   height=\"20\" class=\"tahoma1\" align=\"center\">دانشکده</td>";
    echo "<td width=\"47\"   height=\"20\" class=\"tahoma1\" align=\"center\">نوع کارشناس</td>";
    echo "<td width=\"47\"   height=\"20\" class=\"tahoma1\" align=\"center\">تعداد طرح ها</td>";
    echo "<td width=\"40\"   height=\"20\" class=\"tahoma1\" align=\"center\">يکسان کردن ايميل با عضو شورا</td>";
    echo "<td width=\"40\"   height=\"20\" class=\"tahoma1\" align=\"center\">يکسان کردن ايميل با محيط مجري</td>";
    echo "<td width=\"123\"   height=\"20\" class=\"tahoma1\" align=\"center\">نام خانوادگي</td>";
    echo "<td width=\"104\"   height=\"20\" class=\"tahoma1\" align=\"center\">نام</td>";
    echo "<td width=\"100\"   height=\"20\" class=\"tahoma1\" align=\"center\">نام کاربري</td>";
    echo "<td width=\"40\"   height=\"20\" class=\"tahoma1\" align=\"center\">کد کارشناس</td>";
	echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\">رديف</td>";
    
    echo "<td width=\"16\"   height=\"20\"></td>";
    echo "</tr>";
   $color="#E2E0E0";
   $cntr=1;
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    $mycod_karshenas = $myrow_fetched["cod_karshenas"];
    $cod_daneshkade  = $myrow_fetched["cod_daneshkade"];
    $karshenas_type1=$myrow_fetched["karshenas_type"];
    if($karshenas_type1=='8')
    	$karshenas_type1="ناظر";
    if($karshenas_type1=='7')
    	$karshenas_type1="داور";
    if($karshenas_type1=='7')
    	$karshenas_type1="داور متدلوژي";
    
    	$q2="select * from karshenasan_tarh where cod_karshenas='$mycod_karshenas' ";
    	$res2=mysql_query($q2) or die("Error ");
    	$num=mysql_num_rows($res2);
    $creator = $myrow_fetched["creator"];
    $fath_name_e = $myrow_fetched["fath_name_e"];
    $fath_name = $myrow_fetched["fath_name"];
    $sal_tavalod1=$myrow_fetched["sal_tavalod"];
    if($fath_name_e=='1')
    	$color="yellow";
    else if($fath_name_e=='2')
    	$color="#5EF4F";
   
    $q_daneshkade="select * from modir_daneshkade,daneshkade where daneshkade.cod_daneshkade=modir_daneshkade.cod_daneshkade and modir_daneshkade.modir_username='$creator'";
    //echo  $q_daneshkade;
    $r_daneshkade=mysql_query($q_daneshkade) or die("Error ");
    if(mysql_num_rows($r_daneshkade) > 0 )
    {
    	$rf_daneshkade=mysql_fetch_array($r_daneshkade);
    	$daneshkade_name=$rf_daneshkade["daneshkade_name"];
    }
    else
    {
    	$daneshkade_name="-----";
    }
    if($fath_name_e=='1'){
    	$color1="red";
    	$text="انجام شده";
    }
    else {
    	$color1=$color;
    	$text="";
    }
   if($sal_tavalod1=='1'){
    	$color2="red";
    	$text2="انجام شده";
    }
    else {
    	$color2=$color;
    	$text2="";
    }
    
    	echo "<tr bgcolor=\"$color\">";
    	echo "<td width=\"16\"   height=\"20\"></td>";
    	echo "<td width=\"47\"><p align=\"center\"><a href=\"change_users_password.phtml?admin=$admin&seed=$seed&db=karshenasan&username=".$myrow_fetched["cod_karshenas"]."&user_field=cod_karshenas\" ><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
    	echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_karshenas.phtml?mainwindow=karshenasan_edgham.phtml&admin=$admin&seed=$seed&action=delete_karshenas&delete_id=".$myrow_fetched["cod_karshenas"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    	echo "<td width=\"47\"><p align=\"center\"><a href='$PHP_SELF?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas&action=edit_karshenas'><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".$daneshkade_name."</a></p></td>";
    	
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".$karshenas_type1."</a></p></td>";
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".$num."</a></p></td>";
    	echo "<td width=\"40\" bgcolor=\"$color2\"  height=\"20\" class=\"tahoma1\" align=\"center\">$text2</td>";
    	echo "<td width=\"40\" bgcolor=\"$color1\"  height=\"20\" class=\"tahoma1\" align=\"center\">$text</td>";
   
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["karshenas_family"],0,18)."</a></p></td>";
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["karshenas_name"],0,18)."</a></p></td>";
    	echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["username"],0,18)."</a></p></td>";
    	echo "<td   width=\"40\"  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".$myrow_fetched["cod_karshenas"]."</a></p></td>";
		echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenasan_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".$cntr."</a></p></td>";    
    	echo "<td width=\"16\"   height=\"20\"></td>";
    	$cntr++;
    	echo "</tr>";
    	if($fath_name_e=='1')
    	$color="#CFCDCD";
    else if($fath_name_e=='2')
    	$color="#CFCDCD";
   
    
   }
     
   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>




