<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


?>



<? echo "<form name=\"add-tarh\" method=\"post\"  action=\"letter_to_mojri_body.phtml?action=add&admin=$admin&seed=$seed\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="400" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/letter_to_mojri.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="400" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"entry_error_1")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">روي اين شورا کارشناس تعريف شده و قابل حذف نيست</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">
        <div align="center">
          <table border="0" width="100%" bgcolor="F0F0FF" height="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="cod_tarh" size="48" class="edit-tarh-type"  dir=RTL   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>کد طرح</td>
            </tr>
           
            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="تاييد" name="submit_tarh"></td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
  </table>
</form>
<?
   footer_forms($admin,$seed);
?>



