<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");

echo "<br>";


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;


/*
$query="select * from modir_daneshkade where  modir_username = '$admin'";
	$result=mysql_query($query);
	$row_fetched=mysql_fetch_array($result);
	$cod_daneshkade=$row_fetched["cod_daneshkade"];
*/
$RecPerPage=15;
 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=7000;
      $current=1;
    }
    
	
	if(isset($payan_name) && (strcmp($payan_name,"0")==0 || strcmp($payan_name,"1")==0 ))
	  $payanname="payan_name='$payan_name'";
     else
	 $payanname="1";
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

if(isset($name_e)  )
{
  $query="select * from user_login  where $payanname and (name like $myname_search  or family like $myname_search or email like $myname_search)   order by family desc";
}
else
  $query="select * from user_login where $payanname and 1 order by family desc";

 $result=mysql_query($query) or die("Error in selecting data from tarh 1");

$reccount = mysql_num_rows($result);

 if(isset($name_e)  )
{
  $query="select * from user_login where  $payanname and (name like $myname_search  or family like $myname_search or email like $myname_search)   order by family desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from user_login where $payanname and 1 order by family desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;


 


 
 

$result=mysql_query($query) or die("Error in selecting data from tarh");
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>مجريان<b></td>
 </tr>
 </table>
  
 
 

   <? 
echo "<form name=\"payan_name_select\" method=\"post\" action=\"$PHP_SELF?admin=$admin&seed=$seed&name_e=$name_e&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";

?>
 
 
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
   <td  align="left" class="tahoma1">
 
 <select class='tahoma1' size="1" name="payan_name" onchange="JavaScript:document.payan_name_select.submit();"  dir="rtl"> 
    <option  <?  if(strcmp($payan_name,'-1')==0) echo " selected "; ?>
 value="-1" class="tahoma1">همه موارد</option>
  <option  <?  if(strcmp($payan_name,'0')==0) echo " selected "; ?>
 value="0" class="tahoma1">مجريان</option>
  <option  <?  if(strcmp($payan_name,'1')==0) echo " selected "; ?>
 value="1" class="tahoma1">دانشجويان</option>
  </select>نوع کاربر
  
  </td>
 <?
     echo "</form>";

 ?>
   <? 
echo "<form name=\"search_form\" method=\"post\" action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&payan_name=$payan_name\">";

?>

 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
  <?
     echo "</form>";

 ?>

 </tr>
 </table>
<?
}
  

  
if(mysql_num_rows($result) > 0 )
{
  if(isset($name_e))	
      $myascdescpub=$myascdescpub."&name_e=$name_e&payan_name=$payan_name";
  pubshowpages("mojrian.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
 <tr>

   <td colspan='22' bgcolor="#66CCFF" align='left'>
      <p class="tahoma1"><a href= "<? echo "doers-excell.phtml?admin=$admin&seed=$seed";?> " target="_blank"><img src="images/excell.jpg" border='0' /></a></p></td>
      </td>
      </tr>
  <tr>
 
    <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تخصص</font></td>
    
    <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">پست الکترونيکي</font></td>
   <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">شماره موبايل</font></td>
    
    <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
  </tr>
  <?

 $color="#DADADA";
 $color="PALETURQUOISE";
 while($row_fetched=mysql_fetch_array($result))
 {
 
      $hesab=$row_fetched["hesab"];
		$bank_name=$row_fetched["bank_name"];
		$shoabe=$row_fetched["shoabe"];

  
	    $bank_name_desc="";
		if(strlen(trim($bank_name))>0)
		{
 	$q="select *  from hesab_type where hesab_type ='$bank_name'";
 	$rs_bnk=mysql_query($q) or die("error");
	$rf_bnk=mysql_fetch_array($rs_bnk);
	
	$bank_name_desc=$rf_bnk["hesab_type_desc"];
	}
		 

  $cod_tarh=$row_fetched["cod_tarh"];
  $from_letter=$row_fetched["from_letter"];
  $id=$row_fetched["id"];
  $email=$row_fetched["email"];
  $q_user="select * from tarh where creator='$email' and version='-1'";
  $q_result=mysql_query($q_user);
  $tarh_cnt=mysql_num_rows($q_result);
  
   
   echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["takhasos"]."</a></td>";
 
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["email"]."</a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["mobile"]."</a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["family"]."</a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a href=\"mojri_detail.phtml?admin=$admin&seed=$seed&mojri_username=".$row_fetched["email"]."\">".$row_fetched["name"]."</a></td>";
  echo "</tr>";

 }
echo "</table>";

}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}

footer_forms($admin,$seed);


?>
