<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>

<script type="text/javascript">
<!--

function addEvent()
{
var ni = document.getElementById('myDiv');
var numi = document.getElementById('theValue');
var num = (document.getElementById("theValue").value -1)+ 2;
numi.value = num;
var divIdName = "my"+num+"Div";
var newdiv = document.createElement('div');
newdiv.setAttribute("id",divIdName);

newdiv.innerHTML = "<table border=\"0\" width=\"100%\" bgcolor=\"#EEE7F8\"   cellspacing=\"0\" cellpadding=\"0\"  bordercolor=\"#333333\" style=\"border-style: solid; border-width: 0; \">"+

"<tr>"+    
"<td  valign='top'  width=\"10%\" align=\"right\"><textarea  name=\"mosavabe"+num+"\"  rows=\"5\"   cols=\"20\" value=\"\" class=\"edit-tarh-type\"  dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\"></textarea></td>"+
"<td  valign='top'  width=\"90%\" class=\"tahoma1\" ><span class=\"star-message\">*</span>مصوبه</td>"+   
"<td  valign='top'  width=\"10%\" align=\"right\"><input type=\"text\" name=\"mozoa"+num+"\" size=\"20\" value=\"\" class=\"edit-small-2\" dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\"></td>"+
"<td  valign='top'  width=\"90%\" class=\"tahoma1\"><span class=\"star-message\">*</span>موضوع</td>"+  
"</tr>"+
 
 
"</table>"+
"<a class=\"tahoma1\" href=\"javascript:;\" onclick=\"removeEvent(\'"+divIdName+"\')\">حذف</a>";
ni.appendChild(newdiv);
}

function removeEvent(divNum)
{
var d = document.getElementById('myDiv');
var olddiv = document.getElementById(divNum);
d.removeChild(olddiv);
}

//-->
</script>
<?
echo "<br>";

if(isset($action))
{
  if (strcmp($action,"add_hazine_azmayesh")==0)
  {


  	
  	
  	for($i=0;$i<100;$i++)
    {
     $mozoa="mozoa".$i;     
	 $mosavabe="mosavabe".$i;
 
    
     if(strlen(trim($$mozoa)) > 0  && strlen(trim($$mosavabe)) > 0   )
     {
     	$mozoa=$$mozoa;
     	$mosavabe=$$mosavabe;
     	
     	$mozoa=str_replace(",","",$mozoa);
      	$mosavabe=str_replace(",","",$mosavabe);
      	//$persons=str_replace(",","",$persons);
     	 
     	
     	$query  = "insert into mosavabat set subject=\"$mozoa\",mosavabe=\"$mosavabe\" , shomare_jalase=\"$shomare_jalase\"";
      
        $result = mysql_query($query) or die("Error in inserting data into mosavabat");
        $action=" ثبت مصوبات جلسه ".$cod_tarh."<br> با عنوان ".$mozoa;
        set_log($action,$admin,date("Y-m-d, g:i a"));
         
        
      }
     else
       $status="entry_error";
    }
   
  }
 if (strcmp($action,"delete_hazine_azmayesh")==0)
 {
    $query="delete from mosavabat where id = \"$delete_id\" ";

    $result=mysql_query($query) or die("Error in  delete data from hazine azmayesh");
    $action=" حذف مصوبات از آيدي ".$delete_id;
    set_log($action,$admin,date("Y-m-d, g:i a"));

 }
}

?>

<?  echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_hazine_azmayesh&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&shomare_jalase=$shomare_jalase\">"; ?>

<table border="0"  width="60%" cellspacing="0" cellpadding="0" >

<tr>
<TD align=left width="10%"   height=19>
     <a style="text-decoration:none" href="jalase_shora_divide.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh&shomare_jalase=$shomare_jalase" ?>" ><img src=images/return.gif border="0" alt="Return"></a>
      </TD>
  <TD width="90%"  align="right" class="tahoma1" height=19>
      مصوبات جلسه شوراي پژوهشي دانشگاه
      
</td>
</tr>


  
</TABLE>

<table border="0" width="60%" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="0"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <tr>
    
    <td  valign='top'  width="10%" align="right"><textarea  name="mosavabe0"  rows="5"   cols="20" value="" class="edit-tarh-type"  dir=RTL   ></textarea></td>
    <td  valign='top'  width="90%" class="tahoma1" ><span class="star-message">*</span>مصوبه</td>
   
    <td  valign='top'  width="10%" align="right"><input type="text" name="mozoa0" size="20" value="" class="edit-small-2" dir=RTL   ></td>
    <td  valign='top'  width="90%" class="tahoma1"><span class="star-message">*</span>موضوع</td>
  
 </tr>
<?

     echo "<tr>";
     echo "<td width=\"100%\" colspan=\"4\" class=\"tahoma0\" align=\"left\">";
     echo "<input type=\"hidden\" value=\"0\" id=\"theValue\" /><a href=\"javascript:;\" onclick=\"addEvent();\" class=\"tahoma1\">اضافه کردن</a>";
     echo "<div id=\"myDiv\">";
     echo "</div>";
     echo "</td>";
     echo "</tr>";
     ?>
  <tr>
    <td width="100%" colspan="4">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>
</form>

<br>
<table border="1"  width="60%" cellspacing="0" cellpadding="0" >

<tr>
<TD align=center width="100%"   height=19 class='tahoma1'>
     <a  href="jalase_shora_divide.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh&shomare_jalase=$shomare_jalase" ?>" ><b>بازگشت به صورتجلسات براي ادامه ورود اطلاعات و خاتمه صورتجلسه</b></a>
      </TD>
  
</tr>


  
</TABLE>

<br>

  <?
   $query="select * from  mosavabat where shomare_jalase=\"$shomare_jalase\"";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"60%\" >";
     echo "<tr>";
     echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">حذف</td>";
     //echo "<td width=\"5%\"  align=\"center\" class=\"tahoma1\">ويرايش</td>";
      echo "<td width=\"14%\"  align=\"center\"  class=\"tahoma1\">مصوبه</td>";
     echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">موضوع</td>";
     echo "</tr>";

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       echo "<tr>";
       echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=mosavabe.phtml&admin=$admin&seed=$seed&action=delete_hazine_azmayesh&shomare_jalase=".$shomare_jalase."&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
      // echo "<td ><p align=\"center\"><a href=\"edit_hazine_azmayesh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_azmayesh=$cod_azmayesh\" ><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
       echo "<td align=\"center\"  class=\"tahoma1\">".$row_fetched["mosavabe"]."</td>";
       echo "<td align=\"center\"  class=\"tahoma1\">".$row_fetched["subject"]."</td>";
       echo "</tr>";
     }
     
     echo "</table>";

   }

 footer_forms($admin,$seed);
?>

