<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
//$karshenasi_koll_1=mablagh_karshenasi($cod_tarh);
if(isset($action))
 if(strcmp($action,"accept_payment")==0)
 {
  for($i=0;$i<10;$i++)
  {
    $id_pardakht="myid".$i;
    
    if(isset($$id_pardakht))
    {
       $id_pardakht=$$id_pardakht;
       $id_payment_status="radio".$i;
       $id_payment_status=$$id_payment_status;
       $query="update tarh_old_pardakht set tayeed_pardakht='$id_payment_status' where id='$id_pardakht'";
       $result=mysql_query($query) or die("Error");
       if($id_payment_status > 0)
       {
         $action="<br>".$cod_tarh."مربوط به طرح".$id_pardakht."تاييد پرداخت مرحله";
          set_log($action,$admin,date("Y-m-d, g:i a"));
       }   
//       echo $query;
    }
  }
 }
 
echo "<br>";
$query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";
$result=mysql_query($query) or die("Error");
$my_rf=mysql_fetch_array($result);
$tarh_name=$my_rf["tarh_name"];

echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=accept_payment&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
   

    
    
     $query="select * from tarh_old_pardakht where  cod_tarh='$cod_tarh' order by marhale  asc";
     $result=mysql_query($query) or die("Error");
     if(mysql_num_rows($result) > 0)
	 {
     echo "<table border=\"0\" width=\"90%\"  cellspacing=\"1\" cellpadding=\"1\" >";
     echo "<tr>";
     echo "<td align=\"center\" colspan='5'  width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$tarh_name</b></td>";   
     echo "</tr>";
     
     $color="PALETURQUOISE";
     
     echo "<tr>";
       echo "<td align=\"center\" colspan='5'  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>($cod_tarh)پرداختها</b></td>";
     echo "</tr>";
     
     echo "<tr>";
          echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>پرداخت نشده</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>پرداخت شده</b></td>"; 
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مبلغ</b></td>";
      echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>تاريخ پرداخت</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مرحله</b></td>";   
     echo "</tr>";
     
     while($row_fetched=mysql_fetch_array($result))
     {
     $id=$row_fetched["id"];	
     $marhale=$row_fetched["marhale"];	
     $mablagh=$row_fetched["mablagh"];
     $tayeed_pardakht=$row_fetched["tayeed_pardakht"];
     $date_pardakht=$row_fetched["date_pardakht"];
     echo "<tr>";
     if($tayeed_pardakht==1)
     {
       $ok_checked=" checked ";
       $no_checked=" ";
     }
     else
     {
       $ok_checked=" ";
	   $no_checked=" checked ";
	   
     }  
     echo "<input name='myid$id'   type='hidden' value='$id'>";
	      echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><input name='radio$id' $no_checked type='radio' value='0'></td>";  
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><input name='radio$id' $ok_checked type='radio' value='1'></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b> $mablagh</b></td>";
          echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b> $date_pardakht</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$marhale</b></td>";
     echo "</tr>";
     
     }
     echo "<tr>";
     echo "<td width=\"100%\" colspan=\"3\">";
     echo "<p align=\"center\"><input type=\"submit\" value=\"تاييد\" name=\"B1\" class=\"but-small\"></td>";
     echo "</tr>";
     echo "</table>";
	 }
	 else
	  message_show("مبلغي پرداخت نشده","red");
  echo "</form>"; 
   
footer_forms($admin,$seed);
?>

