<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
?>

<script language="javascript">
function maxlen_set(maxchars)
{

 if(document.add_tarh.rank.value.length > maxchars)
 {
   alert('Too much data in the text box! Please remove '+(document.add_tarh.rank.value.length - maxchars)+ ' characters');
   return false;
 }
 else
   return true;
}
</script>

<?
echo "<br>";


if (strcmp($action,"add")==0)
{
 if(strlen(trim($rank)) > 0 &&  strcmp($startyear,"-1")!=0 && strcmp($startmon,"-1")!=0 && strcmp($startday,"-1")!=0 && strcmp($endyear,"-1")!=0 && strcmp($endmon,"-1")!=0 && strcmp($endday,"-1")!=0 )
  {
   // $query="select * from rank where  rank=\"$tarh_name\"";

    //$result=mysql_query($query) or die("Error in query data from tarh-type");
    //if(mysql_num_rows($result) <= 0)
    //{
      $start_date_mix = $startyear."-".$startmon."-".$startday;
	  $end_date_mix = $endyear."-".$endmon."-".$endday;
	  $jalase_date_mix = $jalase_year."-".$jalase_mon."-".$jalase_day;
	  $rank=substr($rank,0,1);

      $query="insert into rank set  year='$year', jalase_date='$jalase_date_mix', start_date='$start_date_mix',end_date='$end_date_mix',rank='$rank'";
      mysql_query($query) or die ("Error in inserting data in tarh-type");
   // }
    // else
     // $status="duplicate_entry";
  }
  else
   $status="entry_error";

}


if (strcmp($action,"delete")==0)
{
  if(strlen(trim($delete_id)) > 0 )
  {
    $query="select * from rank where  id=\"$delete_id\"";
	
    $result=mysql_query($query) or die("Error in query data from tarh-type");
    if(mysql_num_rows($result) > 0)
    {
      $query="delete from rank where id='$delete_id'";

      mysql_query($query) or die ("Error in inserting data in tarh-type");
    }

  }
}

?>
<? echo "<form name=\"add_tarh\" method=\"post\"  action=\"$PHP_SELF?action=add&admin=$admin&seed=$seed\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="550" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="299"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/ranking.jpg" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="550" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">
        <div align="center">
          <table border="0" width="100%" bgcolor="F0F0FF" height="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="rank" size="48" class="edit-tarh-type"   onkeypress="return maxlen_set(1)"></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>Rank</td>
            </tr>
             <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="year" size="48" class="edit-tarh-type"   onkeypress="return maxlen_set(1)"></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>سال</td>
            </tr>
            <tr>
              <td width="66%" align="right">
                <p align="right">

 

       	   <select size="1" dir="rtl"  name="startyear" class="combo-date">
          <option selected value="-1">سال</option>
          <option value="1381">1381</option>
          <option value="1382">1382</option>
          <option value="1383">1383</option>
          <option value="1384">1384</option>
          <option value="1385">1385</option>
	  	  <option value="1386">1386</option>
	      <option value="1387">1387</option>
	      <option value="1388">1388</option>
	      <option value="1389">1389</option>
	      <option value="1390">1390</option>
  	      <option value="1391">1391</option>
	      <option value="1392">1392</option>
	      <option value="1393">1393</option>
	      <option value="1394">1394</option>
	      <option value="1395">1395</option>

		  
		  
        </select>
             <select size="1" dir="rtl"  name="startmon"  class="combo-date">
         <option selected value="-1">ماه</option>
          <option value="01">فروردين</option>
          <option value="02">ارديبهشت</option>
          <option value="03">خرداد</option>
          <option value="04">تير</option>
          <option value="05">مرداد</option>
          <option value="06">شهريور</option>
          <option value="07">مهر</option>
          <option value="08">آبان</option>
          <option value="09">آذر</option>
          <option value="10">دي</option>
          <option value="11">بهمن</option>
          <option value="12">اسفند</option>
        </select>

        <select size="1" dir="rtl"  name="startday"  class="combo-date">
          <option selected value="-1">روز</option>
          <option value="01">1</option>
          <option value="02">2</option>
          <option value="03">3</option>
          <option value="04">4</option>
          <option value="05">5</option>
          <option value="06">6</option>
          <option value="07">7</option>
          <option value="08">8</option>
          <option value="09">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
		  <option value="22">22</option>
		  <option value="23">23</option>
		  <option value="24">24</option>
		  <option value="25">25</option>
		  <option value="26">26</option>
		  <option value="27">27</option>
		  <option value="28">28</option>
		  <option value="29">29</option>
		  <option value="30">30</option>
		  <option value="31">31</option>
        </select>

	</td>

				</td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>از</td>
            </tr>




            <tr>
              <td width="66%" align="right">
                <p align="right">



       	   <select size="1" dir="rtl"  name="endyear" class="combo-date">
          <option selected value="-1">سال</option>
          <option value="1381">1381</option>
          <option value="1382">1382</option>
          <option value="1383">1383</option>
          <option value="1384">1384</option>
          <option value="1385">1385</option>
	  	  <option value="1386">1386</option>
	      <option value="1387">1387</option>
	      <option value="1388">1388</option>
	      <option value="1389">1389</option>
	      <option value="1390">1390</option>
<option value="1391">1391</option>
	      <option value="1392">1392</option>
	      <option value="1393">1393</option>
	      <option value="1394">1394</option>
	      <option value="1395">1395</option>

        </select>
             <select size="1" dir="rtl"  name="endmon"  class="combo-date">
         <option selected value="-1">ماه</option>
          <option value="01">فروردين</option>
          <option value="02">ارديبهشت</option>
          <option value="03">خرداد</option>
          <option value="04">تير</option>
          <option value="05">مرداد</option>
          <option value="06">شهريور</option>
          <option value="07">مهر</option>
          <option value="08">آبان</option>
          <option value="09">آذر</option>
          <option value="10">دي</option>
          <option value="11">بهمن</option>
          <option value="12">اسفند</option>
        </select>

        <select size="1" dir="rtl"  name="endday"  class="combo-date">
          <option selected value="-1">روز</option>
          <option value="01">1</option>
          <option value="02">2</option>
          <option value="03">3</option>
          <option value="04">4</option>
          <option value="05">5</option>
          <option value="06">6</option>
          <option value="07">7</option>
          <option value="08">8</option>
          <option value="09">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
		  <option value="22">22</option>
		  <option value="23">23</option>
		  <option value="24">24</option>
		  <option value="25">25</option>
		  <option value="26">26</option>
		  <option value="27">27</option>
		  <option value="28">28</option>
		  <option value="29">29</option>
		  <option value="30">30</option>
		  <option value="31">31</option>
        </select>

	</td>

				</td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>تا</td>
            </tr>


            <tr>
              <td width="66%" align="right">
                <p align="right">



       	   <select size="1" dir="rtl"  name="jalase_year" class="combo-date">
          <option selected value="-1">سال</option>
          <option value="1381">1381</option>
          <option value="1382">1382</option>
          <option value="1383">1383</option>
          <option value="1384">1384</option>
          <option value="1385">1385</option>
	  	  <option value="1386">1386</option>
	      <option value="1387">1387</option>
	      <option value="1388">1388</option>
	      <option value="1389">1389</option>
	      <option value="1390">1390</option>
<option value="1391">1391</option>
	      <option value="1392">1392</option>
	      <option value="1393">1393</option>
	      <option value="1394">1394</option>
	      <option value="1395">1395</option>

        </select>
             <select size="1" dir="rtl"  name="jalase_mon"  class="combo-date">
         <option selected value="-1">ماه</option>
          <option value="01">فروردين</option>
          <option value="02">ارديبهشت</option>
          <option value="03">خرداد</option>
          <option value="04">تير</option>
          <option value="05">مرداد</option>
          <option value="06">شهريور</option>
          <option value="07">مهر</option>
          <option value="08">آبان</option>
          <option value="09">آذر</option>
          <option value="10">دي</option>
          <option value="11">بهمن</option>
          <option value="12">اسفند</option>
        </select>

        <select size="1" dir="rtl"  name="jalase_day"  class="combo-date">
          <option selected value="-1">روز</option>
          <option value="01">1</option>
          <option value="02">2</option>
          <option value="03">3</option>
          <option value="04">4</option>
          <option value="05">5</option>
          <option value="06">6</option>
          <option value="07">7</option>
          <option value="08">8</option>
          <option value="09">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
		  <option value="22">22</option>
		  <option value="23">23</option>
		  <option value="24">24</option>
		  <option value="25">25</option>
		  <option value="26">26</option>
		  <option value="27">27</option>
		  <option value="28">28</option>
		  <option value="29">29</option>
		  <option value="30">30</option>
		  <option value="31">31</option>
        </select>

	</td>

				</td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>تاريخ جلسه شوراي پژوهشي</td>
            </tr>




            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="اضافه" name="submit_tarh"></td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
  </table>
</form>
<br>

<?

if(DBreccount("rank") > 0)
{
    echo "<table border=\"0\" width=\"700\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"74\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">Rank</td>";
        echo "<td width=\"74\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">سال</td>";
    echo "<td width=\"300\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">تاريخ چلسه شوراي پژوهشي</td>";
    echo "<td width=\"100\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">تاريخ پايان</td>";
    echo "<td width=\"100\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">تاريخ شروع</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
  $Query=mysql_query("select * from rank order by start_date desc") or die("Error in selecting tarh-type");
  while($row_fetched=mysql_fetch_array($Query))
  {
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
  $id=$row_fetched["id"];
  echo "<tr bgcolor=\"$color\">";
  echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
  echo "<td width=\"47\" align=\"center\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"delete_or_apply_tarh_type.phtml?mainwindow=ranking.phtml&admin=$admin&seed=$seed&action=delete&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
  echo "<td width=\"47\" align=\"center\">";
  echo "<p align=\"center\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\"></td>";
  echo "<td width=\"74\" align=\"center\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$row_fetched["rank"]."</td>";
   echo "<td width=\"74\" align=\"center\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$row_fetched["year"]."</td>";

  echo "<td width=\"300\" align=\"center\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$row_fetched["jalase_date"]."</td>";

 echo "<td width=\"100\" align=\"center\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$row_fetched["end_date"]."</td>";

echo "<td width=\"100\" align=\"center\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".$row_fetched["start_date"]."</td>";


  echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
  echo "</tr>";

  }
  echo "<tr>";
  echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"74\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"74\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"300\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"100\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"100\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
  echo "</tr>";
  echo "</table>";
}
else
{

  echo "<p align=\"center\"  class=\"tahoma1\">با استفاده از فرم فوق ميتوانيد رنکهاي مختلف را بارگذاري کنيد";

}

   footer_forms($admin,$seed);
?>



