<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
$dastresi=$row_fetched["dastresi"];
if(strcmp($row_fetched["modir_type"],'4') ==0 )
  $modir_caution=" 1 ";
else
  $modir_caution='1';  
  
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
  
if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($current))
    $current = 1;



if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
  

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=$max_record;
      $current=1;
    }
    
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh ,user_login where tarh.finalized ='0' and user_login.email=tarh.creator  and indoing='1' and tarh_type!='6'   and $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and   $daneshkade_caution and $year_caution   and version='-1'   group by cod_tarh order by tarh_time desc";
}
else
  $query="select * from tarh  where tarh.finalized ='0' and  indoing='1' and tarh_type!='6'  and $modir_caution   and $daneshkade_caution and $year_caution  and version='-1' and ready_gharardad='1' group by cod_tarh order by tarh_time desc";

 

$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);


if(isset($name_e))
{
  $query="select * from tarh ,user_login where  tarh.finalized ='0'  and user_login.email=tarh.creator  and  indoing='1' and tarh_type!='6'   and  $modir_caution and (user_login.family  like $myname_search or  user_login.name  like $myname_search or cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and $daneshkade_caution and $year_caution   and version='-1'  group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from tarh  where tarh.finalized ='0'  and indoing='1' and tarh_type!='6'   and $modir_caution  and $daneshkade_caution and $year_caution  and version='-1'  group by cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh2");
 //echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرح هاي در حال اجرا<b></td>
 </tr>
 <tr>
 <td   align="center" class="tahoma1">
   رنگ قرمز به معني اچ اس آر و رنگ سبز به معني گرانت است
 </td> 
 </tr>
 </table>
 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\">  <select size=\"1\" name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" class=\"but-wide\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
  
?>
  </select>دانشکده / مرکز
  </td>
<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  <?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&tarh_type=$tarh_type\">";

?> 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
	
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
   $myascdescpub=$myascdescpub."&name_e=$name_e";
 pubshowpages("report_tarh_indoing_hazine.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
  
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">هزينه مواد</font></td> 
   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
        
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
   <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=tarh_title_farsi&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>عنوان فارسي</a></font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=cod_tarh&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>کد طرح</a></font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $position_tarh_code=current_position($cod_tarh);
  
  $query122="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='-1' order by name_dastgah";

   $result122=mysql_query($query122) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result122) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched122=mysql_fetch_array($result122))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched122["price"]*$row_fetched122["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }

   /////////////////////////////////////////////////////////////////////////////Start
  
  if($vasile_sum>10000000){
  echo "<tr>";
  
			echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$vasile_sum</td>";
    
    
 

  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
 
   $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
 
 
  
  
 

 
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'><font color=$color_line>". $daneshkade."</font></td>";
  
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line>". $farsistartdate."</font></td>";
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
    $First_mojri_name = "اطلاعات موجود نيست";
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$First_mojri_name."</font></a></td>";
  else
    echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["cod_tarh"]."</font></a></td>";
  echo "</tr>";
  }
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
if($reccount>0)
{
?>
 
 
<? 
} 
footer_forms($admin,$seed);


?>