<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

if ( ! isset($current))
    $current = 1;

$RecPerPage=12;
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=10000;
      $current=1;
    }



if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
   
   

if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   
      
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
else
$myname_search ="1";

if(isset($name_e))

$myname_search="cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search";
//echo $query;







?>


<?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>

 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class='tahoma1' name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
 
?>

</select> دانشکده / مرکز 
</td>
  
  
  
   

<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";

$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  
  
<?

 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </form>
 </tr>


 </table>
 <?






$query="select * from tarh,answer_mojri_gharardad    where    ( $myname_search ) and $daneshkade_caution and $year_caution and  tarh.cod_tarh=answer_mojri_gharardad.cod_tarh   AND indoing = '1'  order by tarh.cod_tarh desc ";

$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);


$query="select * from  tarh,answer_mojri_gharardad    where   ( $myname_search )  and $daneshkade_caution and $year_caution and   tarh.cod_tarh=answer_mojri_gharardad.cod_tarh AND indoing = '1' order by tarh.cod_tarh desc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage;



$result=mysql_query($query) or die("Error in selecting data from tarh 2"); 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><br><b>گزارش پرداخت<b></td>
 </tr>
 </table>
 
<?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";


}
if(mysql_num_rows($result) > 0 )
{
   $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";

 pubshowpages("report_yearly.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>

      <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">پيش بيني اعتبار مورد نياز براي سالهاي بعد</font></td>


 <!--     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">پيش بيني اعتبار مورد نياز براي سال 89</font></td>

      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">پيش بيني اعتبار مورد نياز براي طرح تا پايان 88</font></td>
-->
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">پرداخت شده تا امروز</font></td>
   
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">اعتبار پيش بيني شده براي طرح</font></td>
   
  <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ اتمام طرح</font></td>   

	<td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ شروع طرح</font></td>
   
    <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام طرح</font></td>  
   <td bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"> کد طرح</font></td>   
    </tr>
  <?

 $color=$list_color_1;
 $today=date("Y-m-d");
  $today_miladi=date("Y-m-d");

   $startyear = substr($today,0,4);
  $startmon = substr($today,5,2);
  $startday = substr($today,8,2);
  $today=hijricalender( $startyear , $startmon , $startday );

 $sum_today=0;
 $sum_other=0;
 $sum_aghd=0;
 while($row_fetched=mysql_fetch_array($result))
 {
  
  $cod_tarh=$row_fetched["cod_tarh"];	
 // $tarh_title_farsi=$row_fetched["cod_tarh"];	
   $start_time=$row_fetched["start_time"];	
   $time_month=$row_fetched["time_month"];
   $tarh_title_farsi =$row_fetched["tarh_title_farsi"];
   $mablagh_aghd=$row_fetched["mablagh_aghd_gharardad"];
   
   $sum_aghd=$sum_aghd+$mablagh_aghd;
    if( $start_time > 0 && $time_month > 0 )
 {
   $year=substr($start_time,0,4);
   $month=substr($start_time,5,2);
   $day=substr($start_time,8,2);
   $start_time=$day."/".$month."/".$year;
  // $month_add=$time_month+$month;
   $month_add=$time_month;
  // echo $month_add;
  // exit();
   for($i=1; $i<=$month_add;$i++)
   {
   	$month=$month+1;
    if($month >12 )
    {
      //$year_add=(int)($month_add/12); 
      $year_add++;
 	  $year=$year+1;	 	 	
      //$month=$month_add-($year_add*12); 
	  $month=1;    
     // if($month==0)
 	 //   $month=12;  
    }
    //else
     // $month=$month_add;
   }
  
   $end_time=$day."/".$month."/".$year;
 }
 else
 {
   $end_time="تعريف نشده";   
 }





$q="select sum( khales) as mablagh from tarh_indoing where cod_tarh='$cod_tarh' and date<='$today_miladi'";
 
$rf_q=mysql_query($q) or die("error");
$rf_q=mysql_fetch_array($rf_q);
$mablagh_today=$rf_q["mablagh"];
$sum_today=$sum_today+$mablagh_today;


$q="select sum( mablagh) as mablagh from tarh_indoing where cod_tarh='$cod_tarh' and date<='2010/03/20'";
$rf_q=mysql_query($q) or die("error");
$rf_q=mysql_fetch_array($rf_q);
$mablagh_88=$rf_q["mablagh"];

$mablagh_88=$mablagh_88-$mablagh_today;

$q="select sum( mablagh) as mablagh from tarh_indoing where cod_tarh='$cod_tarh' and date<='2011/03/20'";
$rf_q=mysql_query($q) or die("error");
$rf_q=mysql_fetch_array($rf_q);
$mablagh_89=$rf_q["mablagh"];
$mablagh_89=$mablagh_89-$mablagh_today-$mablagh_88;
//$mablagh_other=$mablagh_aghd-$mablagh_89-$mablagh_today-$mablagh_88;
$mablagh_other=$mablagh_aghd - $mablagh_today ;
$sum_other=$sum_other+$mablagh_other;

  echo "<tr>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_other)."</td>";
//  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_89)."</td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_88)."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_today)."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_aghd)."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$end_time."</td>";
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\">".$start_time."</td>";
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'>".$tarh_title_farsi."</td>";
    echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'>".$cod_tarh."</td>";

  echo "</tr>";
 }
 
 
   echo "<tr>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($sum_other)."</td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($sum_today)."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($sum_aghd)."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\" colspan='4'>&nbsp; </td>";

echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}
echo "</form>";
footer_forms($admin,$seed);
?>