<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");

?>

 <br>
<br> 
<form name="advanced_search" action="<?echo " reporting_result.phtml?admin=$admin&seed=$seed";?>" method="post">
  <table cellSpacing="0" cellPadding="0" width="550" border="0">
    
      <tr>
        <td width="100%" class='tahoma1'align='right'>
        گزارش گيري
        </td>
      </tr>
     
  </table>






<table dir="rtl" style="BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; BORDER-LEFT: 1px solid; BORDER-BOTTOM: 1px solid" borderColor="#333333" cellSpacing="0" cellPadding="2" width="550" height="100" bgColor="#eee7f8" border="0">


  <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%"></td>
    <td noWrap align="left" width="70%"></td>
  </tr>

  <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">سال/رنک </td>
    <?
    $query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  class=\"tahoma1\" align='right'><select size=\"1\" name=\"tarh_year\"   class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> 
  
  </tr>
  
  
  
  
  
  
  <tr bgColor="#eee7f8" nowrap>
    <td noWrap align="center" width="100%" colspan="2" dir="ltr" class="tahoma1">
    <input type="radio" CHECKED value="AND" name="GRP1" >AND
      &nbsp; 
      <input type="radio" value="OR" name="GRP1">OR &nbsp; 
      <input type="radio" value="NOT" name="GRP1">NOT</td>
  </tr>
  
  <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">
    هزينه ها</td>
    <td vAlign="center" noWrap align="right" width="70%" class="tahoma1">
        <select name="hazine_type" class="tahoma1">
        <option value="hazine_all" selected>همه هزينه ها</option>
        <option value="hazine_personnel">هزينه پرسنلي</option>
        <option value="hazine_azmayesh">هزينه آزمايشات و خدمات تخصصي</option>
        <option value="hazine_vasayel">فهرست وسايل و مواردي که بايد خريداري شود</option>
        <option value="hazine_mosaferat">هزينه مسافرت</option>
        <option value="hazine_others">هزينه هاي ديگر</option>
         
      </select>
     
	</td>
  </tr>
  
   <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">
    بيشتر از</td>
    <td vAlign="center" noWrap align="right" width="70%" class="tahoma1">
     <input maxLength="50" size="30" name="morethan" class="edit-user-advanced-search">  
     
	</td>
  </tr>
  
    <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">
    کمتر از</td>
    <td vAlign="center" noWrap align="right" width="70%" class="tahoma1">
     <input maxLength="50" size="30" name="lowerthan" class="edit-user-advanced-search">  
     
	</td>
  </tr>
  
     <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">
    بين</td>
    <td vAlign="center" noWrap align="right" width="70%" class="tahoma1">
     <input maxLength="50" size="30" name="first"  class="edit-user-advanced-search">  
                                                                                     و
     <input maxLength="50" size="30" name="second" class="edit-user-advanced-search">
	</td>
  </tr>
  
  
  <tr bgColor="#eee7f8" nowrap>
    <td noWrap align="center" width="100%" colspan="2" dir="ltr" class="tahoma1">
    <input type="radio" CHECKED value="AND" name="GRP2">AND
      &nbsp; <input type="radio" value="OR" name="GRP2">OR &nbsp; 
    <input type="radio" value="NOT" name="GRP2">NOT</td>
  </tr>
  
  <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%" class="tahoma1">
    موقعيت طرح</td>

	<td vAlign="center" noWrap align="right" width="70%" class="tahoma1">
        </select> 
      <select name="position" class="tahoma1">
        <option value="-1" selected>انتخاب کنيد</option>
        <option value="1">نامعلوم</option>
        <option value="2">قبول شده براي کارشناسي در سطح ساب ادمين</option>
        <option value="3">مصوب شوراي م /ت</option>
        <option value="4">رد در شوراي م/ت</option>
        <option value="5">ارسال به معاونت پژوهشي</option>
        <option value="6">دريافت توسط معاونت پژوهشي</option>
        <option value="7">کارشناسي در سطح معاونت پژوهشي</option>
        <option value="8">مصوب معاونت پژوهشي</option>
        <option value="9">در حال قرارداد</option>
        <option value="10">در حال اجرا</option>       
        <option value="11">خاتمه يافته</option>
        <option value="12">بايگاني طرح</option>
     

      </select>
 
	  </td>
  </tr>
  

  <tr bgColor="#eee7f8" nowrap>
    <td vAlign="center" noWrap align="left" width="30%"></td>
    <td noWrap align="left" width="70%"></td>
  </tr>
</table>

    <table cellSpacing="0" cellPadding="0" width="550"  border="0" bgColor="#FFFFFF">
     
        <tr>
          <td vAlign="center" noWrap align="middle" width="100%" bgColor="#FFFFFF">
            <div align="center">
              <input type="hidden" value="1" name="HIST">
			  <input type="reset" value="پاک کردن" class="but-small">
              <input type="submit" value="گزارش" class="but-small">
            </div>
          </td>
        </tr>
     
    </table>

  </form>
<?
footer_forms($admin,$seed);
?>
