<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";

if(isset($action))
{
  if (strcmp($action,"finish")==0)
  {
   
   	$query="update jalase_shora  set  send_moavenat=\"0\" where  jalase_id='$shomare_jalase' and creator='$sender'";
//echo $query;
        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
        $action="اعلام خاتمه طرح"."<br>".$tarh_name;
   
        set_log($action,$admin,date("Y-m-d, g:i a"));
		message_show("بازگشت صورت جلسه شورا<br><a href='jalase_shora_list.phtml?admin=$admin&seed=$seed'>ليست جلسات </a>","green");
		
		footer_forms($admin,$seed);
		exit();	
    
  }
}


?>


<?  echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=finish&admin=$admin&seed=$seed&shomare_jalase=$shomare_jalase&sender=$sender\">"; ?>

 
<br>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
  <TD align=right width="100%" class="tahoma1"   >
      بازگشت صورتجلسه
      </TD>
</tr>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8" cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
 
  <tr>
   
    <td width="100%" class="tahoma1" valign="top" align="right"><span class="star-message">در صورت بازگشت صورت جلسه ، صورت جلسه در اختيار دانشکده / مرکز قرار مي گيرد</span></td>
  </tr>


  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="بازگشت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>

<?
  footer_forms($admin,$seed);
 ?>




