<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


if(isset($action) )
{
  if (strcmp($action,"add_tarh")==0)
  {

    if( strlen(trim($tarh_type_1)) > 0 && strlen(trim($tarh_type_2)) > 0  )
    {
		$query="select * from savabetsystem ";
		$myresult=mysql_query($query) or die("Error in selecting data from savabetsystem");
		if(mysql_num_rows($myresult) > 0)
          $query="update savabetsystem  set tarh_type_1='$tarh_type_1' ,tarh_type_2='$tarh_type_2'";
        else
          $query="insert into  savabetsystem  set tarh_type_1='$tarh_type_1' ,tarh_type_2='$tarh_type_2'";


        $result=mysql_query($query) or die("Error in inserting data into tarh");
    }
    else
      $status="entry_error";
  }

}


  $query="select * from savabetsystem where 1 ";

  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  if(mysql_num_rows($result) > 0 )
  {
    $row_fetched=mysql_fetch_array($result);
    $tarh_type_1 = $row_fetched["tarh_type_1"];
    $tarh_type_2 = $row_fetched["tarh_type_2"];
  }
  else
  {
    $tarh_type_1 = "";
    $tarh_type_2 = "";
  }
?>


<?  echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=add_tarh&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/savabet_system.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }

?>
  <tr>
    <td width="350" align="right"><input type="text"  value=<? echo "\"$tarh_type_1\""; ?> name="tarh_type_1" size="20" value="<? echo $tarh_name; ?>" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>عنوان نوع طرح 1</td>
  </tr>
   <tr>
    <td width="350" align="right"><input type="text" value=<? echo "\"$tarh_type_2\""; ?> name="tarh_type_2"  value="<? echo $tarh_name_e; ?>" size="20" class="edit-user" dir=RTL    ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>عنوان نوع طرح 2</td>
  </tr>

 

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>

<TABLE cellSpacing=0 cellPadding=0 width="400" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/tarh-type.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
<?
  footer_forms($admin,$seed);
 ?>



