<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/class.phpmailer.php");
include("include/mailserver-statistics.phtml");
require_once('lib/nusoap.php');

echo "<br>";

$query="select * from modir_daneshkade where modir_username='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
$modir_family=$row_fetched["modir_family"];

if(isset($action))
{
  if (strcmp($action,"change_status")==0 )
  {
  	$mydate=date("Y-m-d");
  	$startyear = substr($mydate,0,4);
  $startmon = substr($mydate,5,2);
  $startday = substr($mydate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  
  	$payanname_akhlagh_comment=$payanname_akhlagh_comment."<br>".$modir_family." ".$farsistartdate;
    $query="update tarh set  payanname_akhlagh='$payanname_akhlagh' ,payanname_akhlagh_comment='$payanname_akhlagh_comment'  where cod_tarh='$cod_tarh'";
  insert_position($cod_tarh,"34",$admin);
    //  echo $query;
   //exit();
    $result=mysql_query($query) or die("Error in updating tarh type in tarh");
 //   insert_position($cod_tarh,"8",$admin);
     ?>
           <script language="javascript">
            window.location="<? echo "payanname_list_new_before_akhlagh".".phtml?admin=$admin&seed=$seed&current=$current";  ?>";
           </script>
           <?
  }

}

?>

<? echo "<form name=\"change_status\" method=\"post\" action=\"$PHP_SELF?action=change_status&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&main_window=$main_window&current=$current\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 width="100%" cellPadding=0 border=1>
  <TBODY>
    <TR>
    <TD align=right width="100%"  class="tahoma1" height=19>
     
ارسال به طرح هاي بررسي اخلاقي شده      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


 <tr>
    <td width="100%" colspan="2" class="tahoma1">
      <p align="center">ارسال به طرح هاي بررسي اخلاقي شده</td>
</tr>

 <tr>
    <td width="20%" align="right" class="tahoma1" valign="top"><input type='radio' name='payanname_akhlagh' value='1'>تاييد اخلاق</td>
    </tr>
    <tr>
    <td width="20%" align="right" class="tahoma1" valign="top"><input type='radio' name='payanname_akhlagh' value='0'>رد اخلاق</td>
  </tr>

   <tr>
    <td width="80%" align="right"><textarea   rows="7"  name="payanname_akhlagh_comment"  class="edit-user"  dir=RTL   ></textarea></td>
    <td width="20%" class="tahoma1" valign="top"> توضيحات</td>
  </tr>
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="#" onClick="history.go('-1')" >بازگشت</a></td>
  </tr>
</table>
<?

  footer_forms($admin,$seed);
 ?>




