<?
include("include/database-connect.phtml");
include("include/include.phtml");
require("include/class.phpmailer.php");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/vars.inc.phtml");
include("include/print.phtml");
require("include/mailserver-statistics.phtml");
require_once('lib/nusoap.php');
if(isset($action))
{
  $i=0;
  if (strcmp($action,"send_karshenas")==0)
  {
   for($i==0;$i<400;$i++)
   {
    $myvariable="check".$i;
    $myuser="value_".$i;
    if (isset($$myvariable))
    {
      $myvariable="check".$i;
      $myuser="value_".$i;
      $mycodkarshenas = "cod_karshenas_".$i;
      $myname_family="name_".$i;
	//  $mail = new PHPMailer();
	 // ob_start();
	  //send_mail_tarh($cod_tarh);
     // $emailbody=ob_get_contents();
    //  ob_end_clean();
    //  ob_end_flush();

    //  $mail->IsSMTP();                                      // set mailer to use SMTP
    //  $mail->SMTPAuth=$smtpauth;
   //   $mail->Username=$email_username;
   //   $mail->Password=$email_password;
   //   $mail->Host = $mailserver_host;  // specify main and backup server

     // $mailname=$$myname_family;
    //  $mail->From = $email_from;
	//  $mail->FromName = $email_from_name;
    //  $mail->AddAddress($$myuser, $mailname);
    //  $mail->IsHTML(true);                                  // set email format to HTML

     // $mail->Subject = "طرح پژوهشي ارسال شده از طرف مدير سيستم";
     // $mail->Body    = $emailbody;
    //  $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
     /* if(!$mail->Send())
      {
          $status="mail_err";
      }
      else
      {
          message_show(".طرح به کارشناس مربوطه ارسال شد","green");
          footer_forms($admin,$seed);
          exit();
      }*/

	 // $i++;

	    $query="select * from karshenasan_tarh where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\" and finished=0";
	   
	  $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh");
	  //echo $query;
	  if ( mysql_num_rows($result)==0 )
	  {
	    $mydate=date("Y-m-d");
	    $query="insert into karshenasan_tarh set  send_to_karshenas_date='$mydate',cod_tarh=\"$cod_tarh\" , cod_karshenas=\"".$$mycodkarshenas."\"";
	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh");
	    
	    $query="select * from karshenasan where  cod_karshenas=\"".$$mycodkarshenas."\"";
	   // echo $query;
	     $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh");
	//echo $query;
	//exit();
	  		$row_fetch_email=mysql_fetch_array($result);

	     $mobile=$row_fetch_email["mobile"];
	  	$karshenas_email=$row_fetch_email["karshenas_email"]; 
	  	$familye=$row_fetch_email["karshenas_family"];
	  //  echo $karshenas_email;
	  //  exit();
	//   echo "mohsen".$query; 
	  //  echo "aaaaaaaaaaaaaaaaaaaaaa";
   // exit();
	     $mail = new PHPMailer();
	 $query_title_tarh="select * from tarh where cod_tarh = '$cod_tarh'";
	 $result_title_tarh=mysql_query($query_title_tarh);
	 $rf_title=mysql_fetch_array($result_title_tarh);
	 $title_english=$rf_title["tarh_title_english"];    
     $creator=$rf_title["creator"];    
	$emailbody="";
    $emailbody=$emailbody."<br><b>You got a  proposal '$title_english' <b><br><br>";
    $emailbody=$emailbody."<br>Please login to your Supervisor area of Pajooheshyar and check it<br>";
    $emailbody=$emailbody."<br>You can find it in this menu item ==> 'TARH-HAYE-DAR-HALE-EJRA'<br>";
	$emailbody=$emailbody."<br>Tarh Code is : $cod_tarh<br>";
    $emailbody=$emailbody."<br>You can guide with this link <a href='http://research.tums.ac.ir/sg.pdf' target='_blank'> Guide </a> <br>";
    $emailbody=$emailbody."Please login at: <a href=".$url_address."/login/>Here</a>";
    $emailbody=$emailbody."<center><font face=Arial size=2 color=green>This email has been sent by <a href=\"".$url_address."\">".$url_address."</a>";
    $emailbody=$emailbody."<br>Powered by Peyvand Co. (Peyvandco.com).</font></center>";

    $mail->IsSMTP();                                      // set mailer to use SMTP
    $mail->SMTPAuth=$smtpauth;
    $mail->Username=$email_username;
    $mail->Password=$email_password;
	                                      // set mailer to use SMTP
	$mail->Host = $mailserver_host;  // specify main and backup server
    $mailname=$familye;
    $mail->From = $email_from;
	$mail->FromName = $email_from_name;
    $mail->AddAddress($karshenas_email, $mailname);
    $mail->IsHTML(true);                                  // set email format to HTML
   
   
   $string_nazer="Nazer mohtaram dar mohit nezarat pajoheshyar shoma tarhi baraye nezarat ba code". $cod_tarh ."ersal shode ast (Mohlat zamani 2 hafte)";
    send_sms($mobile,$string_nazer);
 ///   send_sms($mobile,'Check your inbox in pajoheshyar You got a Proposal for review');
    $mail->Subject = "Check your box in $url_address (Do not reply this email)";
    $mail->Body    = $emailbody;
    $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
    if(!$mail->Send())
    {
        $status="mail_err";
//        echo $status;
  //      exit();
    }
	 
     $query="select * from user_login where email='$creator'";
     $rs_mojri=mysql_query($query) or die("error");
	 $rf_mob_mojri=mysql_fetch_array($rs_mojri);
	 $mobile_mojri=$rf_mob_mojri["mobile"];
     send_sms($mobile,'tarh shoma ba code $cod_tarh be nazer tarh ersal shod $url_address');		
	    
	    
	    
	  }
    }
  }

  }
}
   echo "<br>";
   $query="select * from karshenasan,karshenas_type where  karshenasan.karshenas_type=karshenas_type.karshenas_type and karshenasan.karshenas_type='8' order by karshenasan.karshenas_family asc";
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";

//    $query="select * from mojri , mojri_tarh where mojri.mojri_code = mojri_tarh.mojri_code and mojri_tarh.cod_tarh=\"$cod_tarh\"   order by  family ";
  //  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");

    ?>
<? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=send_karshenas&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

    <table border="0" width="90%" cellpadding="1" cellspacing="1">
    <tr>
    <td width="100%" bgcolor="#66CCFF"  colspan="6">

      <p align="center" class="tahoma1"><font color="black">ارسال براي کارشناسان </font></td>
    </tr>

	<tr>
    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">وضعيت ارسال</font></td>
	<td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">ارسال</font></td>
    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">پست الکترونيکي</font></td>
   <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نوع کارشناس</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
    </tr>
  <?

 $color=$list_color_1;
  $i=0;
 while($row_fetched=mysql_fetch_array($result))
 {
 // $cod_tarh=$row_fetched["cod_tarh"];
  $cod_karshenas=$row_fetched["cod_karshenas"];
  $query="select * from karshenasan_tarh where cod_karshenas='$cod_karshenas' and cod_tarh='$cod_tarh'";
  
  $result1=mysql_query($query);
  if(mysql_num_rows($result1) > 0)
  {
     $sended="<b>به اين کارشناس ارسال شده</b>";
     
  }
  else
  $sended="به اين کارشناس ارسال نشده";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"check".$i."\"  value=\"ON\"></td>";
  echo "<input type=\"hidden\" name=\"value_".$i."\" value=\"".$row_fetched["karshenas_email"]."\">";
  echo "<input type=\"hidden\" name=\"name_".$i."\" value=\"".$row_fetched["karshenas_name"]."&nbsp;".$row_fetched["kar_tahghigh_family"]."\">";
  echo "<input type=\"hidden\" name=\"cod_karshenas_".$i."\" value=\"".$row_fetched["cod_karshenas"]."\">";
  
echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$sended."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  echo "</tr>";
  $i++;
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }


echo "</table>";
echo "<br><input type=\"submit\" value=\"ارسال\" name=\"B1\" class=\"but-small\">";
echo "</form>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ کارشناسي  يافت نشد","red");
}


footer_forms($admin,$seed);
?>

