<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");

echo "<br>";
 
if(isset($action))
 {
 if(strcmp($action,"del")==0)
  {
  	$query="delete from subadmin_sms where id='$delete_id'";
  	//echo $query;
  //	exit();
  	$result=mysql_query($query) or die("Error");
  	
  }
 }

$RecPerPage=30;
//confirm_tarh=1
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
    
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;
if ( ! isset($tarh_year))
    $tarh_year = '-1';




if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

//echo $tarh_year;
if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;


  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=10000;
      $current=1;
    }
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

if(isset($name_e)  && strlen(trim($name_e))>0)
{
  $query="select * from subadmin_sms where    (letter_body like $myname_search) order by id desc  ";
}
else
  $query="select * from subadmin_sms where 1 order by id desc " ;



$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e) && strlen(trim($name_e))>0)
{
  $query="select * from subadmin_sms where    (letter_body like $myname_search) order by id desc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from subadmin_sms where  1  order by id desc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;

 

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>ليست پيام هاي کوتاه<b></td>
 </tr>
 
 </table> 
 
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    

echo "<td  align=\"left\" class=\"tahoma1\"></td>";
 
 
 
 echo "<td  align=\"left\" class=\"tahoma1\"> </td>";
 
  
 
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&tarh_type=$tarh_type\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 
 </tr>


 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 //$myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";	
	
 pubshowpages("subadmin_sms_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
  <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">حذف</font></td>
   
   <td width="40%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">متن پيام کوتاه</font></td>
     <td width="12%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تلفن گيرنده پيام</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال کننده</font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
 	
   
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=subadmin_sms_list.phtml&admin=$admin&seed=$seed&action=delete_sms&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a</td>";
  echo "<td bgcolor=$color width=\"40%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["letter_body"]."</td>";
  echo "<td bgcolor=$color width=\"12%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["telno"]."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"> ".$row_fetched["sender"]."</td>";
 
  echo "</tr>";

 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show("پيام کوتاهي يافت نشد","red");
}
 
  
footer_forms($admin,$seed);


?>
