<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";
$query="select * from modir_daneshkade where accept_gharardad='on'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$modir_count=mysql_num_rows($result);

$query="select * from modir_daneshkade where modir_username='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
$row_fetched=mysql_fetch_array($result);
$dastresi=$row_fetched["dastresi"];
$modir_name=$row_fetched["modir_name"];
$modir_family=$row_fetched["modir_family"];
$modir_email=$row_fetched["modir_email"];
$modir_cod=$row_fetched["cod_modir"];

if(strcmp($row_fetched["modir_type"],'4') ==0 )
  $modir_caution=" 1 ";
else
  $modir_caution='1';  
  
    if(strcmp($action,"confirm_tarh")==0)
  {
  	
  	
  for($j=1;$j<30;$j++)
   {
   
    $cod='checktarh'.$j;
    if(isset($$cod))
    {
     $cod_tarh=$$cod;
     
    $query="select * from modir_accept_gharardad where cod_tarh=\"$cod_tarh\" and modir_username='$admin' ";
    $result=mysql_query($query) or die("Error in updating data into tarh");
    if(mysql_num_rows($result) > 0)
    {
           $row_fetched=mysql_fetch_array($result);
    	$modir_comment=$row_fetched["modir_comment"];
    	  $startdate=date("Y-m-d");
    	  $startyear = substr($startdate,0,4);
		  $startmon = substr($startdate,5,2);
		  $startday = substr($startdate,8,2);
		  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
    	  $modir_comment=$modir_comment."<br>".$modir_comment1." "."$farsistartdate";
    	  
    	  
        $query="update modir_accept_gharardad set accept_gharardad='1',modir_comment='$modir_comment', date='".date("Y-m-d")."'  where cod_tarh=\"$cod_tarh\" and modir_username='$admin' ";
      	mysql_query($query) or die("Error in updating data into tarh");
	    $query="select * from modir_accept_gharardad where cod_tarh=\"$cod_tarh\" and accept_gharardad='1' ";
	    $result=mysql_query($query) or die("Error in updating data into tarh");
	    $accept_count=mysql_num_rows($result);
	    if($accept_count==$modir_count)
	    {
	    	$query="select * from max_gharardad_cod";
	    	$result=mysql_query($query) or die("Error in updating data into tarh");
	    	$row_fetched=mysql_fetch_array($result);
	    	$max_gharardad_cod=$row_fetched["max_gharardad_cod"];
	    	$max_gharardad_cod_new=$max_gharardad_cod+1;
	    	$query="update max_gharardad_cod set max_gharardad_cod='$max_gharardad_cod_new' where max_gharardad_cod='$max_gharardad_cod'";
	    	$result=mysql_query($query) or die("Error in updating data into tarh");
	    	$query="update tarh_hesabdari set accept_cod='$max_gharardad_cod' where researchno='$cod_tarh'";
	    	$result=mysql_query($query) or die("Error in updating data into tarh");
	    	
	    	$query="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and  cod_tarh='$cod_tarh'  and group_karshenasan.karshenas_type='1'";
		    //echo $query;
		    $result=mysql_query($query) or die("Error 120000 ff");
			$rf=mysql_fetch_array($result);
			$sms_box=$rf["sms_box"]; 
			//echo $sms_box;
			$startdate =$send_date;
		    $startyear = substr($startdate,0,4);
		    $startmon = substr($startdate,5,2);
		    $startday = substr($startdate,8,2);
		    $send_date=hijricalender( $startyear , $startmon , $startday ); 
			 
			$query="insert into input_sms set sms_from='ADMIN' ,sms_to='$sms_box' , sms_text='tarh ba code $cod_tarh dar mohit amade be gharardad code taeide modiran ra daryaft kard.'";
			//  echo $query;
			$result=mysql_query($query) or die("Error 120000 er");
	    }
    }
    else{
    	  $startdate=date("Y-m-d");
    	  $startyear = substr($startdate,0,4);
		  $startmon = substr($startdate,5,2);
		  $startday = substr($startdate,8,2);
		  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
    	  $modir_comment=$modir_comment1." "."$farsistartdate";
    	
    	$query="insert into modir_accept_gharardad set accept_gharardad='1',modir_comment='$modir_comment',modir_name='$modir_name',modir_family='$modir_family',modir_email='$modir_email',modir_username='$admin',modir_cod='$modir_cod',cod_tarh='$cod_tarh', date='".date("Y-m-d")."'";
		echo $query;
    	mysql_query($query) or die("Error in updating data into tarh1");
   	 	$query="select * from modir_accept_gharardad where cod_tarh=\"$cod_tarh\" and accept_gharardad='1' ";
	    $result=mysql_query($query) or die("Error in updating data into tarh2");
	    $accept_count=mysql_num_rows($result);
	    if($accept_count==$modir_count)
	    {
	    	$query="select * from max_gharardad_cod";
	    	$result=mysql_query($query) or die("Error in updating data into tarh3");
	    	$row_fetched=mysql_fetch_array($result);
	    	$max_gharardad_cod=$row_fetched["max_gharardad_cod"];
	    	$max_gharardad_cod_new=$max_gharardad_cod+1;
	    	$query="update max_gharardad_cod set max_gharardad_cod='$max_gharardad_cod_new' where max_gharardad_cod='$max_gharardad_cod'";
	    	echo $query;
	    	$result=mysql_query($query) or die("Error in updating data into tarh4");
	    	$query="update tarh_hesabdari set accept_cod='$max_gharardad_cod' where researchno='$cod_tarh'";
	    	$result=mysql_query($query) or die("Error in updating data into tarh5");
	    	
	    	$query="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and  cod_tarh='$cod_tarh'  and group_karshenasan.karshenas_type='1'";
		    //echo $query;
		    $result=mysql_query($query) or die("Error 120000 ff");
			$rf=mysql_fetch_array($result);
			$sms_box=$rf["sms_box"]; 
			//echo $sms_box;
			$startdate =$send_date;
		    $startyear = substr($startdate,0,4);
		    $startmon = substr($startdate,5,2);
		    $startday = substr($startdate,8,2);
		    $send_date=hijricalender( $startyear , $startmon , $startday ); 
			 
			$query="insert into input_sms set sms_from='ADMIN' ,sms_to='$sms_box' , sms_text='tarh ba code $cod_tarh dar mohit amade be gharardad code taeide modiran ra daryaft kard.'";
			  echo $query;
			$result=mysql_query($query) or die("Error 120000 er");
	    }
    }
    
    }

   }
   
  }
  
if ( ! isset($tarh_type))
    $tarh_type = '-1';
 
if(strcmp($tarh_type,'-1')!=0 )
{
	$tarh_type_caution="tarh.tarh_type = '$tarh_type'";
}
else
   $tarh_type_caution=1;
  
if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($current))
    $current = 1;



if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   
$cod_daneshkade_new=$cod_daneshkade;

if(isset($tarh_year) and strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
  

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
if(isset($name_e))
{
  $query="select * from tarh ,tarh_hesabdari where  tarh_hesabdari.researchno=tarh.cod_tarh and  indoing='0'    and $modir_caution and (tarh_hesabdari.personname  like $myname_search or tarh_hesabdari.researchno like $myname_search or  tarh.tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and   $daneshkade_caution and $year_caution  and version='-1' and ready_gharardad='1' and tarh_hesabdari.researchno not in (select cod_tarh from modir_accept_gharardad where modir_username='$admin' and accept_gharardad='1') group by tarh.cod_tarh order by tarh_hesabdari.date desc";
}
else
  $query="select * from tarh,tarh_hesabdari  where   tarh_hesabdari.researchno=tarh.cod_tarh and indoing='0'    and $modir_caution  and $daneshkade_caution and $year_caution  and version='-1' and  tarh_hesabdari.researchno not in (select cod_tarh from modir_accept_gharardad where modir_username='$admin' and accept_gharardad='1') and ready_gharardad='1' group by tarh.cod_tarh order by tarh_hesabdari.date desc";

 //echo $query;
 
$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);


if(isset($name_e))
{
  $query="select * from tarh,tarh_hesabdari  where   tarh_hesabdari.researchno=tarh.cod_tarh  and   indoing='0'   and  $modir_caution and (tarh_hesabdari.personname like $myname_search or tarh_hesabdari.researchno like $myname_search or tarh.tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)     and $daneshkade_caution and $year_caution   and version='-1' and ready_gharardad='1' and tarh_hesabdari.researchno not in (select cod_tarh from modir_accept_gharardad where modir_username='$admin' and accept_gharardad='1') group by tarh.cod_tarh order by tarh_hesabdari.date desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from tarh,tarh_hesabdari where   tarh_hesabdari.researchno=tarh.cod_tarh and indoing='0'    and $modir_caution    and $daneshkade_caution and $year_caution  and version='-1' and tarh_hesabdari.researchno not in (select cod_tarh from modir_accept_gharardad where modir_username='$admin' and accept_gharardad='1') and ready_gharardad='1' group by tarh.cod_tarh order by tarh_hesabdari.date desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh2");
 //echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرحهاي آماده به قرارداد<b></td>
 </tr>
 <tr>
 <td   align="center" class="tahoma1">
   رنگ قرمز به معني اچ اس آر و رنگ سبز به معني گرانت است
 </td> 
 </tr>
 </table>
 <?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";
?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\">  <select size=\"1\" name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" class=\"but-wide\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
  
?>
  </select>دانشکده / مرکز
  </td>
<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  <?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&tarh_type=$tarh_type\">";

?> 
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
echo "</form>";
$current_new=$current+1;
}
if(mysql_num_rows($result) > 0 )
{
	echo "<form name=\"sabt_matrah_shode\" method=\"post\"  action=\"$PHP_SELF?action=confirm_tarh&admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&current=$current_new\">";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
   $myascdescpub=$myascdescpub."&name_e=$name_e";
 pubshowpages("tarh_list_confirm_gharardad.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مراحل قرارداد و بازگشت</font></td>
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به طرح هاي در حال اجرا</font></td>  
      
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاييدات مديران پژوهشي</font></td>  
      
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">درخواست کنترل قرارداد</font></td>
      
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">درخواست بازبيني</font></td>
      
      <td  bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><input type="checkbox" name="checkall" onClick="checkUncheckAll(this);">تاييد قرارداد</font></td>
       
     <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مبلغ عقد قرارداد</font></td>  
      
       <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ شروع و اتمام قرارداد</font></td>  
      
       <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر مدير گروه کارشناسي و کارشناسان و شوراي پژوهش دانشگاه</font></td>
 
     <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>  
         <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
       
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال نامه</font></td> 
      
        <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح از نظر کارشناسي</font></td>
  
   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
        
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"> تاريخ ارسال توسط کارشناس</font></td>
       <td width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ثبت کننده طرح</font></td>
      
    <td width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري طرف قرارداد</font></td>
   <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=tarh_title_farsi&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>عنوان فارسي</a></font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><a href=<? echo "tarh_list_new.phtml?cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=cod_tarh&ascdesc=$ascdesc&admin=$admin&seed=$seed"; ?>>کد طرح</a></font></td>
  </tr>
  <?

 $color=$list_color_1;
  $k=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
   $ttype_2=$row_fetched["tarh_type_2"];
  $color_line="black";
  $tarh_type_q="select * from tarhtype_2 where tarh_type='$ttype_2' and (tarh_type_desc like \"%گرانت%\" or  tarh_type_desc like \"%گرنت%\")";
  //echo $tarh_type_q;
  $tarh_type_r=mysql_query($tarh_type_q) or die("error");
  if(mysql_num_rows($tarh_type_r)>0)
  {
  	 $color_line="green";
  }
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   $mablagh_aghd_gharardad=$row_fetched["amount"];
   $qu="select * from modir_accept_gharardad where cod_tarh='$cod_tarh'";
   $myres=mysql_query($qu);
   $count_accept=mysql_num_rows($myres);
	$modir_accept="";
	$modir_name_family="";
   while($myrf=mysql_fetch_array($myres)){
   	$accept_gharardad=$myrf["accept_gharardad"];
   	if($accept_gharardad=="1")
   		$accept="تاييد";
   	else 
   		$accept="بازگشت";
   $modir_name_family.=$myrf["modir_name"]." ".$myrf["modir_family"]." ".$accept."<br>";
   }
  echo "<tr>";
  $accept_cod=$row_fetched["accept_cod"];
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"confirm_gharardad.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&current=$current\" >تاييد قرارداد</a></td>";
  if(strlen($accept_cod)>1){
  	echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"send_in_doing.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ارسال به طرح هاي در حال اجرا <br> کد قرارداد $accept_cod</a></td>";
  }
  else{
  	echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/cancel.png\"  alt=\"شما به اين گزينه دسترسي نداريد\" ></td>";
  }
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"accept_gharardad.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><b><font color='green'>$modir_name_family</font></b></a></td>";
  
  $myquery="select * from control_gharardad_tarh where (cod_tarh=\"$cod_tarh\") ";
    $myresult=mysql_query($myquery) or die("Error in selecting data from tarh  ");
	$num_rows=mysql_num_rows($myresult);
      if ( $num_rows > 0 )
           	$control_gharardad_status="<b>دارد</b>";
      else 
 	    	$control_gharardad_status="ندارد";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"control_gharardad_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color='green'>$control_gharardad_status</font></a></td>";
  
    $myquery="select * from group_karshenasan_tarh where (cod_tarh=\"$cod_tarh\") ";
    $myresult=mysql_query($myquery) or die("Error in selecting data from tarh  ");
	$myrf1=mysql_fetch_array($myresult);
	$bazbini_req=$myrf1["bazbini_req"];
      if ( $bazbini_req !="")
           	$bazbini_req_status="<b><font color='red'>دارد</font></b>";
      else 
 	    	$bazbini_req_status="ندارد"; 
  
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"new_gharardad_bazbini_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color='green'>$bazbini_req_status</font></a></td>";
  
  
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type='checkbox' name=checktarh".$k." value='$cod_tarh' ></td>";
  $k++;
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".number_format($mablagh_aghd_gharardad)."</td>";
  $start_date=$row_fetched["startdate"];
  $end_date=$row_fetched["enddate"];
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$start_date."<br>".$end_date."</td>";
//  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target='_blank' style=\"text-decoration:none\" href=\"rtf.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >چاپ قرارداد</a></td>";
   $position_tarh_code=current_position($cod_tarh);	
  
   $i=check_field_value($dastresi,"a27");
  if($i=="on"){
      echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"group_karshenas_notes.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُGroup Karshenasan Notes\" ></a></td>";
  }
  else 
      echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/cancel.png\"  alt=\"شما به اين گزينه دسترسي نداريد\" ></td>";
 
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويرايشها</a></td>";
   
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
  
  //echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a  href=\"send_tarh_after_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ارسال به طرحهاي بعد از تصويب</a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To...\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target = \"_blank\" href=\"shenasname_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/shenasname_tarh.gif\" width=\"11\" height=\"13\" alt=\"Shenasname tarh\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["status"]=="0")
  {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }


  $startdate = $row_fetched["date"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
 
 
    $status_comment="";

  $q="select distinct group_karshenasan.* from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas   ";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	    $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }	
	 else
	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
	 }
  	}
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  }
 
 
  
  
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh' and version='-1'";
 
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    
  }

 

  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line>".$status_comment."</font></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration : none\" href=\"change_status_after_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mystatus."</a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $daneshkade."</font></a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>". $farsistartdate."</font></a></td>";
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  
 $name=$row_fetched["personname"];
 $family=$row_fetched["family"];
 $First_mojri_name="";
 $First_mojri_name=$name;
 $id=$row_fetched["id"];
 
 $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
  
    $First_mojri = mysql_fetch_array($myresult_mojri);
    $First_mojri_name_asli = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
   
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name_asli = "اطلاعات موجود نيست";
  }
 
    
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line>".$First_mojri_name_asli."</font></td>";
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"mojri_info.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&id=$id\" ><font color=$color_line>".$First_mojri_name."</font></a></td>";
    echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["cod_tarh"]."</font></a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
 echo " <tr>";
echo "    <td width=\"100%\" colspan=\"19\">";
pubshowpages("tarh_list_confirm_gharardad.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
echo "    </td>";
echo "  </tr>";
 
 echo " <tr>";
echo "    <td width=\"100%\" colspan=\"19\">";
echo "      <p align=\"center\"><input type=\"submit\" value=\"تاييد قرارداد\" name=\"B1\" class=\"but-small\"></td>";
echo "  </tr>";

 
echo "</table>";

 echo "</form>";
}

else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}

 
footer_forms($admin,$seed);


?>