<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";

 
 
  $query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
   
  $result=mysql_query($query) or die("Error");
   
     $mycount=0;
    if(mysql_num_rows($result) > 0)
    {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\"  colspan='3' align=\"center\"  class=\"tahoma1\">مشاهده گزارشات</td>";
      echo "</tr>";
      echo "<tr>";
       
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">توضيحات</td>";
      echo "</tr>";

     //echo $dir_name;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$id=$row_fetched["id"];
	      echo "<tr>";
        // echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=send_marhale_report.phtml&admin=$admin&seed=$seed&action=delete_file&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         echo "<td align=\"center\"  class=\"tahoma1\"><a target=\"_blank\" href=\"../reports/$cod_tarh/$file".$row_fetched["filename"]."\">".$row_fetched["filename"]."</a></td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["send_date"]."</td>";
         echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["comments"]."</td>";
         echo "</tr>";
	   
     }
      
      echo "</table>";
	 }
	 else 
	 {
	 	 echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\"  colspan='3' align=\"center\"  class=\"tahoma1\">موردي يافت نشد</td>";
      echo "</tr>";
      echo "</table>";
      
	 }
     
    
     

  

 footer_forms($admin,$seed);
?>







<?
   footer_forms($admin,$seed);
 ?>




