<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

//header_forms($admin,$seed);
global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);

  if( $type == 1 )
    updatesession($username,$rand);
  else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
 }

include("include/styles.phtml");

echo "<br>";

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

if ( ! isset($tarh_year))
    $tarh_year = '-1';



/*
if(strcmp($admin,"rezaii@tums.ac.ir")==0)
  $refered_shora=" tarh.refered_shora ='0' ";
else
  $refered_shora="1";
  */
  
  // $query="select * from tarh,vaziat_tarh  where refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and  $year_caution  and  $daneshkade_caution  and vaziat_tarh.vaziat=tarh.vaziat_moaven and  confirm_moaven_tarh='1' and tarh.version='-1'  and $refered_shora group by cod_tarh  order by right(cod_tarh,4) desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage;

 $refered_shora="1";
if(isset($name_e))                     
{
  $query="select * from tarh,vaziat_tarh  where   refered_shora='0' and send_karshenas_shora='1' and tarh_type!='6' and  $daneshkade_caution  and (cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and vaziat_tarh.vaziat=tarh.vaziat_moaven   and confirm_moaven_tarh='1'  and tarh.version='-1' and  $refered_shora  group by cod_tarh order by right(cod_tarh,4) asc" ;
}
else
  $query="select * from tarh,vaziat_tarh  where  refered_shora='0' and send_karshenas_shora='1' and tarh_type!='6' and  $daneshkade_caution  and vaziat_tarh.vaziat=tarh.vaziat_moaven  and confirm_moaven_tarh='1'   and tarh.version='-1'  and $refered_shora group by cod_tarh order by right(cod_tarh,4) asc" ;


$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);


 if(isset($name_e))
{
  $query="select * from tarh,vaziat_tarh  where   refered_shora='0' and send_karshenas_shora='1' and  tarh_type!='6' and  $daneshkade_caution  and (cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and vaziat_tarh.vaziat=tarh.vaziat_moaven   and confirm_moaven_tarh='1'  and tarh.version='-1'  and $refered_shora group by cod_tarh order by right(cod_tarh,4) asc";
}
else
  $query="select * from tarh,vaziat_tarh  where  refered_shora='0' and send_karshenas_shora='1' and tarh_type!='6' and   $daneshkade_caution  and vaziat_tarh.vaziat=tarh.vaziat_moaven and  confirm_moaven_tarh='1' and tarh.version='-1'  and $refered_shora group by cod_tarh  order by right(cod_tarh,4) asc";




$result=mysql_query($query) or die("Error in selecting data from tarh2");


if(mysql_num_rows($result) > 0 )
{
$myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc";
if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";
if(isset($tarh_year))
  $myascdescpub=$myascdescpub."&tarh_year=$tarh_year";
/// pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#8099B7");
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
<?
if(strcmp($admin,"rezaii@tums.ac.ir")==0)
{
?>

<?
}
?>
 <td width="35%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">هزينه هاي طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده / مرکز</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اصلي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رتبه</font></td>

     <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>

    <td width="35%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
  </tr>
  <?


 $color=$list_color_1;
$cntr=($current-1)*$RecPerPage+1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
   $rotbe = $row_fetched["rotbe_tarh"];
   $cod_daneshkade=$row_fetched["cod_daneshkade"];
   $left_cod=substr($cod_tarh,0,8);
//left($cod_tarh,8);
   $myq1="select max(rotbe_tarh) as max_rotbe from tarh where cod_daneshkade='$cod_daneshkade' and left(cod_tarh,8)='$left_cod'";

//exit();
$myres11=mysql_query($myq1) or die("Error ");
$rf11=mysql_fetch_array($myres11);
$max_rotbe=$rf11["max_rotbe"];

  
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;

 $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
     {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else
       $mystatus="نامعلوم";
  }
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }






 $mytarh_type = $row_fetched["status"];
 $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];


  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To Karshenas\" ></a></td>";
 if(strcmp($admin,"rezaii@tums.ac.ir")==0)
{
 // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">ارسال</td>";
 // echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\" alt=\"Your Notes\" ></a></td>";
  // echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"karshenasan_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\" alt=\"Karshenasan Notes\" ></a></td>";
}


  $query100="select * from karshenas_shora where kar_shora_email='$admin'";
   //echo $

  $result100=mysql_query($query100) or die ("Error in selecting data 1111");

  $row_fetched100=mysql_fetch_array($result100);
  $karshenas_id=$row_fetched100["cod_karshenas"];

  $myq1="select * from karshenas_shora_tarh where cod_tarh='$cod_tarh' and cod_karshenas='$karshenas_id'";

  $rs1=mysql_query($myq1) or die("error");

  if(mysql_num_rows($rs1) >0)
  {
  	$rf1=mysql_fetch_array($rs1);
  	$mynotes=$rf1["notes"];
   	if(strlen(trim($mynotes)) > 0)
  	  $nazar="<br>(نظردهي شده)<br>";
  	else
	  $nazar="";
  }
  // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='send_your_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>$nazar نظرات شما</a></td>";
  echo "<td width=\"35%\" bgcolor=$color align=\"center\" class=\"tahoma1\">";
  echo hazineha_detail_view($cod_tarh);
  echo "</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
 
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$farsistartdate."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$daneshkade."</a></td>";
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$row_fetched["tarh_title_english"]."</a></td>";

  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }
   echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">"." رتبه ".$rotbe." از ".$max_rotbe."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$First_mojri_name."</a></td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$row_fetched["tarh_title_farsi"]."</a></td>";

  $cod_tarh_user=$row_fetched["cod_tarh_user"];


     echo "<td width=\"15%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$cod_tarh."</td>";
 echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$cntr."</td>";
 $cntr++;
  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".در حال حاضر طرح ارسال شده اي به شما وجود ندارد","red");
}
echo "</form>";
//footer_forms($admin,$seed);
?>

