<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");

echo "<br>";


$q="select * from karshenas_shora where kar_shora_email='$admin'";
$re=mysql_query($q) or die("Error");
$rff=mysql_fetch_array($re);
$cod_daneshgah=$rff['cod_daneshgah'];
$cod_daneshkade=$rff['cod_daneshkade'];
$cod_karshenas=$rff['cod_karshenas'];
$cod_daneshkade_second=$rff['cod_daneshkade_second'];
$cod_daneshkade_third=$rff['cod_daneshkade_third'];
$cod_daneshkade_4=$rff['cod_daneshkade_4'];
$cod_daneshkade_5=$rff['cod_daneshkade_5'];
$cod_daneshkade_6=$rff['cod_daneshkade_6'];
$cod_daneshkade_7=$rff['cod_daneshkade_7'];
$cod_daneshkade_8=$rff['cod_daneshkade_8'];
$cod_daneshkade_9=$rff['cod_daneshkade_9'];
$cod_daneshkade_10=$rff['cod_daneshkade_10'];

if($cod_daneshkade!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_first=$rff2['daneshkade_name'];
if($cod_daneshkade=='0')
$daneshkade_name_first="معاونت پژوهشي";
}
if($cod_daneshkade_second!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_second'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_second=$rff2['daneshkade_name'];
}

if($cod_daneshkade_third!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_third'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_third=$rff2['daneshkade_name'];
}
if($cod_daneshkade_4!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_4'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_4=$rff2['daneshkade_name'];
}

if($cod_daneshkade_5!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_5'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_5=$rff2['daneshkade_name'];
}
if($cod_daneshkade_6!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_6'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_6=$rff2['daneshkade_name'];
}


if($cod_daneshkade_7!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_7'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_7=$rff2['daneshkade_name'];
}

if($cod_daneshkade_8!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_8'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_8=$rff2['daneshkade_name'];
}
if($cod_daneshkade_9!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_9'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_9=$rff2['daneshkade_name'];
}

if($cod_daneshkade_10!='-1'){
$q2="select * from daneshkade where cod_daneshkade='$cod_daneshkade_10'";
$re2=mysql_query($q2) or die("Error");
$rff2=mysql_fetch_array($re2);
$mostaghel=$rff2['mostaghel'];
$daneshkade_name_10=$rff2['daneshkade_name'];
}


if ( ! isset($cod_daneshkade1))
    $cod_daneshkade1 = '-1';

if(strcmp($cod_daneshkade1,'-1')!=0 )
{
	$daneshkade_caution="tarh.cod_daneshkade = '$cod_daneshkade1'";
}
else
   $daneshkade_caution=1;
   

if(isset($action))
 if(strcmp($action,"send_matrah_list")==0)
 {
   
   for($j=1;$j<30;$j++)
   {
   
    $cod='checktarh'.$j;
    if(isset($$cod))
    {
     $cod_tarh=$$cod;
     $query="update tarh set send_karshenas_shora='0' where cod_tarh='$cod_tarh' ";
     $result=mysql_query($query) or die("Error");     
//	 echo "mohsen".$$cod."<br>";
    }

   }
//exit(); 
 }    

if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
 
if ( ! isset($tarh_year))
    $tarh_year = '-1';


if(strcmp($tarh_year,'-1')!=0 )
{
    $year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
    
/* 
if(strcmp($admin,"rezaii@tums.ac.ir")==0)
  $refered_shora=" tarh.refered_shora ='0' ";
else
  $refered_shora="1";
  */ 
 
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
     
   $refered_shora="1";
   
     $query="update   tarh  set dastoor_shora='-1' where  refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and   $year_caution  and $daneshkade_caution   and confirm_moaven_tarh='1'  and tarh.version='-1' and  $refered_shora  " ;
    // echo $query;
	 $result34=mysql_query($query) or die ("Error"); 
	 
	// echo $cod_daneshgah;
	 
	 if($cod_daneshgah!='-1'){
	 	$daneshgah_cousion="and tarh.daneshgah='$cod_daneshgah'";
	 }
	 else 
	 	$daneshgah_cousion="and 1"	;
	 	
	 if ( ! isset($cod_daneshkade_ozviat))
    		$cod_daneshkade_ozviat = '-1';
	 	
	 	if(strcmp($cod_daneshkade_ozviat,'-1')!=0){
	 		$cod_daneshkade_ozviat_sql="tarh.cod_daneshkade='$cod_daneshkade_ozviat'";
	 	}
	 	else {
	 		$cod_daneshkade_ozviat_sql="tarh.cod_daneshkade='$cod_daneshkade_ozviat'";
	 	}
  if(strcmp($cod_daneshkade_ozviat,'0')!=0){
		if(isset($name_e))
		{
		  $query="select * from tarh,karshenas_shora_tarh,karshenas_shora where  $year_caution    and (tarh.cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and karshenas_shora_tarh.cod_karshenas='$cod_karshenas' and tarh.cod_tarh=karshenas_shora_tarh.cod_tarh and $cod_daneshkade_ozviat_sql and tarh.version='-1' and view_karshenas='1' $daneshgah_cousion group by tarh.cod_tarh order by tarh_time desc";
		}
		else
		  $query="select * from tarh,karshenas_shora_tarh,karshenas_shora where   $year_caution   and  karshenas_shora_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=karshenas_shora_tarh.cod_tarh and $cod_daneshkade_ozviat_sql  and tarh.version='-1' and view_karshenas='1' $daneshgah_cousion group by tarh.cod_tarh order by tarh_time desc";
		  	
  }
else{	 
		if(isset($name_e))                     
		{
		     
		  $query="select * from tarh,vaziat_tarh  where  refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and   $year_caution  and $daneshkade_caution  and (tarh.cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and vaziat_tarh.vaziat=tarh.vaziat_moaven   and confirm_moaven_tarh='1'  and tarh.version='-1' and  $refered_shora $daneshgah_cousion group by cod_tarh order by right(cod_tarh,4) asc" ;
		}
		else
		  $query="select * from tarh,vaziat_tarh  where  refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and   $year_caution  and  $daneshkade_caution  and vaziat_tarh.vaziat=tarh.vaziat_moaven  and confirm_moaven_tarh='1'   and tarh.version='-1'  and $refered_shora $daneshgah_cousion group by cod_tarh order by right(cod_tarh,4) asc" ;

}
$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);

if(strcmp($cod_daneshkade_ozviat,'0')!=0){
		if(isset($name_e))
		{
		  $query="select tarh.*,karshenas_shora_tarh.*,karshenas_shora.*,tarh.cod_daneshkade as university from tarh,karshenas_shora_tarh,karshenas_shora where  $year_caution    and (tarh.cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and karshenas_shora_tarh.cod_karshenas='$cod_karshenas' and tarh.cod_tarh=karshenas_shora_tarh.cod_tarh and $cod_daneshkade_ozviat_sql  and tarh.version='-1' and view_karshenas='1' $daneshgah_cousion group by tarh.cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage;;
		}
		else
		  $query="select tarh.*,karshenas_shora_tarh.*,karshenas_shora.*,tarh.cod_daneshkade as university from tarh,karshenas_shora_tarh,karshenas_shora where   $year_caution   and  karshenas_shora_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=karshenas_shora_tarh.cod_tarh and $cod_daneshkade_ozviat_sql  and tarh.version='-1' and view_karshenas='1' $daneshgah_cousion group by tarh.cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage;;
		  	
  }else{
 if(isset($name_e))
{
  $query="select tarh.*,tarh.cod_daneshkade as university  from tarh,vaziat_tarh  where  refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and  $year_caution  and  $daneshkade_caution  and (cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and vaziat_tarh.vaziat=tarh.vaziat_moaven and   confirm_moaven_tarh='1'  and tarh.version='-1'  and $refered_shora $daneshgah_cousion group by cod_tarh order by right(cod_tarh,4) asc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select tarh.*,tarh.cod_daneshkade as university  from tarh,vaziat_tarh  where refered_shora='0' and  send_karshenas_shora='1' and tarh_type!='6' and  $year_caution  and  $daneshkade_caution  and vaziat_tarh.vaziat=tarh.vaziat_moaven and  confirm_moaven_tarh='1' and tarh.version='-1'  and $refered_shora $daneshgah_cousion group by cod_tarh  order by right(cod_tarh,4) asc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage;
 
  }
  //echo $query;
$result=mysql_query($query) or die("Error in selecting data from tarh2");

?>
<table  cellSpacing="0" cellPadding="0" width="50%" bgColor="white" border="0">

 <tr>
<?    


echo "<form name=\"change_ozviat\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc\">";

echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class=\"but-wide\" name=\"cod_daneshkade_ozviat\" onchange=\"JavaScript:document.change_ozviat.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">انتخاب کنيد</option>";
if($cod_daneshkade!='-1'&&$cod_daneshkade!=""){
	if(strcmp($cod_daneshkade,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade."\" class=\"tahoma1\">".$daneshkade_name_first."</option>";
		}
 if($cod_daneshkade_second!='-1'&&$cod_daneshkade_second!=""){
	if(strcmp($cod_daneshkade_second,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_second."\" class=\"tahoma1\">".$daneshkade_name_second."</option>";
		}
 if($cod_daneshkade_third!='-1'&&$cod_daneshkade_third!=""){
	if(strcmp($cod_daneshkade_third,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_third."\" class=\"tahoma1\">".$daneshkade_name_third."</option>";
		}
 if($cod_daneshkade_4!='-1'&&$cod_daneshkade_4!=""){
	if(strcmp($cod_daneshkade_4,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_4."\" class=\"tahoma1\">"."$daneshkade_name_4"."</option>";
		}
  if($cod_daneshkade_5!='-1'&&$cod_daneshkade_5!=""){
	if(strcmp($cod_daneshkade_5,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_5."\" class=\"tahoma1\">".$daneshkade_name_5."</option>";
		}
  if($cod_daneshkade_6!='-1'&&$cod_daneshkade_6!=""){
	if(strcmp($cod_daneshkade_6,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_6."\" class=\"tahoma1\">".$daneshkade_name_6."</option>";
		}
  if($cod_daneshkade_7!='-1'&&$cod_daneshkade_7!=""){
	if(strcmp($cod_daneshkade_7,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_7."\" class=\"tahoma1\">".$daneshkade_name_7."</option>";
		}
  if($cod_daneshkade_8!='-1'&&$cod_daneshkade_8!=""){
	if(strcmp($cod_daneshkade_8,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_8."\" class=\"tahoma1\">".$daneshkade_name_8."</option>";
		}
  if($cod_daneshkade_9!='-1'&&$cod_daneshkade_9!=""){
	if(strcmp($cod_daneshkade_9,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_9."\" class=\"tahoma1\">".$daneshkade_name_9."</option>";
		}
 if($cod_daneshkade_10!='-1'&&$cod_daneshkade_10!=""){
	if(strcmp($cod_daneshkade_10,$cod_daneshkade_ozviat)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$cod_daneshkade_10."\" class=\"tahoma1\">".$daneshkade_name_10."</option>";
		}
		?>
		</select>   طرح هاي دانشکده / مرکز که شما عضو شورا آن هستيد 
		</td>
		<?
echo "</form>";
?></tr>
</table>
<?
  if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="left" class="tahoma1" width="60%"><a <? echo "href=\"print_list_tarh.phtml?admin=$admin&seed=$seed\""; ?> target="_blank"><img alt="Print List" src="image/print.gif" border="0"> </a></td>
 </tr>
 <tr>
 <td align="left" class="tahoma1" width="60%"><a <? echo "href=\"pure_tarh_list.phtml?admin=$admin&seed=$seed\""; ?> target="_blank">ليست کلي</a></td>
 </tr>
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرح هاي قابل طرح<b></td>
 </tr>
 <tr>
 <td  align="center" class="tahoma1">
     رنگ سبز به معني گرانت است
 </td> 
 </tr>
 </table> 
<?
?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">

 <tr>
<?    


echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&cod_daneshkade_ozviat=$cod_daneshkade_ozviat\">";

$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" class=\"but-wide\" name=\"cod_daneshkade1\" onchange=\"JavaScript:document.change_daneshkade.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade1)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
 
?>

</select> دانشکده / مرکز 
</td>

<?
echo "</form>";




 echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&cod_daneshkade_ozviat=$cod_daneshkade_ozviat\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" >";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
  
  
<?

 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&cod_daneshkade_ozviat=$cod_daneshkade_ozviat\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20"  class=\"but-small\"  dir=RTL   >
 </td>
 
 </tr>


 </form>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 echo "<form name=\"sabt_matrah_shode\" method=\"post\"  action=\"$PHP_SELF?action=send_matrah_list&admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year\">";
$myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&ascdescfield=$ascdescfield&ascdesc=$ascdesc&cod_daneshkade_ozviat=$cod_daneshkade_ozviat&cod_daneshkade1=$cod_daneshkade1";	
if(isset($name_e))
  $myascdescpub=$myascdescpub."&name_e=$name_e";
if(isset($tarh_year))
  $myascdescpub=$myascdescpub."&tarh_year=$tarh_year";  
 pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#8099B7");
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
  <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
   
<?
if(strcmp($admin,"rezaii@sina.tums.ac.ir")==0)
{
?>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black"><input type="checkbox" name="checkall" onClick="checkUncheckAll(this);">بازگشت به طرح هاي پذيرش شده</font></td> 

   <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به طرحهاي مطرح شده</font></td> 
      
    
<?
}
?>
 <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر ساير اعضاي شورا</font></td>
   
 <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظرات شما</font></td>  
 <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">هزينه هاي طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده / مرکز</font></td>
    <td width="7%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اصلي</font></td>
    
     <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
      
    <td width="35%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
  </tr>
  <?


 $color=$list_color_1;
$cntr=($current-1)*$RecPerPage+1;
$i=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
  
  $tarh_type_color=$row_fetched["tarh_type"];
  $ttype_2=$row_fetched["tarh_type_2"];
  $color_line="black";
  if($tarh_type_color==6)
    $color_line="red";
  else
  {  
    $tarh_type_q="select * from tarhtype_2 where tarh_type='$ttype_2' and (tarh_type_desc like \"%گرانت%\" or  tarh_type_desc like \"%گرنت%\")";
  //echo $tarh_type_q;
    $tarh_type_r=mysql_query($tarh_type_q) or die("error");
    if(mysql_num_rows($tarh_type_r)>0)
    {
    	 $color_line="green";
    }
  }
  
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
     {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }



   $string1="";	   	 
   if(isset($tarh_year))
   {
   	 $string1=$string1."&tarh_year=$tarh_year";
   }

   if(isset($cod_daneshkade))
   {
   	 $string1=$string1."&cod_daneshkade=$cod_daneshkade";
   }	   

  
 $mytarh_type = $row_fetched["status"];
 $cod_daneshkade=$row_fetched["university"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
  
  
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To Karshenas\" ></a></td>";
 if(strcmp($admin,"rezaii@sina.tums.ac.ir")==0)
{
 // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">ارسال</td>";  
echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type='checkbox' name=checktarh".$i." value='$cod_tarh' ></td>";
  $i++;
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\" alt=\"Your Notes\" ></a></td>";
 
}


  $query100="select * from karshenas_shora where kar_shora_email='$admin'";
   //echo $
  
  $result100=mysql_query($query100) or die ("Error in selecting data 1111");
   
  $row_fetched100=mysql_fetch_array($result100);
  $karshenas_id=$row_fetched100["cod_karshenas"];
  
  $myq1="select * from karshenas_shora_tarh where cod_tarh='$cod_tarh' and cod_karshenas='$karshenas_id'";
  //echo $myq1;
  $rs1=mysql_query($myq1) or die("error");

  if(mysql_num_rows($rs1)>0)
  {
  	$rf1=mysql_fetch_array($rs1);
  	$mynotes=$rf1["notes"];
   	if(strlen(trim($mynotes)) > 0)
  	  $nazar="<br>(نظردهي شده)<br>";
  	else
	  $nazar="";  
  }
  else
     $nazar="";  
     
      $query="select * from  karshenas_shora_tarh where cod_tarh=\"$cod_tarh\" and CHAR_LENGTH(notes)> 0 ";

   $result_d=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result_d) > 0)   
   	 $darad_nadarad='نظر دارد'."<br>";
   else	 
  	 $darad_nadarad='نظر ندارد'."<br>"; 
  
	   	 
     echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"karshenasan_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >$darad_nadarad<img border=\"0\" src=\"image/notes.gif\" alt=\"Karshenasan Notes\" ></a>";
   
  	 
//  echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\">";	 
  $query="select * from  karshenas_shora_tarh where cod_tarh=\"$cod_tarh\"  and version='-1' ";
//echo $query;
   $result11=mysql_query($query) or die("Error in selecting data from hazine personnel");
  // echo "ss".mysql_num_rows($result11);
   if(mysql_num_rows($result11) > 0)
   {
     echo "<br>";
     echo "<table width=\"98%\" cellPadding=1 border=1 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"100%\" bgcolor=$color colspan=\"2\" align=\"center\" class=\"tahoma1\"><b>نظر کارشناسان</b></td>";
     echo "</tr>";

     echo "<tr>";
     
     echo "<td width=\"80%\"  bgcolor=$color align=\"center\"  class=\"tahoma1\">نظر</td>";
    // echo "<td width=\"20%\" bgcolor=$color  align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
     echo "</tr>";

     $mycount=0;
     while($row_fetched11=mysql_fetch_array($result11))
     {
       echo "<tr>";
 
       echo "<td align=\"right\" valign='top' bgcolor=$color class=\"tahoma1\" dir='rtl'>".$row_fetched11["notes"]."</td>";
      // echo "<td align=\"center\"  bgcolor=$color class=\"tahoma1\">".$row_fetched11["cod_karshenas"]."</td>";
       echo "</tr>";
     }
       
     echo "</table>";

   }
  	 echo "</td>";
  	 
  	 echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='send_your_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&cod_daneshkade_ozviat=$cod_daneshkade_ozviat&current=$current&$string1'>$nazar نظرات شما</a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"center\" class=\"tahoma1\">";
  echo hazineha_detail_view($cod_tarh);
  echo "</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$farsistartdate."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$daneshkade."</a></td>";
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$row_fetched["tarh_title_english"]."</a></td>";
 
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }

  echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'><font color=$color_line>".$First_mojri_name."</font></a></td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a href='tarh_links.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";
  
  $cod_tarh_user=$row_fetched["cod_tarh_user"];


     echo "<td width=\"7%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><font color=$color_line>".$cod_tarh."</font></td>";
 echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><font color=$color_line>".$cntr."</font></td>";
 $cntr++;
  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
 
  echo " <tr>";
echo "    <td width=\"100%\" colspan=\"12\">";
pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#8099B7");
echo "  </tr>";
 echo " <tr>";
echo "    <td width=\"100%\" colspan=\"12\">";
echo "      <p align=\"center\"><input type=\"submit\" value=\"ثبت\" name=\"B1\" class=\"but-small\"></td>";
echo "  </tr>";

echo "</table>";

}
else // if reccount of tarh  < =0
{
 message_show(".طرح قابل مطرح شدن وجود ندارد","red");
}
echo "</form>";
footer_forms($admin,$seed);
?>

