<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";


  $query="select * from tarh where cod_tarh='$cod_tarh' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  
if(isset($action))
{
  if (strcmp($action,"add_hamkar")==0)
  {

     if(strlen(trim($name)) > 0  && strlen(trim($family)) > 0   &&  strlen(trim($email)) > 0  &&  strstr($email, '@') &&  strlen(trim($cod_bank)) > 0)
     {
      $query="select * from hamkaran where  name = \"$name\" and family=\"$family\" and shno=\"$shno\" and  birth_date=\"$birth_date\" ";

      $result=mysql_query($query) or die("Error in selecting data from  hamkaran list 1");
      if ( mysql_num_rows($result) <= 0 )
      {
        $query = "select * from hamkaran";
        $result = mysql_query($query) or die("Error in Selecting data from hamkaran 2");
        if ( mysql_num_rows($result) > 0 )
        {
          $query = "select max(hamkar_code) as max_hamkar from hamkaran";
          $result = mysql_query($query) or die("Error in Selecting data from hamkaran 3");
          $row_fetched = mysql_fetch_array($result);
          $maxnum = intval($row_fetched["max_hamkar"]);
	  $maxnum = $maxnum +1;
        }
        else
         $maxnum=1;
        $query  = "insert into hamkaran set name=\"$name\" , family=\"$family\",  shno = \"$shno\",  birth_date  = \"$birth_date\", work_addr = \"$work_addr\", home_addr = \"$home_addr\", telno = \"$telno\", fax =\"$fax\", melli_code =\"$melli_code\", email =\"$email\", darajeelmi = $degree  , job = \"$job\", hamkar_code = \"$maxnum\"  , cod_bank=\"$cod_bank\" , bank_name=\"$bank_name\" , shoabe=\"$shoabe\" , hesab=\"$hesab\",sex=\"$sex\" ";
        $action="اضافه / ويرايش همکاران طرح"."<br>".$name."&nbsp;&nbsp;".$family;
        set_log($action,$admin,date("Y-d-m"));

        $result = mysql_query($query) or die("Error in inserting data into hamkaran list#1");
        $query = "insert into hamkar_tarh set hamkar_code = \"$maxnum\" , cod_tarh=\"$cod_tarh\",fase_hamkari=\"$fase_hamkari\", hamkary = \"$hamkary\", line=\"$line\" ";
		$result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh#2");
      }
      else
       {
         
         $row_fetched = mysql_fetch_array($result);
         $hamkar_code = $row_fetched["hamkar_code"];
         $query  = "select * from  hamkar_tarh where hamkar_code = \"$hamkar_code\" and cod_tarh=\"$cod_tarh\" ";
         set_log($action,$admin,date("Y-d-m"));

	     if(mysql_num_rows($result) <= 0)
	     {
  	       $query  = "insert into hamkar_tarh set hamkar_code = \"$hamkar_code\" , cod_tarh=\"$cod_tarh\",fase_hamkari =\"$fase_hamkari\", hamkary = \"$hamkary\" , line=\"$line\" ";
           $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");
           $action="اضافه / ويرايش همکاران طرح";
           set_log($action,$admin,date("Y-d-m"));
         }
       }
     }
     else
       $status="entry_error";
  }
   if (strcmp($action,"delete_hamkar")==0)
 {
    $query="delete from hamkar_tarh where  hamkar_code  = \"$delete_id\" and cod_tarh=\"$cod_tarh\"";

    $result=mysql_query($query) or die("Error in  delete data from karshenas_elmi");
 }
}

?>

<? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=add_hamkar&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>


<TABLE cellSpacing=0 cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center width="500" class="tahoma1"  height=19 bgcolor="#EEE7F8">
      <?
	   echo ""."عنوان طرح : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/hamkaran_tarh.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>
  <tr>
    <td width="350" align="right"><input type="text" name="name" size="20" value="" class="edit-user"dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span> نام</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="name_e" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(نام (انگليسي</td>
  </tr>  -->

  <tr>
  <td width="350" align="right"><input type="text" name="family" size="20" value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>
<!--   <tr>
    <td width="350" align="right"><input type="text" name="family_e" value="" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(نام خانوادگي(انگليسي</td>
  </tr>  -->
  <tr>
    <td width="350" align="right"><input type="text" name="shno" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">شماره شناسنامه</td>
  </tr>
  
  <tr>
    <td width="350" align="right">
    <input type="text" name="birth_date" size="20" class="edit-user"  value="فقط سال تولد را  بصورت چهار رقمي وارد کنيد" onfocus="birth_date.value='' "></td>
    <td width="150" class="tahoma1">سال تولد</td>
  </tr>

   <tr>
   <td width="350" align="right"><select size="1" name="sex" class="edit-user" dir="rtl">
      <option value="-1" class="tahoma1">انتخاب کنيد</option>
      <option value="0" class="tahoma1">زن</option>
      <option value="1" class="tahoma1">مرد</option>

    </select></td>
    <td width="150" class="tahoma1">جنسيت</td>
    </tr>
    
  <tr>
    <td width="350" align="right"><input type="text" name="work_addr" size="20" value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">آدرس محل کار</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="work_addr_en" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(آدرس محل کار (انگليسي</td>
  </tr> -->

    <tr>
    <td width="350" align="right"><input type="text" name="home_addr" size="20" value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">آدرس منزل</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="home_addr_en" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(آدرس منزل (انگليسي</td>
  </tr>  -->

   <tr>
    <td width="350" align="right"><input type="text" name="telno" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">تلفن</td>
   </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="fax" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">فاکس</td>
  </tr>

   <tr>
    <td width="350" align="right"><input type="text" name="melli_code" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد ملي</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="email" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
   <tr>
  <?
    $query="select * from darajeelmi order by darajeelmi_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    
  ?>
    <td width="350" align="right"><select size="1" name="degree" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?
    
    while($row_fetched=mysql_fetch_array($qresult))
    {
      echo "<option value=\"".$row_fetched["darajeelmi"]."\" class=\"tahoma1\">".$row_fetched["darajeelmi_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">درجه علمي</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="hamkary" size="20" value="" class="edit-user"  dir=RTL   ></td>
    <td width="150" class="tahoma1">نوع همکاري</td>
  </tr>
<tr>
    <td width="350" align="right"><input type="text" name="fase_hamkari" size="20"  value="" class="edit-user"  dir=RTL   ></td>
    <td width="150" class="tahoma1">فاز همکاري</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="hamkary_e" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نوع همکاري (انگليسي</td>
  </tr>  -->

   <tr>
    <td width="350" align="right"><input type="text" name="job" size="20"  value="" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">شغل</td>
  </tr>

<!--  <tr>
    <td width="350" align="right"><input type="text" name="job_e" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">(شغل (انگليسي</td>
  </tr>  -->
  
  <tr>
    <td width="350" align="right"><input type="text" name="line" size="20" value="" class="edit-user"  dir=RTL   ></td>
    <td width="150" class="tahoma1">لاين تحقيقاتي</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="hesab" size="20"  value="" class="edit-user" ></td>
    <td width="150" class="tahoma1">شماره حساب</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="bank_name" size="20"   value="نام بانک" onfocus="bank_name.value='' " class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">نام بانک</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="shoabe" size="20"   value="شعبه بانک" onfocus="shoabe.value='' " class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">شعبه بانک</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="cod_bank" size="20"   value="کد بانک" onfocus="cod_bank.value='' "  class="edit-user" ></td>
    <td width="150" class="tahoma1">کد بانک</td>
  </tr>
  
<!--  <tr>
    <td width="350" align="right"><input type="text" name="line_e" size="20" value="" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(لاين تحقيقاتي (انگليسي</td>
  </tr>  -->

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>

<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="sabt_tarh_second.phtml?<?echo "admin=$admin&seed=$seed&cod_tarh=$cod_tarh" ?>" >بازگشت</a></td>
  </tr>
</table>


 <?
   $query="select * from hamkaran , hamkar_tarh where hamkaran.hamkar_code = hamkar_tarh.hamkar_code and hamkar_tarh.cod_tarh=\"$cod_tarh\"   order by  family ";

   $result=mysql_query($query) or die("Error in selecting data from hamkaran tarh");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"0\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حذف</p></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ويرايش</p></td>";
    echo "<td width=\"186\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام خانوادگي</p></td>";
    echo "<td width=\"188\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام</p></td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    echo "<tr bgcolor=\"$color\">";
    echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\">&nbsp;</td>";
    //echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" ><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=hamkaran_tarh.phtml&admin=$admin&seed=$seed&action=delete_hamkar&cod_tarh=".$cod_tarh."&delete_id=".$myrow_fetched["hamkar_code"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"47\"><p align=\"center\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"hamkaran_tarh_every_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&hamkar_code=".$myrow_fetched["hamkar_code"]."\">".substr($myrow_fetched["family"],0,18)."</a></p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"hamkaran_tarh_every_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&hamkar_code=".$myrow_fetched["hamkar_code"]."\">".substr($myrow_fetched["name"],0,18)."</a></p></td>";
    echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";
   }
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"186\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"188\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"><p align=\"center\" class=\"tahoma1\">&nbsp;</p></td>";
    echo "</tr>";

   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>




