<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");

echo "<br>";


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;


$query="select * from modir_daneshkade where  modir_username = '$admin'";
$result=mysql_query($query);
$row_fetched=mysql_fetch_array($result);
$cod_daneshkade=$row_fetched["cod_daneshkade"];

$query="select * from letter_to_mojri where cod_daneshkade='$cod_daneshkade'  and id='$letterno'";

$result=mysql_query($query) or die("Error in selecting data from tarh");

 
 if(mysql_num_rows($result) > 0)
 {
   $row_fetched=mysql_fetch_array($result);
   $body_letter=$row_fetched["letter_body"];
   $subject=$row_fetched["letter_subject"];
 ?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="1">
 <tr>
 <td align="center" class="tahoma1" width="60%" bgcolor="cyan"><b>متن نامه با عنوان :<? echo $subject; ?><b></td>
 </tr>
 <tr>

    <td width="10%" >
      <p align="center" class="tahoma1"><font color="black"><? echo $body_letter; ?></font></td>
  </tr>
 </table>
 
<?
}

footer_forms($admin,$seed);


?>
