<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
//header_forms($admin,$seed);
global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type ==2 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
 }
include("include/styles.phtml");
$query="select * from jalase_shora where shomare_jalase ='$shomare_jalase'";
$result_jalase=mysql_query($query);
$row_fetched_result_jalase=mysql_fetch_array($result_jalase);

//$query="select tarh.*,vaziat_tarh.*  from tarh,vaziat_tarh  where jalase_shora.shomare_jalase='$shomare_jalase' and   jalase_shora.shomare_jalase=jalase_shora_karshenas_shora.shomare_jalase and  jalase_shora_karshenas_shora.cod_karshenas=karshenas_shora.cod_karshenas and jalase_shora.creator='$admin' and karshenas_shora.creator='$admin' group by karshenas_shora.cod_karshenas ";
//echo $query;
//$result_karshenasan_shora=mysql_query($query) or die("Error in selecting data from karshenas_shora");
$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];

  $query="select tarh.*,vaziat_tarh.*  from tarh,vaziat_tarh   where   vaziat_tarh.vaziat=tarh.vaziat  and confirm_tarh='1'  and cod_daneshkade='$cod_daneshkade'  and left(tarh.cod_tarh,5)='$tarh_year'  and tarh.send_moavenat ='1' and tarh.rotbe_tarh!='0'  group by tarh.cod_tarh order by tarh_time desc" ;
//$query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,jalase_shora_tarh where jalase_shora_tarh.shomare_jalase='$shomare_jalase' and jalase_shora_tarh.cod_tarh=tarh.cod_tarh and  vaziat_tarh.vaziat=tarh.vaziat and cod_daneshkade='$cod_daneshkade'  group by tarh.cod_tarh  desc" ;
$color=$list_color_1;
 
$result_tarh_jalase_shora=mysql_query($query) or die("Error in selecting data from tarh");


$color=$list_color_1;
 
if(mysql_num_rows($result_karshenasan_shora)>0)
{
 echo "<table border=\"0\"   width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color  colspan=\"2\" class=\"tahoma1\"  align=\"center\"><b>حاضرين در جلسه</b></td>";
    echo "</tr>";
  while($row_fetched=mysql_fetch_array($result_karshenasan_shora))
  {
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
    echo "<td width=\"70%\" bgcolor=$color class=\"tahoma1\" align=\"right\">".$row_fetched["kar_shora_family"]."&nbsp;".$row_fetched["kar_shora_name"]."</td>";
    echo "<td width=\"30%\" bgcolor=$color class=\"tahoma1\"  align=\"left\">:نام و نام خانوادگي</td>";
    echo "</tr>";
  }
  echo "</table>";
}
$color=$list_color_1;
 
if(mysql_num_rows($result_tarh_jalase_shora)>0)
{
 echo "<table border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color colspan=\"6\" class=\"tahoma1\"  align=\"center\"><b>صورت جلسه رتبه بند? طرحها</b></td>";
    echo "</tr>";
  	echo "<tr>";    
   // echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بند آزاد</td>";
//	echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بودجه مصوب</td>";
    echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">رتبه طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">وضعيت طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">عنوان طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">کد طرح</td>";
    echo "</tr>";
  
  $color=$list_color_1;
 
  while($row_fetched=mysql_fetch_array($result_tarh_jalase_shora))
  {
  	$cod_tarh=$row_fetched["cod_tarh"];
  	$query="select * from jalase_shora_tarh  where cod_tarh='$cod_tarh' and shomare_jalase='$shomare_jalase'";
  	
  	$res=mysql_query($query)or die("tttt");
  	$row_fetched_budje=mysql_fetch_array($res);
  	
  	
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
  // echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched_budje["band_azad"]."</td>";
//	echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched_budje["budjeh"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["rotbe_tarh"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["vaziat_desc"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\" align=\"right\" dir=\"rtl\">".$row_fetched["tarh_title_farsi"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["cod_tarh"]."</td>";
    echo "</tr>";
  }
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  
  echo "<tr>";    
   // echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بند آزاد</td>";
//	echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بودجه مصوب</td>";
  //  echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">رتبه طرح</td>";
    echo "<td   height='80'  colspan='2'  class=\"tahoma1\"  align=\"center\">امضاء کارشناس مربوطه</td>";
    echo "<td    height='80'  colspan='2' class=\"tahoma1\"  align=\"center\">امضاء معاونت پژوهشي م-ت/د</td>";
    
    echo "</tr>";
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  
 
  echo "</table>";
}


///footer_forms($admin,$seed);
?>