<?
include("include/database-connect.phtml");
include("include/include.phtml");

header_forms($admin,$seed);
include("include/styles.phtml");


if (strcmp($action,"sabt")==0)
{
  
     for($i=0;$i<=$RecPerPage;$i++)
     {
       $cod_tarh_address="check".$i;
       $comment="comment".$i;
       if(isset($$cod_tarh_address))
       {
       	$cod_tarh=$$cod_tarh_address;
       	$comment=$$comment;
       	 $now_date=date("Y-m-d");
		$query="update tarh  set  is_tarh=\"1\"   where  cod_tarh='$cod_tarh'";	    
        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
        //echo $query;
        $query="delete from return_daneshkade where cod_tarh='$cod_tarh'";	    
        $result=mysql_query($query) or die("Error 600");
       // echo $query;   
        
         insert_position($cod_tarh,"26",$admin);
        $action="ارسال پايان نامه به  معاونت"."<br>".$tarh_name;
        $query="select * from tarh_send_moavenat where cod_tarh='$cod_tarh'";
       // echo $query;
		$result2=mysql_query($query) or die("Error in selecting data from tarh_send_moavenat");
          // echo $query;
        
        set_log($action,$admin,date("Y-m-d, g:i a"));
       //	echo $$cod_tarh_address;
       }
     }
}
include("include/vars.inc.phtml");       	
echo "<br>";


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];
$cod_modir=$myrow_fetched["cod_modir"];
$first_part_sql=",modir_daneshkade_tarh";
$second_part_sql=" and tarh.cod_tarh=modir_daneshkade_tarh.cod_tarh and modir_daneshkade_tarh.cod_modir='$cod_modir'";




$grant_hsr_isolation='tarh_type!=6';

$myq="select * from tarhtype_2 where grant_tarh='1'";
$res=mysql_query($myq) or die("Error");
$grant_q="";
/*While($myrf=mysql_fetch_array($res) )
{
	$grant_q=$grant_q." and "."tarh_type_2 != '".$myr["tarh_type"]."'";
}
*/
$grant_hsr_isolation=$grant_hsr_isolation.$grant_q;


  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
    
if(isset($name_e))
{
  $query="select *,tarh.finished as fini from tarh $first_part_sql,user_login where $grant_hsr_isolation and archieved='0'  $second_part_sql and  payannameh='1' and  send_moavenat=\"0\" and user_login.email=tarh.creator and (user_login.name like $myname_search or user_login.family like $myname_search or tarh.cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and  payanname_new_gharardad='0'   and submission_payanname_center_status ='1'  and confirm_payan_name='1' and tarh.cod_daneshkade='$cod_daneshkade' and tarh.version='-1'  group by tarh.cod_tarh order by tarh_time desc";
}
else
  $query="select *,tarh.finished as fini from tarh $first_part_sql where  $grant_hsr_isolation and archieved='0'  $second_part_sql and  payannameh='1' and  send_moavenat=\"0\"  and submission_payanname_center_status ='1' and  payanname_new_gharardad='0' and confirm_payan_name='1' and tarh.cod_daneshkade='$cod_daneshkade' and tarh.version='-1'  group by tarh.cod_tarh order by tarh_time desc";

//echo $query;
$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);

 if(isset($name_e))
{
  $query="select *,tarh.finished as fini from tarh$first_part_sql,user_login   where   $grant_hsr_isolation and archieved='0'  $second_part_sql and payannameh='1' and  send_moavenat=\"0\" and  user_login.email=tarh.creator and (user_login.name like $myname_search or user_login.family like $myname_search or tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and  payanname_new_gharardad='0' and tarh.version='-1'   and submission_payanname_center_status ='1' and confirm_payan_name='1' and tarh.cod_daneshkade='$cod_daneshkade' group by tarh.cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select *,tarh.finished as fini from tarh $first_part_sql  where  $grant_hsr_isolation and archieved='0'  $second_part_sql and payannameh='1' and  send_moavenat=\"0\"   and submission_payanname_center_status ='1' and confirm_payan_name='1' and tarh.cod_daneshkade='$cod_daneshkade' and  payanname_new_gharardad='0' and tarh.version='-1'  group by tarh.cod_tarh order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;



$result=mysql_query($query) or die("Error in selecting data from tarh2");
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
  <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>پايان نامه پس از تصويب</b></td>
 </tr>
 </table>
 
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
 </form>
<?
}
if(mysql_num_rows($result) > 0 )
{
echo "<form name=\"send_moavenat\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&action=sabt&shomare_jalase=$shomare_jalase&current=$current&RecPerPage=$RecPerPage\">";
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc&tarh_type=$tarh_type";
 if(isset($name_e))
 $myascdescpub=$myascdescpub."&name_e=$name_e";	
 pubshowpages("tarh_list_new_after_submit.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%","#66CCFF");
 
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت پايان نامه از نظر ويرايش نزد مجري</font></td>
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">آرشيو پايان نامه</font></td>  
  <!--  -->
      
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي پايان نامه</font></td>  
 
  <!--     <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به معاونت پژوهشي دانشکده<br><input type="checkbox" name="checkall" onClick="checkUncheckAll(this);"></font></td>

   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">موقعيت طرح</font></td> -->
   
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ تصويب</font></td>
  
     <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
      <!--  <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايش هاي پايان نامه</font></td> -->
      <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظريه همه کارشناسان</font></td>      
       
        <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">استاد مشاور اول </font></td>  
      <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">استاد راهنما اول </font></td> 
       
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به در آماده به قرارداد</font></td> 
      
       <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به   قبل از تصويب</font></td> 
       <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مکاتبات</font></td>        
 
	     
     <td width="15%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  <?

 $color=$list_color_1;
 $i=0;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $is_tarh=$row_fetched["is_tarh"];
  // $accepttarh=$row_fetched["accepttarh"];
  if(strcmp($row_fetched["indoing"],"1")==0 || strcmp($row_fetched["fini"],"1")==0 || strcmp($row_fetched["ready_gharardad"],"1")==0 )
       $user_editable="غير قابل ويرايش";
    else
       $user_editable="قابل ويرايش";
  
  
 if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
   echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line> $user_editable</font></td>";
   echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"archieve.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/archive.jpg\" alt=\"archive\" ></a></td>";
 
   echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ويرايشها</a></td>";
 /* if(strcmp($is_tarh,'0')==0)
  {
     echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"check".$i."\"  value=\"$cod_tarh\"></td>";
   //   echo "<td width=\"20%\" bgcolor=$color align=\"center\" valign='top' class=\"tahoma1\"><textarea  cols='12'  rows=\"4\"  name=\"comment".$i."\"  dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\"></textarea></td>";


  }
  else
  {
     echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">---</td>";
	 
 	 
	 
// echo "<td width=\"20%\" bgcolor=$color align=\"center\" valign='top' class=\"tahoma1\">----</td>";
  }
  */
  
  
   $position_tarh_code=current_position($cod_tarh);	
 $time_tasvib=$row_fetched["payannameh_submission_date"];
 

  $first_ostad = $row_fetched["first_ostad"];
    if(strcmp($first_ostad,"")!=0){
	    $myq1="select * from user_login where email='$first_ostad'";
		$ostad_res1=mysql_query($myq1) or die("Error in selecting daneshkade");
		$row_fetched_ostad1 = mysql_fetch_array($ostad_res1);
		$ostad_name_rahnama=$row_fetched_ostad1["name"]."&nbsp".$row_fetched_ostad1["family"];
     }
     else 
    	$ostad_name_rahnama="---";

	
    $first_ostad_moshaver = $row_fetched["first_ostad_moshaver"];
    if(strcmp($first_ostad_moshaver,"")!=0){
		$myq="select * from user_login where email='$first_ostad_moshaver'";
		$ostad_res=mysql_query($myq) or die("Error in selecting daneshkade");
		$row_fetched_ostad = mysql_fetch_array($ostad_res);
		$ostad_name_moshaver=$row_fetched_ostad["name"]."&nbsp".$row_fetched_ostad["family"]; 
	      }
    else 
    	$ostad_name_moshaver="---";
	
  //echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$position_tarh[$position_tarh_code]."</td>";
  echo "<td bgcolor=$color width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$time_tasvib."</td>";

  
  // echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_moavenat.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Moavenat\" ></a></td>";
  //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></a></td>";
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
   // echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ويرايش ها</a></td>";
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"group_karshenas_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\"  alt=\"Notes\" ></a></td>";
 
  //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["rotbe_tarh"]."</td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target = \"_blank\" href=\"shenasname_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/shenasname_tarh.gif\" width=\"11\" height=\"13\" alt=\"Shenasname tarh\" ></a></td>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";

  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$ostad_name_moshaver</td>";
   echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$ostad_name_rahnama</td>";
  $i++;
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  //send_moavenat='0' 
  
   if($row_fetched["status"]=="0")
      {
       if($row_fetched["confirm_tarh"]=="1")
  	     $mystatus="در دست بررسي";
    	else   
         $mystatus="نامعلوم";
      } 
     else
      {
        $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
        $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
        $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
        $mystatus=$row_fetched_tarh["vaziat_desc"];
        if($row_fetched_tarh["view_or_no"]=="1")
           $editable=0;
        else
           $editable=1;
      }
  
  if($row_fetched["send_moavenat"]!="0")
  {
  	$mystatus=$mystatus." /"." ارسال شده به معاونت پژوهشي";
  }
  if($row_fetched["confirm_moaven_tarh"]!="0")
  {
  	$mystatus=$mystatus." /"." در دست بررسي در معاونت پژوهشي";
  }

  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration : none\" href=\"change_status.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mystatus."</a></td>";
  //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_moavenat.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/send_daneshkade.gif\" alt=\"Send Moavenat\" ></a></td>";
  
  
      echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_new_gharardad.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ارسال</a></td>";

   echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_tarh_before_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">ارسال</a></td>";
   
  
 // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration : none\" href=\"change_status_after_submit.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">".$mystatus."</a></td>";
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
 // echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"change_year_rank.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Change Rank\" ></a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $farsistartdate."</a></td>";
  
 // $myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh' ORDER  BY mojri.mojri_code";
  //$myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");

  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
    $First_mojri_name = "اطلاعات موجود نيست";
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["cod_tarh"]."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
  echo "<tr>";
  echo "<td width=\"100%\" colspan='12'  align=\"center\" class=\"tahoma1\"><input type=\"submit\" value=\"ثبت\" name=\"B1\" class=\"but-small\"></td>";
  echo "</tr>";
  
echo "</table>";
echo "</form>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ موردي يافت نشد","red");
}

footer_forms($admin,$seed);


?>

