<?
include("include/database-connect.phtml");
include("include/include.phtml");
global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  
  if( $type == 3 )
    updatesession($username,$rand);
  else
  {
   header ("Refresh: 0; url=index.phtml");
   exit();
  }
 }
 
include("include/styles.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
 
echo "<META http-equiv=content-type content=text/html;charset=utf-8>";
//header_forms($admin,$seed);
echo "<br>";


if( isset($action) )
 if ( strlen(trim($notes)) > 0 )
 {
   $query="select * from group_karshenasan where username='$admin'";
   $result=mysql_query($query) or die ("Error in selecting data");
   $row_fetched=mysql_fetch_array($result);
   $karshenas_id=$row_fetched["cod_karshenas"];

   $notes=str_replace("'","",$notes);
   $notes=str_replace("\"","",$notes);
   $notes=str_replace(";","",$notes);
	 
   $query="select max(version) as maxver from karshenasan_tarh where cod_tarh='$cod_tarh'";

   $result=mysql_query($query) or die("Error in selecting data from 1");

   $rf1=mysql_fetch_array($result);
   $maxver=$rf1["maxver"];
   if($maxver=='-1')
      $maxver='1';
   else
      $maxver=$maxver+1;
      
      
     $query="update group_karshenasan_tarh set note_date='".date("Y-m-d")."',comment_karshenas='$notes',version='$maxver' where   cod_karshenas='$karshenas_id' and  cod_tarh='$cod_tarh'   ";
    
	 $result=mysql_query($query) or die ("Error in updating data into user login 1");
   
    // $query="update group_karshenasan_tarh set   gant='$gant',variables='$variables',note_submitted='1',chekide='$chekide',sabt='$sabt',mojrian='$mojrian',daneshjoyan='$daneshjoyan',raveshejra='$raveshejra',hazineha='$hazineha',akhlaghi='$akhlaghi',zamaem='$zamaem',comment_karshenas='$notes' , refered='$refered' where cod_tarh='$cod_tarh' and cod_karshenas='$karshenas_id'  ";

      $query="insert into group_karshenasan_tarh_note set tarh_new='0'  , note_date='".date("Y-m-d")."',version='-1', gant='$gant',variables='$variables',note_submitted='1',chekide='$chekide',sabt='$sabt',mojrian='$mojrian',daneshjoyan='$daneshjoyan',raveshejra='$raveshejra',hazineha='$hazineha',akhlaghi='$akhlaghi',zamaem='$zamaem',comment_karshenas='$notes' , cod_tarh='$cod_tarh' , cod_karshenas='$karshenas_id'  ";  
 
   $result=mysql_query($query) or die ("Error in updating data into user login 2");
   
 //  message_show(".نظريه شما ارسال شد","green");
  
  // $action="تغيير کلمه عبور";
  // set_log($action,$admin,date("Y-d-m"));

   
 }
 else
   $status="entry_error";




    $notes="";
    $chekide='0';
  	$sabt='0';
  	$mojrian='0';
  	$daneshjoyan='0';
  	$raveshejra='0';
  	$hazineha='0';
  	$akhlaghi='0';
  	$zamaem='0';
  	$gant='0';
  	$variables='0';
 


?>
  
<script language="javascript" src="js/farsi.js"></script>
<?
$query="select * from tarh where cod_tarh='$cod_tarh' and version='-1'";

$result1=mysql_query($query) or die("Error in selecting data from tarh");
$row_fetched1=mysql_fetch_array($result1);
$comment_karshenas_shora=$row_fetched1["comment_karshenas_shora"];
$dastoor_shora=$row_fetched1["dastoor_shora"];

?>
<br>
<center>
<TABLE cellSpacing=0  width="490" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD dir="rtl" align=center  class="tahoma1"  height=19  dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$row_fetched1["tarh_title_farsi"];
      ?>
      </TD>
  </TR>

</table>
</center>
  
<?

$query="select * from group_karshenasan_tarh where cod_tarh='$cod_tarh'" ;
$query="select * from group_karshenasan,group_karshenasan_tarh where cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas ";
$color=$list_color_1;						  

$result=mysql_query($query) or die("Error in selecting data from group_karshenasan_tarh");


 
  
  $query1="select * from  shora_pajohesh_daneshgah  where  cod_tarh='$cod_tarh'   ";
     $result12=mysql_query($query1) or die ("Error in updating data into user login 1455");
  
  //footer_forms($admin,$seed);
?>
<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>

     <td width="25%" bgcolor="#66CCFF" colspan='12'>
      <p align="center" class="tahoma1"><font color="black">نظرات قبلي شورا</font></td>
      
      </tr>
      
      
      
      
      
    <tr>
 
    <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نظريه کارشناس شورا</font></td>
   <td width="10%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">دستور شورا</font></td>
    
    <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">کد جلسه</font></td>
        <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
   
    <td width="25%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>  
      
  <?
   $color="#DADADA";
 $color="PALETURQUOISE";
 while($row_fetched12=mysql_fetch_array($result12))
 {
   
  $dastoor_shora=$row_fetched12["dastoor_shora"];
   if(strcmp(trim($dastoor_shora),"-1")==0)
    $dastoor_shora_desc=" تا کنون مصوبه شورا ندارد ";

  if(strcmp(trim($dastoor_shora),"0")==0)
    $dastoor_shora_desc=" مصوب ";
  
  if(strcmp(trim($dastoor_shora),"1")==0)
    $dastoor_shora_desc=" مصوب مشروط ";
  
  if(strcmp(trim($dastoor_shora),"2")==0)
    $dastoor_shora_desc=" غير مصوب ";
  
  if(strcmp(trim($dastoor_shora),"3")==0)
    $dastoor_shora_desc=" بررسي نشده ";
  
  if(strcmp(trim($dastoor_shora),"4")==0)
    $dastoor_shora_desc=" عودت داده مي شود ";

 
  echo "<tr><td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'> ".$row_fetched12["comment_karshenas_shora"]." </td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'> ".$dastoor_shora_desc." </td>";
  echo "<td width=\"15%\" bgcolor=$color align=\"center\" class=\"tahoma1\"> ".$row_fetched12["cod_jalase"]." </td>";
  echo "<td width=\"15%\" bgcolor=$color align=\"right\" class=\"tahoma1\"> ".$row_fetched12["insertion_date"]." </td>";
 
  echo "<td width=\"15%\" bgcolor=$color align=\"right\" class=\"tahoma1\"> ".$row_fetched12["cod_tarh"]." </td>";
  echo "</tr>";

 }
echo "</table>";
 
  
  ?>    
      
  
      
  <?   


$comment_karshenas_shora=$comment_karshenas_shora.": توضيح شوراي دانشگاه"."<br>";

 if(strcmp($dastoor_shora,"-1")==0)
    $dastoor_shora=" تا کنون مصوبه شورا ندارد ";
 
  if(strcmp($dastoor_shora,"0")==0)
    $dastoor_shora=" مصوب ";
  
  if(strcmp($dastoor_shora,"1")==0)
    $dastoor_shora=" مصوب مشروط ";
  
  if(strcmp($dastoor_shora,"2")==0)
    $dastoor_shora=" غير مصوب ";
  
  if(strcmp($dastoor_shora,"3")==0)
    $dastoor_shora=" بررسي نشده ";
  
  if(strcmp($dastoor_shora,"4")==0)
    $dastoor_shora=" عودت داده مي شود ";

?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
 <tr>
    
    <td width="100%"colspan="5" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر شوراي پژوهشي دانشگاه</font></td>
    
  </tr>
  <tr>
	<td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظريه</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">توضيح </font></td>
    
  </tr>
  <tr>
	<td width="20%" bgcolor=<? echo "$color"; ?> dir="rtl">
      <p align="center" class="tahoma1"><font color="black"><? echo $comment_karshenas_shora ;?></font></td>
    <td width="20%" bgcolor=<? echo "$color"; ?>  dir="rtl">
      <p align="center" class="tahoma1"><font color="black"><?echo $dastoor_shora;?> </font></td>
    
  </tr>
  
  </table>
  
  
  
  
  
<?  
  
$query="select * from karshenas_shora,karshenas_shora_tarh where cod_tarh='$cod_tarh' and karshenas_shora.cod_karshenas=karshenas_shora_tarh.cod_karshenas ";
						  

$result_shora=mysql_query($query) or die("Error in selecting data from group_karshenasan_tarh");



if(mysql_num_rows($result_shora) > 0 )
{
	
 //pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
 <tr>
    
    <td width="100%"colspan="5" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر اعضاي شورا</font></td>
    
  </tr>
  <tr>
    <td width="80%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس</font></td>
      
      
        <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد کارشناس </font></td>
      
        <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف </font></td>  
    
  </tr>
  <?


 $color=$list_color_1;

 $color=$list_color_1;
 $table = array();
 $table[0] = "بدون اشکال";
 $table[1] = "عدم وجود اطلاعات";
 $table[2] = "بايد اصلاح شود";
 $table[3] = "ناقص";
$row_cntr=1;
 while($row_fetched=mysql_fetch_array($result_shora))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
  $note_submitted=$row_fetched["note_submitted"];
   $string="";
 
 
  //if(strcmp($note_submitted,"1")==0) 
    $comment_note=$row_fetched["comment_karshenas"];
 // else
 // 	$comment_note="نظر ايشان ثبت نشده"; 


  $username=$row_fetched["username"];
 
///  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"ltr\">".$string."</td>";
  echo "<td width=\"80%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"rtl\">".nl2br($row_fetched["notes"])."</td>";
  //echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$karshenas_type."</td>";  
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["note_date"]."</td>";
 // echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["kar_shora_family"]."</td>";
//  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["kar_shora_name"]."</td>";
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["cod_karshenas"]."</td>";
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_cntr."</td>";
  $row_cntr++;
  
echo "</tr>";
 }
echo "</table>";
}
 

  
  
  
  
  
  
  
  
  
  
   


if(mysql_num_rows($result) > 0 )
{
	
 //pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
 <tr>
    
    <td width="100%"colspan="8" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر مدير گروه کارشناسي و کارشناسان آن</font></td>
    
  </tr>
  <tr>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نوع کارشناس</font></td>
      
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
	<td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
   <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام </font></td>
     
        <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد کارشناس </font></td>
      
        <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف </font></td>  
    
  </tr>
  <?


 $color=$list_color_1;

 $color=$list_color_1;
 $table = array();
 $table[0] = "بدون اشکال";
 $table[1] = "عدم وجود اطلاعات";
 $table[2] = "بايد اصلاح شود";
 $table[3] = "ناقص";
$row_cntr=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
  $note_submitted=$row_fetched["note_submitted"];
   $string="";
// if(strcmp($note_submitted,"1")==0)
 //{
 	$cnt=$row_fetched["chekide"];
 	$string=$string."  چکيده : ".$table[$cnt];
 	$cnt=$row_fetched["sabt"];
 	$string=$string."<br>"." ثبت : ".$table[$cnt];
 	$cnt=$row_fetched["mojrian"];
 	$string=$string."<br>"." مجريان : ".$table[$cnt];
 	$cnt=$row_fetched["daneshjoyan"];
 	$string=$string."<br>"." دانشجويان : ".$table[$cnt];
 	$cnt=$row_fetched["raveshejra"];
 	$string=$string."<br>"." روش اجرا : ".$table[$cnt];
 	$cnt=$row_fetched["hazineha"];
 	$string=$string."<br>"."  هزينه ها : ".$table[$cnt];
 	$cnt=$row_fetched["akhlaghi"];
 	$string=$string."<br>"." ملاحظات اخلاقي : ".$table[$cnt];
 	$cnt=$row_fetched["gant"];
 	$string=$string."<br>"." جدول زمانبندي : ".$table[$cnt];
 	$cnt=$row_fetched["variables"];
 	$string=$string."<br>"." جدول متغيرها : ".$table[$cnt];
 	$cnt=$row_fetched["zamaem"];
 	$string=$string."<br>"." ضمائم : ".$table[$cnt];
// }
 //else
 //  $string="نظر ايشان ثبت نشده";
 
 
  //if(strcmp($note_submitted,"1")==0) 
    $comment_note=$row_fetched["comment_karshenas"];
 // else
 // 	$comment_note="نظر ايشان ثبت نشده"; 

   
  $username=$row_fetched["username"];
  $myq="select * from group_karshenasan where username='$username'";
  $myres=mysql_query($myq) or die("Error in selecting data from group_karshenasan");
  $myrow_fetched=mysql_fetch_array($myres);
  if(strcmp($myrow_fetched["karshenas_type"],"0")==0)
    $karshenas_type="کارشناس گروه کارشناسي";
    
    $cod_11=$row_fetched["cod_karshenas"];
  $qq="select * from group_karshenasan_tarh where cod_karshenas='$cod_11' and cod_tarh='$cod_tarh' and send_to_karshenas_date<> ''";
 
  $rss=mysql_query($qq) or die("error");
  if(mysql_num_rows($rss) > 0)
  {
    $rf1=mysql_fetch_array($rss);
    $send_date=$rf1["send_to_karshenas_date"];
  }
  else
    $send_date="---";  
///  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"ltr\">".$string."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["comment_karshenas"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$karshenas_type."</td>";  
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$send_date."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["cod_karshenas"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_cntr."</td>";
  $row_cntr++;
  
echo "</tr>";
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 //message_show(".نظر ي وجود ندارد","red");
}
//echo "</form>";

$query="select * from karshenasan_tarh where cod_tarh='$cod_tarh'" ;
 $query="select * from karshenasan,karshenasan_tarh where  cod_tarh='$cod_tarh' and karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas";
						  

$result=mysql_query($query) or die("Error in selecting data from group_karshenasan_tarh");



if(mysql_num_rows($result) > 0 )
{
	
 //pubshowpages("tarh_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
<tr>
    <td width="50%" colspan="12" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس در مورد قسمتهاي طرح</font></td>
  
  </tr>
  <tr>
     <td width="50%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظر کارشناس</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام کاربري</font></td>
        <td width="20%" bgcolor=<? echo "$title_color"; ?>> 
       <p align="center" class="tahoma1"><font color="black">خاتمه نظر دهي</font></td>
 <!--    <td width="20%" bgcolor=<? echo "$title_color"; ?>> 
       <p align="center" class="tahoma1"><font color="black">تاريخ نظر دهي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>> 
       <p align="center" class="tahoma1"><font color="black">تاريخ دريافت</font></td> -->
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
	<td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نام </font></td>
     
     
     <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد کارشناس</font></td>
       <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">رديف </font></td>
  </tr>
  <?


 $color=$list_color_1;
 $table = array();
 $table[0] = "بدون اشکال";
 $table[1] = "عدم وجود اطلاعات";
 $table[2] = "بايد اصلاح شود";
 $table[3] = "ناقص";
$row_cntr=1;
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $id=$row_fetched["id"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
 
 
 $string="";
 $note_submitted=$row_fetched["refered"];
// if(strcmp($note_submitted,"1")==0)
// {
 	$cnt=$row_fetched["chekide"];
 	$string=$string."  چکيده : ".$table[$cnt];
 	$cnt=$row_fetched["sabt"];
 	$string=$string."<br>"." ثبت : ".$table[$cnt];
 	$cnt=$row_fetched["mojrian"];
 	$string=$string."<br>"." مجريان : ".$table[$cnt];
 	$cnt=$row_fetched["daneshjoyan"];
 	$string=$string."<br>"." دانشجويان : ".$table[$cnt];
 	$cnt=$row_fetched["raveshejra"];
 	$string=$string."<br>"." روش اجرا : ".$table[$cnt];
 	$cnt=$row_fetched["hazineha"];
 	$string=$string."<br>"."  هزينه ها : ".$table[$cnt];
 	$cnt=$row_fetched["akhlaghi"];
 	$string=$string."<br>"." ملاحظات اخلاقي : ".$table[$cnt];
 	$cnt=$row_fetched["gant"];
 	$string=$string."<br>"." جدول زمانبندي : ".$table[$cnt];
 	$cnt=$row_fetched["variables"];
 	$string=$string."<br>"." جدول متغيرها : ".$table[$cnt];
 	$cnt=$row_fetched["zamaem"];
 	$string=$string."<br>"." ضمائم : ".$table[$cnt];
// }
// else
//   $string="نظر ايشان ثبت نشده";
  $receive_karshenas_date =$row_fetched["receive_karshenas_date"];
    $send_karshenas_date=$row_fetched["send_to_karshenas_date"];
    $finish_karshenasi= $row_fetched["finish_karshenasi"];
    $date_send=$row_fetched["date_send"];
 
  //if(strcmp($note_submitted,"1")==0) 
    $comment_note=$row_fetched["comment_karshenas"];
 // else
  //	$comment_note="نظر ايشان ثبت نشده"; 
$send_date=$row_fetched["note_date"];

/* if(strlen($row_fetched["note_date"]) > 0)
  {
  	$int_val=rand(1,7);
  	
  	$int_val=-$int_val;
  	$ddate=$row_fetched["note_date"];
  	$send_karshenas_date=dateAdd("d","$int_val","$ddate");
  }
  else
   $send_karshenas_date="---";
   */
 // echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"ltr\">".$string."</td>";
  
    
  $karshenas_type=$row_fetched["karshenas_type"];
  if($karshenas_type==8)  
    echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"rtl\"> &nbsp;&nbsp;".$comment_note." </td>";
  else
    echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"rtl\">".$comment_note."</td>";  
  echo "<td width=\"10%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\">".$row_fetched["username"]."</td>";
  // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["note_date"]."</td>";
   //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$send_karshenas_date."</td>";
 echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$finish_karshenasi."</td>"; 
 //  echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$date_send."</td>";
  // echo "<td width=\"50%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$receive_karshenas_date."</td>";
   echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$send_date."</td>";

  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["cod_karshenas"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_cntr."</td>";
  $row_cntr++;
  
echo "</tr>";
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
// message_show(".نظر ي وجود ندارد","red");
}
//echo "</form>";

 
?> 
</body>
<br>
<?
footer_forms($admin,$seed);
?>

  