<?php
$domain_name="research.tums.ac.ir";
$url_address="http://research.tums.ac.ir";
$mailserver_host="127.0.0.1";
$email_from="admin@research.tums.ac.ir";
$email_from_name="Admin of Research";
$email_contact_email="niazi@mui.ac.ir";
$email_contact_email1="rezaii@sina.tums.ac.ir";
$email_contact_email2="kabiri@razi.tums.ac.ir";
$email_contact_name="Mohsen Niazi";
$email_contact_name1="Dr Rezaii";
$email_contact_name2="Dr Kabiri";
$email_username="mail_server_admin";
$email_password="pd42ssm";
$smtpauth="false";
?>
