<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/vars.inc.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");
//require_once('lib/nusoap.php');
//echo $action;
  
 if (strcmp($action,"send_karshenas")==0)
  {
  	$q="select * from karshenasan where username='$admin'";
	$res=mysql_query($q) or die("Error  12");
	if(mysql_num_rows($res) > 0)
	{
		$myrf=mysql_fetch_array($res);
		$cod_karshenas=$myrf['cod_karshenas'];
	}
   for($i==0;$i<130;$i++)
   {
   	
    $myvariable="check".$i;
    $myuser="value_".$i;
    if (isset($$myvariable))
    {
   
      $letter_no=$$myuser;
      $view_date=date("Y-m-d");
      $q="insert into karshenasan_letter_view  set cod_karshenas='$cod_karshenas' , letter_no='$letter_no' ,view_date='$view_date' ";
      //echo $q;
      $res=mysql_query($q) or die("Error 5656" );
    }
    
   }
  }


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
       
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
 if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=10000;
      $current=1;
    }
    

echo "<br><br><br>";

if(isset($name_e))
{
 $query="select letter_to_mojri.* from letter_to_mojri,karshenasan_tarh,karshenasan,tarh where tarh.cod_tarh=karshenasan_tarh.cod_tarh and karshenasan_tarh.cod_karshenas=karshenasan.cod_karshenas and  karshenasan.username='$admin' and  karshenasan_tarh.cod_tarh=letter_to_mojri.cod_tarh and letter_to_mojri.from_letter=tarh.creator and ( letter_to_mojri.letter_subject  like $myname_search or letter_to_mojri.letter_body  like $myname_search) group by letter_no order by id desc";
}
else
{
 $query="select letter_to_mojri.* from letter_to_mojri,karshenasan_tarh,karshenasan,tarh where tarh.cod_tarh=karshenasan_tarh.cod_tarh and  karshenasan_tarh.cod_karshenas=karshenasan.cod_karshenas and  karshenasan.username='$admin' and  karshenasan_tarh.cod_tarh=letter_to_mojri.cod_tarh and letter_to_mojri.from_letter=tarh.creator  group by letter_no order by id desc";
}
 //echo $query;
 $result=mysql_query($query) or die("error in selecting data from letter_to_mojri 1");
 
$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);

if(isset($name_e))
{
 $query="select letter_to_mojri.* from letter_to_mojri,karshenasan_tarh,karshenasan,tarh where tarh.cod_tarh=karshenasan_tarh.cod_tarh and  karshenasan_tarh.cod_karshenas=karshenasan.cod_karshenas and  karshenasan.username='$admin' and  karshenasan_tarh.cod_tarh=letter_to_mojri.cod_tarh and letter_to_mojri.from_letter=tarh.creator and ( letter_to_mojri.letter_subject  like $myname_search or letter_to_mojri.letter_body  like $myname_search) group by letter_no order by id desc  "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
{
 $query="select letter_to_mojri.* from letter_to_mojri,karshenasan_tarh,karshenasan,tarh where tarh.cod_tarh=karshenasan_tarh.cod_tarh and  karshenasan_tarh.cod_karshenas=karshenasan.cod_karshenas and  karshenasan.username='$admin' and  karshenasan_tarh.cod_tarh=letter_to_mojri.cod_tarh and letter_to_mojri.from_letter=tarh.creator group by letter_no order by id desc "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
 $result=mysql_query($query) or die("error in selecting data from letter_to_mojri");
 
 
 
   
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed\">";
 
 ?>
 <table border="0" width="600" cellpadding="1" cellspacing="1">
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
 </form>
<?
 echo "<form name=\"sabt_tarh_1\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&action=send_karshenas\">";
 
if(mysql_num_rows($result) > 0 )
{
   $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&name_e=$name_e";
   pubshowpages("your_letter_list.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"600",$title_color);
 
 	echo "<table border=\"1\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\">";
 	echo "<tr>";
	 
 	echo "<td width=\"10%\" colspan='7' align='center' class=\"tahoma1\">نامه هاي جديد</td>";
 	echo "</tr>";
 	
	echo "<tr>";
	echo "<td width=\"5%\" align='center' class=\"tahoma1\">تبديل نامه به خوانده شده</td>";
	echo "<td width=\"5%\" align='center' class=\"tahoma1\">طرح مربوطه</td>";
	echo "<td width=\"5%\" align='center' class=\"tahoma1\">نظر كارشناس</td>";
 	echo "<td width=\"20%\" align='center' class=\"tahoma1\">عنوان نامه</td>";
 	echo "<td width=\"10%\" align='center' class=\"tahoma1\">شماره</td>";
 	echo "<td width=\"10%\" align='center' class=\"tahoma1\">تاريخ</td>";
 	echo "<td width=\"10%\" align='center' class=\"tahoma1\">رديف</td>";
 	echo "</tr>";
 	$i=0;
 	$cntr=0;
 	while($row_fetched=mysql_fetch_array($result))
 	{
 	 $cntr++;
 	$id=$row_fetched["id"];
 	 echo "<tr>";
     $atf_to=$row_fetched["atf_to_letter"];
     $cod_tarh=$row_fetched["cod_tarh"];
	 if(strlen(trim($atf_to)) > 0)	  
	    $letter_type="پاسخ مجري";	  
	  else
	    $letter_type="نامه به مجري";
	  
	 $letterno=$row_fetched["id"];
     $myq="select * from karshenasan_letter_view where letter_no='$letterno'";
     $rs=mysql_query($myq) or die("Error");
     if(mysql_num_rows($rs)<=  0)
      {
      	$start_bold="<b>";
      	$end_bold="</b>";
      }
      else
      {
      	$start_bold="";
      	$end_bold="";
      }
 	 //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=letter_to_mojri_body.phtml&admin=$admin&seed=$seed&action=delete_tarh&cod_tarh=$cod_tarh&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
     echo "<td width=\"5%\"   align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"check".$i."\"  value=\"ON\"></td>";
     echo "<input type=\"hidden\" name=\"value_".$i."\" value=\"".$letterno."\">";
	 echo "<td width=\"5%\" align='center' class=\"tahoma1\" dir=\"rtl\"><a href='view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$start_bold."طرح".$end_bold."</a></td>";
 	 echo "<td width=\"5%\" align='right' class=\"tahoma1\" dir=\"rtl\"><a href='your_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>".$start_bold." نظرات شما ".$end_bold."</a></td>";
 	 echo "<td width=\"20%\" align='right' class=\"tahoma1\"  dir=\"rtl\"><a href='letter_body_show.phtml?admin=$admin&seed=$seed&letterno=$letterno'>$start_bold".$row_fetched["letter_subject"]."$end_bold</a></td>";
 	 echo "<td width=\"10%\" align='right' class=\"tahoma1\"><a href='letter_body_show.phtml?admin=$admin&seed=$seed&letterno=$letterno'>$start_bold".$row_fetched["letter_no"]."$end_Bold</a></td>";
 	 echo "<td width=\"10%\" align='center' class=\"tahoma1\"><a href='letter_body_show.phtml?admin=$admin&seed=$seed&letterno=$letterno'>$start_bold".$row_fetched["letter_date"]."$end_bold</a></td>";
 	 $current_row=$cntr+($current-1)*$RecPerPage;
 	 echo "<td width=\"10%\" align='center' class=\"tahoma1\"><a href='letter_body_show.phtml?admin=$admin&seed=$seed&letterno=$letterno'>$start_bold ".$current_row." $end_bold</a></td>";
 	 echo "</tr>";
 	 $i++;
    } 	
    echo "<tr>";
    echo "<td width=\"100%\" colspan=\"7\">";
    echo "<p align=\"center\"><input type=\"submit\" value=\"ثبت\" name=\"B1\" class=\"but-small\"></td>";
  echo "</tr>";
 	echo "</table><br>";
 	
 }
 else 
 message_show(".نامه جديدي يافت نشد","red");
 ?>
  

<?
   footer_forms($admin,$seed);
?>



