<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");

echo "<br>";

$query="select * from tarh where  tarh.cod_tarh=\"$cod_tarh\" ";

$result = mysql_query($query) or die("Error in selecting data from tarh , mojri_tarh");
if(mysql_num_rows($result) <= 0 )
{
    echo "<table border=\"0\"  height=\"100%\" width=\"400\"    cellspacing=\"0\" cellpadding=\"2\"  >";

    echo "<tr>";
    echo "<td align=\"center\"   width=\"25%\" class=\"error-message\" colspan=\"2\">.چنين طرحي وجود ندارد</td>";
    echo "</tr>";
    
    echo "</table>";
     footer_forms($admin,$seed);
     exit();
    
}

$row_fetched=mysql_fetch_array($result);
$tarh_name=$row_fetched["tarh_title_farsi"];


if(isset($action))
if(strcmp($action,"send_email")==0)
if( strlen(trim($letter_no))> 0 && strlen(trim($cod_tarh))>0 && strlen(trim($letter_subject))>0)
{
	$mydate=date("Y-m-d");
	$to_letter=$row_fetched["creator"];
	$query="select * from modir_daneshkade where  modir_username = '$admin'";
	$result=mysql_query($query);
	$row_fetched=mysql_fetch_array($result);
	$cod_daneshkade=$row_fetched["cod_daneshkade"];
	
	
    $query="insert into letter_to_mojri set from_letter='$admin',to_letter='$to_letter',cod_daneshkade='$cod_daneshkade',cod_tarh='$cod_tarh' , letter_no='$letter_no' , letter_subject='$letter_subject' , letter_body='$letter_body' , letter_date='$mydate'";
    
    $result=mysql_query($query) or die("error in inserting data");
  	
}
else
  $status="entry_error";

if(isset($action))
 if(strcmp($action,"del")==0)
 {
 	$query="delete from letter_to_mojri where id='$delete_id' ";
 	
 	$result=mysql_query($query) or die("Error in deleting from letter_to_mojri");
 }


?>




<? echo "<form name=\"add-tarh\" method=\"post\"  action=\"letter_to_mojri_body.phtml?action=send_email&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="400" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/letter_to_mojri.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="400" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"entry_error_1")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">روي اين شورا کارشناس تعريف شده و قابل حذف نيست</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  
  

?>
           <tr>
              <td colspan="2" align="left">
                <p align="center" class="tahoma1" dir="rtl"><? echo " نامه به طرح با عنوان: ".$tarh_name;?></td>
            </tr>
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="letter_no" size="48" class="edit-user" ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>شماره نامه</td>
            </tr>
 <!-- <tr>
    <td width="70%" align="right">
    
    	   <select size="1" dir="rtl"  name="mojavezyear" class="combo-date">
          <option selected value="-1">سال</option>
          <option value="1381">1381</option>
          <option value="1382">1382</option>
          <option value="1383">1383</option>
          <option value="1384">1384</option>
          <option value="1385">1385</option>
	  	  <option value="1386">1386</option>
	      <option value="1387">1387</option>
	      <option value="1388">1388</option>
	      <option value="1389">1389</option>
	      <option value="1390">1390</option>

        </select>
             <select size="1" dir="rtl"  name="mojavezmon"  class="combo-date">
         <option selected value="-1">ماه</option>
          <option value="01">فروردين</option>
          <option value="02">ارديبهشت</option>
          <option value="03">خرداد</option>
          <option value="04">تير</option>
          <option value="05">مرداد</option>
          <option value="06">شهريور</option>
          <option value="07">مهر</option>
          <option value="08">آبان</option>
          <option value="09">آذر</option>
          <option value="10">دي</option>
          <option value="11">بهمن</option>
          <option value="12">اسفند</option>
        </select>

        <select size="1" dir="rtl"  name="mojavezday"  class="combo-date">
          <option selected value="-1">روز</option>
          <option value="01">1</option>
          <option value="02">2</option>
          <option value="03">3</option>
          <option value="04">4</option>
          <option value="05">5</option>
          <option value="06">6</option>
          <option value="07">7</option>
          <option value="08">8</option>
          <option value="09">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
		  <option value="22">22</option>
		  <option value="23">23</option>
		  <option value="24">24</option>
		  <option value="25">25</option>
		  <option value="26">26</option>
		  <option value="27">27</option>
		  <option value="28">28</option>
		  <option value="29">29</option>
		  <option value="30">30</option>
		  <option value="31">31</option>
        </select>
 
    </td>
    <td width="30%" class="tahoma1">تاريخ </td>
  </tr>
-->
  <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="letter_subject" size="48" class="edit-user"  dir=RTL   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>موضوع</td>
            </tr>
 <tr>
    <td width="250" align="right"><textarea   rows="7"  name="letter_body"  class="edit-user"  dir=RTL   ></textarea></td>
    <td width="150" class="tahoma1" valign="top">متن نامه</td>
  </tr>
             
            
            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="ارسال" name="submit_tarh"></td>
            </tr>
          </table>
          
</form>
       <br>   
 <?
 $query="select * from letter_to_mojri where cod_tarh='$cod_tarh'";
 
 $result=mysql_query($query) or die("error in selecting data from letter_to_mojri");
 if(mysql_num_rows($result) > 0)
 {
 	echo "<table border=\"1\" width=\"400\" cellpadding=\"0\" cellspacing=\"0\">";
 	
	echo "<tr>";
	echo "<td width=\"5%\" align='center' class=\"tahoma1\">حذف</td>";
	//echo "<td width=\"50%\" align='center' class=\"tahoma1\">متن نامه</td>";
 	echo "<td width=\"20%\" align='center' class=\"tahoma1\">عنوان نامه</td>";
 	echo "<td width=\"10%\" align='center' class=\"tahoma1\">شماره</td>";
 	echo "<td width=\"20%\" align='center' class=\"tahoma1\">تاريخ</td>";
 	echo "</tr>";
 	
 	while($row_fetched=mysql_fetch_array($result))
 	{
 	$id=$row_fetched["id"];	
 	 echo "<tr>";
 	 echo "<td width=\"3%\"  align=\"center\" class=\"tahoma1\"><a href=\"#\" onclick='window.open(\"delete_or_apply.phtml?mainwindow=letter_to_mojri_body.phtml&admin=$admin&seed=$seed&action=delete_tarh&cod_tarh=$cod_tarh&delete_id=".$row_fetched["id"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
 	// echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
 	// echo "<td width=\"50%\" align='right' class=\"tahoma1\" dir=\"rtl\">".$row_fetched["letter_body"]."</td>";
 	 echo "<td width=\"20%\" align='right' class=\"tahoma1\"  dir=\"rtl\"><a tarhet=\"_blank\" href=\"letter_body_show.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&letterno=$id\">".$row_fetched["letter_subject"]."</a></td>";
 	 echo "<td width=\"10%\" align='right' class=\"tahoma1\"><a href=\"letter_body_show.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&letterno=$id\">".$row_fetched["letter_no"]."</a></td>";
 	 echo "<td width=\"20%\" align='center' class=\"tahoma1\"><a href=\"letter_body_show.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&letterno=$id\">".$row_fetched["letter_date"]."</a></td>";
 	 echo "</tr>";
    } 	
 	echo "</table>";
 	
 }
 ?>
  

<?
   footer_forms($admin,$seed);
?>



