<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/print.phtml");

?>
<META http-equiv=content-type content=text/html;charset=windows-1256>
<?
if(!isset($username))
  $username="";
if(!isset($rand))
  $rand="";


$q="select * from tarh where cod_tarh='$cod_tarh'";
$r=mysql_query($q) or die("<br><br><br><center>Server Error!!</center>");
$row_fetched_tarh = mysql_fetch_array($r);


$query="select * from printset where modir_username = \"$admin\"";
$result = mysql_query($query) or die("Error in selecting data from printset");


if( mysql_num_rows($result) > 0 )
{
  $row_fetched = mysql_fetch_array($result);
  $besme_font_size = $row_fetched["besme_font_size"];
  $besme_font_name = $row_fetched["besme_font_name"];
  $besme = "style=\"font-family: $besme_font_name; font-size: $besme_font_size\"";

    //-----------------------------------------------------

  $titr_asli_font_size = $row_fetched["titr_asli_font_size"];
  $titr_asli_font_name = $row_fetched["titr_asli_font_name"];
  $titr_asli = "style=\"font-family: $titr_asli_font_name; font-size: $titr_asli_font_size\"";

  //-----------------------------------------------------

  $porseshname_font_size = $row_fetched["porseshname_font_size"];
  $porseshname_font_name = $row_fetched["porseshname_font_name"];
  $porseshname = "style=\"font-family: $porseshname_font_name; font-size: $porseshname_font_size\"";

  //-----------------------------------------------------


  $anavin_asli_font_size = $row_fetched["anavin_asli_font_size"];
  $anavin_asli_font_name = $row_fetched["anavin_asli_font_name"];
  $anavin_asli = "style=\"font-family: $anavin_asli_font_name; font-size: $anavin_asli_font_size\"";

  //-----------------------------------------------------

  $anavin_farii_text_font_size = $row_fetched["anavin_farii_text_font_size"];
  $anavin_farii_text_font_name = $row_fetched["anavin_farii_text_font_name"];
  $anavin_farii_text = "style=\"font-family: $anavin_farii_text_font_name; font-size: $anavin_farii_text_font_size\"";

  //-----------------------------------------------------

  $anavin_farii_font_size = $row_fetched["anavin_farii_font_size"];
  $anavin_farii_font_name = $row_fetched["anavin_farii_font_name"];
  $anavin_farii = "style=\"font-family: $anavin_farii_font_name; font-size: $anavin_farii_font_size\"";

 //-----------------------------------------------------
 
  $titr_anavin_farii_font_size = $row_fetched["titr_anavin_farii_font_size"];
  $titr_anavin_farii_font_name = $row_fetched["titr_anavin_farii_font_name"];
  $titr_anavin_farii = "style=\"font-family: $titr_anavin_farii_font_name; font-size: $titr_anavin_farii_font_size\"";

 //-----------------------------------------------------

  $jadval_title_font_size = $row_fetched["jadval_title_font_size"];
  $jadval_title_font_name = $row_fetched["jadval_title_font_name"];
  $jadval_title = "style=\"font-family: $jadval_title_font_name; font-size: $jadval_title_font_size\"";

  //-----------------------------------------------------
}

 print_title($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_globals($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_mojrian($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_daneshjoyan($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_hamkaran($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 //print_modir_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 //print_modir_mali_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_body_tarh($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_ravesh_ejra($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_jadval_zamani($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 print_page_break();
 print_hazineha($cod_tarh,$besme,$titr_asli,$porseshname,$anavin_asli,$anavin_farii_text,$anavin_farii,$titr_anavin_farii,$jadval_title);
 
?>

 

