<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


if (strcmp($action,"add")==0)
{
  if(strlen(trim($shora_name)) > 0 && strlen(trim($shora_name_english)) > 0)
  {
    $query="select * from shora_pajoheshi where  shora_name=\"$shora_name\"";
    $result=mysql_query($query) or die("Error in query data from shora 4 ");
    if(mysql_num_rows($result) <= 0)
    {
      $query="insert into shora_pajoheshi set  shora_name='$shora_name',shora_name_en='$shora_name_english',creator='$admin'";
      mysql_query($query) or die ("Error in inserting data in shora 5");
    }
     else
      $status="duplicate_entry";
  }
  else
   $status="entry_error";


}


if (strcmp($action,"delete")==0)
{
  if(strlen(trim($delete_id)) > 0 )
  {

    $query1="select * from karshenas_shora where  cod_shora=\"$delete_id\"";

    $result1=mysql_query($query1) or die("Error in query data from karshenas shora 10");

    $query="select * from shora_pajoheshi where  cod_shora=\"$delete_id\"";

    $result=mysql_query($query) or die("Error in query data from karshenas shora 2");
    if(mysql_num_rows($result1) <= 0)
    {
      if(mysql_num_rows($result) > 0)
      {
        $query="delete from shora_pajoheshi where cod_shora='$delete_id'";
        mysql_query($query) or die ("Error in inserting data in karshenas shora 3");
      }
    }
    else
      $status="entry_error_1";
  }
}

?>



<? echo "<form name=\"add-tarh\" method=\"post\"  action=\"$PHP_SELF?action=add&admin=$admin&seed=$seed\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="400" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/add_shora_type.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="400" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"entry_error_1")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">روي اين شورا کارشناس تعريف شده و قابل حذف نيست</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  ?>
    <tr>
      <td width="100%">
        <div align="center">
          <table border="0" width="100%" bgcolor="F0F0FF" height="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="shora_name" size="48" class="edit-tarh-type"  dir=RTL   ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>نام شورا</td>
            </tr>
            <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="shora_name_english" size="48" class="edit-tarh-type" ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>(نام شورا (انگليسي</td>
            </tr>
            <tr>
              <td width="100%" colspan="2" height="32">

                <p align="center"><input class="but-tarh-type" type="submit" value="اضافه" name="submit_tarh"></td>
            </tr>
          </table>
        </div>
      </td>
    </tr>
  </table>
</form>
<br>

<?

if(DBreccount("shora_pajoheshi") > 0)
{
    echo "<table border=\"0\" width=\"400\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"87\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"124\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">اعضاي شورا</td>";
    echo "<td width=\"110\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام شورا</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
  $Query=mysql_query("select * from shora_pajoheshi order by  cod_shora  desc") or die("Error in selecting data from shora pajoheshi");
  while($row_fetched=mysql_fetch_array($Query))
  {
   if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
   else
     $color="#E2E0E0";
  echo "<tr bgcolor=\"$color\">";
  echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
  echo "<td width=\"87\">";
  echo "<p align=\"center\"><a  href=\"#\" onclick='window.open(\"delete_or_apply_tarh_type.phtml?mainwindow=taarif_shora.phtml&admin=$admin&seed=$seed&action=delete&delete_id=".$row_fetched["cod_shora"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
  echo "<td width=\"47\" bgcolor=\"$color\">";
  echo "<p align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/button_primary.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></td>";
  echo "<td width=\"124\">";
  echo "<p align=\"center\"><a  href=\"add_shora_pajoheshi.phtml?admin=$admin&seed=$seed&cod_shora=".$row_fetched["cod_shora"]."\"><img border=\"0\" src=\"image/button_primary.png\" width=\"11\" height=\"13\" alt=\"Add Shora User\" ></a></td>";
  echo "<td width=\"110\">";
  echo "<p align=\"center\"  class=\"tahoma1\">".substr($row_fetched["shora_name"],0,150)."</td>";
  echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
  echo "</tr>";
  }
  
  echo "<tr>";
  echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"124\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"110\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
  echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
  echo "</tr>";
  echo "</table>";
}
else
{

  echo "<p align=\"center\"  class=\"tahoma1\">با کليک روي کليد اضافه ميتوانيد يک  شورا اضافه کنيد";

}

   footer_forms($admin,$seed);
?>



