<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


if(isset($action))
{
  if (strcmp($action,"add_tarh")==0)
  {

    if(strlen(trim($email)) > 0  && strlen(trim($cod_tarh_new)) > 0  && strlen(trim($family)) > 0  && strlen(trim($name)) > 0  && strlen(trim($tarh_name_e)) > 0  && strlen(trim($tarh_name)) > 0  && strlen(trim($kelid_vaje)) > 0  && strlen(trim($line_tahgig)) > 0 &&   strlen(trim($zarorat)) > 0  && strlen(trim($ahdaf)) > 0  &&  strlen(trim($soalat)) > 0 &&  strlen(trim($raveshejra)) > 0 && $tarh_type!='-1' && $cod_daneshkade!='-1'  )
    {
      $query="select * from tarh where ( tarh_title_farsi =\"$tarh_name\" or tarh_title_english=\"$tarh_name_e\"  ) and creator=\"$admin\" ";
      $result=mysql_query($query) or die("Error in selecting data from tarh  ");

      if ( mysql_num_rows($result) <= 0 )
      {
        $query="select *  from tarh where cod_tarh_user = '$cod_tarh_new'";
        $myresult=mysql_query($query) or die("Error in selecting data from tarh");
        if( mysql_num_rows($myresult) <= 0 )
        {
         $query="select *  from user_login where email = '$email'";
         $myresult1=mysql_query($query) or die("Error in selecting data from tarh");
         if( mysql_num_rows($myresult1) <= 0 )
         {
           $password=randstring(6);
           $query  = "insert into user_login set  name=\"$name\" , family=\"$family\", password='$password', email =\"$email\",  cod_bank=\"$cod_bank\" , bank_name=\"$bank_name\" , shoabe=\"$shoabe\" , hesab=\"$hesab\"";
           $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");
         }

         $query="select *  from tarh";
         $myresult=mysql_query($query) or die("Error in selecting data from tarh");
         if( mysql_num_rows($myresult) > 0 )
         {
            $query="select max(cod_tarh) as max_cod from tarh";
       	    $myresult=mysql_query($query) or die("Error in selecting data from tarh");
            $myfetch=mysql_fetch_array($myresult);
            $max_cod = $myfetch["max_cod"];
	        $max_cod = intval($max_cod);
            $max_cod++;
         }
         else
         {
           $max_cod = 1;
         }


         $query="insert into tarh  set cod_tarh=\"$max_cod\",tarh_title_farsi='$tarh_name' ,tarh_title_english=\"$tarh_name_e\",  kelidvajeh ='$kelid_vaje',  line ='$line_tahgig', zarorat ='$zarorat', ahdaf ='$ahdaf', soalat ='$soalat', shive_ejra  ='$raveshejra', tarh_type =$tarh_type , creator='$email', cod_tarh_user='$cod_tarh_new', tarh_time='".date("Y-m-d")."',vaziat=\"0\" , tarh_type_1='$tarh_type_1', tarh_type_2='$tarh_type_2' ,confirm_tarh ='0' ";
 
		 $result=mysql_query($query) or die("Error in inserting data into tarh #1");
         $action="ثبت چکيده طرح با عنوان"."<br>".$tarh_name;
         set_log($action,$admin,date("Y-d-m"));

         ?>
         <script language="javascript">
         window.location="<? echo "sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh_new";  ?>";
         </script>
         <?
		}
		else
         $status="duplicate_entry";
      }
      else
       $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }

}



$tarh_name="";
$tarh_name_e="";
$tarh_type="";
$kelid_vaje="";
$kelid_vaje_e="";
$line_tahgig="";
$line_tahgig_e="";
$zarorat="";
$ahdaf="";
$soalat="";
$ahdaf="";
$raveshejra="";







?>


<?  echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=add_tarh&admin=$admin&seed=$seed\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/chekide.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">طرحي با اين عنوان توسط شما تعريف شده</td>";
    echo "</tr>";
  }
?>



 <tr>
    <td width="350" align="right"><input type="text" name="name" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام مجري اول</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="family" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي مجري اول</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="hesab" size="20"   class="edit-user" onkeypress="return checkit()" value='<? echo $hesab; ?>'></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>شماره حساب</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="bank_name" size="20"   class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام بانک</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="shoabe" size="20"    class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>شعبه بانک</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="cod_bank" size="20"    class="edit-user" onkeypress="return checkit()"></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>کد بانک</td>
  </tr>



   <tr>
    <td width="350"  align="right"><input type="text" name="email" size="20" class="edit-user"  value="کلمه عبور , پست لکترونيکي شما محسوب خواهد شد" onfocus="email.value=''" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>


 <tr>
    <td width="350" align="right"><input type="text" name="cod_tarh_new" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>کد طرح</td>
  </tr>


  <tr>
    <td width="350" align="right"><input type="text" name="tarh_name" size="20"  class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام طرح</td>
  </tr>
   <tr>
    <td width="350" align="right"><input type="text" name="tarh_name_e"   size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(نام طرح (انگليسي</td>
  </tr>

<tr>
    <td width="350" align="right"><input type="text" name="kelid_vaje" size="20"   class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>کليد واژه ها</td>
  </tr>
 <!--  <tr>
    <td width="350" align="right"><input type="text" name="kelid_vaje_e"   size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>(کليد واژه ها (انگليسي</td>
  </tr>  -->


  <tr>
    <td width="350" align="right"><input type="text" name="line_tahgig"  size="20" class="edit-user"  dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>لاين تحقيقاتي</td>
  </tr>
  <!--  <tr>
     <td width="350" align="right"><input type="text" name="line_tahgig_e"   size="20" class="edit-user" ></td>
     <td width="150" class="tahoma1"><span class="star-message">*</span>(لاين تحقيقاتي(انگليسي</td>
  </tr>  -->

  <tr>
  <?
    $query="select * from tarhtype order by tarh_type_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");

  ?>
    <td width="350" align="right"><select size="1" name="tarh_type" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
         echo "<option value=\"".$row_fetched["tarh_type"]."\" class=\"tahoma1\">".$row_fetched["tarh_type_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نوع طرح</td>
  </tr>


</table>
<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
  <?
   $query="select * from tarhtype_1 order by tarh_type_desc ";
   $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
   if(mysql_num_rows($qresult) > 0 )
   {
   echo "<tr>";
   while($row_fetched=mysql_fetch_array($qresult))
   {
    echo "<td width=\"350\" align=\"right\" class=\"tahoma1\" >".$row_fetched["tarh_type_desc"]."<input type=\"radio\" value=\"".$row_fetched["tarh_type"]."\"  name=\"tarh_type_1\"></td>";
    echo "<td width=\"150\" class=\"tahoma1\" ></td>";
    echo "</tr>";
   }
   }
  ?>

</table>
<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <?
   $query="select * from tarhtype_2 order by tarh_type_desc ";
   $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
   if(mysql_num_rows($qresult) > 0 )
   {
   echo "<tr>";
   while($row_fetched=mysql_fetch_array($qresult))
   {
    echo "<td width=\"350\" align=\"right\" class=\"tahoma1\" >".$row_fetched["tarh_type_desc"]."<input type=\"radio\" value=\"".$row_fetched["tarh_type"]."\"  name=\"tarh_type_2\"></td>";
    echo "<td width=\"150\" class=\"tahoma1\" ></td>";
    echo "</tr>";
   }
   }
  ?>
</table>


<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


         


  <tr>
    <td width="350" align="right"><textarea   rows="7"  name="zarorat"  class="edit-user"  dir=RTL   ></textarea></td>
    <td width="150" class="tahoma1" valign="top"><span class="star-message">*</span>ضرورت اجراي طرح به اختصار</td>
  </tr>

  <tr>
    <td width="350" align="right"><textarea   rows="7"  name="ahdaf" class="edit-user"  dir=RTL   ></textarea></td>
    <td width="150" class="tahoma1" valign="top"><span class="star-message">*</span>اهداف کلي و اختصاصي</td>
  </tr>

  <tr>
    <td width="350" align="right"><textarea   rows="7"  name="soalat" class="edit-user"   dir=RTL   ></textarea></td>
    <td width="150" class="tahoma1" valign="top"><span class="star-message">*</span>سوالات پژوهشي و فرضيات</td>
  </tr>

      <tr>
    <td width="350" align="right"><textarea   rows="7"  name="raveshejra" class="edit-user"  dir=RTL   ></textarea></td>
    <td width="150" class="tahoma1" valign="top"><span class="star-message">*</span>روش اجرا و شيوه هاي تحليل</td>
  </tr>


  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>

<?
  footer_forms($admin,$seed);
 ?>

<script>

            function setdefault()
            {
              document.sabt_tarh.cod_group.options[0].selected=true;

              document.sabt_tarh.cod_daneshkade.options[0].selected=true;
            }



            var temp=document.sabt_tarh.cod_group
            function redirect()
            {
              for (m=temp.options.length-1;m>0;m--)
                temp.options[m]=null
                var myselecteditem = this.sabt_tarh.cod_daneshkade.selectedIndex
                myselecteditem--
                if( myselecteditem<0 )
                  return

                for (i=0;i<group[myselecteditem].length;i++)
                {

                  temp.options[i]=new Option(group[myselecteditem][i].value,group[myselecteditem][i].text)
                }
                temp.options[0].selected=true
            }



            </script>




