<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";
	
//   echo $marhale;
     if(strcmp($marhale,"0")==0)
       $marhale_txt="1";
    else if(strcmp($marhale,"100")==0)
       $marhale_txt="نهايي";
    else 
       $marhale_txt="مياني";
  $date=date("Y-m-d");
  if(isset($action))
{
  if (strcmp($action,"accept_gozaresh")==0)
  {
   $q="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
  // echo $q;
   $result=mysql_query($q) or die("Error in selecting data from marhale_report");
  // echo mysql_num_rows($result) ;
    if(mysql_num_rows($result) > 0)
	 {
	 	$query="update marhale_report set accept_gozaresh='$accept_gozaresh',accept_gozaresh_date='$date' where cod_tarh='$cod_tarh' and marhale='$marhale'";
	 	$result=mysql_query($query) or die("Error in updating data from marhale_report");
	 	?>
           <script language="javascript">
           window.location="<? echo "reports_view.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh";  ?>";
           </script>
        <?
	 //	echo $query;
	 }
  }

}
  $q="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
  $result=mysql_query($q) or die("Error in selecting data from marhale_report");
  $rf=mysql_fetch_array($result);
  $accept_gozaresh=$rf["accept_gozaresh"];

echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=accept_gozaresh&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&unarch=$unarch&current=$current&marhale=$marhale\">"; ?>



<table border="1" width="500" bgcolor="#EEE7F8" cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
 <tr>
    <td width="100%" align="center" colspan="2" class="tahoma1">
     فعال / غير فعال کردن اطلاع رساني به مجري مربوط به گزارش مرحله <? echo $marhale_txt;?></td>
  </tr> 
 <tr>
    
    <td width="50%" align="center" class="tahoma1" >
	     <input type="radio" value="1"  name="accept_gozaresh" <? if(strcmp($accept_gozaresh,"1")==0) echo "checked"  ;?> >غير فعال
     </td>
     
      <td width="50%" align="center" class="tahoma1"  >
	    <input type="radio" value="0"  name="accept_gozaresh" <? if(strcmp($accept_gozaresh,"0")==0) echo "checked"  ;?> >  فعال
     </td>
   
	     
 </tr>

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>
 <table border="0" width="500">
<tr>
    <td width="100%"  align="center" class="tahoma1"><A HREF="javascript:history.go(-1)"> بازگشت</a></td>
</tr>

</table> 
<?

footer_forms($admin,$seed);
?>