<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

if(!isset($version))
 $version="-1";
 $query="select * from tarh where cod_tarh='$cod_tarh' and version='$version'";
 
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
$color="PALETURQUOISE";
echo "<br>";

   
   if(mysql_num_rows($result) > 0)
   {
       echo "<br>";
?>

<TABLE cellSpacing=0  width="90%" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center  class="tahoma1" dir="rtl"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<?

     echo "<table border=\"0\" width=\"90%\"  cellspacing=\"1\" cellpadding=\"1\" >";
     $color="PALETURQUOISE";
     //$row_fetched=mysql_fetch_array($result);
    
     echo "<tr>";
     echo "<td align=\"center\" colspan=\"2\" width=\"100%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>اهداف</b></td>";
     echo "</tr>";
    
     echo "<tr>";
     echo "<td width=\"60%\" dir=\"rtl\" bgcolor=$color align=\"right\" class=\"tahoma1\"  dir=\"rtl\">".$row_fetched["ahdaf"]."</td>";
     echo "<td width=\"40%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\">اهداف کلي و اختصاصي</td>";
     echo "</tr>";

   
     echo "</table>";
   }
   
?>


<?
footer_forms($admin,$seed);
?>

