<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");

echo "<br>";


if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
   $daneshkade_caution="tarh.cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   

if ( ! isset($tarh_year))
    $tarh_year = '-1';

if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=10000;
      $current=1;
    }
       
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
$query="select * from group_karshenasan where username='$admin'";

$result=mysql_query($query) or die("Error in selecting data from karshenas_tarh");
$row_fetched=mysql_fetch_array($result);
$cod_karshenas=$row_fetched["cod_karshenas"];
$karshenas_type=$row_fetched["cod_karshenas"];

if(strcmp($karshenas_type,"0")==0)
  $send_group="send_group_karshenas='0' ";
else
  $send_group="1 ";

if(isset($name_e))
{
  $query="select  tarh.*  from tarh  , user_login   where user_login.email=tarh.creator    and  $send_group and $year_caution  and $daneshkade_caution and ( user_login.name  like $myname_search or tarh.cod_tarh like $myname_search  or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)    and  tarh.archieved='0' and tarh.version='-1'  group by tarh.cod_tarh  order by  tarh.cod_tarh desc";
}
else
  $query="select  tarh.*  from tarh  where   tarh.archieved='0'   and  $send_group and $year_caution  and $daneshkade_caution     and tarh.version='-1'  group by tarh.cod_tarh  order by tarh.cod_tarh desc";

  

$result=mysql_query($query) or die("Error in selecting data from tarh 1");
$reccount = mysql_num_rows($result);


 if(isset($name_e))
{
  $query="select  tarh.*  from tarh , user_login     where user_login.email=tarh.creator     and $send_group and $year_caution  and $daneshkade_caution and ( user_login.name  like $myname_search or tarh.cod_tarh like $myname_search  or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)       and  tarh.archieved='0' and tarh.version='-1'  group by tarh.cod_tarh  order by  tarh.cod_tarh desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select  tarh.*  from tarh where  tarh.archieved='0' and     $send_group and $year_caution  and $daneshkade_caution       and   tarh.version='-1'  group by tarh.cod_tarh  order by  tarh.cod_tarh desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;

 

$result=mysql_query($query) or die("Error in selecting data from tarh 2");








if(mysql_num_rows($result) > 0)
 {

echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&tarh_year=$tarh_year\">";
?>
<table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td colspan="3" align="center" class="tahoma1">
طرح هاي در حال کارشناسي
 </td> 
 </tr>
 <tr>
 <td colspan="3" align="center" class="tahoma1">
   رنگ قرمز به معني اچ اس آر و رنگ سبز به معني گرانت است
 </td> 
 </tr>
 <tr>
 
<?


$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select class=\"but-wide\" size=\"1\" class='tahoma1' name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\" dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
 
?>
  </select> دانشکده / مرکز 
  </td>
  
<?
echo "</form>";
echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
  </td>
  </form>
  
<?   
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 
 ?>
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
   $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year";
     if(isset($name_e))
      $myascdescpub=$myascdescpub."&name_e=$name_e";
 
   pubshowpages("all_tarhs.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
  
    <td rowspan="2" width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
  <!--  <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ليست نظرات شما</font></td> -->
   
    
     <?
      $query="select * from group_karshenasan where username='$admin'";						  
      $result1=mysql_query($query) or die("Error in selecting data from group_karshenasan");
      $row_fetched_end=mysql_fetch_array($result1);
 
     ?>
       <td rowspan="2" width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کليه نظرات</font></td>
     
      <td rowspan="2" width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
  
      
    <td rowspan="2" width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح از نظر کارشناسي</font></td>
    <td colspan="2" width="5%" bgcolor=<? echo "$title_color"; ?> colspan='2'>
      <p align="center" class="tahoma1"><font color="black">فرم ايزو</font></td>
    <td rowspan="2" width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده / مرکز</font></td>
    <td  rowspan="2" width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td rowspan="2" width="40%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
   <tr>
    
     <td width="4%" class='tahoma1' bgcolor=<? echo "$title_color"; ?>>تاريخ دريافت توسط شما
    </td>
    <td width="4%" class='tahoma1' bgcolor=<? echo "$title_color"; ?>>تاريخ ارسال به شما
    </td>
     
   </tr>   
    
  <?


 $color=$list_color_1;

 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  
     $startdate = $row_fetched["receive_karshenas_date"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $receive_karshenas_date=hijricalender( $startyear , $startmon , $startday );
//  $receive_karshenas_date = enum2fnum($receive_karshenas_date);
 
  
   $startdate = $row_fetched["send_to_karshenas_date"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $send_to_karshenas_date=hijricalender( $startyear , $startmon , $startday );
//  $send_to_karshenas_date = enum2fnum($send_to_karshenas_date);
 
  
   if(strcmp($row_fetched["indoing"],"1")==0 || strcmp($row_fetched["finished"],"1")==0 || strcmp($row_fetched["ready_gharardad"],"1")==0 )
       $user_editable="غير قابل ويرايش";
    else
       $user_editable="قابل ويرايش";
  
  
  $ttype_2=$row_fetched["tarh_type_2"];
  $color_line="black";
  $tarh_type_q="select * from tarhtype_2 where tarh_type='$ttype_2' and (tarh_type_desc like \"%گرانت%\" or  tarh_type_desc like \"%گرنت%\")";
  //echo $tarh_type_q;
  $tarh_type_r=mysql_query($tarh_type_q) or die("error");
  if(mysql_num_rows($tarh_type_r)>0)
  {
  	 $color_line="green";
  }
  
  $m_tarh_type=$row_fetched["tarh_type"];
  
  if(strcmp($m_tarh_type,"6")==0)
     $color_line="red";
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  //echo $myq;
  $myres=mysql_query($myq) or die("error");
  $rf=mysql_fetch_array($myres);
  $daneshkade=$rf["daneshkade_name"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
     {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }
//  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a href='finish_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'> $user_editable </a></font></td>";
  //     echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line>$user_editable</font></td>";
//echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"open_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >باز شدن</a></font></td>";
//echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويراستها</a></font></td>";
 // echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >مکاتبات</a></font></td>";


  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></font></td>";
  //echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a   href=\"your_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >نظرات شما</a></td>";
//  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a target=\"_blank\" href=\"notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\" alt=\"Your Notes\" ></a></font></td>";
 // echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"send_karshenasi_shode.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >اتمام کار کارشناسي</a> </font></td>";
    
  
 $query="select * from group_karshenasan where username='$admin'";
						  
 $result1=mysql_query($query) or die("Error in selecting data from group_karshenasan");
 $row_fetched_end=mysql_fetch_array($result1);
 //echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"send_modir_akhlagh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/tick.gif\" alt=\"Send Colleaugue\" ></font></a></td>";
 if(strcmp($row_fetched_end["karshenas_type"],"0")==0)
  {
  //  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a  href=\"send_group_karshenas.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/tick.gif\" alt=\"Send Colleaugue\" ></font></a></td>";
    
 }
 //}
//echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a  href=\"others_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/notes.gif\" alt=\"Others Notes\" ></a></td>";   
 $mytarh_type = $row_fetched["status"];
 
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
 
   
   //echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"karshenasan_notes.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"Karshenasan Notes\" ></a></td>";
 //  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"Send To Karshenas\" > </a></td>";
  
  $status_comment="";

 $q="select * from group_karshenasan where username='$admin'";
 $myres200=mysql_query($q) or die("error");
 $rf=mysql_fetch_array($myres200);
 if($rf["karshenas_type"]=='0')
 {
 
  $q="select * from group_karshenasan_tarh,group_karshenasan where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan_tarh.cod_karshenas=group_karshenasan.cod_karshenas and group_karshenasan.karshenas_type='1' group by group_karshenasan_tarh.cod_tarh";
   
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
    $plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{  		
  	 $kar_name=$myrf1["karshenas_family"];
  	 if(strcmp($myrf1["note_submitted"],"1")==0 || strlen( $myrf1["comment_karshenas"] )>0)
  	 {
	   $plus="+";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
  	 }
  	 else
  	 {
	   $plus="-";
	    $status_comment=$status_comment.$kar_name.":".$plus."<br>";
  	 }
    }	
  }
  }
    //$status_comment=$status_comment.$kar_name.":".$plus."<br>";
  //}
  
  
  $q="select * from karshenasan_tarh where cod_tarh='$cod_tarh'";
  $r=mysql_query($q) or die("Error");
  if(mysql_num_rows($r) > 0)
  {
  	$plus="-";
  	while($myrf1=mysql_fetch_array($r))
  	{
  	 if(strcmp($myrf1["refered"],"1")==0  || strlen( $myrf1["comment_karshenas"] )>0)
  	 {
	   $plus="+";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }
	 else
	  {
	   $plus="-";
	   $qq="select * from karshenasan where cod_karshenas='".$myrf1["cod_karshenas"]."'";
	   $rr=mysql_query($qq) or die("Error");
	   $myrf4=mysql_fetch_array($rr);
	   $status_comment=$status_comment.$myrf4["karshenas_family"].":".$plus."<br>";
	 }	
  	}
    //$status_comment=$status_comment."<br>"."ارسال به اپيدميولوژيست : ".$plus."<br>";  
  
    //$status_comment=$status_comment."<br>"."-".": ارسال به اپيدميولوژيست"."<br>";
  }



 //$mystatus
   $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line><a href='others_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh'>نظرات</a></font></td>";

  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><font color=$color_line>".$First_mojri_name."</font></td>";
 

 echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\" dir=\"rtl\"> <font color=$color_line>".$status_comment."</font></td>";
  
 
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"> <a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$receive_karshenas_date."</font></a></td>";
  
  
 
  echo "<td width=\"5%\" bgcolor=$color align=\"center\" class=\"tahoma1\"> <a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$send_to_karshenas_date."</font></a></td>";
  
  
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$daneshkade."</font></a></td>";
  echo "<td width=\"40%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"> <a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$row_fetched["tarh_title_farsi"]."</font></a></td>";
  
  $cod_tarh_user=$row_fetched["cod_tarh_user"];


     echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><font color=$color_line>".$cod_tarh."</font></a></td>";

  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرحي يافت نشد يا طرح ارسال شده اي به شما موجود نمي باشد","red");
}
echo "</form>";
footer_forms($admin,$seed);


?>

