<?
include("include/database-connect.phtml");
include("include/include.phtml");

include("include/numper.class.php");


global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;

$karshenasi_koll_1=mablagh_karshenasi($cod_tarh);


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";

 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type == 1 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
 }
 
 // $cod_tarh="84-02-06-008";
 
 
  $query="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
  $result=mysql_query($query) or die("Error10");
  if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	$mojri=$row_fetched["mojri_code"];
 	$heiat_elmi=$row_fetched["heiat_elmi"];
 	$start_time=$row_fetched["start_time"];
    $start_time_tmp=$start_time;
 	$pish_pardakht=$row_fetched["pish_pardakht"];
 	$payanname=$row_fetched["payanname"];
 	$nazerin=$row_fetched["nazerin"];
 	$unnazerin=$row_fetched["unnazerin"];
 	$time_month=$row_fetched["time_month"];
 	$zarib_maliat=$row_fetched["maliat"];
    $exists=1; 	
    
 } 	
 else
 {
 	$payanname="0";
 	$mojri="0";
 	$heiat_elmi="0";
 	$start_time="0";
 	$pish_pardakht="0";
 	$nazerin="0";
 	$time_month="0";
 	$unnazerin="0";
    $exists=0;
 }
 
 //$start_time="1385-02-12";
// $time_month="15";
 if( $start_time > 0 && $time_month > 0 )
 {
   $year=substr($start_time,0,4);
   $month=substr($start_time,5,2);
   $day=substr($start_time,8,2);
   $start_time=$day."/".$month."/".$year;
  // $month_add=$time_month+$month;
   $month_add=$time_month;
  // echo $month_add;
  // exit();
   for($i=1; $i<=$month_add;$i++)
   {
   	$month=$month+1;
    if($month >12 )
    {
      //$year_add=(int)($month_add/12); 
      $year_add++;
 	  $year=$year+1;	 	 	
      //$month=$month_add-($year_add*12); 
	  $month=1;    
     // if($month==0)
 	 //   $month=12;  
    }
    //else
     // $month=$month_add;
   }
  
   $end_time=$day."/".$month."/".$year;
 }
 else
 {
   $end_time="تعريف نشده";   
 }
       
    
    $query1="select * from jalase_shora , jalase_shora_tarh where jalase_shora.creator=jalase_shora_tarh.creator and jalase_shora.shomare_jalase=jalase_shora_tarh.shomare_jalase  and jalase_shora_tarh.cod_tarh='$cod_tarh'";
    $result10=mysql_query($query1) or die("Error11");
    if(mysql_num_rows($result10) >0)
    {
      $rf100=mysql_fetch_array($result10);
	  $tarikh_jalase=$rf100["tarikh_jalase"];	
	  $year=substr($tarikh_jalase,0,4);
      $month=substr($tarikh_jalase,5,2);
      $day=substr($tarikh_jalase,8,2);
      $tarikh_jalase=$day."/".$month."/".$year;
      
    }
    else
      $tarikh_jalase=" نا معلوم ";
 
   
   
   $query1="select * from gozaresh_gharardad where cod_tarh='$cod_tarh'";
   $result500=mysql_query($query1)or die("error12");
   if(mysql_num_rows($result500) > 0)
   {
   	$gozaresh_cnt=mysql_num_rows($result500);
   }
   else
   	$gozaresh_cnt=0;

   
   
   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";
	
   $result1=mysql_query($query1) or die("Error14");
   $query="select distinct mojri.* from mojri_tarh , tarh,mojri  where mojri.mojri_code=mojri_tarh.mojri_code and mojri_tarh.cod_tarh = tarh.cod_tarh  and tarh.cod_tarh=\"$cod_tarh\" and mojri_tarh.mojri_or_hamkar='0'  ";
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh");
    
   if(mysql_num_rows($result) > 0 || mysql_num_rows($result1) > 0)
   {
   	$i=0;
  
	while($row_fetched1=mysql_fetch_array($result1))
    {
      
      $cod_mojri=$row_fetched1["email"];
      if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
   	    $checked="1";
      }
      else
      {
   	    $checked="";
      }
  
     if(strcmp($checked,"1")==0)
     { 
      $name_family=$row_fetched1["name"]." ".$row_fetched1["family"];
     }
 
   }
 
 
 
   while($row_fetched=mysql_fetch_array($result))
   {
  
    $cod_mojri=$row_fetched["mojri_code"];
    
    if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
      	
   	    $checked1="1";
      }
     else
      {
   	    $checked1="";
      }
   
 
    if(strcmp($checked1,"1")==0)
    {  
      
      $name_family=$row_fetched["name"]." ".$row_fetched["family"];
  
    }
    
   }
 }
else // if reccount of tarh  < =0
{
 $name_family="توسط مجري تعيين نشده";
}

   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";
	
   $result100=mysql_query($query1) or die("Error14");
   if(mysql_num_rows($result100))
   {
       $rf_mojri=mysql_fetch_array($result100);
      $bank_name=$rf_mojri["bank_name"];
 	   $hesab=$rf_mojri["hesab"];
	   $q1="select * from hesab_type where  hesab_type='$bank_name'";
	   $rs100=mysql_query($q1) or die("error");
	   if(mysql_num_rows($rs100)>0)
	   {
	        $rf500=mysql_fetch_array($rs100);
	        $hesab_type_desc  =$rf500["hesab_type_desc"];
	        $shomare_hesab=   $hesab_type_desc.$hesab;
        }
	   else
	        $shomare_hesab="";
	 }
	 else
	   $shomare_hesab="";
	   

   $query1="select * from answer_mojri_gharardad  where  cod_tarh='$cod_tarh' and bank_name !='-1'";
	
   $result100=mysql_query($query1) or die("Error14");
   if(mysql_num_rows($result100)>0)
   {
       $rf_mojri=mysql_fetch_array($result100);
      $bank_name=$rf_mojri["bank_name"];
 	   $hesab=$rf_mojri["hesab"];
	   $q1="select * from hesab_type where  hesab_type='$bank_name'";
	   $rs100=mysql_query($q1) or die("error");
	   if(mysql_num_rows($rs100)>0)
	   {
	        $rf500=mysql_fetch_array($rs100);
	        $hesab_type_desc  =$rf500["hesab_type_desc"];
	        $shomare_hesab=   $hesab_type_desc.$hesab;
        }
	   else
	        $shomare_hesab="";
	 }
 	   
	   
	   
//--------------------------------------------------------------------------
if(strlen(trim($name_family)) <= 0)
   $name_family="توسط مجري تعيين نشده";


  $query="select * from tarh where cod_tarh='$cod_tarh' and version=\"-1\" ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  
  
  //-------------------- قسمت مربوط به عقد قرارداد
  
  $mablagh_aghd_gharardad = $row_fetched["mablagh_aghd_gharardad"];
  
  if($mablagh_aghd_gharardad  > 0)
  {
  	$a=($gozaresh_cnt-1)*100000;
  	$b=($mablagh_aghd_gharardad*1)/100;
  	// محاسبه گزارش دوم تا ماه نهايي ضربدر 5000 ريال
   	$qr="select * from gozaresh_gharardad where cod_tarh='$cod_tarh' and marhale='2'";
	$resultr=mysql_query($qr) or die("error15");
	$rft=mysql_fetch_array($resultr);	
	$second_gozaresh=$rft["date_gozaresh"]; 
	 
	$year=substr($second_gozaresh,0,4);
    $month=substr($second_gozaresh,5,2);
    $day=substr($second_gozaresh,8,2);
  //  echo $year.":".$month.":".$day;
    $month_remain=0;
  //  echo $end_time."<br>";
    for($k=1;$k<=$time_month;$k++)
    {      	
      $month=$month+1;
      if($month>12)
      {
        $month=1;
        $year=$year+1;
      }
      //$month1=str_replace($month,"0","");
     // $month1=trim($month1);
     
      $my_end_time=substr($end_time,3,7);
	  //$date_tmp=$day."/".$month."/".$year;
       $date_tmp=$month."/".$year; 
      if(strcmp($my_end_time,$date_tmp)==0)
      {
        $month_remain=$k;  // mohasebe teadad mahe dovvom ta gozaresh akhar
        
      }
     // echo $date_tmp.":".$my_end_time."<br>";  
     }
	 
    // echo $month_remain.":".$date_tmp.":".$my_end_time.":".$second_gozaresh.":".$month_remain.":".$time_month.":".$month.":".$year.":".$end_time.":".$date_tmp.":".$my_end_time.":". $date_tmp.":".$end_time;
   //  exit();
  // exit();

     $c=$month_remain*5000;
     $c1=$c;
	 //echo $a."<br>".$b."<br>".$c."<br>".$month_remain;
	 //exit();
	 $nezarat_koll=$a+$b+$c; // نظارت بخش اول کار

	 
	  // محاسبه هزينه پرسنلي و محاسبه ماليات آن
 	  $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1' order by activity_type ";
      $result00=mysql_query($query) or die("Error in selecting data from hazine personnel");
      if(mysql_num_rows($result00) > 0)
      {
     
        $mycount=0;
       while($row_fetched00=mysql_fetch_array($result00))
       {
  
       $my_summary = $row_fetched00["per_hour"]*$row_fetched00["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       }       
      }
      $hazine_personnel=$mycount;
      
      $darsad_50=$mablagh_aghd_gharardad*50/100;
      
      
      if($hazine_personnel > $darsad_50)
	  {	    	
	   //$x=($mablagh_aghd_gharardad*5)/100; 	
	   $y=($nezarat_koll*100)/(100-$zarib_maliat);
	   //$maliat_koll=$x+$y;
	   $aa=($mablagh_aghd_gharardad-$hazine_personnel)*100/(100-$zarib_maliat);
	   $mablagh_koll=$hazine_personnel+$y+$aa;
	   $nezarat_maliat=$nezarat_koll*100/(100-$zarib_maliat);
	  }
	  else
	   {
	   //	$mablagh_aghd_gharardad=($mablagh_aghd_gharardad*100)/95;
	   	//$maliat_koll=($mablagh_aghd_gharardad+$nezarat_koll)*100/95;
	   	$mablagh_koll=$mablagh_aghd_gharardad+$nezarat_koll;
	   	$mablagh_koll=$mablagh_koll*100/(100-$zarib_maliat);
	   	$nezarat_maliat=$nezarat_koll*100/(100-$zarib_maliat);
	   }
	  
	  /*
      $x=($hazine_personnel*5)/100;
     	  
      $y=($nezarat_koll*5)/100;
      $maliat_koll=$x+$y;
	  */

  	 //-------------------marhale 1 ------------------------------------------
 
	  
	  $query="select * from gozaresh_gharardad where marhale='0' and cod_tarh='$cod_tarh'";
      $result88=mysql_query($query) or die("Error");
      if(mysql_num_rows($result88) > 0)
	  {
	  	$rf66=mysql_fetch_array($result88);
	    if($hazine_personnel > $darsad_50)
	    {
	      $mablagh_marhale_0=$rf66["mablagh"]*$mablagh_koll/100;
	      $maliat_marhale_0=$mablagh_marhale_0*$zarib_maliat/100;
	      $hagh_ol_zahme_karshenasi_0=($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
		  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0;
		   $mablagh_khales_mojri_0= $mablagh_khales_mojri_0-$hagh_ol_zahme_karshenasi_0;
	      
	  		
	    }
	    else
	    {
	      $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
	      $mablagh_marhale_0=($darsad_marhale+($darsad_marhale/100))*100/(100-$zarib_maliat);
	      $maliat_marhale_0=$mablagh_marhale_0*$zarib_maliat/100;
	      $hagh_ol_zahme_karshenasi_0=($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
		  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0-$hagh_ol_zahme_karshenasi_0;
	      
	      
	  		      
	    }
	    
	    
	  	
	  }
	//  echo "mohsen <br>".$end_time."<br>".$month_remain."<br>".$mablagh_marhale_0."<br>".$mablagh_aghd_gharardad."<br>".$maliat_1."<br>".$hazine_personnel;
	  //exit();
	   //$mablagh_koll_tarh=$maliat_koll+$nezarat_koll+$mablagh_aghd_gharardad;
	  
	  //-------------------marhale Nahayee ------------------------------------------
	  
	  $a=100000;
	  $query="select * from gozaresh_gharardad where marhale='100' and cod_tarh='$cod_tarh'";
      $result=mysql_query($query) or die("Error");
      $b=0;
	  if(mysql_num_rows($result) > 0)
	  {
	  	$rf66=mysql_fetch_array($result);
	   if($hazine_personnel > $darsad_50)
       {
  	      $mablagh_marhale_end=$rf66["mablagh"]*$mablagh_koll/100;
  	     
  	      $nezarat=125000+$mablagh_marhale_end/100;
      	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
  	
	      $maliat_marhale_end=$mablagh_marhale_end*$zarib_maliat/100;
	      $hagh_ol_zahme_karshenasi_end=100000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100+$month_remain*5000;
	  	
	      $mablagh_khales_mojri_end=$mablagh_marhale_end-$maliat_marhale_end;
	      $mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
	      $hagh_ol_zahme_karshenasi_end=100000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100+$month_remain*5000;
	  		
        }
        else
        {
  	      $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
  	      $hagh_ol_zahme_karshenasi_end=100000+($darsad_marhale/100)+$month_remain*5000;    	      
	      $mablagh_marhale_end=($darsad_marhale+$hagh_ol_zahme_karshenasi_end)*100/(100-$zarib_maliat);
 
	      $maliat_marhale_end=$mablagh_marhale_end*$zarib_maliat/100;
	      $mablagh_khales_mojri_end=$mablagh_marhale_end-$maliat_marhale_end-$hagh_ol_zahme_karshenasi_end;
	    
	     
	     
        }
        
        
	 $date=$rf66["date_gozaresh"];
 $year=substr($date,0,4);
 $month=substr($date,5,2);
 $day=substr($date,8,2);
 $date_end=$day."/".$month."/".$year; 
	   
	  } 
	   
	 
  }
  
  
 
//$mablagh=$nezarat_koll+$maliat_koll+$mablagh_aghd_gharardad;

  
  $emtiaz1=($mablagh_koll/10000000)*2.5;
  $int_emtiaz=(int)$emtiaz1;
  $real_emtiaz=$emtiaz1-$int_emtiaz;
  if($real_emtiaz > .75)
    $int_emtiaz++;  

    
  $cod_daneshkade = $row_fetched["cod_daneshkade"];
  $query="select * from daneshkade where cod_daneshkade='$cod_daneshkade' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $daneshkade_name=$row_fetched["daneshkade_name"];
  
  if(strlen(trim($daneshkade_name)) <=0)
    $daneshkade_name="تعريف نشده";
  
if($start_time==0)
  $start_time="تعريف نشده";
    
//if($end_time==0)
 // $end_time="تعريف نشده";
  
if($time_month==0)
  $time_month="تعريف نشده"; 

$mablagh_koll_tarh=number_format($mablagh_koll_tarh);
 $tarikh_jalase="6/4/1385";
 
$query="select * from karshenasan,karshenas_type,karshenasan_tarh where karshenasan.karshenas_type=karshenas_type.karshenas_type and karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas and karshenasan_tarh.cod_tarh='$cod_tarh' and karshenas_type.karshenas_type_english_desc='viewer'  ";
//echo $query;
$result=mysql_query($query) or die("Error");
if(mysql_num_rows($result) > 0)
{
	$nazer_rf=mysql_fetch_array($result);
	$namer_name=$nazer_rf["karshenas_name"]." ".$nazer_rf["karshenas_family"];
	
} 
else
 $namer_name="نامعلوم";

header('Content-type: application/msword');
?>
{\rtf1\adeflang1025\ansi\ansicpg1256\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f325\fbidi \fnil\fcharset178\fprq2{\*\panose 00000700000000000000}Titr;}
{\f369\froman\fcharset0\fprq0{\*\panose 00000000000000000000}Arabic Style{\*\falt Times New Roman};}{\f370\froman\fcharset238\fprq2 Times New Roman CE;}{\f371\froman\fcharset204\fprq2 Times New Roman Cyr;}
{\f373\froman\fcharset161\fprq2 Times New Roman Greek;}{\f374\froman\fcharset162\fprq2 Times New Roman Tur;}{\f375\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f376\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}
{\f377\froman\fcharset186\fprq2 Times New Roman Baltic;}{\f378\froman\fcharset163\fprq2 Times New Roman (Vietnamese);}{\f390\fmodern\fcharset238\fprq1 Courier New CE;}{\f391\fmodern\fcharset204\fprq1 Courier New Cyr;}
{\f393\fmodern\fcharset161\fprq1 Courier New Greek;}{\f394\fmodern\fcharset162\fprq1 Courier New Tur;}{\f395\fbidi \fmodern\fcharset177\fprq1 Courier New (Hebrew);}{\f396\fbidi \fmodern\fcharset178\fprq1 Courier New (Arabic);}
{\f397\fmodern\fcharset186\fprq1 Courier New Baltic;}{\f398\fmodern\fcharset163\fprq1 Courier New (Vietnamese);}}{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\green255\blue255;\red0\green255\blue0;\red255\green0\blue255;\red255\green0\blue0;
\red255\green255\blue0;\red255\green255\blue255;\red0\green0\blue128;\red0\green128\blue128;\red0\green128\blue0;\red128\green0\blue128;\red128\green0\blue0;\red128\green128\blue0;\red128\green128\blue128;\red192\green192\blue192;}{\stylesheet{
\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \snext0 Normal;}{\*\cs10 \additive \ssemihidden Default Paragraph Font;}{\*
\ts11\tsrowd\trftsWidthB3\trpaddl108\trpaddr108\trpaddfl3\trpaddft3\trpaddfb3\trpaddfr3\trcbpat1\trcfpat1\tscellwidthfts0\tsvertalt\tsbrdrt\tsbrdrl\tsbrdrb\tsbrdrr\tsbrdrdgl\tsbrdrdgr\tsbrdrh\tsbrdrv 
\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch \af0\afs20 \ltrch \fs20\lang1024\langfe1024\cgrid\langnp1024\langfenp1024 \snext11 \ssemihidden Normal Table;}}{\*\latentstyles\lsdstimax156\lsdlockeddef0}{\*\listtable
{\list\listtemplateid-23928742\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0 \fi-360\li360
\jclisttab\tx360\lin360 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li1080\jclisttab\tx1080\lin1080 }{\listlevel
\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698693\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li1800\jclisttab\tx1800\lin1800 }{\listlevel\levelnfc23\levelnfcn23
\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0 \fi-360\li2520\jclisttab\tx2520\lin2520 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0
\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li3240\jclisttab\tx3240\lin3240 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1
\levelspace360\levelindent0{\leveltext\leveltemplateid67698693\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li3960\jclisttab\tx3960\lin3960 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0
{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0 \fi-360\li4680\jclisttab\tx4680\lin4680 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext
\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li5400\jclisttab\tx5400\lin5400 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li6120\jclisttab\tx6120\lin6120 }{\listname ;}\listid1128402517}{\list\listtemplateid1586429276\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360
\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0 \fi-360\li720\jclisttab\tx720\lin720 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext
\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li1440\jclisttab\tx1440\lin1440 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li2160\jclisttab\tx2160\lin2160 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers
;}\f3\fbias0 \fi-360\li2880\jclisttab\tx2880\lin2880 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li3600
\jclisttab\tx3600\lin3600 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698693\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li4320\jclisttab\tx4320\lin4320 }
{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0 \fi-360\li5040\jclisttab\tx5040\lin5040 }{\listlevel\levelnfc23
\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0 \fi-360\li5760\jclisttab\tx5760\lin5760 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0
\levelfollow0\levelstartat1\levelspace360\levelindent0{\leveltext\leveltemplateid67698693\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0 \fi-360\li6480\jclisttab\tx6480\lin6480 }{\listname ;}\listid1787893201}}{\*\listoverridetable
{\listoverride\listid1128402517\listoverridecount0\ls1}{\listoverride\listid1787893201\listoverridecount0\ls2}}{\*\rsidtbl \rsid276507\rsid409024\rsid478087\rsid666643\rsid924817\rsid993911\rsid1134802\rsid1186943\rsid1320478\rsid1576099\rsid1596967
\rsid1653055\rsid1731732\rsid1782375\rsid1917008\rsid2037710\rsid2177621\rsid2298299\rsid2391111\rsid2435314\rsid2435978\rsid2511252\rsid2579700\rsid3411897\rsid3480889\rsid3688306\rsid3866852\rsid3963768\rsid3964714\rsid4092408\rsid4218595\rsid4275875
\rsid4465195\rsid4666352\rsid4856841\rsid5253536\rsid5526691\rsid5654532\rsid5666041\rsid5720439\rsid5779500\rsid5922000\rsid6058996\rsid6172469\rsid6388501\rsid6425265\rsid6433222\rsid6434471\rsid6571741\rsid6777836\rsid6884977\rsid7343948\rsid7603830
\rsid7618971\rsid7812013\rsid7879705\rsid8009968\rsid8140221\rsid8203564\rsid8409362\rsid8591500\rsid8603075\rsid8866725\rsid8875754\rsid8932775\rsid8978491\rsid9071482\rsid9260526\rsid9333627\rsid9707541\rsid9786697\rsid10031425\rsid10365086\rsid10641895
\rsid10687743\rsid11013323\rsid11017886\rsid11086383\rsid11103980\rsid11147431\rsid11209853\rsid11281911\rsid11290438\rsid11304137\rsid11469895\rsid11495724\rsid11616329\rsid11673285\rsid11810295\rsid12018627\rsid12065372\rsid12066061\rsid12203925
\rsid12266535\rsid12322038\rsid12406067\rsid12549482\rsid12811380\rsid13004894\rsid13191797\rsid13517271\rsid13639741\rsid13704766\rsid13914529\rsid14114560\rsid14551136\rsid14628938\rsid14745748\rsid14759550\rsid14834228\rsid14882516\rsid15017470
\rsid15083196\rsid15140096\rsid15739294\rsid15993592\rsid16135934\rsid16219043\rsid16332217\rsid16656259\rsid16717877}{\*\generator Microsoft Word 11.0.5604;}{\info{\title  }{\author admin}{\operator Dear User!}{\creatim\yr2007\mo2\dy10\hr9\min27}
{\revtim\yr2007\mo2\dy10\hr9\min27}{\printim\yr2006\mo8\dy26\hr15\min28}{\version2}{\edmins0}{\nofpages2}{\nofwords546}{\nofchars3117}{\nofcharsws3656}{\vern24689}}\ltrsect 
\widowctrl\ftnbj\aenddoc\noxlattoyen\expshrtn\noultrlspc\dntblnsbdb\nospaceforul\formshade\horzdoc\dgmargin\dghspace180\dgvspace180\dghorigin1800\dgvorigin1440\dghshow1\dgvshow1
\jexpand\viewkind1\viewscale100\pgbrdrhead\pgbrdrfoot\splytwnine\ftnlytwnine\htmautsp\nolnhtadjtbl\useltbaln\alntblind\lytcalctblwd\lyttblrtgr\lnbrkrule\nobrkwrptbl\snaptogridincell\allowfieldendsel\wrppunct\asianbrkrule\rsidroot924817 \fet0\ltrpar 
\sectd \ltrsect\linex0\endnhere\sectlinegrid360\sectdefaultcl\sftnbj {\*\pnseclvl1\pnucrm\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl2\pnucltr\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl3\pndec\pnqc\pnstart1\pnindent720\pnhang 
{\pntxta .}}{\*\pnseclvl4\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxta )}}{\*\pnseclvl5\pndec\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl6\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl7
\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl8\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl9\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}\pard\plain \ltrpar
\qc \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid1596967 \rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \ai\af369\afs18 \rtlch 
\i\f325\fs18\lang1065\insrsid1596967\charrsid1596967 \'c8\'d3\'e3\'e5 \'ca\'da\'c7\'e1\'ed}{\rtlch \ai\af325\afs18\alang1065 \ltrch \i\f369\fs18\insrsid1596967\charrsid1596967 
\par }\pard \ltrpar\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid4275875 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid12322038\charrsid1596967 \'dd\'d1\'e3 \'d4\'e3\'c7\'cf\'e5 16 \'ca\'c7\'ed\'ed\'cf \'90\'d2\'c7
\'d1\'d4 \'e3\'cc\'d1\'ed}{\rtlch \af325\afs18 \ltrch \fs18\insrsid4275875\charrsid1596967 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid1596967 {\ltrch \ab\ai\afs18 \rtlch 
\b\i\f325\fs18\lang1065\insrsid1596967\charrsid1596967 \'dd\'d1\'e3 \'ca\'c7\'ed\'ed\'cf \'90\'d2\'c7\'d1\'d4\'c7\'ca \'d8\'d1\'cd \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed}{\ltrch \ab\ai\afs18 \rtlch \b\i\shad\f325\fs18\lang1025\insrsid1596967\charrsid1596967 

\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'c7\'e1\'dd)}{\rtlch \ab\af325\afs18 \ltrch 
\b\fs18\insrsid4275875\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid9071482 {\ltrch \ab\afs18 
\rtlch \b\f325\fs18\lang1025\insrsid6172469\charrsid1596967 \'e3\'cf\'ed\'d1\'ed\'ca \'e3\'cd\'ca\'d1\'e3 \'c7\'e3\'e6\'d1 \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5}{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid4275875\charrsid1596967 

\par }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid3411897\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid9071482 {\ltrch 
\afs18 \rtlch \f325\fs18\lang1025\insrsid6172469\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid10687743 {
\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid9071482\charrsid1596967 \'c7\'cd\'ca\'d1\'e3\'c7\'f0 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid6172469\charrsid1596967 \'cf\'d1 \'ce\'d5\'e6\'d5 }{\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid8203564\charrsid1596967 \'d8\'d1\'cd}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid6172469\charrsid1596967  \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed \'d4\'e3\'c7\'d1\'e5 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $cod_tarh; ?>}{
\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid4666352\charrsid1596967   \'ca\'cd\'ca \'da\'e4\'e6\'c7\'e4 :}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid6172469\charrsid1596967 
\par }\pard \rtlpar\qj \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid11810295 {
\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? $tarh_name=str_replace("&#61537;",".",$tarh_name); $tarh_name=str_replace("&#61543;",".",$tarh_name); $tarh_name=str_replace("&#61541;",".",$tarh_name); $tarh_name=str_replace("&#1740;","ي",$tarh_name); $tarh_name=str_replace("&#1740","ي",$tarh_name);  echo $tarh_name; ?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid4666352\charrsid1596967 
\par }\pard\plain \rtlpar\qj \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid10687743\yts21 
\rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967 \'c8}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid2298299\charrsid1596967 \'e5 \'c7
\'d3\'ca\'cd\'d6\'c7\'d1}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967  \'e3\'ed\'d1\'d3\'c7\'e4\'cf}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid7603830\charrsid1596967  \'90\'d2\'c7\'d1\'d4}{\ltrch \afs18 \rtlch 
\f325\fs18\lang1065\insrsid2298299\charrsid1596967  }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid7603830\charrsid1596967 \'e3\'cc\'d1\'ed \'cf\'d1}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid2298299\charrsid1596967 \'c7\'ed\'e4 \'e3\'d1\'cd\'e1
\'e5 }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid7603830\charrsid1596967 \'e3\'e4\'c7\'d3\'c8 \'e6 \'c7\'d2 \'e4\'d9\'d1 \'c7\'cc\'d1\'c7\'ed\'ed \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf }{\ltrch \afs18 \rtlch 
\f325\fs18\lang1065\insrsid2298299\charrsid1596967 \'e4\'c7\'d9\'d1}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid1320478\charrsid1596967 /\'df\'c7\'d1\'d4\'e4\'c7\'d3}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid2298299\charrsid1596967  \'e3\'cd
\'ca\'d1\'e3}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13704766\charrsid1596967  \'d8\'d1\'cd}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid2298299\charrsid1596967  }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967 \'c2
\'de\'c7/\'ce\'c7\'e4\'e3 }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid10687743 <? echo $namer_name ;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967  }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid7603830\charrsid1596967 \'de\'d1\'c7\'d1 
\'90\'d1\'dd\'ca\'e5 \'c7\'d3\'ca.}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'c7\'ed\'e4\'df\'e5 \'cf\'d1 \'c7\'ed\'e4 \'ce\'d5\'e6\'d5 \'e3\'d1\'c7\'ca\'c8 \'e3\'e6\'d1\'cf \'ca\'c7\'ed
\'ed\'cf \'df\'c7\'d1\'d4\'e4\'c7\'d3\'ed }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13517271\charrsid1596967 \'e4\'ed\'d2}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid13004894\charrsid1596967 \'e3\'ed \'c8\'c7\'d4\'cf\'a1 \'ce\'e6\'c7\'e5\'d4
\'e3\'e4\'cf \'c7\'d3\'ca \'cf\'d1 \'d5\'e6\'d1\'ca \'d5\'e1\'c7\'cd\'cf\'ed\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'ed\'e4 \'90\'d2\'c7\'d1\'d4 \'d1\'c7 \'c7\'da\'e1\'c7\'e3 \'e6 \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'ed\'90\'ed\'d1\'ed \'c7\'e3\'e6\'d1 \'c7\'cf\'c7\'d1
\'ed \'e6 \'e3\'c7\'e1\'ed  \'cf\'d3\'ca\'e6\'d1 \'e1\'c7\'d2\'e3 \'d5\'c7\'cf\'d1 \'dd\'d1\'e3\'c7\'ed\'ed\'cf.
\par }\pard\plain \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid9071482 
\rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14882516\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid1731732 {\ltrch \ab\afs18 
\rtlch \b\f325\fs18\lang1025\insrsid14882516\charrsid1596967              }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid3866852\charrsid1596967 \'df\'c7\'d1\'d4\'e4\'c7\'d3 }{\ltrch \ab\afs18 \rtlch 
\b\f325\fs18\lang1025\insrsid1731732\charrsid1596967 \'e3\'d1\'c8\'e6\'d8\'e5}{\rtlch \ab\af325\afs18 \ltrch \b\fs18\insrsid6777836\charrsid1596967   }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid6777836\charrsid1596967 
                                                                    \'e3\'da\'c7\'e6\'e4 \'e3\'cf\'ed\'d1 \'81\'8e\zwj\'e6\'e5\'d4\'ed 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx703\tx5914\tx6309\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid9071482 {\ltrch 
\afs18 \rtlch \f325\fs18\lang1025\insrsid6777836\charrsid1596967 \tab }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14882516\charrsid1596967 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14882516\charrsid1596967 \tab }{
\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14882516\charrsid1596967 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14882516\charrsid1596967 \tab }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid3866852\charrsid1596967 

\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid9071482 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid4666352\charrsid1596967  }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid993911\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'c8)
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid6433222 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid6388501\charrsid1596967 \'e3\'da\'c7\'e6\'e4\'ca \'e3\'cd\'ca\'d1\'e3 \'c7\'e3\'e6\'d1 \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid5526691\charrsid1596967 
\par }\pard\plain \rtlpar\qj \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid5654532\yts21 
\rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid14551136\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid6388501\charrsid1596967 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf \'dd\'e6\'de }{\ltrch \afs18 \rtlch 
\f325\fs18\lang1065\insrsid1653055\charrsid1596967 \'90\'d2\'c7\'d1\'d4 \'c7\'d1\'c7\'c6\'e5 \'d4\'cf\'e5 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'e3\'ed\'c8\'c7\'d4\'cf. \'e1\'d0\'c7 \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'e4\'d3\'c8\'ca \'c8\'e5 
\'d5\'cf\'e6\'d1 \'cf\'d3\'ca\'e6\'d1 \'e1\'c7\'d2\'e3 \'c8\'d1\'c7\'ed \'c7\'cf\'c7\'e3\'e5 \'da\'e3\'e1\'ed\'c7\'ca \'c7\'cf\'c7\'d1\'ed \'c7\'de\'cf\'c7\'e3 \'e1\'c7\'d2\'e3 \'e3\'c8\'d0\'e6\'e1 \'dd\'d1\'e3\'c7\'c6\'ed\'cf.
\par }\pard\plain \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid6433222 \rtlch 
\af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14745748\charrsid1596967 
                                                                                                                                                                                                                                                 }{\ltrch 
\ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid6388501\charrsid1596967 \'e3\'cf\'ed\'d1\'ed\'ca \'c7\'e3\'e6\'d1 \'81\zwj\'8e\'e6\'e5\'d4\'ed
\par }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid14745748\charrsid1596967                                                                                                 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid14745748\charrsid1596967 
  
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'cc)}{\rtlch \ab\af325\afs18 \ltrch 
\b\fs18\insrsid2579700\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid6571741 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'d1\'81}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid2435314\charrsid1596967 \'d1}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'ca \'e3\'cd\'ca\'d1\'e3 \'cd\'d3
\'c7\'c8\'cf\'c7\'d1\'ed \'e3\'da\'c7\'e6\'e4\'ca \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid5526691\charrsid1596967 
\par }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid12406067\charrsid1596967 
\par }\pard\plain \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid6571741\yts21 \rtlch 
\af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11013323\charrsid1596967 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4
\'cf\'e5\'c7\'ed}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid15083196\charrsid1596967  "}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11013323\charrsid1596967 \'c7\'e1\'dd \'e6 \'c8}{\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid15083196\charrsid1596967 " }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11013323\charrsid1596967  \'e3\'d1\'c7\'ca\'c8 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'d3\'ca.}{\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid15993592\charrsid1596967  }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid6571741\charrsid1596967 \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7\'ce\'ca \'c7\'de\'d3\'c7\'d8 \'e3\'d1\'c8\'e6\'d8\'e5 \'c7\'de\'cf\'c7\'e3 \'e4\'e3
\'c7\'ed\'ed\'cf.}{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid6571741\charrsid1596967 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid6571741\yts21 {\ltrch \ab\afs18 
\rtlch \b\f325\fs18\lang1025\insrsid6425265\charrsid1596967                                                                                  }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid6571741\charrsid1596967 \'e3\'da\'c7\'e6\'e4 \'81\'8e\'e6
\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5
\par }

\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid16656259\yts21 {\ltrch \ab\afs18 
\rtlch \b\f325\fs18\lang1025\insrsid6425265\charrsid1596967                                                                                     }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid6884977\charrsid1596967 \'cf\'df\'ca\'d1 \'c7\'df\'c8
\'d1 \'dd\'ca\'e6\'cd\'ed}{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid7812013\charrsid1596967 
\par {\listtext\pard\plain\rtlpar \rtlch \af325\afs18 \ltrch \f3\fs18\insrsid7812013\charrsid1596967 \loch\af3\dbch\af0\hich\f3 \'b7\tab}}\pard \rtlpar\qr \fi-360\li0\ri720\widctlpar
\jclisttab\tx720\aspalpha\aspnum\faauto\ls2\adjustright\rin0\lin720\itap0\pararsid14114560\yts21 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid7812013\charrsid1596967 <? echo "رونوشت   : خانم نوروز زاده جهت درج در بانك اطلاعاتي";?>}{\rtlch \af325\afs18 \ltrch \fs18\insrsid16656259 
\par }






\pard \rtlpar\qr \li0\ri360\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin360\itap0\pararsid11147431\yts21 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431 
\par }\pard\plain \ltrpar\qc \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 \rtlch \af0\afs24\alang1025 \ltrch \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431 \page }{\ltrch \ai\af369\afs18 \rtlch \i\f325\fs18\lang1065\insrsid11147431\charrsid11670919 \'c8\'d3\'e3\'e5 \'ca\'da\'c7\'e1\'ed}{\rtlch \ai\af325\afs18\alang1065 \ltrch \i\fs18\insrsid11147431\charrsid11670919 

\par }\pard \ltrpar\ql \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch \f325\fs18\cf1\lang1025\insrsid11147431\charrsid11670919 \'dd\'d1\'e3 \'d4\'e3\'c7\'d1\'e5 17/2 \'cf\'d3\'ca\'e6\'d1\'81\'d1\'cf
\'c7\'ce\'ca \'c7\'de\'d3\'c7\'d8}{\rtlch \af325\afs18\alang1065 \ltrch \fs18\cf1\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qc \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch \b\shad\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'dd\'d1\'e3 \'81\'d1\'cf\'c7\'ce\'ca \'c7\'de\'d3\'c7\'d8 \'de
\'d1\'c7\'d1\'cf\'c7\'cf }{\ltrch \ab\afs18 \rtlch \b\shad\f325\fs18\lang1065\insrsid11147431\charrsid11670919 \'d8\'d1\'cd}{\ltrch \ab\afs18 \rtlch \b\shad\f325\fs18\lang1025\insrsid11147431\charrsid11670919  \'e5\'c7\'ed \'81\zwj\zwj\'8e\'e6\'e5\'d4\'ed
}{\rtlch \af325\afs18 \ltrch \fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'e4\'cf \'c7\'e1\'dd)}{\rtlch \ab\af325\afs18 \ltrch 
\b\fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch 
\b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'e3\'cf\'ed\'d1\'ed\'ca \'e3\'cd\'ca\'d1\'e3 \'c7\'e3\'e6\'d1 \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5}{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid11147431\charrsid11670919 

\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid10687743 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'ca\'e4 \'de\'d1\'c7\'d1\'cf\'c7\'cf \'e3\'e4\'da\'de\'cf\'e5 \'c8\'c7 \'c2\'de\'c7 / \'ce\'c7\'e4\'e3 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 
<? echo $name_family." (  شماره حساب "."$shomare_hesab"." ) ";?> }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919  \'c8\'e5 \'d4\'e3\'c7\'d1\'e5 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743                   }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919  \'cf
\'d1 \'ce\'d5\'e6\'d5 \'d8\'d1\'cd \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed \'d4\'e3\'c7\'d1\'e5 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $cod_tarh;?> }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919   \'ca\'cd\'ca \'da\'e4\'e6
\'c7\'e4 :
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid10687743 <? echo $tarh_name;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid10687743 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'cf\'d1 \'d5\'e6\'d1\'ca \'d5\'e1\'c7\'cd\'cf\'ed\'cf \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7\'ce\'ca \'e3\'c8\'e1\'db}{\ltrch \afs18 \rtlch
<?
 
if($cod_marhale==0)
{
	$mablagh=number_format($mablagh_marhale_0);
	$maliat=number_format($maliat_marhale_0);
	$khales=number_format($mablagh_khales_mojri_0);
	$mablagh_nazer=number_format($hagh_ol_zahme_karshenasi_0);
	$marhale=1;
	$name_karshenas=" دکتر شمشيري (شماره حساب   4462981172 )";
}
else
if($cod_marhale==100)
{
	$mablagh=number_format($mablagh_marhale_end);
 
	$maliat=number_format($maliat_marhale_end);
	$khales=number_format($mablagh_khales_mojri_end);
	$mablagh_nazer=number_format($hagh_ol_zahme_karshenasi_end);
	$marhale=" نهايي ";
	$name_karshenas=$name_family;
}
else
{

$name_karshenas=$name_family;
$query="select * from gozaresh_gharardad  where cod_tarh='$cod_tarh' and marhale!='0' and marhale!='100' and marhale='$cod_marhale' order by marhale asc ";
$result1=mysql_query($query) or die("Error");
$cntr=1;
$mablagh12=0;
while($rf66=mysql_fetch_array($result1))
{
// echo $cntr;
  if($hazine_personnel > $darsad_50)
  {
  	$mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
  	$nezarat=100000+$mablagh_marhale_n/100;
  	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
  	
	$maliat_marhale_n=$mablagh_marhale_n*$zarib_maliat/100;
	$hagh_ol_zahme_karshenasi_n=100000+($rf66["mablagh"]*$mablagh_aghd_gharardad/100)/100;
	$mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n;
	$mablagh_khales_mojri=$mablagh_khales_mojri-$hagh_ol_zahme_karshenasi_n;
	  		
  }
  else
  {
  	 $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
	 $mablagh_marhale_n=($darsad_marhale+(100000+($darsad_marhale/100)))*100/(100-$zarib_maliat);
	 $maliat_marhale_n=$mablagh_marhale_n*$zarib_maliat/100;
	 $hagh_ol_zahme_karshenasi_n=100000+($darsad_marhale/100);
	 
	 $mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n-$hagh_ol_zahme_karshenasi_n;
	 
  }
} 
	$mablagh=number_format($mablagh_marhale_n);
	$maliat=number_format($maliat_marhale_n);
	$khales=number_format($mablagh_khales_mojri);
	$mablagh_nazer=number_format($hagh_ol_zahme_karshenasi_n);
	$marhale=$cod_marhale;   
 }  	
 $mablagh_print=str_replace(",","",$mablagh);
?> 
\f325\fs18\lang1025\insrsid10687743 <? echo $mablagh;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919      \'d1\'ed\'c7\'e1 \'c7\'d2 \'c8\'e6\'cf\'cc\'e5 \'e3\'d5\'e6\'c8 \'d8\'d1\'cd \'c8\'e5 \'d4\'d1\'cd \'d2\'ed\'d1\'c7\'de\'cf\'c7\'e3 \'e3
\'de\'ca\'d6\'ed \'c8\'da\'e3\'e1 \'c2\'ed\'cf.
\par 1. \'e3\'c7\'e1\'ed\'c7\'ca \'c7\'ed\'e4 \'e3\'d1\'cd\'e1\'e5 \'a1 \'c8\'e5 \'e3\'ed\'d2\'c7\'e4  }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $maliat;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919     \'d1\'ed\'c7\'e1

\par 2.\'ce\'c7\'e1\'d5 \'81\'d1\'cf\'c7\'ce\'ca\'ed \'c8\'e5 \'e3\'cc\'d1\'ed\'a1  \'c2\'de\'c7 / \'ce\'c7\'e4\'e3 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743  <? echo $name_family;?> }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919   
\'c8\'e5 \'e3\'ed\'d2\'c7\'e4 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $khales;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919        \'d1\'ed\'c7\'e1 (}{\ltrch \afs18 \rtlch 
\f325\fs18\lang1065\insrsid11147431\charrsid11670919 \'90\'d2\'c7\'d1\'d4}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919  }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $marhale;?> }{\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 )
\par 3. \'ce\'c7\'e1\'d5 \'81\'d1\'cf\'c7\'ce\'ca\'ed \'c8\'e5 \'c2\'de\'c7 / \'ce\'c7\'e4\'e3 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $name_karshenas;?> }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919   \'c8\'da\'e4\'e6\'c7\'e4
 \'e4\'c7\'d9\'d1 / \'df\'c7\'d1\'d4\'e4\'c7\'d3 \'d8\'d1\'cd \'a1 \'c8\'e5 \'e3\'ed\'d2\'c7\'e4 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $mablagh_nazer;?>}{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919   \'d1\'ed\'c7\'e1

\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch 
\b\f325\fs18\lang1025\insrsid11147431\charrsid11670919              }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'df\'c7\'d1\'d4\'e4\'c7\'d3 }{\ltrch \ab\afs18 \rtlch 
\b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'e3\'d1\'c8\'e6\'d8\'e5 }{\rtlch \ab\af325\afs18 \ltrch \b\fs18\insrsid11147431\charrsid11670919   }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid11147431\charrsid11670919                    
                                            }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid11147431                                                         }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid11147431\charrsid11670919      \'e3
\'da\'c7\'e6\'e4 \'e3\'cf\'ed\'d1 \'81\'8e\zwj\'e6\'e5\'d4\'ed 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx703\tx5914\tx6309\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \tab }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 \tab }{\ltrch \afs18 
\rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 \tab }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919  
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'e4\'cf \'c8)
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'e3\'da\'c7\'e6\'e4\'ca \'e3\'cd\'ca\'d1\'e3 \'c7\'e3\'e6\'d1 \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5
\par \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid10687743 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf \'dd\'e6\'de \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7
\'ce\'ca \'e3\'c8\'e1\'db }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? echo $mablagh;?> }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919  \'d1\'ed\'c7\'e1 
\par ( \'c8\'e5 \'cd\'d1\'e6\'dd }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid10687743 <? $numper = new NumPer;$numper->Number =$mablagh_print;$numper->num2per($numper->Number);  echo " ريال  ";?>  }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 ) \'c8\'e5 \'d4\'d1\'cd \'dd\'e6\'de \'c7\'de\'cf\'c7\'e3 \'de\'c7\'e4\'e6\'e4\'ed \'e3
\'da\'e3\'e6\'e1 \'90\'d1\'cf\'cf.
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919                                                                                                                                                       
                                                                                           }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'e3\'cf\'ed\'d1\'ed\'ca \'c7\'e3\'e6\'d1 \'81\zwj\'8e\'e6\'e5\'d4\'ed
\par                                                                                                 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919
\par }{\rtlch \af325\afs18 \ltrch \fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'e4\'cf \'cc)}{\rtlch \ab\af325\afs18 \ltrch 
\b\fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid11147431 {\ltrch \afs18 \rtlch 
\f325\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'d1\'81\'d1\'d3\'ca \'e3\'cd\'ca\'d1\'e3 \'cd\'d3\'c7\'c8\'cf\'c7\'d1\'ed \'e3\'da\'c7\'e6\'e4\'ca \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5 
\par \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf\'e5\'c7\'ed "\'c7\'e1\'dd \'e6 \'c8"  \'e3\'d1\'c7\'ca\'c8 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'d3\'ca}{\ltrch \ab\afs18 \rtlch 
\b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 .                 
\par                                                                                                 }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1065\insrsid11147431                                                                                   }{\ltrch 
\ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919         \'e3\'da\'c7\'e6\'e4 \'81\'8e\'e6\'e5\'d4\'ed \'cf\'c7\'e4\'d4\'90\'c7\'e5
\par }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919                                                                                              }{\ltrch \afs18 \rtlch \f325\fs18\lang1065\insrsid11147431 
                                                                                 }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919                 }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid11147431\charrsid11670919 
\'cf\'df\'ca\'d1 \'c7\'df\'c8\'d1 \'dd\'ca\'e6\'cd\'ed
\par }{\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid11147431\charrsid11670919 
\par 
\par {\listtext\pard\plain\rtlpar \rtlch \af325\afs18 \ltrch \f3\fs18\insrsid11147431\charrsid11670919 \loch\af3\dbch\af0\hich\f3 \'b7\tab}}


\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \aspalpha\aspnum\faauto\adjustright\rin0\lin0\rtlgutter\itap0\pararsid16656259\yts21 {\ltrch \ab\afs18 
\rtlch \b\f325\fs18\lang1025\insrsid6425265\charrsid1596967                                                                                     }{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid6884977\charrsid1596967 \'cf\'df\'ca\'d1 \'c7\'df\'c8
\'d1 \'dd\'ca\'e6\'cd\'ed}{\ltrch \ab\afs18 \rtlch \b\f325\fs18\lang1025\insrsid7812013\charrsid1596967 
\par {\listtext\pard\plain\rtlpar \rtlch \af325\afs18 \ltrch \f3\fs18\insrsid7812013\charrsid1596967 \loch\af3\dbch\af0\hich\f3 \'b7\tab}}\pard \rtlpar\qr \fi-360\li0\ri720\widctlpar
\jclisttab\tx720\aspalpha\aspnum\faauto\ls2\adjustright\rin0\lin720\itap0\pararsid14114560\yts21 {\ltrch \afs18 \rtlch \f325\fs18\lang1025\insrsid7812013\charrsid1596967 <? echo "رونوشت   : خانم نوروز زاده جهت درج در بانك اطلاعاتي";?>}{\rtlch \af325\afs18 \ltrch \fs18\insrsid16656259 
\par }}