<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/vars.inc.phtml");

if(isset($action) )
if(strcmp($action,"save")==0)
{

   $comments=trim(iconv("windows-1256","utf-8",$comments));
    $markaz_type=trim(iconv("windows-1256","utf-8",$markaz_type));
     $emtiaz=trim(iconv("windows-1256","utf-8",$emtiaz));
      $maghale_class=trim(iconv("windows-1256","utf-8",$maghale_class));
      $maghale_darad_nadarad=trim(iconv("windows-1256","utf-8",$maghale_darad_nadarad));
      $vaziat_tarh=trim(iconv("windows-1256","utf-8",$vaziat_tarh));
      $modir_ejrayee_name=trim(iconv("windows-1256","utf-8",$modir_ejrayee_name));
      $modir_ejrayee_family=trim(iconv("windows-1256","utf-8",$modir_ejrayee_family));
      $daneshkade=trim(iconv("windows-1256","utf-8",$daneshkade));
      $start_date=trim(iconv("windows-1256","utf-8",$start_date));
      $year_start=trim(iconv("windows-1256","utf-8",$year_start));
       $month_start=trim(iconv("windows-1256","utf-8",$month_start));
      $start_day=trim(iconv("windows-1256","utf-8",$start_day));
      $end_date=trim(iconv("windows-1256","utf-8",$end_date));
      $end_year=trim(iconv("windows-1256","utf-8",$end_year));
      $end_month=trim(iconv("windows-1256","utf-8",$end_month));
      $end_day=trim(iconv("windows-1256","utf-8",$end_day));
      $read_end_date=trim(iconv("windows-1256","utf-8",$read_end_date));
      $real_end_year=trim(iconv("windows-1256","utf-8",$real_end_year));
      $real_end_month=trim(iconv("windows-1256","utf-8",$real_end_month));
      $real_end_day=trim(iconv("windows-1256","utf-8",$real_end_day));
      $mablagh_kasr=trim(iconv("windows-1256","utf-8",$mablagh_kasr));
      $budject=trim(iconv("windows-1256","utf-8",$budject));
	  $q="select * from   tarh_old_desc where cod_tarh='$cod_tarh'"; 
$rssss=mysql_query($q) or die("error");
if(mysql_num_rows($rssss) > 0)
{
       $q="update   tarh_old_desc set      comments='$comments',markaz_type='$markaz_type',emtiaz='$emtiaz',maghale_class='$maghale_class',maghale_darad_nadarad='$maghale_darad_nadarad',   vaziat_tarh='$vaziat_tarh',modir_ejrayee_name='$modir_ejrayee_name',modir_ejrayee_family='$modir_ejrayee_family',daneshkade='$daneshkade',start_date='$start_date',year_start='$year_start',month_start='$month_start',end_year='$end_year',end_month='$end_month',end_day='$end_day',start_day='$start_day',end_date='$end_date',read_end_date='$read_end_date', real_end_year='$real_end_year',real_end_month='$real_end_month',real_end_day='$real_end_day' ,mablagh_kasr='$mablagh_kasr',budject='$budject'  where cod_tarh='$cod_tarh'";
	  

}
else
{
       $q="insert into   tarh_old_desc set      comments='$comments',markaz_type='$markaz_type',emtiaz='$emtiaz',maghale_class='$maghale_class',maghale_darad_nadarad='$maghale_darad_nadarad',   vaziat_tarh='$vaziat_tarh',modir_ejrayee_name='$modir_ejrayee_name',modir_ejrayee_family='$modir_ejrayee_family',daneshkade='$daneshkade',start_date='$start_date',year_start='$year_start',month_start='$month_start',end_year='$end_year',end_month='$end_month',end_day='$end_day',start_day='$start_day',end_date='$end_date',read_end_date='$read_end_date', real_end_year='$real_end_year',real_end_month='$real_end_month',real_end_day='$real_end_day' ,mablagh_kasr='$mablagh_kasr',budject='$budject'  , cod_tarh='$cod_tarh'";
 
}	  
	   $q=mysql_query($q) or die("errorm 100");

	  $q1= "update   tarh_old  set cod_daneshkade='$cod_daneshkade' where cod_tarh='$cod_tarh' ";
	   $q1=mysql_query($q1) or die("errorm 100");


           ?>
           <script language="javascript">
           window.location="<? echo "old_tarhs.phtml?admin=$admin&seed=$seed&cod_tarh=$max_cod";  ?>";
           </script>
           <?


}
$q="select * from tarh_old_desc  where cod_tarh='$cod_tarh'";
 echo "<br><br><span class='tahoma1' bgcolor='#f6f6f6'> جزئيات طرح</span><br>";
$rs=mysql_query($q) or die("error");

$rf=mysql_fetch_array($rs);
 ?>
 <? echo "<form name=\"add-tarh\" method=\"post\"  action=\"old_tarh_edit.phtml?action=save&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

 			<table class="tahoma1">
				<tbody>
					<tr>
						
						<td width="80%"  align='right' dir='rtl'><input type="	text"  name='comments'  class="edit-user"  dir=RTL    value='<?  echo trim(iconv("utf-8","windows-1256",trim($rf["comments"])));?>'  />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								توضيحات
							</label>
						</td>
					</tr>
                    
                    <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text"  name='markaz_type'  class="edit-user"  dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",trim($rf["markaz_type"])));?> ' />

 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								نوع مرکز
							</label>
						</td>
					</tr>

                    <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text" align='right'  name='emtiaz' class="edit-user"   dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",trim($rf["emtiaz"])));?> ' />

 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								امتياز
							</label>
						</td>
					</tr>
                    
                            <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text"   class="edit-user" name='maghale_class'  dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",trim($rf["maghale_class"])));?> ' />
 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								کلاس مقاله
							</label>
						</td>
					</tr>

                            <tr>	
                            <?  
							  $maghale_Desc= trim(iconv("utf-8","windows-1256",$rf["maghale_darad_nadarad"]));
						 
							?>					
						<td width="80%"  align='right' dir='rtl'><select size="1"    name="maghale_darad_nadarad" class="edit-user" dir="rtl">
                   
                    <?
                        if(strcmp(trim($maghale_Desc),"مقاله ندارد")==0)
						  $selected=" selected ";
                       else
					      $selected="";
						?>

     <option <?  echo $selected ; ?> value="مقاله ندارد" class="tahoma1">مقاله ندارد</option>

                        <?
                        if(strcmp(trim($maghale_Desc),"مقاله دارد")==0)
						  $selected=" selected ";
                       else
					      $selected="";
						?>
    <option  <?  echo $selected ; ?> value="مقاله دارد" class="tahoma1">مقاله دارد</option>

                        <?
                        if(strcmp(trim($maghale_Desc),"نياز ندارد")==0)
						  $selected=" selected ";
                       else
					      $selected="";
						?>

       <option <?  echo $selected ; ?> value="نياز ندارد" class="tahoma1">نياز ندارد</option>
                     </select>
                       
 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								آيا طرح مقاله دارد ؟
							</label>
						</td>
					</tr>

                            <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text"   class="edit-user"   name='vaziat_tarh'  dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",$rf["vaziat_tarh"]));?>' />
 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								وضعيت طرح
							</label>
						</td>
					</tr>

                       

                            <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text"   class="edit-user"   name='modir_ejrayee_name'  dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",$rf["modir_ejrayee_name"]));?>' />

 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								نام مدير اجرايي
							</label>
						</td>
					</tr>

                            <tr>						
						<td width="80%"  align='right' dir='rtl'><input type="	text"   class="edit-user" name='modir_ejrayee_family'  dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",$rf["modir_ejrayee_family"]));?>  ' />
 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								نام خانوادگي مدير اجرايي
							</label>
						</td>
					</tr>




<tr>
  <?
  
  $q="select * from tarh_old  where cod_tarh='$cod_tarh'";
 $rs=mysql_query($q) or die("error");

$rf_old=mysql_fetch_array($rs);

    $query="select * from daneshkade order by daneshkade_name  ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
    $groupcount = mysql_num_rows($qresult);
  ?>
    <td width="80%" align="right"><select size="1"    name="cod_daneshkade" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?
echo $rf["cod_daneshkade"];
    while($row_fetched=mysql_fetch_array($qresult))
    {
	    if(strcmp(trim($rf_old["cod_daneshkade"]),trim($row_fetched["cod_daneshkade"]))==0)
		  $selected=" selected "; 
		else
		   $selected="  ";  
         echo "<option  $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
    }
    ?>
    </select>
	  
  
	</td>
   <td width="20%" class="tahoma1" bgcolor='#f6f6f6'> دانشکده </td>
  </tr>
   

                            <tr>						
						<td width="80%"  align='right' dir='rtl'  ><input type="	text"   class="edit-user"   name='daneshkade'   dir=RTL    value='	<?  echo trim(iconv("utf-8","windows-1256",$rf["daneshkade"]));?>' />

 						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								نام دانشکده
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%" align='right'  ><input type="	text"   class="edit-user"   name='start_date'  dir=RTL    value='	<?  echo trim($rf["start_date"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								تاريخ شروع
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"  name='year_start'   dir=RTL    value='	<?  echo trim($rf["year_start"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								سال شروع
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"  name='month_start'    dir=RTL    value='	<?  echo trim($rf["month_start"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								ماه شروع
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"  name='start_day'   dir=RTL    value='	<?  echo trim($rf["start_day"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								روز شروع
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right' ><input type="	text"   class="edit-user"  name='end_date'    dir=RTL    value='	<?  echo trim($rf["end_date"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								تاريخ پايان
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"   name='end_year'   dir=RTL    value='	<?  echo trim($rf["end_year"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								سال پايان
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"    name='end_month'   dir=RTL    value='	<?  echo trim($rf["end_month"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								ماه پايان
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user" name='end_day'   dir=RTL    value='	<?  echo trim($rf["end_day"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								روز پايان
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right' ><input type="	text"   class="edit-user"  name='read_end_date'   dir=RTL    value='	<?  echo trim($rf["read_end_date"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								تاريخ واقعي پايان طرح
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user"  name='real_end_year'   dir=RTL    value='<?  echo trim($rf["real_end_year"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								سال واقعي پايان طرح
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'  ><input type="	text"   class="edit-user" name='real_end_month'   dir=RTL    value='<?  echo trim($rf["real_end_month"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								ماه واقعي پايان طرح
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'><input type="	text"   class="edit-user"  name='real_end_day' dir=RTL    value='<?  echo trim($rf["real_end_day"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								روز واقعي پايان طرح
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'><input type="	text"   class="edit-user" name='mablagh_kasr'   dir=RTL    value='<?  echo trim($rf["mablagh_kasr"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
							مبلغ کسر پرداخت
							</label>
						</td>
					</tr>
                            <tr>						
						<td width="80%"  align='right'><input type="	text"   class="edit-user" name='budject'   dir=RTL    value='<?  echo trim($rf["budject"]);?>' />
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								بودجه طرح
							</label>
						</td>
					</tr>
                    
                              <tr>						
						<td width="80%"  align='right'>
							 <?  
							 $f_name_jpg="../tasvir_maghalat/".$cod_tarh.".jpg";
							 $f_name_zip="../tasvir_maghalat/".$cod_tarh.".zip";
							 if( file_exists($f_name_jpg))
							    echo "<a href='$f_name_jpg' target='_blank'>".$cod_tarh.".jpg"."</a>";
							 if( file_exists($f_name_zip))
						        echo "<a href='$f_name_zip' target='_blank'>".$cod_tarh.".zip"."</a>";

							 ?>
						</td>
                        <td width="20%" class="tahoma1" bgcolor='#f6f6f6'>
							<label for="name">
								مقاله طرح
							</label>
						</td>
					</tr>
                         
                        <td width="100%" class="tahoma1" bgcolor='#f6f6f6' colspan='2'>
							<p align="center"><input class="but-tarh-type" type="submit" value="ارسال" name="submit_tarh"></p>
						</td>
					</tr>
 
</tbody> 

</table>
</form>
<?
footer_forms($admin,$seed);


?>
