<?
include("include/database-connect.phtml");
include("include/include.phtml");
//require("include/class.phpmailer.php");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/vars.inc.phtml");
require("include/class.smtp.php");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");
//require_once('lib/nusoap.php');
//include("include/print.phtml");
//require("include/mailserver-statistics.phtml");
include ("../sms/include/WebServiceSms.php");
include ("../sms/send_long_sms.php");
  if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
     

if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
if(isset($action))
{
  $i=0;
  if (strcmp($action,"send_karshenas")==0)
  {
   for($i==0;$i<330;$i++)
   {
    $myvariable="check".$i;
    $myvariable2="send_comment".$i;
    $myuser="value_".$i;
    if (isset($$myvariable))
    {
      $myvariable="check".$i;
      $myuser="value_".$i;
      $mycodkarshenas = "cod_karshenas_".$i;
      $myname_family="name_".$i;
      $send_comment_add="g".$i;
         $send_comment=$$$send_comment_add;
	 //$send_comment="send_comment_".$i;

	 // $i++;

	  $query="select * from karshenasan_tarh where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	  $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh 1");
	  if ( mysql_num_rows($result)==0 )
	  {
	  	$query="select * from karshenasan where  cod_karshenas=\"".$$mycodkarshenas."\"";
	     $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh 6666 6 6 6 ");
	
	  		$row_fetch_email=mysql_fetch_array($result);
	  	$query="insert into karshenasan_tarh set     send_to_karshenas_date='".date("Y-m-d")."'  ,cod_tarh=\"$cod_tarh\" , cod_karshenas=\"".$$mycodkarshenas."\",send_comment='$send_comment'";
 	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh 565656");
	    
	  
	  	$karshenas_email=$row_fetch_email["karshenas_email"]; 
	  	$familye=$row_fetch_email["karshenas_family"];
	  	$mobile=$row_fetch_email["mobile"];

	  	$query_karshenas="select * from group_karshenasan where username='$admin' ";
		$result_k=mysql_query($query_karshenas) or die("Error in selecting data from karshenas_elmi_tarh 1");
	  	$row_fetch_k=mysql_fetch_array($result_k);
	  	$username_k=$row_fetch_k["username"];
	  	$mobile_k=$row_fetch_k["mobile"];
	    
	     $mail = new PHPMailer();
    $emailbody="";
    $emailbody=$emailbody."<br><b>You got a proposal <b><br><br>";
    $emailbody=$emailbody."<br>Please login to your judgement area and check it.(Two Weeks Deadline)<br>";
    $emailbody=$emailbody."<br>You can find it in this menu item ==> 'TARH-HAYE-JADID'<br>";
    $emailbody=$emailbody."<br>Tarh Code is : $cod_tarh<br>";
	$emailbody=$emailbody."<br>Expert : $username_k<br>";
	$emailbody=$emailbody."<br>Tell : $mobile_k<br>";
    $emailbody=$emailbody."<br>Please login at: <a href=".$url_address."/login/>Here</a>";
    $emailbody=$emailbody."<center><font face=Arial size=2 color=green>This email has been sent by <a href=\"".$url_address."\">".$url_address."</a>";
    $emailbody=$emailbody."<br>Powered by Peyvand Co. (Peyvandco.com).</font></center>";

    $mail->IsSMTP();                                      // set mailer to use SMTP
    $mail->SMTPAuth=$smtpauth;
    $mail->Username=$email_username;
    $mail->Password=$email_password;
    $mail->WordWrap = 50;  // set word wrap to 50 characters 

    $mail->AddReplyTo($email_from,$email_from_name);
	                                      // set mailer to use SMTP
	$mail->host = $mailserver_host;  // specify main and backup server
    $mailname=$familye;
    $mail->From = $email_from;
	$mail->FromName = $email_from_name;
    $mail->AddAddress($karshenas_email, $mailname);
    $mail->IsHTML(true);                                  // set email format to HTML

    $mail->Subject = "Check your box in $url_address (Do not reply this email)";
    $mail->Body    = $emailbody;
    $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
    if(!$mail->Send())
    {
        $status="mail_err";
    }
    
    
    //send_sms($mobile,"tarh ba code $cod_tarh jahate karshenasi/davari be mohit davari/nezarat shoma ersal shode (mohlate zamani 2 hafte). karshenas: $username_k,shomareye tamas: $mobile_k http://research.tums.ac.ir");
	  $message_string="پژوهشيار: طرح با کد $cod_tarh به محيط داوري شما ارسال گرديده است.لطفا طرح را مورد ارزيابي قرار دهيد. research.tums.ac.ir";
		//$message_string=iconv("windows-1256", "UTF-8",$message_string);
		$subject="ارسال طرح جهت داوري";
		$massage_id=send_long_sms($message_string,$mobile,$subject);  
	    
	    
	    
	  }
	else
	  {
	


         $query="select * from karshenasan where  cod_karshenas=\"".$$mycodkarshenas."\"";
	     $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh 3");
	
		$row_fetch_email=mysql_fetch_array($result);
 	
 $query="update karshenasan_tarh set send_to_karshenas_date='".date("Y-m-d")."' ,refered ='0',send_comment='$send_comment' where  cod_tarh=\"$cod_tarh\" and  cod_karshenas=\"".$$mycodkarshenas."\"  ";
//	    echo $query;

	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh 554545");
  
	  
	  	$karshenas_email=$row_fetch_email["karshenas_email"]; 
	  	$familye=$row_fetch_email["karshenas_family"];
	    	$mobile=$row_fetch_email["mobile"];
	    
	    
	$query_karshenas="select * from group_karshenasan where username='$admin' ";
	$result_k=mysql_query($query_karshenas) or die("Error in selecting data from karshenas_elmi_tarh 1");
  	$row_fetch_k=mysql_fetch_array($result_k);
  	$username_k=$row_fetch_k["username"];
  	$mobile_k=$row_fetch_k["mobile"];
  	
	     $mail = new PHPMailer();
    $emailbody="";
    $emailbody=$emailbody."<br><b>You got a proposal <b><br><br>";
    $emailbody=$emailbody."<br>Please login to your judgement area and check it.(Two Weeks Deadline)<br>";
    $emailbody=$emailbody."<br>You can find it in this menu item ==> 'TARH-HAYE-JADID'<br>";
    $emailbody=$emailbody."<br>Tarh Code is : $cod_tarh<br>";
	$emailbody=$emailbody."<br>Expert : $username_k<br>";
	$emailbody=$emailbody."<br>Tell : $mobile_k<br>";
    $emailbody=$emailbody."<br>Please login at: <a href=".$url_address."/login/>Here</a>";
    $emailbody=$emailbody."<center><font face=Arial size=2 color=green>This email has been sent by <a href=\"".$url_address."\">".$url_address."</a>";
    $emailbody=$emailbody."<br>Powered by Peyvand Co. (Peyvandco.com).</font></center>";

    $mail->IsSMTP();                                      // set mailer to use SMTP
    $mail->SMTPAuth=$smtpauth;
    $mail->Username=$email_username;
    $mail->Password=$email_password;
    $mail->WordWrap = 50;  // set word wrap to 50 characters 

    $mail->AddReplyTo($email_from,$email_from_name);
	                                      // set mailer to use SMTP
	$mail->host = $mailserver_host;  // specify main and backup server
    $mailname=$familye;
    $mail->From = $email_from;
	$mail->FromName = $email_from_name;
    $mail->AddAddress($karshenas_email, $mailname);
    $mail->IsHTML(true);                                  // set email format to HTML

    $mail->Subject = "Check your box in $url_address (Do not reply this email)";
    $mail->Body    = $emailbody;
    $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
    if(!$mail->Send())
    {
        $status="mail_err";
    }
    
    
    
    //send_sms($mobile,"tarh ba code $cod_tarh jahate karshenasi/davari be mohit davari/nezarat shoma ersal shode (mohlate zamani 2 hafte). karshenas: $username_k,shomareye tamas: $mobile_k http://research.tums.ac.ir");
	$message_string="پژوهشيار: طرح با کد $cod_tarh به محيط داوري شما ارسال گرديده است.لطفا طرح را مورد ارزيابي قرار دهيد. research.tums.ac.ir";
		//$message_string=iconv("windows-1256", "UTF-8",$message_string);
		$subject="ارسال طرح جهت داوري";
		$massage_id=send_long_sms($message_string,$mobile,$subject);
	    
	  }
    }
    
    
    
    
    
    
    
     $del_variable="del_check".$i;
    $myuser1="value_".$i;
    if (isset($$del_variable))
    {
      $del_variable="del_check".$i;
      $myuser="value_".$i;
      $mycodkarshenas = "cod_karshenas_".$i;
      $myname_family="name_".$i;
	 

	 // $i++;

	  $query="select * from karshenasan_tarh where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	  $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh 5");
	  if ( mysql_num_rows($result)>0 )
	  {
	    $query="delete from  karshenasan_tarh where  cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	    //echo $query;
	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh 6");
	  }
	 
    }
    
    
    $del_variable="lovely".$i;
    $myuser1="value_".$i;
   
  }

  }
}
   echo "<br>";
   
   
   if(isset($favorite_no_favorite) && strcmp($favorite_no_favorite,'-1') != 0)
   {
   	if(strcmp($favorite_no_favorite,'0') == 0)
   	 $favorite_rule=" and karshenasan.cod_karshenas in (select cod_karshenas from favirite_karshenas where user='$admin')";
   	else
	  if(strcmp($favorite_no_favorite,'1') == 0)
   	     $favorite_rule=" and karshenasan.cod_karshenas not in (select cod_karshenas from favirite_karshenas where user='$admin')";
   	   
   }
   else
     $favorite_rule="";
   
   if(isset($alaghe_type) && strcmp($alaghe_type,'-1') != 0)
     $search_string_1="(alaghe_type_list like '%$alaghe_type%' or alaghe_type_list like '%$alaghe_type%')  ";
   else
     $search_string_1="1";
     
   if(isset($name_e) && strlen($name_e) > 0)
     $search_string="(karshenas_name like '%$name_e%' or karshenas_family like '%$name_e%')  ";
   else
     $search_string="1 ";
   
   $query="select * from karshenasan,karshenas_type  where $search_string  and karshenasan.karshenas_type=karshenas_type.karshenas_type   order by karshenasan.karshenas_family asc"; 
   
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh 1 444");
   $reccount=mysql_num_rows($result);
   
   $query="select * from karshenasan,karshenas_type  where   $search_string and  karshenasan.karshenas_type=karshenas_type.karshenas_type  order by karshenasan.karshenas_family "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ; 
   
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh 2");

 
   if(mysql_num_rows($result) > 0)
   {
   	$myascdescpub=$myascdescpub."&name_e=$name_e&alaghe_type=$alaghe_type&favorite_no_favorite=$favorite_no_favorite&cod_tarh=$cod_tarh";
   	pubshowpages("send_karshenas.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
   // echo "<br>";

 
    ?>

    <table border="0" width="90%" cellpadding="1" cellspacing="1">
   <tr>
    <td width="100%" bgcolor="#66CCFF"  colspan="11">

      <p align="center" class="tahoma1"><font color="black"><b>ارسال به کارشناس</b></font></td>
    </tr>

      <tr>
    
  
     <?
   echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&alaghe_type=$alaghe_type&favirite_no_favorite=$favorite_no_favorite\">";
   ?>
 <td align="right" width="100%" bgcolor="#66CCFF"  colspan="12">
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL value='<? echo trim($name_e); ?>'  >
 </td>
 
 </tr>
 </form>
 <? echo "<form name=\"mojri_tarh_4\" method=\"post\" action=\"$PHP_SELF?action=send_karshenas&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&current=$current\">"; ?>

   
	<tr>
	<td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">توضيحات</font></td>
	
 
	 <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">باز پس گيري</font></td>
	 <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">ارسال</font></td>
	 <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح در دست ايشان</font></td>
 <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح داوري /نظارت شده</font></td>

    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">وضعيت ارسال</font></td>

    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">پست الکترونيکي</font></td>
   <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نوع کارشناس</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
        <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
    </tr>
  <?

 $color=$list_color_1;
  $i=0;
 while($row_fetched=mysql_fetch_array($result))
 {
 // $cod_tarh=$row_fetched["cod_tarh"];
  $cod_karshenas=$row_fetched["cod_karshenas"];
  $query="select * from karshenasan_tarh where cod_karshenas='$cod_karshenas' and cod_tarh='$cod_tarh'";
  $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas' and finished ='1'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh_karshenasi=$rf1["cnt"];
  
  $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh=$rf1["cnt"];
  $result1=mysql_query($query);
  $rf1=mysql_fetch_array($result1);
  $send_comment1=$rf1["send_comment"];
  if(mysql_num_rows($result1) > 0)
  {
     $sended="<b>به اين داور ارسال شده</b>";
     
  }
  else
  $sended="به اين داور ارسال نشده";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  
  echo "<input type=\"hidden\" name=\"g".$i."\" value=\"send_comment".$i."\">";
   echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><textarea   rows=\"3\"  name=\"send_comment".$i."\" class=\"edit-user\"   dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\">$send_comment1</textarea></td>"; 
   echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"del_check".$i."\"  value=\"ON\"></td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"check".$i."\"  value=\"ON\"></td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh_karshenasi."</td>";

  echo "<input type=\"hidden\" name=\"value_".$i."\" value=\"".$row_fetched["karshenas_email"]."\">";
  echo "<input type=\"hidden\" name=\"name_".$i."\" value=\"".$row_fetched["karshenas_name"]."&nbsp;".$row_fetched["kar_tahghigh_family"]."\">";
  echo "<input type=\"hidden\" name=\"cod_karshenas_".$i."\" value=\"".$row_fetched["cod_karshenas"]."\">";
  
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$sended."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  $mycntr=$i+1;
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$mycntr."</td>";
  echo "</tr>";
  $i++;
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }


echo "</table><br>";

 echo "<br><input type=\"submit\" value=\"ارسال\" name=\"B1\" class=\"but-small\"><br><br>";
echo "</form>";

}
else // if reccount of tarh  < =0
{
 message_show(".هيچ کارشناسي  يافت نشد","red");
}

$query="select * from karshenasan_tarh,karshenasan where karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas and cod_tarh='$cod_tarh' group by karshenasan.cod_karshenas";
		$result1=mysql_query($query)or die("Error in selecting data from karshenasan");;
		if(mysql_num_rows($result1) > 0)
		{
		
?>
 <table border="0" width="90%" cellpadding="1" cellspacing="1">
 
<tr>
<td width="100%" bgcolor="#66CCFF"  colspan="11">

      <p align="center" class="tahoma1"><font color="black"><b>ليست کارشناساني که طرح براي آنها ارسال شده </b></font></td>
  
</tr>
	<tr>
	 
			 <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">توضيحات</font></td>
		
	 	 <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح در دست ايشان</font></td>
 <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح داوري /نظارت شده</font></td>

    
     <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تخصص</font></td>

    <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
        <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
    </tr>
   
  
   <?php 
   $j=0;
    while($row_fetched2=mysql_fetch_array($result1))
 {
 	$cod_karshenas=$row_fetched2["cod_karshenas"];
 	$send_comment2=$row_fetched2["send_comment"];
 	 $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas' and finished ='1'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh_karshenasi=$rf1["cnt"];
  
  $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh=$rf1["cnt"];
   if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  
// echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"del_check".$i."\"  value=\"ON\"></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$send_comment2."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh_karshenasi."</td>";
 
  
 
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</td>";

 echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched2["karshenas_takhasos"]."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched2["karshenas_family"]."</td>";
  echo "<td   bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched2["karshenas_name"]."</td>";
  $mycntr=$j+1;
  echo "<td  bgcolor=$color align=\"right\" class=\"tahoma1\">".$mycntr."</td>";
  echo "</tr>";
  $j++;
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 
  
  
 	
 }
		echo "</table>";
		}else
 echo "<b>به کارشناسي ارسال نشده</b>";
  ?>
  
<?php 




footer_forms($admin,$seed);
?>

