<script>
function checkit()
{
	var key;
	key = window.event.keyCode
	
	if((key>=48)&&(key<=57))
	  window.event.returnValue= true
	else
	{
		if(key!=46)
	      window.event.returnValue= false;
	    else  
	    window.event.returnValue= true
	}

	  
}
</script> 


<script type="text/javascript">
function changetextbox()
{ 
	var x=document.getElementById("tamin_etebar");
	var y=document.getElementById("grant_type");
    if (document.getElementById("tarh_type").value == "3") {
        
    	x.style.display = 'block';
    	y.style.display = 'none';
    }
    else if (document.getElementById("tarh_type").value == "2") {
    	
        //alert(document.getElementById("tarh_type").value);
    	x.style.display = 'none';
    	y.style.display = 'block';    	
    }

 else if (document.getElementById("tarh_type").value == "1") {
    	
        //alert(document.getElementById("tarh_type").value);
    	y.style.display = 'none';
    	x.style.display = 'none';
    	
    }
}
//----------------------------------------------

function disablefield()
{	
	var x=document.getElementById("maghta");
	
if ( document.getElementById('define_nazer').checked == true ){
	x.style.display = 'none';
//document.getElementById('PhoneNumber').disabled = true
	}
 if (document.getElementById('change_nazer').checked == true ){
	 
	 x.style.display = 'block';
	}
}
//----------------------------------------------
function disablefield2()
{	
	var x=document.getElementById("mahale_tamin_etebar");
	var y=document.getElementById("mablagh_tamin_etebar");
	var z=document.getElementById("nahveye_tamin_etebar");
		
if ( document.getElementById('tamin_etebar_yes').checked == true ){
		//alert("hhhhh");
		x.style.display = 'none';
		y.style.display = 'none';
		z.style.display = 'none';

	}
 if (document.getElementById('tamin_etebar_no').checked == true ){
	 
	 x.style.display = 'block';
	 y.style.display = 'block';
	 z.style.display = 'block';
	}
}
//----------------------------------------------
function disablefield3()
{	
	var x=document.getElementById("ex_nazer");
	var y=document.getElementById("change_nazer_reason");
	
if ( document.getElementById('change_nazer').checked == true ){
		//alert("hhhhh");
	x.style.display = 'none';
	y.style.display = 'none';
		
	}
 if (document.getElementById('define_nazer').checked == true ){
	 
	 x.style.display = 'block';
	 y.style.display = 'block';
	}
}

//----------------------------------------------
function disablefield4()
{	
	var x=document.getElementById("letter");
	var y=document.getElementById("letter_no");
	var z=document.getElementById("mablagh_mosharekat");
		
if ( document.getElementById('tarh_moshtarak_yes').checked == true ){
		//alert("hhhhh");
	x.style.display = 'none';
	y.style.display = 'none';
	z.style.display ='none';
		
	}
 if (document.getElementById('tarh_moshtarak_no').checked == true ){
	 
	 x.style.display = 'block';
	 y.style.display = 'block';
	 z.style.display = 'block';
	}
}
//-------------------------------------------------
function disablefield5()
{	
	var x=document.getElementById("letter_no_akhlagh");
	var y=document.getElementById("date");
	
	 if (document.getElementById("commite_akhlagh_confirm").value == "3") {
	        
	    	x.style.display = 'block';
	    	y.style.display = 'block';
	    }
	    else  {
	    	
	        //alert(document.getElementById("tarh_type").value);
	    	x.style.display = 'none';
	    	y.style.display = 'none';    	
	    }
}
//-------------------------------------------------

function changetextbox2()
{ 
	var x=document.getElementById("tarh_takhiri_no");
	
    if (document.getElementById("tarh_takhiri").value == "1") {
        
    	x.style.display = 'block';
    	
    }
    else if (document.getElementById("tarh_takhiri").value == "2") {
    	
    	x.style.display = 'none';
    	
    }
}

</script>

<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");

echo "<br>";


$query="select * from group_karshenasan where  username=\"$admin\"";
$result=mysql_query($query) or die("Error in selecting data from tarh  ");
$row_fetched = mysql_fetch_array( $result );
$cod_karshenas=$row_fetched["cod_karshenas"];
//echo date("Y-m-d");
if(isset($action))
{
  if (strcmp($action,"taein_nazer")==0)
  {
   	
	        
   if( strlen(trim($darkhast_type)) >= 0     && $karshenas!=0  )
    {
    	$mablagh_tarh=str_replace(",","",$mablagh_tarh);
      	$mablagh_nahaei=str_replace(",","",$mablagh_nahaei);
      	$mablagh_mosharekat=str_replace(",","",$mablagh_mosharekat);
      	$mablagh_tamin_etebar=str_replace(",","",$mablagh_tamin_etebar);
    	
    	$date = $year."/". $month."/". $day;
      $query="select * from taein_nazer where (cod_tarh=\"$cod_tarh\") and cod_karshenas=\"$cod_karshenas\"";
      $result=mysql_query($query) or die("Error in selecting data from tarh  ");

      if ( mysql_num_rows($result) <= 0 )
      {

      
          $year_date = date("Y") - 1921 ;
  	    
       $hijri_date =jalali_to_gregorian($year,$month,$day);
       $year=$hijri_date[0];
       $month=str_pad($hijri_date[1],2,"0",STR_PAD_LEFT);
       $day=str_pad($hijri_date[2],2,"0",STR_PAD_LEFT);
       $date=$year."-".$month."-".$day; 
       
		  $query="insert into taein_nazer  set  cod_tarh='$cod_tarh',cod_karshenas='$cod_karshenas',darkhast_type='$darkhast_type',modir_confirm='-1',ex_nazer='$ex_nazer',change_reason='$change_reason',karshenas_suggestion='$karshenas_suggestion',karshenas='$karshenas', date='".date("Y-m-d")."'";
		  echo $query;
	      $result=mysql_query($query) or die("Error in inserting data into tarh #100");
          $action="ثبت فرم تعيين/تغيير ناظر طرح با کد"."<br>".$cod_tarh;
          set_log($action,$admin,date("Y-m-d, g:i a"));
        
      
      }
      else {
      	
      	  $query="update taein_nazer  set  darkhast_type='$darkhast_type',cod_karshenas='$cod_karshenas',modir_comment='',modir_confirm='-1',ex_nazer='$ex_nazer',change_reason='$change_reason',karshenas_suggestion='$karshenas_suggestion',karshenas='$karshenas' where cod_tarh='$cod_tarh'";
		echo $query;
	      $result=mysql_query($query) or die("Error in inserting data into tarh #100");
	      
	     $darkhast_type="";
	    // $modir_comment="";
	     
	      
	      
          $action="ويرايش تعيين ناظر طرح با کد"."<br>".$cod_tarh;
           set_log($action,$admin,date("Y-m-d, g:i a"));
      }
          // message_show("فرم کنترل قرارداد مربوط به اين طرح ثبت شد","green");
		          
          // footer_forms($admin,$seed);
          // exit();
         
           ?>
          <script language="javascript">
           window.location="<? echo "in_doing.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh";  ?>";
           </script>
           <?
         
    
    }
   else
      $status="entry_error";
  }

}




 $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }
   

  
  
  $nazer_query = "SELECT  * FROM taein_nazer WHERE cod_tarh = '$cod_tarh'";
  $myresult_nazer= mysql_query( $nazer_query ) or die("Error in selecting data from taein_nazer");
  $rf_nazer = mysql_fetch_array( $myresult_nazer );
  $darkhast_type=$rf_nazer["darkhast_type"];
 // echo $darkhast_type;
  $ex_nazer=$rf_nazer["ex_nazer"];
  $change_reason=$rf_nazer["change_reason"];
  $karshenas_suggestion=$rf_nazer["karshenas_suggestion"];
  $karshenas=$rf_nazer["karshenas"];
  $date=$rf_nazer["date"];
  

echo "<form name=\"sabt_maghale\" method=\"post\"  action=\"$PHP_SELF?action=taein_nazer&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<table border="0"  width="600" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">

<center>
<TABLE cellSpacing=0  width="600" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD dir="rtl" align=center  class="tahoma1"  height=19  dir="rtl">
      <?
	   echo ""."تعيين ناظر طرح شماره   : ".$cod_tarh;
      ?>
      </TD>
  </TR>

</table>
</center>


<table border="1" width="600" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width:1px; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">.مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">کنترل قرارداد اين طرح قبلا ثبت شده است</td>";
    echo "</tr>";
  }
//echo $darkhast_type;
  ?>


<tr>
    <td width="350" align="right" class="tahoma1">
      <input type="radio" value="1" id="define_nazer" name="darkhast_type"  onclick="disablefield3();" >تعيين ناظر
      <input type="radio" value="0" id="change_nazer" name="darkhast_type"  onclick="disablefield3();">تغيير ناظر
    </td>
    <td width="250" align="center" class="tahoma1"><span class="star-message">*</span>نوع درخواست</td>
</tr>

<?
	$query="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
 $result=mysql_query($query) or die("Error");
 $exists=0;
 if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	
 	$nazerin=$row_fetched["nazerin"];
 	$unnazerin=$row_fetched["unnazerin"];

 } 	
?>

<tr >
	<td width="350" align="right" class="tahoma1"  height='40' dir=RTL >

	<? echo "ناظر طرح باشند  : ".$nazerin;?> 
    </td>
   <td width="250" align="center" class="tahoma1" rowspan='2'>پيشنهاد مجري </td>

</tr>
<tr>
	<td width="350" align="right" class="tahoma1" height='40' dir=RTL  >

		<? echo " ناظر طرح نباشند  : ".$unnazerin;?> 
    </td>
 

</tr>

<tr id="ex_nazer" style="display:none;">
    <td width="350" align="right" class="tahoma1"><input type="text" name="ex_nazer" value='<? echo $ex_nazer;?>' size="20"   class="edit-user" dir=RTL  ></td>
    <td width="250" align="center" class="tahoma1">نام ناظر تعيين شده قبلي </td>
</tr>

<tr id="change_nazer_reason" style="display:none;">
    <td width="350" align="right"><textarea   rows="4"  name="change_reason"  class="edit-user"  dir=RTL   ><? echo $change_reason;?></textarea></td>
    <td width="250" align="center" class="tahoma1">علت تغيير ناظر </td>
</tr>
  
  <tr>
    <td width="350" align="right"><input type="text" name="karshenas_suggestion" value='<? echo $karshenas_suggestion;?>' size="20"   class="edit-user" dir=RTL  ></td>
    <td width="250" align="center" class="tahoma1">پيشنهاد کارشناس</td>
  </tr>

   <tr>
  <?
    $query="select * from control_gharardad_karshenas order by id ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
  ?>
    <td align="center"><select size="1" name="karshenas" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?
		
    while($row_fetched=mysql_fetch_array($qresult))
    {
    	if(strcmp($row_fetched["id"],$karshenas)==0)
	    	   $checked=" selected ";
	    	else
			   $checked="";
         echo "<option $checked value=\"".$row_fetched["id"]."\" class=\"tahoma1\">".$row_fetched["karshenas_name"]." ".$row_fetched["karshenas_family"]."</option>";
    }
    ?>
    </select></td>
    <td width="250" align="left" class="tahoma1"><p align="center" class="tahoma1"><span class="star-message">*</span> نام کارشناس طرح</td>
  </tr>


  
 </table>
<table border="0" width="600" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


  
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit"  value="ثبت" name="B1" class="but-small"></p></td>
  </tr>
  
</table>


<script>
            var temp=document.sabt_tarh.cod_group            
            function redirect()
            {
              for (m=temp.options.length-1;m>0;m--)
                temp.options[m]=null
                var myselecteditem = this.sabt_tarh.cod_daneshkade.selectedIndex
                myselecteditem--
                
                if( myselecteditem<0 )
                  return
               
                for (i=0;i<group[myselecteditem].length;i++)
                {                	
                  temp.options[i]=new Option(group[myselecteditem][i].value,group[myselecteditem][i].text)
                }
                temp.options[0].selected=true
            }
            


            </script>
             
</form>
<?
	footer_forms($admin,$seed);
?>