<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);

include("include/styles.phtml");

echo "<br>";


if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
    
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}
$query="select * from karshenasan where username='$admin'";

$result=mysql_query($query) or die("Error in selecting data from karshenas_tarh");
$row_fetched=mysql_fetch_array($result);
$cod_karshenas=$row_fetched["cod_karshenas"];
if(isset($name_e))
{
  $query="select * from tarh,karshenasan_tarh where  karshenasan_tarh.finished='1' and  (tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and karshenasan_tarh.cod_karshenas='$cod_karshenas' and tarh.cod_tarh=karshenasan_tarh.cod_tarh  and karshenasan_tarh.version='-1'  order by tarh_time desc";
}
else
  $query="select * from tarh,karshenasan_tarh where   karshenasan_tarh.finished='1' and karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=karshenasan_tarh.cod_tarh and karshenasan_tarh.version='-1' order by tarh_time desc";


$result=mysql_query($query) or die("Error in selecting data from tarh");
$reccount = mysql_num_rows($result);


 if(isset($name_e))
{
  $query="select * from tarh,karshenasan_tarh where  karshenasan_tarh.finished='1'  and  (tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search)  and karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=karshenasan_tarh.cod_tarh  and karshenasan_tarh.version='-1' order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
}
else
  $query="select * from tarh,karshenasan_tarh where   karshenasan_tarh.finished='1' and  karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=karshenasan_tarh.cod_tarh   and karshenasan_tarh.version='-1'  order by tarh_time desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;

?>
<center>
<span class="tahoma1">طرحهاي کارشناسي شده</span>
</center>
<?

$result=mysql_query($query) or die("Error in selecting data from tarh");
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="right">

 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 </tr>
 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
	
 pubshowpages("tarh_karshenasi_shode.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
        <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کارشناس مربوطه در معاونت پژوهشي</font></td>
   
       <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايشهاي طرح</font></td>
  
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">نظرات شما</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مکاتبات</font></td>  
  <!--  <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال به کارشناس</font></td> -->
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ارسال</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  <?


 $color=$list_color_1;

 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  echo "<tr>";
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><img border=\"0\" src=\"image/e-mail.gif\" width=\"10\" height=\"10\" alt=\"E-mail\" ></td>";
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   
 $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
     {
    if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم";
  } 
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }

 $myq1="select * from group_karshenasan,group_karshenasan_tarh where group_karshenasan_tarh.cod_tarh='$cod_tarh' and group_karshenasan.cod_karshenas=group_karshenasan_tarh.cod_karshenas and group_karshenasan.karshenas_type='1'";
  $myres=mysql_query($myq1) or die("Error");
  
  if(mysql_num_rows($myres) > 0)
  {
    $myrf=mysql_fetch_array($myres);
    $name_family_sender=$myrf["karshenas_name"]."&nbsp;".$myrf["karshenas_family"]."&nbsp;<br>".$myrf["mobile"];
  }
  else
  {
  	 $name_family_sender="نامعلوم";
  }
  

  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$name_family_sender</td>";
echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a  href=\"versions.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >ويراستها</a></td>";
      echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"your_notes.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">کارشناسي شده توسط شما</a></td>";    

  
 $mytarh_type = $row_fetched["status"];
 
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
//  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"send_karshenas.phtml?admin=$admin&seed=$seed&action=confirm_tarh&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/tick-mark.gif\" width=\"11\" height=\"13\" alt=\"ُSend To Karshenas\" ></a></td>";
  
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"letter_list.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >مکاتبات</a></td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$farsistartdate."</a></td>";
  
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_english"]."</a></td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";
  
  $cod_tarh_user=$row_fetched["cod_tarh_user"];


     echo "<td width=\"20%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";

  //echo "<td width=\"35%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرح کارشناسي شده اي نداريد","red");
}
echo "</form>";
footer_forms($admin,$seed);


?>

