<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

//----------------------------------------------------------------
function add_hazineha($cod_tarh , $version)
{
  $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='$version' order by activity_type ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {
     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["per_hour"]*$row_fetched["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       $query="select * from darajeelmi where darajeelmi = '".$row_fetched["degree"]."'";
       $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
       if(mysql_num_rows($qresult) > 0 )
       {
         $row_degree = mysql_fetch_array($qresult);
         $degree_result = $row_degree["darajeelmi_desc"];
       }
       else
         $degree_result = "ثبت نشده";
     }
      $personnel_sum=$mycount;
   }

   
   
   
   $query="select * from  hazine_azmayesh where cod_tarh=\"$cod_tarh\"  and version='$version' order by mozoa_azmayesh ";

   $result=mysql_query($query) or die("Error in selecting data from hazine personnel");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $my_summary = $row_fetched["azmayesh_cnt"]*$row_fetched["hazine_har_bar"];
       $mycount=$mycount+$my_summary;
     }
      $lab_sum=$mycount;
   }

   $query="select * from  fhrest_vasayel_kharid where cod_tarh=\"$cod_tarh\"  and version='$version' order by name_dastgah";

   $result=mysql_query($query) or die("Error in selecting data from fehrest kharid 2");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;

     while($row_fetched=mysql_fetch_array($result))
     {
     //  $mycount=$mycount+$row_fetched["count"];
      // $mycount1=$mycount1+$row_fetched["price"];
      $mycount1=$mycount1+$row_fetched["price"]*$row_fetched["count"];
     }
      //$vasile_sum=$mycount*$mycount1;
      $vasile_sum=$mycount1;

   }
   $query="select * from  hazine_safar where cod_tarh=\"$cod_tarh\"  and version='$version' order by target";

   $result=mysql_query($query) or die("Error in selecting data from hazine safar");
   if(mysql_num_rows($result) > 0)
   {

     $mycount=0;
     $mycount1=0;
     while($row_fetched=mysql_fetch_array($result))
     {
       $mycount=$mycount+$row_fetched["hazine"];
       $mycount1=$mycount1+$row_fetched["persons_cnt"];
     }
	  $trip_sum = $mycount;
   }
 $query = "select * from sayer_hazine where cod_tarh='$cod_tarh'  and version='$version'";
 $result = mysql_query($query) or die("Error in selecting data from sayer_hazine ");

$hazine_taksir=0;
$hazine_digar=0;
 if(mysql_num_rows($result) > 0 )
 {
 	
  while($hazine_row_fetched = mysql_fetch_array($result))	
  {
    $hazine_taksir = $hazine_taksir+$hazine_row_fetched["hazine_taksir"];
    $hazine_digar = $hazine_digar+$hazine_row_fetched["sayer_hazine"];
  }
 }
  $sum_sayer=$hazine_digar+$hazine_taksir;
   $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
	
     echo "<table width=\"280\" cellPadding=1 border=0 bordercolor=\"#333333\" style=\"border-style: solid; border-width: 1; \">";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\"><b>(مجموع(ريال<b></td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\"><b>هزينه<b></td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"     align=\"center\" class=\"tahoma1\">".number_format($personnel_sum)."</td>";
     echo "<td width=\"80%\"   align=\"center\"  class=\"tahoma1\">جمع هزينه پرسنلي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($lab_sum)."</td>";
     echo "<td width=\"80%\"     align=\"center\"  class=\"tahoma1\">جمع هزينه هاي آزمايشات وخدمات تخصصي</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"    align=\"center\" class=\"tahoma1\">".number_format($trip_sum)."</td>";
     echo "<td width=\"80%\"     align=\"center\"  class=\"tahoma1\">جمع هزينه هاي مسافرت</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"    align=\"center\" class=\"tahoma1\">".number_format($vasile_sum)."</td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\">جمع هزِينه هاي وسايل</td>";
     echo "</tr>";
     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($sum_sayer)."</td>";
     echo "<td width=\"80%\"   align=\"center\"  class=\"tahoma1\">جمع ساير هزينه ها</td>";
     echo "</tr>";

     echo "<tr>";
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\">".number_format($eatebare_sazmanha_pardakht_add)."</td>";
     echo "<td width=\"80%\"    align=\"center\"  class=\"tahoma1\">اعتبار از سازمانهاي ديگر</td>";
     echo "</tr>";

	 echo "<tr>";
	 $sum_of_all = $sum_sayer+$vasile_sum+$trip_sum+$lab_sum+$personnel_sum;
     echo "<td width=\"20%\"   align=\"center\" class=\"tahoma1\"><b>".number_format($sum_of_all)."</b></td>";
     echo "<td width=\"80%\"   align=\"center\" class=\"tahoma1\"><b>جمع کل</b></td>";

     echo "</tr>";


     echo "</table>";

 	
}


//-----------------------------------------------------------
echo "<br>";

  
//confirm_tarh=1
  
if ( ! isset($current))
    $current = 1;

if(!isset($ascdescfield))
  $ascdescfield="cod_tarh";

if(!isset($ascdesc))
  $ascdesc="desc";
  

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   

if ( ! isset($tarh_year))
    $tarh_year = '-1';




if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

//echo $tarh_year;
if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;




if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

$query="select * from tarh where  cod_tarh='$cod_tarh'";


$result=mysql_query($query) or die("Error in selecting data from tarh1");
$reccount = mysql_num_rows($result);
 

$query="select * from tarh where cod_tarh='$cod_tarh'  order by  version desc  ";


if(strcmp($ascdesc,'asc')==0)
  $ascdesc="desc";
else
  $ascdesc="asc";  

$result=mysql_query($query) or die("Error in selecting data from tarh2");
 
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="100%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b><? echo $cod_tarh; ?> ويرايشهاي مربوط به طرح با کد<b></td>
 </tr>
 </table> 
  

<?
}
if(mysql_num_rows($result) > 0 )
{
// $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year&ascdescfield=$ascdescfield&ascdesc=$ascdesc";	
// pubshowpages("tarh_list_new.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"100%",$title_color);
?>

<table border="0" width="100%" cellpadding="1" cellspacing="1">
  <tr>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">جمع هزينه ها</font></td>  
 
 		<td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ ويرايش</font></td>  
      <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ باز شدن طرح</font></td>  
 
 		
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
    <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
    <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
    <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويراست طرح</font></td>
      
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $open_tarh_date=$row_fetched["open_tarh_date"];
  $last_ver_date=$row_fetched["last_ver_date"];
  
   $startyear = substr($last_ver_date,0,4);
  $startmon = substr($last_ver_date,5,2);
  $startday = substr($last_ver_date,8,2);
  $last_ver_date=hijricalender( $startyear , $startmon , $startday );
  
  $startyear = substr($open_tarh_date,0,4);
  $startmon = substr($open_tarh_date,5,2);
  $startday = substr($open_tarh_date,8,2);
  $open_tarh_date=hijricalender( $startyear , $startmon , $startday );
  
 
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
  
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
  {
  	if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم"; 
  }
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }
  
  
  
  
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //$myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh'  ORDER  BY mojri.mojri_code";
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }
  $version=$row_fetched["version"];
  //echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  //$hazine_in_version=add_hazineha($cod_tarh , $version);
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >";
   $sum_sayer=$hazine_digar+$hazine_taksir;
    echo add_hazineha($cod_tarh , $version);
  echo "</a></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$last_ver_date</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">$open_tarh_date</td>";
  
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >". $daneshkade."</a></td>";
  
  //echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >". $farsistartdate."</a></td>";
 
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >".$row_fetched["tarh_title_farsi"]."</a></td>";

  $cod_tarh=$row_fetched["cod_tarh"];
  $version=$row_fetched["version"];

     echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >".$cod_tarh."</a></td>";
  $thisver=$row_fetched["version"];
  if(strcmp($thisver,"-1")==0)
    $thisver="ويراست جاري";   
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&version=$version\" >".$thisver."</a></td>";   
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرح ارسال شده  جديدي يافت نشد","red");
}
echo "</form>";

footer_forms($admin,$seed);


?>
