<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");

echo "<br>";
if ( ! isset($tarh_year))
    $tarh_year = '-1';

if(strcmp($tarh_year,'-1')!=0 )
{
	$year_caution="tarh.cod_tarh like \"$tarh_year".'%'."\"";
}
else
   $year_caution=1;
   

if ( ! isset($current))
    $current = 1;

if ( ! isset($cod_daneshkade))
    $cod_daneshkade = '-1';

if(strcmp($cod_daneshkade,'-1')!=0 )
{
	$daneshkade_caution="cod_daneshkade = '$cod_daneshkade'";
}
else
   $daneshkade_caution=1;
   


if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;
 

      $startdate = date("Y-m-d");
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  //$farsistartdate = enum2fnum($farsistartdate);
 $date_today=str_replace("/","-",$farsistartdate);

if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=10000;
      $current=1;
    }
        
if(isset($name_e))
{
  $myname_search = "\"%".trim($name_e)."%\"";
}

$query="select * from group_karshenasan where username='$admin'";

$result=mysql_query($query) or die("Error in selecting data from karshenas_tarh");
$row_fetched=mysql_fetch_array($result);
$cod_karshenas=$row_fetched["cod_karshenas"];

if(isset($name_e))
{
   $query=" select tarh.*,gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from tarh,gozaresh_gharardad,group_karshenasan_tarh where $year_caution and gozaresh_gharardad.marhale!=0 and tarh.finalized='0' and (tarh.cod_tarh like $myname_search or  tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) and tarh.cod_tarh=gozaresh_gharardad.cod_tarh and   date_gozaresh < '$date_today' and gozaresh_gharardad.cod_tarh not in (select cod_tarh from marhale_report where gozaresh_gharardad.marhale=marhale_report.marhale ) and $daneshkade_caution and group_karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=group_karshenasan_tarh.cod_tarh   group by cod_tarh order by tarh_title_farsi  desc";
  	
}
else
 $query=" select tarh.*,gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from tarh,gozaresh_gharardad,group_karshenasan_tarh where  $year_caution and gozaresh_gharardad.marhale!=0 and  tarh.finalized='0' and tarh.cod_tarh=gozaresh_gharardad.cod_tarh and   date_gozaresh < '$date_today' and gozaresh_gharardad.cod_tarh not in (select cod_tarh from marhale_report where gozaresh_gharardad.marhale=marhale_report.marhale ) and $daneshkade_caution  and group_karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=group_karshenasan_tarh.cod_tarh   group by cod_tarh order by tarh_title_farsi  desc";
  
  

$result=mysql_query($query) or die("Error in selecting data from tarh");
$reccount = mysql_num_rows($result);
 
 if(isset($name_e))
{

  $query=" select tarh.*,gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from tarh,gozaresh_gharardad,group_karshenasan_tarh where $year_caution and  gozaresh_gharardad.marhale!=0 and  tarh.finalized='0' and (tarh.cod_tarh like $myname_search or tarh_title_farsi like $myname_search or  tarh_title_english like $myname_search) tarh.cod_tarh=gozaresh_gharardad.cod_tarh and   date_gozaresh < '$date_today' and gozaresh_gharardad.cod_tarh not in (select cod_tarh from marhale_report where gozaresh_gharardad.marhale=marhale_report.marhale ) and $daneshkade_caution and group_karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=group_karshenasan_tarh.cod_tarh   group by cod_tarh order by tarh_title_farsi  desc".($current-1)*$RecPerPage.",".$RecPerPage ;
  
}
else
 $query=" select tarh.*,gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from tarh,gozaresh_gharardad,group_karshenasan_tarh where $year_caution and  gozaresh_gharardad.marhale!=0 and  tarh.finalized='0' and tarh.cod_tarh=gozaresh_gharardad.cod_tarh and   date_gozaresh < '$date_today' and gozaresh_gharardad.cod_tarh not in (select cod_tarh from marhale_report where gozaresh_gharardad.marhale=marhale_report.marhale ) and $daneshkade_caution and group_karshenasan_tarh.cod_karshenas='$cod_karshenas'  and tarh.cod_tarh=group_karshenasan_tarh.cod_tarh   group by cod_tarh order by tarh_title_farsi  desc"." limit ".($current-1)*$RecPerPage.",".$RecPerPage ;
 

//echo $query;
$result=mysql_query($query) or die("Error in selecting data from tarh");
 if(mysql_num_rows($result) > 0)
 {
 ?>
 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">
 <tr>
 <td align="center" class="tahoma1" width="60%"><b>طرحهاي داراي گزارش تاخيري<b></td>
 </tr>
 </table>
<?
echo "<form name=\"change_daneshkade\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed\">";
?>

 <table  cellSpacing="0" cellPadding="0" width="90%" bgColor="white" border="0">

 <tr>
<?    



$query="select * from daneshkade order by  daneshkade_name  desc";
$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"> دانشکده <select size=\"1\" name=\"cod_daneshkade\" onchange=\"JavaScript:document.change_daneshkade.submit();\"  class='tahoma1' dir=\"rtl\">";
echo "<option value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["cod_daneshkade"],$cod_daneshkade)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["cod_daneshkade"]."\" class=\"tahoma1\">".$row_fetched["daneshkade_name"]."</option>";
 }
  
?>
  </select>
  </form>
  <?echo "<form name=\"change_year\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_daneshkade=$cod_daneshkade\">";



$query="select left(cod_tarh,5) as tarh_year from tarh group by left(cod_tarh,5) order by  cod_tarh desc";

$qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");
echo "<td  align=\"left\" class=\"tahoma1\"><select size=\"1\" name=\"tarh_year\" onchange=\"JavaScript:document.change_year.submit();\" dir=\"rtl\" class=\"but-small\">";
	if(strcmp($row_fetched["tarh_year"],'-1')==0)
   	  $selected=" selected ";
    else
	  $selected=""; 
echo "<option $selected value=\"-1\" class=\"tahoma1\">همه موارد</option>";

while($row_fetched=mysql_fetch_array($qresult))
 {
  	if(strcmp($row_fetched["tarh_year"],$tarh_year)==0)
   	  $selected=" selected ";
    else
	  $selected="";    	  
    echo "<option $selected value=\"".$row_fetched["tarh_year"]."\" class=\"tahoma1\">".$row_fetched["tarh_year"]."</option>";
 }
 
?>
  </select> سال/رنک 
   
  </form>
  </td>
<?
 echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";

?>  
 <td align="right" >
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL   >
 </td>
 
 </tr>
<?
  if (strcmp($status,"confirm_error")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\"><br>ابتدا به طرح کد بدهيد سپس آنرا تاييد براي بررسي کنيد<br></td>";
    echo "</tr>";
  }
?>


 </table>
<?
}
if(mysql_num_rows($result) > 0 )
{
 $myascdescpub=$myascdescpub."&cod_daneshkade=$cod_daneshkade&tarh_year=$tarh_year";	
 pubshowpages("waited_reports.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
?>

<table border="0" width="90%" cellpadding="1" cellspacing="1">
  <tr>
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مراحل تاخير دار</font></td>
      <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">قرارداد</font></td>
   <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">تاريخ گزارش اول</font></td>

   <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">وضعيت طرح از نظر پرداخت</font></td>
   
    <td width="4%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">چاپ</font></td>
     <!--  <td width="3%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ويرايش</font></td> -->
      <td width="5%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">ارسال نامه</font></td> 
     <td width="10%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">دانشکده /مرکز</font></td>  
     <td width="20%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">مجري اول</font></td>
    <td width="25%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">عنوان فارسي</font></td>
    <td width="30%" bgcolor=<? echo "$title_color"; ?>>
      <p align="center" class="tahoma1"><font color="black">کد طرح</font></td>
  </tr>
  <?

 $color=$list_color_1;
 
 while($row_fetched=mysql_fetch_array($result))
 {
  $cod_tarh=$row_fetched["cod_tarh"];
  
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  $myres=mysql_query($myq);
  $myrf=mysql_fetch_array($myres);
  $daneshkade=$myrf["daneshkade_name"];
    $query=" select gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from  gozaresh_gharardad where  gozaresh_gharardad.marhale=0 and     cod_tarh='$cod_tarh'  order by marhale  desc";
  // echo $query;
  $myres=mysql_query($query) or die("Error 1");
  $date_gozaresh_first=0;
  while($rf_list=mysql_fetch_array($myres))
  {
  	$date_gozaresh_first=$rf_list["date_gozaresh"];
  }
   $query=" select gozaresh_gharardad.marhale,gozaresh_gharardad.date_gozaresh from  gozaresh_gharardad where  gozaresh_gharardad.marhale!=0 and   date_gozaresh < '$date_today' and gozaresh_gharardad.cod_tarh not in (select cod_tarh from marhale_report where gozaresh_gharardad.marhale=marhale_report.marhale ) and cod_tarh='$cod_tarh'  order by marhale  desc";
  // echo $query;
  $myres=mysql_query($query) or die("Error 1");
  $string_delayed="";
  while($rf_list=mysql_fetch_array($myres))
  {
  	$marhale_lst=$rf_list["marhale"];
  	if(strcmp($marhale_lst,"0")==0)
  	  $marhale_lst="اول";
  	
	if(strcmp($marhale_lst,"100")==0)
  	  $marhale_lst="آخر";  
  	$string_delayed=$string_delayed."<br>".$marhale_lst.":".$rf_list["date_gozaresh"]."<br>";
  }
  
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
   $myq1="select * from tarh_indoing where cod_tarh='$cod_tarh' order by marhale desc";
  $res=mysql_query($myq1) or die("ERROR");
  $payment_status="";
  if(mysql_num_rows($res)>0)
  {
  	while($my_rf=mysql_fetch_array($res))
  	{
  		$marhale_indoing=$my_rf["marhale"];
  		$submitted=$my_rf["submitted"];
  		if(strcmp($submitted,'1')==0)
  		  $paid=" پرداخت شده ";
  		else 
  		  $paid=" پرداخت نشده ";  
  		  if($marhale_indoing==0)
  		    $marhale_indoing='1';
  		 if($marhale_indoing==100)
  		    $marhale_indoing='آخر';    
  	    //$payment_status=$payment_status."<br><br>".$paid.":".$marhale_indoing." مرحله ";
  	    $payment_status=" مرحله ".$marhale_indoing.":".$paid."<br><br>".$payment_status;
  	}
  }
  echo "<tr>";
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\">$string_delayed</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" style=\"text-decoration:none\" href=\"rtf.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >صدور قرارداد</a></td>";
  echo "<td width='20%'  bgcolor=$color align=\"center\" class=\"tahoma1\" dir='ltr'>$date_gozaresh_first</td>";
 
  echo "<td width='20%'  bgcolor=$color align=\"center\" class=\"tahoma1\" dir='rtl'>$payment_status</td>";
  echo "<td width=\"4%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a target=\"_blank\" href=\"print_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" ><img border=\"0\" src=\"image/print.gif\" width=\"19\" height=\"19\" alt=\"Print\" ></a></td>";
   $edit_request=$row_fetched["edit_request"];
  // echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"sabt_tarh_second.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
  echo "<td width=\"3%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a href=\"letter_to_mojri_body.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\"><img border=\"0\" src=\"image/letter.gif\" width=\"11\" height=\"13\" alt=\"Send Letter\" ></a></td>";
  
  $editable=1;
  $mytarh_type = $row_fetched["vaziat"];
  if($row_fetched["vaziat"]=="0")
  {
  	if($row_fetched["confirm_tarh"]=="1")
  	   $mystatus="در دست بررسي";
  	else   
       $mystatus="نامعلوم"; 
  }
  else
  {
    $query="select * from vaziat_tarh where vaziat='$mytarh_type'";
    $result_tarhtype=mysql_query($query) or die("Error in selectiong data from tarhtype");
    $row_fetched_tarh=mysql_fetch_array($result_tarhtype);
    $mystatus=$row_fetched_tarh["vaziat_desc"];
    if($row_fetched_tarh["view_or_no"]=="1")
       $editable=0;
    else
       $editable=1;
  }
  
  
  $startdate = $row_fetched["tarh_time"];
  $startyear = substr($startdate,0,4);
  $startmon = substr($startdate,5,2);
  $startday = substr($startdate,8,2);
  $farsistartdate=hijricalender( $startyear , $startmon , $startday );
  $farsistartdate = enum2fnum($farsistartdate);
  //$myquery_mojri = "SELECT  * FROM tarh, mojri_tarh, mojri WHERE mojri_tarh.cod_tarh = tarh.cod_tarh AND mojri.mojri_code=mojri_tarh.mojri_code and tarh.cod_tarh = '$cod_tarh'  ORDER  BY mojri.mojri_code";
  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }

 // echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$mystatus."</td>";
  echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $daneshkade."</a></td>";
  //echo "<td width=\"10%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >". $farsistartdate."</a></td>";
 
  if(mysql_num_rows($myresult_mojri) > 0 )
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"first_mojri_detail.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$First_mojri_name."</a></td>";
  else
    echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$First_mojri_name."</td>";
  echo "<td width=\"25%\" bgcolor=$color align=\"right\" class=\"tahoma1\" dir=\"rtl\"><a style=\"text-decoration:none\" href=\"view_tarh_form.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$row_fetched["tarh_title_farsi"]."</a></td>";

  $cod_tarh=$row_fetched["cod_tarh"];

  if( strcmp(trim($cod_tarh_user),"0")!=0 )
     echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"sabt_cod_tarh.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh\" >".$cod_tarh."</a></td>";
     
  echo "</tr>";
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }
echo "</table>";
}
else // if reccount of tarh  < =0
{
 message_show(".طرح ارسال شده  جديدي يافت نشد","red");
}
echo "</form>";

footer_forms($admin,$seed);


?>
