<?
 $farsi_title_font_style1="style=\"font-family: zar; font-size: 17pt; font-weight: bold\"";
 $farsi_title_font_style2="style=\"font-family: zar; font-size: 15pt; font-weight: bold\"";
 $farsi_title_font_style3="style=\"font-family: zar; font-size: 13pt; font-weight: bold\"";
 $besme_font_style="style=\"font-family: zar; font-size: 10pt\"";
 $daneshgah_font_style="style=\"font-family: zar; font-size: 14pt\"";
 $chekide_font_style="style=\"font-family: mitra ; font-size: 14pt\"";
 $envan_font_style="style=\"font-family: mitra; font-size: 14pt\"";
 $text_font_style="style=\"font-family: zar; font-size: 13pt\"";
 $lable_font_style="style=\"font-family: zar; font-size: 12pt\"";
 $print_table_style="style=\"font-family: yagut; font-size: 10pt\"";

 $university_name="معاونت پژوهشي دانشگاه علوم پزشکي و خدمات بهداشتي درماني استان اصفهان";

 ?>
