</section>

            </section>
        </section>
        <footer class="site-footer">
            <div class="text-center">
                2014 &copy; Dadevarz Peyvand  - Powered by : Isfahan.ir

                <a href="#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>

    </section>

    <script src="../js/jquery.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <!--<script src="js/jquery.js"></script>-->
    <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media/js/jquery.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="../js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="../js/jquery.scrollTo.min.js"></script>
    <script src="../js/jquery.nicescroll.js" type="text/javascript"></script>
   <!-- <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media/js/jquery.dataTables.js"></script>-->
    
     <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/media2/js/jquery.dataTables.min.js"></script>
    
	<script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/TableTools/js/dataTables.tableTools.js"></script>
	
	<!-- Relation to page grid3, two next script -->
        <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/ColReorder/js/dataTables.colReorder.min.js"></script>
        <script type="text/javascript" language="javascript" src="../assets/advanced-datatable/extensions/ColVis/js/dataTables.colVis.min.js"></script>
 
 <script src="../js/respond.min.js"></script>



    <script src="../js/common-scripts.js"></script>

 
    <script>
        function startTime() {
            var today = new Date();
            var h = today.getHours();
            var m = today.getMinutes();
            var s = today.getSeconds();
            // add a zero in front of numbers<10
            m = checkTime(m);
            s = checkTime(s);
            document.getElementById('hour').innerHTML = h + ":" + m + ":" + s;
            t = setTimeout(function () { startTime() }, 500);
        }

        function checkTime(i) {
            if (i < 10) {
                i = "0" + i;
            }
            return i;
        }
    </script>
 <script src="/assets/select2/select2.min.js"></script>
</body>
</html>