<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="SaeedSalehi">
    
    <link rel="shortcut icon" href="img/favicon.png">

    <title>داده هاي اوليه</title>


    <link href="../new_css/bootstrap.min.css" rel="stylesheet">
    <link href="../new_css/bootstrap-reset.css" rel="stylesheet">

    <link href="../assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />
    <link href="../assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />

    <link href="../new_css/style.css" rel="stylesheet">
    <link href="../new_css/style-responsive.css" rel="stylesheet" />
	<link href="../assets/advanced-datatable/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />
 <link href="/assets/select2/select2.css" rel="stylesheet"/>

<link href="/assets/advanced-datatable/extensions/ColReorder/css/dataTables.colReorder.min.css" rel="stylesheet"/>
<link href="/assets/advanced-datatable/extensions/ColVis/css/dataTables.colVis.css" rel="stylesheet"/>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lte IE 9]>
	<link href="../new_css/ie.css" rel="stylesheet" />
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body onload="startTime()">

    <section id="container" class="">

        <header class="header white-bg">

            <a class="logo">
                <img src="../img/logo.png" alt="" />
            </a>
            <div class="top-nav ">
                <div class="top-nav-info">
                    <span>
                        <i class="icon-user"></i>
                        آقاي سعيد صالحي (کارشناس)

                    </span>
                    <span>
                        <i class="icon-time"></i>
                        <span id="hour"></span>


                    </span>
                    <span>
                        <i class="icon-calendar"></i>
                        امروز دوشنبه 21 ارديبهشت 1393

                    </span>
                </div>
            </div>
            <div class="pajooheshyar-section">
                <a class="pajooheshyar-logo">
                    <img src="../img/logo-pajooheshyar.png" alt="">
                </a>
                <div class="header-buttons">
                    <ul class="list-unstyled header-panel">
                        <li><a href="#"><i class="icon-power-off "></i></a></li>
                        <li><a href="#"><i class="icon-envelope"></i></a></li>
                        <li><a href="#"><i class="icon-cog"></i></a></li>
                        <li><a href="#"><i class="icon-user"></i></a></li>
                        <li><a href="#"><i class="icon-lock"></i></a></li>
                        <li><a href="#"><i class="icon-home"></i></a></li>
                    </ul>
                </div>
            </div>
        </header>

       <?php include("../user/include/new_menu.php");
       		$move_to_user="move_to_user.phtml?admin=$admin&seed=$seed";
       		$move_to_karshenas="move_to_davar.phtml?admin=$admin&seed=$seed";
       		$move_to_karshenas_shora="";
        	 $q="select * from sessions where username='$admin' and rand='$seed'";
			 $rs=mysql_query($q) or die("error 333");
			 $rf=mysql_fetch_array($rs);
			 $usertype=$rf["usertype"];

       		   if($usertype!='3'){
       		   	$active_karshenas="";
       		   	$move_to_karshenas="#";
       		   }
              else{
              	$active_karshenas="active";
              }
	              $q="select * from karshenasan  where karshenas_email='$admin'";
				  $rs=mysql_query($q) or die("error");
				  if(mysql_num_rows($rs) > 0)
				  {
				    $karshenas="1";
				  }
              
               if($usertype!='2'){
               	  $active_mojri="";
               	  $move_to_user="#";
               }
              else{
              	$active_mojri="active";
              }
	              $q="select * from user_login  where email='$admin'";
				  $rs=mysql_query($q) or die("error");
				  if(mysql_num_rows($rs) > 0)
				  {
				    $mojri="1";
				  }
              
              if($usertype!='6'){
              	  $active_karshenas_shora="";
              	  $move_to_karshenas_shora="#";
              }
              else{
              	$active_karshenas_shora="active";
              }
	              $q="select * from karshenas_shora  where kar_shora_email='$admin'";
				  $rs=mysql_query($q) or die("error");
				  if(mysql_num_rows($rs) > 0)
				  {
				    $karshenas_shora="1";
				  }
              
       ?>

        <section id="main-content">
            <section class="wrapper">
                <section class="panel">
                    <header class="panel-heading  tab-right blue-line">

                        <ul class="nav nav-tabs pull-right">

                            
                            <?php  if(strcasecmp($mojri,"1")==0 ){?>
                            <li class="<?php echo $active_mojri;?>">
                                <a  href="<?php $move_to_karshenas_shora;?>">
                                    <i class="icon-user"></i>
                                    محيط مجري
                                </a>
                            </li>
                            <?php } if(strcasecmp($karshenas_shora,"1")==0 ){?>
                            <li class="<?php echo $active_karshenas_shora;?>">
                                <a  href="">
                                    <i class="icon-user"></i>
                                    محيط عضو شورا
                                </a>
                            </li>
                            <?php } if(strcasecmp($karshenas,"1")==0 ){?>
                            <li class="<?php echo $active_karshenas;?>">
                                <a  href="<?php echo $move_to_karshenas;?>">
                                    <i class="icon-user"></i>
                                    محيط داوري
                                </a>
                            </li>
                            <?php }?>
                        </ul>

                    </header>