<style>
<!--
.edit-user        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:170 }
.star-message     {font-family: tahoma; font-size: 8pt; color=red}
.tahoma1          {font-family: tahoma; font-size: 8pt}
.tahoma2          {font-family: tahoma; font-size: 10pt}
.but-small        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:80 }
.but-wide        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:180; height:18 }
.but-login        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:140 }
.edit-sugnup        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:270 }
.edit-feedback    { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:320 }
.error-message    {font-family: tahoma; font-size: 8pt; color=red}
.edit-user-advanced-search        { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 9pt ; width:170 }
.advanced-search-combo    { border-style: solid; border-width: 1 ; font-family: tahoma; font-size: 8pt ; width:120 }
-->
</style>

