<?
  $RecPerPage = 10;
  $PageCountShows = 17;
  $textfont="arial";
  $titlefont="arial";
  $titlesize="3";
  $textsize="3";
  $searchurl="http://localhost/journals/search.phtml";
  $englishfont = " \"arial\" size = \"3\"";
  $farsifont = " \"tahoma\" size = \"3\"";
  $title_color="#8099b7";
  $list_color_1="#e7ecf2";
  
  
  $list_color_2="#D1DBE7";
  $position_tarh[1]="نامعلوم";
  $position_tarh[2]="قبول شده براي کارشناسي در سطح ساب ادمين";
  $position_tarh[3]="مصوب شوراي م /ت";
  $position_tarh[4]="رد در شوراي م/ت";
  $position_tarh[5]="ارسال به معاونت پژوهشي";
  $position_tarh[6]="دريافت توسط معاونت پژوهشي";
  $position_tarh[7]="کارشناسي در سطح معاونت پژوهشي";
  $position_tarh[8]="مصوب معاونت پژوهشي";
  $position_tarh[9]="در حال قرارداد";
  $position_tarh[10]="در حال اجرا";
  $position_tarh[11]="خاتمه يافته";
  $position_tarh[12]="بايگاني توسط معاونت پژوهشي";
  $position_tarh[13]="بازگشت به دانشكده";
  $position_tarh[14]="بايگاني توسط دانشكده / مركز";
    $position_tarh[15]="تاييد نام شده";
  $position_tarh[16]="قبول شده براي کارشناسي در سطح  گروه";
   $position_tarh[17]="آرشيو شده در سظح گروه";
   $position_tarh[18]="ارسال به طرح هاي بعد از تصويب گروه"; 
   $position_tarh[19]="ارسال طرح از گروه به دانشکده";
    $position_tarh[20]="بازگشت طرح به گروه";
  $position_tarh[21]="بايگاني توسط مجري"; 
  $position_tarh[22]="مصوب کميته اخلاق دانشکده"; 
    $position_tarh[23]="بررسي در کميته اخلاق"; 
    $position_tarh[24]="منتظر تاييد دريافت ";  
	$position_tarh[25]="مصوب کميته اخلاق دانشگاه";  
	$position_tarh[26]="ثبت شده";  
	$position_tarh[27]="پايان نامه قبل از تصويب";  

	$position_tarh[28]="مصوب";  
$position_tarh[29]="ارسال به دانشگاه براي تاييد قرارداد";  
$position_tarh[30]="بازگشت طرح از دانشگاه به دانشکده";  
$position_tarh[31]="منتظر تاييد استاد راهنما"; 
$position_tarh[32]="تاييد شده توسط استاد راهنما.منتظر تاييد دانشکده";
$position_tarh[33]="دريافت شده توسط دانشکده منتظر تاييده اخلاق";  
$position_tarh[34]="تاييد شده اخلاق منتظر تصويب";
$position_tarh[35]="تصويب شده منتظر آماده قرارداد";  
$position_tarh[36]="آماده قراداد.منتظر ارسال قرارداد امضا شده";
$position_tarh[37]="مختومه";  
$position_tarh[38]="خاتمه يافته با کسب امتياز تعهدات";
$max_record=6000;

 //$position_tarh=array("1"=>"نامعلوم",2=>"قبول شده براي کارشناسي در سطح ساب ادمين",3=>"مصوب شورا? م/ت",4=>"رد در شوراي م/ت",5=>"ارسال به معاونت پژوهشي",6=>"دريافت توسط معاونت پژوهشي",7=>"کارشناسي در سطح معاونت پژوهشي",8=>"مصوب معاونت پژوهشي",9=>"در حال قرارداد",10=>"در حال اجرا",11=>"خاتمه يافته",12=>"بايگاني طرح"); 
?>
