<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


$query="select * from modir_daneshkade where modir_username ='$admin'";

$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade_shora=$myrow_fetched["cod_daneshkade"];



if(isset($action))
{
  if (strcmp($action,"add_karshenas")==0)
  {

     if( strlen(trim($kar_name)) > 0 && strlen(trim($kar_family)) > 0  &&  strlen(trim($kar_email)) > 0 &&  strstr($kar_email, '@') &&  strlen(trim($kar_pass)) > 0 && strcmp(trim($kar_pass),trim($kar_re_pass))==0 )
    {
      $query="select * from karshenas_shora where  kar_shora_email=\"$kar_email\"";
     // echo $query;
      $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");

      if ( mysql_num_rows($result)> 0 )
      {
	  $repeated_record ="repeated_record =1,";
          }
		  else
		  $repeated_record="";
        $query="insert into karshenas_shora set  $repeated_record  mobile='$mobile',kar_shora_name='$kar_name' ,kar_shora_name_e='$kar_name_e', kar_shora_family='$kar_family', kar_shora_family_e = '$kar_family_e',  kar_shora_rade_elmi='$kar_rade_elmi',  kar_shora_takhasos  = '$kar_takhasos', kar_shora_takhasos_e  = '$kar_takhasos_e',  kar_shora_email  ='$kar_email', cod_daneshkade='$cod_daneshkade' , shenasname='$shenasname' , sal_tavalod='$saltavalod' , fath_name='$nampedar', fath_name_e='$nampedar_e', creator='$admin', password='$kar_pass',melli_code='$cod_melli',cod_shora='$cod_shora'";
	//	echo $query;
	//	exit(); 
        $result=mysql_query($query) or die("Error in inserting data into karshenas elmi");

     /* }
      else
       $status="duplicate_entry";*/
    }
    else
      $status="entry_error";
  }

 if (strcmp($action,"delete_shora")==0)
 {
    $query="delete from karshenas_shora where cod_karshenas = \"$delete_id\"";
    
    $result=mysql_query($query) or die("Error in  delete data from karshenas_shora");
 }


  if (strcmp($action,"edit_karshenas_second")==0)
  {
     
     if(   strlen(trim($kar_name)) > 0 && strlen(trim($kar_family)) > 0   )
    {
	  if(strlen(trim($saltavalod)) > 5)
		 $saltavalod="";
      $query="select * from karshenas_shora where cod_karshenas=\"$cod_karshenas\"";
      $result=mysql_query($query) or die("Error in selecting data from kar_shora elmi 12");

      if ( mysql_num_rows($result) > 0 )
      {

        $query="update  karshenas_shora set mobile='$mobile' ,kar_shora_name='$kar_name' ,kar_shora_name_e='$kar_name_e', kar_shora_family='$kar_family', kar_shora_family_e = '$kar_family_e',  kar_shora_rade_elmi='$kar_rade_elmi',  kar_shora_takhasos  = '$kar_takhasos', kar_shora_takhasos_e  = '$kar_takhasos_e',   cod_daneshkade='$cod_daneshkade' , shenasname='$shenasname' , sal_tavalod='$saltavalod' , fath_name='$nampedar', fath_name_e='$nampedar_e',melli_code='$cod_melli' where cod_karshenas='$cod_karshenas'";
      
        $result=mysql_query($query) or die("Error in inserting data into kar_shora elmi");
        $action="";
      }
      else
       $status="duplicate_entry";
    }
    else
    {
      $status="entry_error";
      $action="edit_karshenas";
    }
  }
 
 
  if (strcmp($action,"edit_karshenas")==0) 
 {
 	$query="select * from karshenas_shora where cod_karshenas='$cod_karshenas'";
 	$result=mysql_query($query) or die("Error in selecting data from kar_shoraan"); 	
 	$row_fetched=mysql_fetch_array($result);
 	$kar_shora_name=$row_fetched["kar_shora_name"];
 	$kar_shora_family=$row_fetched["kar_shora_family"];
 	$shenasname=$row_fetched["shenasname"];
 	$sal_tavalod=$row_fetched["sal_tavalod"];
 	$fath_name=$row_fetched["fath_name"];
 	$melli_code=$row_fetched["melli_code"];
 	$kar_shora_type=$row_fetched["kar_shora_type"];
 	$kar_shora_email=$row_fetched["kar_shora_email"];
 	$kar_shora_rade_elmi=$row_fetched["kar_shora_rade_elmi"];
 	$kar_shora_takhasos=$row_fetched["kar_shora_takhasos"];
	$mobile=$row_fetched["mobile"];  	
 }
 else
 {
 	$kar_shora_name="";
 	$kar_shora_family="";
 	$shenasname="";
 	$sal_tavalod="";
 	$fath_name="";
 	$melli_code="";
 	$kar_shora_type="";
 	$kar_shora_email="";
 	$kar_shora_rade_elmi="";
 	$kar_shora_takhasos="";
 	$mobile="";
 }



 
}

?>
 

<?



   $query="select * from karshenas_shora  where cod_shora=\"$cod_shora\"  order by  kar_shora_name";
   $query="select * from karshenas_shora,modir_daneshkade  where  cod_shora=\"$cod_shora\"  and modir_daneshkade.modir_username =karshenas_shora.creator and ( modir_daneshkade.modir_type='1' or  modir_daneshkade.modir_type='4')";
 $query="select * from karshenas_shora where (cod_daneshkade='$cod_daneshkade_shora' or cod_daneshkade_second='$cod_daneshkade_shora' or cod_daneshkade_third='$cod_daneshkade_shora' or cod_daneshkade_4='$cod_daneshkade_shora' or cod_daneshkade_5='$cod_daneshkade_shora' or cod_daneshkade_6='$cod_daneshkade_shora' or cod_daneshkade_7='$cod_daneshkade_shora' or cod_daneshkade_8='$cod_daneshkade_shora' or cod_daneshkade_9='$cod_daneshkade_shora' or cod_daneshkade_10='$cod_daneshkade_shora')";
  
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"600\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"0\" width=\"600\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
   // echo "<td width=\"80\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">کلمه عبور</td>";
    //echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    //echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"150\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام خانوادگي</td>";
    echo "<td width=\"164\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام</td>";
     echo "<td width=\"164\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">کد</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    $mycod_karshenas = $myrow_fetched["cod_karshenas"];
    echo "<tr bgcolor=\"$color\">";
    echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
   // echo "<td width=\"80\"><p align=\"center\"><a href=\"change_users_password.phtml?admin=$admin&seed=$seed&db=karshenas_shora&username=".$myrow_fetched["cod_karshenas"]."&user_field=cod_karshenas\" ><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
   // echo "<td width=\"27\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_shora_pajoheshi.phtml?cod_shora=$cod_shora&mainwindow=add_shora_pajoheshi.phtml&admin=$admin&seed=$seed&action=delete_shora&delete_id=".$myrow_fetched["cod_karshenas"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
//    echo "<td width=\"27\"><p align=\"center\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></td>";
    //echo "<td width=\"47\"><p align=\"center\"><a href='$PHP_SELF?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas&action=edit_karshenas&cod_shora=$cod_shora'><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></a></td>";
    $mycod_karshenas = $myrow_fetched["cod_karshenas"];
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenas_shora_detail.phtml?cod_shora=$cod_shora&admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["kar_shora_family"],0,18)."</a></p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenas_shora_detail.phtml?cod_shora=$cod_shora&admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["kar_shora_name"],0,18)."</a></p></td>";
     echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenas_shora_detail.phtml?cod_shora=$cod_shora&admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["cod_karshenas"],0,18)."</a></p></td>";
    echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   }
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
 //   echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
   // echo "<td width=\"27\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    //echo "<td width=\"27\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"133\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"134\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
        echo "<td width=\"134\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
    echo "</tr>";

   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>




