
<?php

     include("include/include.phtml");
     header_forms($admin,$seed);
	 include("include/database-connect.phtml");
     include("include/styles.phtml");
  
  	$q1="select * from modir_daneshkade,daneshkade where modir_username='$admin' and daneshkade.cod_daneshkade=modir_daneshkade.cod_daneshkade";
  	    			$rslt=mysql_query($q1);
  	    			$rff=mysql_fetch_array($rslt);
  	    			$modir_mostaghel_type=$rff["modir_mostaghel_type"];
					 $mostaghel=$rff["mostaghel"];
					 $cod_daneshkade=$rff["cod_daneshkade"];
					 
  
     echo "<br>";
?>


 


<TABLE cellSpacing="0" cellPadding="0" width="500" border="0">
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/title-user-define.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>



<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<tr>
<td >
<?

$status="";
if(isset($action))
{
  if (strcmp($action,"add_admin")==0)
  {

    if(strlen(trim($admin_dan_name)) > 0 &&strlen(trim($admin_dan_english_family)) > 0  &&    strlen(trim($admin_dan_username)) > 0  &&  strlen(trim($admin_dan_family)) > 0 && strlen(trim($admin_dan_email)) > 0 && strlen(trim($admin_dan_pass)) > 0 && strlen(trim($admin_dan_repass)) > 0 && strcmp(trim($admin_dan_pass),trim($admin_dan_repass))==0  && strstr($admin_dan_email, '@') && !strstr($admin_dan_username,'@') )
    {
      $query="select * from modir_daneshkade where modir_username=\"$admin_dan_username\"";

      $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");

      if ( mysql_num_rows($result) <= 0 )
      {
        $query="insert into modir_daneshkade set   moaven_or_daneshjoyee='0', modir_english_name='$admin_dan_english_name' ,modir_english_family='$admin_dan_english_family', modir_username='$admin_dan_username', cod_daneshkade = '$cod_daneshkade', modir_name='$admin_dan_name', modir_family = '$admin_dan_family', modir_email ='$admin_dan_email' , modir_tel ='$admin_dan_tel' , modir_fax ='$admin_dan_fax', modir_mobile ='$admin_dan_mobile', password='$admin_dan_pass',modir_type =5 ";
 
        $result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
      }
      else
       $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }
  
  if (strcmp($action,"delete_admin_dan")==0)
  {
    if(strlen($delete_id) > 0 )
    {
      $query="delete from modir_daneshkade where cod_modir=\"$delete_id\"";
	 
      $result=mysql_query($query) or die("Error in inserting data into modir daneshkade");
    }
  }
}

?>



<? echo "<form name=\"add_admin_daneshkade\" method=\"post\"  action=\"$PHP_SELF?action=add_admin&admin=$admin&seed=$seed&daneshkade=$daneshkade\">"; ?>
<table border="0" width="490">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>


  <tr>
    <td width="25%"><input type="text" name="admin_dan_name"  class="edit-user"  dir=RTL   ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام </td>
  </tr>
   
  <tr>
    <td width="25%"><input type="text" name="admin_dan_family"  class="edit-user"   dir=RTL   ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>

  <tr>
    <td width="25%"><input type="text" name="admin_dan_english_family"  class="edit-user" dir=RTL    ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام مرکز</td>
  </tr>

  <tr>
    <td width="25%"><input type="edit" name="admin_dan_username"  class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>نام کاربري</td>
  </tr>
   
  <tr>
    <td width="25%"><input type="text" name="admin_dan_email"  class="edit-user" ></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
  <tr>
    <td width="25%"><input type="text" name="admin_dan_tel"  class="edit-user"></td>
    <td width="25%" class="tahoma1">تلفن</td>
  </tr>
  <tr>
    <td width="25%"><input type="text" name="admin_dan_mobile"  class="edit-user"></td>
    <td width="25%" class="tahoma1">موبايل</td>
  </tr>
  <tr>
    <td width="25%"><input type="text" name="admin_dan_fax"  class="edit-user"></td>
    <td width="25%" class="tahoma1">فکس</td>
  </tr>
  <tr>
    <td width="25%"><input type="password" name="admin_dan_pass"  class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>کلمه عبور</td>
  </tr>
  <tr>
    <td width="25%"><input type="password" name="admin_dan_repass"  class="edit-user"></td>
    <td width="25%" class="tahoma1"><span class="star-message">*</span>تکرار کلمه عبور</td>
  </tr>
  <tr>
    <td width="50%" colspan="2" align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
  

</table>
</td>
</tr>

</table>
<table border="0" width="500">
 
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><span class="star-message">توجه :نام کاربري بايد فاقد @ باشد</span></td>
</tr>

</table>


 <?
   $query="select * from modir_daneshkade where cod_daneshkade=\"$cod_daneshkade\" and modir_type='5'";
 
   $result=mysql_query($query) or die("Error in selecting data from modir daneshkade");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
     echo "<td  height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">کلمه عبور</p></td>";
    
echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">حذف</p></td>";
    echo "<td    height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">ويرايش</p></td>";
    echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام خانوادگي</p></td>";
    echo "<td   height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام</p></td>";
    echo "<td     height=\"20\" class=\"tahoma1\" align=\"center\"><p align=\"center\" class=\"tahoma1\">نام کاربري</p></td>";
     echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    $cod_modir=$myrow_fetched["cod_modir"];
	 $moaven_or_daneshjoyee=$myrow_fetched["moaven_or_daneshjoyee"];

    echo "<tr bgcolor=\"$color\">";
     echo "<td  ><p align=\"center\"><a href=\"change_users_password.phtml?admin=$admin&seed=$seed&db=modir_daneshkade&username=".$cod_modir."&user_field=cod_modir\" ><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
	
	if(strcmp(trim($moaven_or_daneshjoyee),'0')==0)
       $moaven_or_daneshjoyee_dsc="معاون پؤوهشي د/م";
	else
       $moaven_or_daneshjoyee_dsc="مسئول طرح هاي دانشجويي";

    
    echo "<td  ><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_admin_dan.phtml?mainwindow=admin_daneshkade.phtml&admin=$admin&seed=$seed&daneshkade=$daneshkade&action=delete_daneshkade&delete_id=".$myrow_fetched["cod_modir"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td  ><p align=\"center\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Change Password\" ></td>";

    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".substr($myrow_fetched["modir_family"],0,18)."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".substr($myrow_fetched["modir_name"],0,18)."</p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\">".$myrow_fetched["modir_username"]."</p></td>";
     echo "</tr>";
   }
 
   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>


