<?
include("include/database-connect.phtml");
include("include/include.phtml");

include("include/numper.class.php");


global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;

$karshenasi_koll_1=mablagh_karshenasi($cod_tarh);


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";

 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type == 2 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login/");
   exit();
  }
 }
 
 // $cod_tarh="84-02-06-008";
 
 
  $query="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
  $result=mysql_query($query) or die("Error10");
  if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	$mojri=$row_fetched["mojri_code"];
 	$heiat_elmi=$row_fetched["heiat_elmi"];
 	$start_time=$row_fetched["start_time"];
    $start_time_tmp=$start_time;
 	$pish_pardakht=$row_fetched["pish_pardakht"];
 	$payanname=$row_fetched["payanname"];
 	$nazerin=$row_fetched["nazerin"];
 	$unnazerin=$row_fetched["unnazerin"];
 	$time_month=$row_fetched["time_month"];
 	$zarib_maliat=$row_fetched["maliat"];
    $exists=1; 	
    
 } 	
 else
 {
 	$payanname="0";
 	$mojri="0";
 	$heiat_elmi="0";
 	$start_time="0";
 	$pish_pardakht="0";
 	$nazerin="0";
 	$time_month="0";
 	$unnazerin="0";
    $exists=0;
 }
 
 //$start_time="1385-02-12";
// $time_month="15";
 if( $start_time > 0 && $time_month > 0 )
 {
   $year=substr($start_time,0,4);
   $month=substr($start_time,5,2);
   $day=substr($start_time,8,2);
   $start_time=$day."/".$month."/".$year;
  // $month_add=$time_month+$month;
   $month_add=$time_month;
  // echo $month_add;
  // exit();
   for($i=1; $i<=$month_add;$i++)
   {
   	$month=$month+1;
    if($month >12 )
    {
      //$year_add=(int)($month_add/12); 
      $year_add++;
 	  $year=$year+1;	 	 	
      //$month=$month_add-($year_add*12); 
	  $month=1;    
     // if($month==0)
 	 //   $month=12;  
    }
    //else
     // $month=$month_add;
   }
  
   $end_time=$day."/".$month."/".$year;
 }
 else
 {
   $end_time="تعريف نشده";   
 }
       
    
    $query1="select * from jalase_shora , jalase_shora_tarh where jalase_shora.creator=jalase_shora_tarh.creator and jalase_shora.shomare_jalase=jalase_shora_tarh.shomare_jalase  and jalase_shora_tarh.cod_tarh='$cod_tarh'";
    $result10=mysql_query($query1) or die("Error11");
    if(mysql_num_rows($result10) >0)
    {
      $rf100=mysql_fetch_array($result10);
	  $tarikh_jalase=$rf100["tarikh_jalase"];	
	  $year=substr($tarikh_jalase,0,4);
      $month=substr($tarikh_jalase,5,2);
      $day=substr($tarikh_jalase,8,2);
      $tarikh_jalase=$day."/".$month."/".$year;
      
    }
    else
      $tarikh_jalase=" نا معلوم ";
 
   
   
   $query1="select * from gozaresh_gharardad where cod_tarh='$cod_tarh'";
   $result500=mysql_query($query1)or die("error12");
   if(mysql_num_rows($result500) > 0)
   {
   	$gozaresh_cnt=mysql_num_rows($result500);
   }
   else
   	$gozaresh_cnt=0;

   
   
   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";
	
   $result1=mysql_query($query1) or die("Error14");
   $query="select distinct mojri.* from mojri_tarh , tarh,mojri  where mojri.mojri_code=mojri_tarh.mojri_code and mojri_tarh.cod_tarh = tarh.cod_tarh  and tarh.cod_tarh=\"$cod_tarh\" and mojri_tarh.mojri_or_hamkar='0'  ";
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh");
    
   if(mysql_num_rows($result) > 0 || mysql_num_rows($result1) > 0)
   {
   	$i=0;
  
	while($row_fetched1=mysql_fetch_array($result1))
    {
      
      $cod_mojri=$row_fetched1["email"];
      if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
   	    $checked="1";
      }
      else
      {
   	    $checked="";
      }
  
     if(strcmp($checked,"1")==0)
     { 
      $name_family=$row_fetched1["name"]." ".$row_fetched1["family"];
     }
 
   }
 
 
 
   while($row_fetched=mysql_fetch_array($result))
   {
  
    $cod_mojri=$row_fetched["mojri_code"];
    
    if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
      	
   	    $checked1="1";
      }
     else
      {
   	    $checked1="";
      }
   
 
    if(strcmp($checked1,"1")==0)
    {  
      
      $name_family=$row_fetched["name"]." ".$row_fetched["family"];
  
    }
    
   }
 }
else // if reccount of tarh  < =0
{
 $name_family="توسط مجري تعيين نشده";
}

   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";
	
   $result100=mysql_query($query1) or die("Error14");
   if(mysql_num_rows($result100))
   {
       $rf_mojri=mysql_fetch_array($result100);
      $bank_name=$rf_mojri["bank_name"];
 	   $hesab=$rf_mojri["hesab"];
	   $q1="select * from hesab_type where  hesab_type='$bank_name'";
	   $rs100=mysql_query($q1) or die("error");
	   if(mysql_num_rows($rs100)>0)
	   {
	        $rf500=mysql_fetch_array($rs100);
	        $hesab_type_desc  =$rf500["hesab_type_desc"];
	        $shomare_hesab=   $hesab_type_desc.$hesab;
        }
	   else
	        $shomare_hesab="";
	 }
	 else
	   $shomare_hesab="";
	   

   $query1="select * from answer_mojri_gharardad  where  cod_tarh='$cod_tarh' and bank_name !='-1'";
	
   $result100=mysql_query($query1) or die("Error14");
   if(mysql_num_rows($result100)>0)
   {
       $rf_mojri=mysql_fetch_array($result100);
      $bank_name=$rf_mojri["bank_name"];
 	   $hesab=$rf_mojri["hesab"];
	   $q1="select * from hesab_type where  hesab_type='$bank_name'";
	   $rs100=mysql_query($q1) or die("error");
	   if(mysql_num_rows($rs100)>0)
	   {
	        $rf500=mysql_fetch_array($rs100);
	        $hesab_type_desc  =$rf500["hesab_type_desc"];
	        $shomare_hesab=   $hesab_type_desc.$hesab;
        }
	   else
	        $shomare_hesab="";
	 }
 	   
	   
	   
//--------------------------------------------------------------------------
if(strlen(trim($name_family)) <= 0)
   $name_family="توسط مجري تعيين نشده";

  $query="select * from tarh where cod_tarh='$cod_tarh' and version=\"-1\" ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $eatebare_sazmanha=$row_fetched["eatebare_sazmanha"];
  $tarh_type= $row_fetched["tarh_type"];
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $nezarat=$row_fetched["nezarat"];  // sabet nezarat
   $entezar=$row_fetched["entezar"];  // entezar be ezaye har mah
  $gozaresh_ezafi  =$row_fetched["gozaresh_ezafi"];  // be ezaye har gozaresh ezafi be joz gozaresh payani
  
  
   $cod_daneshkade = $row_fetched["cod_daneshkade"];
  $query="select * from daneshkade where cod_daneshkade='$cod_daneshkade' ";
  
  $result_daneshkade=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched_daneshkade=mysql_fetch_array($result_daneshkade);
  $daneshkade_name=$row_fetched_daneshkade["daneshkade_name"];
  $daneshkade_tel =$row_fetched_daneshkade["daneshkade_tel"];
  $daneshkade_fax =$row_fetched_daneshkade["daneshkade_fax"];
  $signer_address  =$row_fetched_daneshkade["signer_address"];
    $static_second_part  =$row_fetched_daneshkade["static_second_part"];
  $signer_name=$row_fetched_daneshkade["signer_name"];
  
$tarh_name=str_replace("&#61537;",".",$tarh_name); 
$tarh_name=str_replace("&#61543;",".",$tarh_name); 
$tarh_name=str_replace("&#61541;",".",$tarh_name);  
$tarh_name=str_replace("&#1740;","ي",$tarh_name); 
$tarh_name=str_replace("&#1740","ي",$tarh_name);
  
  $q="select * from tarhtype where tarh_type='$tarh_type'";
  $q_res=mysql_query($q) or die("Error");
  $rf=mysql_fetch_array($q_res) or die("Error");
  $tarh_type_desc=trim($rf["tarh_type_english_desc"]);
   $tarh_type_desc="";
  if(strcmp($tarh_type_desc,"HSR")==0)
    $tarh_type_desc="(اچ اس آر)";
  else
  {
  	$q="select * from tarh,tarhtype_2 where tarh.tarh_type_2=tarhtype_2.tarh_type and cod_tarh='$cod_tarh' and grant_tarh='1'";
  	$q_res=mysql_query($q) or die("Error");
  	if(mysql_num_rows($q_res) > 0)
  	{
  	  $rf_grant=mysql_fetch_array($q_res);
	  $tarh_type_desc=$rf_grant["tarh_type_desc"];		
	}  
  }
    
  $q_payan_name="select * from tarh,darajeelmi  where  payan_name='1' and  cod_tarh='$cod_tarh' and darajeelmi.darajeelmi = tarh.payan_name_daraje_elmi";
  $q_res=mysql_query($q_payan_name) or die("Error");
  if(mysql_num_rows($q_res) > 0 )
  {
  	$rf_payanname=mysql_fetch_array($q_res);
  	$maghtaa_payan_name=$rf_payanname["darajeelmi_english_desc"];
  	$tarh_type_desc=$tarh_type_desc."($maghtaa_payan_name مقطع پايان نامه :)";
  }
    
  if(strcmp($eatebare_sazmanha,'1')==0)
   $eatebar_sazmanha="با تامين اعتبار از سازمانهاي ديگر";
  else
   $eatebar_sazmanha=""; 
  
  //-------------------- قسمت مربوط به عقد قرارداد
  
    
  $mablagh_aghd_gharardad = $row_fetched["mablagh_aghd_gharardad"];
  
  if($mablagh_aghd_gharardad  > 0)
  {
  	$a=($gozaresh_cnt-1)*$gozaresh_ezafi  ;
	//$a=0;
  	$b=$nezarat;
  	// محاسبه گزارش دوم تا ماه نهايي ضربدر 5000 ريال
  	$qr="select * from gozaresh_gharardad where cod_tarh='$cod_tarh' and marhale='2'";
	$resultr=mysql_query($qr) or die("error15");
	$rft=mysql_fetch_array($resultr);	
	$second_gozaresh=$rft["date_gozaresh"]; 
	 
	$year=substr($second_gozaresh,0,4);
    $month=substr($second_gozaresh,5,2);
    $day=substr($second_gozaresh,8,2);
  //  echo $year.":".$month.":".$day;
    $month_remain=0;
  //  echo $end_time."<br>";
    for($k=1;$k<=$time_month;$k++)
    {      	
      $month=$month+1;
      if($month>12)
      {
        $month=1;
        $year=$year+1;
      }
      //$month1=str_replace($month,"0","");
     // $month1=trim($month1);
     
      $my_end_time=substr($end_time,3,7);
	  //$date_tmp=$day."/".$month."/".$year;
       $date_tmp=$month."/".$year; 
      if(strcmp($my_end_time,$date_tmp)==0)
      {
        $month_remain=$k;  // mohasebe teadad mahe dovvom ta gozaresh akhar
        
      }
     // echo $date_tmp.":".$my_end_time."<br>";  
     }
    // echo $month_remain.":".$date_tmp.":".$my_end_time.":".$second_gozaresh.":".$month_remain.":".$time_month.":".$month.":".$year.":".$end_time.":".$date_tmp.":".$my_end_time.":". $date_tmp.":".$end_time;
   //  exit();
  // exit();
     $c=$month_remain*$entezar;  // this is for old version
	 $c=$time_month*$entezar;
     $c1=$c;
	 //echo $a."<br>".$b."<br>".$c."<br>".$month_remain;
	 //exit();
	 $nezarat_koll=$a+$b+$c; // نظارت بخش اول کار
	

/*	echo "month remaining : ".$month_remain."<br>";
     echo "gozaresh cnt :".$gozaresh_cnt."<br>";
	  echo "gozaresh ezafi :".$gozaresh_ezafi."<br>";
	 echo "(gozaresh_cnt-1)*gozaresh_ezafi: ".$a."<br>";
	 echo "nezarat sabet :".$b."<br>";
	  echo "entezar :".$entezar."<br>";
	 echo "month remaining * entezar sabet :".$c."<br>";
	 echo "nezarat_koll :".$nezarat_koll."<br>";
 
	 exit();
	*/  
	  
	  // محاسبه هزينه پرسنلي و محاسبه ماليات آن
 	  $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1' order by activity_type ";
      $result00=mysql_query($query) or die("Error in selecting data from hazine personnel");
      if(mysql_num_rows($result00) > 0)
      {
     
        $mycount=0;
       while($row_fetched00=mysql_fetch_array($result00))
       {
  
       $my_summary = $row_fetched00["per_hour"]*$row_fetched00["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       }       
      }
      $hazine_personnel=$mycount;
      
      $darsad_50=$mablagh_aghd_gharardad*50/100;
      
	  
	  $mablagh_koll=($mablagh_aghd_gharardad+$nezarat_koll)*100/(100-$zarib_maliat);
	  	//$mablagh_koll=$mablagh_aghd_gharardad+$nezarat_koll+$maliat_koll;
		
	 
      /*
      if($hazine_personnel > $darsad_50)
	  {	    	
	   //$x=($mablagh_aghd_gharardad*5)/100; 	
	   $y=($nezarat_koll*100)/95;
	   //$maliat_koll=$x+$y;
	   $aa=($mablagh_aghd_gharardad-$hazine_personnel)*100/95;
	   $mablagh_koll=$hazine_personnel+$y+$aa;
	   $nezarat_maliat=$nezarat_koll*100/95;
	  }
	  else
	   {
	   //	$mablagh_aghd_gharardad=($mablagh_aghd_gharardad*100)/95;
	   	//$maliat_koll=($mablagh_aghd_gharardad+$nezarat_koll)*100/95;
	   	$mablagh_koll=$mablagh_aghd_gharardad+$nezarat_koll;
	   	$mablagh_koll=$mablagh_koll*100/95;
	   	$nezarat_maliat=$nezarat_koll*100/95;
	   }
	  */
	  
	  /*
      $x=($hazine_personnel*5)/100;
     	  
      $y=($nezarat_koll*5)/100;
      $maliat_koll=$x+$y;
	  */
  	 //-------------------marhale 1 ------------------------------------------
  	 
	  
  	 if($cod_marhale!=0 && $cod_marhale!=100){
  	 	
				$query="select * from gozaresh_gharardad  where cod_tarh='$cod_tarh' and marhale='$cod_marhale' order by marhale asc ";
				$result1=mysql_query($query) or die("Error");
				$cntr=1;
				$mablagh12=0;
				while($rf66=mysql_fetch_array($result1))
				{
				// echo $cntr;
				   
				  	$mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
				  	//$nezarat=$rf66["mablagh"]*$nezarat_koll/100;
				  	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
				  	
					$maliat_marhale_n=$mablagh_marhale_n*$zarib_maliat/100;
					
					 $hagh_ol_zahme_karshenasi_n= $nezarat_koll*$rf66["mablagh"]/100; 	 
					 $nezarat=$hagh_ol_zahme_karshenasi_n;
				/////	$mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n;
				//	$mablagh_khales_mojri=$mablagh_khales_mojri-$hagh_ol_zahme_karshenasi_n;
					 $mablagh_khales_mojri_n=$mablagh_aghd_gharardad*$rf66["mablagh"]/100;
				  	   
				}
	  
  	 }  
  	 else if($cod_marhale==0){ 
  	 	
	  //-----------------------------------------------------------------------
  	   $query="select * from gozaresh_gharardad where marhale='0' and cod_tarh='$cod_tarh'";
      $result88=mysql_query($query) or die("Error");
		      if(mysql_num_rows($result88) > 0)
			  {
			  	$rf66=mysql_fetch_array($result88);
			  ////  if($hazine_personnel > $darsad_50)
			  ////  {
			      $mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
			      $maliat_marhale_n=$mablagh_marhale_n*$zarib_maliat/100;
			       $hagh_ol_zahme_karshenasi_n= $nezarat_koll*$rf66["mablagh"]/100;
				  $mablagh_khales_mojri_n=$mablagh_marhale_n-$maliat_marhale_n;
				   $mablagh_khales_mojri_n= $mablagh_khales_mojri_n-$hagh_ol_zahme_karshenasi_n;
			      
			  		
			  ////  }
			 ////   else
			 ////   {
			 ////     $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
			 ////     $mablagh_marhale_0=($darsad_marhale+($darsad_marhale/100))*100/95;
			 ////     $maliat_marhale_0=$mablagh_marhale_0*5/100;
			 //// 	  $hagh_ol_zahme_karshenasi_0= $nezarat_koll*$rf66["mablagh"]/100;
			////	  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0-$hagh_ol_zahme_karshenasi_0;	      	      
			  		      
			  ////  }
			    
			
			  }
	    
	  	else{}
	  
	//  echo "mohsen <br>".$end_time."<br>".$month_remain."<br>".$mablagh_marhale_0."<br>".$mablagh_aghd_gharardad."<br>".$maliat_1."<br>".$hazine_personnel;
	  //exit();
	   //$mablagh_koll_tarh=$maliat_koll+$nezarat_koll+$mablagh_aghd_gharardad;
	   
	  //-------------------marhale Nahayee ------------------------------------------
  	 }
  	 else{
  	 	
  	 $a=$static_second_part;
	  $query="select * from gozaresh_gharardad where marhale='100' and cod_tarh='$cod_tarh'";
      $result=mysql_query($query) or die("Error");
      $b=0;
	  if(mysql_num_rows($result) > 0)
	  {
			  
			  	$rf66=mysql_fetch_array($result);
			 ////  if($hazine_personnel > $darsad_50)
		     ////  {
		  	      $mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
		  	      
		  	   ///   $nezarat=125000+$mablagh_marhale_end/100;
		       
			      $maliat_marhale_n=$mablagh_marhale_n*$zarib_maliat/100;
				 
			       $mablagh_khales_mojri_n=$mablagh_marhale_n-$maliat_marhale_n;
			      //$mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
				///  $mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
				
				
				 $mablagh_khales_mojri_n=$mablagh_aghd_gharardad*$rf66["mablagh"]/100;
		  	     
			  	   $hagh_ol_zahme_karshenasi_n= $nezarat_koll*$rf66["mablagh"]/100; 	
			  		
		       
		        
			 $date=$rf66["date_gozaresh"];
		 $year=substr($date,0,4);
		 $month=substr($date,5,2);
		 $day=substr($date,8,2);
		 $date_end=$day."/".$month."/".$year; 
			   
			  
			   
			
		  }
  
  
  }
//$mablagh=$nezarat_koll+$maliat_koll+$mablagh_aghd_gharardad;

  
  $emtiaz1=($mablagh_koll/10000000)*2.5;
  $int_emtiaz=(int)$emtiaz1;
  $real_emtiaz=$emtiaz1-$int_emtiaz;
  if($real_emtiaz > .75)
    $int_emtiaz++;  

    
  $cod_daneshkade = $row_fetched["cod_daneshkade"];
  $query="select * from daneshkade where cod_daneshkade='$cod_daneshkade' ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $daneshkade_name=$row_fetched["daneshkade_name"];
  
  if(strlen(trim($daneshkade_name)) <=0)
    $daneshkade_name="تعريف نشده";
  
if($start_time==0)
  $start_time="تعريف نشده";
    
//if($end_time==0)
 // $end_time="تعريف نشده";
  
if($time_month==0)
  $time_month="تعريف نشده"; 

$mablagh_koll_tarh=number_format($mablagh_koll_tarh);
 $tarikh_jalase="6/4/1385";
 
$query="select * from karshenasan,karshenas_type,karshenasan_tarh where karshenasan.karshenas_type=karshenas_type.karshenas_type and karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas and karshenasan_tarh.cod_tarh='$cod_tarh' and karshenas_type.karshenas_type_english_desc='viewer'  ";
//echo $query;
$result=mysql_query($query) or die("Error");
if(mysql_num_rows($result) > 0)
{
	$nazer_rf=mysql_fetch_array($result);
	$namer_name=$nazer_rf["karshenas_name"]." ".$nazer_rf["karshenas_family"];
	
} 
else
 $namer_name="نامعلوم";

 
 $tarh_name=str_replace("&#61537;",".",$tarh_name); 
 $tarh_name=str_replace("&#61543;",".",$tarh_name); 
 $tarh_name=str_replace("&#61541;",".",$tarh_name);  
 $tarh_name=str_replace("&#1740;","ي",$tarh_name); 
 $tarh_name=str_replace("&#1740","ي",$tarh_name);
 
 
$qry="select * from   modir_daneshkade,modir_daneshkade_tarh where modir_daneshkade_tarh.cod_modir =modir_daneshkade.cod_modir  and modir_daneshkade_tarh.cod_tarh='$cod_tarh' and modir_daneshkade.modir_type='5' ";

$rsss=mysql_query($qry) or dir("error");

$rfff=mysql_fetch_array($rsss);

$sub_subadmin=$rfff["modir_english_family"];


 
$cntr=$cod_marhale;
if($cntr==0)
       $marhale_jadval_zamani=" اول ";
    
	if($cntr==1)
       $marhale_jadval_zamani=" دوم ";
    
    if($cntr==2)
       $marhale_jadval_zamani=" سوم ";

    if($cntr==3)
       $marhale_jadval_zamani=" چهارم ";
	
	if($cntr==4)
       $marhale_jadval_zamani=" پنجم ";
	
	 if($cntr==5)
       $marhale_jadval_zamani=" ششم ";  

	if($cntr==100)
       $marhale_jadval_zamani=" مرحله نهايي ";
  }     
 $mablagh_marhale_n=number_format($mablagh_marhale_n);
  $maliat_marhale_n=number_format($maliat_marhale_n);
   $mablagh_khales_mojri_n=number_format($mablagh_khales_mojri_n);
   $hagh_ol_zahme_karshenasi_n=number_format($hagh_ol_zahme_karshenasi_n);
header('Content-type: application/msword');
?>
{\rtf1\adeflang1065\ansi\ansicpg1256\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs1065{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbidi \fnil\fcharset178\fprq2{\*\panose 00000700000000000000}Titr{\*\falt Courier New};}
{\f40\fbidi \froman\fcharset0\fprq0{\*\panose 00000000000000000000}Arabic Style{\*\falt Times New Roman};}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
{\fdbmajor\f31501\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fhimajor\f31502\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria;}
{\fbimajor\f31503\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\flominor\f31504\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
{\fdbminor\f31505\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fhiminor\f31506\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}
{\fbiminor\f31507\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f340\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}{\f341\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}
{\f343\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}{\f344\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}{\f345\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f346\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}
{\f347\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}{\f348\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}{\f360\fbidi \fmodern\fcharset238\fprq1 Courier New CE;}{\f361\fbidi \fmodern\fcharset204\fprq1 Courier New Cyr;}
{\f363\fbidi \fmodern\fcharset161\fprq1 Courier New Greek;}{\f364\fbidi \fmodern\fcharset162\fprq1 Courier New Tur;}{\f365\fbidi \fmodern\fcharset177\fprq1 Courier New (Hebrew);}{\f366\fbidi \fmodern\fcharset178\fprq1 Courier New (Arabic);}
{\f367\fbidi \fmodern\fcharset186\fprq1 Courier New Baltic;}{\f368\fbidi \fmodern\fcharset163\fprq1 Courier New (Vietnamese);}{\f680\fbidi \froman\fcharset238\fprq2 Cambria Math CE;}{\f681\fbidi \froman\fcharset204\fprq2 Cambria Math Cyr;}
{\f683\fbidi \froman\fcharset161\fprq2 Cambria Math Greek;}{\f684\fbidi \froman\fcharset162\fprq2 Cambria Math Tur;}{\f687\fbidi \froman\fcharset186\fprq2 Cambria Math Baltic;}{\f688\fbidi \froman\fcharset163\fprq2 Cambria Math (Vietnamese);}
{\f720\fbidi \fswiss\fcharset238\fprq2 Tahoma CE;}{\f721\fbidi \fswiss\fcharset204\fprq2 Tahoma Cyr;}{\f723\fbidi \fswiss\fcharset161\fprq2 Tahoma Greek;}{\f724\fbidi \fswiss\fcharset162\fprq2 Tahoma Tur;}
{\f725\fbidi \fswiss\fcharset177\fprq2 Tahoma (Hebrew);}{\f726\fbidi \fswiss\fcharset178\fprq2 Tahoma (Arabic);}{\f727\fbidi \fswiss\fcharset186\fprq2 Tahoma Baltic;}{\f728\fbidi \fswiss\fcharset163\fprq2 Tahoma (Vietnamese);}
{\f729\fbidi \fswiss\fcharset222\fprq2 Tahoma (Thai);}{\flomajor\f31508\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}{\flomajor\f31509\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}
{\flomajor\f31511\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}{\flomajor\f31512\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}{\flomajor\f31513\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}
{\flomajor\f31514\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}{\flomajor\f31515\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}{\flomajor\f31516\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}
{\fdbmajor\f31518\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}{\fdbmajor\f31519\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}{\fdbmajor\f31521\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}
{\fdbmajor\f31522\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}{\fdbmajor\f31523\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\fdbmajor\f31524\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}
{\fdbmajor\f31525\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}{\fdbmajor\f31526\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}{\fhimajor\f31528\fbidi \froman\fcharset238\fprq2 Cambria CE;}
{\fhimajor\f31529\fbidi \froman\fcharset204\fprq2 Cambria Cyr;}{\fhimajor\f31531\fbidi \froman\fcharset161\fprq2 Cambria Greek;}{\fhimajor\f31532\fbidi \froman\fcharset162\fprq2 Cambria Tur;}
{\fhimajor\f31535\fbidi \froman\fcharset186\fprq2 Cambria Baltic;}{\fhimajor\f31536\fbidi \froman\fcharset163\fprq2 Cambria (Vietnamese);}{\fbimajor\f31538\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}
{\fbimajor\f31539\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}{\fbimajor\f31541\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}{\fbimajor\f31542\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}
{\fbimajor\f31543\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\fbimajor\f31544\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}{\fbimajor\f31545\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}
{\fbimajor\f31546\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}{\flominor\f31548\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}{\flominor\f31549\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}
{\flominor\f31551\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}{\flominor\f31552\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}{\flominor\f31553\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}
{\flominor\f31554\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}{\flominor\f31555\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}{\flominor\f31556\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}
{\fdbminor\f31558\fbidi \froman\fcharset238\fprq2 Times New Roman CE;}{\fdbminor\f31559\fbidi \froman\fcharset204\fprq2 Times New Roman Cyr;}{\fdbminor\f31561\fbidi \froman\fcharset161\fprq2 Times New Roman Greek;}
{\fdbminor\f31562\fbidi \froman\fcharset162\fprq2 Times New Roman Tur;}{\fdbminor\f31563\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\fdbminor\f31564\fbidi \froman\fcharset178\fprq2 Times New Roman (Arabic);}
{\fdbminor\f31565\fbidi \froman\fcharset186\fprq2 Times New Roman Baltic;}{\fdbminor\f31566\fbidi \froman\fcharset163\fprq2 Times New Roman (Vietnamese);}{\fhiminor\f31568\fbidi \fswiss\fcharset238\fprq2 Calibri CE;}
{\fhiminor\f31569\fbidi \fswiss\fcharset204\fprq2 Calibri Cyr;}{\fhiminor\f31571\fbidi \fswiss\fcharset161\fprq2 Calibri Greek;}{\fhiminor\f31572\fbidi \fswiss\fcharset162\fprq2 Calibri Tur;}
{\fhiminor\f31575\fbidi \fswiss\fcharset186\fprq2 Calibri Baltic;}{\fhiminor\f31576\fbidi \fswiss\fcharset163\fprq2 Calibri (Vietnamese);}{\fbiminor\f31578\fbidi \fswiss\fcharset238\fprq2 Arial CE;}
{\fbiminor\f31579\fbidi \fswiss\fcharset204\fprq2 Arial Cyr;}{\fbiminor\f31581\fbidi \fswiss\fcharset161\fprq2 Arial Greek;}{\fbiminor\f31582\fbidi \fswiss\fcharset162\fprq2 Arial Tur;}{\fbiminor\f31583\fbidi \fswiss\fcharset177\fprq2 Arial (Hebrew);}
{\fbiminor\f31584\fbidi \fswiss\fcharset178\fprq2 Arial (Arabic);}{\fbiminor\f31585\fbidi \fswiss\fcharset186\fprq2 Arial Baltic;}{\fbiminor\f31586\fbidi \fswiss\fcharset163\fprq2 Arial (Vietnamese);}}{\colortbl;\red0\green0\blue0;\red0\green0\blue255;
\red0\green255\blue255;\red0\green255\blue0;\red255\green0\blue255;\red255\green0\blue0;\red255\green255\blue0;\red255\green255\blue255;\red0\green0\blue128;\red0\green128\blue128;\red0\green128\blue0;\red128\green0\blue128;\red128\green0\blue0;
\red128\green128\blue0;\red128\green128\blue128;\red192\green192\blue192;}{\*\defchp \fs22 }{\*\defpap \ql \li0\ri0\sa200\sl276\slmult1\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 }\noqfpromote {\stylesheet{
\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af0\afs24\alang1025 \ltrch\fcs0 \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \snext0 \sqformat \spriority0 \styrsid8670810 Normal;}{\*\cs10 
\additive \ssemihidden \sunhideused \spriority1 Default Paragraph Font;}{\*
\ts11\tsrowd\trftsWidthB3\trpaddl108\trpaddr108\trpaddfl3\trpaddft3\trpaddfb3\trpaddfr3\trcbpat1\trcfpat1\tblind0\tblindtype3\tscellwidthfts0\tsvertalt\tsbrdrt\tsbrdrl\tsbrdrb\tsbrdrr\tsbrdrdgl\tsbrdrdgr\tsbrdrh\tsbrdrv \ql \li0\ri0\sa200\sl276\slmult1
\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af0\afs22\alang1065 \ltrch\fcs0 \fs22\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \snext11 \ssemihidden \sunhideused \sqformat Normal Table;}{\*\cs15 \additive 
\rtlch\fcs1 \af0\afs16 \ltrch\fcs0 \fs16 \sbasedon10 \ssemihidden \styrsid16673069 annotation reference;}{\s16\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af0\afs20\alang1025 \ltrch\fcs0 
\fs20\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \sbasedon0 \snext16 \slink17 \ssemihidden \styrsid16673069 annotation text;}{\*\cs17 \additive \rtlch\fcs1 \af0\afs20\alang1025 \ltrch\fcs0 \fs20 
\sbasedon10 \slink16 \slocked \ssemihidden \styrsid15740391 Comment Text Char;}{\s18\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \ab\af0\afs20\alang1025 \ltrch\fcs0 
\b\fs20\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \sbasedon16 \snext16 \slink19 \ssemihidden \styrsid16673069 annotation subject;}{\*\cs19 \additive \rtlch\fcs1 \ab\af0\afs20\alang1025 \ltrch\fcs0 \b\fs20 
\sbasedon17 \slink18 \slocked \ssemihidden \styrsid15740391 Comment Subject Char;}{\s20\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af38\afs16\alang1025 \ltrch\fcs0 
\f38\fs16\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \sbasedon0 \snext20 \slink21 \ssemihidden \styrsid16673069 Balloon Text;}{\*\cs21 \additive \rtlch\fcs1 \af38\afs16\alang1025 \ltrch\fcs0 \f38\fs16 
\sbasedon10 \slink20 \slocked \ssemihidden \styrsid15740391 Balloon Text Char;}}{\*\listtable{\list\listtemplateid-23928742\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext
\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li360\jclisttab\tx360\lin360 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext
\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li1080\jclisttab\tx1080\lin1080 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li1800\jclisttab\tx1800\lin1800 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698689
\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li2520\jclisttab\tx2520\lin2520 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698691
\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li3240\jclisttab\tx3240\lin3240 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li3960\jclisttab\tx3960\lin3960 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698689
\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li4680\jclisttab\tx4680\lin4680 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698691
\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li5400\jclisttab\tx5400\lin5400 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li6120\jclisttab\tx6120\lin6120 }{\listname ;}\listid1128402517}{\list\listtemplateid1586429276\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1
\levelspace0\levelindent0{\leveltext\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li720\jclisttab\tx720\lin720 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0
\levelindent0{\leveltext\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li1440\jclisttab\tx1440\lin1440 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext
\leveltemplateid67698693\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li2160\jclisttab\tx2160\lin2160 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext
\leveltemplateid67698689\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li2880\jclisttab\tx2880\lin2880 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext
\leveltemplateid67698691\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li3600\jclisttab\tx3600\lin3600 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li4320\jclisttab\tx4320\lin4320 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698689
\'01\u-3913 ?;}{\levelnumbers;}\f3\fbias0\hres0\chhres0 \fi-360\li5040\jclisttab\tx5040\lin5040 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698691
\'01o;}{\levelnumbers;}\f2\fbias0\hres0\chhres0 \fi-360\li5760\jclisttab\tx5760\lin5760 }{\listlevel\levelnfc23\levelnfcn23\leveljc2\leveljcn0\levelfollow0\levelstartat1\levelspace0\levelindent0{\leveltext\leveltemplateid67698693
\'01\u-3929 ?;}{\levelnumbers;}\f10\fbias0\hres0\chhres0 \fi-360\li6480\jclisttab\tx6480\lin6480 }{\listname ;}\listid1787893201}}{\*\listoverridetable{\listoverride\listid1128402517\listoverridecount0\ls1}{\listoverride\listid1787893201
\listoverridecount0\ls2}}{\*\rsidtbl \rsid276507\rsid409024\rsid478087\rsid545272\rsid550214\rsid666643\rsid924817\rsid947815\rsid993911\rsid1134802\rsid1186943\rsid1320478\rsid1576099\rsid1596967\rsid1653055\rsid1731732\rsid1734928\rsid1782375
\rsid1917008\rsid2037710\rsid2177621\rsid2245390\rsid2297053\rsid2298299\rsid2391111\rsid2435314\rsid2435978\rsid2511252\rsid2579700\rsid3150368\rsid3411897\rsid3480889\rsid3688306\rsid3866852\rsid3963768\rsid3964714\rsid4092408\rsid4218595\rsid4222148
\rsid4275875\rsid4465195\rsid4666352\rsid4671322\rsid4856841\rsid4878914\rsid4995943\rsid5049265\rsid5182040\rsid5253536\rsid5526691\rsid5654532\rsid5666041\rsid5703837\rsid5720439\rsid5779500\rsid5922000\rsid6058996\rsid6172469\rsid6388501\rsid6425265
\rsid6433222\rsid6434471\rsid6571741\rsid6777836\rsid6884977\rsid7030470\rsid7343948\rsid7364279\rsid7562509\rsid7603830\rsid7618971\rsid7812013\rsid7879705\rsid7945770\rsid8009968\rsid8140221\rsid8151534\rsid8203564\rsid8409362\rsid8591500\rsid8603075
\rsid8670810\rsid8866725\rsid8875754\rsid8932775\rsid8978491\rsid9071482\rsid9260526\rsid9333627\rsid9659606\rsid9707541\rsid9785332\rsid9786697\rsid10031425\rsid10251537\rsid10365086\rsid10641895\rsid10687743\rsid10757896\rsid11013323\rsid11017886
\rsid11086383\rsid11103980\rsid11147431\rsid11209853\rsid11211463\rsid11281911\rsid11290438\rsid11304137\rsid11469895\rsid11495724\rsid11537473\rsid11616329\rsid11670919\rsid11673285\rsid11810295\rsid12018627\rsid12065372\rsid12066061\rsid12203925
\rsid12266535\rsid12322038\rsid12406067\rsid12410109\rsid12549482\rsid12678028\rsid12811380\rsid12864477\rsid13004894\rsid13191797\rsid13517271\rsid13598533\rsid13639741\rsid13704766\rsid13778624\rsid13914529\rsid14114560\rsid14232973\rsid14551136
\rsid14623252\rsid14628938\rsid14704266\rsid14745748\rsid14759550\rsid14834228\rsid14882516\rsid15017470\rsid15083196\rsid15140096\rsid15474288\rsid15545768\rsid15739294\rsid15740391\rsid15993592\rsid16135934\rsid16219043\rsid16271372\rsid16332217
\rsid16600097\rsid16656259\rsid16673069\rsid16717877\rsid16720916}{\mmathPr\mmathFont34\mbrkBin0\mbrkBinSub0\msmallFrac0\mdispDef1\mlMargin0\mrMargin0\mdefJc1\mwrapIndent1440\mintLim0\mnaryLim1}{\info{\author admin}{\operator Ali}
{\creatim\yr2012\mo9\dy4\hr15\min36}{\revtim\yr2012\mo9\dy4\hr15\min36}{\printim\yr2006\mo8\dy26\hr15\min28}{\version2}{\edmins1}{\nofpages2}{\nofwords316}{\nofchars2649}{\nofcharsws2960}{\vern32771}}{\*\xmlnstbl {\xmlns1 http://schemas.microsoft.com/offi
ce/word/2003/wordml}}\paperw12240\paperh15840\margl1800\margr1800\margt1440\margb1440\gutter0\ltrsect\rtlgutter 
\widowctrl\ftnbj\aenddoc\trackmoves1\trackformatting1\donotembedsysfont0\relyonvml0\donotembedlingdata0\grfdocevents0\validatexml0\showplaceholdtext0\ignoremixedcontent0\saveinvalidxml0\showxmlerrors0\noxlattoyen
\expshrtn\noultrlspc\dntblnsbdb\nospaceforul\formshade\horzdoc\dgmargin\dghspace180\dgvspace180\dghorigin1800\dgvorigin1440\dghshow1\dgvshow1
\jexpand\viewkind1\viewscale110\pgbrdrhead\pgbrdrfoot\splytwnine\ftnlytwnine\htmautsp\nolnhtadjtbl\useltbaln\alntblind\lytcalctblwd\lyttblrtgr\lnbrkrule\nobrkwrptbl\snaptogridincell\allowfieldendsel\wrppunct
\asianbrkrule\rsidroot924817\newtblstyruls\nogrowautofit\usenormstyforlist\noindnmbrts\felnbrelev\nocxsptable\indrlsweleven\noafcnsttbl\afelev\utinl\hwelev\spltpgpar\notcvasp\notbrkcnstfrctbl\notvatxbx\krnprsnet\cachedcolbal \nouicompat \fet0
{\*\wgrffmtfilter 013f}\nofeaturethrottle1\ilfomacatclnup0\ltrpar \sectd \ltrsect\rtlgutter\linex0\endnhere\sectlinegrid360\sectdefaultcl\sectrsid15740391\sftnbj {\*\pnseclvl1\pnucrm\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl2
\pnucltr\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl3\pndec\pnqc\pnstart1\pnindent720\pnhang {\pntxta .}}{\*\pnseclvl4\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxta )}}{\*\pnseclvl5\pndec\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}
{\pntxta )}}{\*\pnseclvl6\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl7\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}{\*\pnseclvl8\pnlcltr\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}
{\*\pnseclvl9\pnlcrm\pnqc\pnstart1\pnindent720\pnhang {\pntxtb (}{\pntxta )}}\pard\plain \ltrpar\qc \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid1596967 \rtlch\fcs1 \af0\afs24\alang1025 \ltrch\fcs0 
\fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 {\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 \i\f39\fs18\lang1065\insrsid1596967\charrsid1596967 \'c8\'d3\'e3\'e5}{\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 
\i\f39\fs18\lang1065\insrsid1596967\charrsid1596967  }{\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 \i\f39\fs18\lang1065\insrsid1596967\charrsid1596967 \'ca\'da\'c7\'e1\'ed}{\rtlch\fcs1 \ai\af39\afs18\alang1065 \ltrch\fcs0 
\i\f40\fs18\insrsid1596967\charrsid1596967 
\par }\pard \ltrpar\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid4275875 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid12322038\charrsid1596967 \'dd\'d1\'e3 \'d4\'e3\'c7\'cf\'e5 16 \'ca\'c7\'ed
\'ed\'cf \'90\'d2\'c7\'d1\'d4 \'e3\'cc\'d1\'ed}{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid4275875\charrsid1596967 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid1596967 {\ltrch\fcs1 \ab\ai\afs18 
\rtlch\fcs0 \b\i\f39\fs18\lang1065\insrsid1596967\charrsid1596967 \'dd\'d1\'e3 \'ca\'c7\'ed\'ed\'cf \'90\'d2\'c7\'d1\'d4\'c7\'ca \'d8\'d1\'cd \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed}{\ltrch\fcs1 \ab\ai\afs18 \rtlch\fcs0 
\b\i\shad\f39\fs18\lang1025\insrsid1596967\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'c7\'e1\'dd)}{\rtlch\fcs1 
\ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid4275875\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid15474288 {\ltrch\fcs1 
\ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid11537473 \'e3\'da\'c7\'e6\'e4\'ca \'e3\'cd\'ca\'d1\'e3 \'81\'8e\'e6\'e5\'d4\'ed  <? echo"$daneshkade_name";?>}{\rtlch\fcs1 \ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid3411897\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid9071482 {
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid6172469\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid15545768 {
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid9071482\charrsid1596967 \'c7\'cd\'ca\'d1\'e3\'c7\'f0 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid6172469\charrsid1596967 \'cf\'d1 \'ce\'d5\'e6\'d5 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid8203564\charrsid1596967 \'d8\'d1\'cd}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid15545768  \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed \'d4\'e3\'c7\'d1\'e5}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid4666352\charrsid1596967  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid15545768  <? echo $cod_tarh; ?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4666352\charrsid1596967  \'ca\'cd\'ca \'da\'e4\'e6\'c7\'e4 :}{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid15545768  <? echo $tarh_name;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4666352\charrsid15545768 
\par }\pard \rtlpar\qj \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid545272 {\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid13004894\charrsid1596967 \'c8}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid2298299\charrsid1596967 \'e5 \'c7\'d3\'ca\'cd\'d6\'c7\'d1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid13004894\charrsid1596967  \'e3\'ed\'d1\'d3\'c7\'e4\'cf}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid7603830\charrsid1596967  \'90\'d2\'c7\'d1\'d4}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid2298299\charrsid1596967  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid7603830\charrsid1596967 \'e3\'cc\'d1\'ed \'cf\'d1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid2298299\charrsid1596967 \'c7\'ed\'e4 
\'e3\'d1\'cd\'e1\'e5 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid7603830\charrsid1596967 \'e3\'e4\'c7\'d3\'c8 \'e6 \'c7\'d2 \'e4\'d9\'d1 \'c7\'cc\'d1\'c7\'ed\'ed}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid5182040  }{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid13004894\charrsid1596967 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'df\'c7\'d1\'d4\'e4\'c7\'d3\'ed }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid5182040\charrsid1596967 \'e3\'ed }{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid13004894\charrsid1596967 \'c8\'c7\'d4\'cf\'a1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid10251537 \'e1\'d0\'c7}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid13004894\charrsid1596967  \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'cf\'d1 \'d5\'e6\'d1\'ca \'d5\'e1\'c7\'cd\'cf\'ed\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'ed\'e4 \'90\'d2\'c7\'d1\'d4 \'d1\'c7 \'c7\'da\'e1\'c7\'e3 \'e6 \'e4\'d3\'c8
\'ca \'c8\'e5 \'81\'ed\'90\'ed\'d1\'ed \'c7\'e3\'e6\'d1 \'c7\'cf\'c7\'d1\'ed \'e6 \'e3\'c7\'e1\'ed  \'cf\'d3\'ca\'e6\'d1 \'e1\'c7\'d2\'e3 \'d5\'c7\'cf\'d1 \'dd\'d1\'e3\'c7\'ed\'ed\'cf.
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid9071482 {
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid14882516\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid15545768 {\ltrch\fcs1 
\ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid14882516\charrsid1596967              }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid3866852\charrsid1596967 \'df\'c7\'d1\'d4\'e4\'c7\'d3 }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 
\b\f39\fs18\lang1025\insrsid1731732\charrsid1596967 \'e3\'d1\'c8\'e6\'d8\'e5}{\rtlch\fcs1 \ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid6777836\charrsid1596967  }{\rtlch\fcs1 \ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid15545768  <? echo $sub_subadmin?>}{\rtlch\fcs1 
\ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid6777836\charrsid1596967  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid6777836\charrsid1596967                   }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid947815 \'98\'c7
\'d1\'d4\'e4\'c7\'d3 \'e3\'d3\'c6\'e6\'e1 \'e3\'d1\'c8\'e6\'d8\'e5}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid6777836\charrsid1596967                      }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid8151534 
                                                                             }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid6777836\charrsid1596967                               }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 
\b\f39\fs18\lang1025\insrsid6777836\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx703\tx5914\tx6309\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid9071482 {
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid6777836\charrsid1596967 \tab }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid14882516\charrsid1596967 \tab \tab }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid3866852\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid9071482 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid4666352\charrsid1596967  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid993911\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'c8)}{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid2579700\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7562509 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid15545768 \'d3\'d1\'81\'d1\'d3\'ca \'e3\'cd\'ca\'d1\'e3 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid15545768 <? echo $daneshkade_name;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid5182040   }{\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid5526691\charrsid1596967 
\par }\pard \rtlpar\qj \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid5654532 {\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid14551136\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid6388501\charrsid1596967 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf \'dd\'e6\'de }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid1653055\charrsid1596967 \'90\'d2\'c7\'d1\'d4 \'c7\'d1\'c7\'c6\'e5 \'d4\'cf\'e5 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'e3\'ed\'c8\'c7\'d4\'cf. \'e1\'d0\'c7 \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'e4\'d3\'c8\'ca \'c8\'e5 
\'d5\'cf\'e6\'d1 \'cf\'d3\'ca\'e6\'d1 \'e1\'c7\'d2\'e3 \'c8\'d1\'c7\'ed \'c7\'cf\'c7\'e3\'e5 \'da\'e3\'e1\'ed\'c7\'ca \'c7\'cf\'c7\'d1\'ed \'c7\'de\'cf\'c7\'e3 \'e1\'c7\'d2\'e3 \'e3\'c8\'d0\'e6\'e1 \'dd\'d1\'e3\'c7\'c6\'ed\'cf.
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid947815 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid14745748\charrsid1596967 
                                                                                                                                                                                                                                                 }{\ltrch\fcs1 
\ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid16673069                                                                                                                                                                   }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid8151534      }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid16673069    }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid8151534                         }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid947815 \'e3\'da\'c7\'e6\'e4 \'81\'8e\'e6\'e5\'d4\'ed  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid8151534     }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid12410109 <? echo $daneshkade_name;?>}{
\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid6388501\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid6433222 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid14745748\charrsid1596967                                                                                                 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid14745748\charrsid1596967   
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2579700 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'c8\'e4\'cf \'cc)}{\rtlch\fcs1 \ab\af39\afs18 
\ltrch\fcs0 \b\fs18\insrsid2579700\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2245390 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'d1\'81}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid2435314\charrsid1596967 \'d1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'ca 
\'e3\'cd\'ca\'d1\'e3 \'cd\'d3\'c7\'c8\'cf\'c7\'d1\'ed }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid2245390 2}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid12410109 35}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid5526691\charrsid1596967 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid6571741 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid2579700\charrsid1596967 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12406067\charrsid1596967 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid6571741 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid11013323\charrsid1596967 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf\'e5\'c7\'ed}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid15083196\charrsid1596967  "}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11013323\charrsid1596967 \'c7\'e1\'dd \'e6 \'c8}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid15083196\charrsid1596967 " }{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11013323\charrsid1596967  \'e3\'d1\'c7\'ca\'c8 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'d3\'ca.}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid15993592\charrsid1596967  }{\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid6571741\charrsid1596967 \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7\'ce\'ca \'c7\'de\'d3\'c7\'d8 \'e3\'d1\'c8\'e6\'d8\'e5 \'c7\'de\'cf\'c7\'e3 \'e4\'e3\'c7\'ed\'ed\'cf.}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid6571741 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid8151534 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1065\insrsid8151534\charrsid1596967 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid5703837 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid6425265\charrsid1596967                                                                                  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid7030470      }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid5703837 \'d3\'d1\'81\'d1\'d3\'ca}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid12410109  <? echo $daneshkade_name; ?>}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid5182040  }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid6571741\charrsid1596967 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp20 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp20 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid8670810 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid6425265\charrsid1596967                                                                                     }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7812013\charrsid1596967 
\par }\pard \ltrpar\qc \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid550214 {\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid7030470 
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431 \page }{\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 \i\f39\fs18\lang1065\insrsid11147431\charrsid11670919 \'c8\'d3\'e3\'e5}{\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 
\i\f39\fs18\lang1065\insrsid11147431\charrsid11670919  }{\ltrch\fcs1 \ai\af40\afs18 \rtlch\fcs0 \i\f39\fs18\lang1065\insrsid11147431\charrsid11670919 \'ca\'da\'c7\'e1\'ed}{\rtlch\fcs1 \ai\af39\afs18\alang1065 \ltrch\fcs0 
\i\fs18\insrsid11147431\charrsid11670919 
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\cf1\lang1025\insrsid11147431\charrsid11670919 \'dd\'d1\'e3 \'d4\'e3\'c7\'d1\'e5 17/2 \'cf\'d3\'ca\'e6\'d1\'81\'d1\'cf\'c7\'ce\'ca \'c7\'de\'d3\'c7\'d8}{\rtlch\fcs1 \af39\afs18\alang1065 \ltrch\fcs0 
\fs18\cf1\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qc \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid3150368 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\shad\f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'dd\'d1\'e3 \'81\'d1\'cf\'c7\'ce\'ca \'c7
\'de\'d3\'c7\'d8 \'de\'d1\'c7\'d1\'cf\'c7\'cf }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\shad\f39\fs18\lang1065\insrsid11147431\charrsid11670919 \'d8\'d1\'cd}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\shad\f39\fs18\lang1025\insrsid3150368  \'e5\'c7\'ed \'81\'8e}{
\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\shad\f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'e6\'e5\'d4\'ed}{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'e4\'cf \'c7\'e1\'dd)}{\rtlch\fcs1 
\ab\af39\afs18\alang1065 \ltrch\fcs0 \b\fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2245390 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7364279 \'e3\'da\'c7\'e6\'e4\'ca}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid15474288  \'e3\'cd\'ca\'d1\'e3}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7364279  \'81\'8e\'e6\'e5
\'d4\'ed}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid15474288  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid2245390 <? echo $daneshkade_name; ?>}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2245390 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'ca\'e4 \'de\'d1\'c7\'d1\'cf\'c7\'cf \'e3\'e4\'da\'de\'cf\'e5 \'c8\'c7 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 <?echo $name_family;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid8670810 (\'d4\'e3\'c7\'d1\'e5 \'cd\'d3\'c7\'c8 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid2245390 <?echo $shomare_hesab;?>}{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid8670810 )}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919  \'c8\'e5 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 \'d4\'e3\'c7\'d1\'e5}{
\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid8670810  \'de\'d1\'c7\'d1\'cf\'c7\'cf}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid8670810     }{\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'cf\'d1 \'ce\'d5\'e6\'d5 \'d8\'d1\'cd \'ca\'cd\'de\'ed\'de\'c7\'ca\'ed }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid12410109 \'c8\'e5 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4995943 \'d4\'e3\'c7\'d1\'e5 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 <? echo $cod_tarh; ?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid4995943  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'ca\'cd\'ca \'da\'e4\'e6\'c7\'e4 :}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109  <? echo $tarh_name; ?>
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid12410109 {\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'cf\'d1 \'d5\'e6\'d1\'ca \'d5\'e1\'c7\'cd\'cf\'ed\'cf \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7\'ce\'ca }{\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f0\fs24\lang1025\insrsid9659606  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4995943 \'e3\'c8\'e1\'db }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919    }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid12410109 <?echo $mablagh_marhale_n;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919   \'d1\'ed\'c7\'e1 \'c7\'d2 \'c8\'e6\'cf\'cc\'e5 \'e3\'d5\'e6\'c8 \'d8\'d1\'cd \'c8\'e5 \'d4\'d1\'cd \'d2\'ed\'d1\'c7\'de\'cf\'c7
\'e3 \'e3\'de\'ca\'d6\'ed \'c8\'da\'e3\'e1 \'c2\'ed\'cf.
\par 1. \'e3\'c7\'e1\'ed\'c7\'ca \'c7\'ed\'e4 \'e3\'d1\'cd\'e1\'e5 \'a1 \'c8\'e5 \'e3\'ed\'d2\'c7\'e4  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4995943 5% \'da\'cf\'cf \'dd\'e6\'de}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid12410109 \'a1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919   }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid12410109 <?echo $maliat_marhale_n;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919   \'d1\'ed\'c7\'e1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 2.\'ce\'c7\'e1\'d5 \'81\'d1\'cf\'c7\'ce\'ca\'ed \'c8\'e5 \'e3\'cc\'d1\'ed\'a1 <?echo $mablagh_khales_mojri_n;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'d1\'ed\'c7\'e1 (}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid11147431\charrsid11670919 \'90\'d2\'c7\'d1\'d4}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109  \'e3\'d1
\'cd\'e1\'e5}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 <?echo $marhale_jadval_zamani;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid10687743  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid11147431\charrsid11670919 )
\par 3. \'ce\'c7\'e1\'d5 \'81\'d1\'cf\'c7\'ce\'ca\'ed \'c8\'da\'e4\'e6\'c7\'e4 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 \'cd\'de }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'e4\'c7\'d9\'d1 / 
\'df\'c7\'d1\'d4\'e4\'c7\'d3 \'d8\'d1\'cd \'a1 \'c8\'e5 \'e3\'ed\'d2\'c7\'e4 }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid12410109 <?echo $hagh_ol_zahme_karshenasi_n;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid11147431\charrsid11670919  \'d1\'ed\'c7\'e1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7364279   }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\sl360\slmult1\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch\fcs1 
\afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid8670810 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid11147431\charrsid11670919              \'df\'c7\'d1\'d4\'e4\'c7\'d3 \'e3\'d1\'c8\'e6\'d8\'e5 }{\rtlch\fcs1 \ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid11147431\charrsid11670919  }{\rtlch\fcs1 \ab\af39\afs18 
\ltrch\fcs0 \b\fs18\insrsid12410109 <? echo $sub_subadmin?>}{\rtlch\fcs1 \ab\af39\afs18 \ltrch\fcs0 \b\fs18\insrsid11147431\charrsid11670919  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431\charrsid11670919  }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 
\b\f39\fs18\lang1065\insrsid8670810             \'98\'c7\'d1\'d4\'e4\'c7\'d3 \'e3\'d3\'c6\'e6\'e1 \'e3\'d1\'c8\'e6\'d8\'e5}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid12410109 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid12410109 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid12410109                       }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431\charrsid11670919                                                               }{\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431                                               }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid13778624        }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431 
          }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1065\insrsid11147431\charrsid11670919      
\par }\pard \ltrpar\ql \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7030470 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid7030470 
\par }\pard \rtlpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10 \brdrr\brdrs\brdrw10\brsp80 \tx7920\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7030470 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7030470\charrsid11670919 \'c8\'e4\'cf \'c8)
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7030470 {\ltrch\fcs1 \ab\afs18 
\rtlch\fcs0 \b\f39\fs18\lang1065\insrsid7030470 
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid7030470 \'d3\'d1\'81\'d1\'d3\'ca \'e3\'cd\'ca\'d1\'e3 <? echo $daneshkade_name;?>
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf \'dd\'e6\'de \'ce\'e6\'c7\'e5\'d4\'e3\'e4\'cf \'c7\'d3\'ca \'e4\'d3\'c8\'ca \'c8\'e5 \'81\'d1\'cf\'c7\'ce\'ca }{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid8670810 \'98\'e1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid10687743  }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4222148 <?echo $mablagh_marhale_n;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1025\insrsid11147431\charrsid11670919  \'d1\'ed\'c7\'e1 
\par (}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid4222148 1250 \'d1\u1740\'ed\'c7\'e1}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 ) \'c8\'e5 \'d4\'d1\'cd \'dd\'e6\'de \'c7\'de\'cf\'c7\'e3 \'de\'c7\'e4\'e6
\'e4\'ed \'e3\'da\'e3\'e6\'e1 \'90\'d1\'cf\'cf.}{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431 
\par }\pard \ltrpar\qc \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7030470 {\rtlch\fcs1 \af39\afs18 
\ltrch\fcs0 \fs18\insrsid7030470\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid7030470 {\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid7030470                                      }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7030470 \'e3\'da\'c7\'e6\'e4 \'81\'8e\'e6\'e5\'d4\'ed      <? echo $daneshkade_name;?>}{\ltrch\fcs1 \afs18 \rtlch\fcs0 
\f39\fs18\lang1065\insrsid11147431 
\par }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1065\insrsid7030470                                   }{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid7030470                   }{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid16720916 
\par                            }{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid16720916\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'c8\'e4\'cf \'cc)}{\rtlch\fcs1 \ab\af39\afs18 
\ltrch\fcs0 \b\fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid2297053 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'d1\'81\'d1\'d3\'ca \'e3\'cd\'ca\'d1\'e3 \'cd\'d3\'c7\'c8\'cf\'c7\'d1\'ed }{\ltrch\fcs1 \afs18 \rtlch\fcs0 \f39\fs18\lang1025\insrsid7030470 <? echo $daneshkade_name;?>}{\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 
\fs18\insrsid11147431\charrsid11670919 
\par }\pard \ltrpar\qr \li0\ri0\widctlpar\brdrt\brdrs\brdrw10\brsp20 \brdrl\brdrs\brdrw10\brsp80 \brdrb\brdrs\brdrw10\brsp20 \brdrr\brdrs\brdrw10\brsp80 \wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0\pararsid11147431 {\ltrch\fcs1 \afs18 
\rtlch\fcs0 \f39\fs18\lang1025\insrsid11147431\charrsid11670919 \'d3\'e1\'c7\'e3 \'da\'e1\'ed\'df\'e3:
\par \'c8\'c7 \'ca\'e6\'cc\'e5 \'c8\'e5 \'e3\'d8\'c7\'e1\'c8 \'e3\'e4\'cf\'d1\'cc \'cf\'d1 \'c8\'e4\'cf\'e5\'c7\'ed "\'c7\'e1\'dd \'e6 \'c8"  \'e3\'d1\'c7\'ca\'c8 \'e3\'e6\'d1\'cf \'ca\'c7\'ed\'ed\'cf \'c7\'d3\'ca}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 
\b\f39\fs18\lang1025\insrsid11147431\charrsid11670919 .                 }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid11147431 
\par }{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7030470                                                \'d3\'d1\'81\'d1\'d3\'ca <? echo $daneshkade_name;?>}{\ltrch\fcs1 \ab\afs18 \rtlch\fcs0 \b\f39\fs18\lang1025\insrsid7030470\charrsid11670919 
\par }\pard \rtlpar\qr \li0\ri720\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin720\itap0\pararsid4222148 {\rtlch\fcs1 \af39\afs18 \ltrch\fcs0 \fs18\insrsid16656259 
\par }{\*\themedata 504b030414000600080000002100828abc13fa0000001c020000130000005b436f6e74656e745f54797065735d2e786d6cac91cb6ac3301045f785fe83d0b6d8
72ba28a5d8cea249777d2cd20f18e4b12d6a8f843409c9df77ecb850ba082d74231062ce997b55ae8fe3a00e1893f354e9555e6885647de3a8abf4fbee29bbd7
2a3150038327acf409935ed7d757e5ee14302999a654e99e393c18936c8f23a4dc072479697d1c81e51a3b13c07e4087e6b628ee8cf5c4489cf1c4d075f92a0b
44d7a07a83c82f308ac7b0a0f0fbf90c2480980b58abc733615aa2d210c2e02cb04430076a7ee833dfb6ce62e3ed7e14693e8317d8cd0433bf5c60f53fea2fe7
065bd80facb647e9e25c7fc421fd2ddb526b2e9373fed4bb902e182e97b7b461e6bfad3f010000ffff0300504b030414000600080000002100a5d6a7e7c00000
00360100000b0000005f72656c732f2e72656c73848fcf6ac3300c87ef85bd83d17d51d2c31825762fa590432fa37d00e1287f68221bdb1bebdb4fc7060abb08
84a4eff7a93dfeae8bf9e194e720169aaa06c3e2433fcb68e1763dbf7f82c985a4a725085b787086a37bdbb55fbc50d1a33ccd311ba548b63095120f88d94fbc
52ae4264d1c910d24a45db3462247fa791715fd71f989e19e0364cd3f51652d73760ae8fa8c9ffb3c330cc9e4fc17faf2ce545046e37944c69e462a1a82fe353
bd90a865aad41ed0b5b8f9d6fd010000ffff0300504b0304140006000800000021006b799616830000008a0000001c0000007468656d652f7468656d652f7468
656d654d616e616765722e786d6c0ccc4d0ac3201040e17da17790d93763bb284562b2cbaebbf600439c1a41c7a0d29fdbd7e5e38337cedf14d59b4b0d592c9c
070d8a65cd2e88b7f07c2ca71ba8da481cc52c6ce1c715e6e97818c9b48d13df49c873517d23d59085adb5dd20d6b52bd521ef2cdd5eb9246a3d8b4757e8d3f7
29e245eb2b260a0238fd010000ffff0300504b03041400060008000000210096b5ade296060000501b0000160000007468656d652f7468656d652f7468656d65
312e786d6cec594f6fdb3614bf0fd87720746f6327761a07758ad8b19b2d4d1bc46e871e698996d850a240d2497d1bdae38001c3ba618715d86d87615b8116d8
a5fb34d93a6c1dd0afb0475292c5585e9236d88aad3e2412f9e3fbff1e1fa9abd7eec70c1d1221294fda5efd72cd4324f1794093b0eddd1ef62fad79482a9c04
98f184b4bd2991deb58df7dfbb8ad755446282607d22d771db8b944ad79796a40fc3585ee62949606ecc458c15bc8a702910f808e8c66c69b9565b5d8a314d3c
94e018c8de1a8fa94fd05093f43672e23d06af89927ac06762a049136785c10607758d9053d965021d62d6f6804fc08f86e4bef210c352c144dbab999fb7b471
7509af678b985ab0b6b4ae6f7ed9ba6c4170b06c788a705430adf71bad2b5b057d03606a1ed7ebf5babd7a41cf00b0ef83a6569632cd467faddec9699640f671
9e76b7d6ac355c7c89feca9cccad4ea7d36c65b258a206641f1b73f8b5da6a6373d9c11b90c537e7f08dce66b7bbeae00dc8e257e7f0fd2badd5868b37a088d1
e4600ead1ddaef67d40bc898b3ed4af81ac0d76a197c86826828a24bb318f3442d8ab518dfe3a20f000d6458d104a9694ac6d88728eee2782428d60cf03ac1a5
193be4cbb921cd0b495fd054b5bd0f530c1931a3f7eaf9f7af9e3f45c70f9e1d3ff8e9f8e1c3e3073f5a42ceaa6d9c84e5552fbffdeccfc71fa33f9e7ef3f2d1
17d57859c6fffac327bffcfc793510d26726ce8b2f9ffcf6ecc98baf3efdfdbb4715f04d814765f890c644a29be408edf3181433567125272371be15c308d3f2
8acd249438c19a4b05fd9e8a1cf4cd296699771c393ac4b5e01d01e5a30a787d72cf1178108989a2159c77a2d801ee72ce3a5c545a6147f32a99793849c26ae6
6252c6ed637c58c5bb8b13c7bfbd490a75330f4b47f16e441c31f7184e140e494214d273fc80900aedee52ead87597fa824b3e56e82e451d4c2b4d32a423279a
668bb6690c7e9956e90cfe766cb37b077538abd27a8b1cba48c80acc2a841f12e698f13a9e281c57911ce298950d7e03aba84ac8c154f8655c4f2af074481847
bd804859b5e696007d4b4edfc150b12addbecba6b18b148a1e54d1bc81392f23b7f84137c2715a851dd0242a633f900710a218ed715505dfe56e86e877f0034e
16bafb0e258ebb4faf06b769e888340b103d3311da9750aa9d0a1cd3e4efca31a3508f6d0c5c5c398602f8e2ebc71591f5b616e24dd893aa3261fb44f95d843b
5974bb5c04f4edafb95b7892ec1108f3f98de75dc97d5772bdff7cc95d94cf672db4b3da0a6557f70db629362d72bcb0431e53c6066acac80d699a6409fb44d0
8741bdce9c0e4971624a2378cceaba830b05366b90e0ea23aaa241845368b0eb9e2612ca8c742851ca251ceccc70256d8d87265dd96361531f186c3d9058edf2
c00eafe8e1fc5c509031bb4d680e9f39a3154de0accc56ae644441edd76156d7429d995bdd88664a9dc3ad50197c38af1a0c16d684060441db02565e85f3b966
0d0713cc48a0ed6ef7dedc2dc60b17e92219e180643ed27acffba86e9c94c78ab90980d8a9f0913ee49d62b512b79626fb06dccee2a432bbc60276b9f7dec44b
7904cfbca4f3f6443ab2a49c9c2c41476dafd55c6e7ac8c769db1bc399161ee314bc2e75cf8759081743be1236ec4f4d6693e5336fb672c5dc24a8c33585b5fb
9cc24e1d4885545b58463634cc5416022cd19cacfccb4d30eb45296023fd35a458598360f8d7a4003bbaae25e331f155d9d9a5116d3bfb9a95523e51440ca2e0
088dd844ec6370bf0e55d027a012ae264c45d02f708fa6ad6da6dce29c255df9f6cae0ec38666984b372ab5334cf640b37795cc860de4ae2816e95b21be5ceaf
8a49f90b52a51cc6ff3355f47e0237052b81f6800fd7b802239daf6d8f0b1571a8426944fdbe80c6c1d40e8816b88b8569082ab84c36ff0539d4ff6dce591a26
ade1c0a7f669880485fd484582903d284b26fa4e2156cff62e4b9265844c4495c495a9157b440e091bea1ab8aaf7760f4510eaa69a6465c0e04ec69ffb9e65d0
28d44d4e39df9c1a52ecbd3607fee9cec7263328e5d661d3d0e4f62f44acd855ed7ab33cdf7bcb8ae889599bd5c8b3029895b6825696f6af29c239b75a5bb1e6
345e6ee6c28117e73586c1a2214ae1be07e93fb0ff51e133fb65426fa843be0fb515c187064d0cc206a2fa926d3c902e907670048d931db4c1a44959d366ad93
b65abe595f70a75bf03d616c2dd959fc7d4e6317cd99cbcec9c58b34766661c7d6766ca1a9c1b327531486c6f941c638c67cd22a7f75e2a37be0e82db8df9f30
254d30c1372581a1f51c983c80e4b71ccdd28dbf000000ffff0300504b0304140006000800000021000dd1909fb60000001b010000270000007468656d652f74
68656d652f5f72656c732f7468656d654d616e616765722e786d6c2e72656c73848f4d0ac2301484f78277086f6fd3ba109126dd88d0add40384e4350d363f24
51eced0dae2c082e8761be9969bb979dc9136332de3168aa1a083ae995719ac16db8ec8e4052164e89d93b64b060828e6f37ed1567914b284d262452282e3198
720e274a939cd08a54f980ae38a38f56e422a3a641c8bbd048f7757da0f19b017cc524bd62107bd5001996509affb3fd381a89672f1f165dfe514173d9850528
a2c6cce0239baa4c04ca5bbabac4df000000ffff0300504b01022d0014000600080000002100828abc13fa0000001c0200001300000000000000000000000000
000000005b436f6e74656e745f54797065735d2e786d6c504b01022d0014000600080000002100a5d6a7e7c0000000360100000b000000000000000000000000
002b0100005f72656c732f2e72656c73504b01022d00140006000800000021006b799616830000008a0000001c00000000000000000000000000140200007468
656d652f7468656d652f7468656d654d616e616765722e786d6c504b01022d001400060008000000210096b5ade296060000501b000016000000000000000000
00000000d10200007468656d652f7468656d652f7468656d65312e786d6c504b01022d00140006000800000021000dd1909fb60000001b010000270000000000
00000000000000009b0900007468656d652f7468656d652f5f72656c732f7468656d654d616e616765722e786d6c2e72656c73504b050600000000050005005d010000960a00000000}
{\*\colorschememapping 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822207374616e64616c6f6e653d22796573223f3e0d0a3c613a636c724d
617020786d6c6e733a613d22687474703a2f2f736368656d61732e6f70656e786d6c666f726d6174732e6f72672f64726177696e676d6c2f323030362f6d6169
6e22206267313d226c743122207478313d22646b3122206267323d226c743222207478323d22646b322220616363656e74313d22616363656e74312220616363
656e74323d22616363656e74322220616363656e74333d22616363656e74332220616363656e74343d22616363656e74342220616363656e74353d22616363656e74352220616363656e74363d22616363656e74362220686c696e6b3d22686c696e6b2220666f6c486c696e6b3d22666f6c486c696e6b222f3e}
{\*\latentstyles\lsdstimax267\lsdlockeddef0\lsdsemihiddendef1\lsdunhideuseddef1\lsdqformatdef0\lsdprioritydef99{\lsdlockedexcept \lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority0 \lsdlocked0 Normal;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority9 \lsdlocked0 heading 1;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 2;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 3;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 4;
\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 5;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 6;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 7;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 8;\lsdqformat1 \lsdpriority9 \lsdlocked0 heading 9;
\lsdpriority39 \lsdlocked0 toc 1;\lsdpriority39 \lsdlocked0 toc 2;\lsdpriority39 \lsdlocked0 toc 3;\lsdpriority39 \lsdlocked0 toc 4;\lsdpriority39 \lsdlocked0 toc 5;\lsdpriority39 \lsdlocked0 toc 6;\lsdpriority39 \lsdlocked0 toc 7;
\lsdpriority39 \lsdlocked0 toc 8;\lsdpriority39 \lsdlocked0 toc 9;\lsdqformat1 \lsdpriority35 \lsdlocked0 caption;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority10 \lsdlocked0 Title;\lsdpriority1 \lsdlocked0 Default Paragraph Font;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority11 \lsdlocked0 Subtitle;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority22 \lsdlocked0 Strong;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority20 \lsdlocked0 Emphasis;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority59 \lsdlocked0 Table Grid;\lsdunhideused0 \lsdlocked0 Placeholder Text;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority1 \lsdlocked0 No Spacing;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading;\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List;\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List;\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List;\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid;\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 1;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 1;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 1;\lsdunhideused0 \lsdlocked0 Revision;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority34 \lsdlocked0 List Paragraph;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority29 \lsdlocked0 Quote;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority30 \lsdlocked0 Intense Quote;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 1;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 1;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 1;\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 2;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 2;\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 3;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 3;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 3;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 3;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 3;\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 3;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 4;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 4;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 4;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 4;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 4;\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 5;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 5;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 5;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 5;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 5;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 5;\lsdsemihidden0 \lsdunhideused0 \lsdpriority60 \lsdlocked0 Light Shading Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority61 \lsdlocked0 Light List Accent 6;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority62 \lsdlocked0 Light Grid Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority63 \lsdlocked0 Medium Shading 1 Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority64 \lsdlocked0 Medium Shading 2 Accent 6;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority65 \lsdlocked0 Medium List 1 Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority66 \lsdlocked0 Medium List 2 Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority67 \lsdlocked0 Medium Grid 1 Accent 6;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority68 \lsdlocked0 Medium Grid 2 Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority69 \lsdlocked0 Medium Grid 3 Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority70 \lsdlocked0 Dark List Accent 6;
\lsdsemihidden0 \lsdunhideused0 \lsdpriority71 \lsdlocked0 Colorful Shading Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority72 \lsdlocked0 Colorful List Accent 6;\lsdsemihidden0 \lsdunhideused0 \lsdpriority73 \lsdlocked0 Colorful Grid Accent 6;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority19 \lsdlocked0 Subtle Emphasis;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority21 \lsdlocked0 Intense Emphasis;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority31 \lsdlocked0 Subtle Reference;\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority32 \lsdlocked0 Intense Reference;
\lsdsemihidden0 \lsdunhideused0 \lsdqformat1 \lsdpriority33 \lsdlocked0 Book Title;\lsdpriority37 \lsdlocked0 Bibliography;\lsdqformat1 \lsdpriority39 \lsdlocked0 TOC Heading;}}{\*\datastore 010500000200000018000000
4d73786d6c322e534158584d4c5265616465722e352e30000000000000000000000e0000
d0cf11e0a1b11ae1000000000000000000000000000000003e000300feff0900060000000000000000000000010000000100000000000000001000000200000001000000feffffff0000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffdffffff04000000feffffff05000000fefffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff52006f006f007400200045006e00740072007900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000500ffffffffffffffff01000000ec69d9888b8b3d4c859eaf6cd158be0f00000000000000000000000060ff
7e4e8d8acd010300000080020000000000004d0073006f004400610074006100530074006f0072006500000000000000000000000000000000000000000000000000000000000000000000000000000000001a000101ffffffffffffffff02000000000000000000000000000000000000000000000060ff7e4e8d8acd01
60ff7e4e8d8acd0100000000000000000000000052005100cc004300c3005900d400df00540055005700d700c30042004f00df0055004b0046004900c60051003d003d000000000000000000000000000000000032000101ffffffffffffffff03000000000000000000000000000000000000000000000060ff7e4e8d8a
cd0160ff7e4e8d8acd010000000000000000000000004900740065006d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000201ffffffff04000000ffffffff000000000000000000000000000000000000000000000000
00000000000000000000000000000000da00000000000000010000000200000003000000feffffff0500000006000000070000000800000009000000feffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3c623a536f75726365732053656c65637465645374796c653d225c4150412e58534c22205374796c654e616d653d224150412220786d6c6e733a623d22687474703a2f2f736368656d61732e6f70656e786d6c666f726d6174732e6f7267
2f6f6666696365446f63756d656e742f323030362f6269626c696f6772617068792220786d6c6e733d22687474703a2f2f736368656d61732e6f70656e786d6c666f726d6174732e6f72672f6f6666696365446f63756d656e742f323030362f6269626c696f677261706879223e3c2f623a536f75726365733e0d0a0000
0000000000000000000000000000000000000000000000000000000000000000000000003c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822207374616e64616c6f6e653d226e6f223f3e0d0a3c64733a6461746173746f72654974656d2064733a6974656d49443d227b38443032
304234352d334638442d343534442d423738432d3133424635304131343839397d2220786d6c6e733a64733d22687474703a2f2f736368656d61732e6f70656e786d6c666f726d6174732e6f72672f6f6666696365446f63756d656e742f323030362f637573746f6d586d6c223e3c64733a736368656d61526566733e3c
64733a736368656d615265662064733a7572693d22687474703a2f2f736368656d61732e6f70656e500072006f007000650072007400690065007300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000200ffffffffffffffffffffffff000000000000
0000000000000000000000000000000000000000000000000000000000000400000055010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff00000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff0000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000786d6c666f726d6174732e6f72672f6f6666696365446f63756d656e742f323030362f6269626c696f677261706879222f3e3c2f64733a736368656d61526566733e3c2f64733a6461746173746f
72654974656d3e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000105000000000000}}

