<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");

header_forms($admin,$seed);
echo "<br>";

 $query="select * from modir_daneshkade where modir_username='$admin'";
 $result=mysql_query($query) or die("Error");
 $rf=mysql_fetch_array($result) or die("Error");
 $cod_daneshkade=$rf["cod_daneshkade"];
 
 $query="select distinct marhale_report.*,tarh.tarh_title_farsi  from tarh,marhale_report where tarh.cod_tarh=marhale_report.cod_tarh and tarh.cod_daneshkade='$cod_daneshkade' and submit_subadmin='0' and marhale='100'";
 
 
  //$query="select * from marhale_report where cod_tarh='$cod_tarh' and marhale='$marhale'";
   
  $result=mysql_query($query) or die("Error");
   
     $mycount=0;
    if(mysql_num_rows($result) > 0)
    {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"98%\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\" bgcolor= $title_color colspan='6' align=\"center\"  class=\"tahoma1\"><b>مشاهده گزارشات</b></td>";
      echo "</tr>";
      echo "<tr>";
        echo "<td width=\"5%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">تاييد گزارش</td>"; 
      echo "<td width=\"20%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "<td width=\"10%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">تاريخ ارسال</td>";
      echo "<td width=\"10%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">توضيحات</td>";
      echo "<td width=\"30%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">کد طرح</td>";
      echo "<td width=\"30%\" bgcolor= $title_color align=\"center\"  class=\"tahoma1\">نام طرح</td>";
      echo "</tr>";
 $color=$list_color_1;
//$dir_name="../reports/".$cod_tarh;
     //echo $dir_name;
     while($row_fetched=mysql_fetch_array($result))
     {
     	$id=$row_fetched["id"];
     	$cod_tarh=$row_fetched["cod_tarh"];
     	$marhale=$row_fetched["marhale"];
     	
     	$startdate = $row_fetched["send_date"];
  		$startyear = substr($startdate,0,4);
  		$startmon = substr($startdate,5,2);
  		$startday = substr($startdate,8,2);
  		$farsistartdate=hijricalender( $startyear , $startmon , $startday );
  		$farsistartdate = enum2fnum($farsistartdate);
  		$comments=$row_fetched["comments"];
  		if(strlen($comments)<=0)
  		 $comments="&nbsp;";
	      echo "<tr>";
        // echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=send_marhale_report.phtml&admin=$admin&seed=$seed&action=delete_file&cod_tarh=".$cod_tarh."&delete_id=".$id."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\"><a  href=\"submit_marhale.phtml?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&marhale=$marhale\">تاييد</a></td>";
         
		 
		 
	echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\">";	 
		 
	 $dir_name="../reports/".$cod_tarh;	 
	 if ($dir = @opendir($dir_name))
     {
       

     //echo $dir_name;
     $mydir = dir($dir_name);
     //while(($file = $mydir->read()) !== false)
     while($file = $mydir->read())
     {
	   if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0 || strcmp(trim($file),"Thumbs.db")==0) && strcmp(substr($file,0,5),'final')==0 )
	   {
        // echo "<tr>";
         $myq="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='100' and submitted='0'";
         $res=mysql_query($myq) or die("Error");
         if(mysql_num_rows($res)>0)
            $level_submitted='1';
         else 
            $level_submitted='0';  
     	
     	
	    // echo "<tr>";
	    
         //echo "<td ><p align=\"center\"><a href=\"#\" onclick='window.open(\"hazf_item_tarh.phtml?mainwindow=upload_file.phtml&admin=$admin&seed=$seed&action=delete_file&cod_tarh=".$cod_tarh."&delete_id=".$file."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
         echo "<p><a target=\"_blank\" href=\"../reports/$cod_tarh/$file\">".$file."</a></p>";
       //  echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">".$row_fetched["send_date"]."</td>";
        
		// echo "</tr>";
	   }
     }
      closedir($dir);
     // echo "</table>";
	 }

		 
		 
		 
		 
		 
		 
		 
		 
		  echo " </td>";
	 // echo "<td align=\"center\" bgcolor=$color class=\"tahoma1\"><a target=\"_blank\" href=\"../reports/$cod_tarh/$file".$row_fetched["filename"]."\">".$row_fetched["filename"]."</a></td>";
         echo "<td width=\"10%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">".$farsistartdate."</td>";
         echo "<td width=\"10%\" bgcolor=$color align=\"center\"  class=\"tahoma1\">".$comments."</td>";
         echo "<td width=\"30%\" bgcolor=$color   class=\"tahoma1\" dir='rtl' align='right'>".$row_fetched["cod_tarh"]."</td>";
          echo "<td width=\"30%\" bgcolor=$color   class=\"tahoma1\" dir='rtl' align='right'>".$row_fetched["tarh_title_farsi"]."</td>";
         echo "</tr>";
	   
     }
      
      echo "</table>";
	 }
	 else 
	 {
	 	 echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"500\" >";
      echo "<tr>";
       
       
      echo "<td width=\"20%\"  colspan='3' align=\"center\"  class=\"tahoma1\">موردي يافت نشد</td>";
      echo "</tr>";
      echo "</table>";
      
	 }
     
    
     

  

 footer_forms($admin,$seed);
?>



 
