<?
include("include/database-connect.phtml");
include("include/include.phtml");
include("include/vars.inc.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
$query="select * from jalase_shora where shomare_jalase ='$shomare_jalase'";
$result_jalase=mysql_query($query);
$row_fetched_result_jalase=mysql_fetch_array($result_jalase);

//$query="select * from karshenas_shora, jalase_shora_karshenas_shora,jalase_shora where jalase_shora.shomare_jalase='$shomare_jalase' and   jalase_shora.shomare_jalase=jalase_shora_karshenas_shora.shomare_jalase and  jalase_shora_karshenas_shora.cod_karshenas=karshenas_shora.cod_karshenas and jalase_shora.creator='$admin' and karshenas_shora.creator='$admin' group by karshenas_shora.cod_karshenas ";
//echo $query;
$query="select * from karshenas_shora where  karshenas_shora.creator='$admin' group by karshenas_shora.cod_karshenas ";

$result_karshenasan_shora=mysql_query($query) or die("Error in selecting data from karshenas_shora");
$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];
$query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,jalase_shora_tarh where jalase_shora_tarh.shomare_jalase='$shomare_jalase' and jalase_shora_tarh.cod_tarh=tarh.cod_tarh and  vaziat_tarh.vaziat=tarh.vaziat and cod_daneshkade='$cod_daneshkade'  group by tarh.cod_tarh  desc" ;
$color=$list_color_1;
 
$result_tarh_jalase_shora=mysql_query($query) or die("Error in selecting data from tarh");

  echo "<br><table  border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  echo "<tr>";
  echo "<td width=\"50%\"  bgcolor=$color  class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["shomare_jalase"]."</td>";
  echo "<td width=\"50%\"  bgcolor=$color class=\"tahoma1\"  align=\"left\">:شماره جلسه</td>";
  echo "</tr>";
  echo "<tr>";
  echo "<td width=\"50%\"  bgcolor=$color class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["tarikh_jalase"]."</td>";
  echo "<td width=\"50%\" bgcolor=$color  class=\"tahoma1\"  align=\"left\">:تاريخ جلسه</td>";
  echo "</tr>";
  /*echo "<tr>";
  echo "<td width=\"50%\" class=\"tahoma1\" align=\"right\">".$row_fetched_result_jalase["band_azad"]."</td>";
  echo "<td width=\"50%\" class=\"tahoma1\"  align=\"left\">:توضيحات</td>";
  echo "</tr>";*/
  echo "<tr>";
  echo "<td width=\"50%\" class=\"tahoma1\" align=\"right\">&nbsp;</td>";
  echo "<td width=\"50%\" class=\"tahoma1\"  align=\"left\">&nbsp;</td>";
  echo "</tr>";
echo "</table>";
$color=$list_color_1;
 
if(mysql_num_rows($result_karshenasan_shora)>0)
{
 echo "<table border=\"0\"   width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color  colspan=\"2\" class=\"tahoma1\"  align=\"center\"><b>حاضرين در جلسه</b></td>";
    echo "</tr>";
  while($row_fetched=mysql_fetch_array($result_karshenasan_shora))
  {
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
    echo "<td width=\"70%\" bgcolor=$color class=\"tahoma1\" align=\"right\">".$row_fetched["kar_shora_family"]."&nbsp;".$row_fetched["kar_shora_name"]."</td>";
    echo "<td width=\"30%\" bgcolor=$color class=\"tahoma1\"  align=\"left\">:نام و نام خانوادگي</td>";
    echo "</tr>";
  }
  echo "</table>";
}
$color=$list_color_1;
 
if(mysql_num_rows($result_tarh_jalase_shora)>0)
{
 echo "<table border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" bgcolor=$color colspan=\"6\" class=\"tahoma1\"  align=\"center\"><b>وضعيت طرحها در اين جلسه</b></td>";
    echo "</tr>";
  	echo "<tr>";    
    echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بند آزاد</td>";
	echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">بودجه مصوب</td>";
    echo "<td   bgcolor=$color class=\"tahoma1\"  align=\"center\">رتبه طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">وضعيت طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">عنوان طرح</td>";
    echo "<td   bgcolor=$color  class=\"tahoma1\"  align=\"center\">کد طرح</td>";
    echo "</tr>";
  
  $color=$list_color_1;
 
  while($row_fetched=mysql_fetch_array($result_tarh_jalase_shora))
  {
  	$cod_tarh=$row_fetched["cod_tarh"];
	/* $query="select * from tarh,vaziat_tarh where   archieved='0' and  vaziat_tarh.vaziat=tarh.vaziat and (tarh.vaziat='8' or tarh.vaziat='0') and confirm_tarh='1'    and version='-1' and cod_tarh='$cod_tarh'   group by cod_tarh order by tarh_time desc" ;
	$rs_t=mysql_query($query) or die("error");
	$rf_t=mysql_Fetch_array($rs_t);
	$rotbe_tarh=$rf_t["rotbe_tarh"];
	*/
	//$rotbe_tarh=$row_fetched["rotbe_tarh"];
  	$query="select * from jalase_shora_tarh  where cod_tarh='$cod_tarh' and shomare_jalase='$shomare_jalase'";
  	 
  	$res=mysql_query($query)or die("tttt");
  	$row_fetched_budje=mysql_fetch_array($res);
  	
  	$rotbe_tarh=$row_fetched_budje["rotbe_tarh"];
  	
  		 
    $vaziat_shora=$row_fetched_budje["vaziat_tarh_shora"];
    if(strcmp($vaziat_shora,'-1')==0)
      $vaziat_dsc=$row_fetched["vaziat_desc"];
    else 
    {
    	$query="select * from jalase_shora_tarh,vaziat_tarh  where  jalase_shora_tarh.vaziat_tarh_shora =vaziat_tarh.vaziat and shomare_jalase='$shomare_jalase' and cod_tarh='$cod_tarh' ";
  	
     	$res1=mysql_query($query)or die("tttt");
     	$rf_vaziat=mysql_fetch_array($res1);
     	$vaziat_dsc=$rf_vaziat["vaziat_desc"];
    }
  	
  	
  	
  	if(strcmp($color,$list_color_1)==0)
      $color=$list_color_2;
    else
      $color=$list_color_1;
	echo "<tr>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched_budje["band_azad"]."</td>";
	echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched_budje["budjeh"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$rotbe_tarh."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$vaziat_dsc."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\" align=\"right\" dir=\"rtl\">".$row_fetched["tarh_title_farsi"]."</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".$row_fetched["cod_tarh"]."</td>";
    echo "</tr>";
  }
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\">&nbsp;</td>";
  echo "</tr>";
  
  echo "<form name=\"sabt_tarh\" target=\"_blank\" method=\"post\"  action=\"print_jalase.phtml?admin=$admin&seed=$seed&action=sabt&shomare_jalase=$shomare_jalase\">";
  echo "<tr>";  
  echo "<td colspan=\"6\" class=\"tahoma1\" valign=\"top\" align=\"center\"><b>بند آزاد مربوط به جلسه</b></td>";
  echo "</tr>";

  echo "<tr>";
  echo "<td  colspan=\"6\"  align=\"center\"><textarea   rows=\"7\"  name=\"band_azad_jalase\"  class=\"edit-user\"  dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\"></textarea></td>";  
  echo "</tr>";
 
  echo "<tr>";
  echo "<td width=\"30%\" align=\"center\" colspan=\"6\" class=\"tahoma1\"><input type=\"submit\"  value=\"خاتمه و صدور صورت جلسه چاپي \" name=\"finish\" ></td>";
  echo "</tr>";
 
  /*echo "<tr>";
  echo "<br><td colspan=\"6\"  class=\"tahoma1\"  align=\"center\"><b><a target=\"_blank\" href=\"print_jalase.phtml?admin=$admin&seed=$seed&shomare_jalase=$shomare_jalase\">"."چاپ صورت جلسه"."</a></b></td>";
  echo "</tr>";*/
  echo "</form>";
  echo "</table>";
}


footer_forms($admin,$seed);
?>