<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");

echo "<br>";


if(isset($action))
{
  if (strcmp($action,"add_karshenas")==0)
  {

    if( strlen(trim($kar_name)) > 0 &&strlen(trim($kar_family)) > 0   &&  strlen(trim($kar_email)) > 0 &&  strstr($kar_email, '@') &&  strlen(trim($kar_pass)) > 0 &&  strlen(trim($kar_re_pass)) > 0  && strcmp(trim($kar_pass),trim($kar_re_pass))==0 )
    {
      $query="select * from karshenas_tahgig where kar_tahghigh_name=\"$kar_name\" and  kar_tahghigh_family=\"$kar_family\" and kar_tahghigh_email=\"$kar_email\" and  shenasname=\"$shenasname\" and sal_tavalod=\"$saltavalod\" and fath_name=\"$nampedar\" and fath_name_e=\"$nampedar_e\"";

      $result=mysql_query($query) or die("Error in selecting data from karshenas tahghigh ");

      if ( mysql_num_rows($result) <= 0 )
      {

        $query="insert into karshenas_tahgig set kar_tahghigh_name='$kar_name' ,kar_tahghigh_name_e='$kar_name_e', kar_tahghigh_family='$kar_family', kar_tahghigh_family_e = '$kar_family_e',  kar_tahghigh_rade_elmi='$kar_rade_elmi',  kar_tahghigh_takhasos  = '$kar_takhasos', kar_tahghigh_takhasos_e  = '$kar_takhasos_e',  kar_tahghigh_email  ='$kar_email', cod_daneshkade='$daneshkade' , shenasname='$shenasname' , sal_tavalod='$saltavalod' , fath_name='$nampedar', fath_name_e='$nampedar_e', creator='$admin', password='$kar_pass',melli_code='$cod_melli'";

        $result=mysql_query($query) or die("Error in inserting data into karshenas tahghigh 1");

      }
      else
       $status="duplicate_entry";
    }
    else
      $status="entry_error";
  }

 if (strcmp($action,"delete_karshenas")==0)
 {
    $query="delete from karshenas_tahgig where cod_karshenas = \"$delete_id\"";

    $result=mysql_query($query) or die("Error in  delete data from karshenas ravesh tahgig");
 }


}



?>


<? echo "<form name=\"add_karshenas\" method=\"post\"  action=\"$PHP_SELF?action=add_karshenas&admin=$admin&seed=$seed\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="249"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/karshenas_ravesh_tahgig.gif" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>


<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين کاربري قبلا تعريف شده</td>";
    echo "</tr>";
  }
?>
  <tr>
    <td width="350" align="right"><input type="text" name="kar_name" size="20" class="edit-user"dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام</td>
  </tr>
   <tr>
    <td width="350" align="right"><input type="text" name="kar_name_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام (انگليسي</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="kar_family" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>نام خانوادگي</td>
  </tr>
   <tr>
    <td width="350" align="right"><input type="text" name="kar_family_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام خانوادگي(انگليسي</td>
  </tr>

   <tr>
    <td width="350" align="right"><input type="text" name="shenasname" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">شماره شناسنامه</td>
  </tr>
    <tr>
    <td width="350" align="right">
    

    <input type="text" name="saltavalod" size="20" class="edit-user" value="فقط سال تولد را  بصورت چهار رقمي وارد کنيد" onfocus="saltavalod.value='' "></td>
    <td width="150" class="tahoma1">سال تولد</td>
  </tr>

    <tr>
    <td width="350" align="right"><input type="text" name="nampedar" size="20" class="edit-user"  dir=RTL   ></td>
    <td width="150" class="tahoma1">نام پدر</td>
  </tr>

   <tr>
    <td width="350" align="right"><input type="text" name="nampedar_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(نام پدر (انگليسي</td>
  </tr>
  <tr>
    <td width="350" align="right"><input type="text" name="cod_melli" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">کد ملي</td>
  </tr>
 <tr>
    <td width="350"  align="right"><input type="text" name="kar_email" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>پست الکترونيکي</td>
  </tr>
  <tr>
  <?
    $query="select * from darajeelmi order by darajeelmi_desc ";
    $qresult=mysql_query($query) or die("Error in selecting data from daraje elmi");

  ?>
    <td width="350" align="right"><select size="1" name="kar_rade_elmi" class="edit-user" dir="rtl">
    <option value="-1" class="tahoma1">انتخاب کنيد</option>
    <?

    while($row_fetched=mysql_fetch_array($qresult))
    {
      echo "<option value=\"".$row_fetched["darajeelmi"]."\" class=\"tahoma1\">".$row_fetched["darajeelmi_desc"]."</option>";
    }
    ?>
    </select></td>
    <td width="150" class="tahoma1">درجه علمي</td>
  </tr>
  <tr>
    <td width="350" align="right"><input type="text" name="kar_takhasos" size="20" class="edit-user" dir=RTL   ></td>
    <td width="150" class="tahoma1">تخصص</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="text" name="kar_takhasos_e" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1">(تخصص (انگليسي</td>
  </tr>


   <tr>
    <td width="350" align="right"><input type="password" name="kar_pass" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>کلمه عبور</td>
  </tr>

  <tr>
    <td width="350" align="right"><input type="password" name="kar_re_pass" size="20" class="edit-user" ></td>
    <td width="150" class="tahoma1"><span class="star-message">*</span>تکرار کلمه عبور</td>
  </tr>
  

  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>
</table>

</form>


 <?
   $query="select * from karshenas_tahgig  order by  kar_tahghigh_name ";
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
   if(mysql_num_rows($result) > 0)
   {
    echo "<br>";
    echo "<table border=\"1\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<table border=\"0\" width=\"500\"  cellspacing=\"0\" cellpadding=\"0\" >";
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/top-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">کلمه عبور</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">حذف</td>";
    echo "<td width=\"47\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">ويرايش</td>";
    echo "<td width=\"163\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام خانوادگي</td>";
    echo "<td width=\"164\" background=\"image/top-top.gif\" height=\"20\" class=\"tahoma1\" align=\"center\">نام</td>";
    echo "<td width=\"16\"  background=\"image/top-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   $color="#E2E0E0";
   while($myrow_fetched=mysql_fetch_array($result))
   {
    if(strcmp($color,"#E2E0E0")==0)
      $color="#CFCDCD";
    else
      $color="#E2E0E0";
    echo "<tr bgcolor=\"$color\">";
    echo "<td width=\"16\" background=\"image/left-left.gif\" height=\"20\"></td>";
    echo "<td width=\"47\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"changepass_dan.phtml?mainwindow=karshenas_ravesh_tahgig.phtml&admin=$admin&seed=$seed&daneshkade=$daneshkade&action=chgpass_daneshkade&changpass_id=".$myrow_fetched["cod_modir"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/password.gif\" width=\"11\" height=\"13\" alt=\"Change Password\" ></a></td>";
//    echo "<td width=\"27\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_admin_dan.phtml?mainwindow=karshenas_ravesh_tahgig.phtml&admin=$admin&seed=$seed&daneshkade=$daneshkade&action=delete_daneshkade&delete_id=".$myrow_fetched["cod_modir"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"27\"><p align=\"center\"><a href=\"#\" onclick='window.open(\"del_karshenas.phtml?mainwindow=karshenas_ravesh_tahgig.phtml&admin=$admin&seed=$seed&action=delete_karshenas&delete_id=".$myrow_fetched["cod_karshenas"]."\",\"popupwindow\",\"toolbar=no,status=no,scrollbars=no,width=250,height=120,left=((screen.width-250) / 2),top=((screen.height - 120) / 2),resizable=no\")'><img border=\"0\" src=\"image/button_drop.png\" width=\"11\" height=\"13\" alt=\"Delete\" ></a></td>";
    echo "<td width=\"27\"><p align=\"center\"><img border=\"0\" src=\"image/button_edit.png\" width=\"11\" height=\"13\" alt=\"Edit\" ></td>";
    $mycod_karshenas = $myrow_fetched["cod_karshenas"];
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\"  href=\"karshenas_ravesh_tahgig_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["kar_tahghigh_family"],0,18)."</a></p></td>";
    echo "<td  class=\"tahoma1\" align=\"right\"><p align=\"center\" class=\"tahoma1\"><a style=\"text-decoration:none\" href=\"karshenas_ravesh_tahgig_detail.phtml?admin=$admin&seed=$seed&cod_karshenas=$mycod_karshenas\">".substr($myrow_fetched["kar_tahghigh_name"],0,18)."</a></p></td>";
	echo "<td width=\"16\" background=\"image/right-right.gif\" height=\"20\"></td>";
    echo "</tr>";
   }
    echo "<tr>";
    echo "<td width=\"16\" background=\"image/left-bot.gif\" height=\"20\"></td>";
    echo "<td width=\"47\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"27\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"27\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"133\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"134\" background=\"image/bot-bot.gif\" height=\"20\" class=\"tahoma1\" align=\"center\"></td>";
    echo "<td width=\"16\"  background=\"image/right-bot.gif\" height=\"20\"></td>";
    echo "</tr>";

   echo "</table>";

  }
  footer_forms($admin,$seed);
 ?>




