<?
include("include/database-connect.phtml");
include("include/include.phtml");

global $HTTP_GET_VARS,$HTTP_POST_VARS;
while(list($key, $value) = each($HTTP_GET_VARS))
$$key = $value;

while(list($key, $value) = each($HTTP_POST_VARS))
$$key = $value;


 if(!isset($admin))
  $admin="";
 if(!isset($seed))
  $seed="";
 if(isset($admin) && isset($seed))
 {
  $type = checksession($admin,$seed);
  if( $type ==2 )
    updatesession($admin,$seed);
  else
  {
   header ("Refresh: 0; url=../login.phtml");
   exit();
  }
 }

include("include/vars.inc.phtml");

include("include/styles.phtml");

$query="select * from jalase_shora,modir_daneshkade where jalase_shora.creator=modir_daneshkade.modir_username and jalase_shora.shomare_jalase='$shomare_jalase'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];
$myq="select * from daneshkade where cod_daneshkade='$cod_daneshkade'";
  	$myres=mysql_query($myq);
  	$myrf=mysql_fetch_array($myres);
  	$daneshkade_name=$myrf["daneshkade_name"];

$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
//$cod_daneshkade=$myrow_fetched["cod_daneshkade"];



if(isset($action))
{
  if (strcmp($action,"sabt")==0)
  {
  	$query="update jalase_shora set band_azad='$band_azad_jalase' where shomare_jalase='$shomare_jalase'";
	//echo $query;
  	$result=mysql_query($query) or die("Error in selecting data from jalase_shora");
  }
}
$query="select * from jalase_shora where shomare_jalase ='$shomare_jalase'";
$result_jalase=mysql_query($query);
$row_fetched_result_jalase=mysql_fetch_array($result_jalase);

$query="select * from karshenas_shora, jalase_shora_karshenas_shora where   jalase_shora_karshenas_shora.cod_karshenas=karshenas_shora.cod_karshenas and jalase_shora_karshenas_shora.shomare_jalase ='$shomare_jalase'";
$query="select * from karshenas_shora, jalase_shora_karshenas_shora,jalase_shora where jalase_shora.shomare_jalase='$shomare_jalase' and   jalase_shora.shomare_jalase=jalase_shora_karshenas_shora.shomare_jalase and  jalase_shora_karshenas_shora.cod_karshenas=karshenas_shora.cod_karshenas and jalase_shora.creator='$admin' and karshenas_shora.creator='$admin' group by karshenas_shora.cod_karshenas ";
$query="select * from karshenas_shora where  (cod_daneshkade='$cod_daneshkade' or cod_daneshkade_second='$cod_daneshkade' or cod_daneshkade_third='$cod_daneshkade' or cod_daneshkade_4='$cod_daneshkade' or cod_daneshkade_5='$cod_daneshkade' or cod_daneshkade_6='$cod_daneshkade' or cod_daneshkade_7='$cod_daneshkade' or cod_daneshkade_8='$cod_daneshkade' or cod_daneshkade_9='$cod_daneshkade' or cod_daneshkade_10='$cod_daneshkade') group by karshenas_shora.cod_karshenas ";
$result_karshenasan_shora=mysql_query($query) or die("Error in selecting data from karshenas_shora");
$query="select * from modir_daneshkade where modir_username ='$admin'";
$result=mysql_query($query) or die("Error in selecting data from modir_daneshkade");
$myrow_fetched = mysql_fetch_array($result);
$cod_daneshkade=$myrow_fetched["cod_daneshkade"];

$query="select tarh.*,vaziat_tarh.* from tarh,vaziat_tarh,jalase_shora_tarh where jalase_shora_tarh.shomare_jalase='$shomare_jalase' and jalase_shora_tarh.cod_tarh=tarh.cod_tarh and  vaziat_tarh.vaziat=tarh.vaziat  group by tarh.cod_tarh  desc" ;


//echo $query;

$result_tarh_jalase_shora=mysql_query($query) or die("Error in selecting data from tarh");

  echo "<table border=\"0\" width=\"100%\" cellpadding\"1\" cellspacing=\"1\">";

   echo "<tr>";
  echo "<td width=\"100%\" class=\"tahoma1\" align=\"center\" dir=\"ltr\"><b>بسمه تعالي</b></td>";  
  echo "</tr>";
  echo "<tr>";
  echo "<td width=\"100%\" class=\"tahoma1\" align=\"center\" dir=\"ltr\"><b> جلسه ".enum2fnum($row_fetched_result_jalase["shomare_jalase"])." مربوط به دانشکده / مرکز ".$daneshkade_name."</b></td>";  
  echo "</tr>";

  echo "<tr>";
  echo "<td width=\"100%\" class=\"tahoma1\" align=\"right\"><b>".enum2fnum($row_fetched_result_jalase["shomare_jalase"])."</b>:شماره جلسه</td>";  
  echo "</tr>";

  echo "<tr>";
  echo "<td width=\"100%\" class=\"tahoma1\" align=\"right\"><b>".enum2fnum($row_fetched_result_jalase["tarikh_jalase"])."</b>:تاريخ جلسه</td>";  
  echo "</tr>";

  echo "<tr>";
  echo "<td width=\"50%\" class=\"tahoma1\" align=\"right\">&nbsp;</td>";
  echo "<td width=\"50%\" class=\"tahoma1\"  align=\"left\">&nbsp;</td>";
  echo "</tr>";
echo "</table>";

if(mysql_num_rows($result_tarh_jalase_shora)>0)
{
 echo "<br><table border=\"1\" width=\"100%\" cellpadding\"0\" cellspacing=\"0\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" colspan=\"5\" class=\"tahoma1\"  align=\"center\"><b>وضعيت طرحها در اين جلسه</b></td>";
    echo "</tr>";
  	 
    $row_number=1;
  while($row_fetched=mysql_fetch_array($result_tarh_jalase_shora))
  {
  	$cod_tarh=$row_fetched["cod_tarh"];

  $myquery_mojri = "SELECT  * FROM tarh, user_login WHERE tarh.creator = user_login.email AND tarh.cod_tarh = '$cod_tarh'";
  $myresult_mojri = mysql_query( $myquery_mojri ) or die("Error in selecting data from First mojri");
  $mojri_tag="1";
  if(mysql_num_rows($myresult_mojri) > 0 )
  {
    $First_mojri = mysql_fetch_array( $myresult_mojri );
    $First_mojri_name = $First_mojri["name"]."&nbsp;".$First_mojri["family"];
  }
  else
  {
    $mojri_tag="0";
    $First_mojri_name = "اطلاعات موجود نيست";
  }  	
     

  	$query="select * from jalase_shora_tarh  where cod_tarh='$cod_tarh' and shomare_jalase='$shomare_jalase'";
  	//echo $query;
  	$res=mysql_query($query)or die("tttt");
  	$row_fetched_budje=mysql_fetch_array($res);
    $rank_year=substr($cod_tarh,0,5); 
    $vaziat_shora=$row_fetched_budje["vaziat_tarh_shora"];
	$rotbe_tarh=$row_fetched_budje["rotbe_tarh"];
    if(strcmp($vaziat_shora,'-1')==0)
      $vaziat_desc=$row_fetched["vaziat_desc"];
    else 
    {
    	$query="select * from jalase_shora_tarh,vaziat_tarh  where  jalase_shora_tarh.vaziat_tarh_shora =vaziat_tarh.vaziat and shomare_jalase='$shomare_jalase' and cod_tarh='$cod_tarh' ";
  	
     	$res1=mysql_query($query)or die("tttt");
     	$rf_vaziat=mysql_fetch_array($res1);
     	$vaziat_desc=$rf_vaziat["vaziat_desc"];
    }
	/*
	$string1=" بررسي شد ".
	$row_fetched["vaziat_desc"].
	" با وضعيت ".
	$rank_year.
	.
	$row_fetched["rotbe_tarh"].
	  .
	*/
	$rank_year="<span dir='ltr'>".$rank_year."</span>";
	$band_azad_print=$row_fetched_budje["band_azad"];
	//echo $band_azad_print;
	if(strlen(trim($band_azad_print)) > 0)
	   $band_azad_print=" توضيحات طرح : ".$band_azad_print;
	else
	   $band_azad_print="";     
	   
	
	 /*  
	 $query="select * from tarh,vaziat_tarh where   archieved='0' and  vaziat_tarh.vaziat=tarh.vaziat and (tarh.vaziat='8' or tarh.vaziat='0') and confirm_tarh='1'    and version='-1' and cod_tarh='$cod_tarh'   group by cod_tarh order by tarh_time desc" ;
	$rs_t=mysql_query($query) or die("error");
	$rf_t=mysql_Fetch_array($rs_t);
	$rotbe_tarh=$rf_t["rotbe_tarh"];
	   */
	$string1=" طرح تحقيقاتي به شماره "."<span dir='ltr'>".enum2fnum($cod_tarh)."</span>"." با عنوان ".$row_fetched["tarh_title_farsi"]." مجري آقاي / خانم ".$First_mojri_name." با بودجه ".$row_fetched_budje["budjeh"]."  و رتبه ".$rotbe_tarh." در رنک ".$rank_year."  ".$vaziat_desc." شد ".$band_azad_print;
	
	
  	echo "<tr>";
    echo "<td dir=\"rtl\"  class=\"tahoma1\"  align=\"right\"><span dir='rtl'>$string1</span></td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">".enum2fnum($row_number)."</td>";
    $row_number++;
    echo "</tr>";
	 
  }
  
  $query="select * from jalase_shora where  shomare_jalase='$shomare_jalase'";
	 //echo $query;
  	$result=mysql_query($query) or die("Error in selecting data from jalase_shora");
	$rf_band=mysql_fetch_Array($result);
	$band_azad_jalase=$rf_band["band_azad"];
    echo "<tr>";
    echo "<td dir=\"ltr\"  class=\"tahoma1\"   align=\"right\">$band_azad_jalase</td>";
    echo "<td   class=\"tahoma1\"  align=\"center\">توضيحات</td>";
    
    echo "</tr>";
  echo "</table>";
}

if(mysql_num_rows($result_karshenasan_shora)>0)
{
 echo "<br><table border=\"1\" width=\"100%\" cellpadding\"0\" cellspacing=\"0\">";
  	echo "<tr>";    
    echo "<td width=\"100%\" colspan=\"2\" class=\"tahoma1\"  align=\"center\"><b>امضاء حاضرين در جلسه</b></td>";
    echo "</tr>";
  
  while($row_fetched=mysql_fetch_array($result_karshenasan_shora))
  {
  
	echo "<tr>";
	

      echo "<td width=\"33%\" height=\"60\" class=\"tahoma1\" dir=\"rtl\" align=\"right\">"."<br>".$row_fetched["kar_shora_name"]."&nbsp;".$row_fetched["kar_shora_family"]."</td>";
	 


    echo "</tr>";
    
  }
  echo "</table>";
}



?>