<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/class.phpmailer.php");
include("include/mailserver-statistics.phtml");
require_once('lib/nusoap.php');

echo "<br>";


 $q1="select * from modir_daneshkade,daneshkade where modir_username='$admin' and daneshkade.cod_daneshkade=modir_daneshkade.cod_daneshkade";
  	    			$rslt=mysql_query($q1);
  	    			$rff=mysql_fetch_array($rslt);
  	    			$have_group=$rff["have_group"];
					$cod_daneshkade=$rff["cod_daneshkade"];
					$mostaghel=$rff["mostaghel"];


if(isset($action))
{
   if (strcmp($action,"change_status")==0   )
  {
  	$query_tarh_d="select * from daneshkade_tarh where cod_tarh='$cod_tarh' and cod_daneshkade='$cod_daneshkade' and visible='1'";
 	$result_tarh_d=mysql_query($query_tarh_d) or die("Error in updating data into tarh");
    if(mysql_num_rows($result_tarh_d) > 0){
    	$query="update daneshkade_tarh set submission_center_status ='1' where cod_tarh=\"$cod_tarh\" and cod_daneshkade='$cod_daneshkade' ";
    	$result=mysql_query($query) or die("Error in updating tarh type in tarh");
    	$query="update tarh set  new_gharardad_daneshkade  ='0' , submission_center_status ='1',finished='1' where cod_tarh='$cod_tarh' and version='-1'";
    }
    else
    $query="update tarh set  new_gharardad_daneshkade  ='0' , submission_center_status ='1',finished='1' where cod_tarh='$cod_tarh' and version='-1'";
  //  echo $query;
   //exit();
    $result=mysql_query($query) or die("Error in updating tarh type in tarh");
    insert_position($cod_tarh,"3",$admin);
     if(strcmp($mostaghel,"0")==0)
     {
	  ?>
           <script language="javascript">
           window.location="<? echo "tarh_list_new_after_submit".".phtml?admin=$admin&seed=$seed";  ?>";
           </script>
           <?
      }
	  else
	  {
     ?>
           <script language="javascript">
           window.location="<? echo "tarh_list_new_after_submit_mostaghel".".phtml?admin=$admin&seed=$seed";  ?>";
           </script>
           <?
	  }
  }

}
$query="select * from daneshkade,modir_daneshkade,jalase_shora_tarh where daneshkade.cod_daneshkade=modir_daneshkade.cod_daneshkade and daneshkade.cod_daneshkade='$cod_daneshkade' and jalase_shora_tarh.creator= modir_daneshkade.modir_username  and  cod_tarh='$cod_tarh' ";
  ////echo $query;
  $result3=mysql_query($query) or die("Error in selecting data from karshenas elmi ");

?>



<? echo "<form name=\"change_status\" method=\"post\" action=\"$PHP_SELF?action=change_status&admin=$admin&seed=$seed&cod_tarh=$cod_tarh&main_window=$main_window\">"; ?>

<table border="0"  width="500" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 width="100%" cellPadding=0 border=1>
  <TBODY>
    <TR>
    <TD align=right width="100%"  class="tahoma1" height=19>
     
      ارسال به طرح هاي بعد از تصويب
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">


 <tr>
    <td width="100%" colspan="2" class="tahoma1">
      <p align="center">ارسال به طرحهاي بعد از تصويب</td>
</tr>
 
<?
 /*if (mysql_num_rows($result3)<=0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">طرح قابل ارسال نيست<br>لطفا قبل از ارسال طرح به دانشکده صورتجلسه مربوط به اين طرح را تنظيم کنيد</td>";
    echo "</tr></table>";
    footer_forms($admin,$seed);
    exit();
  }*/
?>
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>


</form>
<table border="0" width="500">
<tr>
    <td width="50%" colspan="2" align="center" class="tahoma1"><a style="text-decoration:none" href="javascript:go(-1)" >بازگشت</a></td>
  </tr>
</table>
<?

  footer_forms($admin,$seed);
 ?>




