<?
include("include/database-connect.phtml");
include("include/include.phtml");
require("include/class.phpmailer.php");
header_forms($admin,$seed);
include("include/styles.phtml");
include("include/vars.inc.phtml");
include("include/print.phtml");
require("include/mailserver-statistics.phtml");


 $q1="select * from modir_daneshkade,daneshkade where modir_username='$admin' and daneshkade.cod_daneshkade=modir_daneshkade.cod_daneshkade";
  	    			$rslt=mysql_query($q1);
  	    			$rff=mysql_fetch_array($rslt);
  	    			$daneshkade=$rff["daneshkade_name"];
  
if(isset($showall))
    if($showall==1)
    {
      $RecPerPage=1000;
      $current=1;
    }
     

if ( ! isset($current))
    $current = 1;

if( ! isset($startw))
    $startw = 0;

if ( !isset($endw))
    $endw = 0;

if(isset($action))
{
  $i=0;
  if (strcmp($action,"send_karshenas")==0)
  {
   for($i==0;$i<100;$i++)
   {
    $myvariable="check".$i;
    $myuser="value_".$i;
    if (isset($$myvariable))
    {
      $myvariable="check".$i;
      $myuser="value_".$i;
      $mycodkarshenas = "cod_karshenas_".$i;
      $myname_family="name_".$i;
      $send_comment_add="g".$i;
         $send_comment=$$$send_comment_add;
      

	 // $i++;
		$send_comment=$send_comment."<br>"." "."ادمين"." ".$daneshkade;
	
	//  $mail = new PHPMailer();
	 // ob_start();
	  //send_mail_tarh($cod_tarh);
     // $emailbody=ob_get_contents();
    //  ob_end_clean();
    //  ob_end_flush();

    //  $mail->IsSMTP();                                      // set mailer to use SMTP
    //  $mail->SMTPAuth=$smtpauth;
   //   $mail->Username=$email_username;
   //   $mail->Password=$email_password;
   //   $mail->Host = $mailserver_host;  // specify main and backup server

     // $mailname=$$myname_family;
    //  $mail->From = $email_from;
	//  $mail->FromName = $email_from_name;
    //  $mail->AddAddress($$myuser, $mailname);
    //  $mail->IsHTML(true);                                  // set email format to HTML

     // $mail->Subject = "طرح پژوهشي ارسال شده از طرف مدير سيستم";
     // $mail->Body    = $emailbody;
    //  $mail->AltBody = "This is the body in plain text for non-HTML mail clients";
     /* if(!$mail->Send())
      {
          $status="mail_err";
      }
      else
      {
          message_show(".طرح به کارشناس مربوطه ارسال شد","green");
          footer_forms($admin,$seed);
          exit();
      }*/

	  //$i++;

	  $query="select * from karshenasan_tarh where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	  $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh");
	  if ( mysql_num_rows($result)==0 )
	  {
	    $query="insert into karshenasan_tarh set cod_tarh=\"$cod_tarh\" , cod_karshenas=\"".$$mycodkarshenas."\",send_comment='$send_comment'";
	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh");
	  }
	  else
	  {
	    $query="update karshenasan_tarh set refered='0',send_comment='$send_comment' where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	    
	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh");
	  }
	  
    }
    
     $del_variable="del_check".$i;
    $myuser1="value_".$i;
    if (isset($$del_variable))
    {
      $del_variable="del_check".$i;
      $myuser="value_".$i;
      $mycodkarshenas = "cod_karshenas_".$i;
      $myname_family="name_".$i;
	 

	 // $i++;

	  $query="select * from karshenasan_tarh where cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	  $result=mysql_query($query) or die("Error in selecting data from karshenas_elmi_tarh 5");
	  if ( mysql_num_rows($result)>0 )
	  {
	    $query="delete from  karshenasan_tarh where  cod_tarh=\"$cod_tarh\" and cod_karshenas=\"".$$mycodkarshenas."\"";
	    //echo $query;
	    $result = mysql_query($query) or die ("error in inserting data into karshenas_elmi_tarh 6");
	  }
	 
    }
    
    
    $del_variable="lovely".$i;
    $myuser1="value_".$i;
  }

  }
}
   echo "<br>";
   
   
   
$grant_hsr_isolation='tarh_type!=6';

$myq="select * from tarhtype_2 where grant_tarh='1'";
$res=mysql_query($myq) or die("Error");
$grant_q="";
While($myrf=mysql_fetch_array($res) )
{
	$grant_q=$grant_q." and "."tarh_type_2 != '".$myr["tarh_type"]."'";
}
$grant_hsr_isolation=$grant_hsr_isolation.$grant_q;

  
   if(isset($name_e) && strlen($name_e) > 0)
     $search_string="(karshenas_name like '%$name_e%' or karshenas_family like '%$name_e%')  ";
   else
     $search_string="1 ";
   
   $query="select * from karshenasan,karshenas_type  where $search_string  and karshenasan.karshenas_type=karshenas_type.karshenas_type   order by karshenasan.karshenas_family asc"; 
   
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh 1 444");
   $reccount=mysql_num_rows($result);
   
   $query="select * from karshenasan,karshenas_type  where   $search_string and  karshenasan.karshenas_type=karshenas_type.karshenas_type  order by karshenasan.karshenas_family "." limit ".($current-1)*$RecPerPage.",".$RecPerPage ; 
   
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh 2");

 
   if(mysql_num_rows($result) > 0)
   {
   	$myascdescpub=$myascdescpub."&name_e=$name_e&alaghe_type=$alaghe_type&favorite_no_favorite=$favorite_no_favorite&cod_tarh=$cod_tarh";
   	pubshowpages("send_karshenas.phtml",$current,$PageCountShows,$reccount,$startw,$endw,$RecPerPage,$admin,$seed,$myascdescpub,"90%",$title_color);
   // echo "<br>";
//    $query="select * from mojri , mojri_tarh where mojri.mojri_code = mojri_tarh.mojri_code and mojri_tarh.cod_tarh=\"$cod_tarh\"   order by  family ";
  //  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");

    ?>

    <table border="0" width="90%" cellpadding="1" cellspacing="1">
    <tr>
    <td width="100%" bgcolor="#66CCFF"  colspan="6">

      <p align="center" class="tahoma1"><font color="black">ارسال براي کارشناسان </font></td>
    </tr>
     <tr>
  <?
  echo "</form>";
   echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?admin=$admin&seed=$seed&cod_tarh=$cod_tarh&alaghe_type=$alaghe_type&favirite_no_favorite=$favorite_no_favorite\">";
   ?>
 <td align="right" width="100%" bgcolor="#66CCFF"  colspan="12">
 <input type="submit" name="submit" value="جستجو" class="but-small">
 <input type="text" name="name_e" size="20" class="edit-small-2"  dir=RTL value='<? echo trim($name_e); ?>'  >
 </td>
 
 </tr>
 </form>
 <? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=send_karshenas&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>
 
	<tr>
	<td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">توضيحات</font></td>
	<td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">باز پس گيري</font></td>
    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">ارسال</font></td>
	<td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">وضعيت ارسال</font></td>
    <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">پست الکترونيکي</font></td>
   <td width="3%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نوع کارشناس</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td width="35%" bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
    </tr>
  <?

 $color=$list_color_1;
 
  $i=0;
 while($row_fetched=mysql_fetch_array($result))
 {
 // $cod_tarh=$row_fetched["cod_tarh"];
  $cod_karshenas=$row_fetched["cod_karshenas"];
  $query="select * from karshenasan_tarh where cod_karshenas='$cod_karshenas' and cod_tarh='$cod_tarh'";
  
  $result1=mysql_query($query);
  if(mysql_num_rows($result1) > 0)
  {
     $sended="<b>به اين کارشناس ارسال شده</b>";
     
  }
  else
  $sended="به اين کارشناس ارسال نشده";
  $rf1=mysql_fetch_array($result1);
   $send_comment1=$rf1["send_comment"];
  if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
   echo "<input type=\"hidden\" name=\"g".$i."\" value=\"send_comment".$i."\">";
   echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><textarea   rows=\"3\"  name=\"send_comment".$i."\" class=\"edit-user\"   dir=RTL  onkeydown=\"return FarsiKeyDown()\" onkeypress=\"return FarsiKeyPress()\">$send_comment1</textarea></td>"; 
   echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"del_check".$i."\"  value=\"ON\"></td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"check".$i."\"  value=\"ON\"></td>";
  echo "<input type=\"hidden\" name=\"value_".$i."\" value=\"".$row_fetched["karshenas_email"]."\">";
  echo "<input type=\"hidden\" name=\"name_".$i."\" value=\"".$row_fetched["karshenas_name"]."&nbsp;".$row_fetched["kar_tahghigh_family"]."\">";
  echo "<input type=\"hidden\" name=\"cod_karshenas_".$i."\" value=\"".$row_fetched["cod_karshenas"]."\">";
  
echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$sended."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_family"]."</td>";
  echo "<td width=\"30%\" bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched["karshenas_name"]."</td>";
  echo "</tr>";
  $i++;
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 }


echo "</table>";
echo "<br><input type=\"submit\" value=\"ارسال\" name=\"B1\" class=\"but-small\"><br>";
echo "</form>";
}
else // if reccount of tarh  < =0
{
 message_show(".هيچ کارشناسي  يافت نشد","red");
}
$query="select * from karshenasan_tarh,karshenasan where karshenasan.cod_karshenas=karshenasan_tarh.cod_karshenas and cod_tarh='$cod_tarh' group by karshenasan.cod_karshenas";
		$result1=mysql_query($query)or die("Error in selecting data from karshenasan");;
		if(mysql_num_rows($result1) > 0)
		{
		
?>
 <table border="0" width="90%" cellpadding="1" cellspacing="1">
 
<tr>
<td width="100%" bgcolor="#66CCFF"  colspan="11">

      <p align="center" class="tahoma1"><font color="black"><b>ليست کارشناساني که طرح براي آنها ارسال شده </b></font></td>
  
</tr>
	<tr>
	 	 <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">توضيحات</font></td>
	 	 <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح در دست ايشان</font></td>
 <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تعداد طرح داوري /نظارت شده</font></td>

    
     <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">تخصص</font></td>

    <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام خانوادگي</font></td>
    <td   bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">نام</font></td>
        <td  bgcolor="#66CCFF">
      <p align="center" class="tahoma1"><font color="black">رديف</font></td>
    </tr>
   
  
   <?php 
   $j=0;
    while($row_fetched2=mysql_fetch_array($result1))
 {
 	$cod_karshenas=$row_fetched2["cod_karshenas"];
 	$send_comment2=$row_fetched2["send_comment"];
 	
 	 $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas' and finished ='1'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh_karshenasi=$rf1["cnt"];
  
  $q1="select count(*) as cnt from karshenasan_tarh where cod_karshenas='$cod_karshenas'";
  $res1=mysql_query($q1) or die("Error in selecting data from karshenasan");
  $rf1=mysql_fetch_array($res1);
  $cnt_tarh=$rf1["cnt"];
   if(strcmp($color,$list_color_1)==0)
   $color=$list_color_2;
  else
   $color=$list_color_1;
  echo "<tr>";
  
// echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\"><input type=\"checkbox\" name=\"del_check".$i."\"  value=\"ON\"></td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$send_comment2."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$cnt_tarh_karshenasi."</td>";
 
  
 
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_email"]."</td>";
//  echo "<td width=\"20%\" bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched["karshenas_type_desc"]."</td>";

 echo "<td  bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched2["karshenas_takhasos"]."</td>";
  echo "<td   bgcolor=$color align=\"center\" class=\"tahoma1\">".$row_fetched2["karshenas_family"]."</td>";
  echo "<td   bgcolor=$color align=\"right\" class=\"tahoma1\">".$row_fetched2["karshenas_name"]."</td>";
  $mycntr=$j+1;
  echo "<td  bgcolor=$color align=\"right\" class=\"tahoma1\">".$mycntr."</td>";
  echo "</tr>";
  $j++;
 /* if (strcmp($color,"#DADADA")==0)
    $color="#EFEFEF";
  else
    $color="#DADADA";*/
 
  
  
 	
 }
		echo "</table>";
		}else
 echo "<b>به کارشناسي ارسال نشده</b>";
  ?>
  
<?php 





footer_forms($admin,$seed);
?>

