<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);

include("include/styles.phtml");
include("include/vars.inc.phtml");
require("include/class.phpmailer.php");
require("include/mailserver-statistics.phtml");
require_once('lib/nusoap.php');

echo "<br>";

//if(isset($telno)) 
if(isset($action))
if(strcmp($action,"send_email")==0)
if(   strlen(trim($telno))==11)
{
   if(strlen($telno)==11)
   {
   	   //$letter_body = iconv("windows-1256", "UTF-8", $letter_body);

   	  // $letter_body=arabic2utf($letter_body);
   	  $letter_body_org=$letter_body;
   	 // $letter_body=iconv("windows-1256", "UTF-8",$letter_body);
   	   $letter_body=$letter_body;
   	   
       send_sms("$telno",$letter_body,$admin);
       $query="insert into subadmin_sms set sender='$admin',telno='$telno',letter_body='$letter_body_org'";
    //   echo $query;
       $result=mysql_query($query) or die("error3");
       message_show("پيام شما ارسال شد","green");
       footer_forms($admin,$seed);
       exit();
       
   }
    else
	 $status="mobile_error";   
       
}
 else
  $status="entry_error";

if(isset($action))  
   if (strcmp($action,"del")==0)
  {
  	$query="delete from sms_user where id='$delete_id'";
  	$result=mysql_query($query) or die("error");
  }
?>




<? echo "<form name=\"sms\" method=\"post\"  action=\"subadmin_send_sms.phtml?action=send_email&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>
<TABLE cellSpacing=0 cellPadding=0 width="500" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 width="100%" cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=right class="tahoma1" width="100%" align="right"  height=19>
    ارسال پيام کوتاه  
	   </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>

  <table border="0"  width="500" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
   <?
      if (strcmp($status,"mobile_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">شماره تلفن همراه موجود در پروفايل مجري صحيح نيست</td>";
    echo "</tr>";
  }
     if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">مواردي که با ستاره مشخص شده اند را بطور کامل پر کنيد</td>";
    echo "</tr>";
  }
  if (strcmp($status,"entry_error_1")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">روي اين شورا کارشناس تعريف شده و قابل حذف نيست</td>";
    echo "</tr>";
  }
  if (strcmp($status,"duplicate_entry")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">چنين موردي قبلا تعريف شده</td>";
    echo "</tr>";
  }
  
  if(isset($telno))
    $telno=$telno;
  else  
  $telno=""; 
  
  if(isset($mojri_username)) 
  {
  	$query_mojri="select * from user_login where email='$mojri_username'";
  	$mojri_res=mysql_query($query_mojri) or die("error");
  	if(mysql_num_rows($mojri_res)>0)
  	{
  		$mojri_row_fetch=mysql_fetch_array($mojri_res);
  		$name_family=$mojri_row_fetch["name"]."&nbsp;".$mojri_row_fetch["family"];
  	}
  }

?>

   <tr>
              <td colspan="2" align="left">
                <p align="center" class="tahoma1" dir="rtl">متن ارسالي حداکثر 200 کاراکتر است</td>
            </tr>
           <tr>
              <td colspan="2" align="left">
                <p align="center" class="tahoma1" dir="rtl" >استفاده كننده محترم از سرويس پيامك
در خصوص استفاده از اين سرويس به نكات ذيل توجه فرماييد:
1- اين امكان براي استفاده در برنامه پژوهشيار و صرفا در جهت پيگيري و اطلاع رساني طرحهاي تحقيقاتي تعبيه شده است.
2-با توجه به تعهد دانشگاه به استفاده از سرويس مربوطه در راستاي تفاهم نامه فيمابين دانشگاه و مخابرات، استفاده از اين سرويس در خارج از اهداف برنامه پژوهشيار ممنوع ميباشد و بر اين اساس تمامي پيامهاي رد و بدل شده روزانه چك ميشود
چنانچه در استفاده از اين سرويس  به مشكلي بر خورد كرديد مراتب را به (مديريت امور پژوهش )آقاي رماوندي و شماره تلفن 81633623 اطلاع دهيد.

				</td>
            </tr>
        <?
        if(mysql_num_rows($mojri_res)>0)
  	{
  		?>
  		<tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" dir="rtl" readonly name="telno" value='<? echo $name_family; ?>' size="48" class="edit-user" ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1">نام و نام خانوادگي</td>
            </tr>
  		 
  		<?
  	}
        
        ?>    

  <tr>
              <td width="66%" align="right">
                <p align="right"><input type="text" name="telno" value='<? echo $telno; ?>' size="48" class="edit-user" ></td>
              <td width="24%" align="left">
                <p align="left" class="tahoma1"><span class="star-message">*</span>شماره همراه</td>
            </tr>
            
 <tr>
    <td  width="66%" align="right">
	<textarea class="edit-user"  name="letter_body" wrap="physical" cols="38" rows="5"
onKeyDown="textCounter(document.sms.letter_body,document.sms.remLen1,130);return FarsiKeyDown()"
onKeyUp="textCounter(document.sms.letter_body,document.sms.remLen1,130)"  dir=RTL  ></textarea>

<!--	<textarea class="edit-user"  name="letter_body" wrap="physical" cols="38" rows="5"
onKeyDown="textCounter(document.sms.letter_body,document.sms.remLen1,130)"
onKeyUp="textCounter(document.sms.letter_body,document.sms.remLen1,130)" ></textarea>
-->
	
 </td>
    <td width="24%" class="tahoma1" valign="top">متن پيام</td>
  </tr>
   <tr>
         <td width="100%" colspan="2"  >

          <input readonly type="text" name="remLen1" size="3" maxlength="3" value="130">
          characters left
  </tr>
            <tr>
              <td width="100%" colspan="2" >

                <p align="center"><input class="but-tarh-type" type="submit" value="ارسال" name="submit_tarh"></td>
            </tr>
          </table>
          
</form>
 <?

   footer_forms($admin,$seed);
?>



