<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
//require_once('lib/nusoap.php');
include ("../sms/include/WebServiceSms.php");
include ("../sms/send_long_sms.php");
//$karshenasi_koll_1=mablagh_karshenasi($cod_tarh);

echo "<br>";

echo "<form name=\"sabt_tarh\" method=\"post\"  action=\"$PHP_SELF?action=submit_payment&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">";
     if(isset($action) && strcmp($action,"submit_payment")==0 && isset($tayeed_marhale))
     {
       $now_date=date("Y-m-d");
       $q="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='$tayeed_marhale'";
       //echo $q;
       $res=mysql_query($q) or die("Error 00");
       if(mysql_num_rows($res) <=0 )
       {
         $mablagh_marhale="mablagh_marhale_".$tayeed_marhale;       	       	
       	 $mablagh_marhale=$$mablagh_marhale;
       	          
         $maliat_marhale="maliat_marhale_".$tayeed_marhale;
		 $maliat_marhale=$$maliat_marhale;
         
         $mablagh_khales_mojri="mablagh_khales_mojri_".$tayeed_marhale;
		 $mablagh_khales_mojri=$$mablagh_khales_mojri;
         
         $maliat_marhale="maliat_marhale_".$tayeed_marhale;
		 $maliat_marhale=$$maliat_marhale;
		 
		  $karshenasi="hagh_ol_zahme_karshenasi_".$tayeed_marhale;
		 $karshenasi=$$karshenasi;
		 
		// echo $maliat_marhale;
		 $query="insert into tarh_indoing set   submitted='1',comments='$comments',time_month='$time_month',emtiaz='$int_emtiaz',start_time='$start_time',time_marhale='$start_time',cod_tarh='$cod_tarh' , date='$now_date',marhale='$tayeed_marhale',mablagh='$mablagh_marhale',maliat='$maliat_marhale',khales='$mablagh_khales_mojri',karshenasi='$karshenasi'";
	 
         $result=mysql_query($query) or die("Error 2");
       }
       $now_date=date("Y-m-d");
       
       
       
       $query="update gozaresh_gharardad set  submitted_pay='1' where cod_tarh='$cod_tarh' and marhale='$tayeed_marhale'";
     //  echo $query;
       $result=mysql_query($query)  or die("Error 00000");
       
       $query="update tarh_indoing set  date='$now_date',submitted='1' where cod_tarh='$cod_tarh' and marhale='$tayeed_marhale'";
     //  echo $query;
       $result=mysql_query($query)  or die("Error 00000");
       $now_date=date("Y-m-d");
       if(strcmp($tayeed_marhale,'100')==0)
       {
       	 $query="update tarh set finalized ='1' where cod_tarh='$cod_tarh'";
       	 $result=mysql_query($query) or die("Error");
		 insert_position($cod_tarh,"12",$admin);
       }
       	$query="select user_login.* from tarh, user_login where cod_tarh='$cod_tarh' and tarh.creator=user_login.email";
     	$result=mysql_query($query) or die("error ");
     	$row_fetched=mysql_fetch_array($result);
     	$telno=$row_fetched["mobile"];
        $action="تاييد پرداخت مرحله "."<br>.".$tayeed_marhale."<br>.".$cod_tarh;
        set_log($action,$admin,date("Y-m-d, g:i a"));
        if($tayeed_marhale==0)
     	  $tayeed_marhale=1;
     	
		if($tayeed_marhale==100)
     	  $tayeed_marhale='final';
        //$letter_body="marhale ".$tayeed_marhale." az tarh ".$cod_tarh." tayeed shod ";
       // send_sms("$telno",$letter_body,$admin);
        $message_string="پژوهشيار: مرحله $tayeed_marhale از طرح $cod_tarh تاييد شد. research.tums.ac.ir";
		//$message_string=iconv("windows-1256", "UTF-8",$message_string);
		$subject="پاسخ به سوالات قرارداد";
		$massage_id=send_long_sms($message_string,$telno,$subject);
        
    
       
     }
     
 
  $query="select * from answer_mojri_gharardad where cod_tarh='$cod_tarh'";
 
  $result=mysql_query($query) or die("Error10");
  if(mysql_num_rows($result)>0)
 {
 	$row_fetched=mysql_fetch_array($result);
 	$mojri=$row_fetched["mojri_code"];
 	$heiat_elmi=$row_fetched["heiat_elmi"];
 	$start_time=$row_fetched["start_time"];
    $start_time_tmp=$start_time;
 	$pish_pardakht=$row_fetched["pish_pardakht"];
 	$payanname=$row_fetched["payanname"];
 	$nazerin=$row_fetched["nazerin"];
 	$unnazerin=$row_fetched["unnazerin"];
 	$time_month=$row_fetched["time_month"];
    $exists=1; 	
    
 } 	
 else
 {
 	$payanname="0";
 	$mojri="0";
 	$heiat_elmi="0";
 	$start_time="0";
 	$pish_pardakht="0";
 	$nazerin="0";
 	$time_month="0";
 	$unnazerin="0";
    $exists=0;
 }
 
 //$start_time="1385-02-12";
// $time_month="15";
 if( $start_time > 0 && $time_month > 0 )
 {
   $year=substr($start_time,0,4);
   $month=substr($start_time,5,2);
   $day=substr($start_time,8,2);
   $start_time=$day."/".$month."/".$year;
   $month_add=$time_month+$month;
   if($month_add > 12 )
   {
     $year_add=(int)($month_add/12); 
	 $year=$year+$year_add;	 	 	
     $month=$month_add-($year_add*12);     
    
   }
   else
    $month=$month_add;
   
  
   $end_time=$day."/".$month."/".$year;
 }
 else
 {
   $end_time="تعريف نشده";   
 }
   
    
    
    $query1="select * from jalase_shora , jalase_shora_tarh where jalase_shora.creator=jalase_shora_tarh.creator and jalase_shora.shomare_jalase=jalase_shora_tarh.shomare_jalase  and jalase_shora_tarh.cod_tarh='$cod_tarh'";
    $result10=mysql_query($query1) or die("Error11");
    if(mysql_num_rows($result10) >0)
    {
      $rf100=mysql_fetch_array($result10);
	  $tarikh_jalase=$rf100["tarikh_jalase"];	
	  $year=substr($tarikh_jalase,0,4);
      $month=substr($tarikh_jalase,5,2);
      $day=substr($tarikh_jalase,8,2);
      $tarikh_jalase=$day."/".$month."/".$year;
      
    }
    else
      $tarikh_jalase=" نا معلوم ";
 
   
   
   $query1="select * from gozaresh_gharardad where cod_tarh='$cod_tarh'";
   $result500=mysql_query($query1)or die("error12");
   if(mysql_num_rows($result500) > 0)
   {
   	$gozaresh_cnt=mysql_num_rows($result500);
   }
   else
   	$gozaresh_cnt=0;

   
   
   $query1="select distinct user_login.* from user_login,tarh where user_login.email=tarh.creator and tarh.cod_tarh='$cod_tarh'";
	
   $result1=mysql_query($query1) or die("Error14");
   $query="select distinct mojri.* from mojri_tarh , tarh,mojri  where mojri.mojri_code=mojri_tarh.mojri_code and mojri_tarh.cod_tarh = tarh.cod_tarh  and tarh.cod_tarh=\"$cod_tarh\" and mojri_tarh.mojri_or_hamkar='0'  ";
   $result=mysql_query($query) or die("Error in selecting data from mojri_tarh");
    
   if(mysql_num_rows($result) > 0 || mysql_num_rows($result1) > 0)
   {
   	$i=0;
  
	while($row_fetched1=mysql_fetch_array($result1))
    {
      
      $cod_mojri=$row_fetched1["email"];
      if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
   	    $checked="1";
      }
      else
      {
   	    $checked="";
      }
  
     if(strcmp($checked,"1")==0)
     { 
      $name_family=$row_fetched1["name"]." ".$row_fetched1["family"];
     }
 
   }
 
 
 
   while($row_fetched=mysql_fetch_array($result))
   {
  
    $cod_mojri=$row_fetched["mojri_code"];
    
    if($exists==1)
      if(strcmp($cod_mojri,$mojri)==0)
      {
      	
   	    $checked1="1";
      }
     else
      {
   	    $checked1="";
      }
   
 
    if(strcmp($checked1,"1")==0)
    {  
      
      $name_family=$row_fetched["name"]." ".$row_fetched["family"];
  
    }
    
   }
 }
else // if reccount of tarh  < =0
{
 $name_family="توسط مجري تعيين نشده";
}

//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
if(strlen(trim($name_family)) <= 0)
   $name_family="توسط مجري تعيين نشده";


  $query="select * from tarh where cod_tarh='$cod_tarh' and version=\"-1\" ";
  $result=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];
  $eatebare_sazmanha=$row_fetched["eatebare_sazmanha"];
  $tarh_type= $row_fetched["tarh_type"];
  $cod_daneshkade=$row_fetched["cod_daneshkade"];
  $nezarat=$row_fetched["nezarat"];  // sabet nezarat
   $entezar=$row_fetched["entezar"];  // entezar be ezaye har mah
  $gozaresh_ezafi  =$row_fetched["gozaresh_ezafi"];  // be ezaye har gozaresh ezafi be joz gozaresh payani
  
  
   $cod_daneshkade = $row_fetched["cod_daneshkade"];
  $query="select * from daneshkade where cod_daneshkade='$cod_daneshkade' ";
  
  $result_daneshkade=mysql_query($query) or die("Error in selecting data from karshenas elmi ");
  $row_fetched_daneshkade=mysql_fetch_array($result_daneshkade);
  $daneshkade_name=$row_fetched_daneshkade["daneshkade_name"];
  $daneshkade_tel =$row_fetched_daneshkade["daneshkade_tel"];
  $daneshkade_fax =$row_fetched_daneshkade["daneshkade_fax"];
  $signer_address  =$row_fetched_daneshkade["signer_address"];
    $static_second_part  =$row_fetched_daneshkade["static_second_part"];
  $signer_name=$row_fetched_daneshkade["signer_name"];
  
$tarh_name=str_replace("&#61537;",".",$tarh_name); 
$tarh_name=str_replace("&#61543;",".",$tarh_name); 
$tarh_name=str_replace("&#61541;",".",$tarh_name);  
$tarh_name=str_replace("&#1740;","ي",$tarh_name); 
$tarh_name=str_replace("&#1740","ي",$tarh_name);
  
  $q="select * from tarhtype where tarh_type='$tarh_type'";
  $q_res=mysql_query($q) or die("Error");
  $rf=mysql_fetch_array($q_res) or die("Error");
  $tarh_type_desc=trim($rf["tarh_type_english_desc"]);
   $tarh_type_desc="";
  if(strcmp($tarh_type_desc,"HSR")==0)
    $tarh_type_desc="(اچ اس آر)";
  else
  {
  	$q="select * from tarh,tarhtype_2 where tarh.tarh_type_2=tarhtype_2.tarh_type and cod_tarh='$cod_tarh' and grant_tarh='1'";
  	$q_res=mysql_query($q) or die("Error");
  	if(mysql_num_rows($q_res) > 0)
  	{
  	  $rf_grant=mysql_fetch_array($q_res);
	  $tarh_type_desc=$rf_grant["tarh_type_desc"];		
	}  
  }
    
  $q_payan_name="select * from tarh,darajeelmi  where  payan_name='1' and  cod_tarh='$cod_tarh' and darajeelmi.darajeelmi = tarh.payan_name_daraje_elmi";
  $q_res=mysql_query($q_payan_name) or die("Error");
  if(mysql_num_rows($q_res) > 0 )
  {
  	$rf_payanname=mysql_fetch_array($q_res);
  	$maghtaa_payan_name=$rf_payanname["darajeelmi_english_desc"];
  	$tarh_type_desc=$tarh_type_desc."($maghtaa_payan_name مقطع پايان نامه :)";
  }
    
  if(strcmp($eatebare_sazmanha,'1')==0)
   $eatebar_sazmanha="با تامين اعتبار از سازمانهاي ديگر";
  else
   $eatebar_sazmanha=""; 
  
   
  //-------------------- قسمت مربوط به عقد قرارداد
  
  $mablagh_aghd_gharardad = $row_fetched["mablagh_aghd_gharardad"];
  
  if($mablagh_aghd_gharardad  > 0)
  {
  	$a=($gozaresh_cnt-1)*$gozaresh_ezafi  ;
	//$a=0;
  	$b=$nezarat;
  	// محاسبه گزارش دوم تا ماه نهايي ضربدر 5000 ريال
  	$qr="select * from gozaresh_gharardad where cod_tarh='$cod_tarh' and marhale='2'";
	$resultr=mysql_query($qr) or die("error15");
	$rft=mysql_fetch_array($resultr);	
	$second_gozaresh=$rft["date_gozaresh"]; 
	 
	$year=substr($second_gozaresh,0,4);
    $month=substr($second_gozaresh,5,2);
    $day=substr($second_gozaresh,8,2);
  //  echo $year.":".$month.":".$day;
    $month_remain=0;
  //  echo $end_time."<br>";
    for($k=1;$k<=$time_month;$k++)
    {      	
      $month=$month+1;
      if($month>12)
      {
        $month=1;
        $year=$year+1;
      }
      //$month1=str_replace($month,"0","");
     // $month1=trim($month1);
     
      $my_end_time=substr($end_time,3,7);
	  //$date_tmp=$day."/".$month."/".$year;
       $date_tmp=$month."/".$year; 
      if(strcmp($my_end_time,$date_tmp)==0)
      {
        $month_remain=$k;  // mohasebe teadad mahe dovvom ta gozaresh akhar
        
      }
     // echo $date_tmp.":".$my_end_time."<br>";  
     }
    // echo $month_remain.":".$date_tmp.":".$my_end_time.":".$second_gozaresh.":".$month_remain.":".$time_month.":".$month.":".$year.":".$end_time.":".$date_tmp.":".$my_end_time.":". $date_tmp.":".$end_time;
   //  exit();
  // exit();
     $c=$month_remain*$entezar;  // this is for old version
	 $c=$time_month*$entezar;
     $c1=$c;
	 //echo $a."<br>".$b."<br>".$c."<br>".$month_remain;
	 //exit();
	 $nezarat_koll=$a+$b+$c; // نظارت بخش اول کار
	

/*	echo "month remaining : ".$month_remain."<br>";
     echo "gozaresh cnt :".$gozaresh_cnt."<br>";
	  echo "gozaresh ezafi :".$gozaresh_ezafi."<br>";
	 echo "(gozaresh_cnt-1)*gozaresh_ezafi: ".$a."<br>";
	 echo "nezarat sabet :".$b."<br>";
	  echo "entezar :".$entezar."<br>";
	 echo "month remaining * entezar sabet :".$c."<br>";
	 echo "nezarat_koll :".$nezarat_koll."<br>";
 
	 exit();
	*/  
	  
	  // محاسبه هزينه پرسنلي و محاسبه ماليات آن
 	  $query="select * from  hazine_personnel where cod_tarh=\"$cod_tarh\"  and version='-1' order by activity_type ";
      $result00=mysql_query($query) or die("Error in selecting data from hazine personnel");
      if(mysql_num_rows($result00) > 0)
      {
     
        $mycount=0;
       while($row_fetched00=mysql_fetch_array($result00))
       {
  
       $my_summary = $row_fetched00["per_hour"]*$row_fetched00["majmoa_saat"];
       $mycount=$mycount+$my_summary;
       }       
      }
      $hazine_personnel=$mycount;
      
      $darsad_50=$mablagh_aghd_gharardad*50/100;
      
	  
	  $mablagh_koll=($mablagh_aghd_gharardad+$nezarat_koll)*100/95;
	  	//$mablagh_koll=$mablagh_aghd_gharardad+$nezarat_koll+$maliat_koll;
		
	 
      /*
      if($hazine_personnel > $darsad_50)
	  {	    	
	   //$x=($mablagh_aghd_gharardad*5)/100; 	
	   $y=($nezarat_koll*100)/95;
	   //$maliat_koll=$x+$y;
	   $aa=($mablagh_aghd_gharardad-$hazine_personnel)*100/95;
	   $mablagh_koll=$hazine_personnel+$y+$aa;
	   $nezarat_maliat=$nezarat_koll*100/95;
	  }
	  else
	   {
	   //	$mablagh_aghd_gharardad=($mablagh_aghd_gharardad*100)/95;
	   	//$maliat_koll=($mablagh_aghd_gharardad+$nezarat_koll)*100/95;
	   	$mablagh_koll=$mablagh_aghd_gharardad+$nezarat_koll;
	   	$mablagh_koll=$mablagh_koll*100/95;
	   	$nezarat_maliat=$nezarat_koll*100/95;
	   }
	  */
	  
	  /*
      $x=($hazine_personnel*5)/100;
     	  
      $y=($nezarat_koll*5)/100;
      $maliat_koll=$x+$y;
	  */
   

  	 //-------------------marhale 1 ------------------------------------------
 
	  
	 $query="select * from gozaresh_gharardad where marhale='0' and cod_tarh='$cod_tarh'";
      $result88=mysql_query($query) or die("Error");
      if(mysql_num_rows($result88) > 0)
	  {
	  	$rf66=mysql_fetch_array($result88);
	  ////  if($hazine_personnel > $darsad_50)
	  ////  {
	      $mablagh_marhale_0=$rf66["mablagh"]*$mablagh_koll/100;
	      $maliat_marhale_0=$mablagh_marhale_0*5/100;
	       $hagh_ol_zahme_karshenasi_0= $nezarat_koll*$rf66["mablagh"]/100;
		  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0;
		   $mablagh_khales_mojri_0= $mablagh_khales_mojri_0-$hagh_ol_zahme_karshenasi_0;
	      
	  		
	  ////  }
	 ////   else
	 ////   {
	 ////     $darsad_marhale=$rf66["mablagh"]*$mablagh_aghd_gharardad/100;	
	 ////     $mablagh_marhale_0=($darsad_marhale+($darsad_marhale/100))*100/95;
	 ////     $maliat_marhale_0=$mablagh_marhale_0*5/100;
	 //// 	  $hagh_ol_zahme_karshenasi_0= $nezarat_koll*$rf66["mablagh"]/100;
	////	  $mablagh_khales_mojri_0=$mablagh_marhale_0-$maliat_marhale_0-$hagh_ol_zahme_karshenasi_0;	      	      
	  		      
	  ////  }
	    
	    
	    
	     echo "<input type='hidden' name='darsad_marhale_0' value='$darsad_marhale'>";
        echo "<input type='hidden' name='hagh_ol_zahme_karshenasi_0' value='$hagh_ol_zahme_karshenasi_0'>";
        echo "<input type='hidden' name='mablagh_marhale_0' value='$mablagh_marhale_0'>";
        echo "<input type='hidden' name='maliat_marhale_0' value='$maliat_marhale_0'>";
         echo "<input type='hidden' name='mablagh_khales_mojri_0' value='$mablagh_khales_mojri_0'>";
       
	  	
	  }
	//  echo "mohsen <br>".$end_time."<br>".$month_remain."<br>".$mablagh_marhale_0."<br>".$mablagh_aghd_gharardad."<br>".$maliat_1."<br>".$hazine_personnel;
	  //exit();
	   //$mablagh_koll_tarh=$maliat_koll+$nezarat_koll+$mablagh_aghd_gharardad;
	  
	  //-------------------marhale Nahayee ------------------------------------------
	  
	  $a=$static_second_part;
	  $query="select * from gozaresh_gharardad where marhale='100' and cod_tarh='$cod_tarh'";
      $result=mysql_query($query) or die("Error");
      $b=0;
	  if(mysql_num_rows($result) > 0)
	  {
	  	$rf66=mysql_fetch_array($result);
	 ////  if($hazine_personnel > $darsad_50)
     ////  {
  	      $mablagh_marhale_end=$rf66["mablagh"]*$mablagh_koll/100;
  	      
  	   ///   $nezarat=125000+$mablagh_marhale_end/100;
       
	      $maliat_marhale_end=$mablagh_marhale_end*5/100;
		 
	       $mablagh_khales_mojri_end=$mablagh_marhale_end-$maliat_marhale_end;
	      //$mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
		///  $mablagh_khales_mojri_end=$mablagh_khales_mojri_end-$hagh_ol_zahme_karshenasi_end;
		
		
		 $mablagh_khales_mojri_end=$mablagh_aghd_gharardad*$rf66["mablagh"]/100;
  	     
	  	   $hagh_ol_zahme_karshenasi_end= $nezarat_koll*$rf66["mablagh"]/100; 	
	  		
        echo "<input type='hidden' name='darsad_marhale_100' value='$darsad_marhale'>";
        echo "<input type='hidden' name='hagh_ol_zahme_karshenasi_100' value='$hagh_ol_zahme_karshenasi_end'>";
        echo "<input type='hidden' name='mablagh_marhale_100' value='$mablagh_marhale_end'>";
        echo "<input type='hidden' name='maliat_marhale_100' value='$maliat_marhale_end'>";
         echo "<input type='hidden' name='mablagh_khales_mojri_100' value='$mablagh_khales_mojri_end'>";
        
	 $date=$rf66["date_gozaresh"];
 $year=substr($date,0,4);
 $month=substr($date,5,2);
 $day=substr($date,8,2);
 $date_end=$day."/".$month."/".$year; 
	    //$myq="insert into tarh_indoing set cod_tarh='$cod_tarh',marhale='100',";
	  } 
	   
	 
  }
  
  
 
//$mablagh=$nezarat_koll+$maliat_koll+$mablagh_aghd_gharardad;

   
  $emtiaz1=($mablagh_koll/10000000)*2.5;
  $int_emtiaz=(int)$emtiaz1;
  $real_emtiaz=$emtiaz1-$int_emtiaz;
  if($real_emtiaz > .75)
    $int_emtiaz++;  

    
 
  if(strlen(trim($daneshkade_name)) <=0)
    $daneshkade_name="تعريف نشده";
  
if($start_time==0)
  $start_time="تعريف نشده";
    
//if($end_time==0)
 // $end_time="تعريف نشده";
  
if($time_month==0)
  $time_month="تعريف نشده"; 

$mablagh_koll_tarh=number_format($mablagh_koll_tarh);
 $year_tarh=substr($cod_tarh,0,2);
 $rank=substr($cod_tarh,4,1);
 $query="select * from rank where rank='$rank' and year='$year_tarh'";
  
 $res=mysql_query($query) or die("Rank Error");
 if(mysql_num_rows($res) > 0)
 {
 	$rf_rank=mysql_fetch_array($res);
 	$jalase_date=$rf_rank["jalase_date"];
 }
 else
   $jalase_date="تعريف نشده";
    
 $tarikh_jalase="6/4/1385";
 $tarikh_jalase=$jalase_date;
$y=substr($tarikh_jalase,0,4);
$m=substr($tarikh_jalase,5,2);
$d=substr($tarikh_jalase,8,2); 
$tarikh_jalase="$d / $m / $y";
 /*
if(strcmp($tarh_type_desc,'HSR')==0) 
$tarh_type_desc="(HSR)"; 
else 
$tarh_type_desc="";

*/
$mablagh_koll_tarh=number_format($mablagh_koll_tarh);
?>

<TABLE cellSpacing=0  width="90%" cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

  <TR>

      <TD align=center  class="tahoma1" dir="rtl"  height=19 bgcolor="#EEE7F8" dir="rtl">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
  </TR>

</table>
<br>

<?

     echo "<table border=\"0\" width=\"90%\"  cellspacing=\"1\" cellpadding=\"1\" >";
     $color="PALETURQUOISE";
     $row_fetched=mysql_fetch_array($result);
     echo "<tr>";
       echo "<td align=\"center\" colspan='7'  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>کليه مبالغ به ريال است</b></td>";
     echo "</tr>";
     
     echo "<tr>";
      echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>تاييد شده</b></td>";  
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>تاييد پرداخت</b></td>";     
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>حق الزحمه کارشناسي</b></td>";     
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مبلغ خالص مرحله</b></td>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>ماليات</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مبلغ مرحله</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>مرحله</b></td>";   
     echo "</tr>";
     //echo $query;
     $submitted_ok="-----";
     //echo $row_fetched["submitted"];
     $q_marhale_0="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='0'";
     $q_marhale_result=mysql_query($q_marhale_0) or die("Error");
     if(mysql_num_rows($q_marhale_result)>0)
     {
     	$q_marhale_fetch=mysql_fetch_array($q_marhale_result);
     	$submitted_in=$q_marhale_fetch["submitted"];
     	
     	if(strcmp($submitted_in,'1')==0)
          $submitted_ok="تاييد شده";
        else 
          $submitted_ok="-----";
     }
    
     echo "<tr>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$submitted_ok</b></td>"; 
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b><input type='radio'  value='0' name='tayeed_marhale'></b></td>";     
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($hagh_ol_zahme_karshenasi_0)."</b></td>";     
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_khales_mojri_0)."</b></td>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($maliat_marhale_0)."</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_marhale_0)."</b></td>";
     echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>1</b></td>";
     echo "</tr>";
   
     
     
     
     
     
     
     
     
     
     
     
    
$query="select * from gozaresh_gharardad  where cod_tarh='$cod_tarh' and marhale!='0' and marhale!='100' order by marhale asc ";
$result1=mysql_query($query) or die("Error");
$cntr=1;
$mablagh12=0;
while($rf66=mysql_fetch_array($result1))
{
// echo $cntr;
   
  	$mablagh_marhale_n=$rf66["mablagh"]*$mablagh_koll/100;
  	//$nezarat=$rf66["mablagh"]*$nezarat_koll/100;
  	//$mablagh_marhale_n=($mablagh_marhale_n+$nezarat)*100/95;
  	
	$maliat_marhale_n=$mablagh_marhale_n*5/100;
	
	 $hagh_ol_zahme_karshenasi_n= $nezarat_koll*$rf66["mablagh"]/100; 	 
	 $nezarat=$hagh_ol_zahme_karshenasi_n;
/////	$mablagh_khales_mojri=$mablagh_marhale_n-$maliat_marhale_n;
//	$mablagh_khales_mojri=$mablagh_khales_mojri-$hagh_ol_zahme_karshenasi_n;
	 $mablagh_khales_mojri=$mablagh_aghd_gharardad*$rf66["mablagh"]/100;
  	   
	  		
  
       echo "<input type='hidden' name='darsad_marhale_".$marhale."' value='$darsad_marhale'>";
        echo "<input type='hidden' name='hagh_ol_zahme_karshenasi_".$marhale."' value='$hagh_ol_zahme_karshenasi_n'>";
        echo "<input type='hidden' name='mablagh_marhale_".$marhale."' value='$mablagh_marhale_n'>";
        echo "<input type='hidden' name='maliat_marhale_".$marhale."' value='$maliat_marhale_n'>";
         echo "<input type='hidden' name='mablagh_khales_mojri_".$marhale."' value='$mablagh_khales_mojri'>";
    
  
  
  
  
 $cntr++;
 $date=$rf66["date_gozaresh"];
 $year=substr($date,0,4);
 $month=substr($date,5,2);
 $day=substr($date,8,2);
 $date=$day."/".$month."/".$year;

 $percent_gozaresh=$rf66["percent_gozaresh"];
 
 $this_time=$rf66["date_gozaresh"];
 //	$start_time_tmp=$start_time; 
	$this_time=substr($this_time,0,7);
	
//	echo $this_time;
   // echo $start_time_tmp;
	$year=substr($start_time_tmp,0,4);
//	echo $year;
    $month=substr($start_time_tmp,5,2);
    $day=substr($start_time_tmp,8,2);
    
    for($k=1;$k<=$time_month;$k++)
    {      	
      $month=$month+1;
      if($month>12)
      {
        $month=1;
        $year=$year+1;
      }
	  $date_tmp=$year."-".str_pad($month,2,0,STR_PAD_LEFT);
	 // $date_tmp=substr($date_tmp,0,5);
       //echo  $year."&".$month."      ";
      //echo $date_tmp."   ".$this_time;  
      if(strcmp($this_time,$date_tmp)==0)
      {
        $marhale_jadval_zamani=$k;  // mohasebe teadad mahe dovvom ta gozaresh akhar
        
      }
        
     }
     
     
     
    if($marhale_jadval_zamani==1)
       $marhale_jadval_zamani=" اول ";
    
	if($marhale_jadval_zamani==2)
       $marhale_jadval_zamani=" دوم ";
    
    if($marhale_jadval_zamani==3)
       $marhale_jadval_zamani=" سوم ";

    if($marhale_jadval_zamani==4)
       $marhale_jadval_zamani=" چهارم ";
	
	if($marhale_jadval_zamani==5)
       $marhale_jadval_zamani=" پنجم ";
	
	 if($marhale_jadval_zamani==6)
       $marhale_jadval_zamani=" ششم ";   
	   
	   
     $q_marhale_0="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='$cntr'";
     $q_marhale_result=mysql_query($q_marhale_0) or die("Error");
     $submitted_ok="-----";
	 if(mysql_num_rows($q_marhale_result)>0)
     {
     	$q_marhale_fetch=mysql_fetch_array($q_marhale_result);
     	$submitted_in=$q_marhale_fetch["submitted"];
     	
     	if(strcmp($submitted_in,'1')==0)
          $submitted_ok="تاييد شده";
        else 
          $submitted_ok="-----";
     }
     echo "<tr>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$submitted_ok</b></td>"; 
 
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b><input type='radio'  value='$cntr' name='tayeed_marhale'></b></td>";     
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($hagh_ol_zahme_karshenasi_n)."</b></td>";
     
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_khales_mojri)."</b></td>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($maliat_marhale_n)."</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_marhale_n)."</b></td>";
      echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$cntr</b></td>";
     echo "</tr>";
} 
$cntr++;
 
      $q_marhale_0="select * from tarh_indoing where cod_tarh='$cod_tarh' and marhale='100'";
      //echo $q_marhale_0;
     $q_marhale_result=mysql_query($q_marhale_0) or die("Error");
     $submitted_ok="-----";
	 if(mysql_num_rows($q_marhale_result)>0)
     {
     	$q_marhale_fetch=mysql_fetch_array($q_marhale_result);
     	$submitted_in=$q_marhale_fetch["submitted"];
     	
     	if(strcmp($submitted_in,'1')==0)
          $submitted_ok="تاييد شده";
        else 
          $submitted_ok="-----";
     }
     echo "<tr>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$submitted_ok</b></td>"; 
 
       echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b><input type='radio'  value='100' name='tayeed_marhale'></b></td>";     
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($hagh_ol_zahme_karshenasi_end)."</b></td>";
     
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_khales_mojri_end)."</b></td>";
     echo "<td align=\"center\"  width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($maliat_marhale_end)."</b></td>";
     echo "<td align=\"center\"   width=\"20%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>".number_format($mablagh_marhale_end)."</b></td>";
      echo "<td align=\"center\"   width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>$cntr</b></td>";
     echo "</tr>";
     
       echo "<tr>";
       echo "<td align=\"center\"  colspan='7' width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><b>در صورت تاييد ، طرح به طرحهاي در حال اجرا مي رود</b></td>";
     echo "</tr>";
     
        echo "<tr>";
       echo "<td align=\"center\" colspan='7'  width=\"5%\" bgcolor=$color align=\"left\" class=\"tahoma1\" valign=\"top\"><input type=\"submit\" value=\"تاييد\" name=\"B1\" class=\"but-small\"></td>";
     echo "</tr>";
     
      
     
    
     
     
     
     echo "</table>";
  
  echo "</form>"; 
   
footer_forms($admin,$seed);
?>

