<?
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
include("include/styles.phtml");
$query="select * from tarh where cod_tarh='$cod_tarh' ";
   $result=mysql_query($query) or die("Error in selecting data from karshenas elmi");
    $row_fetched=mysql_fetch_array($result);
  $tarh_name = $row_fetched["tarh_title_farsi"];

   echo "<br>";
?>
  <TABLE cellSpacing=0 width="60%"  cellPadding=2 border=0 bordercolor="#333333" style="border-style: solid; border-width: 1; ">

    <TR>

      <TD align=center class="tahoma1"  height=19 bgcolor="#EEE7F8">
      <?
	   echo ""."عنوان طرح  : ".$tarh_name ;
      ?>
      </TD>
    </TR>

  </table>

<?
echo "<br>";



     $mycount=0;
     $dir_name="../attachments/".$cod_tarh;
     if ($dir = @opendir($dir_name))
     {
      echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\"  width=\"60%\" >";
      echo "<tr>";
      echo "<td width=\"20%\"  align=\"center\"  class=\"tahoma1\">نام فايل</td>";
      echo "</tr>";

     //echo $dir_name;
     $mydir = dir($dir_name);
     //while(($file = $mydir->read()) !== false)
     while($file = $mydir->read())
     {
	   if( !(strcmp(trim($file),".")==0 || strcmp(trim($file),"..")==0  || strcmp(trim($file),"Thumbs.db")==0) )
	   {
         echo "<tr>";
               echo "<td align=\"center\"  class=\"tahoma1\"><a target=\"_blank\" href=\"../attachments/$cod_tarh/$file\">".$file."</a></td>";
         echo "</tr>";
	   }
     }
      closedir($dir);
      echo "</table>";
	 }




footer_forms($admin,$seed);
?>

