<?
include("include/styles.phtml");
include("include/database-connect.phtml");
include("include/include.phtml");
header_forms($admin,$seed);
echo "<br>";

if(isset($action))
{
  if (strcmp($action,"sabt")==0)
  {
	 $query="select * from tarh where cod_tarh_user=\"$cod_tarh_user\"";
	 $result1=mysql_query($query) or die("Error in selecting data from tarh");
	 if(! intval($cod_tarh_user <= 0))
	 {
	   if(mysql_num_rows($result1) <= 0)
	   {
         $query  = "update tarh set cod_tarh_user =\"$cod_tarh_user\" where cod_tarh=\"$cod_tarh\"";
         $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");
	   }
	   else
        	$status="duplicate_entry";
	 }
	 else
	    $status="entry_error";
  }
}

?>

<? echo "<form name=\"mojri_tarh\" method=\"post\" action=\"$PHP_SELF?action=sabt&admin=$admin&seed=$seed&cod_tarh=$cod_tarh\">"; ?>

<table border="0"  width="400" cellspacing="0" cellpadding="0" >
<tr>
<td width="100%">
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
 <TBODY>
  <TR>
  <TD vAlign=bottom align=left>
  <TABLE cellSpacing=0 cellPadding=0 border=0>
  <TBODY>
    <TR>
    <TD align=middle width="149"   height=19>
      </TD>
      <TD align=middle width="251"  background="image/sabt_cod_tarh.jpg" height=19>
      </TD>
  </TR>
  </TBODY>
  </TABLE>
  </TD>
  </TR>
 </TBODY>
</TABLE>
</TABLE>

<table border="0" width="400" bgcolor="#EEE7F8"   cellspacing="0" cellpadding="2"  bordercolor="#333333" style="border-style: solid; border-width: 1; ">
<?
 if (strcmp($status,"duplicate_entry")==0 )
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">طرحي با اين کد وجود دارد</td>";
    echo "</tr>";
  }

  $query  = "select * from tarh  where  cod_tarh=\"$cod_tarh\" ";
  $result = mysql_query($query) or die("Error in inserting data into hamkaran_tarh 002");

  $row_fetched = mysql_fetch_array($result);
  
  $cod_tarh_user = $row_fetched["cod_tarh_user"];

  if (strcmp($status,"entry_error")==0)
  {
    echo "<tr>";
    echo "<td align=\"center\" class=\"error-message\" width=\"25%\" class=\"tahoma1\" colspan=\"2\">کد طرح بايد بزرگتر از صفر باشد</td>";
    echo "</tr>";
  }
 
?>

<tr>
    <td width="100" align="right"><textarea   rows="3"  name="cod_tarh_user" class="edit-user"  dir=RTL   ><? echo $cod_tarh_user  ; ?></textarea></td>
    <td width="300" class="tahoma1"  valign="top">کد طرح</td>
  </tr>
  
  <tr>
    <td width="100%" colspan="2">
      <p align="center"><input type="submit" value="ثبت" name="B1" class="but-small"></td>
  </tr>

</table>

</form>

<?
  footer_forms($admin,$seed);
 ?>




